### ISSUE TITLE
Mouseover links

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#10]
I really like the buttons, but would it be possible to have the target displayed a mouseover?

**Comment by cmungall** [comment]
Which buttons specifically?

**Comment by mcourtot** [comment]
I meant the buttons on the general page, e.g. towards the project "home",
the "tracker" or the "mailing-list" ones. I'll check whether it's feasible:
I should look in the Jekyll doc I suspect? Trying to be a bit more useful
than just complaining and hoping I can do the edits myself ;)

**Comment by cmungall** [comment]
Bootstrap docs would be the best place to start for anything like 
mouseovers, no jekyll required. The file to edit would be 
ontology_detail.html (it uses liquid templates but you don't need to 
know the details)

If you want to make changes locally and test how they look you'll need 
to install jekyll, which if you have Ruby is I think as simple as

     gem install jekyll
	jekyll serve

**Comment by cmungall** [comment]
I'm going to have to revert this, I think you committed the _site files

**Comment by cmungall** [comment]
I reverted but doesn't seem to show up on this page - I will bring yr changes to ontology_table back in

**Comment by cmungall** [comment]
We have mouseover on buttons, thanks @mcourtot, looks great!

**Comment by mcourtot** [comment]
Did you figure out what went wrong? Still trying to find my way around, so
feedback very welcome.
