### ISSUE TITLE
Dump a CURIE map as part of pipeline

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#100]
Many applications (e.g. robot) consume a curie map for convenience, e.g. to allow end-users to use short-forms like GO:0000001

The pipeline could easily dump these, `uc(ontology.id) : $OBO/uc(ontology.id)_`. Exceptions for grandfathered mixed case ID spaces (e.g. FBbt).

A yaml form and JSON-LD context file would be ideal

**Comment by nlharris** [comment]
is this still something that's wanted?

**Comment by nlharris** [comment]
or maybe this was already done?

**Comment by jamesaoverton** [comment]
Yes, this was done a long time ago. Whenever the registry files are regenerated, we rebuild this JSON-LD context file: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/context.jsonld
