### ISSUE TITLE
Principle #8 documentation - automated validation

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1009]
FP 8 - Documentation

Automated checks:
1. Is there a homepage for user documentation?
2. Is there a description?
3. Is there documentation in the ontology header?

Mechanism:

We can pull the `homepage` tag from the ontology YAML. This should be a valid URL that resolves (does not return HTTP status > 400). We can't guarantee that this is a documentation page, though.

There should also be a `description` tag in the ontology YAML. This is already checked in the metadata validation and if it is missing, the ontology gets a warning.

We can also check the ontology header for some annotations. I propose that we provide standard annotation properties to use for these that we can list on the FP page under implementation:
* creator (`dc:creator` or `oboInOwl:created_by`?)
* maintainer (`dc:contributor` or `oboInOwl:saved-by`?)
* description (`dc:description` or maybe `rdfs:comment`, but that can be used for a lot of things)

We want version and license info as well, but that is checked in FP 4 and FP 1, respectively.

**Comment by safisher** [comment]
I wonder if there's an issue with URL redirections or timeouts. ORNASEQ is flagged as "does not resolve" but the URL is valid, although it redirects to https.

FP8 Documented: {comment: 'homepage URL (http://kim.bio.upenn.edu/software/ornaseq.shtml)
      does not resolve', status: ERROR}

The dashboard is a great idea and will surely help lots of us!

**Comment by jamesaoverton** [comment]
Thanks @safisher. I think you're right that we need to follow 3xx redirects.

**Comment by nlharris** [comment]
I think the dashboard now does this? @matentzn?

**Comment by matentzn** [comment]
At least for @safisher s case it works, yes! I think this can be closed. Follow up tickets should go straight to the [OBO Dashboard tracker](https://github.com/OBOFoundry/OBO-Dashboard/issues).
