### ISSUE TITLE
Namespace issues in cl-basic.obo

### ISSUE THREAD

**Issue by ukemi** [OBOFoundry/OBOFoundry.github.io#101]
We have recently noticed that the namespaces for terms in the ontology are inconsistent. Some terms have the namespace 'cell' (CL:0001033), some have 'cl' (CL:0001040) and some terms are lacking a namespace entirely (CL:0001033). Shouldn't they all have a consistent namespace?

**Comment by cmungall** [comment]
Note to others: David is talking about the obo-namespace field, not the ID space. This is what the obo format doc has to say: http://owlcollab.github.io/oboformat/doc/obo-syntax.html#4.3

So CL isn't explicitly in violation of anything here. However, I know this kind of arbitrariness confuses many obo format consuming pipelines, so I'll file something on the CL tracker
