### ISSUE TITLE
OGSF and OGI have invalid trackers

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1021]
OGSF (active) and OGI (orphaned) both have issue trackers via Google Code. These links direct to a page with the following error:
```
There was an error getting resource 'issues':

401: Anonymous caller does not have storage.objects.get access to google-code-archive/v2/code.google.com/ogsf/issues-page-1.json.
```

We might not be able to resolve the OGI tracker. I see a contact (Asiyah Yu Lin) for OGSF. Do we know if they have a GitHub?

**Comment by cmungall** [comment]
Looks like this escaped the sweep in #76

**Comment by nlharris** [comment]
@linikujp (the contact for OGSF): has this been addressed?

**Comment by linikujp** [comment]
OGSF is here: https://github.com/linikujp/OGSF
I don't have OGI in the github yet. Will set it up soon.
Please let me know what to do next.

**Comment by nlharris** [comment]
are there still action items here?

**Comment by matentzn** [comment]
@cthoyt your recent sweeps must have caught this right: all non obsolete ontologies now have valid issue trackers, and issue trackers are mandatory?

**Comment by cthoyt** [comment]
I just checked there was something there, not that it’s valid. That being said, all but three active ontologies have github repositories so it’s pretty safe to assume the corresponding trackers work

**Comment by matentzn** [comment]
I think this is good enough for me. OGSF works and OGI is not an ontology in the registry. This issue is dealt with! Thanks.
