### ISSUE TITLE
OBO Foundry homepage does not load

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1022]
Clarification - the table does not load. Additionally, no links appear under the Principles tab.

It looks like `_config.yml` was deleted and `principles/all.yml` was changed in the commit f8c05a3, cc @cmungall

**Comment by jamesaoverton** [comment]
We haven't heard from @cmungall. I've asked @beckyjackson to revert the recent changes until we figure this out.

**Comment by cmungall** [comment]
oh crap I'm sorry hold on  I'll fix

**Comment by cmungall** [comment]
I just ran the makefile to regenerate: this should fix it once it percolates: https://github.com/OBOFoundry/OBOFoundry.github.io/commit/3e61d9d941c9938a8feda20d5259568d1097e40c

**Comment by cmungall** [comment]
I believe it is fixed, it has just not percolated yet... firing up jekyll to check

**Comment by cmungall** [comment]
@beckyjackson would you mind checking locally, when I run jekyll it's making the site, but gh pages seems to be taking a reaally long time to refresh...

**Comment by cmungall** [comment]
Thanks!

**Comment by beckyjackson** [comment]
FIxed by 5ae095e
