### ISSUE TITLE
ontology table is missing from homepage

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#1023]
http://obofoundry.org/ - the page is missing the table with the ontologies, the page is loading for me in Chrome and Firefox, but the able is missing

![image](https://user-images.githubusercontent.com/6722114/62903514-c3e56900-bd17-11e9-9482-a0c7582d8679.png)

Maybe related to #1022

**Comment by beckyjackson** [comment]
Sorry, I should have clarified. It's the table that doesn't load, not the whole page. So yes, this is the same as #1022. :)

**Comment by nicolevasilevsky** [comment]
I will close this ticket then :)
