### ISSUE TITLE
Ensure top level links resolve

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#103]
All links from the menu at the top of the page should resolve and or be removed. See #94 (which goes further than what is needed for milestone 1 as it covers also internal links and images)
@mcourtot and @cmungall to look into which are broken and fix/remove. Others to (please) help) by checking.

**Comment by nlharris** [comment]
I will check this. (I am not yet empowered to assign issues in this tracker, though, even to myself.)

**Comment by jamesaoverton** [comment]
@nlharris I added you to the `metadata-editors` team, which will should give you permission to assign issues to yourself and others. Let me know if that doesn't work.

**Comment by nlharris** [comment]
looks to me like at this point all the menu links work.
