### ISSUE TITLE
Is there a guidance for registering an ontology to OBO foundry?

### ISSUE THREAD

**Issue by linikujp** [OBOFoundry/OBOFoundry.github.io#1037]
Sorry for being outdated myself. Is there a step by step guidance for a newbee to register his/her ontology to be part of the OBO foundry ontology? 
Is this page still update : http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html ?

Please advise.

Thanks,
Asiyah

**Comment by nlharris** [comment]
The FAQ points to http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html
That page was updated just two weeks ago, so it seems like the answer to the user's second question is "yes".

**Comment by jamesaoverton** [comment]
Yes, I think that recently updated guide addresses this issue.
