### ISSUE TITLE
Adopt licenses for OBO registry and PURL system

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1046]
The OBO community is committed to open source licenses for our ontologies, but we have not been as clear about the licenses for our shared community resources. Specifically, we have not stated a clear license for the code and data in the OBO registry (this repository) and the OBO PURL system (https://github.com/OBOFoundry/purl.obolibrary.org).

The OBO Operations committee plans to adopt open licenses for existing code and data, and make the new licenses clear to contributors.

1. Code: The code for the registry and PURL system was written by a handful of software developers. We will coordinate with these authors to apply a permissive [BSD3 software license](https://opensource.org/licenses/BSD-3-Clause) to the relevant code.

2. Data: A large number of ontology developers have contributed to the OBO registry (80+) and PURL configuration data (50+). The OBO Operations Committee would like to apply a [CC0 "No Rights Reserved" license](https://creativecommons.org/share-your-work/public-domain/cc0/) to these data. Since these data are already publicly available and widely used, we hope that there will be no objections to clarifying that we intend them to be freely shared. We will announce this plan on the obo-discuss@googlegroups.com mailing list and wait one month for comments before making a final decision.

We will also add/update our README, LICENSE, CONTRIBUTING, and other documentation files to make the licenses clear to our users and contributors.

I'll leave this issue open for a few days for comments. Then I plan to announce this early next week on obo-discuss@googlegroups.com.

**Comment by dr-shorthair** [comment]
Indeed, CC0 is appropriate for data, including ontologies. Attribution is implicit through the URI with a trail back to the repository where credit and responsibility is clear.

**Comment by nlharris** [comment]
has this already been decided and completed?

**Comment by jamesaoverton** [comment]
Fixed by f57d72135302050379ba6ff19d64e66432425eb8 and https://github.com/OBOFoundry/purl.obolibrary.org/commit/0f94288e256b8f317db058f75e57209af1576b4a
