### ISSUE TITLE
Letter of support for Protege

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1054]
The Operations Committee should write a letter of support for the Protege project's upcoming grant application, before (approximately) October 9.

https://mailman.stanford.edu/pipermail/protege-announce/2019-September/000041.html

**Comment by cmungall** [comment]
+1

>

**Comment by rvita** [comment]
FYI: OBI just sent their letter of support.

**Comment by nlharris** [comment]
LoS sent by @ramonawalls on 8 Oct. I think this ticket can be closed. (I don't have power to close tickets in this repo--or, for that matter, to add labels or assignees. Can those powers be granted to me?)

**Comment by jamesaoverton** [comment]
@nlharris You should now have permission to assign and close issues.

I'll close this one.
