### ISSUE TITLE
TOXic Process Ontology (TXPO)

### ISSUE THREAD

**Issue by txpo-ontology** [OBOFoundry/OBOFoundry.github.io#1057]
## Ontology title
Toxic Process Ontology

## Requested ID space
TXPO

## Ontology location
Home page:
https://toxpilot.nibiohn.go.jp
Github:
https://github.com/txpo-ontology/TXPO

## Contact person
Name: Yuki Yamagata
Email address:  y-yamagata@nibiohn.go.jp
GitHub username: txpo-ontology

## Issue tracker
https://github.com/txpo-ontology/TXPO/issues

## Ontology license

- [X ] CC-BY (version 3 or later)

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
TOXic Process Ontology (TXPO) systematizes a wide variety of terms involving toxicity courses and processes.
The first version of TXPO focuses on liver toxicity.

## Related OBO Foundry ontologies
BFO, GO, UBERON, CL (Cell Ontology), ChEBI, PATO, DOID, Relational ontology (RO)

## Intended use/related projects
Knowledge systematization for toxic processes for drug safety evaluation

## Data source
From textbooks ,we researched drug-induced hepatotoxic mechanisms and obtained information about toxic courses and related processes, molecules and their roles, and biological structures. Next, we searched for the latest information from toxic course-related articles using PubMed.

## Additional comments or remarks
Elucidating the mechanism of toxicity is crucial in drug safety evaluations. We focus on toxic processes and developed a toxic process ontology, designated TXPO.
The TXPO contains an is-a hierarchy that is organized into three layers: the top layer contains general terms, mostly derived from the Basic Formal Ontology. The intermediate layer contains biomedical terms in OBO foundry, and the lower layer contains toxicological terms.
More details: https://www.researchgate.net/publication/335060857

////////
Dear OBO-Discuss,
We have developed the TOXic Process Ontology (TXPO), and we requested a prefix and PURL in OBO two month ago via OBO-discuss mailing list.
It's been more than two months, but I haven't received the response yet.
So, I’ll send the request again just in case.

Sincerly, 
Yuki Yamagata, Ph.D.

**Comment by ramonawalls** [comment]
The request for an OBO Foundry PURL was approved today at the Operations Committee meeting. There were some concerns about overlap with other OBO ontologies, although we were encouraged to see the reuse of many terms from OBI, PATO, etc. Please feel free to reach out on the obo-discuss list or to individual ontologies if you need further coordination with existing OBO Foundry ontologies.

To activate the purl, please create a pull with the appropriate YAML files in https://github.com/OBOFoundry/purl.obolibrary.org. If you need any guidance on how to do that, let us know.

**Comment by cmungall** [comment]
I notice you have have many similar terms to GO under the role hierarchy. These are only linked to GO in the comments, not computationally. Is it not possible for you to use GO terms directly and request new terms where required?

**Comment by txpo-ontology** [comment]
> The request for an OBO Foundry PURL was approved today at the Operations Committee meeting. 
Thank you for your approval.
We are pleased.

> To activate the purl, please create a pull with the appropriate YAML files in https://github.com/OBOFoundry/purl.obolibrary.org. If you need any guidance on how to do that, let us know.

We try to make YAML file.
Could I get the guidance?
Thank you.
Yuki

**Comment by txpo-ontology** [comment]
> I notice you have have many similar terms to GO under the role hierarchy. These are only linked to GO in the comments, not computationally. Is it not possible for you to use GO terms directly and request new terms where required?

Thank you for your comment.
Yes, there are some roles in TXPO, which have the comment "related molecular function GO: XXXX.”
Role is a specifically dependent continuant, and GO's molecular function is a process as occurrent. 
Therefore, if the process (molecular function) involved is in the GO term, I write it in the comment.
But, maybe I should move them from the comment to the Database cross-reference.

Use case example of choline transmembrane transporter inTXPO.
In the phospholipidosis (toxic course), 
"increasing glycerophospholipid material (process)” has participant “SLC44A2 (human) (molecule)”.
SLC44A2 (human) has role "choline transmembrane transporter (role)”.

**Comment by txpo-ontology** [comment]
We created the YAML file and have successfully registered OBO Foundry.
Thank you!

Yuki

**Comment by pbuttigieg** [comment]
@txpo-ontology 


On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.

**Comment by txpo-ontology** [comment]
Dear Dr. Pier Luigi But­ti­gieg,

Thank you for contacting us.
Our request was already approved.
TXPO  on OBO-Foundry site:
http://www.obofoundry.org/ontology/txpo.html

So, please close this issue.
Thank you.

Kind regards, 

Yuki Yamagata, Ph.D.
y-yamagata@nibiohn.go.jp
Laboratory of Toxicogenomics Informatics
National Institutes of Biomedical Innovation, Health and Nutrition
7-6-8 Asagi, Saito, Ibaraki, 
567-0085, Osaka, Japan

https://toxpilot.nibiohn.go.jp

**Comment by pbuttigieg** [comment]
@txpo-ontology many thanks for your feedback Yamagata-san, closing now....
