### ISSUE TITLE
Prefix request for PNADO

### ISSUE THREAD

**Issue by obopneumonia** [OBOFoundry/OBOFoundry.github.io#1060]
Dear OBO Foundry technical working group,

Please, consider this kind reminder about my PNADO prefix request. It has been exactly two weeks since the first submission of the application, and I didn't get any response yet. I would appreciate any feedback or comments.

Pneumonia Diagnosis Ontology

PNADO provides the necessary knowledge to diagnose infective pneumonia. It covers symptoms and clinical signs, clinical history, pathogens, laboratory tests and results, imaging, differential diagnosis and pneumonia complications. PNADO is mainly developed to improve pneumonia diagnosis that is affected by errors by using it in a clinical decision support system. PNADO is built with collaboration with physicians from Gatineau hospital and it was evaluated by a pneumologist from Charles-Le Moyne hospital. PNADO will be submitted for another rigorous evaluation of domain experts.

More information can be found at https://github.com/obopneumonia/PNADO/blob/master/PNADO.owl

References
Azzi, Sabrina, Michal Iglewski, Véronique Nabelsi. Ontology Design for Pneumonia Diagnostic. IEEE Conference on Biomedical and Health Informatics (BHI). Las Vegas, 2018.

Azzi, Sabrina, Michal Iglewski, Véronique Nabelsi. Design of a Pneumonia Ontology for Diagnosis Decision Support System. World Academy of Science, Engineering and Technology International Journal of Health and Medical Engineering 12. 10 (2018) : 463-466.

Azzi, Sabrina, Michal Iglewski, Véronique Nabelsi. Design of a Pneumonia Ontology for Diagnosis Decision Support System. Conference proceedings of the ICCDSSHIA 2018: 20th International Conference on Clinical Decision Support Systems, Health Information and Applications, (2018).

Contact
Sabrina Azzi, sabr.azzi@gmail.com, GitHub: obopneumonia

Tracker link: https://github.com/obopneumonia/PNADO/issues

Acknowledgements
This ontology repository was created using the ontology starter kit

**Comment by nataled** [comment]
Dear Sabrina,

It appears that the github links you provided (both above and in your original email) do not work (Error 404 Not Found). Can you provide a link to the ontology so that it can be given a look?

Best regards,
Darren Natale

**Comment by jamesaoverton** [comment]
Maybe this? https://github.com/obopneumonia/pdo_owl

**Comment by obopneumonia** [comment]
Hi all,

I did not pay attention to the visibility aspect. I just changed the settings. The repository is now public. Sorry for the inconvenience.

https://github.com/obopneumonia/PNADO/blob/master/PNADO.owl

Best regards,

Sabrina

**Comment by jamesaoverton** [comment]
See email announcement here: https://groups.google.com/forum/#!topic/obo-discuss/n4QZPsFc-k4

**Comment by jamesaoverton** [comment]
We discussed this request on the 2019-10-08 call. Alex Diehl was assigned to reply, but I can't find his GitHub username to assign this issue to him.

The committee is concerned about the scope of PNADO and how it is supposed to fit with other OBO ontologies. I'm not an expert on this domain, only on ontology development -- the following are just my opinions.

Looking at the PNADO.owl file here:

https://github.com/obopneumonia/PNADO/blob/master/PNADO.owl

I see that PNADO:0000001 defines a class 'cardiovascular system symptom' with an XREF annotation points to SYMP:0000528. But [SYMP:0000528](http://purl.obolibrary.org/obo/SYMP_0000528) is an existing term for 'cardiovascular system symptom' -- PNADO should simply reuse SYMP:0000528, not define a new term. The OWL file contains more than 1000 PNADO terms, and it seems like there are many cases like this one where a SYMP or HP term has been assigned a new PNADO IRI.

There are also many cases where a PNADO class has been defined with XREFs to SNOMED CT and UMLS CUIs. If these are simply reused SNOMED CT or UMLS terms then they should probably just use SNOMED or UMLS identifiers. I'm also worried about copyright if these are just terms copied from SNOMED or UMLS.

What genuinely new terms is PNADO defining? The GitHub repo was built with ODK, but it looks like all the terms were manually added to PNADO.owl, so I can't tell what's new and what's reused.

If there aren't any new terms, that's fine for an ontology that just brings together existing resources, but then I don't see the need for a new PNADO prefix and addition to the OBO registry. If there are just a few, then I'd prefer to see them added to existing ontologies.

**Comment by matentzn** [comment]
@addiehl

**Comment by jamesaoverton** [comment]
Can someone give another perspective on this?

The author contacted me directly, so I tried to give a constructive response, but now I think my reply was too critical.

**Comment by obopneumonia** [comment]
Dear James,

The aim of our work is to design an ontology for pneumonia diagnosis to help physicians during the diagnosis process. PNA is the medical abbreviation of pneumonia. It can be used in a clinical decision support system. One of the challenges of our work is to reuse ontologies and resolve inconsistencies and conflicts when the concept is differently presented in many ontologies, this is often the case.
When there is no conflict, we reuse the original identifier. When the reused terms are found in several ontologies, we introduce a new identifier. We follow your suggestion to reduce the number of new identifiers.
In some cases, we need to introduce a new identifier when the concept does not correspond to our ontology intended model. For example, the definition of symptom in SYMP ontology is: "A perceived change in function, sensation or appearance reported by a patient indicative of a disease". In PNADO, we make the difference between what is reported as a body abnormality by a patient (symptom) and what the physician diagnoses (disease). For this reason, we consider arrythmia, endocarditis and bronchitis as diseases and not symptoms.
We are not alone having problems with this issue. There are several cases where one concept has multiple identifiers in OBO ontologies. "Fever" is such an example, used in HP ontology and in SYMP with an another IRI.
We reuse some terms from SNOMED_CT and UMLS (with definitions) according to the requirements of PNADO. We do not think that there is any problem about copyright. HP is an example of the ontology in OBO that reuses terms from SNOMED_CT and UMLS.
The knowledge is dynamic and PNADO has a structure to facilitate integration of new terms. We also add new relations so that emerging knowledge can be easily incorporated in future updates.
All the terms having a new identifier with the prefix PNADO are new.

Best regards,

Sabrina

**Comment by jamesaoverton** [comment]
The goals of this project all sound good to me.

My concern is term reuse. Yes, sometimes existing OBO projects overlap and are not as orthogonal as they should be. But a new project should be committed to reusing existing terms whenever possible. The solution to overlap is not more overlap. I also see many cases where PNADO is creating a new IDs for terms where overlap is not an issue, including a large set of RO relations.

> When the reused terms are found in several ontologies, we introduce a new identifier.

Surely this approach only makes the overlap problem worse. It would be much better to pick one existing OBO ID, reuse it, and xref to the other existing OBO ID. A new PNADO ID doesn't help.

> For this reason, we consider arrhythmia, endocarditis and bronchitis as diseases and not symptoms.

I'm not sure I agree about 'arrhythmia', but 'endocarditis' and 'bronchitis' are diseases in the Human Disease Ontology (DO) and those terms should be reused. I see many other disease terms in PNADO that already exist in DO.

> We also add new relations

PNADO should use existing RO relations and not make new IDs for 'has role', 'participates in', etc. New relation IDs undermine data integration even more than new class IDs.

When you reuse existing terms, you break out of the "data silo". You benefit from existing data and annotations, for free. This is the core value of OBO, and it's how PNADO can help solve the data integration problems that you have pointed to.

---

I support the stated goals of PNADO. The lack of term reuse is undermining those goals. I think the PNADO project has to show commitment to reusing existing OBO terms before the OBO community makes the commitment to including and maintaining PNADO in the OBO Library.

At this point I've spent hours looking at PNADO and replying to this issue. I've said everything I have to say. I'll leave it to other OBO Operation Committee members to handle this request from now on.

**Comment by cmungall** [comment]
I want to clarify one aspect of this:

> HP is an example of the ontology in OBO that reuses terms from SNOMED_CT and UMLS

This is not correct - HP never reuses terms from SNOMED, or from UMLS. SNOMED may independently have the same or similar concept included, and this may have been cross-referenced. And HPO has been incorporated into UMLS, so the direction is the other way round there.

**Comment by bpeters42** [comment]
Dear Sabrina, 

I wanted to check-in with you what your thoughts are on the feedback received. The request for a PURL namespace is one of the few times where people will look in detail at your project. The answers you received were all intended to help you make your project better, especially in terms of how it can be used in the context of other OBO ontologies, and benefit from improvements in them.  It would be fantastic if you could respond how you are planning to act (or not) on the recommendations. It is of course ultimately up to you what you want to do. 
- Bjoern

**Comment by obopneumonia** [comment]
Dear Bjoern,

The feedback raised very good questions. I will submit the new version of the ontology soon.

Best regards,

Sabrina

**Comment by cmungall** [comment]
Closing this for now, can reopen on receipt on new version of ontology
