### ISSUE TITLE
Reminder about FOBI prefix request

### ISSUE THREAD

**Issue by pcastellanoescuder** [OBOFoundry/OBOFoundry.github.io#1063]
Dear OBO Foundry,

It has been two weeks since the first submission of the FOBI ontology, and I didn't get any response yet. I would appreciate any feedback or comments.

Thanks in advance!

## Ontology title
Food-Biomarker Ontology
## Requested ID space
fobi
## Ontology location
 https://github.com/pcastellanoescuder/FoodBiomarkerOntology
## Contact person
Name: Pol Castellano Escuder
Email address: polcaes@gmail.com
GitHub username: pcastellanoescuder
## Issue tracker
 https://github.com/pcastellanoescuder/FoodBiomarkerOntology/issues
## Ontology license
- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
- [ ] Other: *please specify*
## Available ontology formats
The FOBI is available in both **OBO** and **OWL** formats.
## What domain is the ontology intended to cover?
The FOBI intend to cover the relationships between foods and metabolites (food-intake biomarkers). This relationships are very heterogeneous and unclear among different research groups so we want to cover this issue.
## Related OBO Foundry ontologies
FoodOn and ChEBI.
## Data source
To design the FOBI we used FooDB, ChemOnt, HMDB and ChEBI.
## Additional comments or remarks

**Comment by jamesaoverton** [comment]
We don't need two issues for this request. I'm closing this one in favour of the original #1055.
