### ISSUE TITLE
Figures about concepts and relationships

### ISSUE THREAD

**Issue by angelosalatino** [OBOFoundry/OBOFoundry.github.io#1068]
Hi there,
I research in taxonomies and ontologies of science.
I found this very interesting project. Does anyone know how many distinct concepts are covered across the different ontologies?

Or actually, is there a way to download all of them all at once, so that I can integrate them in my triple store?

Many thanks in advance
A

**Comment by matentzn** [comment]
Hey; I started a very basic analysis a few years back: http://rpubs.com/matentzn/obo112017

**Comment by matentzn** [comment]
A yaml file that lists all the ontologies, including download locations, is here: http://obofoundry.org/registry/ontologies.yml

**Comment by cmungall** [comment]
How familiar are you with sparql? A lot of basic stats like number of
classes can be down via the ontobee endpoint. But distinct unique concepts
may be fewer than distinct classes due to overlap...

**Comment by angelosalatino** [comment]
Thank you very much guys. The SPARQL endpoint is very handy indeed.

**Comment by nlharris** [comment]
It seems like this issue can be closed, since @angelosalatino was happy with the answers, but should any of this useful info be added to the website?

**Comment by angelosalatino** [comment]
Yes. I managed to complete my analysis. Thank you very much, guys.
