### ISSUE TITLE
broken links on ChEBI page

### ISSUE THREAD

**Issue by goekce** [OBOFoundry/OBOFoundry.github.io#1070]
on http://obofoundry.org/ontology/chebi.html the last two links for chebi-lite and chebi-core are not working. All ChEBI ontologies are here: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

**Comment by matentzn** [comment]
We have recently switched to http for chebi because we had problems with some of our tools; are Chebi core and lite not served via http? I will fix this tomorrow or Tuesday no matter what, but would be just god to know.

**Comment by matentzn** [comment]
Ok, we did not have a generic fall-through configured for chebi.. Hopefully, this 

https://github.com/OBOFoundry/purl.obolibrary.org/pull/589

will address your issue @goekce 

Thanks for reporting!

**Comment by matentzn** [comment]
Fixed.
