### ISSUE TITLE
Use /meta/ PURLs rather than hardcoding github links

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1090]
See https://github.com/OBOFoundry/purl.obolibrary.org/pull/428

in the navbar we have links to various artefacts that are raw GH URLs. We should instead use PURLs like:

http://obofoundry.github.io/registry/context.jsonld

**Comment by jsstevenson** [comment]
@cmungall closed by #2554 , right?

**Comment by matentzn** [comment]
I think so, if there is more to do we can open a new issue!
