### ISSUE TITLE
Resources menu is broken on website

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1091]
Does not drop down, and links directly to a file on github

**Comment by nlharris** [comment]
The second part of this (which I think is also captured in #1100) seems to be fixed, but the Resources menu still doesn't drop down; it just goes straight to http://obofoundry.org/resources. (Which doesn't seem to me like terrible behavior, but I don't know what else is supposed to be in that menu.)

**Comment by nlharris** [comment]
So are there supposed to be other items in the Resources menu?

**Comment by nlharris** [comment]
I'm going to close this because I think it's fixed. If there are still issues with the Resources menu, reopen this or create a new issue specifying what's wrong.
