### ISSUE TITLE
Resources link goes to GH rather than a web page

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1100]
Clicking 'resources' on front page takes us to

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/resources.md

We need to:

 1.  add frontmatter to this
 2. and just link it as http://obofoundry.org/resources like all the other pages

**Comment by nlharris** [comment]
It looks like these were fixed by you in PR #1091?
(Isn't a PR that fixes an issue supposed to close that issue?)

**Comment by jamesaoverton** [comment]
@nlharris GitHub looks for [special keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link PRs with issues, such as "closes", "fixes", "resolves".

I'll just close this.

**Comment by nlharris** [comment]
What I was really getting at was, why aren't the people who close the PRs using the gh keywords?

**Comment by jamesaoverton** [comment]
The keywords should be in the PR description, not just in a comment -- I was mistaken about this.

We should all make a habit of writing "Fixes #foo" in PR descriptions whenever appropriate. There's no good reason not to do so.
