### ISSUE TITLE
Request for review of Uberon

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1102]
The review process can begin. I have filled in form

**Comment by cmungall** [comment]
Note: I would also like to request that the Uberon review process and end products are fully open and transparent (including anything critical)

**Comment by nataled** [comment]
The EWG requests the following clarifications regarding your answers to the Self-Review:

Principle 4: What is the answer? For example, how are versions specified? Is there an archive of versions somewhere? (Side note: What are your recommendations to bring the principle up to full specification (beyond indicating how to specify the versionIRI--that's already being worked on). Please comment under existing ticket #955 if your ideas have not already been stated there.

Principle 11: What is the answer? We are looking for the point person for contact. This cannot be a group email. 

Principle 16: ‘Funding’ will likely help ensure that maintenance is done, but is not a plan. Let's suppose funding is obtained. What would be the maintenance plan? Would that differ if no funding is obtained?

External Reviewer: Any suggestions?

**Comment by nlharris** [comment]
> I have filled in form
Where might one find your answers, @cmungall?

**Comment by cmungall** [comment]
@nataled - can you put a link to the google sheet with my answers? Can we just copy them here? As stated previously I would like everything to be fully transparent.

Also, I can't remember my original answers...

**Comment by nataled** [comment]
@cmungall Your answers are here: https://docs.google.com/spreadsheets/d/1RV3LGWFldcPjSanB-Zpqfk-orQv7V0V_lCO5shdmTFU/edit#gid=0

Should be next to last row.

**Comment by nlharris** [comment]
@matentzn might you be able to answer @nataled's questions?

**Comment by matentzn** [comment]
Sorry I think I don’t know too much; not sure at all about the context of this thread and which questions need answering now! happy to help though!

**Comment by nataled** [comment]
@matentzn the pertinent questions are those asked in my comment from Feb 18th (currently showing up as a comment from "15 days ago")

**Comment by matentzn** [comment]
I am sorry to bounce this around, but the only other person who I can think of that could answer these questions is @balhoff (sorry jim).

**Comment by cmungall** [comment]
## p4

This is documented here: http://uberon.org/versioning

Each version of the ontology has a distinct resolvable PURL, as does every ontology artefact. You can find the list of versions on the site uberon.org.

note with OBO hat:

we need to be clearer what we are asking people for here, what is in compliance.

Do we have clear positive and negative examples?

it would be good if we requested a release index purl that resolved to an rdf file with all versions. But we don't and I don't think anyone does this.

(I've already commented on issue 955!)

## p11

me

(note that you can find this from the OBO metadata, we don't need to ask redundant things of submitters)

## p16

I'm really unclear about this principle, we seem to be confusing a few different things: a maintenance plan, scientific consensus, and date of last release

 - Maintenance plan: How much detail do you need? Do you have examples of maintenance plans for existing foundry ontologies? For uberon our rough plan is:
    - encourage contributions from broader community. This has been successful as documented in http://www.ncbi.nlm.nih.gov/pubmed/25009735. We have a lot of expert input on the tracker. We have increasing numbers of people that make PRs
    - use of logical axioms to automate as much classification and QC as possible
    - seeking funding to allow necessary maintenance and tool development
 - the [actual principle](http://obofoundry.org/principles/fp-016-maintenance.html) says "The ontology needs to reflect changes in scientific consensus to remain accurate over time.". As I state in #959 I don't think this is generally enforceable and should be treated more as a mission, or as a  But of course, if the scientific consensus changes on anatomy then Uberon will change
 - the dashboard passes here: http://obo-dashboard-test.ontodev.com/uberon/dashboard.html, this checks if there has been a release in 3 years

I think we need to simplify and clarify this principle, we need to be clear in our communication with ontology submitters

**Comment by wdduncan** [comment]
@nataled 
Have you had a chance to review this?

**Comment by nataled** [comment]
@wdduncan not personally. Reviewers have been assigned, however, and the clock has now started. We are shooting for a one month turnaround.

**Comment by wdduncan** [comment]
Onard responded to @cstoeckert 
He said that Onard is retired/semi-retired now. So, we need to update contact info for the FMA.
Chris is going to follow up with Onard about new contact person and suggesting another reviewer.

**Comment by cstoeckert** [comment]
Onard confirmed that he is still the contact person and will let us know when there is someone new.

**Comment by wdduncan** [comment]
Onard says he will be available after May if we hasn't found someone.

@wdduncan will email Peter Elkin and see if a grad willing to do it.

**Comment by ramonawalls** [comment]
I recommend @megbalk as an external reviewer.

**Comment by wdduncan** [comment]
Update:
Still awaiting feedback from reviewers.

**Comment by cmungall** [comment]
Is this still in progress? I have not seen any public material, but I consented to a review on the condition it was public

I recommend closing this ticket if it's no longer in progress

**Comment by wdduncan** [comment]
If I recall correctly, I think the review of UBERON got derailed by discussions about:
- maintaining the obo library distinction
- whether the dashboard was sufficient
- what exactly were the criteria for reviewing an ontology

I have not attend an obo call in a while. Perhaps these issues were resolved and the review is ready to proceed? Or perhaps it is best to close the close the ticket?

**Comment by nataled** [comment]
No longer relevant.
