### ISSUE TITLE
obsolete Beta Cell Genomics Ontology (BCGO)

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#1104]
The BCGO ontology was developed for supporting beta cell genomics database that are no longer in operation. So, the ontology is not under active development.

http://www.obofoundry.org/ontology/bcgo.html

**Comment by cmungall** [comment]
Can you go ahead and make the PR?

**Comment by zhengj2007** [comment]
@cmungall I have made the PR. https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1112

**Comment by nlharris** [comment]
PR #1112 was merged, so shouldn't this issue have been closed?
