### ISSUE TITLE
Principle #5 "Scope"

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#1105]
Current scope field is free text. I think it would be good to provide controlled vocabulary. It will be easy for users to find the ontologies that they may be interested in.

For my work to submit new term requests to OBO ontologies, I went through all the OBO ontologies and tagged them using few keywords for identifying which more appropriate ontology I should go. That's why I think if we can tag the ontology using controlled vocabulary in scope field will be very helpful.

This file shows the tags I assigned to OBO Foundry ontologies. It may be useful for creating the controlled vocabulary for scope.
https://docs.google.com/spreadsheets/d/1pnsRsZluXcBlMqLfPmcCxXiiKxkr3s-nmuNve3kRMhE/edit#gid=78923188

**Comment by nataled** [comment]
Please add your comment to issue #965, already opened for this principle.

**Comment by zhengj2007** [comment]
merged to tracker #965
