### ISSUE TITLE
EMAPA detail page update

### ISSUE THREAD

**Issue by tfhayamizu** [OBOFoundry/OBOFoundry.github.io#1111]
We are requesting that the detail page for the Mouse Developmental Anatomy (EMAPA) ontology be updated.

[EMAPA wiki update.docx](https://github.com/OBOFoundry/OBOFoundry.github.io/files/4182141/EMAPA.wiki.update.docx)

**Comment by cmungall** [comment]
Hi Terry,

We have a FAQ entry on how to update the metadata:

http://obofoundry.org/faq/how-do-i-edit-metadata.html

It's a bit daunting if you haven't edited info on GitHub before, but the general pattern is quite useful for many other projects. If you run into issues just let me know on this ticket and one of the OBO team will help.

**Comment by nlharris** [comment]
sounds like #1125 fixed this issue, so this issue can now be closed?

**Comment by nlharris** [comment]
Fixed by #1125
