### ISSUE TITLE
Prefix Request: Core Ontology for Biology and Biomedicine (COB)

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1115]
## Ontology title
Core Ontology for Biology and Biomedicine

## Requested ID space
COB

## Ontology location
https://github.com/OBOFoundry/COB

## Contact person
Name: Bjoern Peters
Email address: bpeters@lji.org
GitHub username: @bpeters42

## Issue tracker
https://github.com/OBOFoundry/COB/issues

## Ontology license

- [x] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Key terms for all OBO ontologies

## Intended use/related projects
The goal is to improve interoperabilty and reuse across the OBO community through better coordination of key terms. Our plan is to keep this ontology small, but ensure that one or more COB terms can be used as the root of any given OBO library ontology.

## Additional comments or remarks
This project is an attempt to bring together key terms from a wide range of OBO projects into a single, small ontology.

**Comment by zhengj2007** [comment]
Discussed on Mar 10, 2020 call. We accept the request.

**Comment by jonquet** [comment]
Well I think for the rest f the world the "core ontology" or "upper level ontology"  used by OBO ontologies is BFO.. 
Are you not afraid to create some confusion with COB?

**Comment by jamesaoverton** [comment]
I suppose there is a risk of some confusion, but there is also a need for better coordination on terms such as "cell", "population", and "life cycle", which are out-of-scope for BFO.
