### ISSUE TITLE
Coronavirus Infectious Disease Ontology

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#1123]
Submitted via OBO discuss @yongqunh 
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## CIDO
Requested Prefix: CIDO
Ontology Title: Coronavirus Infectious Disease Ontology
Download link: https://raw.githubusercontent.com/biomedontology/cido/master/src/ontology/cido.owl
Home page: https://github.com/biomedontology/cido
Contact e-mail: yuhong20040416@sina.com, yongqunh@med.umich.edu
Mailing-list:  cido-discuss@googlegroups.com
Tracker link:  https://github.com/biomedontology/cido/issues

Description:
The Coronavirus Infectious Disease Ontology (CIDO) is a biomedical ontology of the coronavirus infectious diseases. CIDO aims to provide standardized human- and computer-interpretable annotation and representation of various coronavirus infectious diseases, including their etiology, transmission, pathogenesis, epidemiology, diagnosis, prevention, and treatment. Its development follows the OBO Foundry Principles.

Submitted request via OBO Discuss 
Dr. Hong Yu, Director of Department of Respiratory and critical Care Medicine, Guizhou Province People’s Hospital, Guizhou University Medical College, Guiyang, Guizhou, China
Dr. Yongqun Oliver He, Associate Professor, University of Michigan Medical School, Ann Arbor, MI, USA.

**Comment by zhengj2007** [comment]
Discussed on Mar 10th, 2020. We accept the request since no objection in 2 weeks.

@yongqunh Please go ahead to make the registry files (md and yml).

**Comment by yongqunh** [comment]
Thanks, @zhengj2007. I just added the md file, and will be working on the yml file.

**Comment by yongqunh** [comment]
Thanks, James!

**Comment by yongqunh** [comment]
The cido.yml file has also been generated. Thanks, Jie and James!

**Comment by jamesaoverton** [comment]
Thanks @yongqunh. The PURLs are working and I've updated the registry files, but there seems to be a problem with GitHub pages, so CIDO is not yet showing up on the main obofoundry.org table. I'm hope that problem resolves itself in a day or two.

**Comment by yongqunh** [comment]
I see. No problem. Thanks for noticing!
