### ISSUE TITLE
change Setting up Protege 4.3 to Protege 5

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#114]
Current setting up Protege page refers to Protege 4.3
http://obofoundry.github.io/docs/SettingUpProtege.html

Most of OBO ontology projects moved to Github. So, the redirect link is using https rather than http. However, Protege 4.3 cannot handle https protocol and have issues to open the ontology from https URL. No changes of the screenshots used in the SettingUpProtege.html on Protege 5 beta. So, I suggest rename the "Setting up Protege 4.3" to "Setting up Protege 5" on the menu bar and change 4.3 to 5 in the "Introduction" section on the page.

**Comment by zhengj2007** [comment]
In addition ID policy linked to the old website
http://obofoundry.org/id-policy.shtml

should be replaced by 
http://obofoundry.github.io/id-policy.html

**Comment by cmungall** [comment]
Or just "Setting up Protege". If you click the "Edit" button you should be able to edit the text

General Q: where is the boundary between 'foundry' docs related to ID policy etc and general "here is how to run your ontology" project docs. We have a ton of README-editors files duplicated in multiple github projects, it would be great to consolidate these, the OBO site seems like a good place.

**Comment by zhengj2007** [comment]
"Setting up Protege" looks good to me.

What you suggested looks good to me. Actually I also wrote protege and web protege tutorial for my coworkers. If it is available on the OBO site, it can save my time.

In addition, I think it would be nice to have links to the OBO tutorial documents created by James, and general ontology development tools on the OBO site.

**Comment by nlharris** [comment]
The "Setting up Protege" page (http://obofoundry.github.io/docs/SettingUpProtege.html) still talks about 4.3, not 5. That probably needs to be updated, right?

> In addition, I think it would be nice to have links to the OBO tutorial documents created by James, and general ontology development tools on the OBO site.

See #356

**Comment by nlharris** [comment]
Since http://obofoundry.github.io/docs/SettingUpProtege.html was retired, I think this issue can be closed.
