### ISSUE TITLE
Move dashboard to obolibrary jenkins

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1141]
It is time to move the dashboard to our jenkins (https://build.obolibrary.io/job/obofoundry/)

I think this should be straightforward. @beckyjackson has done a great job documenting this and making it portable. See instructions here:

https://github.com/OBOFoundry/OBO-Dashboard

I suggest running this in an odk container in Jenkins, but if a new container is required, it should be distributed by dockerhub.

It does produce a lot of reporting (~1gb), and it may take some time to run over all ontologies. The files will need to be deployed on s3.

Note: this could be a good time to kill https://build.berkeleybop.org/job/simple-build-obo-all/ (see also http://www.obofoundry.org/faq/what-is-the-build-field.html). All this does it conversion using robot, it could easily be incorporated into the dashboard workflow.

**Comment by jamesaoverton** [comment]
Running in ODK’s Docker container should be fine, although we haven’t tested that. @beckyjackson estimates a few hours for a full dashboard build. We can talk about the details on Monday.

**Comment by nlharris** [comment]
still want to do this via jenkins?

**Comment by jamesaoverton** [comment]
@matentzn What do you think?

**Comment by matentzn** [comment]
Ideally we have a fully supported 32 GB memory obo foundry jenkins server and than, yes, I favour this. But I do not think this is important right now - I am still improving the dashboard and at least for 2021, there is no reason to move to jenkins (as I will do the updates) - we can review this again when the dashboard is stable.

**Comment by jamesaoverton** [comment]
Ok. Let's open a new issue when we have a solid plan.
