### ISSUE TITLE
Food Interactions with Drugs Evidence Ontology (FIDEO)

### ISSUE THREAD

**Issue by getbordea** [OBOFoundry/OBOFoundry.github.io#1147]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Food Interactions with Drugs Evidence Ontology (FIDEO)

## Requested ID space
FIDEO

## Ontology location
https://github.com/getbordea/fideo.git

## Contact person
Name: Georgeta Bordea
Email address: georgeta.bordea@u-bordeaux.fr
GitHub username: getbordea

## Issue tracker
https://github.com/getbordea/fideo/issues

## Ontology license

- [ X] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Food-Drug interactions automatically extracted from scientific literature

## Related OBO Foundry ontologies
BFO, DIDEO, FoodOn, ChEBi

## Intended use/related projects
The project is developed as part of the ANR funded MIAM project:
https://miam.limsi.fr/

## Data source
MeSH

**Comment by jamesaoverton** [comment]
@ddooley We'd appreciate your expert feedback on this request!

**Comment by ddooley** [comment]
Ok I will ask some questions about the project before the weekend is done.

**Comment by ddooley** [comment]
Just got to this now.  Am emailing Georgeta.

**Comment by ddooley** [comment]
@getbordea Did you get the email I sent about questions for FIDEO? I've just resent it. I'd welcome a conversation too!

**Comment by beckyjackson** [comment]
Discussed on call 5/5/2020 - we are granting the request for FIDEO.

@getbordea please go ahead and make a PR for a metadata file and a PURL configuration file. If you have any questions please let us know!

**Comment by matentzn** [comment]
Here are instructions how to add the PURL config: https://github.com/OBOFoundry/purl.obolibrary.org

**Comment by nlharris** [comment]
@getbordea did you do as requested?

**Comment by ddooley** [comment]
There's a new portal for managing this stuff, at [http://editor.obolibrary.org](http://editor.obolibrary.org) , that should work and hopefully make it simpler since ontology is on github.

**Comment by getbordea** [comment]
Hi Nomi,
We decided to move the project from my personal github account to the official git account of our research group and there were some delay because of that. I will proceed with your instructions as soon as possible.
Regards,Georgeta
    On Tuesday, July 7, 2020, 11:55:18 PM GMT+2, Nomi Harris <notifications@github.com> wrote:  
 
 


@getbordea did you do as requested?

**Comment by alanruttenberg** [comment]
Some feedback: That's a lot of permission that's being asked for without an
informative landing page explaining what the tools does and why such
extensive permissions are necessary. I didn't proceed further because of
that. *Deploy keys.* Seriously??
I suggest trying to organize this in a way that does not require any write
permissions and instead produces artifacts that people can add to their
repository themselves. Most repositories are public so you shouldn't need
to explicitly ask for read permission.

This application will be able to *read and write all public repository data*.
This includes the following:

   - Code
   - Issues
   - Pull requests
   - Wikis
   - Settings
   - Webhooks and services
   - Deploy keys

Regards,
Alan

**Comment by jamesaoverton** [comment]
The new editor works, but is still in development and has not yet been widely advertised.

For the editor we want to write PRs on behalf of the user, and unfortunately GitHub OAuth has a very coarse permissions model for writes. We are investigating alternatives.

**Comment by jamesaoverton** [comment]
Thank you for the PURL entry: https://github.com/OBOFoundry/purl.obolibrary.org/pull/676

I created a registry entry PR https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1250. @getbordea please review this PR and let us know if you want any changes.

**Comment by jamesaoverton** [comment]
Ok, I merged the registry and PURL entries, and have updated the obofoundry.org site.
