### ISSUE TITLE
Principles should be numerically sorted on obofoundry.org

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1148]
I could swear they used to be properly sorted, but now it's a jumble. See the table of contents on the left of <http://obofoundry.org/principles/fp-001-open.html> and also the "Principles" dropdown.

I think the Jekyll template just iterates through `site.principles` list, so the root of the problem is that the list of principles is scrambled in `_config.yml`. But I don't know what's causing it, and I don't have time to figure it out right now.

**Comment by nlharris** [comment]
@jamesaoverton do you want to assign this to yourself?
