### ISSUE TITLE
ID policy page - missing menu bar, broken link

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#115]
http://obofoundry.github.io/id-policy.html
Don't contain menu bar

The image is missing with broken link:
http://obofoundry.github.io/id-relationship.png

**Comment by zhengj2007** [comment]
All pages under FAQ does not have menu bar. Although there is OBOFoundry link on the page allows you to go back to homepage, it would be nice to have consistent layout for these pages.

**Comment by nlharris** [comment]
http://obofoundry.github.io/id-policy.html and other FAQ pages do have menu bars now, and I don't see any broken images on that page, so I think this can be closed.
