### ISSUE TITLE
Jenkins is not actually running integration tests?

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1155]
On PR #1153 I noticed that Travis failed while Jenkins passed. Looking at the Jenkins log, it's not clear to me that it's actually running any tests:

https://build.obolibrary.io/job/obofoundry/job/OBOFoundry.github.io/job/rvita-patch-56/1/console

By the history of the Jenkinsfile, I guess we were only using this for the dashboard, which we aren't doing anymore:

https://github.com/OBOFoundry/OBOFoundry.github.io/commits/master/Jenkinsfile

So should we just remove the Jenkinsfile and rely on Travis? That would be fine with me.

**Comment by kltm** [comment]
I think this may be more a @cmungall question--I'm not sure what the strategy here is for any given OBO project.

**Comment by jamesaoverton** [comment]
We'll just disable Jenkins for now.

**Comment by nlharris** [comment]
so can we close this or does it need to be fixed for real?

**Comment by nlharris** [comment]
also note that maybe the jenkins stuff will be changed to github actions given the new pricing model?
