### ISSUE TITLE
New Ontology Request for COVID Ontology

### ISSUE THREAD

**Issue by COVIDOnto** [OBOFoundry/OBOFoundry.github.io#1158]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
COVID Ontology

## Requested ID space
covido

## Ontology location
https://github.com/COVIDOnto/COVID-Onto

## Contact person
Name: Shen Liu
Email address: shen.liu@imicams.ac.cn
GitHub username: COVIDOnto

## Issue tracker
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1158

## Ontology license
CC-BY (version 3)

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Diseases, Clinical Presentations, Anatomic Sites, Demographic and Socioeconomic Characteristics, Organisms, Substances, Psychological Assistances, Epidemic Preventions and Control related to COVID-19

## Related OBO Foundry ontologies
No

## Intended use/related projects
No

## Data source
From published articles, books and other open accessed literature.

## Additional comments or remarks
No

**Comment by balhoff** [comment]
@yongqunh can you please review overlap of this request with your recently approved CIDO Coronavirus Infectious Disease Ontology ? Perhaps collaboration would be appropriate?

**Comment by yongqunh** [comment]
I see. Yes. There is overlap. Let’s reply to that request.
Thanks,
Oliver

**Comment by yongqunh** [comment]
Dear Dr. Shen Liu,

Your request for COVID ontology appears to overlap with our Coronavirus Infectious Disease Ontology (CIDO) which has been discussed and approved by OBO Foundry:
http://obofoundry.org/ontology/cido.html

We are happy to collaborate with you on this important and emerging work.

Thanks,
Oliver

Yongqun "Oliver" He, DVM, PhD
Associate Professor
Unit for Laboratory Animal Medicine
Department of Microbiology and Immunology
Center for Computational Medicine and Bioinformatics
and Comprehensive Cancer Center
University of Michigan Medical School
Office: 2511F ARF, 1150 W. Medical Center Dr.
Ann Arbor, MI 48109
Email: yongqunh@med.umich.edu<mailto:yongqunh@med.umich.edu>
Tel: 734-615-8231 (O)
http://www.hegroup.org/

**Comment by bpeters42** [comment]
We didn't hear back, and hope that working with Oliver's CIDO ontology will work. Also, given that the requested scope included diseases, organisms, anatomical site, but did not list any OBO foundry ontologies as 'related', we would be quite concerned that this ontology will not follow principles of re-use.

**Comment by yongqunh** [comment]
Hi Bjoern,
I have contacted the listed contact person of the COVID Ontology through email about possible collaboration. However, I have not got any feedback yet. I will continue to try to contact later.

Thanks,
Oliver
