### ISSUE TITLE
Oral Health and Disease Ontology (OHD)

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1169]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Oral Health and Disease Ontology

## Requested ID space
OHD

## Ontology location
http://purl.obolibrary.org/obo/ohd.owl

## Contact person
Name: Bill Duncan or Alan Ruttenberg
Email address: wdduncan@gmail.com or alanruttenberg@gmail.com
GitHub username: wdduncan or alanruttenberg

## Issue tracker
https://github.com/oral-health-and-disease-ontologies/ohd-ontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [x ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
RDF/XML

## What domain is the ontology intended to cover?
* Oral diseases and disorders 
* Procedures used to treat oral diseases and disorders
* Procedures used to maintain oral health

## Related OBO Foundry ontologies
* FMA
* BFO
* OGMS
* CARO
* RO
* OBI

## Intended use/related projects
* R21 project to study longevity of amalgam restorations. Publication accepted by JBMS, awaiting publications.
* National Dental Practice Based Research Network study of longevity of posterior composite restorations and root canal treatments. Publications in progress.

## Data source
Note sure what to put here. But, we translated electronic dental record data from 99 dental practices using 2 different systems.

**Comment by lschriml** [comment]
Bill - let me know if you need disease terms from the DO.

Cheers,
Lynn

**Comment by wdduncan** [comment]
@lschriml will give feedback.

**Comment by lschriml** [comment]
@lschriml will provide feedback, for this application ontology. 
To aid in development. 
Lynn

**Comment by lschriml** [comment]
As Bill stated in group call that he considers that manual review process does not help, @lschriml will not be spending time to provide feedback on this submission for review.

**Comment by wdduncan** [comment]
@lschriml I believe what I was said was that before we proceed with doing reviews, we need to assess:
* The cost of doing the review vs. the benefit of doing the review
* Who benefits from the review: 
  - The ontology developer? 
  - Outside consumers of ontologies?
  - Is the outcome of doing a review mainly to decide to put (or not put) a "star" by the ontology on the OBO Foundry page?
* Can we (at present) distinguish between application and domain ontologies in all cases (not just the OHD). At present, it doesn't seem like we can. This (in my mind) is a different issue than reviews, but it keeps making it into the conversation somehow.

Others on the call were much more skeptical of the review process than I am. I just want the review process to serve a clear purpose and have that purpose justify the effort of doing them.

**Comment by mellybelly** [comment]
Just to note that I prefer the criteria used in the dashboard over a manual review. We don't generally submit our ontologies for review, because it is not as useful as other mechanisms for review (by publication peer review or by users) and/or the new automated methods.

**Comment by addiehl** [comment]
As an application ontology, this is not undergoing review.

**Comment by addiehl** [comment]
@matentzn

**Comment by wdduncan** [comment]
Three questions:
1. What **precisely** defines something to be an "application ontology"?
2. Why aren't so-called application ontologies reviewed?
3. Where is this policy stated?

**Comment by mellybelly** [comment]
tagging for governance task team

**Comment by matentzn** [comment]
There are too many things going on in this PR.

@wdduncan are you under the impression the review should go forward? I think the Operations Committee was simply unsure what the state of this was.

You are also totally right about your comments on application ontologies @wdduncan; its never been defined and agreed upon, nor stated nor anything - it's no ground at the moment for not reviewing. In the meeting I had the impression the review request was withdrawn. Seems that's wrong..

Anyways, @mellybelly there is a lot here to unpack - from the very existence of review requests (as opposed to registration requests) to the question of application ontologies: key issues that needs answering.

Anyways, this needs to go into new issues (please do not comment on this here but open a new ones if you feel you want to say stuff and its not pertaining to OHD directly).

**Comment by wdduncan** [comment]
Thanks for you response @matentzn.  The request was never withdrawn. It was just became mired in the difficulties surrounding the review process.

**Comment by mellybelly** [comment]
This ticket is about purpose of OBO Ontology review: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1140
Until we resolve/update some of these governance issues, we will continue to see comments like these creeping into new ontology requests and review requests. 

Other relevant tickets: 
Define a continuum of OBOFoundry compatible ontologies #1367 
Reference ontologies vs. "Other" kinds #1546

I have tagged this one for the governance task team to review.

**Comment by cmungall** [comment]
OHD is now registered: https://obofoundry.org/ontology/ohd

open any new tickets with any new requests
