### ISSUE TITLE
The Amphioxus Development and Anatomy Ontology (AMPHX)

### ISSUE THREAD

**Issue by hescriva** [OBOFoundry/OBOFoundry.github.io#1170]
## Ontology title
The Amphioxus Development and Anatomy Ontology

## Requested ID space
AMPHX

## Ontology location
https://github.com/EBISPOT/amphx_ontology
https://raw.githubusercontent.com/EBISPOT/amphx_ontology/master/amphx.owl

## Contact person
Name: Hector Escriva
Email address: hescriva@obs-banyuls.fr
GitHub username: @hescriva

## Issue tracker
https://github.com/EBISPOT/amphx_ontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: please specify

## Available ontology formats
OWL, OBO

## What domain is the ontology intended to cover?
The ontology should be used in the domain of Developmental Biology and Evolution of the different species of the cephalochordate genus Branchiostoma ([NCBITaxon:7737](https://www.ebi.ac.uk/ols/ontologies/ncbitaxon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_7737)).

## Related OBO Foundry ontologies
UBERON

## Intended use/related projects
This ontology is intended to be used for description of gene expression in amphioxus (e.g. Insitus, RNA-seq). The ontology was created in the context of the European project CORBEL (https://www.corbel-project.eu/home.html), and used in the database MARIMBA (http://marimba.obs-vlfr.fr/home)

## Data source
The ontology was created through literature review describing the different developmental stages, embryonic structures and adult structures and tissues from three different amphioxus species (B. lanceolatum, B. floridae and B. belcheri)

**Comment by cmungall** [comment]
The 2 week request for comments period has passed and there have been no objections raised, so the ontology can be registered. Congratulations!

@matentzn are you taking care of making the pull request?

Some comments/requests. Acceptance into OBO is not contingent on these:

 - map to uberon where you have species-specific versions of uberon classes
 - consider making the ontology is-a complete (I'm guessing you are making this with oboedit which will one day stop working...)
    - e.g. ventral fin should be is-a fin
 - are you sure your relationships follow the all-some pattern? E.g. you have an axiom "dorsal fin SubClassOf part-of some whole embryo". But this isn't true as these finds are also found in adults
 - avoid capitalization except for proper names
 - you have cycles, e.g. Gut part-of Gut
     - hmm, looks like you are using a standard ODK setup, I would have thought travis/robot checks would have caught that....
 - consider following some of the naming conventions and design patterns in https://github.com/obophenotype/developmental-stage-ontologies cc @ANiknejad @fbastian 
    - I see you are using temporal relations to link stages, this is great!
    - you have terms "X stage" "X period" and "X development"
    - the "X development" terms (e.g. "Larva development") clash with names of developmental processes in GO, whereas you make these is-a stages
 - consider joining obo-anatomy as well as obo-discuss

**Comment by bpeters42** [comment]
Closing as this was approved.
