### ISSUE TITLE
Principle #fp-000, fp-001 "Summary"

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1171]
This request was sent to me by Barry Smith:

* Change navigation header  'Principle: Overview' to 'Principle**s**: Overview' (page fp-000)
*  Change navigation header 'Principle: Open (principle 1)' to 'Principle: Open **License** (principle 1)' (page fp-001)

**Comment by nlharris** [comment]
Regarding request 1, that turns out to be not so easy, as the header "Principle:" is part of the layout used for all the Principles pages, so to change that we'd have to create a new layout just for this overview page--IMO, probably not worth the effort.
Regarding request 2, I think "Open License" is actually a narrower statement than "Open". "Open" suggests that the ontology is in fact freely available and reusable--which of course an open license would ideally imply, but which in reality doesn't necessarily guarantee.

**Comment by nataled** [comment]
EWG conclusion:
1) Purely a TWG issue
2) Given that CC0 is not technically a license, we should not make the suggested change.

**Comment by nlharris** [comment]
can we close this issue?

**Comment by nataled** [comment]
There are two parts to this ticket. Part one is a correction, part two is a suggested change. We (the EWG) have determined that the part relevant to us (the change) should NOT be done. However, part one is still on the table but needs to be addressed by the TWG. The options are to either wait for that group to make the call and THEN close this issue, or to close this (combined) issue and create one that addresses part one only.

**Comment by nlharris** [comment]
i get that, but the change requested in part one, although technically a correction, is so trivial that it seems to me to not be worth the non-trivial amount of work it would take to fix. i feel that our time could be better spent on more pressing issues.

**Comment by wdduncan** [comment]
I took a brief look a the header. From a technical standpoint, what is needed for the header to determine what page the header is part of and then displaying the appropriate text.  
In other languages (e.g., PHP) this is easy to do. I do not know how easy it is in jinja.

**Comment by nataled** [comment]
It isn't my call to make. These are typically discussed within the relevant group (TWG in this case). If they agree with you, fine. They might not though.

**Comment by cmungall** [comment]
I agree with Nomi, we have limited resources and we have many more pressing changes to make in this tracker.

If someone does want to take this on it is of course easy to do in liquid templates (@wdduncan - we use liquid templates, not jinja2). The system we use is documented here:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md#details

The template is here:

_layouts/principle.html

someone would modify:

```
      <h1>
        Principle: {{ page.title }}
      </h1>      
```

and wrap this with an `if`, see https://shopify.github.io/liquid/tags/control-flow/

And check if page.title == 'Overview', show plural form if it is

**Comment by wdduncan** [comment]
@cmungall  Thanks for the info. I may do this, depending on how the next week goes ...
