### ISSUE TITLE
Clytia hemisphaerica Development and Anatomy Ontology (CLYH)

### ISSUE THREAD

**Issue by L-Leclere** [OBOFoundry/OBOFoundry.github.io#1178]
## Ontology title
Clytia hemisphaerica Development and Anatomy Ontology (CLYH) 

## Requested ID space
CLYH

## Ontology location
https://github.com/EBISPOT/clyh_ontology/blob/master/clyh.owl

## Contact person
Name: Lucas Leclere
Email address: lucas.leclere@obs-vlfr.fr
GitHub username: L-Leclere

## Issue tracker
https://github.com/EBISPOT/clyh_ontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
obo,owl

## What domain is the ontology intended to cover?
The Clytia hemisphaerica Development and Anatomy Ontology (CLYH) describes the anatomical and developmental features of the Clytia hemisphaerica life cycle. This species is a member of the phylum Cnidaria and belongs to the hydrozoan clade Leptothecata. Its life cycle comprises three stages: a planula larva, a benthic polyp colony, and a sexually-reproducing jellyfish (medusa).

## Related OBO Foundry ontologies
UBERON

## Intended use/related projects
This ontology is intended to be used for description of gene expression in Clytia hemisphaerica (e.g. Insitus, RNA-seq). The ontology was created in the context of the European project CORBEL (https://www.corbel-project.eu/home.html), and used in the database MARIMBA (http://marimba.obs-vlfr.fr/home)

## Data source
The ontology was created through literature review of Clytia and other hydrozoans describing the different developmental and life cycle stages.

**Comment by L-Leclere** [comment]
Were you able to discuss the inclusion of CLYH? Thank you!

**Comment by beckyjackson** [comment]
Hi @L-Leclere, thank you for following up!

We have discussed this on our call on 5/5/2020 and we are granting the request for the CLYH prefix. Please go ahead and submit a PR for a metadata file and PURL configuration.

Let us know if you have any questions!

**Comment by matentzn** [comment]
All done now, closing.
