### ISSUE TITLE
Display usage field on ontology detail pages

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1179]
See #1008 we now have usage field curated for many ontologies

But this is not visible on the ontology page. Should be on the sidebar, e.g. on http://obofoundry.org/ontology/uberon

This would be a simple addition to _layouts/ontology_detail.html

**Comment by nlharris** [comment]
Not totally simple, as the usages field can have multiple entries that would need to be displayed in some reasonable way.
e.g., in https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/uberon.md:

> usages:
 - user: http://bgee.org/
   seeAlso: https://www.biosharing.org/biodbcore-000228
   type: annotation
   description: Bgee is a database to retrieve and compare gene expression patterns between animal species. Bgee in using Uberon to annotate the site of expression, and Bgee curators one the major contributors to the ontology.
   examples:
    - url: http://bgee.org/?page=gene&gene_id=ENSG00000244734
      description: "Uberon terms used to annotate expression of human hemoglobin subunit beta"
 - user: https://www.encodeproject.org/
   seeAlso: https://www.biosharing.org/biodbcore-000034
   type: annotation
[etc]

Ontology sidebars are created here (as Chris said; just trying to save the person who addresses this some time): https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_layouts/ontology_detail.html

**Comment by cmungall** [comment]
yep, we'd iterate over all the entries and show subfields - the person implementing could look at `page.publications` as a template

**Comment by nlharris** [comment]
seems like maybe this is done and can be closed?

**Comment by nlharris** [comment]
I think this is done. Reopen (or open a new ticket) if needed.
