### ISSUE TITLE
Explore use of Disqus on pages: principles, ontologies

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#118]
Continued from #5 
On the call we discussed the possibility of using disqus on these pages. See: 

[9/22/15 8:49:38 AM] Chris Mungall: https://disqus.com/
[9/22/15 8:50:07 AM] Chris Mungall: http://stackoverflow.com/questions/21446165/how-do-i-use-disqus-comments-in-github-pages-blog-markdown

**Comment by alanruttenberg** [comment]
I've had bad experiences with disqus and use adblocker to block it. I'd suggest looking for an alternative. One idea would be to use genius.com, which is used to add annotations to any web page. Looks quite slick and has a simple API. I'll look for others.

**Comment by cmungall** [comment]
Like this?

http://genius.it/obofoundry.github.io/principles/fp-001-open.html

**Comment by alanruttenberg** [comment]
Nice :)
We probably do want a threaded discussion. The question is where (would a regular mailing list do?) and whether there is an alternative to disqus. I'll look around.

**Comment by alanruttenberg** [comment]
Maybe Discourse https://www.discourse.org/. It's not nested, but it is open source and we can self host.
https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963/6

Also worth looking at 

- http://posativ.org/isso/ 
- http://tildehash.com/

**Comment by VincentTam** [comment]
It might be very late, but [some Isso's SEO issues](https://github.com/posativ/isso/issues?utf8=%E2%9C%93&q=seo) might interest you.  Isso can't get comments incorporated into the HTML source code of the page, and it loads a 3rd-party script while content rendering.

[Staticman](https://staticman.net) is a staticman commenting system that makes use of GitHub/GitLab Pull/Merge Requests.  Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments and a much better SEO.

P.S. I maintain @staticmanlab, a public GitLab instance of Staicman.

**Comment by nlharris** [comment]
what's the status of this?

**Comment by alanruttenberg** [comment]
I'm against using Disqus for privacy reasons - they are a data harvester
and have historically exhibited a variety of dark patterns. I'm all for
using some other commenting system. Staticman looks like the right
direction. Spam is always the problem with commenting systems, and this is
where something built up like Disqus is very helpful. I see Staticman has
the ability to moderate, though having a pull request having to be approved
for each comment looks kind of heavy.  I can have a look around for some
other systems, and I'd encourage others to.

Alan

**Comment by alanruttenberg** [comment]
Maybe https://github.com/adtac/commento
Found it in this list:
https://ourcodeworld.com/articles/read/1265/top-7-best-open-source-self-hosted-comment-system-alternatives-to-disqus

On Tuesday, July 14, 2020, Alan Ruttenberg <alanruttenberg@gmail.com> wrote:
> I'm against using Disqus for privacy reasons - they are a data harvester
and have historically exhibited a variety of dark patterns. I'm all for
using some other commenting system. Staticman looks like the right
direction. Spam is always the problem with commenting systems, and this is
where something built up like Disqus is very helpful. I see Staticman has
the ability to moderate, though having a pull request having to be approved
for each comment looks kind of heavy.  I can have a look around for some
other systems, and I'd encourage others to.
> Alan
>
> On Tue, Jul 14, 2020 at 3:46 AM Nomi Harris <notifications@github.com>
wrote:

**Comment by nlharris** [comment]
i would like to close this as obsolete -- any objections?

**Comment by matentzn** [comment]
I think it's still ok to consider, but on the other hand adds complexity to our current set up with not enough value. I also agree with closing.
