### ISSUE TITLE
FOVT purl

### ISSUE THREAD

**Issue by megbalk** [OBOFoundry/OBOFoundry.github.io#1182]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
FOVT: FuTRES (Functional Trait Resource for Environmental Studies) Ontology of Vertebrate Traits

## Requested ID space
FOVT

## Ontology location
https://github.com/futres/fovt

## Contact person
Name: Meghan Balk or Ramona Walls
Email address: balkm@email.arizona.edu or rwalls@email.arizona.edu
GitHub username: megbalk or rwalls

## Issue tracker
https://github.com/futres/fovt/issues

## Ontology license

- [ X] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Measurable traits of vertebrates

## Related OBO Foundry ontologies
UBERON
OBA
BCO

## Intended use/related projects
To easily aggregate data at the individual level for vertebrate organisms. These traits include morphological measurements on fossil, sub-fossil, museum, trapped, and photographed specimens.

## Data source
FOVT is an amalgamation of published datasets and online databases, such as VertNet.

## Additional comments or remarks
FOVT is an application ontology. New traits and required anatomical terms will be added to UBERON and OBA.

**Comment by balhoff** [comment]
@megbalk will FOVT contain the actual relations of traits to specimens? And the traits themselves would be in OBA?

**Comment by pbuttigieg** [comment]
I notice the "Environmental" aspect of this ontology - would ENVO be reused here to qualify the environments that the traits occur in?

**Comment by bpeters42** [comment]
This was discussed on the OBO-operations call on 4/21, and there was agreement that this should be approved on the call . If there are no further objections on OBO-discuss by 4/27, this should go in.

**Comment by megbalk** [comment]
@pbuttigieg we have no plans as of now to use ENVO; we currently only record latitude and longitude data.

**Comment by beckyjackson** [comment]
Hi @megbalk - there have been no further objections, so we are approving the request for FOVT.

The PURL configuration PR looks good, please make a metadata file PR in this repo as well.

Let us know if you have any questions!

**Comment by jamesaoverton** [comment]
Closed by #1208 and https://github.com/OBOFoundry/purl.obolibrary.org/pull/646
