### ISSUE TITLE
Need a place for announcement templates

### ISSUE THREAD

**Issue by rlwalls2008** [OBOFoundry/OBOFoundry.github.io#119]
The Outreach WG will prepare some basic markdown templates to announce things like an ontology review, workshops, revised principles, etc. Is there already a folder where I can put those? If not, where do you suggest I create one?

These are for announcements that would be posted under _posts.

**Comment by cmungall** [comment]
Good idea.

I suggest a new top-level directory, `post-templates`. 

Also can you include this in the documentation:

The main thing to remember is the date *must* be `YYYY-MM-DD`. The file can be `YYYY-MM-DD-whatever-you-like-but-keep-it-short.md` (no spaces).

**Comment by rlwalls2008** [comment]
Great. Thanks. I will add the template folder when I upload the DO letter.

**Comment by rlwalls2008** [comment]
I created a top-level folder called post-templates.
Close with commit 20df947e30a93ea39a491544115ad80257ba2146

**Comment by cmungall** [comment]
Can you make analogous changes to the template?

https://github.com/OBOFoundry/OBOFoundry.github.io/commit/2fdd9db3d1700de9784f1c188d2651562907712d

**Comment by cmungall** [comment]
```
---
layout: post
title:  "$SHORT_TITLE"
date:   YYYY-MM-DD
categories: update
summary: "$DESCRIPTION."
image: '$IMG_URL'
---

$TEXT_HERE
```

image field can be blank, but it looks nice on the news page if its not blank. We should have some stock images for new-ontology, meeting, etc

we're not using category or tags at the moment, these can be left out

note the file must be `.md` and follow the naming conventions
