### ISSUE TITLE
Ontology for Nutritional Studies (ONS) 

### ISSUE THREAD

**Issue by FrancescoVit** [OBOFoundry/OBOFoundry.github.io#1198]
## Ontology title
Ontology for Nutritional Studies (ONS) 

## Requested ID space
ONS

## Ontology location
 https://github.com/enpadasi/Ontology-for-Nutritional-Studies

## Contact person
Name: Francesco Vitali
Email address: francesco.vitali.bio@gmail.com
GitHub username: FrancescoVit

## Issue tracker
https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
ONS is intended to cover the domain of human nutritional studies, and more broadly to cover human nutrition and diet related concepts, and their connection with experimentally produced data or evidences. 

## Related OBO Foundry ontologies
BFO as upper level
OBI as mid level
Other ontologies used:
IAO
FOODON
CHEBI
NCBITaxon
RO

## Intended use/related projects
ONS has been developed under the ENPADASI JPI European project to provide a mean of harmonizing nutritional studies over different databases, to foster integrated analysis. After this initial application oriented development, we expanded the concept integrated and connected in ONS to the entire nutritional study field, covering aspects of conducting a nutritional study, but also aspects related to human nutrition, diet, food composition. 
In future development, it is our commitment to delve deeper into the broader topic of food and health; connecting food intake and composition data to transformations of food ingested bio-actives due to human and microbial metabolism,  and finally to heath consequence, by integrating -omics analysis to the ONS conceptual frame.

## Data source
Term search in ontobee, manual curation of terms inside the ENPADASI consortium

## Additional comments or remarks
Additional description can be found in the related publicaiton: https://doi.org/10.1186/s12263-018-0601-y

**Comment by beckyjackson** [comment]
Hi @FrancescoVit - we have discussed this on 5/5/2020 and if there are no further objections by 5/12/2020, then we will approve the request for the ONS prefix.

Thank you!

**Comment by ramonawalls** [comment]
Request approved. Please create a new configuration for your ontology following the instructions at https://github.com/OBOFoundry/purl.obolibrary.org, and let us know if you need help by filing an issue in that repo.

**Comment by jamesaoverton** [comment]
Let's leave this open until the registry and PURL entries are created.

**Comment by FrancescoVit** [comment]
[Pull](https://github.com/OBOFoundry/purl.obolibrary.org/pull/661) request created

**Comment by FrancescoVit** [comment]
For registry entry, I made this [pull request](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1221) to add the ons.md. Hope everything was fine, please comment/correct if I made any msitake
