### ISSUE TITLE
The Echinoderm Anatomy and Development Ontology (ECAO)

### ISSUE THREAD

**Issue by echinoderm-ontology** [OBOFoundry/OBOFoundry.github.io#1201]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
The Echinoderm Anatomy and Development Ontology

## Requested ID space
ECAO

## Ontology location
https://github.com/echinoderm-ontology/ecao_ontology

## Contact person
Name: Charles Ettensohn
Email address: ettensohn@cmu.edu
GitHub username: @ettensohn

## Issue tracker
https://github.com/echinoderm-ontology/ecao_ontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL,OBO

## What domain is the ontology intended to cover?
The ontology should be used in the domain of Developmental Biology and Evolution of the different species of the phylum Echinodermata (NCBITaxon:7586).

## Related OBO Foundry ontologies
UBERON

## Intended use/related projects
This ontology is intended to be used for the description and  curation of information related to gene regulatory processes in echinoderms (e.g., expression patterns of endogenous genes and reporter DNA constructs, phenotypic effects of gene perturbations, etc.). The ontology was developed in collaboration with Echinobase, a database of echinoderm genomics.

## Data source
The ontology was created using scientific literature describing the different developmental stages and the embryonic, larval and adult anatomical structures of two echinoderm species (Paracentrotus lividus and Strongylocentrotus purpuratus).

**Comment by beckyjackson** [comment]
Hi @echinoderm-ontology - we have discussed this on our call 5/5/2020 and if there are no further objections by 5/12/2020, then we will approve the request for the ECAO prefix.

Thank you!
