### ISSUE TITLE
Please add an obo file format of the existing 'Mouse adult gross anatomy' ontology 

### ISSUE THREAD

**Issue by sierra-moxon** [OBOFoundry/OBOFoundry.github.io#1209]
## Ontology title
Mouse adult gross anatomy

## Requested ID space
This ontology already exists, this request is for an obo version of the file in addition to the owl version if possible.

**Comment by matentzn** [comment]
There seems to be an OBO version already:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ma.yml

http://purl.obolibrary.org/obo/ma.obo

I added it to the obofoundry metadata pages:
#1211 

Is this what you mean?

**Comment by matentzn** [comment]
Ok, merged this. @sierra-moxon does this take care of this here issue?

**Comment by sierra-moxon** [comment]
yep, thanks.
