### ISSUE TITLE
Property for representing ontology release status (alpha, beta, production)

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1213]
@jonquet suggests [here](https://github.com/INCATools/ontology-development-kit/issues/338) the use of [omv:status](https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v1.4_profile.rdfs#L367).

Are there any other opinions? Else I will request omv:status to be added to OMO.

**Comment by nlharris** [comment]
since no one suggested anything else, should Nico go ahead with his "else"?

**Comment by alanruttenberg** [comment]
I wasn't clear on what the values of omv:status would be - what purpose it
would serve.
At some point in OBI's history we used DOAP
<https://github.com/ewilderj/doap/wiki> in case that's useful.
Alan

**Comment by matentzn** [comment]
@jonquet Are the allowed values for omv:status documented somewhere?

**Comment by jonquet** [comment]
Not much. OMV was an important project  but it's abandonned now. We are considering re-adopting the properties in the "mod" namespace in the future version of MOD2.0 being currently discussed (as a profile of DCAT2).

You can still have a look at : 
http://ontolog.cim3.net/file/resource/OOR/OMV/OMV-Reportv2.4.1.pdf
Table 5.12
The ontology itself: 
https://sourceforge.net/projects/omv2/files/OMV%20Core%20Ontology/OMV_v2.4.1.owl/download
defines the omv:status property as : 
"It specifies the tracking information for the contents of the ontology. Pre-defined values"
But no pre-defined values are available. 

In AgroPortal  we use these values (represented as strings): 
<img width="450" alt="Capture d’écran 2020-06-19 à 10 41 31" src="https://user-images.githubusercontent.com/7379183/85114455-8dbb2480-b219-11ea-9e77-f83b1177e91d.png">

**Comment by matentzn** [comment]
Alright, lets wait then until we have a stable property for this. @jonquet please keep us updated - I am happy to follow your lead on this one here (i.e. which property to use for representing this `status`).

**Comment by nlharris** [comment]
any change in status?

**Comment by jonquet** [comment]
We have re-adopted omv:status in the mod name space as defined here: 
https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L487
 I would recommend using this property. 
Although this work is still in progress.

**Comment by matentzn** [comment]
Closing this in favour of https://github.com/information-artifact-ontology/ontology-metadata/issues/110
