### ISSUE TITLE
Requested Prefix: ONA

### ISSUE THREAD

**Issue by miguelfortuna** [OBOFoundry/OBOFoundry.github.io#1215]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Ontology for Avida: a computational approach for performing experimental evolution on digital organisms.

## Requested ID space
ONA

## Ontology location
https://gitlab.com/fortunalab/ontology-avida

## Contact person
Name: Miguel A. Fortuna
Email address: fortuna@ebd.csic.es
GitLab username: miguelfortuna

## Issue tracker
https://gitlab.com/fortunalab/ontology-avida/-/issues

## Ontology license
- [ ] CC-BY (version 4.0)

## Available ontology formats
owl
obo
json

## What domain is the ontology intended to cover?
digital evolution

## Related OBO Foundry ontologies
SWO

## Intended use/related projects
CDAO
ECOCORE
GENO
PCO
SWO

## Data source
https://github.com/devosoft/avida
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005414
https://royalsocietypublishing.org/doi/10.1098/rstb.2016.0431
https://github.com/miguelfortuna/avida_genbank
https://github.com/miguelfortuna/avida_host-parasite

## Additional comments or remarks
Digital evolution is an artificial life approach for studying self-replicating computer programs that evolve within a user-defined computational environment. The lack of a clearly defined vocabulary makes biologists feel reluctant to embrace this field. This unique ontology has the potential to change this picture overnight.

**Comment by cmungall** [comment]
@ctb and @ihh you may find this interesting (an Ontology for Avida - more info here: https://gitlab.com/fortunalab/ontology-avida/-/issues)

**Comment by cmungall** [comment]
@miguelfortuna this seems very interesting. Do you have any more information about how people might use this ontology?

you may also want to think about how your concepts relate to other concepts in OBO. We already have a 'genotype' concept, how does a digital genotype relate to that? We like to have unambiguous labeling so users of combined ontologies don't get confused, would you be open to terminology like 'digital genotype' (with a localized synonym for 'genotype')?

Congrats on getting the ontology development kit to work with gitlab!

**Comment by cmungall** [comment]
Also we like to have the ID space be meaningful. Why "ONA"?

**Comment by pbuttigieg** [comment]
@miguelfortuna we're reviewing this in our OBO Operations call, would you have feedback for @cmungall?

**Comment by pbuttigieg** [comment]
@miguelfortuna Please note, inactivity for more than 2 weeks will result in the issue being closed. Please feel free to reopen if you would like to pursue this further.

**Comment by lschriml** [comment]
Miguel - closing this ticket for now.
Please get in touch and we can re-open the ticket.
Cheers,
Lynn

**Comment by cmungall** [comment]
Replaced by #1581
