### ISSUE TITLE
ontologies with no description

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#122]
- aao OBS
- adw OBS
- ato OBS
- bila OBS
- bootstrep OBS
- cmf 
- dc_cl OBS
- dinto 
- ehda OBS
- ehdaa OBS
- ev OBS
- flu 
- gaz 
- gro OBS
- habronattus OBS
- ico 
- ido 
- iev OBS
- imr OBS
- ipr OBS
- loggerhead OBS
- mao OBS
- mat OBS
- mf 
- nbo 
- ncithesaurus 
- nif_dysfunction OBS
- nif_grossanatomy OBS
- obo_rel OBS
- omit 
- omp 
- ovae 
- pao OBS
- pd_st OBS
- pgdso OBS
- plo OBS
- propreo OBS
- rnao 
- sao OBS
- sopharm OBS
- swo 
- tahe OBS
- tahh OBS
- upheno 
- vhog OBS
- vo 
- vt 
- vto 
- ypo OBS
- zea OBS

**Comment by rvita** [comment]
edited ido and rnao to have description as part of metadata updates. I will continue to check for and edit descriptions for all remaining ontologies as part of this process.

**Comment by rvita** [comment]
Of non obsoleted ontologies, only cmf is still missing a description. cmf will be made into status inactive. Before being deemed active, cmf will need homepage, products description & license. Will open new item specific to cmf.
