### ISSUE TITLE
Clinical Trial Ontology

### ISSUE THREAD

**Issue by akodamullil** [OBOFoundry/OBOFoundry.github.io#1220]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Clinical Trial Ontology

## Requested ID space
CTO

## Ontology location
https://github.com/ClinicalTrialOntology/CTO

## Contact person
Name: Dr. Alpha Tom Kodamullil
Email address: alpha.tom.kodamullil@scai.fraunhofer.de
GitHub username: akodamullil

## Issue tracker
https://github.com/ClinicalTrialOntology/CTO/issues

## Ontology license

CC-BY (version 3 or later)

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Clinical Trial Ontology (CTO) is designed to formally represent and integrate all terms used to describe and register the clinical trials. 

## Related OBO Foundry ontologies
BFO as upper level
Ontology for Biomedical Investigation (OBI)
Information Artifact Ontology (IAO)
Precision Medicine and Investigation (OPMI)

## Intended use/related projects
The development of CTO was done within the context of collaboration between Fraunhofer SCAI, Germany; University of Michigan; Center for Devices and Radiological Health, FDA; and National Center for Biotechnology Information, National Library of Medicine, National Institutes of Health, Bethesda. Respective related projects are described below:

At Fraunhofer SCAI, the work was supported and funded from the EU’s Horizon 2020 Framework Programme for Research and Innovation under the Specific Grant Agreement No. 785907 (Human Brain Project SGA2 by the HBP Medical Informatics Platform) and No. 826421 (VirtualBrainCloud), and a Fraunhofer internal funding MAVO project "Human Brain Pharmacome". 
At University of Michigan, the work was supported by the NIH-NIDDK U2C Project (1U2CDK114886) and a grant from the Michigan Medicine–Peking University Health Sciences Center Joint Institute for Clinical and Translational Research (U063430). 
At NCBI side, thhe work of QL and EB was supported by the Intramural Research Program of the National Library of Medicine, National Institutes of Health.

## Data source
Term search in ontobee, import using OntoFox and manual curation of terms by various experts from the collaboration team.

## Additional comments or remarks
We have submitted the associated paper to conference ICBO 2020
Authors : Yu Lin, Stephan Gebel, Qingliang Li, Summit Madan, Johannes Darms, Evan Bolton, Martin Hofmann-Apitius, Yongqun He and Alpha Kodamullil
Title :   CTO: a Community-Based Clinical Trial Ontology and its Applications in PubChemRDF and SCAIView
Track :   ICBO2020 main research papers

**Comment by mellybelly** [comment]
Consider how this relates to the seemingly senescent OCRE ontology or content in the eagle-i resource ontology ERO 
https://bioportal.bioontology.org/ontologies/OCRE
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4019723/
http://www.ontobee.org/ontology/ERO?iri=http://purl.obolibrary.org/obo/ERO_0000016

**Comment by linikujp** [comment]
Our current thinking is that clinical research and clinical trial are different. Certainly clinical trial is a subclass of clinical research. The CTO ontology aims to characterize the aspect of clinical trial that made it differentiate from other clinical researches that are not a clinical trial.

**Comment by akodamullil** [comment]
Hello @bpeters42 , could we get an update about assignment of CTO ID and PURL link for us. Thank you in advance.!

**Comment by bpeters42** [comment]
Sorry for the delayed response. Looking at the CTO file and terms, they would all fall within the scope of OBI, as clinical trials are a subtype of biomedical investigations. There are certainly a number of terms that are not currently in OBI, and it would be great if you could work with the OBI team, rather than creating a separate entity. But there is no way of forcing you. And as apart from orthogonality, you are following the other OBO principles, we should consider this namespace request granted.

**Comment by linikujp** [comment]
@bpeters42 Thank you!
We will reach out to OBI team to ask for your input and coordinate our work.
