### ISSUE TITLE
Update New Ontology Guidelines to include namespace constraints

### ISSUE THREAD

**Issue by pbuttigieg** [OBOFoundry/OBOFoundry.github.io#1222]
Following on from an Operations Committee call:

[Our guidelines](http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html) should include a note to avoid three-letter namespaces, considering four or more letter namespaces.

**Comment by nlharris** [comment]
this came up again recently. i don't see anything on http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html yet about three-letter namespaces.

**Comment by jamesaoverton** [comment]
This might be the recent change you're thinking of: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1362

**Comment by nlharris** [comment]
yes, you're right. so can we close this ticket?
