### ISSUE TITLE
I have started with ontology and protege so I would need valid ID and IRI to publish my work

### ISSUE THREAD

**Issue by aakriti365** [OBOFoundry/OBOFoundry.github.io#1223]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology location
Protege,Web,Desktop

## Contact person
Name:Akriti kumari
Email address:aakritisingh024@gmail.com
GitHub username: aakriti365

## Ontology license

- [ ] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
owl/xml,rdf/xml,turtle

## What domain is the ontology intended to cover?
Finance,retail

## Intended use/related projects
yes

## Data source
from enterprise or creating on my own

## Additional comments or remarks
I want to learn this and would be a great help if ID is provided to me.

**Comment by jamesaoverton** [comment]
Hi @aakriti365. Finance and retail are not in the scope of the Open Biological and Biomedical Ontologies, so we can't provide an OBO ID for this project.

http://purl.org is a free service from the Internet Archive that you might consider.
