### ISSUE TITLE
Use github actions to generate _config.yml

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1224]
currently we rely on an obo maintainer to manually run the makefile to compile any changes to ontology/, then commit push results

We should just use github actions for this. It's easy to make a custom workflow that will run the make step.

Note: if we wanted to move away from hosting on gh pages, e.g. static site served off of S3, there are actions for this:

https://github.com/marketplace/actions/build-jekyll

**Comment by matentzn** [comment]
Can you give us the step by step workflow
you envision here? No human review of release artefacts anymore?

**Comment by jamesaoverton** [comment]
@matentzn: GitHub Pages / Jekyll does most of the work to build the site from the various Markdown files. However the `_config.yml` and `registry/` files need an extra step, documented here: https://github.com/OBOFoundry/OBOFoundry.github.io#generation-of-downstream-artefacts

I think that only @cmungall and I ever do that step. When I do it, I only take the quickest glance -- I don't do a through review the results. I trust the code. It just concatenates and converts, nothing fancy.

I think @cmungall is just suggesting that we automate that rebuild step with GitHub Actions. Sounds like a good idea to me!

**Comment by matentzn** [comment]
@jamesaoverton Sorry this was meant to go to the ODK ticket Chris posted. Thanks for clarification though. :)

**Comment by jamesaoverton** [comment]
Discussed on the Operations call 2020-08-09. We would like to automate this better, but there's a concern about breaking things. We agreed on the call to try it out and see what happens.

**Comment by cthoyt** [comment]
Note to all following this issue, I've created a technical solution in #1657

**Comment by wdduncan** [comment]
Thanks @cthoyt   
I totally lost track of this.
