### ISSUE TITLE
Principle 6 - Textual Definitions

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1232]
- Fix links. 

Need to be more clear on why it’s important that the logical definition matches the textual one. Perhaps highlighting a scenario where an ambiguous textual def would lead to annotations that don’t match the (more restricted) logical def, causing misclassification. State that it’s okay not to have a logical def if the class is fuzzy or the axioms/relations can’t be composed with our current stack: subclass axioms can get one pretty far, without being a “definition” a la equivalence axioms.

**Comment by nataled** [comment]
Example provided.
