### ISSUE TITLE
Principle 4 - URI/Identifier space rewrite

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1233]
Needs **Summary** and **Purpose** sections.  
Language needs to be cleaned up / rewritten.

The link for http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Chemotherapy_Regimen is broken.  
Does the **Original Formulation** part need to be in a code block?

**Comment by ramonawalls** [comment]
Principle 4 is versioning. I am goin to close this issue and make a new one. For URI/identifier space, see #954, principle 3.
