### ISSUE TITLE
Add search and sort to ontology table on homepage

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1241]
Discussed on the 2020-07-14 Operations call:

Users should be able to search for ontology and sort results. I think this is pretty much independent of other changes to the main ontology table discussed recently.

Currently the best users can do from the homepage is use their browser's Ctrl-F search for keywords. Consensus on the call was to use a bit of JavaScript to allow users to filter rows of the table by keywords, and to sort the table by column.

While this can be done in vanilla JavaScript, suggestions for a really small/light JS library would be appreciated. We currently use an old JQuery (1.10) and Boostrap 3.

**Comment by nlharris** [comment]
See also #43

**Comment by nlharris** [comment]
This is now DONE, right? 🙌
