### ISSUE TITLE
Principle #ALL Principles - retain OBO format specific implementations? 

### ISSUE THREAD

**Issue by bpeters42** [OBOFoundry/OBOFoundry.github.io#1243]
A number of principles have statements about how they are implemented for a developer working with OBO format. For example, #6, textual definitions: http://www.obofoundry.org/principles/fp-006-textual-definitions.html
States that the OBO implementation should look like: 
"id: GO:0000109
name: nucleotide-excision repair complex
def: "Any complex formed of proteins that act in nucleotide-excision repair." [PMID:10915862]"

We would suggest to remove all references to OBO format, as all the automated validation will be using OWL.

**Comment by nataled** [comment]
Current principle 2 is that both OBO and OWL (in RDF/XML) formats are acceptable, but that the PURL must resolve to OWL, and it is the OWL that gets evaluated. That means any of the below situations are both possible and compliant:

1) Ontology is edited in OBO, then converted to OWL
2) Ontology is edited in OWL, then converted to OBO
3) Ontology is edited in OWL, no conversion done

Only developers that use the first method will need guidance. Is there a way to determine the use of OBO format? For example, I imagine that we could assess the YAML files for mention of some .obo file as a product (@jamesaoverton would that work? I'm not sure if such mentions are required). Considering that the second case above might exist, this means any number thus determined would be an upper boundary, consisting of 'true' OBO users (case 1) and others not reliant upon that format (case 2).

**Comment by cstoeckert** [comment]
Proposal to remove current mention of OBO format and replace with a pointer to a page that provides guidance on usage of OBO format (or other format such as database schema). Page must be in place first before removal.

**Comment by wdduncan** [comment]
We discussed this on the operations call and decided we needed to keep the OBO-format guidance information.
