### ISSUE TITLE
Add conversion information to FAQ

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1244]
The FAQ should contain information about how to convert obo format to OWL.

**Comment by nlharris** [comment]
Sounds useful! Can you do a PR with the suggested info?

**Comment by wdduncan** [comment]
On the last editorial call we discussed not doing an FAQ, and putting a conversion section at the bottom of each page.

**Comment by nicolevasilevsky** [comment]
Agreed on 10/06/20 call that this is useful.

**Comment by nicolevasilevsky** [comment]
Point to ROBOT convert documentation page
