### ISSUE TITLE
Update instructions on main OBO Foundry page for how to submit a new ontology

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1246]
We need to make it more clear on how to submit a new ontology on the main page. Currently, we just have some language pointing to the github site, and it isn't until you go to submit an issue that you see the "New Ontology Request" button.  
I don't think the instructions need to be very verbose. Something as short as this could work:  
```
New ontologies are submitted to the OBO Foundry by submitting a new issue on the OBO Foundry GitHub page (https://github.com/OBOFoundry/OBOFoundry.github.io).
```
We also could add a link in the "Participate" drop down menu to directly submit an ontology.

---------------------------------------------
For background info I am copying the email thread that raised this issue.

from @cmungall 
FYI
need to make instructions easier

---------- Forwarded message ---------
From: Chris Mungall <cjmungall@lbl.gov>
Date: Tue, Jul 21, 2020 at 1:31 PM
Subject: Re: OBO Foundry Library
To: John Beverley <johnbeverley2021@u.northwestern.edu>

Hi John, nice to meet you! If you want to make a submission follow the instructions on http://obofoundry.org/ and it's never wrong to put something on the tracker, thanks!

On Tue, Jul 21, 2020 at 1:09 PM John Beverley <johnbeverley2021@u.northwestern.edu> wrote:
Hi Chris (if I may), 

I hope you're as well as can be expected given the circumstances. I also hope this is the appropriate email for contacting you. 

I've been directed your way by Barry due to my work on two covid-19 ontologies - the Virus Infectious Disease Ontology (VIDO) and the COVID-19 Infectious Disease Ontology (IDO-COVID-19). Specifically, in the interest of having them added to the OBO Library (embedded links are to these respective ontologies on Bioportal). 

This is my first time making such a request, so forgive me if there are procedures I've overlooked in reaching out to you. I see there are review criteria on the OBO Foundry site, but it's unclear to me whether reviews are required for ontologies in the OBO Foundry, or for any ontology in the OBO Library, so I wasn't sure if I should reach out on the issue tracker or not. If that's in fact the way to go, I'm happy to make a request on the issue tracker. 

Thanks so much, 
-John

Reply by @ramonawalls 
First we need to make decisions about what the criteria should be, if any. The current instructions are pretty good, but can lead to confusion by not mentioning any review criteria. However, there aren't really any criteria for requesting a PURL to mention. I think we have begun to make progress on this issue in the bi-weekly calls.

I think finding the instructions is harder than following them.

Reply by @wdduncan 
I think the main OBO Foundry site could be clearer about how to request a new namespace or submit an ontology. I went to the main OBO Foundry site with the mindset of "how would I submit an ontology".
I followed the instructions to the GitHub site:
You can contribute to this site using GitHub OBOFoundry/OBOFoundry.github.io 
and got kind of lost there.

The blocks of text:
I want to contribute
Please do! Anyone can fork and make PR, or create an issue in the tracker.

Note that most members of the community will do this via the obofoundry.org website - each ontology page has links for editing the metadata.

See CONTRIBUTING.md

lead me to think that info about contributing an ontology would be available on CONTRIBUTING.md, but that page is about contributing to issues. The "Participation" drop down menu also doesn't have a clear "How to submit your ontology" option. it would be good to add this.

We also need to update the language: 
The processes of the Editorial working group are modelled on the journal refereeing process. 
Since that is in flux.

**Comment by nlharris** [comment]
I think Bill's suggestions are reasonable. For the wording on the home page, I would suggest something like
[Submit your ontology to the OBO Foundry by creating a new issue in GitHub](https://github.com/OBOFoundry/OBOFoundry.github.io)

I also like Bill's idea of adding "Submit an ontology" to the Participate menu.

**Comment by wdduncan** [comment]
@matentzn suggests making some short videos on how to submit new ontologies.  He VOLUNTEERED to do this :)

**Comment by matentzn** [comment]
Right now, the phrasing for "submit a new ontology" is very technical (request a PURL), check this:
http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

We should really make a simple: Submit an ontology page, link it from the start page and explain the whole process, including links to github, in a few easy steps.

**Comment by nlharris** [comment]
Yes, we really should. Maybe you, me, and @nicolevasilevsky can work on that? It will complement your work on the videos.

**Comment by nicolevasilevsky** [comment]
Sounds good to me! I'm always in favor of simplifying instructions. Happy to help with this.

**Comment by nlharris** [comment]
Great. I think we can keep this ticket, with the modification that we will create a new "How to submit a new ontology" page and link to it from the home page (and also from the appropriate menus and other places).

**Comment by nlharris** [comment]
Even the title of that page ("Policy for OBO IDSPACE and associated PURL requests") is overly complicated and unintuitive. The page does discuss how to submit a new ontology, but the title seems to refer only to one specific technical aspect of that.

**Comment by nlharris** [comment]
When #1301 is merged, this issue can be closed.

**Comment by nlharris** [comment]
#1301 (simply text on home page) has been merged, and there is now a simple "how to submit a new ontology" page (http://obofoundry.org/faq/how-do-i-register-my-ontology.html), so I think we can close this, right?

**Comment by matentzn** [comment]
I will still record a video, so you can leave it open for a few more days. :) Thanks for all the nice work!

**Comment by nlharris** [comment]
@matentzn  I think we should make a separate ticket for the video (which you already did a first draft of!) so I can close this ticket. Sound ok?

**Comment by matentzn** [comment]
Yeah, lets do that.
