### ISSUE TITLE
All Alliance (AGR) ontologies should have a JSON product

### ISSUE THREAD

**Issue by kltm** [OBOFoundry/OBOFoundry.github.io#1248]
The Alliance is currently shifting over to using OBO JSON within their pipeline

To help support the community, it would be great if the JSON version for the ontologies used by the Alliance were available directly from the Foundry.

Tagging @cmungall 

@sierra-moxon, what OBO Foundry ontologies are you currently using? (Also I don't know Juancarlos's github handle...)

**Comment by matentzn** [comment]
@sierra-moxon provided this list last year: https://github.com/INCATools/ontology-development-kit/issues/267

**Comment by cmungall** [comment]
As an aside, it would be great to have usage tags populated for all ontologies used in the alliance

As an example, wbphenotype has a wormbase usage tag:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/wbphenotype.md

when this can be used for queries in the alliance we can add a usage tag here

currently doid is the only one tagged with an alliance usage:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/doid.md

**Comment by azurebrd** [comment]
Thanks @kltm !

**Comment by nlharris** [comment]
Are we waiting for a reply from @sierra-moxon (who doesn't seem to be known in this org)?

**Comment by azurebrd** [comment]
Ah, sorry @nlharris .  This is the .yaml file that Alliance uses to download external .obo ontology files. https://github.com/alliance-genome/agr_ferret/blob/master/src/datasets/ONTOLOGY.yaml

The ones currently used by Alliance are : 
http://purl.obolibrary.org/obo/apo.obo
http://purl.obolibrary.org/obo/bspo.obo
http://purl.obolibrary.org/obo/bto.obo
http://purl.obolibrary.org/obo/chebi.obo
http://purl.obolibrary.org/obo/cl.obo
http://purl.obolibrary.org/obo/doid.obo
http://purl.obolibrary.org/obo/dpo.obo
http://purl.obolibrary.org/obo/eco.obo
http://purl.obolibrary.org/obo/emapa.obo
http://purl.obolibrary.org/obo/fbbt.obo
http://purl.obolibrary.org/obo/fbcv.obo
http://purl.obolibrary.org/obo/fypo.obo
http://purl.obolibrary.org/obo/hp.obo
http://purl.obolibrary.org/obo/mmo.obo
http://purl.obolibrary.org/obo/mmusdv.obo
http://purl.obolibrary.org/obo/mp.obo
http://purl.obolibrary.org/obo/obi.obo
http://purl.obolibrary.org/obo/pato.obo
http://purl.obolibrary.org/obo/so.obo
http://purl.obolibrary.org/obo/wbbt.obo
http://purl.obolibrary.org/obo/wbls.obo
http://purl.obolibrary.org/obo/wbphenotype.obo
http://purl.obolibrary.org/obo/zfa.obo
http://purl.obolibrary.org/obo/zfs.obo

And also this non-.obo file 
http://purl.obolibrary.org/obo/eco/gaf-eco-mapping.txt

**Comment by sierra-moxon** [comment]
Hi @nlharris  - I work for ZFIN and the Alliance as a data manager and software engineer - I did post the list last year on a related ticket: INCATools/ontology-development-kit#267.  @azurebrd also updated just now. :)

**Comment by nlharris** [comment]
Thanks, @sierra-moxon. @kltm can this issue be closed now?

**Comment by kltm** [comment]
@nlharris 
I'm not sure that "the JSON version for the ontologies used by the Alliance were available directly from the Foundry" has been met. Also see https://github.com/INCATools/ontology-development-kit/issues/267

**Comment by matentzn** [comment]
This issue is unfulfilled, but it's not (currently at least) the OBO foundries mandate to provide JSON files for all ontologies - the Alliance needs to request the export of JSON products for each other the ontologies they are interested in on their respective trackers - there is no central build or anything through which we could (or should) manage release products on an OBO level. Sorry about that @kltm :/ Not sure who to talk to at the alliance, but this needs to be requested from their end!

We could leave this open, but the truth is, no one will ever deal with this at OBO -> so its better if the alliance takes this in their own hands! Happy to help! Once I see issues popping up at various repos, I am certainly going to be there to support their implementation!

**Comment by kltm** [comment]
@matentzn I think the underlying question here is where the canonical JSON should exist. Functionally, if people want JSON and the Alliance produces it, they would become the de facto upstream resource.

**Comment by dosumis** [comment]
Can we have JSON format version be a be a default product on ODK?  Doesn't it make sense to get back to the Alliance and have them ask their members to produce JSON versions of their ontologies in order for these to be consumed by AGR?

**Comment by matentzn** [comment]
Thats exactly how I see it @dosumis. JSON is part of odk, needing only a tiny config parameter - the bigger issue is, whether the Alliance can fund the migration of all its associated repos to ODK - that plus a policy to release JSON will be the correct way to solve this issue.
