### ISSUE TITLE
Synchronize contents of md with what is in provider owl

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#125]

**Comment by cmungall** [comment]
To generate a report:

```
make sparql-consistency-report.txt
```

Note we have some expected differences. The local description field is often short and terse. Perhaps this should be mapped to some kind of tagline property?

**Comment by nlharris** [comment]
Is this still relevant?

**Comment by jamesaoverton** [comment]
In my opinion, the dashboard checks account for this sufficiently. Please reopen if you disagree.
