### ISSUE TITLE
Use of "Recommendation" in Principle pages

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1251]
On the Principle pages we have a section name "Recommendation".  This makes it seems like the content under this is optional. I think this is too weak. We need stronger wording.

**Comment by nlharris** [comment]
would it make sense to change "Recommendations" to "Requirements"?

**Comment by wdduncan** [comment]
Yes. I think "Requirements" makes more sense in the context of the page.
Nice suggestion @nlharris !

**Comment by wdduncan** [comment]
For each principle we need to assess if it a recommendation or a requirement (or both).  
Decision on call is to leave as is for now.  

TODO: assign folks to review each principle and decide whether recommendation or requirement (or both) is most appropriate.

**Comment by nicolevasilevsky** [comment]
On the EWG call we decided we'd rename to 'Recommendations/Requirements'
