### ISSUE TITLE
Develop OBO format guidance page

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1252]
From the OBO operations call on 2020-07-28:

Bill Duncan and Chris Mungall will start the document of guidance about how to conform to principles with examples for obo format. 

cc @cmungall

**Comment by wdduncan** [comment]
@bpeters42 
We discussed having an OBO-format file support FAQ [page](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/issue-1252/faq/obo-file-format-support.md).  

I was decided that we should revisit the issue, and instead put OBO-format support at the bottom of each principle page. The reason for this has do worries that the guidance for OBO-format may easily get out of sync with what is required by the principle.

**Comment by bpeters42** [comment]
That is not my preference, but I am okay with it, as long as there is a clear separator, and the 'OBO format implementation' section is at the very bottom of the page.

**Comment by nlharris** [comment]
So is PR #1254 now obsolete?

**Comment by wdduncan** [comment]
@nlharris Yes. It is. I will close.
