### ISSUE TITLE
Genomics Cohorts Knowledge Ontology (GECKO)

### ISSUE THREAD

**Issue by beckyjackson** [OBOFoundry/OBOFoundry.github.io#1253]
## Ontology title
Genomics Cohorts Knowledge Ontology

## Requested ID space
GECKO

## Ontology location
https://github.com/IHCC-cohorts/GECKO

## Contact person
Name: Rebecca Jackson
Email address: rbca.jackson@gmail.com
GitHub username: @beckyjackson 

## Issue tracker
https://github.com/IHCC-cohorts/GECKO/issues

## Ontology license

- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
[OWL](https://github.com/IHCC-cohorts/GECKO/blob/master/gecko.owl)

## What domain is the ontology intended to cover?
biological and genomics cohort studies

## Related OBO Foundry ontologies
OBI, CMO

## Intended use/related projects
[International HundredK+ Cohorts Consortium (IHCC)](https://ihccglobal.org/) cohort browser (in development)

## Data source
GECKO is an ontologized-version of the [CINECA data model](https://docs.google.com/spreadsheets/d/1ZXqTMIhFtGOaodw7Fns5YghvY_pWos-RuSa2BFnO5l4/edit#gid=0) ([CINECA](https://www.cineca-project.eu/)) to harmonized data from across all [IHCC member cohorts](https://ihccglobal.org/membercohorts/)

**Comment by mellybelly** [comment]
Possibly some overlap with the Population and Community Ontology could potentially coordinate http://www.obofoundry.org/ontology/pco.html

@ramonawalls

**Comment by cstoeckert** [comment]
Looks like there is shared interest with VEuPathDB ontology. Let's work together!

**Comment by zhengj2007** [comment]
Discussed on Aug 11th OBO operation committee meeting. Approved for adding it in.

**Comment by pbuttigieg** [comment]
Good form overall, cool use of COB (looks much cleaner to non-OBO eyes).

### High-level points:

- There are no ORCIDs or links to responsible parties in the ontology metadata or the class metadata. 
- CC-BY is acceptable by OBO standards, but somewhat odd with ontologies (do people have to cite uses of IRIs?) Not something to resolve here, but CC-0 is more practical / less confusing in other ways
- 

### Class-level points

#### Overly generic GECKO classes 

(the list below is not exhaustive)

Some classes are very generic, such as unique identifier (GECKO_0000055)

![image](https://user-images.githubusercontent.com/2276146/89922365-388b0600-dbff-11ea-8d3a-f3e637996b2e.png)

That should more properly be in IAO (or maybe COB?). If it's not, it violates the orthogonality principle. 

For the sake of expediency, it would be good practice to add an editor note on GECKO_0000055 linking that to an issue on IAO (or other ontology) requesting the term. When the term is created in the more general ontology, the GECKO term should be obsoleted and replaced. This could be a more general policy, I think. We sometimes do this with ENVO / PATO.

Similar for the population data classes, more properly housed in PCO, IMHO:
![image](https://user-images.githubusercontent.com/2276146/89923456-eea31f80-dc00-11ea-9e4e-4c27816dd4bf.png)

Similar case for population size, which sounds STATOish, with the population size needing a class in PCO to align to the GECKO class, and a term like "statistical sample size" in STATO (if not already there).

![image](https://user-images.githubusercontent.com/2276146/89923572-14c8bf80-dc01-11ea-91b5-eb6d5934702a.png)

Similar case for timeline - that's probably high-level enough to go to COB:
![image](https://user-images.githubusercontent.com/2276146/89923746-56f20100-dc01-11ea-881a-01e913bde7d5.png)


#### Histories

![image](https://user-images.githubusercontent.com/2276146/89923837-7721c000-dc01-11ea-80ab-7b35f1710015.png)

It seems like a COB/BFO:history term should be used as a superclass here. Perhaps that's a COB issue, but it would be good if GECKO created such an issue for COB.

#### Reproducibility

Is the COB-based spin-up accessible to others? e.g. is it an ODK option now?

**Comment by ddooley** [comment]
Happy to have GECKO come into OBOFoundry.  

One thing that is a problem within OBOFoundry that shows up in GECKO is whether or not "[geographical location](http://purl.obolibrary.org/obo/COB_0000032)" is a material entity class, or a site / immaterial entity.  GECKO doesn't have to solve this.  But I will open an issue in OBOFoundry /COB on that, and GECKO can take note of any change in parenthood for that term.

**Comment by beckyjackson** [comment]
Thanks for the feedback @pbuttigieg - I've opened an issue in the GECKO tracker to discuss moving these. (IHCC-cohorts/GECKO#9)

@ddooley - I'll keep an eye out for this issue and update GECKO accordingly. Thanks!

**Comment by ramonawalls** [comment]
As a general rule, terms that are likely to be used only by GECKO would get GECKO ids, but those that are likely to be reused more widely (e.g., cohort, population data item) should move into PCO, or other ontologies as @pbuttigieg described.

I would be happy to include terms that are generally useful into the PCO. Please file issues at https://github.com/PopulationAndCommunityOntology/pco/issues.
