### ISSUE TITLE
Gender, Sex, and Sexual Orientation (GSSO) ontology

### ISSUE THREAD

**Issue by Superraptor** [OBOFoundry/OBOFoundry.github.io#1258]
## Ontology title
Gender, Sex, and Sexual Orientation (GSSO) ontology

## Requested ID space
GSSO (gsso)

## Ontology location
- https://github.com/Superraptor/GSSO (main)
- https://bioportal.bioontology.org/ontologies/GSSO (BioPortal)
- (A tertiary dedicated website is in the final stages of security checks, URL hasn't yet been assigned, but will be hosted at Cincinnati Children's Hospital Medical Center [CCHMC]) **UPDATE (22/09/2020): Website is up here: https://gsso.research.cchmc.org/.

## Contact person
Name: Clair Kronk
Email address: kronkcj@mail.uc.edu
GitHub username:  Superraptor

## Issue tracker
https://github.com/Superraptor/GSSO/issues

## Ontology license
- Other: [Apache 2.0 License]([https://www.apache.org/licenses/LICENSE-2.0)

## Available ontology formats
- Manchester-Syntax OWL (GitHub/BioPortal)
- RDF/XML (GitHub/BioPortal)
- CSV (BioPortal)
- [JSON-LD planned for release later]

## What domain is the ontology intended to cover?

Interdisciplinary information concerning gender, sex, and sexual orientation for primary usage in the biomedical and adjacent sciences.

## Related OBO Foundry ontologies
N/A (to my knowledge).

## Intended use/related projects
- Usage in identification of gender, sex, and sexual orientation-related terminology in electronic health records
- Indexing LGBTQIA+ content in libraries, archives, and databases
- Informational resource and training materials for medical professionals

## Data source
- Over 800 journal articles, books, encyclopedias, etc.; the creation process is outlined here: https://doi.org/10.1093/jamia/ocaa061 and here: https://doi.org/10.3233/SHTI190213.

## Additional comments or remarks
This is my first ontology and I have had issues in finalizing URI formats and can shift those around if necessary via Protege to better fit any guidelines. There are also numerous linkages to external ontologies for various kinds of information (anatomical info frequently links FMA and UBERON URIs for instance). 

I'm excited to submit and learn and contribute to the OBO Foundry's principles! Thank you so much for all of your work!

**Comment by dosumis** [comment]
Hi Clare, 

Many thanks for your submission.  Is there is a term in the ontology for same sex attraction?

Regards,
David

**Comment by Superraptor** [comment]
Hello Dave!

Yes, there is! "same-sex attraction" has the ID 001232. The version 2.0 of this entry is on the NCBO BioPortal here: https://bioportal.bioontology.org/ontologies/GSSO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FGSSO%2FGSSO_001232.

Hopefully we can get some shorter URIs through OBO. These are definitely a tad overwhelming for now. You can also download the ontology (https://github.com/Superraptor/GSSO) and open within Protege for faster lookup (https://protege.stanford.edu/).

The next version will include some notes regarding the synonym "same-gender attraction" and its relationship to "same-sex attraction".

Sorry for taking so long to respond! I didn't originally get a notification to the correct email, so I'll have to change that! I also can answer any questions at my academic email kronkcj (at) mail.uc.edu.

Thanks again!

-Clair

**Comment by dosumis** [comment]
Hi Clair,

Thanks for you response.  Your ontology is impressively comprehensive.  It’s clear a lot of thought has gone into the structure and I’m impressed by the amount of re-use of other ontologies.  Some notes in line.

> On 2 Sep 2020, at 21:11, Clair Kronk <notifications@github.com> wrote:
> 
> 
> Hello Dave!
> 
> Yes, there is! "same-sex attraction" has the ID 001232. The version 2.0 of this entry is on the NCBO BioPortal here: https://bioportal.bioontology.org/ontologies/GSSO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FGSSO%2FGSSO_001232 <https://bioportal.bioontology.org/ontologies/GSSO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FGSSO%2FGSSO_001232>.
> 
> Hopefully we can get some shorter URIs through OBO. These are definitely a tad overwhelming for now. You can also download the ontology (https://github.com/Superraptor/GSSO <https://github.com/Superraptor/GSSO>) and open within Protege for faster lookup (https://protege.stanford.edu/ <https://protege.stanford.edu/>).
> 
> The next version will include some notes regarding the synonym "same-gender attraction" and its relationship to "same-sex attraction".
> 
> 
That’s what I’m interested in.  Based on the definitions, it doesn’t seem possible to refer to same-sex attraction as distinct from same-gender attraction.  This seems like something of a limitation:


Preferred Name	
same-sex attraction
Synonyms	
same-sex attracted
Definitions	
Interpersonal attractions between members of the same gender.
ID	
http://purl.bioontology.org/ontology/GSSO/GSSO_001232
alternate name	
same-sex attractions
definition	
Interpersonal attractions between members of the same gender.
has related synonym	
same-sex attracted
has synonym	
same-gender attraction


Many thanks, 

David

**Comment by pbuttigieg** [comment]
This candidate ontology has very good domain coverage and cross-referencing. I'd be very interested in importing parts of it into the [UN SDGIO ](https://github.com/SDG-InterfaceOntology/sdgio) as we enter its next phase of development linked to the UN Decade of Ocean Science for Sustainable Development.

However, there are several issues in its coherency. Some examples below...

Some definition/label pairs, however, may need some more precision / evaluation against counterexamples. For example: 

[interpersonal attraction](http://purl.bioontology.org/ontology/GSSO/GSSO_001218)
> The attraction between people which leads to the development of relationships.

The attraction may not lead to the development of relationships. 

It's also a bit odd to have BFO:'specifically independent continuant' with an NCBI class for "[characteristic](http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25447)" under it, with [attractiveness ](http://purl.bioontology.org/ontology/GSSO/GSSO_006433) defined as a quality. Would it not make sense to use PATO:quality here for semantic coherency?

Also, and more importantly, the NCBI thesaurus links aren't resolving at the time of this comment. e.g. for characteristic: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25447
 

[aesthetic attraction](http://purl.bioontology.org/ontology/GSSO/GSSO_001221)
> Occurs when someone appreciates the appearance, beauty, or aesthetics of another person or persons, disconnected from sexual or romantic attraction.

The label here is overly broad given the definition. Several other cases occur. 


There are also some instances where a new GSSO classes was minted (like for [mortality rate](http://purl.bioontology.org/ontology/GSSO/GSSO_006826) where existing resources (which were imported elsewhere) like the NCBI Thesauri provide content. Is there a rationale for minting new terms rather than importing here?

Occasionally, there's definitional drift as we go deeper into hierarchies. For example, with the [identity](http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C68806) (⚠️ the NCBI Thesauri IRIs aren't resolving my side, may be a transient issue) branch. 
This starts as a "sum of characteristics", but then drifts to "The unique numerical identity of a person or being in the course of time." for [personal identity](http://purl.bioontology.org/ontology/GSSO/GSSO_003283), and then to "The sum of a being's knowledge and understanding of their self." for [self-identity](http://purl.bioontology.org/ontology/GSSO/GSSO_003284)

There are also seem to be some semantically incorrect IRI matches, it seems. For example:

[food](http://purl.bioontology.org/ontology/STY/T168)

This has an ID http://purl.bioontology.org/ontology/STY/T168
And has a CHEBI ID: http://purl.obolibrary.org/obo/CHEBI_33290

The CHEBI class is a CHEBI:'physiological role', not a BFO:object. 

I'm not sure how this is intended. 

I'm also quite confused by the alignment to upper-level classes, which leads to things like [relationships ](http://purl.bioontology.org/ontology/GSSO/GSSO_000717) as characteristics (which could be okay modelling, but somehow doesn't sit right and the definition doesn't really clarify how this is so)

There's a mix of BFO, SIO, [NCBI Thesauri](http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25377), and others. 
![image](https://user-images.githubusercontent.com/2276146/92503146-1e921280-f201-11ea-8d2e-d2c321361255.png)

**Comment by cmungall** [comment]
@Superraptor after discussion on the OBO call. we would like to go ahead and add GSSO to the OBO registry pending one technical revision - we require use of OBO PURLs in the OBO library, so effectively replacing `http://purl.bioontology.org/ontology/GSSO/` with `http://purl.obolibrary.org/obo/GSSO_`. Would this cause any problems on your side? You would have to update the docs on your README but I don't think this places any undue technical burden on you. Are you open to this?

Following @pbuttigieg's point, for the NCIT classes we recommend the OBO PURLs for NCIT, e.g. http://purl.obolibrary.org/obo/NCIT_Cnnnn. 

Both @pbuttigieg and @dosumis have good comments on the content, I suggest a good place to follow up is on your tracker, by joining OBO you'd be committing to good faith efforts to engage on these issues and issues of interoperability in general
https://github.com/Superraptor/GSSO/issues

Some additional comments from me personally: I came across this ontology a few months ago and am really impressed by the effort and content, it definitely addresses gaps in OBO at the moment

**Comment by Superraptor** [comment]
Hi!

Thank you so much for the responses and notes. I definitely want to make sure this is the best ontology possible. I'll try my best to address concerns top-to-bottom!

First, Dave,

Yes, it currently isn't possible to refer to them separately. There are a few reasonings for this currently, but for now I've added the following comment on usage to the next draft of the GSSO:

"""
Note that same-sex and same-gender attraction are listed as synonyms in this entry. This may not always be the case depending on the type of organism (i.e. human or non-human) or when considering sex vs. gender in various arenas. In general, attraction is based on a number of factors in humans, including gender expression (but not unknowable biological factors such as chromosomal composition or individual gene expression).
"""

Basically, the terms have been used so interchangeably in so many different fields that any separation could lead to potential biases, which I'm hoping to avoid. Thinking about this from the library science side of things, it would cause a lot of confusion to separate the two, in my opinion. However, I'm happy to look at any literature you might have on the subject!


Pier,

(1) interpersonal attraction. I see where you're coming from here. Per the definition it could absolutely be possible that a relationship is unreciprocated. I paraphrased that definition from the Wikipedia page [https://en.wikipedia.org/wiki/Interpersonal_attraction] (I know, not the most cohesive source). I will shift this to be more in-line with the following definition from the International Encyclopedia of the Social & Behavioral Sciences: "Interpersonal attraction is traditionally defined in social psychology as a positive attitude or evaluation regarding a particular person, including the three components conventionally ascribed to attitudes: behavioral (tendency to approach the person), cognitive (positive beliefs about the person), and affective (positive feelings for the person)."

(2) BFO:'specifically independent continuant'. I can't remember precisely why this was chosen. I thought I had patterned it off of another ontology's usage. You're absolutely right on this though. Even the definition of 'quality' notes that it is a specifically dependent continuant (SDC). I will re-list quality under SDC and characteristic (defined as distinguishing qualities) underneath 'quality'. I think that makes more sense. Thank you for pointing this out!

(3) NCI Thesaurus links... I used the links from the NCBO BioPortal, so that's unfortunate, but I can independently verify that they are not working at present. I will switch them over the OBO PURLs mentioned in a later comment! (Hopefully an easy search and replace!)

(4) 'aesthetic attraction' is a term commonly used in the asexual community (see here: http://wiki.asexuality.org/Aesthetic_attraction). I can definitely attempt to redefine this in a less broad manner. Thank you!

(5) In terms of where new terms were minted instead of re-use, there were one of three things occurring: (1) the term was overly broad with synonyms that should've been separate terms so those were broken out, (2) the hierarchy was significantly different as to cause confusion, or (3) the definition was different enough that it seemed to represent a different term. In the cause of mortality rate I believe it was situation 1 which was occurring.

(6) For the definitional drift, that's definitely something that has been hard to avoid. In the identity section it is definitely a problem because of the mixing of various fields of knowledge. Essentially the sum of a being's knowledge and understanding of their self is unique in the psychological sense, numerical here meaning that any identity can be differentiated quantitatively from any other identity (even if only theoretically). I can add this into notes.

(7) Thank you for pointing out the CHEBI issue! I will fix that.

(8) Placing hierarchies was certainly the most difficult part of this process over the last year and a half (especially as a singular developer). I'm always happy to discuss alternative hierarchies, but I tried to stay in alignment with existing hierarchies where possible, even if that meant "mixing" hierarchies occasionally. 

Thank you for all of your feedback! I'm definitely willing to hear out as much as possible to make the ontology as usable as possible!

Chris,

You posted while I was drafting this! I'm so excited! That's great to hear! I will upload a new version (hopefully later today) to GitHub as 2.0.4 with changed PURLs. This shouldn't cause too many issues on my side, so no worries! (just some updates to the docs and a couple python files on our dev site, so nothing too bad!)

I will fix all of the NCIT references as well!

And yes! For any feedback, please feel free to add an issue at the GSSO's GitHub page here: https://github.com/Superraptor/GSSO/issues. 

Best wishes and thank you so much everyone!

-Clair Kronk

**Comment by Superraptor** [comment]
Chris,

2.0.4 with changed PURLs has been added to the GitHub (https://github.com/Superraptor/GSSO). I've also reuploaded it to the NCBO BioPortal (pending update, probably done by tomorrow).

Additionally, a demo site is in the works which will be released probably next week, I will follow up with that once it is ready!

Best wishes,

Clair

**Comment by Superraptor** [comment]
The site is in its final development phases, but the final URL will be here: https://gsso.research.cchmc.org/.

**Comment by cmungall** [comment]
Hi @Superraptor we will need a stable URL that resolves to the latest version of the ontology. We can't use URLs like
https://raw.githubusercontent.com/Superraptor/GSSO/master/gsso_v2.0.4_rdf_xml.owl

As these point to a specific version

(as an aside: it's up to you how you manage files in GitHub, but you may want to consider using the GitHub release mechanism rather than depositing distinct versioned files)

We typically don't take BioPortal URLs but it's something we could consider. Generally OBOs make their ontologies available on the OBO registry, and BP picks up from there.

As an example, here is the PURL registry for PATO:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pato.yml

And this is how the GitHub repo is laid out, with the latest release names 'pato.owl':

https://github.com/pato-ontology/pato/

You may also be interested in the ODK:
https://github.com/INCATools/ontology-development-kit/

This helps you set up a github repo with a standard OBO layout - it's a bit hard to use retrospectively but you may find the documentation and general idea helpful

**Comment by Superraptor** [comment]
@cmungall all of the 2.0.4 URIs have been shifted to the OBO format! i.e. they now look like http://purl.obolibrary.org/obo/GSSO_000130.

**Comment by Superraptor** [comment]
They don't resolve currently as they need to be uploaded to the OBO registry, but they will once that has been accomplished.

**Comment by Superraptor** [comment]
I'll try to get things set up and compliant as soon as possible!

**Comment by Superraptor** [comment]
Sorry to keep posting, but I've been constructing the YML and I'm wondering if there's a separate process to upload to Ontobee? That would probably be necessary to get this working, but here's the draft:

```
# PURL configuration for http://purl.obolibrary.org/obo/gsso

idspace: GSSO
base_url: /obo/gsso

base_redirect: https://github.com/Superraptor/GSSO

products:
- gsso.owl: https://raw.githubusercontent.com/Superraptor/GSSO/master/gsso.owl
- gsso.obo: https://raw.githubusercontent.com/Superraptor/GSSO/master/gsso.obo
- gsso.json: https://raw.githubusercontent.com/Superraptor/GSSO/master/gsso.json

term_browser: ontobee
example_terms:
- GSSO_000130

entries:
- exact: /tracker
  replacement: https://github.com/Superraptor/GSSO/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/Superraptor/GSSO/releases

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=GSSO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/GSSO_000130
    to: http://www.ontobee.org/browser/rdf.php?o=GSSO&iri=http://purl.obolibrary.org/obo/GSSO_000130

- prefix: /subsets/
  replacement: https://raw.githubusercontent.com/Superraptor/GSSO/master/subsets/

- prefix: /imports/
  replacement: https://raw.githubusercontent.com/Superraptor/GSSO/master/imports/

- exact: /
  replacement: https://github.com/Superraptor/GSSO/
```

Some of these don't resolve right now, but I'll rearrange the GItHub to get it compliant ASAP!

**Comment by cmungall** [comment]
No worries about the questions!

Once your ontology registered with OBO it will automatically propagate to OntoBee (not immediately)

Your YAML looks good. Once your repo is arranged you could go ahead and make a PR adding this file to the config repo in https://github.com/OBOFoundry/purl.obolibrary.org (or we can do this for you). We'd also make a PR in this repo for the core metadata
https://github.com/OBOFoundry/purl.obolibrary.org

**Comment by Superraptor** [comment]
@cmungall Okay! It's mostly rearranged. I think some files need to be added (in terms of various folders). But I'll go ahead and add the file to the config repo! Thank you so much for all of your help with everything!

**Comment by Superraptor** [comment]
@cmungall Okay... I've started looking at the pull requests, and it's a bittt esoteric. I don't want to accidentally mess anything up syntax-wise, so maybe if you are able to add it, it might avoid any unnecessary headache. The yml is in metadata here: https://github.com/Superraptor/GSSO/tree/master/metadata.

**Comment by Superraptor** [comment]
@cmungall just following up on this!

**Comment by mellybelly** [comment]
lots of work going on related to gender/sex definitions here: https://confluence.hl7.org/display/VOC/The+Gender+Harmony+Project
see especially: https://confluence.hl7.org/display/VOC/Gender+Harmony+Context+Definitions

Given the medical context of these, it would be important for the xrefs equivalencies to be well documented using a SSSOM or xref declaration.

Very interesting work!

**Comment by Superraptor** [comment]
@mellybelly thanks so much! Once the Gender Harmony Project has xrefs I can definitely add them! I'm not seeing IRIs or PURLs on the site listed, but if I have those I can definitely map them! I wasn't aware of this project it looks great!

**Comment by wdduncan** [comment]
Approved pending technical changes previously mentioned.

**Comment by Superraptor** [comment]
@wdduncan thank you for moving the ontology! I'm just waiting on @cmungall, who offered to help with the pull requests since I was having a bit of trouble. Thank you all for all of your help!

**Comment by wdduncan** [comment]
@Superraptor Your Welcome!

**Comment by Superraptor** [comment]
Hi @cmungall, sorry to bother, but is possible to get some help on the pull request side of things? Thanks!

**Comment by matentzn** [comment]
Now this:
https://github.com/OBOFoundry/purl.obolibrary.org/pull/692/files

:D

**Comment by Superraptor** [comment]
@matentzn and @cmungall reviewed on both I think (hopefully I did it right)! Thank you both so much for your help! It's very, very, very much appreciated! At this point, what do next steps/timeline look like for the URIs and general interoperability?

**Comment by matentzn** [comment]
I think you are done @Superraptor 

You just wait for the systems to pick you up (which usually takes a few days, maybe a week) and then you are all sorted!

**Comment by matentzn** [comment]
I will close this now as no further action is required.

**Comment by Superraptor** [comment]
@matentzn just checking in on this! will the IRIs be available/accessible soon? Thanks so much!

**Comment by matentzn** [comment]
Hey @Superraptor 

The stable IDs have been registered for a while!

Try: http://purl.obolibrary.org/obo/gsso.owl

The website, and ontobee, are a bit behind.. Can you ping here again when it has not been updated in 2 weeks time?

**Comment by Superraptor** [comment]
@matentzn awesome! Thanks so much! Will do!

**Comment by Superraptor** [comment]
Hey! Just checking in, it does not appear to be updated as of yet.

**Comment by matentzn** [comment]
Almost there.. :) Just a few more things to iron out on our end!

**Comment by Superraptor** [comment]
It's added! Thank you all so much for everything and all of your help and hard work! It means a lot!

**Comment by matentzn** [comment]
Gladly! And thank you for your contributions as well.
