### ISSUE TITLE
Ontology for Nutritional Epidemiology (ONE)

### ISSUE THREAD

**Issue by cyang0128** [OBOFoundry/OBOFoundry.github.io#1261]
## Ontology title
Ontology for Nutritional Epidemiology (ONE)

## Requested ID space
ONE(one)

## Ontology location

https://bioportal.bioontology.org/ontologies/ONE (BioPortal)
https://github.com/cyang0128/Nutritional-epidemiologic-ontologies (GitHub)

## Contact person
Name: Chen Yang
Email address: Chen.Yang@UGent.be
GitHub username: cyang0128

Name: Carl Lachat
Email address: Carl.Lachat@UGent.be
GitHub username: carllachat

## Issue tracker
https://github.com/cyang0128/Nutritional-epidemiologic-ontologies/issues

## Ontology license
CC-BY 4.0

## Available ontology formats
OWL-RDF/XML

## What domain is the ontology intended to cover?
Nutritional epidemiology is a specific research area. The generic ontologies for food science, nutrition science or medical science failed to cover the specific characteristics of nutritional epidemiologic studies. As a result, we developed the ontology for nutritional epidemiology (ONE) in order to describe nutritional epidemiologic studies accurately.

## Related OBO Foundry ontologies
The present work is an extension of the Ontology for Nutritional Studies (ONS) that was developed as a comprehensive ontology to describe research in a broader human nutrition domain. The present work adds value to FoodOn, which formulates descriptions of nutrients, food items and diets.

## Intended use/related projects
(http://www.enpadasi.eu/) The European Nutritional Phenotype Assessment and Data Sharing Initiative (ENPADASI) is part of the Joint Programming Initiative (JPI) “a healthy diet for a healthy life” and is funded by national funding agencies in nine European countries.

## Data source
To enable the description of domain-specific output in nutritional epidemiology, we propose the Ontology for Nutritional Epidemiology (ONE) according to three authoritative guidance for nutritional epidemiology:

Pinart, M., Nimptsch, K., Bouwman, J., Dragsted, L. O., Yang, C., De Cock, N., Lachat, C., et al. (2018). Joint data analysis in nutritional epidemiology : identification of observational studies and minimal requirements. JOURNAL OF NUTRITION, 148(2), 285–297. https://doi.org/10.1093/jn/nxx037

Yang, C.; Pinart, M.; Kolsteren, P.; Van Camp, J.; De Cock, N.; Nimptsch, K.; et al.(2017) Perspective: Essential study quality descriptors for data from nutritional epidemiologic research. Advances in Nutrition, 8(5):639–51. https://doi.org/10.3945/an.117.015651

Lachat, C., Hawwash, D., Ocké, M. C., Berg, C., Forsum, E., Hörnel, A., Larsson, C., et al. (2016). Strengthening the Reporting of Observational Studies in Epidemiology-Nutritional Epidemiology (STROBE-nut): an extension of the STROBE Statement. PLOS MEDICINE, 13(6). https://doi.org/10.1371/journal.pmed.1002036

## Additional comments or remarks
Two journal papers and one IEEE conference paper have been published regarding the development and applications of the ontology:

Yang, C.; Hawwash, D.; De Baets, B.; Bouwman, J.; Lachat, C. (2020) Perspective: Towards automated tracking of content and evidence appraisal of nutrition research. Advances in Nutrition (IF=7.265). https://doi.org/10.1093/advances/nmaa057

Yang, C., De Baets, B., & Lachat, C. (2019). From DIKW pyramid to graph database: a tool for machine processing of nutritional epidemiologic research data. In 2019 IEEE International Conference on Big Data (Big Data) (pp. 5202–5205). Los Angeles, CA, USA: IEEE. https://doi.org/10.1109/bigdata47090.2019.9006469

Yang, C.; Ambayo, H.; De Baets, B.; Kolsteren, P.; Thanintorn, N.; Hawwash, D.; Bouwman, J.; Bronselaer, A.; Pattyn, F.; Lachat, C. (2019) An Ontology to Standardize Research Output of Nutritional Epidemiology: From Paper-Based Standards to Linked Content. Nutrients (IF=4.546), 11, 1300. https://doi.org/10.3390/nu11061300

**Comment by ddooley** [comment]
@cyang0128 after wednesday Sep 16 I'll be able to have a closer look at this.  Cheers!

**Comment by wdduncan** [comment]
Doesn't currently meet OBO standards. Still needs work. Waiting for update.

**Comment by cyang0128** [comment]
@nlharris @wdduncan @ddooley thanks a lot!!!
thank you so much @ddooley for your very kind comments! ONE has been updated accordingly: 
https://github.com/cyang0128/Nutritional-epidemiologic-ontologies/blob/master/ONE.owl 

the GitHub page of ONE has been updated as well:
https://github.com/cyang0128/Nutritional-epidemiologic-ontologies

looking forward to join the OBOFoundry family, or get your comments if ONE requires a further update! thanks again for your work.

**Comment by ddooley** [comment]
There's just one other question I'll have for the OBOFoundry folks, which is whether manchester syntax is ok for .owl file or if there is a community preference to offer it up as RDF/XML syntax.

**Comment by matentzn** [comment]
The edit file can be in any format, but the release owl files should all by RDFXML, see here: http://obofoundry.org/principles/fp-002-format.html

**Comment by cyang0128** [comment]
@matentzn thanks a lot! @ddooley ONE has been updated accordingly:
https://github.com/cyang0128/Nutritional-epidemiologic-ontologies/blob/master/ONE.owl

**Comment by ddooley** [comment]
ONE is now approved for admission into OBOFoundry!

**Comment by cyang0128** [comment]
@ddooley thanks a lot!!! looking forward to further instructions about how to maintain/update ONE indexed in OBOFoundry!

**Comment by jamesaoverton** [comment]
Registry and PURL entries have been added, see #1361.
