### ISSUE TITLE
Health Surveillance ontology (HSO)

### ISSUE THREAD

**Issue by nandadorea** [OBOFoundry/OBOFoundry.github.io#1272]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Health Surveillance ontology (HSO)

## Requested ID space
HSO

## Ontology location
curently at: 
https://w3id.org/hso
https://bioportal.bioontology.org/ontologies/HSO

## Contact person
Name: Fernanda Dórea
Email address: fernanda.dorea@svase
GitHub username: nandadorea

## Ontology license

- [ ] CC0 (public domain)
- [x ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Surveillance (public health, animal health and food safety) activities, such as case reporting, testing of samples, surveys, monitoring, etc.

## Related OBO Foundry ontologies
OBI, GenEpiO

## Intended use/related projects
We intend to use the ontology to annotate public datasets resulting form surveillance, such as those provided by the European Centers for Disease Control, or the Europen Food Safety Agency

## Additional comments or remarks
The ontology currently has it's own permaid, but all URIs have been created using "HSO_", hoping that we would eventually migrate to the OBO family. The activities are modeled mirroring protocols in OBI, but specialized to cover surveillance activities specifically.

**Comment by wdduncan** [comment]
@ddooley Will investigate the file structure and ontology terms and give update on next OBO-operations call.

**Comment by ddooley** [comment]
Github repo is at: https://github.com/SVA-SE/HSO

**Comment by ddooley** [comment]
I did a review with Fernanda Dorea and think HSO will be a great addition to the foundry.  It demonstrates many hours put towards reuse of foundry vocabularies.  Fernanda is going to work on adding definitions to HSO terms, and as well some sample vs specimen entity work.  Then I think it will be ready for admission.  She'll be switching term purls to purl.obolibrary.org/obo/hso when accepted.

**Comment by ddooley** [comment]
HSO is now approved for admission into OBOFoundry!

**Comment by nlharris** [comment]
When a new ontology like this is approved, does that mean we can close the ticket? Or is there more to be done?

**Comment by nicolevasilevsky** [comment]
(Per the OBO call) - Not until the registry and PURL are in - this is in progress.

**Comment by nicolevasilevsky** [comment]
related #1368

**Comment by jamesaoverton** [comment]
See these PRs:

- Registry https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1368
- PURL https://github.com/OBOFoundry/purl.obolibrary.org/pull/709

**Comment by jamesaoverton** [comment]
All done!
