### ISSUE TITLE
Remove History section from Principle pages

### ISSUE THREAD

**Issue by wdduncan** [OBOFoundry/OBOFoundry.github.io#1275]
We should remove the `History` section from the Principle pages. This is better placed in separate document, and link to the archived page.

**Comment by wdduncan** [comment]
Approved during OBO operations call.
We will start going through the pages on the editorial calls and making changes in which the history sections are removed.

**Comment by nicolevasilevsky** [comment]
pending PRs- Nicole, Darren and Lynn updated these records on the 02/16/21 EWG call
