### ISSUE TITLE
Update Operations Committee members?

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1278]
I think some of the members listed on  http://obofoundry.org/docs/Membership.html may have moved on. It may be time to revise the list. I made a spreadsheet last August--can update. https://docs.google.com/spreadsheets/d/1VurNA9SahgNUxeU9ZxeK4JCcGICNs3oP21FUmy01968/edit#gid=0

(No rush--just wanted to note this while I was thinking of it.)

Also, what is the formal process for adding new people to the Operations Committee? I would like to nominate @nicolevasilevsky.

**Comment by matentzn** [comment]
100+ on @nicolevasilevsky

**Comment by mellybelly** [comment]
AFAIK we don't have any governance documented for the committee membership or terms, this might be a good thing to work on. 

+100 on Nicole also! (but i clearly have a COI ;-))

**Comment by matentzn** [comment]
Also @ddooley is not on that list? (despite being _clearly_ a member).

**Comment by nlharris** [comment]
@ddooley now added by PR #1279

**Comment by nlharris** [comment]
https://docs.google.com/spreadsheets/d/1VurNA9SahgNUxeU9ZxeK4JCcGICNs3oP21FUmy01968/edit#gid=0 now updated, with a few new people to add to the Operations Committee member web page (pending approval) and few members who haven't been visibly active lately to consider moving to the Alumni section.

**Comment by nlharris** [comment]
see also #1375
