### ISSUE TITLE
Process for adding new OBO Operations Committee members?

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1280]
We have an onboarding doc but it doesn't describe the process for nominating and adding new members. See also #1278.

**Comment by nlharris** [comment]
@cmungall notes (in #1412) that we should also document the SOP/rules for moving existing members to "alumni" status.

**Comment by nlharris** [comment]
The onboarding doc (which I don't want to link here) also needs some other clarifications and improvements. @nicolevasilevsky would be a great person to take this on, particularly since she onboarded fairly recently and probably has some recollection of where the points of friction were. I would be happy to help, @nicolevasilevsky...

**Comment by matentzn** [comment]
- [ ] Operations committee to identifier volunteer to assign.

**Comment by cmungall** [comment]
I would like to make the onboarding doc public, and have it linked clearly from the main site.

The rules for nominating ops members should also be public and the process be transparent. It should clearly and concisely answer questions such as:

 - who can nominate new members
 - can members of the community put themselves forward
 - what characteristics / criteria are for members
 - how is this decided - e.g voting?
 - what are expectations; for ops members in general, and members of WGs
 - what is the offboarding procedure

**Comment by nlharris** [comment]
@mellybelly This seems like one for the governance task team!

**Comment by mellybelly** [comment]
+1! we need a governance tag, are you equipped to make one so i can go through everything and tag things?

**Comment by nlharris** [comment]
label already exists and added to this issue 😀

**Comment by matentzn** [comment]
Coming up again now, need to document this better. related:

- There is this page https://obofoundry.org/faq (not linked from anywhere)
- Which points to a page https://obofoundry.org/join.shtml (that does not exist)

**Comment by matentzn** [comment]
OFOC call:

Draft a simple "new members" SOP and add it here to issue. We can start by writing down the current informal process which seems to work fine, bit at least write it down.

**Comment by nlharris** [comment]
Nico addressed that with this PR (awaiting approval): Document current informal process for admitting new OFOC members #1807

**Comment by nlharris** [comment]
> *  [ ]  There is this page https://obofoundry.org/faq (not linked from anywhere)
> * [ ]  Which points to a page https://obofoundry.org/join.shtml (that does not exist)

I think https://obofoundry.org/faq is obsolete. There is a FAQ menu on obofoundry.org that includes some of the info that's on that orphan faq page. I'll see if there's anything else on it that should be added to the FAQ menu.

**Comment by nlharris** [comment]
Ok, I went through https://obofoundry.org/faq. I think there is some useful info to mine from it and put elsewhere; then that obsolete page can be deleted. Below I comment on each section of /faq and suggest how I think we should proceed.

> How do I join the OBO Foundry?
Joining is easy! Just follow the steps on our join page [link 404s]. We look forward to hearing from you.

Not in main FAQ. Not clear what 'join' even means. "Contribute" section of FAQ has "How do I submit my ontology", and there's a Participate menu with mailing lists, Slack, etc., so I don't think there's any content here we need to merge in. Action: none.

> How should I cite the OBO Foundry?
Smith B....(2007). "The OBO Foundry: coordinated evolution of ontologies to support biomedical data integration", Nature Biotechnology 25, 1251 - 1255.

That is the old publication. There's no "how to cite OBO Foundry" in main FAQ -- Citation section just has "How do I cite an ontology?". There is a Citation menu that includes "Cite the OBO Foundry" (which points to the new paper). Action: I suggest we add "How do I cite the OBO Foundry?" to main FAQ to make the info easier to find. If there are no objections, I'll do that.

> Are the ontologies in the OBO Foundry available only in OBO format?
No! Here is a definition of the OBO language in terms of OWL semantics [links to https://www.bioontology.org//wiki/Index.php/OboInOwl:Main_Page, which is empty]. You can download any OBO ontology in various formats--including OWL--here [raw link to http://ontologies.berkeleybop.org/].

There is a page https://obofoundry.org/faq/where-is-the-obo-file.html -- maybe this info could be added to that page? There's also http://robot.obolibrary.org/convert about converting between e.g. OWL and OBO. Action: I could use some guidance about what best to do here.

> Is there a tool that will let me create or edit OBO ontologies?
OBO-Edit, an open source Java tool, offers a convenient visual interface for creating, editing, and browsing ontologies. It was initially created to work on OBO-format ontologies, but is currently being extended to handle other ontology formats, such as OWL.

This seems very out of date. If we want to add this Q&A to the main FAQ, I think the answer can just point to https://obofoundry.org/resources, which includes a list of ontology-related tools. Action: Let me know whether you want me to add this Q (with answer pointing to https://obofoundry.org/resources) to the main FAQ.

> How should we resolve conflicts when ontologies overlap?
Make every attempt to resolve inconsistencies and merge the ontologies. Tools are available for aiding this process (such as OBOL and Prompt) and the community can be used to help clarify best practices. Also, face-to-face meetings can helpful to resolve details that cannot be covered through email.

Not in main FAQ -- useful to add? Seems like maybe it should be covered in one of the principles, though I'm not sure which. Action: Let me know what you think.

**Comment by nlharris** [comment]
I am working on this but will open a new ticket because this has diverged from the original aim of the ticket.

**Comment by nlharris** [comment]
I believe the original request in this ticket (documenting the process for nominating and adding new members) is satisfied by the creation of the NewOBOFC page (already-merged PR #1807) and by linking to it from the OFOC page (see my PR #1926) and the new Participation page (see my PR #1928).

The stuff about improving the FAQ I moved to a new ticket: #1930
