### ISSUE TITLE
broken image link on announcement page in Safari

### ISSUE THREAD

**Issue by cstoeckert** [OBOFoundry/OBOFoundry.github.io#129]
The Foundry icon is not showing up on Safari, it is in Firefox.
http://obofoundry.org/update/2015/08/11/welcome.html

**Comment by cmungall** [comment]
Not a browser issue, one is just caching more.

https://github.com/OBOFoundry/OBOFoundry.github.io/commit/cbc4e2070b12e0617b702b001c7019e99893f81a
