### ISSUE TITLE
new OBO Foundry page, default format for download button

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#130]
Can Ontology editors specify which type of file will be connected to the download file page ? 

Or should this link to the ontology page, where the editors can provide options (owl and/or obo).

**Comment by cmungall** [comment]
obo-format is deprecated. There are many reasons why people use it in an edit workflow e.g. better diffs. But that is independent of downloads

I appreciate most bioinformaticians prefer an obo download, but I don't think this stratifies neatly with ontology, so it would be weird to have an ad-hoc mix of obo and owl defaults on the front page (though there are a set of ontologies that bioinformaticians tend to use more, like doid, go, etc).

I think the best thing is to remove the download on the front page, force people to go to the ontology detail page, and see the specifics of the products on offer. There may be caveats with the obo download. For now the obo for doid would be equivalent to the owl, but you need to make a choice when you add more detailed axiomatization, do you try and force that into the obo or remove it?

**Comment by nlharris** [comment]
Is this now addressed?

**Comment by jamesaoverton** [comment]
I would say that this has been addressed:

1. the main download button is OWL, following Principle 2
2. other formats are listed prominently as `products`

Please reopen if I'm mistaken.
