### ISSUE TITLE
broken links on page ProjectHome.html

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#131]
The link of MissionStatement:
http://obofoundry.github.io/docs/MissionStatement.md
  indicated that "File not found"

However, I do find the file in the github project.

I am using Firefox in PC.

**Comment by cmungall** [comment]
http://obofoundry.github.io/docs/MissionStatement.html

**Comment by cmungall** [comment]
Is this the mission statement of the OBOFOC or the OBOF? Confusing

**Comment by zhengj2007** [comment]
OBOFOC
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/MissionStatement.md

**Comment by cmungall** [comment]
Then I recommend renaming the file

**Comment by cmungall** [comment]
So I just took across what was on the original obofoc wiki, which was a 
mixture of obofoc stuff and the other committees, including stuff that 
is really super-useful for users like the obo purl documentation, which 
we didn't have anywhere else. This didn't seem like the domain of the 
obo ops, so I just assumed this was mixed documentation, hence placement 
in the "docs" directory.

But it's confusing if we have a file called "mission statement" and this 
is the ms of the OBOFOC, and none of the other committees have an MS, 
and the OBOF itself doesn't have a mission statement.

I think we need to refactor thinking a little more outward facing rather 
than internal committee language. I would keep the docs directory as 
being generic documentation and name files that are specific to a 
committee accordingly

**Comment by zhengj2007** [comment]
Agree. How about discuss it at the next OBOFOC meeting? In addition, I'd prefer to rename documentation to something like Operation Committee.

I checked the link of "mission statement' in the ProjectHome.md. It is correct. Will the html automatically generate based on the md file?

**Comment by cmungall** [comment]
On 1 Oct 2015, at 7:42, jie zheng wrote:

> Agree. How about discuss it at the next OBOFOC meeting? In addition, 
> I'd prefer to rename documentation to something like Operation 
> Committee.

Right, but the point is that the documentation that is currently in that 
directory is not specific to the operation committee

> I checked the link of "mission statement' in the ProjectHome.md. It is 
> correct. Will the html automatically generate based on the md file?

Yes. It's intended to be a simple system. You can edit the md file 
either through the github web interface (just click on the edit button 
on any page), or by doing a local check out, commit, push. The changes 
will be reflect as html on the main website within a few seconds. See 
the FAQ for details.
