### ISSUE TITLE
Link to nonexistent page from docs/OperationsCommittee.md

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1316]
`[Members](Membership.html) of the OBO Foundry Operations Committee aim at improving flow of operations and making things happen within the [OBO Foundry](http://obofoundry.org), in collaboration with the [OBO Foundry Coordinating Editors](http://obofoundry.org/coordination.shtml) and external invited experts. `

There is no page coordination.shtml, but I don't know what the right URL is there. If no one else knows either, I'll just get rid of that hyperlink.

**Comment by matentzn** [comment]
Sounds like this should be linked (and rephrased to mean) the editorial working group? http://obofoundry.org/docs/EditorialWG.html

**Comment by matentzn** [comment]
Sounds like this should be linked (and rephrased to mean) the editorial working group? http://obofoundry.org/docs/EditorialWG.html

**Comment by nlharris** [comment]
Hmm. Possibly, but I'm not sure. Isn't the Editorial WG a subset of the Operations Committee?

**Comment by nlharris** [comment]
Maybe @jamesaoverton or @cmungall can interpret this?
