### ISSUE TITLE
add to ‘how do I register my ontology page?” -- instruction to ask if you want to be added to the Slack

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#1321]
Where it says "send email to obo-discuss" add a note about "if you wanna joing the obo-community slack (optional), please indicate in your email"

Decision from 10/06/20 OBO Operations mtg.

**Comment by cmungall** [comment]
This is too buried. It should be more prominent.

**Comment by cmungall** [comment]
Why don't we make a public channel? https://slack.com/help/articles/360017938993-What-is-a-channel

**Comment by ddooley** [comment]
Link approved to Slack workplace!

**Comment by nlharris** [comment]
so are we done with this or do we need to add the slack link somewhere?

**Comment by matentzn** [comment]
Thats not been done I think.. Someone needs to add a link to the "participate" menu and perhaps on the front page. Just make sure that it is says "OBO community" and not "OBO foundry".

![image](https://user-images.githubusercontent.com/7070631/99431600-ef83d580-2902-11eb-81f9-5ecf349cb43e.png)

i can review the changes.

**Comment by nlharris** [comment]
@nicolevasilevsky is this something you could do? Otherwise, I can work on it.

**Comment by nicolevasilevsky** [comment]
I'll work on this, @nlharris!
