### ISSUE TITLE
Add link to Nicole's MORRC scoring spreadsheet

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1339]
@nicolevasilevsky made a google spreadsheet for the Minimum Ontology Registration Request Checklist (MORRC) described on https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md

We should save a blank copy of Nicole's spreadsheet for future use, and point to it from the MORRC page. I can do that, if others agree.

See also related issue #1322

**Comment by nlharris** [comment]
Just found this OBO Foundry Ontology Review form: https://docs.google.com/forms/d/16jcXL_NdAdeS5xAHqvvPFAEnXsLhVJ4Gd8HokrLbTBo/viewform
and now I recall that there was some discussion about it, but can't find it right now.

**Comment by nlharris** [comment]
Maybe I was thinking of #882?

**Comment by matentzn** [comment]
You can find the spreadsheet in this ticket:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/392

**Comment by nlharris** [comment]
I guess I left this too long; I'm now not sure what my action item is. Is it to make a copy of Nicole's filled in score sheet (https://docs.google.com/spreadsheets/d/13vOaibPpo2m4u8jKDjF5_Z7sP_o2igblNLSgVyKwQ2o/edit#gid=0), put it somewhere publicly readable, and point to it from the Registration Checklist (https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md)?

**Comment by nlharris** [comment]
Cleared MORRC scoring spreadsheet: https://docs.google.com/spreadsheets/d/1aH8ivqS1pE5IchJtkWYOfebmtkd-s2Zsdq4b5PK8hgQ/edit#gid=0

**Comment by nlharris** [comment]
Can someone clarify whether I'm supposed to add a link to the MORRC scoring spreadsheet from https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md? Maybe @jamesaoverton knows?

**Comment by matentzn** [comment]
Not James domain- this is all EWG matter. But in this case, yea, feel free to add a link! I will approve.

**Comment by nicolevasilevsky** [comment]
I'm on the EWG and that sounds good to me. Thanks @nlharris and @matentzn

**Comment by nlharris** [comment]
Thanks, @nicolevasilevsky and @matentzn! I decided to first make some changes to the MORCC scoring sheet.

**Comment by nlharris** [comment]
@nicolevasilevsky see what you think of my new version: https://docs.google.com/spreadsheets/d/1aH8ivqS1pE5IchJtkWYOfebmtkd-s2Zsdq4b5PK8hgQ/edit#gid=0

**Comment by nicolevasilevsky** [comment]
I love it!
