### ISSUE TITLE
Ontology of units of Measure

### ISSUE THREAD

**Issue by SLvanL** [OBOFoundry/OBOFoundry.github.io#1341]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Ontology of units of Measure

## Requested ID space
OM

## Ontology location
https://github.com/HajoRijgersberg/OM

## Contact person
Name: Hajo Rijgersberg 
Email address: hajo.rijgersberg@wur.nl
GitHub username: HajoRijgersberg

## Issue tracker

https://github.com/HajoRijgersberg/OM/issues

## Ontology license

CC-BY (4.0)

## Available ontology formats

OWL2 RDF/XML

## What domain is the ontology intended to cover?

The Ontology of units of Measure (OM) 2.0 models concepts and relations important to scientific research. It has a strong focus on units, quantities, measurements, and dimensions.

## Related OBO Foundry ontologies

Measurement method ontology
Clinical measurement ontology
Units of measurement ontology
Experimental condition ontology

## Intended use/related projects

The OM ontology provides classes, instances, and properties that represent the different concepts used for defining and using measures and units. It includes, for instance, common units such as the SI units metre (om:metre) and kilogram (om:kilogram), but also units from other systems of units such as the mile (om:mile) or nautical mile (om:nauticalMile-International). For many application areas it includes more specific units and quantities, such as the unit of the Hubble constant: km/s/Mpc om:kilometrePerSecond-TimePerMegaparsec, or the quantity vaselife om:VaseLife.

The following application areas are supported by OM:

Geometry
Mechanics
Thermodynamics
Electromagnetism
Fluid mechanics
Chemical physics
Photometry
Radiometry and Radiobiology
Nuclear physics
Astronomy and Astrophysics
Cosmology
Earth science
Meteorology
Material science
Microbiology
Economics
Information technology
Typography
Shipping
Food engineering
Post-harvest technology
Dynamics of texture and taste
Packaging

**Comment by cmungall** [comment]
@SLvanL @ HajoRijgersberg can you comment on how OM fits into the existing OBO landscape, specifically PATO and UO

Note there is an existing long-running discussion on the pato tracker, perhaps you could comment there:
https://github.com/pato-ontology/pato/issues/101#issuecomment-702680371

**Comment by kaiiam** [comment]
cc @mpsaloha as well. It'd be ideal to see some sort of convergence of ontologies for units within OBO.

**Comment by ramonawalls** [comment]
I am wondering if efforts toward this ontology wouldn't be better placed by fixing the problems with UO and the other existing ontologies. What use cases does this new ontology fill that can't be met with existing ontologies.

If it does make sense to make this new ontology, I strongly urge a different abbreviation. O&M is already widely used in the semantic web and standards worlds, and using OM here is likely to cause confusion.

**Comment by ddooley** [comment]
I'd love to see a convergence too.  I'll say that OM is already mature, like QUDT. It has a bit more engineering to it than UO, as evidenced by a spreadsheet app the author did that I've seen that does unit conversion. Looking forward to hearing from its authors about how it could fit in. This issue could be discussed at an operations committee session - with input from UO & OM & ... ?

**Comment by HajoRijgersberg** [comment]
Thank you all for your interest in OM and ontology of units, quantities and the like in general! I am very much looking forward to further discussion and hope that we can take steps to improve - if and where necessary - ontology of units and related concepts in OBO. First, I should study UO. I looked at it a long time ago, but I assume that the ontology has evolved in the meantime. I would definitely like to attend an operations committee session, Damion! :)
@SLvanL , just commented on dr. Short Hair, see pato-ontology/pato#101!

**Comment by nlharris** [comment]
What is the status of this? Are we waiting for action from the ontology owner?

**Comment by kaiiam** [comment]
I believe @HajoRijgersberg is coming to the upcoming Jan 11th OBI meeting? Perhaps this can be discussed at that meeting. I would also like to use that opportunity to present about our proposed UO revamp see [this presentation](https://drive.google.com/file/d/1vM-BtKB28jPmags8lrAO-dnfSBjzmYtH/view?usp=sharing).

**Comment by ddooley** [comment]
Yes Hajo will be there, and I believe his colleague Jan Top.  I think they will take 10 min to describe OM and future possibilities.  So that and UO presentation will be productive.

**Comment by HajoRijgersberg** [comment]
Indeed! :)
Looking forward to meeting you all!

**Comment by kaiiam** [comment]
> Looking forward to meeting you all!

Yes @HajoRijgersberg you as well!

**Comment by HajoRijgersberg** [comment]
Dear people,
Because of a death I don't know if I'll be able to be at the meeting tomorrow. My apologies! Could we perhaps postpone the meeting for a week? I understand that that would be difficult. Or maybe more meetings will follow?
By the way, I don't know how to attend the meeting. Maybe someone can provide a link?
Best, Hajo

**Comment by jamesaoverton** [comment]
I’m very sorry to hear that. Yes we can postpone.

When we have the call we’ll use the OBI weekly call slot. The details are at the bottom of this page: http://obi-ontology.org/

**Comment by dr-shorthair** [comment]
Would be interested in attending too, but 12:00 Eastern == 04:00 local (AEST) so probably not.

**Comment by ramonawalls** [comment]
Perhaps the call could be recorded, or at least documented on github,
for those that cannot attend in person.
------------------------------------------------------
Ramona L. Walls, Ph.D.
Assistant Research Professor, Bio5 Institute, University of Arizona
Part-time artist (https://www.instagram.com/omnivoresgratitutude/)

**Comment by kaiiam** [comment]
I'm sorry to hear that @HajoRijgersberg, please don't feel obligated to join today.  

I presume the regular OBI meeting is still on for today?

Perhaps we can schedule another meeting to have the broader OM-QUDT-UO discussion with @dr-shorthair and @HajoRijgersberg? Usually the "best" (least horrible) time slot to cover AU/EU/NA (sorry it's late in Europe) is 

UTC | EST | AEDT | CET | PST
-- | -- | -- | -- | --
20:00:00| 3:00 pm |  7:00 am (next day) | 21:00 | 12:00 noon

If desired people can suggest dates (or alternative times) for such a meeting? If not perhaps just an email thread?

**Comment by jamesaoverton** [comment]
On the OBI call today we decided to go ahead with the presentation that Kai linked to above. Of course we didn't make any decisions, but at least OBI developers had a heads up on some of the issues. As suggested I tried to record the presentation, but I failed. I encourage everyone to look at Kai's slides for one possible approach, but he can review them whenever we do manage to have a call.

@kaiiam Could you please try to schedule another call? We can use the OBI slot again, but if we can find a better slot that would be great.

I think we should also move the discussion somewhere other than this GitHub issue.

**Comment by kaiiam** [comment]
Yes will do. Myself and or @ddooley can start an email thread to continue this conversation.

**Comment by dr-shorthair** [comment]
> start an email thread

I'd prefer to see conversations curated in GitHub issue(s).

**Comment by HajoRijgersberg** [comment]
Dear people,
Thanks for all your kind words! I am back now. The death was the grandfather of my wife who was living with us, in our home...
I'll check on your presentation soon, Kai. I am running behind in a lot of emails and work now! :)
21:00 CET is no problem for me. I'm an evening person! :)
Email thread or Github conversations is also alright with me!
Best, Hajo

**Comment by kaiiam** [comment]
@HajoRijgersberg our condolences, please take you time no rush on this just let us know when you're ready.

**Comment by HajoRijgersberg** [comment]
Thanks, yes I'm ready. Just running behind with a lot of work now, so that could be a reason for postponing things sometimes.
Looking forward to seeing/speaking/writing you all!

**Comment by nlharris** [comment]
What is the next step?

**Comment by kaiiam** [comment]
@nlharris thanks for weighing in. This issue has resulted the formation of an informal OBO units working group, we've had two meetings thus far and I will schedule a third soon. See the [shared drive folder](https://drive.google.com/drive/folders/1tAWTNofQ_0O5TUM-zfOxX_nYRQ-jS3ut?usp=sharing), and this [UO_revamp github repo](https://github.com/kaiiam/UO_revamp). Also see the `units` channel in the obo-community slack group.

Although the discussion participants include (but not limited to) @HajoRijgersberg, @dr-shorthair, @jamesaoverton and @zhengj2007, @cmungall, we'd like to try and keep this as an open process. @nlharris Let me know if you can have any suggestions about improving that.

**Comment by jamesaoverton** [comment]
I'm dropping the "new ontology" label, at least for now, because this is a distinct kind of issue.

**Comment by kaiiam** [comment]
Yes it's more likely going to be something like a merger of OM with UO/PATO and then mapping that merged system to QUDT/UCUM. I'll schedule our next call, perhaps we can pick this this discussion up further.

**Comment by kaiiam** [comment]
For anyone interested, our next OM/UO units harmonization working group meeting will be March 10th (19:00 UTC) (attend from [here](https://us04web.zoom.us/j/77874763613?pwd=bVMvNFBHNnJiTUZKNmM5MStrcUJQZz09)).

**Comment by ramonawalls** [comment]
Great to see this moving forward. Thanks all!

**Comment by kaiiam** [comment]
@mpsaloha wrote the following via email:

> Hi folks!
> I've been interacting a lot recently with more "earth-science" related semantics folks, and there is a strong sense of growing momentum in support of QUDT.  Can any of you quickly summarize or point me to some papers/ppts that compare/contrast the features of UO/OM/QUDT?
> thanks!
> Mark

You can find more information/links about our ongoing efforts in the "units" channel of the obo-community slack as well as this [OM-OBO Units Harmonization Working Group google drive folder](https://drive.google.com/drive/folders/1tAWTNofQ_0O5TUM-zfOxX_nYRQ-jS3ut?usp=sharing) (both of which I've added you @mpsaloha to. Also see our working [github repo](https://github.com/kaiiam/UO_revamp). Specifically see the [presentations folder](https://drive.google.com/drive/folders/1Y57ToDK3uhQrsjgy2IXGK1fTHdwLKwT0?usp=sharing) with some material from myself and @dr-shorthair. Perhaps a start toward your question but @mpsaloha I'm sure you have much more to tell us. I'd be great to have you joining our working group if you have time.

**Comment by ddooley** [comment]
A more extensive comparison paper was published in 2018: http://www.semantic-web-journal.net/system/files/swj1775.pdf "Comparison and evaluation of ontologies for units of measurement" - covers UO, OM and QUDT.

**Comment by dr-shorthair** [comment]
Though the statistics of the coverage of QUDT is now very out-of-date. the paper looked at QUDT v1 and there has been a *lot* of maintenance in the last two years.,

**Comment by HajoRijgersberg** [comment]
I'm having this idea now that UO/PATO and OM move towards each other, step by step, by including (inverse) properties, instances, etc. from each other.
In case UO/PATO will use non-opaque URIs, UO/PATO and OM could even resemble more.
Looking forward to further discussion next Wednesday! Thanx Kai, for organizing! :)

**Comment by nlharris** [comment]
What is the status of this?

**Comment by kaiiam** [comment]
Thanks for bringing this up again @nlharris. The long and short is a number of us including @jamesaoverton @HajoRijgersberg @dr-shorthair and others had a series of meetings which culminated in the creation of https://units-of-measurement.org/ (UOM). More details can be found in the [WSBO2021 presentation on UOM](https://www.youtube.com/watch?v=Rk_VDBCTiRY).

While the projects is mostly finished there remains some more work to be done: finalizing mappings to other unit systems, finish up definitions support of other languages etc. I'll be picking this up again once I have time to work on it again. The intention is to publish this work and I'll be writing the draft in the coming year. There is still room for contributions if anyone is interested. Please let us know. 

As for the original intention of this ticket, the above (UOM) work should sufficiently map OM units to the new UOM system (and to UO and others systems) so it should satisfy the original intent of getting OM units to work interoperably with OBO projects. There is still an open question regarding incorporating/mapping the non unit classes from OM e.g. the quantities such as [OM:Torque](http://www.ontology-of-units-of-measure.org/resource/om-2/Torque), which PATO would greatly benefit from the incorporation of. TBD if that ever gets traction.

**Comment by cmungall** [comment]
What are the actionable steps for OBO?

1. New issue: I think we need to file a new issue where we register UOM. This is an odd case as it won't have OBO purls but I think we should make the request and discuss on that issue
2. This issue: We need an action on the OM request submitted by @HajoRijgersberg
      - do you want to pursue this @HajoRijgersberg, given progress with UOM since the initial request was made? Our preference in OBO would be not have multiple overlapping ontologies for a domain, but if you want to register OM then we need to give it full consideration
      - if the OM developers no longer seek a namespace we can close this

**Comment by kaiiam** [comment]
Thanks @cmungall as for item 1. above do we intend to register UOM with OBO? My understanding was that we weren't but I'm happy to do so if we agree on it. @jamesaoverton thoughts? 

For point 2. @HajoRijgersberg and @SLvanL please let us know!

> Our preference in OBO would be not have multiple overlapping ontologies for a domain

Note that OBO already has UO for the domain so I think this is a special case here.

**Comment by nlharris** [comment]
Are we still waiting for action from the submitter?

**Comment by HajoRijgersberg** [comment]
> For point 2. @HajoRijgersberg and @SLvanL please let us know!

Sorry, I must have overlooked this request. In the mean time a lot of dialogues have taken place with the people involved in this thread (and more people). See the comment of Kai in this thread on Jan 27, that explains it clearly, I think.

**Comment by HajoRijgersberg** [comment]
> Are we still waiting for action from the submitter?

So I think not, but anyone, please correct me if I have understood anything incorrectly.

**Comment by kaiiam** [comment]
No was my understanding as well.

**Comment by HajoRijgersberg** [comment]
@ddooley and @cmungall, the new UOM (the revamped UO, with OM and other ontologies' influences) is/remains/will be the OBO units ontology. Indeed because the preference of OBO would be not have multiple overlapping ontologies for a domain, it was my perception that there is no need for OM. Moreover, we have analysed the differences and similarities between UO and OM, and see that there is great opportunity (in the future) to merge these two ontologies. UOM can be considered as the first step in that process.
Hope this is a clear answer? If not (or yes), please let me know! :)

**Comment by kaiiam** [comment]
I think that makes sense. OBO already has UO as the units ontology. UOM is a bridge between systems that isn't officially part of OBO. So I'd think that neither UOM or OM would officially be in OBO. 

In the future time permitting it would be great to bring in other parts of OM like their quantities/qualities into PATO or similar within OBO.

**Comment by nlharris** [comment]
Ok, I'm still a bit confused. Are there still any action items for this issue, or can it now be closed?

**Comment by cmungall** [comment]
I'm closing this as the original request is withdrawn - but I don't want to shut down further discussion. There is #units on the OBO slack and many of the participants of this discussion are over there, and issues can be raised in the relevant repos. There are still some complex issues to resolve such as such as continued support of UO vs use of UOM.
