### ISSUE TITLE
Versioning term identifiers

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1347]
@mcourtot wrote:
> I was trying to find the OBO deprecation policy at http://www.obofoundry.org/principles/fp-000-summary.html
> While we have the overall ID policy, we don't have anything specifically addressing the question of versioning of term identifiers - we don't version them because they're stable through time or get deprecated.
> Context is the ticket at https://github.com/EBISPOT/DUO/issues/89, but in general it'd be good to publish the deprecation policy somewhere (we had the OBI one derived from GO). Or is there already such a document online you could point me to?

@mellybelly agreed:
> Agree I have long wanted to improve term versioning. 
Perhaps something can be drawn from our community identifiers paper: 
https://journals.plos.org/plosbiology/article/figures?id=10.1371/journal.pbio.2001414
Such as figure 5 and related text. 
Add to current ID principle? Melanie, happy to help draft.

**Comment by matentzn** [comment]
@mcourtot @mellybelly 

Lets say we had a good uniform strategy for deprectation (we can make it the action item of this ticket to write this up) - what other facets of versioning are you thinking about? The identifiers themselves are versioned through the context (ontology, which is versioned) they appear in - so I am not sure what other action items might be hiding in this ticket here. Thanks for clarification :)

**Comment by mcourtot** [comment]
The request from https://github.com/EBISPOT/DUO/issues/89 was about an easy way to retrieve a specific version of a term. For example if you wanted to see the version of the DUO term http://purl.obolibrary.org/obo/DUO_0000007 in the release https://github.com/EBISPOT/DUO/releases/tag/v2017-10-16 that's not trivial.

**Comment by matentzn** [comment]
That would be indeed very difficult, but could be solved in tool level.. Basically you would need a tool like OLS that indexes all versions. Then you could provide an API where you could do a lookup like:

ebi.ols.ac.uk/api/term?id=DUO:0001?ontology-version=2020-08-10

The call would lookup the ontology with version IRI `http://....2020-08-10/duo.owl` and return the term from that version. I don't think its a bad idea, indeed, it would be amazing to do that.. however, so far, no tool I know can do that (maybe the bioportal API could?). You could propose it to Helen - it would be a major endeavour for OLS, but there is lots of movement at OLS, and maybe its not as infeasible as I think now..
This is about the only thing I can think of to solve this practically.. So more a

**Comment by balhoff** [comment]
It seems like retrieving a specific version of the term would be a feature provided by a terminology server, with inputs of the term IRI and the ontology version IRI. I guess I can't see how having a version-specific identifier for a particular term makes that any different, and seems like it would complicate use of the term greatly, especially for data integration. I seem to remember @alanruttenberg wrote something about this (downsides of versioned term IRIs) a while back, but I can't find it. Hopefully I'm not misrepresenting that!

I do think that it makes sense to record the version of the ontology(ies) in use at the time of annotation.

**Comment by matentzn** [comment]
Two people one.. :D

**Comment by nlharris** [comment]
Is more discussion required here or is the action item clear?

**Comment by matentzn** [comment]
Yes @mcourtot unless we misunderstood your ticket, I think this is beyond obo scope - this would be a ticket for a terminology server - or OLS.

**Comment by nlharris** [comment]
Can I close as Won't Do?
