### ISSUE TITLE
Check why som CC-BY images don't show up

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#135]
eg for po. I thought it was due to the use of https, but updating didn't change anything.

**Comment by mcourtot** [comment]
you seem to indicate it was due to http/https - I had updated po but didn't make difference. Was there something else? I had checked the build was run, so not sure what happened?

**Comment by cmungall** [comment]
Hard to say without seeing yr exact steps. So you remade the 
_config.yml?

**Comment by mcourtot** [comment]
Yes - I didn't notice the check in extract_metadata, so I had just updated
the md file but not re run the makefile.
