### ISSUE TITLE
Video Tutorial: Request an Ontology ID space

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1352]
See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1246 for discussion

**Comment by matentzn** [comment]
Please move to https://github.com/OBOAcademy/obook/issues

**Comment by nlharris** [comment]
@nicolevasilevsky can probably do that

**Comment by nicolevasilevsky** [comment]
done
