### ISSUE TITLE
Advertise James's Overton OBO Hour

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1354]
Mondays at 11:00 AM Eastern
See Slack (#general) for Zoom link

Add this to OBO calendar, and also maybe tweet as @OBOFoundry? Add to website, or is it too changeable for that?

(Tagging @jamesaoverton, @nicolevasilevsky)

**Comment by jamesaoverton** [comment]
I added this to the Google Calendar (I hope) and sent an email to obo-discuss. I don't really want to advertise on Twitter. If this experiment turns out well, we can add it to the website later. I don't want to overcommit.
