### ISSUE TITLE
Fixes to membership pages, drive from metadata

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1358]
[from obo ops call today]

http://obofoundry.org/docs/Membership

Only a fraction of names are hyperlinked

Many of the hyperlinks are dead (Alan, Simon)

Nicole's name is wrong

This page should be metadata driven. We should have github and/or orcids for everyone and hyperlink to these (people can link to their institute sites from orcid/gitub if they like)

**Comment by nicolevasilevsky** [comment]
I fixed my name :)

**Comment by nlharris** [comment]
Updating names: see #1278

**Comment by nlharris** [comment]
updates were done manually but i don't think the possibility of automating this has been explored yet.

**Comment by nlharris** [comment]
This is now automated, thanks to @cthoyt! 🎉
