### ISSUE TITLE
Discuss plans for OBO Metadata Editor

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1360]
@jannahastings and I have been developing a webapp to help users work with OBO registry files and OBO PURL configuration files. It provides three things:

1. a form for OBO registration requests
2. an editor for OBO registry files
3. an editor for OBO PURL configuration files

Anyone with a GitHub account can log in an use this system to create an issue or pull request. The primary design goal is to make this an optional layer on top of our existing GitHub workflows., so if this system breaks then we can always fall back to our existing GitHub workflows.

- https://editor.obolibrary.org
- https://github.com/jamesaoverton/purl-editor

## Details

1. OBO Foundry Ontology Registration Request: This form is based on the Google Form that the Editorial WG developed and the current GitHub issue template for requests. It has the benefits of both: a nice form with inline documentation and validation, which creates a GitHub issue.

2. OBO registry files consist of structured data in YAML format followed by unstructured data in Markdown format. The current workflow is to edit these in the generic GitHub web-based file editor, and run automated validation after changes are saved. Our new tool provides an editor with syntax highlighting, customized auto-complete, context sensitive documentation, and a "Validate" button that provides immediate feedback and highlights any errors in the YAML. Changes are then submitted as a Pull Request, which is validated again, and can be approved or rejected by OBO administrators.

3. OBO PURL configuration files are in YAML format. The current workflow is similar to the registry workflow, and the benefits of the new system are the same.

The system can edit existing files and create new ones, and it can use a previous New Ontology issue to fill out most of the details for registry files and PURL configuration files.

## Plans

- [ ] do some more debugging
- [ ] move the repository to the OBOFoundry GitHub organization
- [ ] rename the repository from `purl-editor` to something more accurate
- [ ] advertise to the Operations Committee and OBO Tools groups
- [ ] once things are working well, advertise to the wider OBO community, and update documentation to recommend this tool

**Comment by jamesaoverton** [comment]
Feedback and discussion from the Operations call 2020-11-17:

1. Name: This was originally just for editing PURL configs, so the repo is named "purl-editor". Now it also handles the registry, so I've been calling it "OBO Metadata Editor". I considered calling it "OBO Editor" but didn't want to conflict with the OBO-format editor used by many ontologies. On the Operations call today people suggested "OBO Metadata Tools" and "OBO Metadata Edit Page".

2. URL: I'm currently using `http://editor.obolibrary.org` but the URL should reflect whatever name we choose.

3. @matentzn asked about having the registration form point to the OWL file (product). I'm  not opposed to this, but my two concerns are:
    A. that a project my request registration before they have an OWL file
    B. we want to keep the number of fields small

4. IDSPACE: following on discussions today about restricting short IDSPACEs, we can make the validation of this field more strict.

Please add anything I missed or any other comments or questions that you may have!

**Comment by matentzn** [comment]
To be honest, I think editor is simple enough to train people to use it. Thats just my 2 cents.
