### ISSUE TITLE
Implement schema for usages

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1371]
Issue #1179 asks to add usage information to the ontology detail pages. Before we can do that, we need to standardize that information. #1008 points out that there are different formats in the registry right now. The current schema just allows the `usages` key without any constraint:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/schema/registry_schema.json#L417

So the steps are:

- [ ] implement a JSON Schema for usages based on @beckyjackson's suggestion in #1008 
- [ ] update all registry entries to conform to the new schema
- [ ] update [ontology_detail.html](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_layouts/ontology_detail.html) layout to add the usages #1179

**Comment by matentzn** [comment]
Good one.

I can help with fixing the metadata if needed.
