### ISSUE TITLE
Provide OBO community with guidelines/options in the face of new Travis plans

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1373]
Most (all?) OBO ontologies rely on travis for checking PRs, and many ontologies have entirely PR-based development, with even trusted editors making PRs rather than committing to master.

This is more difficult with new billing:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

See some community thoughts on this here:

https://twitter.com/mxstbr/status/1323225573683060736

This is not good for us as so many ontologies are dependent on Travis for development. We need to provide advice, and perhaps change odk setup (cc @matentzn ). This of course holds for our software projects too.

We had some discussion on slack:
https://obo-communitygroup.slack.com/archives/C01B6MQCDLN/p1604346019009200

@deepakunni3 wrote some guidelines on migrating from travis org to travis com but I'm not sure that helps here
https://docs.google.com/document/d/1LDx2kRFSPWnpMS21Eh2IJU0it6q8vQj7NSMnfGA2fdE/edit

For some projects I'm involved with we have switched to github actions e.g https://github.com/biolink/biolinkml/tree/master/.github/workflows

But GH may also impose unclear limits

The current status as I understand is:

 - Travis now has a limit on credits
 - This may be a lifetime limit, or a periodic limit, with automatic topping up
 - It may be possible to apply for more credits if you are open source, but it's not clear how easy this is, if it's a full solution

We should have a centralized place for providing guidance and sharing strategies

Not every group need have the same strategy. Some projects like GO may have the resources to switch to a paid plan (start at $150/m). This may bring some advantages, e.g. parallel builds, better machines for faster builds. Some projects like GO may hit the credit limit faster due to large numbers of daily PRs (and in fact we have hit this limit). cc @balhoff @kltm 

It's not clear what ontologies would be next affected.

**Comment by nlharris** [comment]
Ugh.

Should we add this to the OBO Operations agenda for tomorrow?

**Comment by kltm** [comment]
I see a few paths:

1. Tie things to a beefy central Jenkins (or similar) instance. Pros: we can use real machines with real memory and properly control and scale what we do. Cons: harder to deal with, less independent, other issues (@matentzn )
2. Pay for Travis. Pros: easy and what we're doing now. Cons: a little expensive; possibly v/expensive when doing many projects (it adds up).
3. Migrate to a different platform. Pros: can maybe squeeze into another system's free tier; might even integrate better. Cons: migration cost; possibly just deferring the problem and we're back to 1 or 2 in a few months or years.

**Comment by nicolevasilevsky** [comment]
@nlharris I added this to the agenda

**Comment by dosumis** [comment]
We're moving VFB to GitHub Actions.  I believe @matentzn has been looking into this for ODK.

**Comment by matentzn** [comment]
I am wondering now what will happen if/when the same fate will befall GitHub actions. There is another option which could work - migrate all ontologies to separate orgs (the Travis limits are imposed on an org by org basis). Its ridiculous, and will make managing teams harder, but it may be a last resort. Obviously I am against that option, just wanted to put it out there.

If we go for sets solution 1, then I would only advocate that if there is some kind of formal maintenance plan associated with that.. It would be a real pain if we moved all our pipelines to some server, only then, after 3 years, to be told that "we don't have money to support this" anymore. Is there some kind of way to really get access for a robust OBO server with 256 GB memory (to run jobs in parallel), 10 TB disk and some minimal support  if stuff breaks and needs restarting? I would like that!

**Comment by balhoff** [comment]
I set up a replacement QC check for GO using GitHub Actions: https://github.com/geneontology/go-ontology/blob/master/.github/workflows/qc.yml

**Comment by cmungall** [comment]
@balhoff just showed me how to see allocations for an org, e.g.

https://travis-ci.org/github/obophenotype?tab=insights

![image](https://user-images.githubusercontent.com/50745/100800553-9c6a5200-33db-11eb-8d85-57d6a87a432b.png)

As I understand 508 minutes = 5080 credits of a total allocation of 10k.

**Comment by balhoff** [comment]
To see credits:

Click on your user icon in top right, select Settings , then down the left find your organization and  click on it,  then click Plan tab.

**Comment by cmungall** [comment]
From @deepak

 travis-ci.org will be shut down on Dec 31, 2020.
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

See
https://docs.google.com/document/d/1LDx2kRFSPWnpMS21Eh2IJU0it6q8vQj7NSMnfGA2fdE/edit

For notes on transitioning from org to com

(AFAICT this is orthogonal to plans, just an annoying additional step)

**Comment by matentzn** [comment]
Another thing that springs to mind is to optimise what is tested a bit more -> some of our pipelines run an entire test build, which may not be feasible anymore. So to start with, we should make sure that (which may be the case, but checking), no test pipeline refreshes imports - this takes up a huge number of minutes of our contingents. Another thing is that we should probably create a list of repos with active travis jobs. Which other orgs come to mind to check:

@balhoff walked me through setting up an ODK github actions test - its trivial. Dare I say, even easier than travis. So if someone could find out what the actual limits for free tier are, that would help, and I could start migrating some pipelines to GitHub actions and add them to ODK.

**Comment by mah11** [comment]
> if someone could find out what the actual limits for free tier are

https://github.com/pricing says 2000 Actions minutes/month

**Comment by matentzn** [comment]
I am wondering though per what.. per organisation? per repo? 2000 minutes/month/repo could actually work for us, especially if we have an easy way to - in a busy month - being able to switch to travis quickly.

**Comment by mah11** [comment]
For pombase I see our total at the organization level (it seems to need admin access so pombase is the only organization I can check).

**Comment by nicolevasilevsky** [comment]
From @matentzn (I am posting on his behalf):
Hey all, for this with problems on the Travis quota front: it took me about 4 minutes to move Uberon from travis to github actions. This is how its done:

1. add a folder .github/workflows in the top level of your github repo
2. Copy the Uberon check, which is a copy of the GO check (thanks so much @Jim Balhoff for figuring this out for us!) into that directory
3. Go to your .travis.yml file (top level of repo, MP example) and check the script section (in MP, that would be cd src/ontology && sh run.sh make test) and adjust the “steps” section in the qc.yml file accordingly (ex: run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' test),. Important difference: you dont need sh.run.sh anymore because the test is run inside ODK as a whole! So for other set ups (like HP) that have some tests in, some tests outside ODK, I recommend adding more than one qc.yml files for now, unless someone has a better idea!
4. commit the test
5. Next time you create a pull request or commit something, the test will be run and send you some nice email.
6. IMPORTANT: Now you can deactive your travis checks: Go to your travis site (example), click on “More options-->Settings” and deactive “Build pushed branches” and “Build pushed pull requests” like so:  

![image](https://user-images.githubusercontent.com/6722114/105561410-7d958700-5ccb-11eb-9812-5707792e6816.png)

**Comment by nlharris** [comment]
I believe this info was communicated to the OBO community -- is there anything else to be done? Should this be added to the documentation somewhere?

**Comment by matentzn** [comment]
Its fine, there are no more action items right now. ODK now has the option to generate the gh actions workflows automatically. So I would say close.
