### ISSUE TITLE
New Ontology Request: DWCOBO

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#1390]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Darwin Core for OBO

## Requested ID space
DWCOBO

The current plan is not to release a singe dwcobo.owl file, but rather to release two files: dwcobo-terms.owl and dwcobo-iri.owl, corresponding to DwC's RDF code for data and object properties, respectively.

## Ontology location
repo: https://github.com/BiodiversityOntologies/dwcobo

There are two ontologies that convert DwC as RDF to OWL, one for each DwC namespace.

The ontologies are currently at https://raw.githubusercontent.com/BiodiversityOntologies/dwcobo/master/src/ontology/dwcobo-terms.owl and https://raw.githubusercontent.com/BiodiversityOntologies/dwcobo/master/src/ontology/dwcobo-iri.owlhttps://raw.githubusercontent.com/BiodiversityOntologies/dwcobo/master/src/ontology/dwcobo-iri.owl (in the src directory), but when I am ready to do a release, the latest version will be stored in the root directory of the repo. 

## Contact person
Name: Ramona Walls
Email address: rlwalls2008@gmail.com
GitHub username: ramonawalls

## Issue tracker
https://github.com/BiodiversityOntologies/dwcobo/issues

## Ontology license

- [ ] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ x] Other: *please specify*

The Intention is to make the ontology and all code CC0, but I am waiting for information about the license of Darwin Core.

## Available ontology formats
OWL, OBO upon request, but I don't know if anyone needs the OBO version.

## What domain is the ontology intended to cover?
Biodiversity occurrences and events.

## Related OBO Foundry ontologies
https://github.com/BiodiversityOntologies/bco

## Intended use/related projects
The first use case for this ontology is to modularize the use of DwC terms in BCO. However, I expect that other ontologies will want to import DwC terms, and this will provide a standardized way of doing so.

## Data source
DwC as RDF comes from https://github.com/tdwg/rs.tdwg.org. These properties are widely used in many data sources, including gbif.org

## Additional comments or remarks
I have created initial versions of the ontologies, but there are still a few issues to work out. Please see a full explanation of how the ontologies were created  and what still needs to be done at https://github.com/BiodiversityOntologies/dwcobo/blob/master/README.md

I am creating these ontologies based on known use cases for BCO, but I am open to different formats and suggestions based on other use cases.  My goal was to create OWL files that stay as close as possible to the original DwC RDF while supporting reasoning that is consistent with what is already specified in DwC. Any additional inferences (e.g., equivalence between DwC classes and OBO ontology classes) is outside the scope of these ontologies and lives in places like BCO.

**Comment by nlharris** [comment]
As requested, copying the discussion from obo-discuss:

Hilmar wrote:
> You’re probably familiar with DarwinCore-SW, which has been published a few year ago:
http://www.semantic-web-journal.net/content/darwin-sw-darwin-core-based-terms-expressing-biodiversity-data-rdf-1
Can you say how this effort would relate to or build on that?

Ramona responded:
> Good question, Hilmar. DarwinCore-SW is more comparable to BCO, in that it models the relationships among the Darwin Core classes. A key difference  between dwc-sw and bco is that bco fits within the OBO Foundry framework and is rooted in BFO. Because BCO follows OBO Foundry best and common practices, it is easily integrated with other OBO Foundry ontologies.
The new ontologies I am proposing are semantically light, and just provide an OWL representation of the DwC as RDF. They are slightly more semantically rich than dwc as rdf, because I have chosen to transform the DwC grouping classes into actual domains for the dwc properties. I'm happy to hear feedback about this idea.

**Comment by nlharris** [comment]
Chris wrote:

It feels a bit outside the scope of OBO. But I like your idea of making BCO the OBO-ified artefact, and have mappings to DWC (as well as MIxS, NEON, IGSN/Sesar/etc?).

I think your richer version of DWC is useful, but it still feels outside the scope of OBO:

 - I don't think the IRIs are correctly formed, is your intent to reuse DWC ones, or to make a new namespace in OBO
 - A lot of the terms already appear in existing OBO ontologies: dwc:behavior, dwc:country, dwc:habitat, dwc:lifeStage, dwc:Dataset
 - A lot of terms appear to conflict, but represent different concepts than how they are currently used by members of the OBO community; e.g. dwc:pathway, dwc:class
 - The modeling seems in conflict with OBO modeling - e.g. dataset is represented as an individual, not a class; there are duplicate IRIs for all concepts, with datatype and object property versions

I fully support the goals of making a semantically richer DWC data dictionary (we both want to do a similar thing for MIxS, along with others like Jie Zheng). But I'm not sure what is gained by registering this product with OBO and making parallel OBO PURLs? Ideally your richer representation could be folded back into the main DWC, but absent that do you lose anything by registering on say w3id.org and submitting to bioportal? Also is there not a danger in now having *four* URIs for each DWC property ({obo,dwc} x {OP,DP})?

I don't mean to shut this down, I think there is a clear need for OBO-adjacent efforts such as providing semantically enhanced data dictionaries, and OBO provides a lot of the useful technology for doing this, there is a legitimate discussion about extending OBO vs creating a parallel infrastructure (an analogous situation exists for conversions of databases into "ontologies" and knowledge graphs).

I think it would be useful to 'clone' OBO for a broader registry of 'semantic artefacts' that are OBO-adjacent. This would include schemas and data dictionaries in the environmental/diversity sciences (MIxS, NEON, IGSN/Sesar, DWC). A lot of the same technology could be leveraged (e.g. cloned OLS/BioPortal/OntoBee instances - or even overloading the existing ones).

**Comment by nlharris** [comment]
Ramona responded:
> The intention is reuse the dwc IDs for each term, not create new ones. I was only looking for an OBO Foundry IRI for the ontology artefacts. Yes, w3c would work, and perhaps that is a better idea! I guess I just thought first of what I am most familiar with. In fact, my hope of being able to use OBO tooling with these ontologies wouldn't be so simple anyway, given that the term IRIs would not be obo-formatted PURLs. Also, the conflicts with OBO modeling that you point out (and others that you did not point out), make it far from simple to just plug in DwC to the suite of OBO ontologies. I like your idea of nurturing obo-adjacent artefacts.
> 
> I am not sure about the prospects of this OWL representation being folded back into TDWG. Even if it does come to pass, it will likely take years, and we need to have it functional for our BCO-based projects in the short term. I have filed an issue on the DwC RDF tracker (https://github.com/tdwg/rs.tdwg.org/issues/67) and hope to have some discussion there.

**Comment by ramonawalls** [comment]
Thanks for copying over the discussion @nlharris. I will close this request in favor of using something like w3ids or housing the module within the BCO namespace.
