### ISSUE TITLE
Missing trackers 2020

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1393]
- [x]	[ERO tracker](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/909): 'tracker' is a recommended property
- [x]	KISAO tracker: 'tracker' is a recommended property
- [x]	[MS tracker](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/976): 'tracker' is a recommended property
- [x]	SWO tracker: 'tracker' is a recommended property
- [x]	VT tracker: 'tracker' is a recommended property
- [x]	ZFS tracker: 'tracker' is a recommended property

**Comment by matentzn** [comment]
@ybradford for ZFS FYI

**Comment by matentzn** [comment]
Action items:
- [ ] Contact KISAO to ask for tracker
- [ ] Set up ZFS repo (Nico and @ybradford)
- [ ] Decide what to do if an ontology does not want to provide a tracker (I would like trackers to be mandatory)

**Comment by matentzn** [comment]
We have decided in the OBO foundry meeting of Jan 12 2020 that every ontology _must_ provide a tracker and that this check will be part of the metadata. 

@gambardella Would you be able to provide us with a public issue tracker for KISAO (some place where users can ask for new terms etc)?

**Comment by gambardella** [comment]
Sure. https://sourceforge.net/p/kisao/feature-requests/

**Comment by matentzn** [comment]
Thank you!

**Comment by matentzn** [comment]
This has been completed!
