### ISSUE TITLE
New 'mandatory tracker' requirement

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#1415]
By recent Ops meeting vote, it has been decided that having an issue tracker should be mandatory. While a number of principles mention trackers, none state that these are required (or even recommended). To be decided: (a) Create a new principle; or (b) Insert into an appropriate existing principle. If (b), which one?

**Comment by nataled** [comment]
Related to #960

**Comment by matentzn** [comment]
I would say responsiveness is the right place for the tracker stuff to go..

**Comment by matentzn** [comment]
Or http://obofoundry.org/principles/fp-010-collaboration.html

**Comment by nataled** [comment]
Responsiveness is what we decided in the EWG meeting. It actually was created many years ago for exactly this purpose.

**Comment by nicolevasilevsky** [comment]
we discussed possibly putting it under collaboration too though.

**Comment by nicolevasilevsky** [comment]
@nataled I am working on this now. From what I can see, there isn't already an existing 'responsiveness' principle, so I am creating one.

**Comment by nataled** [comment]
@nicolevasilevsky correct. The "new" principle was not previously stand-alone, as it was extracted during the clean-up phase for the other principles. 

As it might get confusing having two tickets for pretty much the same issue, I decided to close this one in favor of #960 (which is concerned with the wording of principle 20).
