### ISSUE TITLE
CDNO is not in OBO Foundry yet

### ISSUE THREAD

**Issue by LilyAndres** [OBOFoundry/OBOFoundry.github.io#1428]
Dear OBO team,

Thanks a lot for helping me to merge the CDNO md and yaml files on the 9th of February, I really appreciate your help and effort. 
I'm creating this issue to ask when do you think it will be in OBO foundry? I can't see it the OBO page or in Ontobee. 
Is there any error?

I hope you can help me with this please. 

Cheers.

**Comment by nlharris** [comment]
See #1369 for the new ontology request for CDNO.

**Comment by matentzn** [comment]
Once accepted, it could still take a few weeks to for the changes to trickle through the relevant systems.. Your purls should work already though! Can you chase this again around end of February? If something is more urgent, ping me on on slack and I can see if I push this a bit faster.

**Comment by yongqunh** [comment]
It appears that it is still not on the OBO Foundry page. I am not sure why. 
For Ontobee, I have manually uploaded CDNO to Ontobee: 
http://www.ontobee.org/ontology/CDNO
It appears fine with me. Please check out.

**Comment by LilyAndres** [comment]
Thanks a lot @yongqunh I saw it earlier and it was working but I can't see the terms now.
@matentzn thanks, the [purl](http://purl.obolibrary.org/obo/CDNO_0000001) for *'dietary nutritional component'* for example, takes me to a ***Term not found***

I think this is a bit urgent :( I need to submit my thesis at the end of this month so it could be great if we get it in the OBO foundry sooner... I'm sorry for the inconvenience, I think I read somewhere that it could take 20 min to be in the OBO foundry but I probably misunderstood the context.

**Comment by matentzn** [comment]
@yongqunh It does not seem that ontobee picked up CDNO correctly - it seems empty! 
http://www.ontobee.org/ontology/CDNO?iri=http://purl.obolibrary.org/obo/CDNO_0200037

**Comment by matentzn** [comment]
Once https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1430 is merged, it should take about 1 day.

**Comment by LilyAndres** [comment]
Great, thanks a lot. I hope it works.

**Comment by yongqunh** [comment]
Happy to help out. Let's see what will happen after the CDNO shows up on Foundry pages.

**Comment by matentzn** [comment]
It is in OBO foundry now; I will close the issue here, as that's all we can do here! 
http://obofoundry.org/ontology/cdno.html
