### ISSUE TITLE
Obsolete OMIABIS

### ISSUE THREAD

**Issue by mbrochhausen** [OBOFoundry/OBOFoundry.github.io#1442]
The namespace is now owned by OBIB.

**Comment by zhengj2007** [comment]
OBIB IDs will be assigned to OMIABIS terms. OBIB would like to keep the OMIABIS IDs in the OBIB indicate the provenance. Any annotation property is recommended to use? Is 'definition source' a good candidate?

**Comment by cmungall** [comment]
@zhengj2007 - this seems like a separate ticket. I think this ticket can be acted on immediately

**Comment by mbrochhausen** [comment]
If that works for Jie, I am fine with moving forward.
