### ISSUE TITLE
labo ontology cannot be loaded

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1444]
The dashboard shows that the labo ontology falls.

When I try and load the OWL I get:

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/iao/iao-edit.owl> Cause: http://purl.oclc.org/obo/iao/iao-edit.owl
```

It looks like there are various issues with the imports. I recommend only using **registered OBO ontology PURLs** in imports. Don't use edit files. Also consider merging imports on release.

```
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/labo.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/2020-02-06/labo.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/hado.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ogms.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/opmi.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/pdro.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/bfo/2019-08-26/bfo.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/iao-edit.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/obi/obi_core.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/obi/dev/obi-edit.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/omiabis/dev/omiabis.owl"/>
        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ro/core-subset.owl"/>
```

 - [ ] no such ontology as hado
 - [ ] iao-edit - replace with iao
 - [ ] why import both obi_core and obo-edit? just choose core or main
 - [ ] omiabis is to be obsoleted see #1442.

**Comment by nlharris** [comment]
@pfabry do you want to move this ticket to your tracker?

**Comment by matentzn** [comment]
I tried to make tickets at the respective trackers whenever I came across - not sure whether we should keep open at obo foundry level as there is no action item for us. See https://github.com/orgs/OBOFoundry/projects/6

**Comment by pfabry** [comment]
Hi, 
yes I missed the issue made by @matentzn. My mistake.

Concerning some of the points made by @cmungall : 
- hado is an "in house" ontology for which we haven't made yet a registration request to OBO. What should be the proper course of actions in such a case, as we would like to keep the modular structure of our ontologies ?
- Should the merged version of labo (available in the \merged directory) be the main release product ? That would solve the main issue while I fix the imports.

**Comment by matentzn** [comment]
@pfabry The release version of labo should come with merged imports (so call "full" release, see [here](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required)). It is very good practice to provide a [base](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-1-base-required) release as well.

**Comment by matentzn** [comment]
The issue has been fixed and I have also refreshed the dashboard.

**Comment by matentzn** [comment]
http://dashboard.obofoundry.org/dashboard/index.html

Thank you @pfabry
