### ISSUE TITLE
Set up monitoring service for obofoundry.org

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#145]
http://obofoundry.org/ is periodically unreachable (though http://obofoundry.github.io is usually fine)

It would be good to know when this is happening (even if we don't always you how to fix)

Choices: munin, uptimerobot, ...

cc @kltm

**Comment by kltm** [comment]
My uptimerobot checks: http://obofoundry.org, which is not really showing any downtime of worth. I believe we /might/ also have nagios or something else pointed at it. I'll add you to the uptimerobot notifications.

That said, at least for the uptimerobot, it's checking whether it can get a good response, not necessarily what's there. If you could suggest a bit of text, we could change that. As well, we could add something more invasive and unit-testy to Jenkins.

Another possibility, which would be good to confirm, is that it's not odd things getting cached randomly in your computer, which has happened before.

**Comment by kltm** [comment]
I can confirm a strangely long contact period from LBL right now.

**Comment by kltm** [comment]
DNS is resolving fine. Cannot get at:
 54.83.197.87
 ec2-54-83-197-87.compute-1.amazonaws.com

**Comment by cmungall** [comment]
Happening again

good to get confirmation from outside LBL

**Comment by kltm** [comment]
I don't think it ever stopped--I periodically checked from different locations over the weekend. I've added this to the todo for the week. In the meantime, you can use cell tethering or I can give you an account on an external machine.

**Comment by cmungall** [comment]
What's the best system for transparent monitoring (should be a dashboard any obo admin can see)?
