### ISSUE TITLE
New Ontology Request: GOMBO

### ISSUE THREAD

**Issue by BridgetSquidget** [OBOFoundry/OBOFoundry.github.io#1451]
## Ontology title

General Ontology of Marine Bioluminescent Organs (GOMBO)

## Requested ID space

gombo

## Ontology location

[https://github.com/BridgetSquidget/ceph_photophore_ontology](url)

## Contact person

Name: Bridget Vincent	
Email address: bridget.vincent@lifesci.ucsb.edu
GitHub username: @BridgetSquidget

## Issue tracker

[https://github.com/BridgetSquidget/ceph_photophore_ontology/issues](url)

## Ontology license

- [ ] CC0 (public domain)
- [ X ] CC-BY version 4
- [ ] Other: *please specify*

## Available ontology formats

OWL-RDF/XML

## What domain is the ontology intended to cover?

This ontology is intended to cover structures forming and supporting bioluminescent tissues in marine taxa. Currently the ontology covers structures found in cephalopods, but will soon include other organisms such as ostracods and fish. We are now gathering information about ostracod light organs to add to this ontology

## Related OBO Foundry ontologies

We included cross references to other ontologies (some listed below) who already had well-referenced terms that were necessary to include in our ontology.
UBERON, GO, PLANA, XAO, SPD, NCIT, OGI, CHEBI

## Intended use/related projects

This ontology was formed to standardize the definitions of various structures of photophores whose definitions have changed over time. We used this to inform our ancestral state reconstruction analysis to estimate the number of times photophores originated in cephalopods. We intend to continue to use this ontology for other studies in the future and to standardize additional terms in other marine taxa whose definitions and uses have changed over time. It is our hope that this will aid researchers in better understanding how terms are used in various studies and ensure both easier communication and reproducibility in future projects.

## Data source

Terms and definitions for this ontology came from previously published literature.

## Additional comments or remarks

In the ontology, original terms have a “biolum” IRI. This is just a placeholder since we needed something to start with—this will be replaced with the final prefix for this ontology.

**Comment by pbuttigieg** [comment]
>Ontology location
> https://github.com/BridgetSquidget/ceph_photophore_ontology

>Issue tracker
> https://github.com/BridgetSquidget/ceph_photophore_ontology/issues

The actual URLs behind these point to https://github.com/OBOFoundry/OBOFoundry.github.io/issues/url 

Going here (https://github.com/BridgetSquidget/ceph_photophore_ontology) I see three files including `
gombo_v1.owx` which seems to be the ontology file. 

There are no imports or reuse of existing terms, the object properties seem to come from web protege and don't all resolve (e.g. http://webprotege.stanford.edu/RaoxlSiBSPoKaKRl2VCg6M) and I can't seem to find many actual semantics/definitions. [Some content](https://github.com/BridgetSquidget/ceph_photophore_ontology/blob/7c170f6bbc0b6ea22cb4b47e9dae5991fd5bb439/gombo_v1.owx#L3269-L3277) exists like :

```
<AnnotationAssertion>
        <AnnotationProperty IRI="http://webprotege.stanford.edu/RCSW6Ewn8eVSfHJWg6WMRbB"/>
        <IRI>http://purl.obolibrary.org/obo/BIOLUM_0000076</IRI>
        <Literal>The core is an accessory tissue of the axial complex, one of the three subregions of the proximal cup of the photophore organ. It consists of a junctional area between the distal cap region and the proximal cup region of the photophore. Three cell types are present in this tissue: the core cells, junctional cells, and torus cells. The core serves as a way to connect the different regions of the photophore. [1]</Literal>
    </AnnotationAssertion>
    <AnnotationAssertion>
        <AnnotationProperty IRI="http://www.geneontology.org/formats/oboInOwl#created_by"/>
        <IRI>http://purl.obolibrary.org/obo/BIOLUM_0000076</IRI>
        <Literal>clarabourguignon</Literal>
    </AnnotationAssertion>
```

There seem to be OBO like relations, but not with BFO or RO IRIs (see [these](https://github.com/BridgetSquidget/ceph_photophore_ontology/blob/7c170f6bbc0b6ea22cb4b47e9dae5991fd5bb439/gombo_v1.owx#L3874-L3899), for example)

>Data source
Terms and definitions for this ontology came from previously published literature.

I don't see any use of `database_cross_reference` or other properties to link to this literature. Is there another way you track this?

@BridgetSquidget are we looking at the right file?

**Comment by BridgetSquidget** [comment]
@pbuttigieg Thanks so much for pointing out these issues! It seems like there's a problem with the exported file since it seems like certain elements weren't included in the file (like imported terms). We'll look into this and figure out where the problem is and resubmit.

**Comment by alanruttenberg** [comment]
Why are you minting new IDs instead of MIREOTing the appropriate Cell
Ontology terms? Seems to be the same thing with molecular components (GO)
and organs, regions and tissues (Uberon).

**Comment by zhengj2007** [comment]
@BridgetSquidget Any progress on it? Do you need any help?

> @pbuttigieg Thanks so much for pointing out these issues! It seems like there's a problem with the exported file since it seems like certain elements weren't included in the file (like imported terms). We'll look into this and figure out where the problem is and resubmit.

**Comment by matentzn** [comment]
Hey @BridgetSquidget! Aside from the above comments, could you please fill in the following metadata record which will be used by the OBO Foundry website? Note that the values shown are just examples, for example yourfourletterid could be something like aism, cohm, mondo (it does not have to be four letters). your_domain_like_for_example_anatomy could be simply anatomy, and the license should be whatever your actual license is. An example can be found here, but you really only need to fill in the metadata mentioned here. You can copy the below, and make a new comment with the correct information pertaining to your ontology. Thank you!

```
id: gombo
title: The Title Of Your Ontology
contact:
  email: email@example.com
  label: Your Name
description: Some one sentence description of your ontology.
domain: anatomy
homepage: https://github.com/YOURORG/your_repo
products:
  - id: yourfourletterid.owl
  - id: yourfourletterid.obo
dependencies:
  - id: ro
  - id: otheroboontology
tracker: https://github.com/YOURORG/your_repo/issues
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: http://website.of.the.project.using.my.ontology.com
    description: A short description how the project above is using my ontology
```

**Comment by zhengj2007** [comment]
Discussed on OBO operations 2021-06-29 call.

@BridgetSquidget 
Could you please fill in the metadata record that @matentzn mentioned in his comments on April 20? Thanks!

**Comment by nlharris** [comment]
Just noting that we are still waiting for a response from @BridgetSquidget

**Comment by matentzn** [comment]
@BridgetSquidget would you be able to update us on GOMBO please?

**Comment by BridgetSquidget** [comment]
@matentzn Sorry for the delay! We think we fixed the formatting issue and are going through to check some details. We will submit in the next two weeks and will fill out the metadata form. Thank you!

**Comment by BridgetSquidget** [comment]
@matentzn We've added the updated ontology here: https://github.com/BridgetSquidget/gombo/blob/main/gombo_v1.owx
This process has been quite a learning experience but I think we fixed the formatting issue. Thanks so much for your patience!

**Comment by alanruttenberg** [comment]
The version of the license does matter. They are different licenses. 

On October 13, 2021 4:24:53 AM EDT, Nico Matentzoglu ***@***.***> wrote:
***@***.*** thanks,
>
>- I changed your license label to CC-BY (the v4 is not required).
>- You still need to provide the ontology in RDFXML (not OWLXML)
>- You are still missing a bunch of things as per automated checks:
>https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html
>
>You can click on the name of the check, and then "this check is tested automatically" to find out what is needed to fix these!
>
>Thank you!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1451#issuecomment-942055802
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lschriml** [comment]
@BridgetSquidget -- following up on the previous correspondence. 
   Can you share here the status of your updates ? 

Cheers,
Lynn

**Comment by matentzn** [comment]
Due to inactivity, we are closing this issue. @BridgetSquidget we welcome you to re-open this issue when you are ready!

Thank you for your submission and we hope to hear from you again.
