### ISSUE TITLE
Proposal for changing the register my ontology ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1457]
I know people should read it, but from my short OBO Foundry experience, no one really reads (deeply absorbs) the instructions for ontology registration. I would like to suggest the following (and volunteer for doing it, if so the committee supports the idea):

We take the checklist:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md

1) We turn it into a simple Github issue checklist (I love how ROBOT does this in pull requests). Think: 
- [ ] All the root terms in my ontology have definitions
- [ ] For every term in my ontology, I checked whether another OBO foundry ontology has it. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [ ] My ontology file (OWL) is in RDFXML and provides a license annotation
- [ ] Etc etc
2) We require the submitter to check those boxes before the review request is considered.

Let me know what you think, happy to take this on, but only if there is wide agreement.

**Comment by nlharris** [comment]
@matentzn any update on this? (no pressure! just wondering)

**Comment by mellybelly** [comment]
I love the idea, but just wondering about how we decide what rules need to be satisfied for inclusion/submission. For example, are we now requiring that all ontology terms must be reused via URI? while that might be recommended best practice it is not currently happening across a number of current and newly proposed OBO ontologies. Similarly, HPO would fail if a new request was made because we use a custom open license. 

Maybe not this ticket, as this is about how to do the registration, but i think we need to work on the governance for inclusion/exclusion into the obo library for the checklist itself.

**Comment by matentzn** [comment]
What I wanted with this ticket would not go beyond what has already been decided for dashboard criteria. I guess what I really want, and this is not even covered by this ticket, is for people to think first, read these criteria, consider the real philosophy behind OBO, do all that is humanly possible to contribute to upstream to existing ontologies and only as a last resort build their own.

**Comment by matentzn** [comment]
- [ ] Open action items: Vote.

👍 : We add the checklist to the ISSUE template
👎 : We don't add the checklist

**Comment by nlharris** [comment]
How many votes are you hoping for?

**Comment by matentzn** [comment]
I think this is pretty clearly a go. 4 Votes! Awesome! Next action item is to collect the checkbox items. 

- [ ] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML
- [ ] All the root terms in my ontology have definitions using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property
 - [ ] For every term in my ontology, I checked whether another OBO foundry ontology has it. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
 - [ ] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
 - [ ] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
 - [ ] There is no other ontology in the OBO foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.

... More suggestions welcome! Maybe editors call if time?

**Comment by cthoyt** [comment]
- [ ] "I have honestly answered these questions to the best of my ability"

**Comment by nlharris** [comment]
> All the root terms in my ontology have definitions using the IAO:0000115 property

It was suggested that "root" isn't the best term here. "Highest-level"?

**Comment by nlharris** [comment]
>  There is no other ontology in the OBO foundry which would be an appropriate place for my terms.

This is key; let's make it the first item on the list.
