### ISSUE TITLE
context.jsonld is invalid jsonld

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1476]
http://obofoundry.github.io/registry/context.jsonld

[Check](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22owl%22%3A%22http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%22%2C%22xsd%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%22%2C%22dc%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22dce%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%22%2C%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F1.1%2F%22%2C%22dcat%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%22%2C%22faldo%22%3A%22http%3A%2F%2Fbiohackathon.org%2Fresource%2Ffaldo%23%22%2C%22foaf%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%22%2C%22oa%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Foa%23%22%2C%22idot%22%3A%22http%3A%2F%2Fidentifiers.org%2F%22%2C%22void%22%3A%22http%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%22%2C%22doap%22%3A%22http%3A%2F%2Fusefulinc.com%2Fns%2Fdoap%23%22%2C%22pav%22%3A%22http%3A%2F%2Fpurl.org%2Fpav%2F%22%2C%22schemaorg%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22disco%22%3A%22http%3A%2F%2Frdf-vocabulary.ddialliance.org%2Fdiscovery%23%22%2C%22obofmd%22%3A%22http%3A%2F%2Fobofoundry.github.io%2Fvocabulary%2F%22%2C%22obo%22%3A%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%22%2C%22IAO%22%3A%22obo%3AIAO_%22%2C%22NCBITaxon%22%3A%22obo%3ANCBITaxon_%22%2C%22RO%22%3A%22obo%3ARO_%22%2C%22BFO%22%3A%22obo%3ABFO_%22%2C%22ontologies%22%3A%22%40graph%22%2C%22id%22%3A%22%40id%22%2C%22url%22%3A%22%40id%22%2C%22label%22%3A%22rdfs%3Alabel%22%2C%22seeAlso%22%3A%22rdfs%3AseeAlso%22%2C%22comment%22%3A%22rdfs%3Acomment%22%2C%22description%22%3A%22dce%3Adescription%22%2C%22source%22%3A%22dce%3Asource%22%2C%22publisher%22%3A%22dct%3Apublisher%22%2C%22mailing_list%22%3A%22doap%3Amailing-list%22%2C%22tracker%22%3A%7B%22%40id%22%3A%22doap%3Abug-database%22%2C%22notes%22%3A%22consider%20using%20a%20different%20vocabulary%2C%20bug%20database%20does%20not%20describe%20well%20an%20ontology%20tracker%22%7D%2C%22funded_by%22%3A%22disco%3AfundedBy%22%2C%22createdWith%22%3A%22pav%3AcreatedWith%22%2C%22wasDerivedFrom%22%3A%22pav%3AwasDerivedFrom%22%2C%22preferredPrefix%22%3A%22idot%3ApreferredPrefix%22%2C%22alternatePrefix%22%3A%22idot%3AalternatePrefix%22%2C%22identifierPattern%22%3A%22idot%3AidentifierPattern%22%2C%22exampleIdentifier%22%3A%22idot%3AexampleIdentifier%22%2C%22language%22%3A%22dct%3Alanguage%22%2C%22license%22%3A%22dct%3Alicense%22%2C%22domain%22%3A%22dct%3Atheme%22%2C%22format%22%3A%22dct%3Aformat%22%2C%22products%22%3A%22dcat%3Adistribution%22%2C%22Class%22%3A%22owl%3AClass%22%2C%22biosharing%22%3A%22rdfs%3AseeAlso%22%2C%22browsers%22%3A%22rdfs%3AseeAlso%22%2C%22type%22%3A%7B%22%40id%22%3A%22rdf%3Atype%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22created%22%3A%7B%22%40id%22%3A%22dct%3Acreated%22%2C%22%40type%22%3A%22xsd%3AdateTime%22%7D%2C%22creator%22%3A%7B%22%40id%22%3A%22dct%3Acreator%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22depiction%22%3A%7B%22%40id%22%3A%22foaf%3Adepiction%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22logo%22%3A%7B%22%40id%22%3A%22schemaorg%3Alogo%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22audience%22%3A%7B%22%40id%22%3A%22schemaorg%3Aaudience%22%2C%22%40type%22%3A%22schemaorg%3AAudience%22%7D%2C%22contact%22%3A%7B%22%40id%22%3A%22dcat%3AcontactPoint%22%2C%22%40type%22%3A%22foaf%3APerson%22%7D%2C%22email%22%3A%22foaf%3Ambox%22%2C%22build%22%3A%7B%22%40id%22%3A%22obofmd%3Ahas_build_information%22%2C%22%40type%22%3A%22obofmd%3ABuild%22%7D%2C%22checkout%22%3A%22obofmd%3Acheckout%22%2C%22method%22%3A%22obofmd%3Amethod%22%2C%22source_url%22%3A%7B%22%40id%22%3A%22obofmd%3Asource_url%22%2C%22%40type%22%3A%22xsd%3AanyURI%22%7D%2C%22dependencies%22%3A%22obofmd%3Adepends_on%22%2C%22integration_server%22%3A%22obofmd%3Acontinuous_integration_server%22%2C%22activity_status%22%3A%22obofmd%3Aactivity_status%22%2C%22publications%22%3A%22dct%3Apublication%22%2C%22subClassOf%22%3A%22owl%3AsubClassOf%22%2C%22title%22%3A%22dce%3Atitle%22%2C%22homepage%22%3A%7B%22%40id%22%3A%22foaf%3Ahomepage%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22page%22%3A%7B%22%40id%22%3A%22foaf%3Apage%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22twitter%22%3A%7B%22%40id%22%3A%22foaf%3Aaccount%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22facebook%22%3A%7B%22%40id%22%3A%22foaf%3Aaccount%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22google_plus%22%3A%7B%22%40id%22%3A%22foaf%3Aaccount%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22is_about%22%3A%22IAO%3A0000136%22%2C%22taxon%22%3A%7B%22%40id%22%3A%22IAO%3A0000136%22%2C%22%40type%22%3A%22owl%3AClass%22%7D%2C%22ontology_purl%22%3A%22dcat%3AaccessURL%22%2C%22exampleClass%22%3A%7B%22%40id%22%3A%22void%3AexampleResource%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D):

**Comment by nlharris** [comment]
@matentzn did you mean to assign this to yourself?

**Comment by matentzn** [comment]
It seems to be a known problem by @cmungall with no solution at the moment..

**Comment by cmungall** [comment]
this looks like a trivial fix. Remove the "notes"

There are other issues with jsonld 1.1 and handling of OBO style prefixes where the uri ends with "_", but I think that is separate.
