### ISSUE TITLE
Better document difference between OBO format & OBO Foundry/library

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#148]
Create page on wiki with basic explanation.

**Comment by nlharris** [comment]
This seems like a good idea--did it happen?

**Comment by nlharris** [comment]
should we keep this open?

**Comment by nlharris** [comment]
maybe this could be added to the FAQ

**Comment by matentzn** [comment]
If you make a stub PR I will finish it.

**Comment by nlharris** [comment]
actually, i think the basics of this are already here: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/faq/where-is-the-obo-file.md

perhaps the question in the FAQ that points to this should be changed from "Where is the OBO file for my ontology?" to "What's the difference between OBO Format and the OBO Foundry" (and a bit more content added to the page, maybe)

**Comment by matentzn** [comment]
Maybe these questions have individual concerns.. I would just add this to the FAQ:

What is the difference between an OBO **Foundry** and an OBO **Format** ontology?

There has been a lot of confusion about the difference between an OBO Foundry ontology and OBO Format ontology. The OBO Foundry maintains [a registry of ontologies](http://obofoundry.org/). An **OBO Foundry ontology** is simply a member of this registry. This has _nothing at all to do with the [OBO Format](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.1)_, which is simply a serialisation, or file format, for OBO ontologies. Indeed, the OBO foundry does not even require that an ontology be published in OBO format: the canonical format (serialisation) for OBO ontology is an [RDFXML serialisation of OWL](https://obofoundry.org/principles/fp-002-format.html). In summary, if you hear people talking about "OBO ontologies", they could be talking about (at least) two completely different things: (1) Ontologies that are members of the OBO Foundry ontology registry or (2) ontologies that have been serialised into OBO Format!
