### ISSUE TITLE
Add description, image, links to https://github.com/topics/obofoundry

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1493]
https://github.com/topics/obofoundry
> Improve this page
Add a description, image, and links to the obofoundry topic page so that developers can more easily learn about it.
https://github.com/github/explore/tree/master/CONTRIBUTING.md?source=add-description-obofoundry

**Comment by cthoyt** [comment]
I have done this for other topics before and one of the "rules" is that you can't be a maintainer of the thing that you want to make a topic for. If that's an issue for you @nlharris I would happily take care of this

**Comment by nlharris** [comment]
Thanks, that would be great! Can you make a PR and add me as a reviewer?

**Comment by cthoyt** [comment]
I can't assign reviewers since I'm not an admin in the repo, but here's the PR https://github.com/github/explore/pull/2353. Please feel free to comment on it. you can use the
```
```suggestion
   ...
```
block and I can commit them too

**Comment by cthoyt** [comment]
This is all done! Results can be seen https://github.com/topics/obofoundry. I will make an announcement on the slack workspace with a link to instructions on how everyone can tag their repo with this. @nlharris I think we can close this issue

**Comment by nlharris** [comment]
thanks, @cthoyt!
