### ISSUE TITLE
add OBO dashboard to OBO foundry website

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#1495]
add link to OBO dashboard under ‘ontologies’ dropdown: http://dashboard.obofoundry.org/dashboard/index.html

**Comment by nlharris** [comment]
i can do this if there's agreement that we should do it.
(or @matentzn  could do it in about 10 seconds, but i'm happy to take this tiny crumb off his plate!)

**Comment by nicolevasilevsky** [comment]
I think there was agreement on the call last week. Thanks for doing this, @nlharris!
