### ISSUE TITLE
Proposal for next steps

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#15]
* freeze metadata additions to legacy googlecode/sourceforge site
 * plan to redirect obofoundry.org before googlecode dies
 * announce in advance to obo-discuss list
 * decide on protocol for making changes moving forward

**Comment by zhengj2007** [comment]
All sounds good to me. 

I think we can add it as an agenda item on next Tuesday's OBO Foundry Operations Committee meeting or set a technique group call for it.

**Comment by selewis** [comment]
Sounds a dream. +1 from me. 

(and the sooner the better, let's not let an obvious big step forward like this get too bogged down in never-ending debate of minutiae. perhaps set a date the votes are counted?)

**Comment by cmungall** [comment]
Created a draft announcement for the outreach group to send to obo-discuss and other places: http://obofoundry.github.io/allnews.html

**Comment by cmungall** [comment]
Agreed on obo-ops calls. I have emailed obo-discuss
