### ISSUE TITLE
Jena needed - deprecated rdfcat in makefile

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#152]
Makefile calls rdfcat
1. the Jena requirement is not documented
2. rdfcat is deprecated and replaced by riot

I tried an do the update locally but somehow jekyll didn't like it: line 47-48 in makefile

registry/ontologies.ttl: registry/ontologies.nt
    riot --base=http://purl.obolibrary.org/obo/ --strict --check -q registry/ontologies.nt $< > $@.tmp && mv $@.tmp $@

I don't think the server should cough on this, but don't have time to look into it now.

**Comment by cmungall** [comment]
Not sure what you mean when you say jekyll didn't like it. Jekyll doesn't use the makefile (though it uses the files made by the makefile)

**Comment by cmungall** [comment]
One possibility is to use python rdflibs in place of jena, would make for a more uniform environment. But if we keep jena for now then the install procedure needs better documented, and preferably automated here

**Comment by cmungall** [comment]
We could have some job that auto-commits derived products.

Though having an OBO admin quickly look over these is not a bad idea (this could be formalized into a release process, with the individual md files constituting snapshots). But we should stop me being the bottleneck either way!

**Comment by jamesaoverton** [comment]
I think documenting the requirements would address the problem. Messing around today on my Mac, I also had to install python3 and pyyaml to run the Makefile.

If Jena is really a problem, [Rapper](http://librdf.org/raptor/rapper.html) has similar functionality to Riot, but I haven't looked into the details for this use case.

**Comment by cmungall** [comment]
On 3 Nov 2015, at 12:28, James A. Overton wrote:

> I think documenting the requirements would address the problem. 
> Messing around today on my Mac, I also had to install python3 and 
> pyyaml to run the Makefile.

We have this in the .travis.yml, but it should also be done in a less 
obscure way

> If Jena is really a problem, 
> [Rapper](http://librdf.org/raptor/rapper.html) has similar 
> functionality to Riot, but I haven't looked into the details for this 
> use case.

It's only a problem in that it introduces a slight extra level of 
fiddliness into the install procedure (or at least it does at the 
moment, maybe this can be addressed)

Not sure raptor would help here?

Note the makefile also has a target for doing a comparison of the 
metadata with what is published in the owl by the ontology - see 
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/125

This uses SPARQLWrapper

**Comment by mcourtot** [comment]
To answer the Jena issue: it's not an issue but it came as a surprise when
trying to add a new md file and run make. I can add the info in the
site dev readme, and think about how to make the requirements more obvious
to address James' issues.

Re make, after installing Jena I tried:
1. Make : tells me rdfcat is deprecated and exits. I'm insure if this is
just a warning and it did do everything it should have or if it exited upon
error
2. Update the makefile to use riot, run make: it seems to do all it should
and completes, but when I start Jekyll the page doesn't load - not sure if
it's very slow on my machine or if some files are broken due to my
modifications to the make.

I didn't have the chance to really look into it, thus the ticket to not
forget.

**Comment by cmungall** [comment]
Closing, partially superseded by #557
