### ISSUE TITLE
Proposal principle change: do not grant ID prefixes where these are in use by existing databases

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1522]
Currently we restrict new namespace requests to be unique within obo

We should also ban requesting prefixes that are in use by major bio databases. E.g. I should not be allowed to request ENSEMBL or GTEX for unrelated ontologies

I can provide a more detailed justification later but I view this as basic common sense to prevent both user confusion and clashes in common ID registries

**Comment by matentzn** [comment]
Totally agree. Can we operationalise this by pointing to an existing prefix map?

**Comment by cmungall** [comment]
Duplicate with #1519
