### ISSUE TITLE
Add check for GitHub "obofoundry" tag for new ontologies

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1535]
After the successful launch of the GitHub [topic page for the OBO Foundry](https://github.com/topics/obofoundry) motivated by #1493, it would make sense to ask all new ontologies tag themselves with `obofoundry`.

I think it's also worth considering how we should communicate that the `obofoundry` tag isn't an endorsement from the OBO Foundry the same way that getting accepted is. It's the case that anyone can add the tag on GitHub and it may also be meaningful to add other types of resources like software packages (e.g., I added the obofoundry topic to the [PyOBO](https://github.com/pyobo/pyobo) Python software package)

## Code example

The following function in Python could be used to check for a repo if it has a given topic.

```python
from typing import Optional

import requests


def has_topic(owner: str, repo: str, topic: str, token: Optional[str] = None) -> bool:
    """Check if the given GitHub repository has the given topic.

    :param owner: The name of the owner/organization for the repository.
    :param repo: The name of the repository.
    :param topic: The topic to check if the repository has. Case and punctuation sensitive.
    :param token: The GitHub OAuth token. Not required, but if given, will let
        you make many more queries before getting rate limited.
    :return: If the repository has the given topic.
    """
    headers = {
        'Accept': "application/vnd.github.mercy-preview+json",
    }
    if token:
        headers['Authorization'] = f"token {token}",

    res = requests.get(
        f'https://api.github.com/repos/{owner}/{repo}/topics',
        headers=headers,
    )
    res_json = res.json()
    return topic in res_json['names']
```

Example usage:

```python
assert has_topic('obophenotype', 'dicty-phenotype-ontology', topic='obofoundry'))
assert not has_topic('pytorch', 'pytorch', topic='obofoundry'))
```

## See Also

- This issue #1538 is about retroactively adding the tag to existing OBO Foundry ontologies.

**Comment by nlharris** [comment]
@matentzn i was a bit surprised to see that there's not a label 'dashboard' -- should i create one?

**Comment by nlharris** [comment]
More about this ticket (from Slack): Charlie wrote:
> any repo tagged with “obofoundry” as a topic will get listed on this page: https://github.com/topics/obofoundry
If you haven’t tagged your repositories before, you can follow GitHub’s excellent tutorial to get yours listed here too https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics

**Comment by balhoff** [comment]
@cthoyt @nlharris there is a dashboard repo: https://github.com/OBOFoundry/OBO-Dashboard

Should we transfer this issue there?

**Comment by nlharris** [comment]
Maybe? It's up to @matentzn 

BTW, this issue is related to #1538

**Comment by matentzn** [comment]
The issue needs to be discussed at obo foundry operations committee level. Can someone add the tag please so we discuss, then I will move it.

**Comment by jamesaoverton** [comment]
I think it's a good idea to consistently use the "obofoundry" GitHub tag, and we might as well add an automated check like this and track when the tag is and is not used.

But using GitHub is not an OBO requirement and so this cannot be a requirement. We require version control and a public issue tracker, and currently 90% of active projects happen to use GitHub, that's all.

**Comment by matentzn** [comment]
Yes I agree with @jamesaoverton - this is not a matter for the dashboard - I love the tag, but same as slack, this needs to be dealt with in a "social" manner through people looking out and talking, not through a QC check.

**Comment by nlharris** [comment]
We discussed this briefly during an OFOC call and agreed that this should be recommended but not formally required for new ontologies. Thanks for suggesting it, though!

**Comment by matentzn** [comment]
Best practices collected here:

https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1579

Will use this to compile a page for the site once its done which will be circulated to new and old developers.
