### ISSUE TITLE
CDNO is still Crop DNO in Ontobee and OLS

### ISSUE THREAD

**Issue by LilyAndres** [OBOFoundry/OBOFoundry.github.io#1536]
Hi OBO team,

Thanks for your help during the process of the Crop DNO to now Compositional DNO. I saw that in Ontobee under the title the CDNO is still Crop instead of Compositional, so I checked the cdno.md and everything looks ok but I'm not quite sure why in Ontobee and OLS the name is still Crop. Did I miss something in the cdno.md file? Thanks I hope you can help me.

**Comment by yongqunh** [comment]
I think it is because your own OWL file still uses Crop:
https://raw.githubusercontent.com/Southern-Cross-Plant-Science/cdno/master/cdno.owl

**Comment by LilyAndres** [comment]
thanks a lot @yongqunh I will check this and make the changes.

**Comment by LilyAndres** [comment]
Sorry, I think what happened is that the last release is not in the OBO, but the cdno.md has been updated and merged with the incorrect version. I will make a pull request so we can merge the last version in OBO repository.

**Comment by cthoyt** [comment]
It might also be the case that even though the markdown file has been updated, there hasn’t been a full build that propagates the information to the other build artifacts (I also made a few updates that haven’t made it to prime time yet)

**Comment by LilyAndres** [comment]
@cthoyt thanks. I think this time might be the version? In Ontobee I can see the owl file is from 2021-02-06 which is the first release we made and not the latest with the changes from 2021-06-01 where we switch the name from Crop to Compositional.  

![image](https://user-images.githubusercontent.com/25215773/121453166-0b0c1600-c9e4-11eb-977b-1f760e50df02.png)

**Comment by yongqunh** [comment]
Ontobee has updated, but it is still May version:
http://www.ontobee.org/ontology/CDNO
I guess that your June version needs to be approved first.

**Comment by LilyAndres** [comment]
Thanks @yongqunh I will make a pull request.

**Comment by LilyAndres** [comment]
@matentzn thanks, here is my issue.

**Comment by matentzn** [comment]
I dont understand the problem. The last version of CDNO is
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/cdno/releases/2021-05-30/cdno.owl"/>

That is also what is in OntoBee..

**Comment by LilyAndres** [comment]
@matentzn I'm sorry for the confusion, it might something that I need to fix. I just don't understand why the old name of CDNO is still Crop in OLS and in Ontobee **title** of the ontology. 

![image](https://user-images.githubusercontent.com/25215773/121473052-6c90ac80-ca05-11eb-9ba4-51f3b88a83b7.png)

**Comment by matentzn** [comment]
Because in your ontology (in protege!) it says "crop":
https://raw.githubusercontent.com/Southern-Cross-Plant-Science/cdno/master/cdno.owl

**Comment by matentzn** [comment]
https://github.com/Southern-Cross-Plant-Science/cdno/pull/68

**Comment by kaiiam** [comment]
Much obliged @matentzn! https://github.com/Southern-Cross-Plant-Science/cdno/pull/68 should fix this.

**Comment by LilyAndres** [comment]
Thank you for everything OBO team, I will close this issue now.
