### ISSUE TITLE
Encourage repositories to add `obofoundry` topic

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1538]
After completing #1493, it's now time to do a bit of outreach to the community and ask all of the different members to add the `obofoundry` topic to their repos. It's pretty simple through the main page for the repository, but in case it's not obvious there's a tutorial here: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics.

## Methods

I've used the following script https://gist.github.com/cthoyt/95694a05190fc23b997fae62f12f96f1 which generates this table as a summary and also automatically created issues on all of the repos (which get linked back to this one). Note, after a while this triggers the abuse detection in the GitHub API 😆, so I added in a `time.sleep(2)` to calm it down

<details>
  <summary>Full Table, created at the time of filing the issue</summary>

| ontology    | title                                                                      | owner                               | repo                                       | topics                                                                                                                                            | has_obofoundry_topic   |
|-------------|----------------------------------------------------------------------------|-------------------------------------|--------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|------------------------|
| bfo         | Basic Formal Ontology                                                      | BFO-ontology                        | BFO                                        |                                                                                                                                                   | False                  |
| chebi       | Chemical Entities of Biological Interest                                   | ebi-chebi                           | ChEBI                                      |                                                                                                                                                   | False                  |
| doid        | Human Disease Ontology                                                     | DiseaseOntology                     | HumanDiseaseOntology                       |                                                                                                                                                   | False                  |
| go          | Gene Ontology                                                              | geneontology                        | go-ontology                                | ontology,go,owl,obo,obofoundry,gene-ontology                                                                                                      | True                   |
| pato        | Phenotype And Trait Ontology                                               | pato-ontology                       | pato                                       | phenotypes,trait-ontology,obo,ontology,units,qualities,quantities,standards,semantic-web                                                          | False                  |
| po          | Plant Ontology                                                             | Planteome                           | plant-ontology                             |                                                                                                                                                   | False                  |
| pr          | PRotein Ontology (PRO)                                                     | PROconsortium                       | PRoteinOntology                            | obofoundry,biomedical-ontologies,obo,protein-ontology                                                                                             | True                   |
| xao         | Xenopus Anatomy Ontology                                                   | xenopus-anatomy                     | xao                                        | xenopus-anatomy-ontology,anatomy,ontology,xenopus,xao                                                                                             | False                  |
| zfa         | Zebrafish anatomy and development ontology                                 | cerivs                              | zebrafish-anatomical-ontology              |                                                                                                                                                   | False                  |
| aeo         | Anatomical Entity Ontology                                                 | obophenotype                        | human-developmental-anatomy-ontology       |                                                                                                                                                   | False                  |
| agro        | Agronomy Ontology                                                          | AgriculturalSemantics               | agro                                       | agronomy,agriculture,agriculture-research,agronomy-ontology                                                                                       | False                  |
| aism        | Ontology for the Anatomy of the Insect SkeletoMuscular system (AISM)       | insect-morphology                   | aism                                       | ontology,ontology-development-kit,multispecies-anatomy-ontologies,insect-ontology,insect-anatomy-ontologies,insect-anatomy                        | False                  |
| amphx       | The Amphioxus Development and Anatomy Ontology                             | EBISPOT                             | amphx_ontology                             |                                                                                                                                                   | False                  |
| apo         | Ascomycete phenotype ontology                                              | obophenotype                        | ascomycete-phenotype-ontology              |                                                                                                                                                   | False                  |
| apollo_sv   | Apollo Structured Vocabulary                                               | ApolloDev                           | apollo-sv                                  |                                                                                                                                                   | False                  |
| aro         | Antibiotic Resistance Ontology                                             | arpcard                             | aro                                        |                                                                                                                                                   | False                  |
| bco         | Biological Collections Ontology                                            | tucotuco                            | bco                                        | obofoundry                                                                                                                                        | True                   |
| bspo        | Biological Spatial Ontology                                                | obophenotype                        | biological-spatial-ontology                | obofoundry                                                                                                                                        | True                   |
| bto         | BRENDA tissue / enzyme source                                              | BRENDA-Enzymes                      | BTO                                        |                                                                                                                                                   | False                  |
| caro        | Common Anatomy Reference Ontology                                          | obophenotype                        | caro                                       | obofoundry                                                                                                                                        | True                   |
| cdao        | Comparative Data Analysis Ontology                                         | evoinfo                             | cdao                                       | comparative-analysis,phylogenetics,ontology,semantic-web,information-exchange,obofoundry                                                          | True                   |
| cdno        | Compositional Dietary Nutrition Ontology                                   | Southern-Cross-Plant-Science        | cdno                                       | ontology,nutrition,obofoundry,owl                                                                                                                 | True                   |
| cheminf     | Chemical Information Ontology                                              | semanticchemistry                   | semanticchemistry                          | chemistry,ontology,cheminformatics,chemical-information                                                                                           | False                  |
| chiro       | CHEBI Integrated Role Ontology                                             | obophenotype                        | chiro                                      |                                                                                                                                                   | False                  |
| chmo        | Chemical Methods Ontology                                                  | rsc-ontologies                      | rsc-cmo                                    |                                                                                                                                                   | False                  |
| cido        | Coronavirus Infectious Disease Ontology                                    | cido-ontology                       | cido                                       |                                                                                                                                                   | False                  |
| cio         | Confidence Information Ontology                                            | BgeeDB                              | confidence-information-ontology            |                                                                                                                                                   | False                  |
| cl          | Cell Ontology                                                              | obophenotype                        | cell-ontology                              | obofoundry,cell-ontology,ontology,anatomy,cell-types,owl                                                                                          | True                   |
| clao        | Collembola Anatomy Ontology                                                | luis-gonzalez-m                     | Collembola                                 | anatomy,hexapod-anatomy,ontology                                                                                                                  | False                  |
| clo         | Cell Line Ontology                                                         | CLO-Ontology                        | CLO                                        |                                                                                                                                                   | False                  |
| clyh        | Clytia hemisphaerica Development and Anatomy Ontology                      | EBISPOT                             | clyh_ontology                              |                                                                                                                                                   | False                  |
| cmo         | Clinical measurement ontology                                              | rat-genome-database                 | CMO-Clinical-Measurement-Ontology          |                                                                                                                                                   | False                  |
| cob         | Core Ontology for Biology and Biomedicine                                  | OBOFoundry                          | COB                                        | obofoundry,owl,upper-ontology                                                                                                                     | True                   |
| cro         | Contributor Role Ontology                                                  | data2health                         | contributor-role-ontology                  | data2health,pea                                                                                                                                   | False                  |
| cteno       | Ctenophore Ontology                                                        | obophenotype                        | ctenophore-ontology                        |                                                                                                                                                   | False                  |
| cto         | CTO: Core Ontology of Clinical Trials                                      | ClinicalTrialOntology               | CTO                                        | ontology,clinical-trials                                                                                                                          | False                  |
| cvdo        | Cardiovascular Disease Ontology                                            | OpenLHS                             | CVDO                                       |                                                                                                                                                   | False                  |
| ddanat      | Dictyostelium discoideum anatomy                                           | dictyBase                           | migration-data                             |                                                                                                                                                   | False                  |
| ddpheno     | Dictyostelium discoideum phenotype ontology                                | obophenotype                        | dicty-phenotype-ontology                   |                                                                                                                                                   | False                  |
| dideo       | Drug-drug Interaction and Drug-drug Interaction Evidence Ontology          | DIDEO                               | DIDEO                                      |                                                                                                                                                   | False                  |
| dpo         | Drosophila Phenotype Ontology                                              | FlyBase                             | drosophila-phenotype-ontology              | phenotype,ontology,flybase,obofoundry                                                                                                             | True                   |
| duo         | Data Use Ontology                                                          | EBISPOT                             | DUO                                        | obofoundry,ontology,datasets-tagged,biomedical-informatics,biomedical-applications,genomics-data,owl                                              | True                   |
| ecao        | The Echinoderm Anatomy and Development Ontology                            | echinoderm-ontology                 | ecao_ontology                              |                                                                                                                                                   | False                  |
| eco         | Evidence ontology                                                          | evidenceontology                    | evidenceontology                           |                                                                                                                                                   | False                  |
| ecocore     | An ontology of core ecological entities                                    | EcologicalSemantics                 | ecocore                                    |                                                                                                                                                   | False                  |
| ecto        | Environmental conditions, treatments and exposures ontology                | EnvironmentOntology                 | environmental-exposure-ontology            | exposure,obo,ontology,owl,health,environment                                                                                                      | False                  |
| emapa       | Mouse Developmental Anatomy Ontology                                       | obophenotype                        | mouse-anatomy-ontology                     |                                                                                                                                                   | False                  |
| envo        | Environment Ontology                                                       | EnvironmentOntology                 | envo                                       |                                                                                                                                                   | False                  |
| eupath      | VEuPathDB ontology                                                         | VEuPathDB-ontology                  | VEuPathDB-ontology                         | obofoundry                                                                                                                                        | True                   |
| exo         | Exposure ontology                                                          | CTDbase                             | exposure-ontology                          |                                                                                                                                                   | False                  |
| fao         | Fungal gross anatomy                                                       | obophenotype                        | fungal-anatomy-ontology                    |                                                                                                                                                   | False                  |
| fbbi        | Biological Imaging Methods Ontology                                        | CRBS                                | Biological_Imaging_Methods_Ontology        |                                                                                                                                                   | False                  |
| fbcv        | FlyBase Controlled Vocabulary                                              | FlyBase                             | flybase-controlled-vocabulary              | drosophila,flybase,obofoundry,ontology,phenotype,genetics                                                                                         | True                   |
| fideo       | Food Interactions with Drugs Evidence Ontology                             | getbordea                           | fideo                                      |                                                                                                                                                   | False                  |
| flopo       | Flora Phenotype Ontology                                                   | flora-phenotype-ontology            | flopoontology                              |                                                                                                                                                   | False                  |
| foodon      | FOODON                                                                     | FoodOntology                        | foodon                                     | obofoundry,ontology,owl,food,agriculture                                                                                                          | True                   |
| fovt        | FuTRES Ontology of Vertebrate Traits                                       | futres                              | fovt                                       |                                                                                                                                                   | False                  |
| fypo        | Fission Yeast Phenotype Ontology                                           | pombase                             | fypo                                       | fission-yeast,pombase,phenotypes,obofoundry                                                                                                       | True                   |
| gaz         | Gazetteer                                                                  | EnvironmentOntology                 | gaz                                        |                                                                                                                                                   | False                  |
| gecko       | Genomics Cohorts Knowledge Ontology                                        | IHCC-cohorts                        | GECKO                                      |                                                                                                                                                   | False                  |
| genepio     | Genomic Epidemiology Ontology                                              | GenEpiO                             | genepio                                    | obofoundry                                                                                                                                        | True                   |
| geno        | Genotype Ontology                                                          | monarch-initiative                  | GENO-ontology                              | monarchinitiative,ontology,obofoundry                                                                                                             | True                   |
| gno         | Glycan Naming and Subsumption Ontology (GNOme)                             | glygen-glycan-data                  | GNOme                                      |                                                                                                                                                   | False                  |
| hancestro   | Human Ancestry Ontology                                                    | EBISPOT                             | ancestro                                   |                                                                                                                                                   | False                  |
| hao         | Hymenoptera Anatomy Ontology                                               | hymao                               | hao                                        | obofoundry,hymenoptera                                                                                                                            | True                   |
| hom         | Homology Ontology                                                          | BgeeDB                              | homology-ontology                          |                                                                                                                                                   | False                  |
| hsapdv      | Human Developmental Stages                                                 | obophenotype                        | developmental-stage-ontologies             |                                                                                                                                                   | False                  |
| hso         | Health Surveillance Ontology                                               | SVA-SE                              | HSO                                        |                                                                                                                                                   | False                  |
| htn         | Hypertension Ontology                                                      | aellenhicks                         | htn_owl                                    |                                                                                                                                                   | False                  |
| iao         | Information Artifact Ontology                                              | information-artifact-ontology       | IAO                                        |                                                                                                                                                   | False                  |
| iceo        | Integrative and Conjugative Element Ontology                               | ontoice                             | ICEO                                       |                                                                                                                                                   | False                  |
| ico         | Informed Consent Ontology                                                  | ICO-ontology                        | ICO                                        |                                                                                                                                                   | False                  |
| ido         | Infectious Disease Ontology                                                | infectious-disease-ontology         | infectious-disease-ontology                |                                                                                                                                                   | False                  |
| ino         | Interaction Network Ontology                                               | INO-ontology                        | ino                                        |                                                                                                                                                   | False                  |
| labo        | clinical LABoratory Ontology                                               | OpenLHS                             | LABO                                       |                                                                                                                                                   | False                  |
| ma          | Mouse adult gross anatomy                                                  | obophenotype                        | mouse-anatomy-ontology                     |                                                                                                                                                   | False                  |
| maxo        | Medical Action Ontology                                                    | monarch-initiative                  | MAxO                                       | monarchinitiative                                                                                                                                 | False                  |
| mco         | Microbial Conditions Ontology                                              | microbial-conditions-ontology       | microbial-conditions-ontology              |                                                                                                                                                   | False                  |
| mf          | Mental Functioning Ontology                                                | jannahastings                       | mental-functioning-ontology                |                                                                                                                                                   | False                  |
| mfmo        | Mammalian Feeding Muscle Ontology                                          | RDruzinsky                          | feedontology                               |                                                                                                                                                   | False                  |
| mfoem       | Emotion Ontology                                                           | jannahastings                       | emotion-ontology                           |                                                                                                                                                   | False                  |
| mfomd       | Mental Disease Ontology                                                    | jannahastings                       | mental-functioning-ontology                |                                                                                                                                                   | False                  |
| mi          | Molecular Interactions Controlled Vocabulary                               | HUPO-PSI                            | psi-mi-CV                                  |                                                                                                                                                   | False                  |
| miapa       | MIAPA Ontology                                                             | evoinfo                             | miapa                                      | minimum-information,information-exchange,standard,phylogenetics                                                                                   | False                  |
| micro       | Ontology of Prokaryotic Phenotypic and Metabolic Characters                | carrineblank                        | MicrO                                      | ontology,phenomic,prokaryotic-taxonomic-descriptions,microbiology,bioinformatics-databases                                                        | False                  |
| mmo         | Measurement method ontology                                                | rat-genome-database                 | MMO-Measurement-Method-Ontology            |                                                                                                                                                   | False                  |
| mmusdv      | Mouse Developmental Stages                                                 | obophenotype                        | developmental-stage-ontologies             |                                                                                                                                                   | False                  |
| mod         | Protein modification                                                       | HUPO-PSI                            | psi-mod-CV                                 |                                                                                                                                                   | False                  |
| mondo       | Mondo Disease Ontology                                                     | monarch-initiative                  | mondo                                      | monarchinitiative,ontology,obofoundry,mondo,disease,disease-classification,owl                                                                    | True                   |
| mop         | Molecular Process Ontology                                                 | rsc-ontologies                      | rxno                                       |                                                                                                                                                   | False                  |
| mp          | Mammalian Phenotype Ontology                                               | obophenotype                        | mammalian-phenotype-ontology               |                                                                                                                                                   | False                  |
| mpath       | Mouse pathology ontology                                                   | PaulNSchofield                      | mpath                                      |                                                                                                                                                   | False                  |
| mpio        | Minimum PDDI Information Ontology                                          | MPIO-Developers                     | MPIO                                       |                                                                                                                                                   | False                  |
| mro         | MHC Restriction Ontology                                                   | IEDB                                | MRO                                        |                                                                                                                                                   | False                  |
| ms          | Mass spectrometry ontology                                                 | HUPO-PSI                            | psi-ms-CV                                  |                                                                                                                                                   | False                  |
| nbo         | Neuro Behavior Ontology                                                    | obo-behavior                        | behavior-ontology                          | ontology,neuro-behaviour-ontology,behavioural-phenotypes,web-ontology-language,animal-behaviours,obo                                              | False                  |
| ncbitaxon   | NCBI organismal classification                                             | obophenotype                        | ncbitaxon                                  | obofoundry,taxonomy,ncbi-taxonomy,ontology                                                                                                        | True                   |
| ncit        | NCI Thesaurus OBO Edition                                                  | NCI-Thesaurus                       | thesaurus-obo-edition                      |                                                                                                                                                   | False                  |
| ncro        | Non-Coding RNA Ontology                                                    | OmniSearch                          | NCRO-Ontology-Files                        |                                                                                                                                                   | False                  |
| nomen       | NOMEN - A nomenclatural ontology for biological names                      | SpeciesFileGroup                    | nomen                                      | web-ontology-language,ontology,biological-entities,nomenclature,taxa                                                                              | False                  |
| oae         | Ontology of Adverse Events                                                 | OAE-ontology                        | OAE                                        |                                                                                                                                                   | False                  |
| oarcs       | Ontology of Arthropod Circulatory Systems                                  | aszool                              | oarcs                                      |                                                                                                                                                   | False                  |
| oba         | Ontology of Biological Attributes                                          | obophenotype                        | bio-attribute-ontology                     | obofoundry                                                                                                                                        | True                   |
| obcs        | Ontology of Biological and Clinical Statistics                             | obcs                                | obcs                                       |                                                                                                                                                   | False                  |
| obib        | Ontology for Biobanking                                                    | biobanking                          | biobanking                                 |                                                                                                                                                   | False                  |
| ogms        | Ontology for General Medical Science                                       | OGMS                                | ogms                                       |                                                                                                                                                   | False                  |
| ogsf        | Ontology of Genetic Susceptibility Factor                                  | linikujp                            | OGSF                                       |                                                                                                                                                   | False                  |
| ohmi        | Ontology of Host-Microbiome Interactions                                   | ohmi-ontology                       | ohmi                                       |                                                                                                                                                   | False                  |
| ohpi        | Ontology of Host Pathogen Interactions                                     | OHPI                                | ohpi                                       |                                                                                                                                                   | False                  |
| olatdv      | Medaka Developmental Stages                                                | obophenotype                        | developmental-stage-ontologies             |                                                                                                                                                   | False                  |
| omiabis     | Ontologized MIABIS                                                         | OMIABIS                             | omiabis-dev                                |                                                                                                                                                   | False                  |
| omit        | Ontology for MIRNA Target                                                  | OmniSearch                          | omit                                       |                                                                                                                                                   | False                  |
| omo         | OBO Metadata Ontology                                                      | information-artifact-ontology       | ontology-metadata                          |                                                                                                                                                   | False                  |
| omp         | Ontology of Microbial Phenotypes                                           | microbialphenotypes                 | OMP-ontology                               |                                                                                                                                                   | False                  |
| omrse       | Ontology of Medically Related Social Entities                              | ufbmi                               | OMRSE                                      |                                                                                                                                                   | False                  |
| one         | Ontology for Nutritional Epidemiology                                      | cyang0128                           | Nutritional-epidemiologic-ontologies       | ontology,ontology-search,nutrition,epidemiology,data-sharing,dietary-intake,strobe-nut,obofoundry                                                 | True                   |
| ons         | Ontology for Nutritional Studies                                           | enpadasi                            | Ontology-for-Nutritional-Studies           | ontology,nutrition,health,intervention-study,observational-study,metabolomics,food-intake,biomarker,databases,nutritional-studies,diet,obofoundry | True                   |
| ontoneo     | Obstetric and Neonatal Ontology                                            | ontoneo-project                     | Ontoneo                                    |                                                                                                                                                   | False                  |
| oostt       | Ontology of Organizational Structures of Trauma centers and Trauma systems | OOSTT                               | OOSTT                                      |                                                                                                                                                   | False                  |
| opl         | Ontology for Parasite LifeCycle                                            | OPL-ontology                        | OPL                                        |                                                                                                                                                   | False                  |
| opmi        | Ontology of Precision Medicine and Investigation                           | OPMI                                | opmi                                       |                                                                                                                                                   | False                  |
| ornaseq     | Ontology of RNA Sequencing                                                 | safisher                            | ornaseq                                    |                                                                                                                                                   | False                  |
| ovae        | Ontology of Vaccine Adverse Events                                         | OVAE-Ontology                       | ovae                                       |                                                                                                                                                   | False                  |
| pco         | Population and Community Ontology                                          | PopulationAndCommunityOntology      | pco                                        | obofoundry                                                                                                                                        | True                   |
| pdro        | The Prescription of Drugs Ontology                                         | OpenLHS                             | PDRO                                       |                                                                                                                                                   | False                  |
| pdumdv      | Platynereis Developmental Stages                                           | obophenotype                        | developmental-stage-ontologies             |                                                                                                                                                   | False                  |
| peco        | Plant Experimental Conditions Ontology                                     | Planteome                           | plant-experimental-conditions-ontology     |                                                                                                                                                   | False                  |
| phipo       | Pathogen Host Interaction Phenotype Ontology                               | PHI-base                            | phipo                                      |                                                                                                                                                   | False                  |
| plana       | planaria-ontology                                                          | obophenotype                        | planaria-ontology                          |                                                                                                                                                   | False                  |
| planp       | Planarian Phenotype Ontology                                               | obophenotype                        | planarian-phenotype-ontology               |                                                                                                                                                   | False                  |
| poro        | Porifera Ontology                                                          | obophenotype                        | porifera-ontology                          | obofoundry                                                                                                                                        | True                   |
| ppo         | Plant Phenology Ontology                                                   | PlantPhenoOntology                  | PPO                                        |                                                                                                                                                   | False                  |
| psdo        | Performance Summary Display Ontology                                       | Display-Lab                         | psdo                                       | ontology,obo,owl                                                                                                                                  | False                  |
| pso         | Plant Stress Ontology                                                      | Planteome                           | plant-stress-ontology                      |                                                                                                                                                   | False                  |
| pw          | Pathway ontology                                                           | rat-genome-database                 | PW-Pathway-Ontology                        |                                                                                                                                                   | False                  |
| rbo         | Radiation Biology Ontology                                                 | Radiobiology-Informatics-Consortium | RBO                                        |                                                                                                                                                   | False                  |
| ro          | Relation Ontology                                                          | oborel                              | obo-relations                              | obofoundry                                                                                                                                        | True                   |
| rs          | Rat Strain Ontology                                                        | rat-genome-database                 | RS-Rat-Strain-Ontology                     |                                                                                                                                                   | False                  |
| rxno        | Name Reaction Ontology                                                     | rsc-ontologies                      | rxno                                       |                                                                                                                                                   | False                  |
| sepio       | Scientific Evidence and Provenance Information Ontology                    | monarch-initiative                  | SEPIO-ontology                             | monarchinitiative,evidence,provenance                                                                                                             | False                  |
| so          | Sequence types and features ontology                                       | The-Sequence-Ontology               | SO-Ontologies                              |                                                                                                                                                   | False                  |
| spd         | Spider Ontology                                                            | obophenotype                        | spider-ontology                            |                                                                                                                                                   | False                  |
| stato       | The Statistical Methods Ontology                                           | ISA-tools                           | stato                                      | statistics,ontology,owl                                                                                                                           | False                  |
| swo         | Software ontology                                                          | allysonlister                       | swo                                        |                                                                                                                                                   | False                  |
| symp        | Symptom Ontology                                                           | DiseaseOntology                     | SymptomOntology                            |                                                                                                                                                   | False                  |
| taxrank     | Taxonomic rank vocabulary                                                  | phenoscape                          | taxrank                                    |                                                                                                                                                   | False                  |
| to          | Plant Trait Ontology                                                       | Planteome                           | plant-trait-ontology                       |                                                                                                                                                   | False                  |
| trans       | Pathogen Transmission Ontology                                             | DiseaseOntology                     | PathogenTransmissionOntology               |                                                                                                                                                   | False                  |
| tto         | Teleost taxonomy ontology                                                  | phenoscape                          | teleost-taxonomy-ontology                  |                                                                                                                                                   | False                  |
| uberon      | Uberon multi-species anatomy ontology                                      | obophenotype                        | uberon                                     | obofoundry,uberon,ontology,anatomy,monarchinitiative                                                                                              | True                   |
| uo          | Units of measurement ontology                                              | bio-ontology-research-group         | unit-ontology                              | ontology,units-of-measurement,obo                                                                                                                 | False                  |
| upheno      | Unified phenotype ontology (uPheno)                                        | obophenotype                        | upheno                                     | obofoundry                                                                                                                                        | True                   |
| vo          | Vaccine Ontology                                                           | vaccineontology                     | VO                                         |                                                                                                                                                   | False                  |
| vt          | Vertebrate trait ontology                                                  | AnimalGenome                        | vertebrate-trait-ontology                  |                                                                                                                                                   | False                  |
| vto         | Vertebrate Taxonomy Ontology                                               | phenoscape                          | vertebrate-taxonomy-ontology               |                                                                                                                                                   | False                  |
| wbbt        | C. elegans Gross Anatomy Ontology                                          | obophenotype                        | c-elegans-gross-anatomy-ontology           | obofoundry,caenorhabditis-elegans,anatomy,ontology                                                                                                | True                   |
| wbls        | C. elegans development ontology                                            | obophenotype                        | c-elegans-development-ontology             | wormbase,nematodes,development,ontology,caenorhabditis-elegans,obofoundry                                                                         | True                   |
| wbphenotype | C. elegans phenotype                                                       | obophenotype                        | c-elegans-phenotype-ontology               | ontology,elegans-phenotype-ontology,phenotype-term,caenorhabditis-elegans,phenotype-ontologies,phenotypes,nematodes,obofoundry,elegans            | True                   |
| xco         | Experimental condition ontology                                            | rat-genome-database                 | XCO-experimental-condition-ontology        |                                                                                                                                                   | False                  |
| xlmod       | HUPO-PSI cross-linking and derivatization reagents controlled vocabulary   | HUPO-PSI                            | mzIdentML                                  |                                                                                                                                                   | False                  |
| xpo         | Xenopus Phenotype Ontology                                                 | obophenotype                        | xenopus-phenotype-ontology                 | xenopus-phenotype-ontology,phenotype,ontology,xenopus,xpo                                                                                         | False                  |
| zeco        | Zebrafish Experimental Conditions Ontology                                 | ybradford                           | zebrafish-experimental-conditions-ontology |                                                                                                                                                   | False                  |
| zfs         | Zebrafish developmental stages ontology                                    | cerivs                              | zebrafish-anatomical-ontology              |                                                                                                                                                   | False                  |
| zp          | Zebrafish Phenotype Ontology                                               | obophenotype                        | zebrafish-phenotype-ontology               |                                                                                                                                                   | False                  |
| fobi        | FOBI                                                                       | pcastellanoescuder                  | FoodBiomarkerOntology                      | ontology,metabolomics,nutrition,biomarkers,foods,knowledge-graph,ontologies                                                                       | False                  |
| gsso        | Gender, Sex, and Sexual Orientation (GSSO) ontology                        | Superraptor                         | GSSO                                       | gender,ontology,gender-identity,sex,sexuality,gender-diversity                                                                                    | False                  |
| hp          | Human Phenotype Ontology                                                   | obophenotype                        | human-phenotype-ontology                   | hpo,ontology,phenotype,phenotyping,ontologies,obo,owl,semantic-web,obofoundry                                                                     | True                   |
| scdo        | Sickle Cell Disease Ontology                                               | scdodev                             | scdo-ontology                              |                                                                                                                                                   | False                  |
| txpo        | Toxic Process Ontology                                                     | txpo-ontology                       | TXPO                                       |                                                                                                                                                   | False                  |
| sibo        | Social Insect Behavior Ontology                                            | obophenotype                        | sibo                                       |                                                                                                                                                   | False                  |
| ceph        | Cephalopod Ontology                                                        | obophenotype                        | cephalopod-ontology                        |                                                                                                                                                   | False                  |
| ehdaa2      | Human developmental anatomy, abstract                                      | obophenotype                        | human-developmental-anatomy-ontology       |                                                                                                                                                   | False                  |
| rnao        | RNA ontology                                                               | BGSU-RNA                            | rnao                                       |                                                                                                                                                   | False                  |
| upa         | Unipathway                                                                 | geneontology                        | unipathway                                 |                                                                                                                                                   | False                  |
| bcgo        | Beta Cell Genomics Ontology                                                | obi-bcgo                            | bcgo                                       |                                                                                                                                                   | False                  |
| dinto       | The Drug-Drug Interactions Ontology                                        | labda                               | DINTO                                      |                                                                                                                                                   | False                  |
| eo          | Plant Environment Ontology                                                 | Planteome                           | plant-environment-ontology                 |                                                                                                                                                   | False                  |
| tao         | Teleost Anatomy Ontology                                                   | obophenotype                        | uberon                                     | obofoundry,uberon,ontology,anatomy,monarchinitiative                                                                                              | True                   |
| vsao        | Vertebrate Skeletal Anatomy Ontology-                                      | obophenotype                        | uberon                                     | obofoundry,uberon,ontology,anatomy,monarchinitiative                                                                                              | True                   |
</details>

**Comment by cthoyt** [comment]
@mbrochhausen GitHub rightly protects itself and its users from abuse by looking for fishy people like me who are opening lots of issues programatically in very quick succession. After 15 or 20 issues posted, it started returning a warning that I was abusing the API and should try later.

After I initially posted the comment you're referring to, I realized I could just add a simple rate limit by using `time.sleep(2)` between each issue creation, which seemed to be enough to avoid further error messages

**Comment by matentzn** [comment]
We (OFOC call today) decided to mandate this softly as part of best practices which are collected here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1579

Thanks for the suggestion! Great.

**Comment by cthoyt** [comment]
@matentzn excellent

**Comment by cthoyt** [comment]
As of right now, 43 of the repositories that I originally pinged **two years ago** have not responded. I just pinged all 43, tagging their responsible people (this is now possible since in the last two years, I have convinced the OBO community that having the GitHub handle easily accessible for each active ontology is valuable). I suggest that in a few months, we review who remains unresponsive and begin marking ontologies as orphaned/inactive accordingly.

**Comment by matentzn** [comment]
>  I suggest that in a few months, we review who remains unresponsive and begin marking ontologies as orphaned/inactive accordingly.

You can always initiate a process like this, but not dealing with a specific issue does not all by itself constitute "inactivity"

**Comment by cthoyt** [comment]
True, but most of the remaining haven’t committed in the last 3-5 years and haven’t addressed any of the issues or PRs. I would be keen on having a more concrete definition of “inactive” and would hope that it includes any repository that hasn’t committed or responded to issues in the last X years (pick whatever x feels most comfortable)
