### ISSUE TITLE
FBcv and DPO both have same preferred prefix

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1559]
Two resources from FlyBase http://www.obofoundry.org/ontology/dpo and http://www.obofoundry.org/ontology/fbcv maintained by @Clare72 both have "FBcv" written as their preferred prefix. They state that DPO is a subset of FBcv. Would it make sense to assign DPO a different preferred prefix?

**Comment by dosumis** [comment]
FBcv IDs long predate the splitting out of dpo as a distinct ontology.  The churn of changing preferred prefix would be huge.

**Comment by matentzn** [comment]
I think this is a case where the idea of a unique prefix and an OBO prefix diverge - maybe the only case. So @cthoyt what happened was that for some years, DPO was part of FBcv before it was split away. For continuity and avoiding churn on the FlyBase side, it was decided that basically the same ID space (with different ID ranges) would be maintained for both: `http://purl.obolibrary.org/obo/FBcv_`. OBO tools will turn this into `FBcv:` - which is what is reflected by the `preferredPrefix` field in the metadata for both ontologies. 

I don't understand prefix maps well enough - so is the goal to maintain a bi-map? One where the prefix is unique, and the associated URL prefix is also unique? If that's so, the right way would be to _not_ have a preferred prefix for DPO at all..

**Comment by matentzn** [comment]
@cthoyt as this `wont fix`,  can you clarify further action items or otherwise close the issue?

**Comment by cmungall** [comment]
It seems simplest if DPO is omitted from bioregistry? There will be no IDs of the form DPO:nnnnn to resolve, so no need.

Being able to designate and register names for subsets of ontologies it's very useful, but this is an OBO *ontology* registry task and not something an ID prefix registry needs to worry about. On the OBO side we could do more in our metadata to state that a particular ontology ID may have no IDs minted within that space (because it's an 'application ontology', because it's a subset of an existing ontology...)

**Comment by cthoyt** [comment]
Good point! I’ve been tracking which resources don’t actually mint their own terms in the bioregistry, but it would be ideal if they were first class annotations in the OBO Foundry! Doing this could also address this discussion about what is an “application” ontology

**Comment by matentzn** [comment]
In this case though it wouldn't be an indication of application ontology, as DPO hosts first class ids.. which other ontologies did you find that not mint their own ids?

**Comment by cthoyt** [comment]
ChIRO is one example

**Comment by nlharris** [comment]
Is the problem described in the title of this issue now fixed?

**Comment by Clare72** [comment]
dpo and fbcv still both use `FBcv:` and there is no plan to change this.
This issue should probably be closed if there is nothing else to do.
