### ISSUE TITLE
Many OBO ontology repositories don't specify a LICENSE file

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1563]
The OWL and OBO formats have ontology-level metadata for linking to various accepted Creative Commons (or equivalent) permissive licenses.

GitHub also has a first-class notion of a repository-level `LICENSE` file that allows programmatic access to the licensing information, as well as adding the information to the repository overview page. For many purposes, such as reviewing the overall health of the OBO community, having direct programmatic access to this data is favorable to parsing all ontologies. The OBO Foundry also maintains the license information for some ontologies, but it's hard to tell if these are up to date and it is not always complete.

It would be nice for repositoies for OBO Foundry ontologies to maintain the LICENSE file in parallel to the structured metadata in the OWL format. Several already do. Similarly to #1538, I am thinking about automating adding issues to all repositories that do not currently have a LICENSE file. Here are two resources that I will include:

1. A tutorial on how to add a LICENSE file through the github interface - https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
2. Information about how to choose a permissive license, if one hasn't already been assigned (though to be in OBO Foundry,   I think it's already required to have a permissive license based on [fp-001](http://www.obofoundry.org/principles/fp-001-open.html)) - https://choosealicense.com/non-software/

**Comment by matentzn** [comment]
I think this is a great thing to push for. The OBO foundry could really do with a tutorial on licenses - For example, what does the LICENSE file really refer to? The OWL ontology file? The Makefile ODK pipeline? The documentation?

**Comment by nlharris** [comment]
This is a good suggestion, @cthoyt. Where on the obofoundry website should the instructions about license files go?

Also ccing @kltm (Seth) who is an expert on licenses.

**Comment by kltm** [comment]
I think the only thing I'd add here for the moment is that I'd be wary of CC-BY-SA-4.0; the Recommendations and Requirements at http://www.obofoundry.org/principles/fp-001-open.html I think do a good job explaining what is desired.

From experience, how licensing information is best communicated can depend on the audience. Options include clearly and unambiguously on website, in a repo, or in the ontology itself. It would be good to get recommendations (and howtos) into the official documentation. It would be pretty easy in a lot of cases to also have the automatic checks to make sure that these existed and were in sync.

**Comment by matentzn** [comment]
> I think the only thing I'd add here for the moment is that I'd be wary of CC-BY-SA-4.0;

Can you expand on that with a few words @kltm 

I agree we should document these recommendations on how to document the licenses very well;

**Comment by cthoyt** [comment]
> This is a good suggestion, @cthoyt. Where on the obofoundry website should the instructions about license files go?
> 
> 
> 
> Also ccing @kltm (Seth) who is an expert on licenses.

I think in the same place as the discussion about ontology licensing. I could draft some text and send it as a comment here for editing and revising, then the right committee could discuss before me or someone else can pick exactly the right place to make a PR

**Comment by kltm** [comment]
@matentzn A quick mile high perspective of why CC-BY-SA might be best not to encourage can be found here: http://reusabledata.org/license-type . The TL;DR is basically SAs behave a bit like the GPL, which is fine and good, but is not necessarily what you'd want your upstreams to have if you'd like your downstreams to be on different or flexible terms.

**Comment by matentzn** [comment]
Interesting, thank you!

**Comment by matentzn** [comment]
We discussed this at the OBO foundry call - for now, we tentatively decided against pushing for `LICENSE` files for a variety of reasons:

- The `LICENSE` file relates in a, for us, non-transparent way to our ontology licenses. There is so much code mixed up with the ontology artefacts themselves, its unclear how to draw the line when say, ODK is `MIT` and the ontology is cc-0. There is currently not enough bandwidth to really sort this out in a legally correct way unfortunately!
- The OBO foundry cares about the licenses for each other individual ontology artefacts - most people on the call believe that this is sufficient and the github LICENSE files are not strictly necessary

@cthoyt fair enough? :) let me know what you think. We are a bit of a conservative bunch (for better and for worse), so battles need to be picked extremely carefully!

**Comment by matentzn** [comment]
Closing, please re-open if stuff in here that has not been clarified.

**Comment by cthoyt** [comment]
Sorry this has been the only tab I haven’t closed in the last week because I had to do some thinking before replying. Will do ASAP

**Comment by dosumis** [comment]
+ 1 to not using SA.  We've had to contact all our data contributors on one project to try to switch to vanilla CC-BY.  We can support license stacking on the project, but as I understand it, CC-BY-SA does not mix with stricter licenses (e.g. NC - which some of our data requires).

**Comment by matentzn** [comment]
The official OBO recommendation states:

http://obofoundry.org/principles/fp-001-open.html

"OBO Foundry Ontologies MUST EITHER be released under a Creative Commons CC-BY license version 3.0 or later, OR released into the public domain under CC0. It should be clearly stated in the ontology file.

Note: CC-BY licenses allow others to distribute, remix, tweak, and build upon the work, even commercially, as long as they credit the creators for the original creation. CC0 specifies that the creators of an ontology waive, to the extent that they legally can be, all rights and place the ontology in the public domain. It does not prevent them from requesting that the ontology be properly credited and cited, but prevents any legal recourse if it is not credited..."

If this does not clearly mean "avoid SA", we should make a PR to clarify this, but IMO its sounds ok.

**Comment by kltm** [comment]
@matentzn It might be more clear to use the license and waiver full names in the first paragraph (with links); i.e. "a Creative Common Attribution 3.0 International (CC BY 3.0) license or later" and "Creative Commons CC0 public domain dedication" or something.

**Comment by matentzn** [comment]
Cool, done in #1586, can you take a peek @kltm ?
