### ISSUE TITLE
Convert ontology request form to use new-style GitHub form templates

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1571]
The current new ontology request form ([try it here](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology-request.md&title=)) is defined by a markdown template ([here](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/.github/ISSUE_TEMPLATE/new-ontology-request.md)). GitHub has recently launched a new issue template builder that creates structured forms ([see blog post](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) and [related docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)). Since there are a few issues discussing the poor compliance and low utility of the the new ontology request forms (e.g., #1457), this could be a powerful tool for us.

I've previously used these forms in combination with a script for parsing them and creating pull requests on the Bioregistry ([example script](https://github.com/bioregistry/bioregistry/blob/main/src/bioregistry/gh/new_prefix.py)) and had a good experience.

I've already begun converting this form over in my own fork of this repo by creating the [new-ontology.yml](https://github.com/cthoyt/OBOFoundry.github.io/blob/master/.github/ISSUE_TEMPLATE/new-ontology.yml) file in the `ISSUE_TEMPLATES` folder. You can try it [here](https://github.com/cthoyt/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology.yml&title=Request+for+new+ontology+%5BNAME%5D) - this form will change a bit as I try to include more of the metadata as structured fields.

**Comment by nlharris** [comment]
Thanks for doing this! I had the new issue templates on my list to investigate.

**Comment by cthoyt** [comment]
@nlharris there are a couple things that aren't so clear how they could be translated to a form and we might have to leave for free-form YAML in one of these boxes. You can see some of them that I've already made - ultimately I would like to make as many things in structured fields rather than unstructured ones. Please let me know any feedback and I can try to incorporate them.

**Comment by nlharris** [comment]
I will take a look soon (working on a grant proposal today).
