### ISSUE TITLE
License checkboxes in GitHub tickets get misinterpreted as "tasks"

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1574]
For an example, see https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1520
The ontology submitter has dutifully checked off one of the three licenses:
![Screen Shot 2021-08-21 at 12 11 00 PM](https://user-images.githubusercontent.com/348704/130332589-a42a82fd-9538-47c1-9f42-67174cd2576f.png)
GitHub interprets a checklist in the issue description as a list of tasks to be completed, and reports this issue as having 1 of 3 tasks completed, which is misleading:
![Screen Shot 2021-08-21 at 12 10 44 PM](https://user-images.githubusercontent.com/348704/130332601-d97cbc56-1ede-4afe-81b3-07d83249e927.png)

This issue may become moot when we switch to the new-style GH issue templates (#1571).

**Comment by cthoyt** [comment]
@nlharris this is a good point, unfortunately there's no GitHub flavored markdown syntax for a "radio box" which is actually the way that we'd like people to interpret this text. It may be a bit confusing if one is checking issues that have _all_ tasks finished, but this shouldn't inhibit any of the workflows as they are. I hope the new-style form template can solve this more directly!

**Comment by matentzn** [comment]
Note that eventually, the registration process is facilitated through the OBO editors app: https://editor.obolibrary.org/

This won't directly change this issue here. I think we can ignore the task/multiple choice conceptual mismatch.

**Comment by matentzn** [comment]
Closing because this cant be solved.
