### ISSUE TITLE
Automatically mark new ontology issues as stale when no recent interaction

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1575]
What is the status of this? Are we waiting for submitter action, or are they waiting for feedback from OBO Foundry?

_Originally posted by @nlharris in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1508#issuecomment-903162708_

@nlharris has recently done an exemplary job of shepherding the community of new OBO ontology submitters, but there might be a technical solution to lessen the burden on her - https://github.com/actions/stale could be used to mark any issue tagged with "new ontology" as stale (e.g., add an additional label called "stale") after a given amount of time. Perhaps the best length would be 4-6 weeks but that's up for discussion. This doesn't close the issue (which would probably make submitters upset, or even worse, lead to duplicate threads) but rather is a mark so people can filter on this tag, and more specifically consider whether to dismiss abandoned discussions later.

**Comment by nlharris** [comment]
> @nlharris has recently done an exemplary job of shepherding the community of new OBO ontology submitters

Not just recently. 😉

I appreciate the thought, but honestly, I think we get few enough new ontology submissions that trying to automate the tagging is not necessary and is more likely to cause resentment from various parties. I like the general thought of using actions to automate some of our processes, though!

**Comment by matentzn** [comment]
I agree with @nlharris - there are too few NORs for this to be worth it - we can handle this manually.
