### ISSUE TITLE
Versioning of OBO ontologies?

### ISSUE THREAD

**Issue by justaddcoffee** [OBOFoundry/OBOFoundry.github.io#1576]
Is there a versioning system for OBO Foundry ontologies, or a plan to make one? 

We are currently building a [pipeline](https://github.com/Knowledge-Graph-Hub/kg-obo) to transform OBO foundry ontologies into a format that is more amenable to graph machine learning, and it would be great to have information about versions so we could, for example, make previous versions available for reanalysis.

**Comment by balhoff** [comment]
Every ontology has (or should have) a version IRI which is stated within the ontology. Each version should be retrievable in perpetuity from its version IRI. In practice this doesn't always work, but it works for most. What we don't have, but need, is an actual listing of what versions of each ontology are available. This information is available idiosyncratically from particular ontologies (e.g. http://release.geneontology.org) but it would be great to keep this in RDF, for the whole library. I have some vague plans to do this. 😄

**Comment by justaddcoffee** [comment]
Thanks @balhoff!

**Comment by nlharris** [comment]
See also #771 and #1414 

Are there action items here? Should this ticket be kept open?

**Comment by justaddcoffee** [comment]
I think for our purposes we can close this, since I think we can just use the version IRI

Thanks for the link to the existing tickets - the discussions of versioning there are along the lines of what I was hoping to find, but version IRIs should work fine too

**Comment by cthoyt** [comment]
I’ve been interested in this recently as well and am keeping track of the current versions of all ontologies and other biomedical resources I can at https://github.com/cthoyt/bioversions

**Comment by alanruttenberg** [comment]
You should be able to scrape the versions from https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

**Comment by cmungall** [comment]
Most ontologies I'm aware of use a generic redirect for versions so this
won't work
