### ISSUE TITLE
issue tracker for Ontology review request still points to googlecode

### ISSUE THREAD

**Issue by cstoeckert** [OBOFoundry/OBOFoundry.github.io#158]
On http://www.obofoundry.org/docs/ReviewProcessGuidelines.html
Under How to request an ontology review. The issue tracker link goes to google code.

**Comment by cmungall** [comment]
Hi Chris, you should be able to edit this easily, click on the edit button on the bottom. You may have to make a PR, we can give everyone in the relevant WGs permission if I have a list of gh usernames

**Comment by cstoeckert** [comment]
Thanks Chris. Was able to fix one but see that the page needs further updating. Am checking with the Editorial Working Group on proposed changes.
