### ISSUE TITLE
Any ideas for an OBO volunteering scheme?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1589]
As a volunteering organisation, we are reliant on contributions from the community - for advice, coding, and many other aspects of our work. 

OBO is currently a bit "old" - full of super experienced people with little to no time for doing the smaller things. However, we have a great need in particular in the area of web development which could be accomplished by more junior developers. I am wondering this:

Does anyone out there in the OBO sphere know students that would like to get some real-world exposure for some coding that could be highly impactful and look nice on a CV? I would sort out stuff like volunteering badges/certificates if this helps with anything, if people with more access to undergrad level students (or MSc) could help me organising the volunteering effort as a whole. I have marked some issues that obviously I would clarify with action items before we unleashed them on anyone [here](https://github.com/OBOFoundry/OBOFoundry.github.io/labels/volunteering-scheme).

If you have any ideas moving this forward, that would be great.

Aside from that,  at the last OFOC call yesterday (7 Sep 21) we also discussed that:
- we may be able to tap into the Biocuration microgrants? ~ USD $500 (500 CHF)
- ensure that our grants all list a significant proportion of contractor money for OBO related tasks (note that the overhead of setting up contracts is huge, so keep that in mind)
- recruit trainees from our ongoing OBO training programmes
- Find a good pot of money to apply for an OBO grant.

**Comment by jamesaoverton** [comment]
In my opinion, the fastest and easiest way to get smallish things done is for funded projects (i.e. databases) that use OBO and have junior (web) developers on staff to donate a few of their hours. We can find a few hours for experienced OBO Technical Working Group people to bring them up to speed on specific tasks, and review the results.

If you have junior developers with some extra time, please let us know. They'll learn some new skills, so it should be a win-win.

Here's my perspective on the other options. For the past 10 years my career has been 100% contract work for grant-funded projects using OBO.

- I agree that it's good for everyone to write a small OBO budget into new grant applications. OBO Operations is happy to write letters of support.
- Regarding microgrants: I don't know how much paperwork this requires, but I would much rather spend the time writing code than filing paperwork and chasing invoices for such a small sum.
- Regarding an OBO grant: We've always talked about chasing grants, but the only one we've ever actually applied for (and won) was the OBO Technical Services grant. It was a rare funding opportunity for hardening existing open source community tooling: three years, non-renewable. We used it for many things: ROBOT (especially `robot report`), PURL system updates, OBO registry manual review and code updates, the OBO Dashboard, starting on COB, and other stuff I'm forgetting at the moment. We submitted this paper to summarize a bunch of that work: <https://www.biorxiv.org/content/10.1101/2021.06.01.446587v1>. Good grant opportunities are rare, grant submission takes immense effort, it's high risk, overhead costs are high, and the timelines are long.
- Regarding contracts: I spend way more time and effort than you might expect dealing with paperwork. Once a grant lands, it still takes six months (on average) for me to start get paid for work with a new client. Asking people (especially junior people) to work without getting paid for months on end is asking a lot. Generally speaking, institutions that are big enough to win grants are built to deal with other large institutions, and they are very bad at dealing with small businesses and independent contractors. Government funding comes with government bureaucracy.

**Comment by matentzn** [comment]
Awesome, thank you @jamesaoverton; I totally agree with the entire assessment!

**Comment by cthoyt** [comment]
@matentzn reminder to reach out to @mazpar about this

**Comment by matentzn** [comment]
@mazpar and others: basically we are in the early stages of defining a scheme for volunteer involvement at the OBO Foundry, which is an open organisation whose goal is to organise biomedical knowledge. We have some open problems around web development that require some attention and have only a loose timeline. I would volunteer to mentor you or anyone  that would like to go in this direction. Tasks involve things like making a searchable table for our metadata (basically make this table http://obofoundry.org/ of ontologies sortable, and other related issues). If you are interested to tackle some of that, please reach out and I am happy to walk you through the issue. Right now, volunteering is obviously chaos, but as a byproduct of your early involvement we can perhaps streamline this.

**Comment by mazpar** [comment]
@matentzn I would be interested in this. Most likely starting December I would have some free time to devote to this as currently I have too much on my plate.

**Comment by matentzn** [comment]
Awesome @mazpar - no strings attached, I will ping you again in December to see whether you are interested then!

**Comment by matentzn** [comment]
Hey @mazpar - we have a bit of work that needs to be done around the website presentation, in particular work with:

- jinja templates
- html
- yaml metadata

Let me know if you are still interested.

**Comment by nlharris** [comment]
@mazpar just checking to see if you're interested in this.

**Comment by cmungall** [comment]
Are there any actionable outcomes that will close this issue? Should we move this to Discussions? Should we have a short section on volunteering on one of the pages?

**Comment by matentzn** [comment]
No, I think all the discussion was had; there is no more specific thing to be done here.
