### ISSUE TITLE
Evaluate alternatives to OCLC/Purlz

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#159]
Example:
https://github.com/jamesaoverton/obo-purls

**Comment by cmungall** [comment]
Relevant thread:

https://groups.google.com/forum/#!topic/persistenturls/Qp4RPPvZey4

**Comment by cmungall** [comment]
Proposed list of requirements:

 1. able to redirect exact or partial URL suffixes
 2. reliable
 3. transparent mechanism
 4. permanent record of which URL suffixes have every been registered or used
 5. ability to roll back
 6. easy of editing from both community and obo-admins
 7. lightweight/low cost maintenance
 8. no need for additional middleman servers

**Comment by alanruttenberg** [comment]
Note that w3id.org requires https URLs so we would need to have some host in-between redirecting http to https.

**Comment by alanruttenberg** [comment]
I'm not keen on the idea of ontology developers having to write apache directives. For one thing it means that we are required to review every change, as I'm sure that Apache is close to, if not, turing complete.

For the moment I'm assuming that this will be short term. On that basis here's an idea: 

1) Authentication: Send a generated token to each of the emails of people listed as ontology point persons in our existing metadata.

2) Make a google form similar with similar fields as current - 
 - choice of absolute or partial redirect
 - purl path
 - redirection string
 - ontology prefix
 - token

This fills a google spreadsheet (token in hidden column so we can share spreadsheet for read by all)

A script periodically translates this into apache directives.
- It only uses rules where token and namespace match
- Later same rules take precedent over earlier ones.
- Invalid rules are ignored.
- Extra bonus: Rules that violate syntax or other constraints trigger email to ontology point person, reverse looked up by token.

Several of us with machines put up an apache server specifically for this purpose (everything else disabled), and periodically pull the script output (can be put on github).
We set up the DNS for purl.obolibrary.org to round-robin our machines

For any use that doesn't fit in this model you need to submit a ticket.

PROs - 
- Simple interface for free. 
- Don't have to worry about vetting written apache directives
- purl "domains" come for free
- fixing/maintaining is mostly editing spreadsheet
- we can choose level of redundancy
- easy for us to add another redundant provider
- simple enough input that we don't *have* to use apache if for some reason we don't want to - it would be easy to change to another redirection mechanism

CONs -
- Need to think about denial of service. Perhaps an IFTTT script that periodically cleans rows without valid tokens
- There is some work to do in writing the script.

I can offer a machine at the Dental School. Chris already has a machine running. 

I'm sure there are more cons, but I'm not going to spend time finding more  for now - I'm interested in hearing your thoughts. 

In the interim I am trying to see whether there's a future for purl.oclc.org. Despite Jeff's comment re:w3id I have doubts about whether it would be a reliable long-term solution.

**Comment by jamesaoverton** [comment]
Chris, Seth, and I have been improving the system here: https://github.com/jamesaoverton/obo-purls

We had been planning on using raw Apache config, but decided against it for the reasons Alan points out.

The system now uses a simple YAML configuration file per-project, and a Python script to translate YAML to Apache configuration. We tried a tabular format, but long lines made it easier to read and write the YAML. The translation step lets us constrain and validate the entries. There's also code for migrating OCLC XML records to YAML.

Tomorrow I plan to set up automated testing and set up a server.

**Comment by jamesaoverton** [comment]
I've set up automated testing, started a test server, and improved the documentation. Please take a look: https://github.com/jamesaoverton/obo-purls

**Comment by jamesaoverton** [comment]
On the OFOC call today we decided to move forward with the new system. I have transferred the repository to https://github.com/OBOFoundry/purl.obolibrary.org. Development will continue there: please follow that issue tracker for updates.
