### ISSUE TITLE
Link to standard Medical Terminologies

### ISSUE THREAD

**Issue by meghbhalerao** [OBOFoundry/OBOFoundry.github.io#1591]
<Apologies, my question does not fit into any standard issue templates.>

Dear Authors, 

I am working on the datasets in http://obofoundry.org, and I wanted to know this - are the concepts mentioned in the .obo datasets linked to any larger medical terminology database such as MEDIC, UMLS (Unified Medical Language System) and others.

For example in the cl.obo dataset a query "nerve of hindlimb" is mapped to "hindlimb nerve" concept. I was wondering if this same query is mapped to any larger syonym set of a standard biomedical knowledge base?

Does my question make sense?

Please let me know if something is unclear. 
Thanks and looking forward to hearing from you.
Megh

**Comment by nataled** [comment]
@cmungall and/or @addiehl can you address this question?

**Comment by nlharris** [comment]
@nicolevasilevsky or @matentzn might also know.

**Comment by mellybelly** [comment]
Many of the more clinically focused ontologies have xrefs to medical terminologies. However, until SSSOM mapping files are available for each ontology, you can expect heterogeneous population of the xrefs and little to no documentation regarding how the mappings were created. 

Relating to MEDIC, Mondo was created in part to create robust equivalence mappings across disease ontologies, and this includes MEDIC and related resources. See https://mondo.monarchinitiative.org/pages/sources/ for more info.

**Comment by matentzn** [comment]
To add to @mellybelly I would say that the most systematic maps to the larger clinical space are from HPO to Mesh (I think you can get these from UMLS), 

There are some from MedGen to Mondo (see for example [here](https://www.ncbi.nlm.nih.gov/medgen/C0220668)) which you can get from Mondo itself (as @mellybelly says, its probably best to wait for the [sssom mappings](https://github.com/monarch-initiative/mondo/tree/sssom-rewrite/src/ontology/mappings) to be officially included in the release, but in the meantime, you can get the links simply from the Mondo ontology artefact, e.g. https://mondo.monarchinitiative.org/.

There is a large amount of biomedical research data at EBI annotated also with [EFO](https://www.ebi.ac.uk/efo/), which uses Mondo, but maintains a lot of mappings where it does not.

There are other mappings to consider, like Uberon-FMA which are a bit outdated and available through https://github.com/obophenotype/uberon, and with CL, there is a lot of work going on in the Human Cell Atlas and Brain Data Standards projects (@dosumis may be able to help here). 

In generally we want to become better as a community at mapping to outside terminologies - and slowly moving in that direction :)

**Comment by nlharris** [comment]
@meghbhalerao does this sufficiently answer your question?

**Comment by nlharris** [comment]
Closing; please reopen if needed!
