### ISSUE TITLE
integration with ontobee

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#16]
cc @ontoden

We could just output ontologies.txt from https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/ontologies.yml

But may be better if ontobee could take the native format directly. Note the new yaml offers better possibilities for ontobee users. For example, some ontologies have >1 namedGraph imported, but this is AFAICT done informally using an ad-hoc internal registry, which we can now centralize

I believe the new OLS takes in the yaml, cc @simonjupp

**Comment by ontoden** [comment]
Sounds good. We (Ontobee) will take a look at the yaml format and see how we can use it. 
Oliver He

**Comment by cmungall** [comment]
Check out the simple python script `util/processor.py` to see some examples of processing the yaml - e.g. there is a command that will mirror all products on a local drive.

Note there are some interesting possibilities for ontobee - some ontologies like to have two different products on ontobee, or have the version loaded be something different from their canonical product (for example, for go we would like to have go-plus.owl loaded). Rather than hacking this with the separate ontobee repo as we have done in the past, we can simply add tags such as 'load_into_ontobee: true' - suggestions welcome

**Comment by ontoden** [comment]
I like the idea. To have tags like 'load_into_ontobee: true'  would fit well with different needs.

Oliver

**Comment by cmungall** [comment]
cc @simonjupp, comments about having different "editions" of ontologies, with a selected subset of editions available in a browser. Or having a 'non-standard' edition be the default in advanced browsers. E.g. go-plus for GO, cc @dosumis

**Comment by simonjupp** [comment]
Are there many ontologies that have these "editions" then? 

I'm more in favour of loading the full edition and having better support to extract views/subsets from the full edition. I think we can show  things like the basic view on the fly, and we are also contemplating some other view options like "hide upper-ontology terms by default".

We will support views from slims defined in the ontology and we also have plans to support more data driven views, so generating a view from a given a list of terms or set of annotations.

I'm also happy to honour any "load_into_ols:true" tag if you go that way.

**Comment by cmungall** [comment]
On 23 Sep 2015, at 23:47, simonjupp wrote:

> Are there many ontologies that have these "editions" then?

Well technically subsets count as distinct products but of course there 
is no use case to load these as a separate graph. There aren't many 
'superset' editions. The two main uses are GO (go.owl has any 
external-pointing axioms slimmed out) and uberon 
(https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies)

> I'm more in favour of loading the full edition and having better 
> support to extract views/subsets from the full edition. I think we can 
> show  things like the basic view on the fly, and we are also 
> contemplating some other view options like "hide upper-ontology terms 
> by default".

Makes sense

> We will support views from slims defined in the ontology and we also 
> have plans to support more data driven views, so generating a view 
> from a given a list of terms or set of annotations.

Yep

> I'm also happy to honour any "load_into_ols:true" tag if you go that 
> way.
