### ISSUE TITLE
Add behave/selenium tests

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#161]
Would be neat for testing PRs that affect the UI, e.g.
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/160

**Comment by nlharris** [comment]
is this still something that needs to be done?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by matentzn** [comment]
My humble opinion is that this is so deep frozen ice box (low down the list of priorities) it may as well be closed.

**Comment by nlharris** [comment]
since no one else has defended this poor frozen ticket, i'm closing it. feel free to thaw (reopen) it if desired.
