### ISSUE TITLE
Consider adding example identifiers for ontologies in metadata

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1622]
I'd like to propose we add a new optional field for the ontology metadata to store an example identifier.

It appears that the configuration files for the [purl.obolibrary.org](https://github.com/OBOFoundry/purl.obolibrary.org) repository already contain example terms using the "short form" syntax, which is like a CURIE but with an underscore `_` as the delimiter, so perhaps these could be taken in.

Here's an example for AMPHX: https://github.com/OBOFoundry/purl.obolibrary.org/blob/133f728664392330251717ee4c0f4564c0d1799b/config/amphx.yml#L11-L12

Related: I recently made a comment https://github.com/OBOFoundry/OBOFoundry.github.io/issues/400#issuecomment-936724635 on a thread talking about different properties of ontologies that could be used to classify them, potentially moving towards a real definition of "reference" vs. "application" ontology. Having this as a first class annotation of an example could address one of the issues that tells us if an ontology mints its own identifiers

**Comment by jamesaoverton** [comment]
My point is that the OBO PURL system was designed to fill a specific, narrow purpose. It converts the YAML config files into Apache .htaccess files. For example, it doesn't really know about the `purl.obolibrary.org` domain, so you can run it locally like <http://localhost:8080/obo/OBO_0000070>.

If you want to convert those `example_terms` to CURIEs, then I would suggest constructing an IRI by concatenating `http://purl.obolibrary.org/obo/` with the Term ID `OBI_000070` to get <http://purl.obolibrary.org/obo/OBI_0000070>, and then using the prefixes defined in [`obo_context.jsonld`](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/obo_context.jsonld) to convert that IRI to a CURIE. If that doesn't work, there's a bug somewhere.

**Comment by balhoff** [comment]
> @balhoff what could we do to fix obo context? Tldr on that ticket you linked..

I'll open another ticket.

**Comment by cthoyt** [comment]
Thanks everyone for the discussion. My ultimate goal was to make sure that Bioregistry could import OBO Foundry ontologies, including an example. Since it's required that OBO Foundry ontologies have PURL configuration and that it can be deterministically accessed via URL, my original goal is solvable without making any convolution of concerns.
