### ISSUE TITLE
Clarify documentation of usage

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1627]
To clearly understand what counts as a "usage", we need to clarify the documentation on the principle, and some instructions for how to review pull requests.

From the OBOC call today:

-  Usage is not "usage" but "documented usage" of even more precisely, "evidence of use". 
- An evidence of use can be established by one of two ways: 
   - A link to a URL that resolves to a term, such as https://platform.opentargets.org/disease/HP_0003614
   - A link to a technical document that describes how _individual terms_ of the ontology are used in the system (mentioning at least one id by name)
- A link to a page saying "I am using ontology X" is not sufficient anymore!

So I, as a pull request reviewer, need to know _exactly_ what is acceptable "evidence of use".

**Comment by matentzn** [comment]
## For OFOC call:

We need to clarify _explicitly_ whether an "evidence of usage" must be established during submission. As it stands, you _have to_, as we currently require the dashboard to pass.

**Comment by nataled** [comment]
Quick note: this principle is one that applies at the time of (manual) review, not at time of submission. Given the uncertainty surrounding the review process and Foundry vs Library status, it's unclear at what point this principle should be applied, if at all.

**Comment by nataled** [comment]
From OFOC call:

Currently, the principle states “An ontology that has not been used by other than the developer(s) is not yet ready for review. Note that the ontology can still be listed in other ontology portals such as the OBO Library”

**Issue:** It might not be clear what is meant by 'review' here, especially in light of the downplay of manual reviews. The only hint is the following sentence, which mentions that library status is not impeded by this principle.

**Issue:** The OBO Library is not an 'other ontology portal'. Can (minimally) revise sentence to remove ' other ontology portals such as'

**Issue:** Again, given the downplay of manual reviews, the distinction about 'still be listed in the OBO Library' might be confusing.

One suggestion regarding the Dashboard focused on the fact that this principle is one that doesn't apply to new submissions, but does apply to what we can call 'mature' ontologies. @cmungall suggested that some wording be added to our documentation saying, in effect, that dashboard flags for this principle can be ignored for new ontologies.

Another suggestion regarding the Dashboard focused on the tiered levels of acceptance. For example, the ontology would Pass if there are 3+ usages, get a Warning for 2 usages, and get an Info flag for 0-1 usages.

ACTION ITEMS:
- EWG will clarify wording
- Add note to SOPs that new submissions can ignore this flag
- Further discussion needed, as we did not get to discuss exactly what qualifies as evidence of usage

**Comment by matentzn** [comment]
My preference would be that for NORs, we explicitly exclude the usage as a criterion, but keep it _red_ both on the main dashboard and the NOR dashboard when no usage is provided. Review here means purely "determining whether the minimum criteria for being listed in the OBO foundry ontology catalog are fulfilled", ie: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md

**Comment by nataled** [comment]
On the principle page, under 'Criteria for Review', we need to state that this can be ignored for new ontologies. A similar statement will need to be added to any NOR documentation pages or forms.
