### ISSUE TITLE
Many license annotations don't match what's in the ontology

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1636]
As a follow-up to #1635, it's worth noting the Bioregistry is tracking conflicts between the OBO Foundry's license metadata (which is manually curated) and the OLS's license metadata (which I think is parsed from the ontology). There are several remaining conflicts to address, listed at https://biopragmatics.github.io/bioregistry/warnings/#license-conflicts.

You could also use the following Python code to generate the table

```python
from tabulate import tabulate

from bioregistry import manager

if __name__ == '__main__':
    print(tabulate(
        manager.get_license_conflicts(),
        headers=['prefix', 'override', 'obo', 'ols'],
        tablefmt='github',
    ))
```

I'll include it here in addition to the one on the website

| prefix   | obo       | ols                                                |
|----------|-----------|----------------------------------------------------|
| aism     | CC-BY     | https://creativecommons.org/licenses/by/4.0/       |
| amphx    | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| apollosv | CC-BY 3.0 | https://creativecommons.org/licenses/by/4.0/       |
| bspo     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| chmo     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| cido     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| cl       | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| clao     | CC-0      | https://creativecommons.org/licenses/by/4.0/       |
| cto      | CC-BY     | http://creativecommons.org/licenses/by/4.0         |
| dpo      | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| dron     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| duo      | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| envo     | CC-BY     | https://creativecommons.org/publicdomain/zero/1.0/ |
| eupath   | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| fbbt     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| fbcv     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| fbdv     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| fobi     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| foodon   | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| fypo     | CC-BY     | https://creativecommons.org/licenses/by/4.0/       |
| genepio  | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| hso      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| iao      | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| iceo     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| ico      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| maxo     | CC-BY     | https://creativecommons.org/licenses/by/4.0/       |
| mf       | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| mfoem    | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| mro      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| oae      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| obib     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| ogg      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| ogms     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| ogsf     | CC-BY 3.0 | New BSD license                                    |
| ohpi     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| ons      | CC-BY     | https://creativecommons.org/licenses/by/4.0/       |
| ontoneo  | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| oostt    | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| opmi     | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| pato     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| phipo    | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| plana    | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| planp    | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| pr       | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| psdo     | CC-BY     | https://creativecommons.org/licenses/by/4.0/       |
| rbo      | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| stato    | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| txpo     | CC-BY 3.0 | http://creativecommons.org/licenses/by/4.0/        |
| uberon   | CC-BY     | http://creativecommons.org/licenses/by/3.0/        |
| vo       | CC-BY     | http://creativecommons.org/licenses/by/4.0/        |
| xao      | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| xpo      | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| zeco     | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |
| zfa      | CC-BY     | https://creativecommons.org/licenses/by/3.0/       |

**Comment by matentzn** [comment]
Great effort to look for conflicts here! I think two things are conflated here:

1. in OBO metadata the license has two fields, `url` and `label`. The first thing to check would be whether these two are in conflict - the current validator allows all sorts of variations on the label, and I wouldn't be surprised if there was a CC-BY 3.0 label paired with a 4.0 URL. So this I would check first
2. OLS always uses OBO metadata directly. So there cant be any conflicts - the table you present here looks like it is comparing the OBO license.label property with the dc:license annotation in the ontology. Can you clarify where what information comes from? OLS uses the OBO metadata file directly!

```
license:
  url: https://creativecommons.org/licenses/by/4.0/
  label: CC-BY
```

**Comment by cthoyt** [comment]
Thanks for the feedback, Nico. I'm going to close this issue and open a clean one with a better table
