### ISSUE TITLE
Non-obsolete ontologies are missing licenses (and contact information)

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1637]
There are several ontologies that are not marked as deprecated that don't have licenses (though it might be the case that all are orphaned). Worse, these ontologies are offenders in not having very well-documented metadata on how to get in touch or request improvements:

| prefix                                            | contact       | email                   | github   | tracker   |
|---------------------------------------------------|---------------|-------------------------|----------|-----------|
| [fix](http://www.obofoundry.org/ontology/fix)     | chEBI         |                         |          |           |
| [miro](http://www.obofoundry.org/ontology/miro)   | C. Louis      | louis@imbb.forth.gr     |          |           |
| [ogi](http://www.obofoundry.org/ontology/ogi)     |               |                         |          |           |
| [rex](http://www.obofoundry.org/ontology/rex)     |               |                         |          |           |
| [vario](http://www.obofoundry.org/ontology/vario) | Mauno Vihinen | mauno.vihinen@med.lu.se |          |           |

The following code was used to produce this table after running `pip install bioregistry`:

```python
from tabulate import tabulate

from bioregistry.external.obofoundry import get_obofoundry


def main():
    rows = []
    for key, entry in sorted(get_obofoundry(force_download=True).items()):
        if entry["deprecated"]:
            continue
        license_label = entry.get("license")
        license_url = entry.get("license.url")
        if license_label is None and license_url is None:
            contact_email = entry.get("contact", "")
            contact_name = entry.get("contact.label", "")
            contact_github = entry.get("contact.github", "")
            tracker = entry.get("tracker", "")
            rows.append((
                f"[{key}](http://www.obofoundry.org/ontology/{key})",
                contact_name,
                contact_email,
                contact_github and f"@{contact_github}",
                tracker,
            ))

    print(tabulate(
        rows,
        headers=["prefix", "contact", "email", "github", "tracker", ],
        tablefmt="github",
    ))


if __name__ == '__main__':
    main()
```

**Comment by cthoyt** [comment]
After doing some digging in the PURL system, there is some GitHub information available:

- MIRO's https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/miro.yml leads to https://github.com/VEuPathDB-ontology/MIRO
- FIX leads to yet another redirect via http://ontologies.berkeleybop.org/fix.owl (not sure if this is an actual address). This is a ChEBI resource so I would say to mirror the contact information from ChEBI
- OGI points to https://ontology-for-genetic-interval.googlecode.com. This link is down, this resource no longer exists. It should be marked as obsolete/deprecated/abandoned
- REX points to http://ontologies.berkeleybop.org/rex.owl and has been noted to have been last edited by "kirill"
- VariO points to a website that is completely opaque to the curation process

**Comment by nlharris** [comment]
Pinging @GerardGH again

**Comment by cthoyt** [comment]
It's worth noting that when I wrote the code that checked this, I was unaware of the difference between the obsolete label and inactive/orphaned labels.  These five ontologies are all marked as orphaned, and should therefore be disregarded for most checks. I think it's okay to close this, though any input would be welcome
