### ISSUE TITLE
Many ontologies' license labels and URLs don't match

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1638]
As a follow-up to #1635 and with some wisdom from Nico given in related issue #1636, there are several conflicts between the license labels and license URLs. Most of these are due to the lack of specificity of the CC-BY version. 

How to fix:

1. Open up your ontology's markdown file in https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology
2. Press the pencil icon in the top right to edit
3. Fix the license label. E.g., update from `CC-BY` to `CC-BY 3.0` or `CC-BY 4.0`
4. Scroll to the bottom and press the big green button to propose a pull request

See example PR at https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1639, 30 second tutorial video at https://www.youtube.com/watch?v=hGokszEUZtA.

Here's a table of all the ontologies with this issue, plus the actionable contact information on who is responsible for each in case someone is inclined to nudge them:

| prefix                                                | license_label   | license_url                                     | contact                    | email                                    | github                        | tracker                                                                        |
|-------------------------------------------------------|-----------------|-------------------------------------------------|----------------------------|------------------------------------------|-------------------------------|--------------------------------------------------------------------------------|
| [aism](http://www.obofoundry.org/ontology/aism)       | CC-BY           | https://creativecommons.org/licenses/by/4.0/    | Jennifer C. Girón          | entiminae@gmail.com                      |                               | https://github.com/insect-morphology/aism                                      |
| [amphx](http://www.obofoundry.org/ontology/amphx)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Hector Escriva             | hescriva@obs-banyuls.fr                  |                               | https://github.com/EBISPOT/amphx_ontology                                      |
| [aro](http://www.obofoundry.org/ontology/aro)         | CC-BY           | https://creativecommons.org/licenses/by/4.0/    | CARD                       | card@mcmaster.ca                         | @raphenya                     | https://github.com/arpcard/aro                                                 |
| [bfo](http://www.obofoundry.org/ontology/bfo)         | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Barry Smith                | phismith@buffalo.edu                     | @phismith                     | https://github.com/BFO-ontology/BFO                                            |
| [bspo](http://www.obofoundry.org/ontology/bspo)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Chris Mungall              | cjmungall@lbl.gov                        | @cmungall                     | https://github.com/obophenotype/biological-spatial-ontology                    |
| [cdno](http://www.obofoundry.org/ontology/cdno)       | CC-BY           | https://creativecommons.org/licenses/by/3.0/    | Liliana Andres Hernandez   | l.andres.hernandez.18@student.scu.edu.au | @LilyAndres                   | https://github.com/Southern-Cross-Plant-Science/cdno                           |
| [chmo](http://www.obofoundry.org/ontology/chmo)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Colin Batchelor            | batchelorc@rsc.org                       | @batchelorc                   | https://github.com/rsc-ontologies/rsc-cmo                                      |
| [cido](http://www.obofoundry.org/ontology/cido)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   |                               | https://github.com/cido-ontology/cido                                          |
| [cl](http://www.obofoundry.org/ontology/cl)           | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Alexander Diehl            | addiehl@buffalo.edu                      | @addiehl                      | https://github.com/obophenotype/cell-ontology                                  |
| [clo](http://www.obofoundry.org/ontology/clo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Sirarat Sarntivijai        | siiraa@umich.edu                         |                               | https://github.com/CLO-Ontology/CLO                                            |
| [clyh](http://www.obofoundry.org/ontology/clyh)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Lucas Leclere              | lucas.leclere@obs-vlfr.fr                | @L-Leclere                    | https://github.com/EBISPOT/clyh_ontology                                       |
| [cro](http://www.obofoundry.org/ontology/cro)         | CC-BY           | https://creativecommons.org/licenses/by/2.0/    | Marijane White             | whimar@ohsu.edu                          | @marijane                     | https://github.com/data2health/contributor-role-ontology                       |
| [cteno](http://www.obofoundry.org/ontology/cteno)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Chris Mungall              | cjmungall@lbl.gov                        | @cmungall                     | https://github.com/obophenotype/ctenophore-ontology                            |
| [cto](http://www.obofoundry.org/ontology/cto)         | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Dr. Alpha Tom Kodamullil   | alpha.tom.kodamullil@scai.fraunhofer.de  | @akodamullil                  | https://github.com/ClinicalTrialOntology/CTO                                   |
| [dpo](http://www.obofoundry.org/ontology/dpo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Clare Pilgrim              | cp390@cam.ac.uk                          |                               | https://github.com/FlyBase/drosophila-phenotype-ontology                       |
| [dron](http://www.obofoundry.org/ontology/dron)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | William Hogan              | hoganwr@gmail.com                        |                               | https://github.com/ufbmi/dron/                                                 |
| [duo](http://www.obofoundry.org/ontology/duo)         | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Melanie Courtot            | mcourtot@gmail.com                       | @mcourtot                     | https://github.com/EBISPOT/DUO                                                 |
| [ecao](http://www.obofoundry.org/ontology/ecao)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Charles Ettensohn          | ettensohn@cmu.edu                        | @ettensohn                    | https://github.com/echinoderm-ontology/ecao_ontology                           |
| [ecocore](http://www.obofoundry.org/ontology/ecocore) | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Pier Luigi Buttigieg       | p.buttigieg@gmail.com                    | @pbuttigieg                   | https://github.com/EcologicalSemantics/ecocore                                 |
| [envo](http://www.obofoundry.org/ontology/envo)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Pier Luigi Buttigieg       | p.buttigieg@gmail.com                    | @pbuttigieg                   | https://github.com/EnvironmentOntology/envo                                    |
| [eupath](http://www.obofoundry.org/ontology/eupath)   | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Chris Stoeckert            | stoeckrt@pennmedicine.upenn.edu          | @cstoeckert                   | https://github.com/VEuPathDB-ontology/VEuPathDB-ontology                       |
| [fbbt](http://www.obofoundry.org/ontology/fbbt)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Clare Pilgrim              | cp390@cam.ac.uk                          |                               |                                                                                |
| [fbcv](http://www.obofoundry.org/ontology/fbcv)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Clare Pilgrim              | cp390@cam.ac.uk                          |                               | https://github.com/FlyBase/flybase-controlled-vocabulary                       |
| [fbdv](http://www.obofoundry.org/ontology/fbdv)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Clare Pilgrim              | cp390@cam.ac.uk                          |                               |                                                                                |
| [fobi](http://www.obofoundry.org/ontology/fobi)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Pol Castellano Escuder     | polcaes@gmail.com                        | @pcastellanoescuder           | https://github.com/pcastellanoescuder/FoodBiomarkerOntology                    |
| [foodon](http://www.obofoundry.org/ontology/foodon)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Damion Dooley              | damion_dooley@sfu.ca                     | @Public-Health-Bioinformatics | https://github.com/FoodOntology/foodon                                         |
| [fypo](http://www.obofoundry.org/ontology/fypo)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Midori Harris              | mah79@cam.ac.uk                          | @mah11                        | https://github.com/pombase/fypo                                                |
| [genepio](http://www.obofoundry.org/ontology/genepio) | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Damion Dooley              | damion_dooley@sfu.ca                     |                               | https://github.com/GenEpiO/genepio                                             |
| [geno](http://www.obofoundry.org/ontology/geno)       | CC-BY-SA        | https://creativecommons.org/licenses/by-sa/2.0/ | Matthew Brush              | mhb120@gmail.com                         | @mbrush                       | https://github.com/monarch-initiative/GENO-ontology                            |
| [hsapdv](http://www.obofoundry.org/ontology/hsapdv)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | bgee                       | bgee@sib.swiss                           |                               | https://github.com/obophenotype/developmental-stage-ontologies                 |
| [hso](http://www.obofoundry.org/ontology/hso)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Fernanda Dorea             | fernanda.dorea@sva.se                    | @nandadorea                   | https://github.com/SVA-SE/HSO                                                  |
| [iao](http://www.obofoundry.org/ontology/iao)         | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Jie Zheng                  | jiezheng@pennmedicine.upenn.edu          | @zhengj2007                   | https://github.com/information-artifact-ontology/IAO                           |
| [iceo](http://www.obofoundry.org/ontology/iceo)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Meng LIU                   | liumeng94@sjtu.edu.cn                    |                               | https://github.com/ontoice/ICEO                                                |
| [ico](http://www.obofoundry.org/ontology/ico)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   | @yongqunh                     | https://github.com/ICO-ontology/ICO                                            |
| [ino](http://www.obofoundry.org/ontology/ino)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   |                               | https://github.com/INO-ontology/ino                                            |
| [maxo](http://www.obofoundry.org/ontology/maxo)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Leigh Carmody              | Leigh.Carmody@jax.org                    | @LCCarmody                    | https://github.com/monarch-initiative/MAxO                                     |
| [mco](http://www.obofoundry.org/ontology/mco)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Citlalli Mejía-Almonte     | citlalli.mejiaalmonte@gmail.com          |                               | https://github.com/microbial-conditions-ontology/microbial-conditions-ontology |
| [mf](http://www.obofoundry.org/ontology/mf)           | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Janna Hastings             | janna.hastings@gmail.com                 | @jannahastings                | https://github.com/jannahastings/mental-functioning-ontology                   |
| [mfmo](http://www.obofoundry.org/ontology/mfmo)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Robert Druzinsky           | druzinsk@uic.edu                         | @RDruzinsky                   | https://github.com/RDruzinsky/feedontology                                     |
| [mfoem](http://www.obofoundry.org/ontology/mfoem)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Janna Hastings             | janna.hastings@gmail.com                 | @jannahastings                | https://github.com/jannahastings/emotion-ontology                              |
| [mfomd](http://www.obofoundry.org/ontology/mfomd)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Janna Hastings             | janna.hastings@gmail.com                 |                               | https://github.com/jannahastings/mental-functioning-ontology                   |
| [mmusdv](http://www.obofoundry.org/ontology/mmusdv)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | bgee                       | bgee@sib.swiss                           |                               | https://github.com/obophenotype/developmental-stage-ontologies                 |
| [mpath](http://www.obofoundry.org/ontology/mpath)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Paul Schofield             | pns12@hermes.cam.ac.uk                   |                               | https://github.com/PaulNSchofield/mpath                                        |
| [mpio](http://www.obofoundry.org/ontology/mpio)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Mathias Brochhausen        | mbrochhausen@uams.edu                    | @mbrochhausen                 | https://github.com/MPIO-Developers/MPIO                                        |
| [mro](http://www.obofoundry.org/ontology/mro)         | CC-BY           | https://creativecommons.org/licenses/by/3.0/    | Bjoern Peters              | bpeters@lji.org                          | @bpeters42                    | https://github.com/IEDB/MRO                                                    |
| [ms](http://www.obofoundry.org/ontology/ms)           | CC-BY           | https://creativecommons.org/licenses/by/3.0/    | Gerhard Mayer              | gerhard.mayer@rub.de                     |                               | https://github.com/HUPO-PSI/psi-ms-CV                                          |
| [nbo](http://www.obofoundry.org/ontology/nbo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | George Gkoutos             | g.gkoutos@bham.ac.uk                     | @gkoutos                      | https://github.com/obo-behavior/behavior-ontology                              |
| [oae](http://www.obofoundry.org/ontology/oae)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqunh He                | yongqunh@med.umich.edu                   |                               | https://github.com/OAE-ontology/OAE                                            |
| [obcs](http://www.obofoundry.org/ontology/obcs)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Jie Zheng                  | jiezheng@pennmedicine.upenn.edu          |                               | https://github.com/obcs/obcs                                                   |
| [obib](http://www.obofoundry.org/ontology/obib)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Jie Zheng                  | jiezheng@pennmedicine.upenn.edu          |                               | https://github.com/biobanking/biobanking                                       |
| [ogg](http://www.obofoundry.org/ontology/ogg)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   |                               |                                                                                |
| [ogms](http://www.obofoundry.org/ontology/ogms)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Brian Aevermann            | baeverma@jcvi.org                        |                               | https://github.com/OGMS/ogms                                                   |
| [ohd](http://www.obofoundry.org/ontology/ohd)         | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Alan Ruttenberg            | alanruttenberg@gmail.com                 |                               |                                                                                |
| [ohmi](http://www.obofoundry.org/ontology/ohmi)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   |                               | https://github.com/ohmi-ontology/ohmi                                          |
| [ohpi](http://www.obofoundry.org/ontology/ohpi)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Edison Ong                 | edong@umich.edu                          |                               | https://github.com/OHPI/ohpi                                                   |
| [olatdv](http://www.obofoundry.org/ontology/olatdv)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | bgee                       | bgee@sib.swiss                           |                               | https://github.com/obophenotype/developmental-stage-ontologies                 |
| [omp](http://www.obofoundry.org/ontology/omp)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | James C. Hu                | jimhu@tamu.edu                           |                               | https://github.com/microbialphenotypes/OMP-ontology                            |
| [one](http://www.obofoundry.org/ontology/one)         | CC-BY           | https://creativecommons.org/licenses/by/4.0/    | Chen Yang                  | chen.yang@ugent.be                       | @cyang0128                    | https://github.com/cyang0128/Nutritional-epidemiologic-ontologies              |
| [ons](http://www.obofoundry.org/ontology/ons)         | CC-BY           | https://creativecommons.org/licenses/by/4.0/    | Francesco Vitali           | francesco.vitali@ibba.cnr.it             | @FrancescoVit                 | https://github.com/enpadasi/Ontology-for-Nutritional-Studies                   |
| [ontoneo](http://www.obofoundry.org/ontology/ontoneo) | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Fernanda Farinelli         | fernanda.farinelli@gmail.com             |                               | https://github.com/ontoneo-project/Ontoneo                                     |
| [oostt](http://www.obofoundry.org/ontology/oostt)     | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Mathias Brochhausen        | mbrochhausen@gmail.com                   |                               | https://github.com/OOSTT/OOSTT                                                 |
| [opmi](http://www.obofoundry.org/ontology/opmi)       | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Yongqun Oliver He          | yongqunh@med.umich.edu                   |                               | https://github.com/OPMI/opmi                                                   |
| [ornaseq](http://www.obofoundry.org/ontology/ornaseq) | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Stephen Fisher             | safisher@upenn.edu                       |                               | https://github.com/safisher/ornaseq                                            |
| [ovae](http://www.obofoundry.org/ontology/ovae)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqunh He                | yongqunh@med.umich.edu                   |                               | https://github.com/OVAE-Ontology/ovae                                          |
| [pato](http://www.obofoundry.org/ontology/pato)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | George Gkoutos             | g.gkoutos@gmail.com                      | @gkoutos                      | https://github.com/pato-ontology/pato/                                         |
| [pdumdv](http://www.obofoundry.org/ontology/pdumdv)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | bgee                       | bgee@sib.swiss                           |                               | https://github.com/obophenotype/developmental-stage-ontologies                 |
| [phipo](http://www.obofoundry.org/ontology/phipo)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Alayne Cuzick              | alayne.cuzick@rothamsted.ac.uk           |                               | https://github.com/PHI-base/phipo                                              |
| [plana](http://www.obofoundry.org/ontology/plana)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Sofia Robb                 | smr@stowers.org                          |                               | https://github.com/obophenotype/planaria-ontology                              |
| [planp](http://www.obofoundry.org/ontology/planp)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Sofia Robb                 | smr@stowers.org                          |                               | https://github.com/obophenotype/planarian-phenotype-ontology                   |
| [poro](http://www.obofoundry.org/ontology/poro)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Bob Thacker                | robert.thacker@stonybrook.edu            |                               | https://github.com/obophenotype/porifera-ontology                              |
| [ppo](http://www.obofoundry.org/ontology/ppo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Ramona Walls               | rlwalls2008@gmail.com                    |                               | https://github.com/PlantPhenoOntology/PPO                                      |
| [pr](http://www.obofoundry.org/ontology/pr)           | CC-BY           | http://creativecommons.org/licenses/by/4.0/     | Darren Natale              | dan5@georgetown.edu                      | @nataled                      | https://github.com/PROconsortium/PRoteinOntology                               |
| [psdo](http://www.obofoundry.org/ontology/psdo)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Zach Landis-Lewis          | zachll@umich.edu                         |                               | https://github.com/Display-Lab/psdo                                            |
| [pso](http://www.obofoundry.org/ontology/pso)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Laurel Cooper              | cooperl@science.oregonstate.edu          |                               | https://github.com/Planteome/plant-stress-ontology                             |
| [pw](http://www.obofoundry.org/ontology/pw)           | CC-BY           | https://creativecommons.org/licenses/by/4.0/    | G. Thomas Hayman           | gthayman@mcw.edu                         |                               | https://github.com/rat-genome-database/PW-Pathway-Ontology                     |
| [rbo](http://www.obofoundry.org/ontology/rbo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Daniel C. Berrios          | daniel.c.berrios@nasa.gov                | @DanBerrios                   | https://github.com/Radiobiology-Informatics-Consortium/RBO                     |
| [sepio](http://www.obofoundry.org/ontology/sepio)     | CC-BY           | https://creativecommons.org/licenses/by/3.0/    | Matthew Brush              | mhb120@gmail.com                         |                               | https://github.com/monarch-initiative/SEPIO-ontology                           |
| [stato](http://www.obofoundry.org/ontology/stato)     | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Alejandra Gonzalez-Beltran | alejandra.gonzalez.beltran@gmail.com     |                               | https://github.com/ISA-tools/stato                                             |
| [uberon](http://www.obofoundry.org/ontology/uberon)   | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Chris Mungall              | cjmungall@lbl.gov                        |                               | https://github.com/obophenotype/uberon                                         |
| [uo](http://www.obofoundry.org/ontology/uo)           | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | George Gkoutos             | g.gkoutos@gmail.com                      |                               | https://github.com/bio-ontology-research-group/unit-ontology                   |
| [vo](http://www.obofoundry.org/ontology/vo)           | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yongqunh He                | yongqunh@med.umich.edu                   |                               | https://github.com/vaccineontology/VO                                          |
| [xao](http://www.obofoundry.org/ontology/xao)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Erik Segerdell             | esegerd3@gmail.com                       | @seger                        | https://github.com/xenopus-anatomy/xao                                         |
| [xlmod](http://www.obofoundry.org/ontology/xlmod)     | CC-BY           | https://creativecommons.org/licenses/by/3.0/    | Gerhard Mayer              | gerhard.mayer@rub.de                     |                               | https://github.com/HUPO-PSI/mzIdentML                                          |
| [xpo](http://www.obofoundry.org/ontology/xpo)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Erik Segerdell             | esegerd3@gmail.com                       | @seger                        | https://github.com/obophenotype/xenopus-phenotype-ontology                     |
| [zeco](http://www.obofoundry.org/ontology/zeco)       | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yvonne Bradford            | ybradford@zfin.org                       |                               | https://github.com/ybradford/zebrafish-experimental-conditions-ontology        |
| [zfa](http://www.obofoundry.org/ontology/zfa)         | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Ceri Van Slyke             | van_slyke@zfin.org                       | @cerivs                       | https://github.com/cerivs/zebrafish-anatomical-ontology                        |
| [zp](http://www.obofoundry.org/ontology/zp)           | CC-BY           | http://creativecommons.org/licenses/by/3.0/     | Yvonne Bradford            | ybradford@zfin.org                       |                               | https://github.com/obophenotype/zebrafish-phenotype-ontology                   |

This table was generated with the following Python code:

```python
from tabulate import tabulate

from bioregistry.external.obofoundry import get_obofoundry
from bioregistry.license_standardizer import standardize_license


def main():
    rows = []
    for key, entry in sorted(get_obofoundry(force_download=True).items()):
        if entry["deprecated"] or entry["inactive"]:
            continue
        license_label = entry.get("license")
        license_url = entry.get("license.url")
        if license_label is None and license_url is None:
            continue
        # if license_label is None or license_url is None:
        #     raise ValueError
        if standardize_license(license_url) != standardize_license(license_label):
            contact_email = entry.get("contact", "")
            contact_name = entry.get("contact.label", "")
            contact_github = entry.get("contact.github", "")
            repository = entry.get("repository", "")
            rows.append(
                (
                    f"[{key}](http://www.obofoundry.org/ontology/{key})",
                    license_label,
                    license_url,
                    contact_name,
                    contact_email,
                    contact_github and f"@{contact_github}",
                    repository,
                )
            )

    print(
        tabulate(
            rows,
            headers=[
                "prefix",
                "license_label",
                "license_url",
                "contact",
                "email",
                "github",
                "tracker",
            ],
            tablefmt="github",
        )
    )


if __name__ == "__main__":
    main()
```

**Comment by mbrochhausen** [comment]
I am grateful for this bug report and I will follow up with it ASAP.

However, from a motivational and psychological perspective not using the
word "offenders" might prove helpful. Just my 2 cents...

Best,
Mathias

**Comment by batchelorc** [comment]
Hello,

A quick note on how to fix this would be welcome!

All the best,
Colin.

**Comment by matentzn** [comment]
Just to be clear, no one made a mistake here.. `CC-BY` is a legal label for the cc-by 3 license, and the only offender here is me who thought that this kind of ambiguity is fine :). I do think though that a standardised label is indeed better.

To fully complete this ticket, 

- [ ] Change the validation script to not allow CC-BY in the label

**Comment by matentzn** [comment]
Yeah, just make a PR on the schema when you are done, its easy to see what needs changing: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/schema/registry_schema.json#L214
