### ISSUE TITLE
NCRO ontology is missing in both the OBO Library and Ontobee

### ISSUE THREAD

**Issue by Huang-OMIT** [OBOFoundry/OBOFoundry.github.io#165]
The NCRO ontology is not included in the new OBO Library and Ontobee any more. Maybe due to some unexpected situations during the OBO website transition?
(the original link for this ontology was: http://www.obofoundry.org/cgi-bin/detail.cgi?id=ncro)

Any help is highly appreciated!

Jingshan

**Comment by alanruttenberg** [comment]
I'm confused - I added ncro.md to ontologies (std commit to master). I see that the travis build succeeded. However ncro isn't showing up on obofoundry.org.
What am I missing?

**Comment by alanruttenberg** [comment]
The detail page gets built: http://obofoundry.org/ontology/ncro.html but there it isn't in the list on obofoundry.org

**Comment by cmungall** [comment]
still requires an obo-admin to type `make`. This could potentially be automated but having an obo-admin do a final check for overall coherency is not necessarily a bad thing.

**Comment by alanruttenberg** [comment]
OK. How about you make me an obo-admin.

**Comment by ncro-devel** [comment]
oh, and "make" where? in a clone, followed by a commit and push?

**Comment by cmungall** [comment]
@alanruttenberg I think you have been all along https://github.com/orgs/OBOFoundry/teams/obo-admin

(btw I just renamed "Admin" team to "OBO-Admin" as GH recommends not naming teams "Admin" any more)

**Comment by cmungall** [comment]
@ncro-devel I don't know who you are exactly but as an ontology contributor you shouldn't need to worry about anything beyond your own .md file which can be edited via the web interface http://obofoundry.org/faq/how-do-i-edit-metadata.html

**Comment by alanruttenberg** [comment]
It's me. I put in the comment while logged into that account, by mistake.
