### ISSUE TITLE
Misleading message "This ontology uses a mixed-case prefix. Identifiers should..."

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1658]
Example:

http://obofoundry.org/ontology/foodon

![image](https://user-images.githubusercontent.com/50745/142055051-ffcf7bd5-e6e9-490b-be23-b467a28d1c23.png)

> This ontology uses a mixed-case prefix. Identifiers and URIs should use "FOODON"

This is confusing as in fact foodon doesn't use a mixed-case prefix

Originally we *only* provided preferredPrefix for exceptions but in #1621 this was added to all

I would like to keep the notification, but have it only show up for non-standard preferred prefixes

**Comment by nlharris** [comment]
That seems not just misleading but wrong. Why is that error message getting triggered for FOODON?

**Comment by matentzn** [comment]
I think I provided a fix here: 
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1659

**Comment by jamesaoverton** [comment]
I don't think this is fixed? I still see this message for FOODON.

**Comment by lschriml** [comment]
I noticed this banner message on several ontologies yesterday, that do not have a mixed case prefix.

**Comment by matentzn** [comment]
Blocked by https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1662

**Comment by jamesaoverton** [comment]
I don't think it's blocked. Changes to the GitHub Pages templates should work as soon as they are committed to `master`. 

![IMG_0399](https://user-images.githubusercontent.com/292409/142480202-8680d96f-3e03-4b18-b582-6ab026a6726b.jpg)

**Comment by matentzn** [comment]
Oh.. Then something else is wrong.. maybe these jinja templates are not used the way I thought..

**Comment by matentzn** [comment]
Fixed now after a lot of trial and error.
