### ISSUE TITLE
Create a page that shows all relevant github trackers plus summary statistics on issues

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#166]
Would be useful to see a table, one row per tracker, showing the relevant ontologies plus number of open and closed tickets

The github API is easy, here's an example of how it's used:

https://github.com/owlcollab/owltools/blob/master/OWLTools-Oort/reporting/query-github-for-new-tickets.js

**Comment by nlharris** [comment]
maybe we could get a bored student to do this this summer?

**Comment by nlharris** [comment]
is this still something we want?

**Comment by matentzn** [comment]
This is now covered by @cthoyt https://cthoyt.com/obo-community-health/
