### ISSUE TITLE
Add check:`id` entry in metadata should be lower-case

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1667]
While the preferred prefix can have mixed case, it seems that the `id` field for _all_ OBO Foundry ontologies, even including ones with uppercase or mixed case preferred prefixes have been completely lowercased. The current testing suite does not check for this, and the merge of https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1646 is the first example where the `id` was uppercase.

I noticed this because it broke the Bioregistry build, which assumed that the ID fields would be lowercase.

**Comment by cthoyt** [comment]
The specific example for EPSO was fixed in https://github.com/OBOFoundry/OBOFoundry.github.io/commit/ef6aa8d4ea34421cb2b4b1e26e1a63456365d1f2, but this issue shouldn't be closed until there's a technical solution to guard against this in the future

**Comment by matentzn** [comment]
Yep we need a check

**Comment by cthoyt** [comment]
Could be trivially added to #1661.

**Comment by nlharris** [comment]
#1661 was already merged; did the change include this new check?

**Comment by cthoyt** [comment]
No, it did not. I am still unsure how we will go about implementing new tests outside of the existing framework

**Comment by matentzn** [comment]
Isnt there some thing in json schema to specify _all lowercase_?

**Comment by cthoyt** [comment]
A regex would work

**Comment by nlharris** [comment]
@cthoyt this seems like the sort of thing that you could do a PR for and then it'd be done...

**Comment by matentzn** [comment]
Weird, there already is a check:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/schema/registry_schema.json#L142

Trying now: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1818

Doesnt work the error was spurious. Any idea?

**Comment by cthoyt** [comment]
No idea, let's close this one, since some other improvements to the testing pipeline in the mean time might have fixed it
