### ISSUE TITLE
Can't run make

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#167]
I get an error on a fresh repository

laptop:/Users/alanr/repos % cd OBOFoundry.github.io 
laptop:/Users/alanr/repos/OBOFoundry.github.io % make
git pull
Already up-to-date.
./util/extract-metadata.py concat-principles -o principles/all.yml.tmp principles/fp-000-summary.md principles/fp-001-open.md principles/fp-002-format.md principles/fp-003-uris.md principles/fp-004-versioning.md principles/fp-005-delineated-content.md principles/fp-006-textual-definitions.md principles/fp-007-relations.md principles/fp-008-documented.md principles/fp-009-users.md principles/fp-010-collaboration.md principles/fp-011-locus-of-authority.md principles/fp-012-naming-conventions.md principles/fp-016-maintenance.md  && mv principles/all.yml.tmp principles/all.yml
Traceback (most recent call last):
  File "./util/extract-metadata.py", line 237, in <module>
    main()
  File "./util/extract-metadata.py", line 44, in main
    func(args)
  File "./util/extract-metadata.py", line 175, in concat_principles_yaml
    (obj, md) = load_md(fn)
  File "./util/extract-metadata.py", line 190, in load_md
    text = f.read() 
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1030: ordinal not in range(128)
make: **\* [principles/all.yml] Error 1

**Comment by cmungall** [comment]
I haven't seen this before. But then we haven't tested the script for various character encoding issues.

Do you get this on a fresh checkout? I'm wondering if you have local modifications with unusual characters in one of the md files.

**Comment by alanruttenberg** [comment]
Fresh checkout. I thought it might be ncro but I removed it and in any case it validates on travel.

**Comment by jamesaoverton** [comment]
I could not reproduce this problem just now on a fresh repository.

Mac OS X 10.11.1 (15B42); GNU Make 3.81 (from Apple); Python 3.5.0 (from Homebrew); my disk is formatted "OS X Extended".
