### ISSUE TITLE
New Ontology Request

### ISSUE THREAD

**Issue by Aymenchaalia** [OBOFoundry/OBOFoundry.github.io#1672]
African Ethnolinguistic Ontology

**Comment by cthoyt** [comment]
Hi @Aymenchaalia could you please open a new issue for your ontology request following the new ontology request issue template (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology-request.md&title=) and please close this one?

**Comment by nlharris** [comment]
Hi @Aymenchaalia, just pinging you again to ask if you can open a new issue as cthoyt requested above. Thanks!

**Comment by nlharris** [comment]
Given no response from the requester and not enough information to do anything about this ontology, I'm closing. @Aymenchaalia we still encourage you to open a new ontology request issue if you are interested in having your ontology considered for the OBO Foundry!
