### ISSUE TITLE
make target to install dependencies

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#168]
I think this is what I landed up having to do

sudo gem install jekyll
sudo gem install redcarpet
brew install python3
pip3 install pygments
pip3 install sparqlwrapper

However on the last I get an error for keepalive

<code>
Collecting sparqlwrapper
  Downloading SPARQLWrapper-1.7.4.tar.gz
Collecting rdflib>=4.0 (from sparqlwrapper)
  Downloading rdflib-4.2.1.tar.gz (889kB)
    100% |################################| 892kB 595kB/s 
Collecting keepalive>=0.4.1 (from sparqlwrapper)
  Downloading keepalive-0.4.1.tar.gz
Collecting isodate (from rdflib>=4.0->sparqlwrapper)
  Downloading isodate-0.5.4.tar.gz
Collecting pyparsing (from rdflib>=4.0->sparqlwrapper)
  Downloading pyparsing-2.0.6-py2.py3-none-any.whl
Building wheels for collected packages: sparqlwrapper, rdflib, keepalive, isodate
  Running setup.py bdist_wheel for sparqlwrapper
  Stored in directory: /Users/alanr/Library/Caches/pip/wheels/08/d5/15/6024314eb1b620149f6fb2e14da608749c3a83224001af7c0a
  Running setup.py bdist_wheel for rdflib
  Stored in directory: /Users/alanr/Library/Caches/pip/wheels/5f/cc/22/bba65aa21c61d538dffb4960bd74ece936f3b0ef71ade47fb5
  Running setup.py bdist_wheel for keepalive
  Complete output from command /usr/local/opt/python3/bin/python3.5 -c "import setuptools;**file**='/private/var/folders/mb/9b1crp9j53j70xyy5yk8rngc0000gn/T/pip-build-j7cce9ii/keepalive/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /var/folders/mb/9b1crp9j53j70xyy5yk8rngc0000gn/T/tmprc_j09rzpip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 950: ordinal not in range(128)

---

  Failed building wheel for keepalive
  Running setup.py bdist_wheel for isodate
  Stored in directory: /Users/alanr/Library/Caches/pip/wheels/8a/b6/2c/9346712a1822e562d16c4d6a5ae242ebf45128a8cb2e7b4abe
Successfully built sparqlwrapper rdflib isodate
Failed to build keepalive
Installing collected packages: isodate, pyparsing, rdflib, keepalive, sparqlwrapper
  Running setup.py install for keepalive
Successfully installed isodate-0.5.4 keepalive-0.4.1 pyparsing-2.0.6 rdflib-4.2.1 sparqlwrapper-1.7.4
</code>

**Comment by alanruttenberg** [comment]
make target: I mean can we get a target "make devinstall" which would install the dependencies?
The dependencies are listed in the makefile, but probably should be listed in README-sitedev.md

I would update it, but I don't know if I have it right. I'm on yosemite.

**Comment by alanruttenberg** [comment]
Forgot, also did pip3 install pyyaml

**Comment by jamesaoverton** [comment]
It's not trivial to write cross-platform install scripts, and I would not willingly run one on my machine.

For non-trivial cross-platform project installs, I use a combination of Vagrant and Ansible to set up and provision a local virtual machine. It should work on Linux, Mac, and Windows. Example:

- https://github.com/OBOFoundry/purl.obolibrary.org#development-and-testing
- https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/tools/Vagrantfile
- https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/tools/site.yml

James

**Comment by cmungall** [comment]
That feels a bit over the top for this repo. I'd hoped a platform-independent install would be easy, once the main environment is installed (ruby for sitedevs, python for obo admins).

I'd suggest 3 install targets:

 1. sitedev-install (assumes ruby already installed, which may be platform specific)
 2. oboadmin-install (assumes python3 and jena-command line)
 3. oboadmin-dev-install (assumes python3)

If we get a CSS/liquid-template/bootstrap guru, then all they need is 1.

For the typical OBO tech or ops person, all they need is 2. This is really just to ensure downstream products are built (combined yaml, json, rdf). This could even be farmed out to a CI job. The additional jena dependency is a bit annoying and as @mcourtot noted some versions don't work. I think this could be done in pure python, just for simplicitly of installation.

3 is a bit experimental and is required if you want to do certain kind of reporting, such as for #125

**Comment by alanruttenberg** [comment]
Do you both develop on OS X? If so having the OSX incantations would be
great. Or even Linux.

I was trying to run the site on a yaml I was writing for ncro. Being the
first one I'm doing I wanted to make sure I didn't break anything.

Btw, another thing I didn't see was docs for the tags used in the yaml. Is
that somewhere?

**Comment by cmungall** [comment]
I'm on OS X, will add incantations

btw, you should be able to add ncro entirely through the github web interface (though it's convenient to do it from a local workspace, can copy and modify)

yaml tags: most of these map to an RDF property via the JSON-LD context, and the RDF properties are in theory document, but of course dc leaves a lot of leeway; this isn't really ideal as a cohesive piece of documentation. There are various snippets on different docs like the faqs, but these should be collected into one document. possibly executable, e.g. yaml schema

**Comment by nlharris** [comment]
what's the status of this?

**Comment by nlharris** [comment]
since this is 5 years old, i think we should close this, and reopen or create a new issue if there are still problems. ok?

**Comment by jamesaoverton** [comment]
I agree with @nlharris
