### ISSUE TITLE
Principle #7 "Relations" - add text stating preference for RO addition

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#1680]
Current text indicates that a new relation can be created in an ontology developer's own IDspace, but I think this is not preferred. If so, we should add text indicating that the preference is to submit to RO. We would also need to indicate the conditions under which one path should be taken over the other, something like

"If a new (in meaning) relation is needed, the new relation SHOULD be submitted to RO if it is generic enough."

Then we clarify what we mean by 'new' (and also 'duplicative'). In the above, "(in meaning)" was used to indicate that the newness is not based on string, but on the definition and its usage.

**Comment by alanruttenberg** [comment]
I don't think this is necessary. The language already requests coordination
with RO. In that discussion, if the relation is generic in the sense
desired, the request can be made.

I will register my opinion here that I think forcing all relations to be in
RO is not advisable. The constraint is unlike any other coordination
constraint in that the RO does not have well-defined domain scope. Domain
scopes are subject-matter constraints, not structural constraints. RO is
very large and so most users will need to MIREOT terms. I believe there
should be a breakdown of relation ontologies by domain, with a minimal set
of the most commonly used relations centralized, for example as part of
COB.

**Comment by nataled** [comment]
Wording updated.
