### ISSUE TITLE
Add "last commit" badges to homepage and ontology page

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1687]
Shields.io will generate all sorts of nice badges that give summary-level information on repositories that can be formatted in using the following markdown:

```markdown
![GitHub last commit](https://img.shields.io/github/last-commit/:organization/:name)
```

It would be useful to include this on one or both of the homepage and ontology-specific pages to give users directly more insight into how maintained an ontology has been lately, regardless of its status as "active", "orphaned", etc.

A few examples:

| Ontology | Repo | Badge |
|----------|-------|--------|
| PLANA | obophenotype/planaria-ontology | ![GitHub last commit](https://img.shields.io/github/last-commit/obophenotype/planaria-ontology) |
| CHEMINF | semanticchemistry/semanticchemistry | ![GitHub last commit](https://img.shields.io/github/last-commit/semanticchemistry/semanticchemistry) |
| INO | INO-ontology/ino | ![GitHub last commit](https://img.shields.io/github/last-commit/INO-ontology/ino) |

Caveats:
- I'm not sure what the color scheme is, but I guess it's an opinionated traffic light scheme for when things are getting stale.
- About 3/4 of ontologies in OBO Foundry have structured annotations for the repository. Almost all of those annotations correspond to GitHub repositories. See comment [here](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1688#issuecomment-989857410)

Note: I'd be happy to provide the implementation of this if it gets positive feedback.

**Comment by matentzn** [comment]
I love it! In case there is a vote in my absence, I vote for this!

**Comment by nlharris** [comment]
Yes, seems great, particularly since it will automatically update itself without further intervention required! (Red and green are not the most accessible colors, but since the information is also in text, I think that's fine.)
