### ISSUE TITLE
Ontology is missing in Onotbee and Obo Foundry page

### ISSUE THREAD

**Issue by phwegner** [OBOFoundry/OBOFoundry.github.io#1689]
The Epilepsy Ontology (EPSO) got accepted a couple of weeks ago but I still cannot see it in Ontobee. 

Is there anything that needs to be done before it gets uploaded there ?

**Comment by matentzn** [comment]
Its not missing on the OBO foundry page:

**Comment by matentzn** [comment]
https://obofoundry.org/ontology/epso.html

**Comment by matentzn** [comment]
And ontobee is independent of OBO Foundry.. You will have to talk to @yongqunh to ask about that!

**Comment by phwegner** [comment]
@matentzn Okay, I checked it on Wednesday and couldn't find it... But then everything is good. Thank you for you fast response.

**Comment by yongqunh** [comment]
It is available in Ontobee now:
http://www.ontobee.org/ontology/EPSO
