### ISSUE TITLE
Names with non ASCII characters deteriorate during metadata integration

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1695]
Raw data:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/lepao.md?plain=1#L7

Result:
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1690/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R3310

**Comment by matentzn** [comment]
@JCGiron Can you, until this problem is solved, change lepao.md and colao.md to use your names without the special characters?

**Comment by JCGiron** [comment]
Sure thing!
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1696
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1697

**Comment by matentzn** [comment]
Thank you so much!

**Comment by cthoyt** [comment]
Probably can be fixed with the settings of the yaml dumper

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/9e41ff3cf5c42f54c7494efe78c694c3174c5e64/util/extract-metadata.py#L221

**Comment by matentzn** [comment]
Tried it, setting _allow_unicode_ results in 

![image](https://user-images.githubusercontent.com/7070631/146245063-6753d99a-c9ea-4919-879b-b7e7b2f9a99c.png)

**Comment by cthoyt** [comment]
That looks like JSON, that's a different one. You need `ensure_ascii=False` for JSON dumps

**Comment by matentzn** [comment]
It was ruaml yaml.. 

https://newbedev.com/pyyaml-dump-unicode-with-special-characters-i-e-accents
