### ISSUE TITLE
Proposed revisions to FAQ: Submit a new ontology

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#1706]
Pertaining to https://obofoundry.org/faq/how-do-i-register-my-ontology.html

There is a few redundant link; would like to streamline it a bit.

1) Remove the last sentence "Please see this guide for detailed instructions and background."
2) Change the first listed instruction from "Review the expectations and requirements for membership here" to "Review the [OBO Foundry requirements and technical details](https://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html)" document for membership expectations and submission instructions"

**Comment by nlharris** [comment]
sounds ok to me

**Comment by matentzn** [comment]
sounds good

**Comment by nataled** [comment]
Note that, unlike most other pages, there is no 'Edit' button on this page. I was able to find it and make the changes.
