### ISSUE TITLE
Update OPL contact information

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1717]
While the [Ontology for Parasite LifeCycle (OPL)](https://obofoundry.org/ontology/opl) has the contact person listed as Priti Parikh, I don't see any evidence of a person by that name interacting with the repository at https://github.com/OPL-ontology/OPL.

@zhengj2007: you seem to be the only one who has pushed to that repository, so it would be great if you could provide a recommendation on how to update the contact information for this ontology

**Comment by cthoyt** [comment]
@cstoeckert you are also listed as contact, so your input would also be valued. Thanks!

**Comment by zhengj2007** [comment]
@cthoyt I contact Priti by email asking whether she still wants to be listed as the contact person.

**Comment by cthoyt** [comment]
@zhengj2007 thanks for the feedback. Would you please find out what her GitHub handle is if you're able to get in touch? Thanks!

**Comment by zhengj2007** [comment]
@cthoyt I asked her github handle when I emailed her. But I haven't got her response yet.

**Comment by zhengj2007** [comment]
@cthoyt I got reply from Priti. She said she is willing to change the contact person to me. Do you want to update the OPL page or you'd let me to do it? Thanks!

**Comment by cthoyt** [comment]
I took care of it! Thanks for looking into this.

**Comment by cthoyt** [comment]
Btw @zhengj2007 could you send me your ORCID?

**Comment by zhengj2007** [comment]
> Btw @zhengj2007 could you send me your ORCID?

Have sent to you by email.
