### ISSUE TITLE
obsolete should supersede inactive

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1722]
Following from

 * #1721 

There is a lovely rainbow of colors here:

https://obofoundry.org/ontology/ehda

![image](https://user-images.githubusercontent.com/50745/148106439-2abcf76c-15bf-411d-a53e-bf23c3b310b6.png)

I think obsolete implies inactive, we should either constrain the schema to allow either but not both, or we should filter at the UI level

The mixed-case indicator is a false positive but that is reported in another issue

Another oddity here is that the replacement for ehda (ehdaa2) is inactive (not not obsolete). I think this is OK and valid but it may be confusing to some. We may also want to make suggestions for active alternatives for ehdaa2 (this would be uberon or fma, the latter which now includes more embryonic terms but is still less complete than ehdaa2). Some of this may be best done in plain old fashioned text.

**Comment by matentzn** [comment]
- [X] inactive and orphaned banners should only show up when not deprecated (https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1738).
- [X] irregular preferred prefix check only if preferred prefix is set (https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1738).
- [ ] Should inactive ontologies be considered?

**Comment by nlharris** [comment]
did anyone make a decision about the last point above?

**Comment by matentzn** [comment]
I think no. 

@cthoyt Do you know if there are ontologies being referred to by consider that are marked as `inactive`?

**Comment by cthoyt** [comment]
```python
import requests
import yaml

URL = "https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/ontologies.yml"


def main():
    records = yaml.safe_load(requests.get(URL).text)["ontologies"]
    prefixes = {
        record["id"]
        for record in records
        if record["activity_status"] in {"inactive"}
    }
    for record in records:
        if record.get("replaced_by") in prefixes:
            print(record["id"])


if __name__ == '__main__':
    main()
```

Gives back:
- ehda
- ehdaa

**Comment by matentzn** [comment]
If you would be so kind to add a test to disallow this and remove the consider relation from these two, that would be very appreciated :) This will close this ticket here as well.

**Comment by cmungall** [comment]
ehda and ehdaa were replaced by ehdaa2. we should not lose this information

**Comment by cthoyt** [comment]
i have no opinion one way or another. The text inside ehdaa2 about alternatives isn't super actionable, though - it reads

> This ontology has been inactive for several years, as of 2022. As of yet there is no complete replacement ontology, but OBO users may want to consider potential alternatives:
>
>    - [HsapDv](https://obofoundry.org/ontology/hsapdv) contains human-specific embryonic stage terms for Carnegie stages
>    - [Uberon](https://obofoundry.org/ontology/uberon) includes embryonic anatomy and developmental stage relations, but is more taxonomically general than EHDAA2, and may be less complete and less precise. Uberon includes EHDAA2 in its composite metazoan build.
>    - [FMA](https://obofoundry.org/ontology/fma) now includes some himan embryonic anatomy, but is constructed on different principles than EHDAA2, and may be less complete and less precise in places
>
> As of 2022, EHDAA2 still has the most complete set of human structure to stage relationships of any ontology in OBO, but note that it is no longer updated.

**Comment by matentzn** [comment]
Is `replaced_by` intended to capture provenance, or intended to guide the OBO Foundry users to our reference ontologies? If its just about provenance, then I totally misunderstood its purpose and we wouldn't constrain the field..

**Comment by nlharris** [comment]
Closing; please open a new ticket if there are still actionable tasks.
