### ISSUE TITLE
Require `repository` for new ontologies

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1730]
Currently, only an issue tracker is required. I think it makes sense to also require new ontologies to provide a repository (e.g., on GitHub (highly preferred), GitLab, BitBucket, etc.)

Implicitly, this will encourage all new ontologies to use a public repository as their main place for curation.

This was motivated by the recent new ontology request for ELO (#1729), which did not include a repository. It seems to be the case that a potential submitter is not aware this is important, because it is not included in the form.

**Comment by matentzn** [comment]
Yes I agree with this. Every ontology should have a repo. Sometimes, this differs from the issue tracker, for example, if groups keep projects in separate repos but want issues in a specific community facing repo. What needs doing to achieve this? Which ontologies currently in OBO do not have a repository?

**Comment by cthoyt** [comment]
I proposed a fix for these three ontologies as well as an accompanying update to the schema in #1741. Merge on that should wait on people having a chance to comment on this, but I think it's pretty uncontroversial so maybe give it until the end of the week.

**Comment by matentzn** [comment]
I think we are good with MAMO and OGG as you suggest.

**Comment by nlharris** [comment]
Do we need to discuss this on a call?

**Comment by lschriml** [comment]
Yes
