### ISSUE TITLE
ONE and TXPO's contact email addresses are dead

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1745]
I was looking for ORCID authors and tried to get in touch with some, but I found the following emails were broken. I also gave suggestions based on what I could find on the internet:

| Ontology | GitHub | Broken Email | Suggested email
|------|-------------|----------|----------|
| ONE | @cyang0128 | chen.yang@ugent.be |  chenyangnutrition@gmail.com (found on GitHub) |
| TXPO | @yuki-yamagata | y-yamagata@nibiohn.go.jp | yuki.yamagata [at] riken.jp (found at https://so.riken.jp/members/) |

Could you please suggest new email addresses to put, or let us know if you can't be the contact person for your respective ontologies anymore?

**Comment by txpo-ontology** [comment]
I'm Yuki Yamagata.
I apologize for the inconvenience.
I updated my contact address of TXPO information in the Bioportal site:
https://bioportal.bioontology.org/ontologies/TXPO
But I'm sorry, I'm not familiar with the OBO-foundry site, and I don't 
know how to update the information.

My address is ***@***.*** and
ORCID:0000-0002-9673-1283
https://orcid.org/0000-0002-9673-1283

Thanks,
Yuki

-- 
Yuki Yamagata Ph.D
Laboratory for Developmental Dynamics
RIKEN Center for Biosystems Dynamics Research
***@***.***

**Comment by cthoyt** [comment]
Thanks, Yuki! We'll fix this in #1746 😄
