### ISSUE TITLE
ECTO depends on NPO, an ontology not listed in the OBO Foundry

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1768]
ECTO depends on NPO, an ontology not listed in the OBO Foundry:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/e02769b65ce671f3d3478b09904052cbc759130d/ontology/ecto.md?plain=1#L42

I believe this means the NanoParticle Ontology (https://bioregistry.io/registry/npo). What are the rules/guidelines on depending on outside ontologies? This is the only instance throughout the OBO Foundry where this happens.

**Comment by matentzn** [comment]
Delete the NPO reference.

**Comment by cthoyt** [comment]
Should there also be follow-up to say not to do this? Should we institute a technical check for validity of these dependencies (also in the spirit of #1766) before closing this?

**Comment by matentzn** [comment]
If we want to be all serious about the list of dependencies, I would say we:

- [ ] need to have separate metadata elements for OBO and non-OBO dependencies
- [ ] the non-obo ones should be a valid bioregistry prefix
- [ ] the obo one should be a a valid ID within OBO (no matter if inactive, if the id is in there its fine)

Have at it if you want to push this forward!
