### ISSUE TITLE
Move this repo to squash merge

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1775]
I have activated squash merge for the repo:

![image](https://user-images.githubusercontent.com/7070631/151391026-81d1a318-79ae-46e6-a545-4c71a89a0361.png)

You will notice that when merging pull requests, it will now say "squash merge" instead of "merge", and it will cause all commits in a pull request to be combined before the merge to reduce the overall number of commits and increase readability of the git history.

@cthoyt thank you for the suggestion!

This ticket can be closed by whoever finds it first, because its done.

**Comment by cthoyt** [comment]
Going along with this, we should be careful to ask people to make meaningful titles for their PRs now, since that's what will show up in the git history

**Comment by nlharris** [comment]
Some of us already strive to make meaningful titles for our PRs. I doubt those who don't can be easily persuaded to change their ways. 🙂

**Comment by matentzn** [comment]
Patience, love and education will do it!

**Comment by nlharris** [comment]
Closing as per Nico's comment, "This ticket can be closed by whoever finds it first, because its done."
