### ISSUE TITLE
Rework id-policy document

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#178]
The [id-policy ](http://obofoundry.org/id-policy.html) document could do with an overhaul. It's confusing, out of date in many respects, and could be simplified.
- Update to reflect practice w.r.t. PRO, which embeds UniProtKB local IDs
- Separation of concerns: the document should deal with URL structure; contraction of URLs to prefixed identifiers can be separated out, and is already covered elsewhere (e.g. for obo-format in the obo-format specs)
- The ID-expressions were an abandoned idea
- The 'legacy PURLs' (purl.obo/obo) are safely in the dustbin of history. These should still be documented as one still encounters them in forgotten stale ontologies, but they need not take up a prominent place in the documentation
- Many ontologies vary slightly in the structure of release purls
- Release purl documentation could come with links to a handy guide explaining how ordinary mortals can do this (e.g. by using github releases, combined with https://github.com/OBOFoundry/purl.obolibrary.org redirects)

**Comment by mcourtot** [comment]
Also the fig at http://obofoundry.org/id-policy.html doesn't resolve. I'll try and find the source in archive.

**Comment by nlharris** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/id-policy.md was updated 8 months ago (and I don't see a figure on it). Are there still things that need to be done on this document, or can this issue be closed?

**Comment by jamesaoverton** [comment]
<http://obofoundry.org/id-policy.html> work for me now. The policy was revised in #1044.
