### ISSUE TITLE
Sortable table for the OBO website

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#1795]
As discussed on the OBO oepration call on 02/08/22, we need a sortable table to change the sort order for the dashboard/website. 
For example:
- Need a default sort order (TBD - could be domain ontology, project ontology). 
- Need tag based and flexible sorting. 
@matentzn will specify specs

**Comment by nlharris** [comment]
That would be great!

See also Add search and sort to ontology table on homepage #1241

**Comment by matentzn** [comment]
closing in favour of https://github.com/OBOFoundry/OBOFoundry.github.io/issues/43
