### ISSUE TITLE
Ontologies that don't resolve  

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#18]
These ontologies don't resolve from the yaml file

http://www.berkeleybop.org/ontologies/dpo.owl
http://www.berkeleybop.org/ontologies/kisao.owl
http://www.berkeleybop.org/ontologies/lipro.owl
http://www.berkeleybop.org/ontologies/nmr.owl
http://www.berkeleybop.org/ontologies/ovao.owl
http://www.berkeleybop.org/ontologies/resid.owl
http://www.berkeleybop.org/ontologies/rnao.owl
http://www.berkeleybop.org/ontologies/xso.owl

**Comment by cmungall** [comment]
@dosumis do you recall why we made the purl for dpo be http://purl.obolibrary.org/obo/fbcv/dpo.owl

We *could* make this a subset of the main http://obofoundry.github.io/ontology/fbcv.html - but we decided to mark this as obsolete at some point

It's probably too much churn to change this now, I suggest we have http://obofoundry.github.io/ontology/dpo.html as its own top level and live with the fact the ontology and class purls aren't derived in exactly the same way

**Comment by dosumis** [comment]
> @dosumis do you recall why we made the purl for dpo be http://purl.obolibrary.org/obo/fbcv/dpo.owl

Probably because we never got around to making a foundry request for dpo.  Puting it under fbcv made sense as dpo is a subontology of fbcv and we didn't want the churn at FlyBase caused by splitting it out.  I guess there's no reason not to put in a foundry request  http://purl.obolibrary.org/obo/dpo.owl .  We could keep the old PURL too.  CC @mmc46

**Comment by cmungall** [comment]
Note to site developers: you can now do the following:

```
make valid-purl-report.txt
```

to validate all product purls (ie the canonical product for an ontology project, as well as each individual registered product)

**Comment by cmungall** [comment]
> http://www.berkeleybop.org/ontologies/dpo.owl
registered product is http://purl.obolibrary.org/obo/fbcv/dpo.owl
resolves
> http://www.berkeleybop.org/ontologies/kisao.owl
http://purl.obolibrary.org/obo/kisao.owl resolves
(but note the ontologyID is not a purl. Consider deregister?
> http://www.berkeleybop.org/ontologies/lipro.owl
product deregistered

> http://www.berkeleybop.org/ontologies/nmr.owl
obsolete
> http://www.berkeleybop.org/ontologies/ovao.owl
typo. Entry removed

> http://www.berkeleybop.org/ontologies/resid.owl
obsolete
> http://www.berkeleybop.org/ontologies/rnao.owl
works
> http://www.berkeleybop.org/ontologies/xso.owl
typo. Removed.

**Comment by dosumis** [comment]
Why the berkeleybop URL for dpo?
