### ISSUE TITLE
Add attrubition guidelines for axioms

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#180]
http://obofoundry.org/principles/fp-001-open.html
assumes that reuse is on the level of 'term' (aka class?). We also need attribution on the axiom level; e.g. for bridging ontologies

**Comment by nlharris** [comment]
did this get done?

**Comment by alanruttenberg** [comment]
You raise an interesting case. The choice of leaving attribution by term
was that it's little burden, and encourages reuse.

There's also the issue of how attribution is done when a term is reused in
another ontology. Again using the IRI as attribution
is practical and the alternative annoying.

I guess my starting position is that we don't have to have special rules
for bridging ontologies or axioms. They reuse terms that are also
attributable using the IRI. Same notice goes on the ontology as usual.

Alan

**Comment by nlharris** [comment]
is this still relevant?

**Comment by alanruttenberg** [comment]
Concur with @matentzn
