### ISSUE TITLE
Add link to publications

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#182]
We had this on the legacy site (note: currently legacy/publications button goes to a 404)

How best to manage the publications? A markdown file? A mendeley/zotero group? What is the procedure for adding? Anyone can add? Tickets/pull-requests, with +1s from others?

**Comment by jamesaoverton** [comment]
See #220

**Comment by jamesaoverton** [comment]
I think this is closed by PR #233, merged in 55ca958710f6828559a53b647b8a082f62695bb2
