### ISSUE TITLE
Add to FAQ - What tools are available for editing and OBO Ontologies

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#183]
Link to protege and other editing tools, plugins, any other pages of utility

**Comment by cmungall** [comment]
This would be very useful. We also have a ton of useful material such as @jamesaoverton's tutorials, guides on using continuous integration etc. I suggest we start with a general menu item for "tools and tutorials" and have a big flat list underneath this.

Alternatively we could just treat this as a separate concern and organize everything here:
https://github.com/jamesaoverton/obo-tutorial

**Comment by nlharris** [comment]
should the title of this be "What tools are available for editing OBO Ontologies"?

**Comment by nlharris** [comment]
Similar to #633
