### ISSUE TITLE
Develop SOP for Changing Ontology Metadata

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#1848]
As discussed in #1845 - thank you @matentzn for the feedback. 

I am making a suggestion here, that we develop a SOP for adding/updating metadata for an ontology. 
           Specifically, for updates made by the OBO Foundry and/or individuals who are not part of the a project or the PI.

Issues that arose:
 - what metadata in an ontology.md file is the purview of the ontology editor/PI to edit;
-  which fields/data types can/should the OBO Foundry or non-project people edit. 

I think it is fabulous that we, the OBO Foundry, are helping ontology projects to improve their ontologies, be that via Dashboard reports, or analysis of data representations in their ontology.md file. Moving forward, I think we could use some parameters/guidelines on how we deliver that help, to offer advice and solutions. To more clearly establish boundaries/guidelines for these updates. 
 
Some ideas on moving forward: 
- formulate (and communicate to ontology PIs) a plan to: 
           -  identified problems and intended updates 
           - clarifying what types of updates the OBO Foundry might do
           - establish a protocol to communicate with PIs 
                     - emails in addition to GitHub mentions, as these may be missed
                     - most of us use GitHub daily, but we should consider that not all PIs/editors are checking their GitHub daily 
           - with a set time period for PIs/editors to respond to the suggestion (at least a week)
           - add some specifically protected fields that only the project PI/editor would update
           - if an individual has suggestions for a project, it is to be conveyed via a Github ticket, the ontology.md should not be 
              updated otherwise
Cheers,
Lynn

**Comment by matentzn** [comment]
@lschriml would you like to prepare a list of metadata items that you think 
- _must_ be signed off by the contact/pi (id, name, etc) (no merge without permission)
- _should_ be signed off by the contact/pi (publication, etc) (request for permission but merge after 7 days period even without permission) 
- _could_ be signed off by contact/pi (changes to metadata structure that don't affect meaning, typos) (no request for review, merge after 72 hours)

I am against the proposal of the email message, but could be convinced otherwise. For SHOULD and COULD, but could be convinced for an email in the MUST section.

**Comment by cthoyt** [comment]
If there are any fields that _must_ be signed off by the contact, then I think it would be good to in tandem outline what is the time frame the contact person has for this kind of request and what the consequences are for not engaging (e.g., marking the ontology as orphaned)

**Comment by matentzn** [comment]
I would not make the `status` field `MUST`. Other than the title and the identifier I cannot see any reason to make anything `MUST` right now!

**Comment by lschriml** [comment]
@matentzn - good idea, added below.  
I've listed all of the fields, and binned them based on who creates the fields and who edits them.
Cheers,
Lynn

a list of metadata items: 
**list of fields:** 
id, contact (email, label - Name, GitHub, orchid), description, twitter, domain, tags, homepage, products (id, title), browsers (label, title, url), taxon (id, label), title - of the ontology, review (date, document), build (source_url, method, infallible), tracker, publications (id - PubMed ID, title), license (url, label), usages (examples: url, description; user (description, examples (url, description))), activity status, repository, preferredPrefix, depicted_by - project logo

**Fields set by OBO Foundry upon the creation of the project:** 
id
taxon
preferredPrefix

**Fields set by OBO Foundry, after project creation**
 -- after consultation with editor/PI,
                  _must_ be signed off by the contact/pi (id, name, etc) (no merge without permission)
domain
tags
review - to make it optional to show a review
build - source_url - may change over time, by the editor/PI
activity_status: editor/PI MUST be contacted prior to a status change

**Fields set by editor/PI - could be updated by OBO Foundry**, following notification to editor/PI
                       _should_ be signed off by the contact/pi (publication, etc) 
                                   (request for permission but merge after 7 days period even without permission)
contact
browsers


**Fields set by editor/PI - only updated by project editor/PI**
description
twitter
homepage
products
title
tracker
publications
license
usages
repository
depicted_by - project log: the size has been standardized, 
                        Question: should the size of the logo be set by the Foundry ? 

**At the discretion of the OBO Foundry:** 
- changes to metadata structure that don't affect meaning, such as size of images, font, typos, page arrangement.
-  no request for review, merge after 72 hours

**Comment by matentzn** [comment]
I think this looks good in general. Some suggestions:

Lets maybe not think about who proposes changes - anyone can always propose any kind of change. The question is the approval process.

- Changes to the description that do not change the meaning can be approved by OFOC member (typos etc)
- usages that are added should be approvable my OFOC - a community member provides evidence of usage, TWG checks the usage and its fine.
- domain SHOULD be signed of by contact, but can be enacted by OFOC when contact is non-responsive
- tags can be approved by OFOC (linking contact)
- activity_status can be set at the discretion of OFOC (need SOP)

I would suggest that maybe we have a 7 day period for updating metadata where we SHOULD have feedback from the listed contact, and a 1 month period for two reminders (email if necessary) for cases where contact MUST be asked. 

Also, we frequently add metadata to the metadatafile recently, which will always be linked to the contact so they can take a look.

**Comment by nlharris** [comment]
Note that this is on the agenda to discuss in tomorrow's OFOC meeting.

**Comment by matentzn** [comment]
All changes to records need to PR, contact must be tagged. 4 weeks period.


- activity_status
- contact

3 months and 1 email
