### ISSUE TITLE
Publication field: actionable persistent identifiers

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1859]
According to our OBO operations call on the 19th of April, we (the OBO operations committee) mostly unanimously decided to open the publication field to mean: "This is what we want you to cite when you cite this ontology" as opposed to "this is the peer-reviewed publication we have produced describing the ontology".

However, @cthoyt raises valid concerns to just make the `publication` field a complete free for all:

https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1846

We have now increased the range of actionable (you can obtain metadata about it, like, who are the authors, using an API or similar)/persistent identifiers that are permissible to:

- PUBMED_PREFIX = "https://www.ncbi.nlm.nih.gov/pubmed/"
- ARXIV_PREFIX = "https://arxiv.org/abs/"
- BIORXIV_PREFIX = "https://www.biorxiv.org/content/"
- MEDRXIV_PREFIX = "https://www.medrxiv.org/content/"
- ZENODO_PREFIX = "https://zenodo.org/record/"
- DOI_PREFIX = "https://doi.org/"
- CHEMRXIV_DOI_PREFIX = "https://doi.org/10.26434/chemrxiv"

Note that Zenodo has 0 content review, the the burden of uploading a report there is minimal. I think in the spirit of actionable metadata, I would like to follow @cthoyt lead on the matter and promote such structured, actionable identifiers rather than allowing any kind of pdf to be linked. 

Related issues:
- https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1826

### Vote

👍 I am convinced: structured actionable metadata for publications is a good cause. We may be adding further exceptions as we move forward, but not go back to wild west.
🎉 Sounds like a nice plan to have structured actionable metadata but I still want my workshop report to be cited, and its too much of a burden to upload to Zenodo (or another preprint server).

**Comment by graybeal** [comment]
This is a quibble, not so much to affect the main vote as to consider how we might influence things going forward.

I think it is not quite enough to say "there's an API". We need to be able to count on the fundamental queries in that API to change relatively rarely. In BioPortal we had a Resource Index that used over 40 data sources, and in 5 or so years a significant percentage of them stopped working. If you're going to put an actionable IRI into a structured metadata item, then there is some responsibility to avoid making it a maintenance burden for people trying to use it. 

I'd almost rather have a controlled vocabulary, which someone maintains, and which does resolve to the required APIs for each 'term'=publication.  But for practical reasons, maybe conversations with the API providers ("To get on our list of approved APIs, yours have to be at least this persistent!") would be be best tactic.

**Comment by cthoyt** [comment]
Just wanted to point out that in #1890, we had our first successful follow-up to a discussion where the ontology's responsible person suggested a non-actionable URL to a PDF, we were able to communicate why this wasn't so great, provide alternatives (e.g., uploading to arXiv or Zenodo), and they were easily able to do so. You can see how this looks on  Zenodo here: https://zenodo.org/record/6522019. Note, it's also got conference information there!

**Comment by cthoyt** [comment]
Reminder that the voting period will close end of day tomorrow (May 13th)

**Comment by cthoyt** [comment]
So feedback was generally pretty positive for this and the voting period has ended. A few possible next steps before closing this issue:

1. Figure out what OBO Foundry Principle is most appropriate to update to reflect this
    - include a clear definition of *actionable*
    - consolidate text about the reason why we're going to enforce this
    - include counterexamples and why they're bad / not useful / not what we want for OBO Foundry
2. We need to prepare a guide to walk through people who want to include a citation that's not *actionable* e.g., a PDF that was published in the proceedings of ICBO, which is a case that's popped up 3 times since we start talking about improving this metadata a few weeks ago.
3. We need to prepare a very simple governance on how additional *actionable* citation types can be proposed and what the criteria are (e.g., why are DBLP and Semantic Scholar not good enough but arXiv is?)
4. Update the right OBO Foundry Principle with all of this information

**Comment by matentzn** [comment]
Thank you @cthoyt I will check with OFOC today which principle is appropriate for this.

**Comment by matentzn** [comment]
@cthoyt can you draft a 3 sentence statement that defines and motivates the use of actionable publication identifiers in OBO metadata and codifies the decision that they are required?

**Comment by nlharris** [comment]
@cthoyt please see Nico's request above!

**Comment by matentzn** [comment]
Ping @cthoyt wanna wrap this up.. :) Thanks!

**Comment by nataled** [comment]
Will take this up at the next EWG meeting.

**Comment by nataled** [comment]
After discussion, the EWG recommends that this information be part of a more global description of the contents of a YAML file. Currently no such description exists. The closest is the FAQ question ["How do I edit the metadata for my ontology?"](https://obofoundry.org/faq/how-do-i-edit-metadata.html) which contains the following:

---
A few key properties to be aware of:

    layout - this is not actually metadata about the ontology but controls how the page is displayed. You should not mess with this unless you are a web style guru.
    id - this should not be touched. Your ontology id is fixed in the system by OBO administrators at time of registration and should never be changed. Contact the OBO team if you have a valid reason for changing this. See [ID Policy](https://obofoundry.org/id-policy.html)
    title - a short name for your ontology - this is typically the spelling out of your ontology acronym.
    description - a short one line description of your ontology. It should state concisely what the contents of the ontology are. Don’t write this like a paper abstract. You can be more verbose in the custom section below
    tracker - typically a github issues url
---

We believe a full document needs to be created, and the contents of that document should be in accordance with what is in the ["Request a New Ontology" issue](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology.yml&title=Request+for+new+ontology+%5BNAME%5D) (and vice versa).

**Comment by cthoyt** [comment]
It would be nice if we could create a temporary place for this so we can close out this issue and the related issues while we wait for doing what you suggested, which I expect will take a while

**Comment by nataled** [comment]
As mentioned, there's no good place for it now. We'll get input on the next Ops call as to the preferred next steps (create new document, or pigeon-hole it somewhere else).

**Comment by matentzn** [comment]
So basically, we need some kind of human readable version of the OBO metadata schema, and fiddle this into the submission guidelines. What about this as a intermediate solution. 
1. We create a new FAQ: "How to prepare and maintain your OBO Metadata record?" and stick it with the other FAQ items. We add a few words how the file is prepared (blueprint from OBO Dashboard, optional curated elements). We add an explanation for the papers.
2. We link that question from the respective section in the Request New Ontology docs

**Comment by nataled** [comment]
@cthoyt you implied in your '3 sentence' write-up that permissible identifiers can be either a CURIE or a URI. Spot checks of a few metadata files shows only URIs. Can you confirm whether or not something like 'PMID:12345678' will work?

**Comment by cthoyt** [comment]
First step was just to standardize the URIs, but a next step will be to further cut them down to use standard prefixes

**Comment by nataled** [comment]
Thank you. At this stage then the FAQ should not mention CURIEs until allowed. 

Another question: The write-up also implies that arXiv and bioRxiv can be cited directly, as opposed to medRxiv and ChemRxiv which can only be done using DOIs (for example, both https://chemrxiv.org/engage/chemrxiv/article-details/61ec153b8d70c3d3600a0e6b and https://doi.org/10.26434/chemrxiv-2021-dtpv3-v11 point to the same resource). Is the different standard intentional, or should all these require DOI?

**Comment by cthoyt** [comment]
It's the case that chemRxiv used to have its own service for getting metadata based on a chemRxiv local unique identifier for papers, but they changed services and that doesn't exist anymore. I am not super familiar with medRxiv so I wasn't sure if it had this kind of API (last time I checked, it explicitly disabled the ability for users to interact with its API in full...)

**Comment by cthoyt** [comment]
I think that's a reasonable simplification.

**Comment by nlharris** [comment]
Is this issue awaiting some sort of decision by the OFOC?

**Comment by matentzn** [comment]
No all decisions are made. Removed the label.

**Comment by cthoyt** [comment]
Following #1988 and series, are we ready to close this?

**Comment by nataled** [comment]
Yes. Just verified that it is now public.
