### ISSUE TITLE
Drafting OBO Foundry SOPs and process documentation

### ISSUE THREAD

**Issue by pbuttigieg** [OBOFoundry/OBOFoundry.github.io#1867]
As in #1861, the OBO Operations call on 2022-04-19 an action to begin documenting and clarifying the standard operating procedures and conventions of OBO operations was set. 

This will provide a basis upon which governance processes may be applied or spliced in (xref efforts by @mellybelly et al.). 

Drafting will begin on a [Wiki page](https://github.com/OBOFoundry/OBOFoundry.github.io/wiki/OBO-Foundry-Standard-Operating-Procedures).

### To contribute to this issue

Please use this issue to identify which processes should be documented. We will open separate issues for more detailed discussions on each process. 

Please indicate support for a topic (to help us prioritise work) using a 👍 on the post, as demonstrated on this post (Edit: you can +1 your own suggestion).

**Comment by pbuttigieg** [comment]
Topic: Documentation (and re-factoring) of the OBO ontology review and classification process for ontologies (a long-standing issue, now being addressed more formally in #1861)

**Comment by nlharris** [comment]
Topic: Process for adding new OBO Operations Committee members? #1280

**Comment by nlharris** [comment]
Topic: Develop SOP for Changing Ontology Metadata #1848

**Comment by nlharris** [comment]
I feel like the items in this issue have now been addressed -- does anything remain to be done?

**Comment by nlharris** [comment]
Closing as done -- please open new tickets if there are still specific items to be completed.
