### ISSUE TITLE
Request for new ontology : Vertebrate Breed Ontology (VBO)

### ISSUE THREAD

**Issue by sabrinatoro** [OBOFoundry/OBOFoundry.github.io#1883]
<a href="https://obofoundry.org/obo-nor.github.io/dashboard/vbo/dashboard.html"><img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOFoundry%2Fobo-nor.github.io%2Fmaster%2Fdashboard%2Fvbo%2Fdashboard-qc-badge.json" /></a>

### Title

Vertebrate Breed Ontology

### Short Description

A single computable resource for vertebrate breed names

### Description

Online Mendelian Inheritance in Animals (OMIA) provides up-to-date summary information on all known harmful and beneficial variants in vertebrates (apart from those vertebrates that have their own similar resource), together with background information on all known inherited disorders and non-disease traits, which are collectively called ‘phenes’. OMIA is hosted by the Sydney School of Veterinary Science (SSVS) within the University of Sydney.

As OMIA developed over the past 26 years, breed names were entered as published in the papers reporting the phenes. Inevitably, the resultant OMIA list of breed names contains inconsistencies, duplications and errors. The ever-increasing inter-connectedness of the internet has highlighted the need for OMIA to adopt a standardised vocabulary for breeds that will enable OMIA to be reciprocally hyperlinked with other relevant internet resources.

The Anstee Hub for Inherited Diseases of Animals (AHIDA) is a new initiative from the SSVS. Currently under development by the Sydney Informatics Hub (SIH) in collaboration the AHIDA team, and with a projected launch in 2022, it will be a web resource for surveillance, reporting and control of inherited diseases in animals. As with OMIA, AHIDA requires a standardised vocabulary for breeds that will enable AHIDA to be reciprocally hyperlinked with other relevant internet resources.

Inspired by the development of the Livestock Breed Ontology (LBO) by Zhiliang Hu, James Reecy and Cari Park at Iowa State University (ISU), the OMIA and AHIDA teams are collaborating with the SIH, with the instigators of the Monarch Initiative and some of their colleagues, and with the creators of LBO to create a breed ontology ― a Vertebrate Breed Ontology (VBO) ― that will include all the known breed names (including synonyms) for all species that are relevant to OMIA and AHIDA.

By far the most comprehensive global resource for breeds is the list of breed names and synonyms compiled by the Food and Agriculture Organisation (FAO) of the United Nations in its Domestic Animal Diversity Information System (DADIS). A powerful attribute of DADIS is that its information is contributed and updated by designated National Coordinators from each of 182 countries. DADIS contains information on more than 15,000 national breed populations representing more than 8,800 breeds across 38 species.

In collaboration with FAO colleagues responsible for DADIS (Roswitha Baumung and Gregoire Leroy), the VBO team is using the DADIS list of breed names and synonyms as the basis for the development of the VBO.

Breed names and synonyms not included in the DADIS list, e.g. for cats, will be added to the VBO. OMIA breed names will then be mapped to VBO ids, as will LBO ids and ids or names from other relevant breed lists. Once developed, the VBO will be incorporated into OMIA and AHIDA, and will be made freely available. It is recognised that, as with the LBO, there will be a continual need for enhancement of the VBO.

### Identifier Space

VBO

### License

CC-BY 4.0

### Domain

organisms

### Source Code Repository

OBOFoundry.github.io

### Homepage

https://monarch-initiative.github.io/vertebrate-breed-ontology/

### Issue Tracker

https://github.com/monarch-initiative/vertebrate-breed-ontology/issues

### Ontology Download Link

https://raw.githubusercontent.com/monarch-initiative/vertebrate-breed-ontology/master/vbo.owl

### Contact Name

Sabrina Toro

### Contact Email

sabrina@tislab.org

### Contact GitHub Username

sabrinatoro

### Contact ORCID Identifier

0000-0002-4142-7153

### Formats

- [X] OWL RDF/XML (.owl)
- [X] OBO (.obo)
- [X] OBO Graph JSON (.json)

### Intended Use Cases and/or Related Projects

Online Mendelian Inheritance in Animals (OMIA, https://omia.org) will use VBO to model their data and make it interoperable.

### Data Sources

Domestic Animal Diversity Information System (DAD-IS) breed list [​​https://www.fao.org/dad-is/en/].

### Additional comments or remarks

We are aware that the majority of terms in VBO do not have definitions (and therefore the corresponding checkbox below was not checked). Breeds are defined as specific groups within a species that have a phenotype, behavior and/or other characteristics sufficiently distinctive for other members of the species to have been given distinctive names. These distinguishing characteristics are not often recorded/communicated. 

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [ ] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by matentzn** [comment]
@sabrinatoro thank you for your submission! Before we assign reviewers and start looking at your ontology, you have the pass the OBO dashboard:

https://obofoundry.org/obo-nor.github.io/dashboard/vbo/dashboard.html

Please let us know when you have fixed all issues (aside from `usages` this may be open/red).

**Comment by sabrinatoro** [comment]
Thank you @matentzn !
The errors from the OBO dashboard have (should have) been resolved. We are however aware of the following outstanding issues that will be addressed at a later stage:
- **Plurality of Users :** At this point, Monarch Initiative and OMIA are committed to using VBO (OMIA is in the process of incorporating VBO in their data). Other organizations with non-human animal data have also communicated their willingness to adopt VBO; discussions are ongoing.  
- **Textual Definitions :** We are aware that the majority of terms in VBO do not have textual definitions. Breeds are defined as specific groups within a species that have a phenotype, behavior and/or other characteristics sufficiently distinctive for other members of the species to have been given distinctive names. Therefore, the concept of a breed is not definable in scientific terms, and there are no scientific criteria for a group of animals to be called a breed.

**Comment by ddooley** [comment]
Hi,
Its neat to see VBO built with ODK, and it looks like some ROBOT generated input.  ID's look fine.

It looks like the src/ontology/imports/ncbitaxon_terms.txt needs to be regenerated into ncbitaxon_import.owl to get rid of a handful of NCBITaxon items showing at top level of VBO.

The names of the species look a little funny with semicolons in them and countries up front, but I understand they need to be there to distinguish regions that a particular product originated from.

Is the Livestock Breed Ontology (LBO, https://bioportal.bioontology.org/ontologies/LBO) going to be rolled into VBO?  Can you give some guidance about which ontology would be supported into the future?  It seems like LBO is active.

I was wondering if it is appropriate to upgrade a few things that are annotations into object properties:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/4000582/171111822-e09f2781-a069-466a-9625-dcc287fa810b.png">
I was thinking rather than have an annotation property "exists in country" that restricted itself to a string reference to Wikipedia country, possibly the generic "located in" could be used.  But RO states that is a relation between instances.  I'll check with OBO folks about that. It would be nice if the wikidata countries (or other geographical location identifiers like "Mount Meru") be an import file?  Then each country could get an ISO code, rather than the shadow annotation of subspecies to the ISO code.

As well, the domestication status looks like something that could be reasoned over, something that has states or qualities.
<img width="867" alt="image" src="https://user-images.githubusercontent.com/4000582/171112643-ff687a04-1d3b-4a3c-b9c7-01434bef86e3.png">
Perhaps a "domesticated" quality, so "'African, Ukrane; Ostrich' has quality some 'domesticated quality' "?  Or perhaps 'has disposition' some 'domesticated disposition'?

**Comment by bpeters42** [comment]
One question / suggestion: Are animals bred for research purposes (e.g. Syrian hamsters, B6 mice) in the scope of this ontology? That is one area we are very interested in, and it would be great if information on e.g. strains from Jackson labs could be represented in the same broader format. Completely understood if that is outside of your main domain, but it will be nice to have different extensions of NCBI taxonomy done in a compatible ways.

**Comment by ddooley** [comment]
Discussed on OBO Operations committee, and aside from the desire to have a few questions about annotation usage above answered, the committee has accepted VBO into the foundry!  I will send a followup email.

**Comment by sabrinatoro** [comment]
@ddooley and @bpeters42 
I want to reflect here what I said in my email as I don't think it was sent to everyone. 
Thank you for accepting VBO into the obo foundry! And thank you for taking the time to review it and offering feedback and suggestions.
I am still consulting with the team, and therefore it is taking me longer than expected to get back to you. I will however answer to your feedback and suggestion as soon as possible. Thank you for your patience.

**Comment by nlharris** [comment]
What are the next steps here?

**Comment by sabrinatoro** [comment]
We are working (slowly) on the suggestions offered here. 
Here is an update: 
# 
> It looks like the src/ontology/imports/ncbitaxon_terms.txt needs to be regenerated into ncbitaxon_import.owl to get rid of a handful of NCBITaxon items showing at top level of VBO.

The reason for the NCBITaxon items showing at top level of VBO was that they were not in the NCBITaxon Ontology.
We added these NCBI_taxon in https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt, and they should show up in the VBO main classification after the next NCBITaxon ontology release.

# 
> Is the Livestock Breed Ontology (LBO, https://bioportal.bioontology.org/ontologies/LBO) going to be rolled into VBO? Can you give some guidance about which ontology would be supported into the future? It seems like LBO is active.

We are working with colleagues at LBO and have an upcoming scheduled meeting to determine our plan. It is clear to the VBO and LBO teams that eventually, VBO and LBO will merge or LBO will become a part of VBO. In the short term, we are planning on creating non-ambiguous mappings between VBO and LBO.

# 
>I was wondering if it is appropriate to upgrade a few things that are annotations into object properties:
I was thinking rather than have an annotation property "exists in country" that restricted itself to a string reference to Wikipedia country, possibly the generic "located in" could be used. But RO states that is a relation between instances. I'll check with OBO folks about that. It would be nice if the wikidata countries (or other geographical location identifiers like "Mount Meru") be an import file? Then each country could get an ISO code, rather than the shadow annotation of subspecies to the ISO code.

- we added a subclass axiom for country, using the object property "located in" as we couldn't find a more precise relation (note: we debated whether to create a new relation called "has geographical location"). 
- the wikidata countries have been made an import file. 

# 
>As well, the domestication status looks like something that could be reasoned over, something that has states or qualities.
Perhaps a "domesticated" quality, so "'African, Ukrane; Ostrich' has quality some 'domesticated quality' "? Or perhaps 'has disposition' some 'domesticated disposition'?

We are still investigating this. We need to review breed information from the other species to determine whether this "domestication status" is required for breeds other than the livestock breeds. If so, we need to make sure that the solution (e.g using a "domesticated" quality) will work for all the breeds. 

# 
>One question / suggestion: Are animals bred for research purposes (e.g. Syrian hamsters, B6 mice) in the scope of this ontology? That is one area we are very interested in, and it would be great if information on e.g. strains from Jackson labs could be represented in the same broader format. Completely understood if that is outside of your main domain, but it will be nice to have different extensions of NCBI taxonomy done in a compatible ways.

YES! We are definitely discussing including laboratory animal breeds/strains into VBO. This has not yet become a priority as we are currently working on improving the current ontology (focused on livestock breeds) and adding cat breeds, but this is definitely on our to-do list. We have been in communication with members of the “Immune Epitope Database and Analysis Project” for whom including these strains in VBO would be useful, and are planning to work with members from the mouse and rat community to ensure that existing resources can be reused and/or leveraged. 

# 
>The names of the species look a little funny with semicolons in them and countries up front, but I understand they need to be there to distinguish regions that a particular product originated from.

We recognize that the concatenation of name+country+species for livestock breed label is less than ideal. We have investigated using parenthesis instead of semicolons. We also investigated other solutions, but we have not been able to find an alternative that would ensure term labels to be unique (since the same breed name can refer to breed in different species and/or different country).

**Comment by matentzn** [comment]
Thank you @sabrinatoro for the detailed response! I hope VBO will continue to be a FAIR ontology resource for the representation of breeds in the ontology world.
