### ISSUE TITLE
Should MAMO be marked as orphaned?

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1886]
Nicholas Gambardella has remained quite elusive while contacting responsible people for OBO Foundry ontologies. He was unresponsive in email over the last year or so, I had to ask around to find out his name had changed and to get his GitHub @gambardella, which was recently deactivated (yes, I'm 100% sure this was right before and checked for typos).

I think it's time to remove this name from the MAMO ontology (https://obofoundry.org/ontology/mamo, https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/mamo.md) and mark it as orphaned, since this repository is unmaintained on SourceForge and the responsible contact is unresponsive.

**Comment by nlharris** [comment]
Sounds reasonable to me. (BTW I'm not sure revealing his past and present names here is appropriate? He may have private reasons for changing his name.)

**Comment by cthoyt** [comment]
this information is part of the commit history in this project, so it's pretty public knowledge both in the scope of this project and externally. Being responsible for an ontology in the OBO Foundry is also commitment to having this kind of public presence, too, so I'd hope this kind of discussion isn't too controversial.

**Comment by matentzn** [comment]
At the OBO operations call we decided that its ok to mark MAMO as orphaned based on the information you provided. However, I do see some activity on their code base by @niko-rodrigue.

@niko-rodrigue are you perhaps the new contact of MAMO? Would you be able to provide some information in regards to its status? Can we add you as the contact?
