### ISSUE TITLE
Unclear sentence in the OBO foundry principles: Open::ontology reuse::principle 2

### ISSUE THREAD

**Issue by linikujp** [OBOFoundry/OBOFoundry.github.io#189]
For ontology re-use: principle 2:
'After any external alterations to an ontology, the ontology must not be redistributed under the same name or with the same ontology IRI.'

This sentence is not clear in the following aspects:
1. What does it mean 'external alternation'? Is there anyone who alter the ontology in a whole or in part.
What I often observed is that we often alter the terms of the ontology, but not the whole ontology.

**Comment by nataled** [comment]
Note: Actual principle this pertains to is #1 http://obofoundry.org/principles/fp-001-open.html

**Comment by nataled** [comment]
This issue has been discussed, with a tentative decision to reword the pertinent section as follows:
===
Original:
After any external alterations to an ontology, the ontology must not be redistributed under the same name or with the same ontology IRI.

Reworded: 
Altered versions of an ontology that are not part of an official release (that is, by the ontology developers) must not be redistributed under the same name or with the same ontology IRI.
===

Note that this (we hope) addresses the first point regarding what is meant by 'external alteration'. Technically speaking, ANY change--even to one term--is considered a change to the ontology as a whole if made and distributed in the context of the whole ontology, and thus the directive about the ontology name and IRI applies. Alterations to individual terms not distributed as part of the whole ontology is covered by the 3rd point.

Please let us know if the proposed changes clarify the issue.

**Comment by nataled** [comment]
Revised as indicated above.
