### ISSUE TITLE
trouble building ncro obo

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#190]
I added the following to my build

```
build:
  source_url: http://purl.obolibrary.org/obo/ncro/prebuild/ncro.owl
  method: owl2obo
```

I've checked that the URL works. However the build failed with the log message included below.
BTW, the current version (soon to be replaced) is inconsistent. Will that prevent an OBO build? Is there a way to specify whether or not reasoning should be applied?

```
Thu Dec 10 23:17:59 PST 2015 :: ONTOLOGY: ncro
Use of uninitialized value in lc at /srv/nfs/share/jenkins/workspace/simple-build-obo-all/owltools/build-obo-ontologies.pl line 89.
Thu Dec 10 23:17:59 PST 2015 :: Missing obo or owl files for ncro
Thu Dec 10 23:17:59 PST 2015 ::   RUNNING: rsync -avz ncro failed-builds && rm -rf ncro
sending incremental file list
rsync: link_stat "/srv/nfs/share/jenkins/workspace/simple-build-obo-all/ncro" failed: No such file or directory (2)

sent 12 bytes  received 12 bytes  48.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
ERROR RUNNING: rsync -avz ncro failed-builds && rm -rf ncro [in ncro ] code: 5888
```

**Comment by cmungall** [comment]
Note you don't need a build tag. But I will help figure this out late

**Comment by alanruttenberg** [comment]
@cmungall thanks

**Comment by cmungall** [comment]
The ontology PURL for NCRO is incorrect:

```
   <owl:Ontology rdf:about="&obo;ncro/ncro.owl">
 ```

should just be `&obo;ncro.owl`

**Comment by alanruttenberg** [comment]
There is no mistake as far as I can tell.  The prebuild is a file. I have given a location of that file. It is not the released ontology fille - it is another artifact. 

The ontology at /obo/ncro.owl does in fact have the correct ontology IRI

--

There are hidden assumptions about the build process, obviously. Can I ask that they be made explicitly?  They are not obvious, and I am not finding them intuitive.

**Comment by nlharris** [comment]
Are there still things here that need to be addressed?

**Comment by jamesaoverton** [comment]
I think it's safe to close this. Please reopen if I'm mistaken.
