### ISSUE TITLE
Generalize "biochemistry" domain to "chemistry and biochemistry"

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1908]
I dont know the difference - we could rename biochemistry to `chemistry` or `chemistry and biochemistry`? Maybe adding `chemistry` and `biochemistry` makes it hard for some people to chose which is more suitable?

_Originally posted by @matentzn in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1884#discussion_r866634979_

**Comment by nlharris** [comment]
Sounds reasonable to me!
