### ISSUE TITLE
Principle 4 "Versioning": clarify "version" string in version IRI

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1921]
So far, the versioning principles only insists on two things:

1. A version IRI MUST exist
2. A version IRI MUST resolve
3. A version IRI SHOULD use the OBO recommended format

However, this can lead to version iris like this:

```
versionIRI: http://obofoundry.org/
```

This is clear not a good version IRI despite the fact that it

- exists
- resolves

I think we should require a version IRI to 

1. either contain an ISO date string (2022-03-01)
2. or a semantic versioning string (2.0, 2.0.1, 2.0.1-alpha)

 (i.e. a version IRI string `MUST` contain one of the above)

I think this is in the spirit of the "versioning" principle, so I don't think this needs a new vote, but correct me if I am wrong!

@cthoyt already started implementing a check for that, should this proposal pass:
https://github.com/OBOFoundry/OBO-Dashboard/pull/70

**Comment by matentzn** [comment]
Not sure this is enough. You can still fake it by providing the purl as the version iri.. at least it is very hard to see computationally that a supposed version iri works still after the next version is release. I still think the iri should contain some kind of versioning information..

**Comment by balhoff** [comment]
I suppose you're right; but I think my condition would also be a valuable check to ensure the version IRI does what it's supposed to do.

**Comment by matentzn** [comment]
I am thinking of dashboard practicality - I would have to write some really smart code to do this check to avoid having to redownload chebi..

**Comment by nlharris** [comment]
See also: #741, #1016, #1347, #1414, #1707

**Comment by nataled** [comment]
I also think we should remove the link to the w3.org description of IRI and version IRI, as it uses 'may' when we say 'should'. I found it confusing. Let me know if there is anything in the w3.org description (https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI) we don't already capture that you think is needed.

**Comment by matentzn** [comment]
I will look at the PR and let you know. Thanks @nataled!

**Comment by nataled** [comment]
Fixed by  #1933
