### ISSUE TITLE
improve "Tutorials" section of Resources page

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1929]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/resources.md

It should at least point to OBO Academy, right? Maybe @nicolevasilevsky can suggest improvements to this page?

**Comment by nlharris** [comment]
Oh wait -- I just realized [OBO Semantic Engineering Training](https://oboacademy.github.io/obook/) is the link. But is "Semantic Engineering Training" an intimidating way to phrase it?

Also, I think the Resources page should include a link to https://obofoundry.org/resources (perhaps under Ontology tools).

**Comment by nicolevasilevsky** [comment]
@nlharris what would you recommend instead of 'semantic engineering'? Maybe just OBO Ontology training? Or we could just add a description like - self-paced ontology training materials, including tutorials, how-to guides, reference material and explanations

**Comment by nicolevasilevsky** [comment]
> Also, I think the Resources page should include a link to http://dashboard.obofoundry.org/ (perhaps under Ontology tools).

sounds good!

**Comment by matentzn** [comment]
I think less emphasis on the training and more on the resource in this context: OBOOK: open documentation for biomedical ontology engineering or some such. Dashboard link is already added by Charlie
