### ISSUE TITLE
FLOPO ontology and prefix

### ISSUE THREAD

**Issue by leechuck** [OBOFoundry/OBOFoundry.github.io#193]
Hello,

We would like to request the FLOPO prefix and inclusion of FLOPO in the OBO library. We sent a mail to obo-discuss for community feedback on 22 Nov 2015, and there seem to be no concerns by the community so far (within the 2 week discussion period specified in the OBO guidelines).

The ontology is available at https://github.com/flora-phenotype-ontology/flopoontology/tree/master/ontology

With best wishes,
Rob.

**Comment by cmungall** [comment]
You may want a more specific taxon for flowering plants. Just make a PR with any requested changes

**Comment by cmungall** [comment]
Note: this isn't in the obolibrary space, so no edit to purl.obolibrary.org github is required.

AFAICT the URL space contravenes recommendations but does not bar from the library, and we have a precendent here

**Comment by leechuck** [comment]
Great, thank you Chris! We'll fix the URLs before Christmas.
