### ISSUE TITLE
Mark ERO and OGI as obsolete?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1942]
https://obofoundry.org/ontology/ero.html
https://obofoundry.org/ontology/ogi.html

http://purl.obolibrary.org/obo/ero.owl
http://purl.obolibrary.org/obo/ogi.owl

PURL does not work at all anymore.

Can someone contact owners?

**Comment by rvita** [comment]
I contacted Marc Ciriello and Juliane Schneider about this 5/26/22

**Comment by matentzn** [comment]
Thank you @rvita

**Comment by matentzn** [comment]
Thank you @rvita, see #1944. Let me know if you learn anything regarding OGI!

**Comment by rvita** [comment]
I was never able to find a contact person for OGI. Does anyone know Lin Yu?

**Comment by cthoyt** [comment]
CC @linikujp they're trying to get in touch

**Comment by cthoyt** [comment]
@rvita I also added all relevant contact information in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1953 if you want to reach out on non-public channels

**Comment by linikujp** [comment]
Thank you @cthoyt and @rvita , I left the comment and questions at #1953 . Please let me know.

**Comment by nlharris** [comment]
What was decided about this?

**Comment by matentzn** [comment]
It's finished! OGI incorporated into OGSF and ERO is obsoleted, closing.
