### ISSUE TITLE
Archive obsolete "Ontology Tools" page

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#1955]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/OntologyTools.md is subsumed by https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/resources.md (and I don't think this obsolete Ontology Tools page is linked to anywhere). I'm not sure I can request deletion (or archiving? is that a thing?) of a file as a PR. If it is agreed that I can get rid of OntologyTools.md I'll just do it.

**Comment by nlharris** [comment]
I did not find any links to it.

These two are mentioned in OntologyTools.md and not resources.md -- add?
> [Onto-Animals](http://www.hegroup.org/ontozoo/)
The Onto-Animal tools support efficient integrated ontology development. These tools can be used together to extract external ontology terms, compare ontologies, edit ontology terms, query and visualize ontologies, and more.

> [AberOWL](http://aber-owl.net/)
AberOWL is a repository of biological ontologies and access to reasoned versions of those ontologies. Ontolgies can be browsed by term labels or queried by Manchester OWL syntax statements.

**Comment by matentzn** [comment]
100%, need to be added.

ontobee is an onto animal, so they can be put underneath one another, AberOwl in the same section as ontobee/OLS

**Comment by nlharris** [comment]
ok, added those. #1959
