### ISSUE TITLE
Add "date added" field to ontologies

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#1967]
This would be pretty difficult to get for old ontologies, so maybe we have to add a dummy value, but it would be very valuable to have the date added on all new ontologies such that we could apply new, higher quality standards to them in a reproducible programmatic way. This would require a few things

1. Add a new field to the JSON schema that can either be a date, or some pre-defined flag
2. Auto-populate existing ontologies with some kind of flag

**Comment by matentzn** [comment]
Full support.

**Comment by lschriml** [comment]
As we all used SourceForge to begin with, a date from that system would be more precise.

**Comment by matentzn** [comment]
@lschriml impossible to reconstruct now though. I think the point really is, that is what I at least care about, that we can specify QC checks as mandatory _moving forward_ - without having to wait for old ontologies to implement. We can have higher standards for new ontologies :)

**Comment by matentzn** [comment]
During yesterday's OFOC call we decided to go with the "`obo_library_since:`" solution that reflects when an ontologies was admitted into the OBO Library, rather than using the `github_added` suggestion proposed by @cthoyt in #1969. However, there was no agreement how to represent unknown values. Due to our use case, we cannot simply omit the tag from the markdown file, so we need to have a vote on the representation of an unknown join date.

## Vote: default date for ontologies where the date of joining OBO foundry is unknown

👍 `obo_library_since: 1001-01-01`
🎉 `obo_library_since: `
👀 `obo_library_since: NA`

This vote is only about the missing value. Where we have this information, we use xsd:date format: `2022-02-01`. Voting closes 20th July.

**Comment by hoganwr** [comment]
[image: image.png]

**Comment by hoganwr** [comment]
Sorry, still learning  Was not clear at al.  Sorry I missed yesterday's
meeting.

**Comment by cthoyt** [comment]
I'm sorry to see that the original purpose of this issue has been lost - the problem we need to solve is to tag each ontology with a date when it was added to OBO so we can enforce stricter automated checks differentially on new ones (since old ones will be slow to adopt new standards, if ever)

The semantics of whether we use "date added to this git repository" (which can be easily accomplished technically, as https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1969 demonstrates) or "when was this accepted into OBO" which is super difficult because this wasn't tracked and there were previous repositories that got migrated into git. Both solutions would help solve the actual problem I want to solve. Again, the first solution technically easy to accomplish, but it seems to be difficult to communicate. The second solution is effectively intractable, since I don't think anyone wants to do this hard work.

The **100% unacceptable solution** would be to make it possible to have a blank field or to make it possible to write NA, since 1) it means we can't validate the contents of this field in a consistent way and 2) new ontology submitters can reverse engineer this and therefore skirt the checks.

**Comment by hoganwr** [comment]
This is about date added and the vote, which explicitly allows you to vote
for empty value in the date field as one option, and NA as the value for
the date field as another option.

This one's not about actionable identifiers.

**Comment by matentzn** [comment]
Yea, I am illustrating about the 100 ways you can fool the automated schema checker into thinking your metadata was correct, and suggesting @cthoyt worries a bit much here..

**Comment by hoganwr** [comment]
The vote is about what the automated checker will allow, or I am
misunderstanding things greatly.

**Comment by matentzn** [comment]
No, thats right! Its about how we should represent "missing values" in a
way that the automated checker will ignore it.

**Comment by cthoyt** [comment]
I'm happy with not doing this, now that we have better ways of applying more strict standards to new ontologies. Thanks everyone for the discussion, and sorry to the people on the OFOC call who spent time on this. I assume that nobody else will pick up doing the ver difficult work of getting the technical side right, but invite anyone who is interested to revive this issue.

**Comment by matentzn** [comment]
I am kinda sorry to see this issue go, but given our priorities, probably the right call. We can always come back to this, and use "first committed" timestamps to approximate "date joined"! Thanks @cthoyt
