### ISSUE TITLE
OBO prefix map should include prefixes of obsolete ontologies

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1976]
I think OBO prefix map should contain prefixes of obsolete ontologies. Sometimes, like [here](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1974/files) one ontology is merged into another, with identifiers and all - it would still be useful to be able to loop these up.

@jamesaoverton objects to that?

**Comment by jamesaoverton** [comment]
I agree.

We don't want to accidentally reuse a prefix for a new project B, when there may be old data / links out there that used the same prefix for an obsolete project A.

**Comment by matentzn** [comment]
Thank you!
