### ISSUE TITLE
Common subset tags across OBO

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#1989]
We are getting closer than ever to having the OBO library ontologies work really well together and as we aim for orthogonality, we also need to aim to be able to generate slices of multiple ontologies for different applications. The creation of a common set of subset tags and registry for such artifacts might help with the proliferation of overlapping ontologies and promote reuse and alignment.

**Comment by matentzn** [comment]
Thank you @mellybelly I agree, this is an important issue!

We are discussing unification of subsets [here](https://github.com/information-artifact-ontology/ontology-metadata/issues/80), so I will close this issue here, but will add your comment there as well.
