### ISSUE TITLE
Dialogue towards possible collaboration with/inclusion of Allotrope Foundation ontologies

### ISSUE THREAD

**Issue by Woolfben** [OBOFoundry/OBOFoundry.github.io#1998]
Hi, I'm Ben Woolford-Lim, the Senior Developer of the Allotrope Foundation, a pre-competitive alliance of pharmaceutical companies who publish, amongst other things, the Allotrope Foundation Ontology (AFO) suite. 

We've had a few requests internally to investigate closer collaboration with the OBO Foundry, or indeed possible submission of the AFO to OBO, including from the [developers of PROCO](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1487#issuecomment-824385109) who are both active members of Allotrope. To that end, I'd like to open discussions on what opportunities might exist, so I can make the appropriate recommendations to our leadership. I've done an initial review of the OBO Foundry principles to try and identify the potential options, but I foresee several potential technical challenges to a standard OBO submission due to the way our ontologies are structured, and in particular due to our broad scope as an ontology suite rather than a singular ontology.

What would be the best way to arrange a discussion on the options for submission, or at least closer collaboration between OBO and Allotrope?

**Comment by matentzn** [comment]
@Woolfben Thank you for this issue - I am personally very excited about any attempt to unify the practices in and around biomedical ontologies across the board, and would welcome a closer relationship between Allotrope Foundation and OBO Foundry very much! I have attended a few Allotrope seminars these past years, and there is really a lot space to align on. 

At a very minimum, it would be awesome if we could work on ontology metadata standardisation together, to ensure users of biomedical ontologies can always use the same kind of tools and expect the same kind of properties for definitions, labels etc. We could also align certain aspects of term-reuse practices - I would certainly have a lot of questions of how you keep terms imported from OBO ontologies up to date! 

There are some hurdles with regards to scope overlap - as per OBO scope principle we try very hard to avoid admitting ontologies that cover the same scope of an ontology that already exists in OBO, for example, phenotypes, diseases, assays (the last will incur some debate, i.e. BAO and OBI, I imagine). 

The "internal requests" - did they articulate what they hope to gain from OBO alignment? :)

Talk soon!

**Comment by Woolfben** [comment]
@matentzn Sorry for the delay in responding, it seems Github didn't set up notifications on this issue as I'd expected (we use Gitlab in Allotrope so those setting don't carry over).

I'm likewise keen to see better standardization in use of ontologies in the field, and it's great to hear you've seen some of what we do already so we've got more of a basis for starting the discussion.

Consistent metadata makes a lot of sense to me, though I believe that's going to be an initial point of contention as we use skos:prefLabel and skos:altLabel primarily, which would conflict with the OBO policy of only one rdfs:label since both are subclasses. I have to admit that keeping OBO terms up to date has not been a main focus to date, partly due to the heavy regulation in the pharma industry which Allotrope emerged from - stability is a core concern, so MIREOTing terms in and keeping them stable has generally taken precedence over maintaining parity with current versions.

Scope was one of the main concerns I'd identified in my initial review, along with the fact that Allotrope is really a suite of ontologies (both upper and domain) rather than a singular artifact. I'm not aware of any existing OBO entries that are in a similar position, so I don't know if there's a mechanism for handling an ontology suite, even without the scope questions.

We can of course look to re-use existing OBO terms to address the scope issue, but as we leverage the ontology in our data standards, it would really depend on how large the scope overlap is as to whether that becomes an infeasibly large effort across our suite of domain models.

The main driver I've heard for OBO alignment from our users perspective are the tooling capabilities you have, and the desire to re-use those with Allotrope ontologies. From our end, I'm keen to see better connection with others in the biomedical ontology community, to ensure standardization and consistency of use across ontologies, and avoid reinventing the wheel wherever possible :)

Would it make sense to schedule a call, to lay the groundwork for what we think is feasible and how we would go about it? I live and work in the UK timezone, though I can be somewhat flexible for important topics like this.

**Comment by matentzn** [comment]
I think it makes sense to have you come to one of the upcoming OBO Operations calls and give a brief (~10 min) overview of the Allotrope ontologies (quite a few people at OBO do not know Allotrope, as they are quite new or live in their domain niches), describe how you use OBO ontologies at the moment and talk a bit about what you would like to learn/know. Another possibility is to fold this discussion into the OBO Townhall at ICBO, which involves a larger OBO Foundry audience (the Operations Committee has ~10-15 members).

Do you have any timelines on the matter? Else it may be better to wait until after ICBO (right now, many ppls on holiday). I will raise this at the next OBO ops call.

**Comment by Woolfben** [comment]
At this point, as it's still speculative, I think the OBO Operations call may be a better fit - I don't want to get hopes up in the wider community if it turns out to be infeasible in the end. 

I don't have any specific timelines for this - it's a factfinding mission at this stage, to be able to present the option to the Allotrope leadership with a decent estimate of effort and the advantages/disadvantages of doing so. I would be happy to do two talks if it's useful - a short early call, to prime the pump and get some thinking started, and a more in-depth call after ICBO with the larger group and a little more focus on questions identified in the first call? If that's not practical, then the single call after ICBO is also fine with me.

**Comment by matentzn** [comment]
@Woolfben Could you join us on the next OBO Ops call on the 9th of August at 5pm UK time? If you send me your email (e.g on linked in https://www.linkedin.com/in/nmatentzoglu/) I will send you an invite.

**Comment by Woolfben** [comment]
@matentzn I can do 5pm on Tuesday. I'm afraid I don't have a LinkedIn account, but my email is benjamin dot woolford-lim at allotrope.org - I will remove it from this post once I see the invite email. I'll be out of office from tomorrow until Tuesday however, so I'll have limited ability to respond ahead of that.

**Comment by nlharris** [comment]
Thanks for joining the OBO Ops call (which I was not able to attend), @Woolfben. Are there action items to add to this ticket, or can it be closed now?

**Comment by Woolfben** [comment]
@nlharris I believe the outcome of the Ops call was further discussion and potentially setting up a working group to determine options for collaboration between Allotrope and OBO. I don't know if that needs to be tracked as an action here or internally within the OBO Ops team?

**Comment by nlharris** [comment]
Can this be closed now?

**Comment by matentzn** [comment]
Let us close for now as there are no concrete action items, but this does not mean we should not pursue this! This is probably better pursuable after some move to non-profit status/.
