### ISSUE TITLE
archive faq.html

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2018]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/faq.html (which makes https://obofoundry.org/faq.html) exists but is obsolete and not linked anywhere. (When I searched for occurrences of faq.html, I found on https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/faq/how-do-i-edit-content.md, which has a link to a faq.html but not this one, and the one it points to doesn't exist.)

Can we just trashcan faq.html without losing it from the history?

**Comment by cthoyt** [comment]
More generally, there are _tons_ of documents that aren't displayed on the website and are from the ~2015 era. can we make a purge?

**Comment by nlharris** [comment]
i would be in favor of that as long as i'm not the one who has to do all the searching for and culling of obsolete pages!

**Comment by cthoyt** [comment]
there's always the _false flag_ approach where we delete the whole website and wait for people to tell us what pages they're upset don't exist anymore ;)

**Comment by nlharris** [comment]
yeaaaah let's not do that. (also, that's not what i understood 'false flag' to refer to!)

**Comment by cthoyt** [comment]
Surprise, I'm a pirate! 🏴‍☠️
