### ISSUE TITLE
Use https version of Ontobee.org 

### ISSUE THREAD

**Issue by yongqunh** [OBOFoundry/OBOFoundry.github.io#2027]
At the top of the obofoundry.or webpage: 
https://obofoundry.org/
there is a search bar. 

current it uses http version of ontobee. for example, when searching for term 'vaccine', it goes to the insecure webpage:  
http://www.ontobee.org/search?ontology=&submit=Search+terms&keywords=vaccine

Since ontobee.org has recently updated to use https instead of http, I would suggest changing
http://www.ontobee.org/
to: 
https://ontobee.org/
such as: 
https://ontobee.org/search?ontology=&submit=Search+terms&keywords=vaccine

Thanks, Oliver

**Comment by matentzn** [comment]
I made a PR here, could you check its all ok @yongqunh 

https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2030

**Comment by nlharris** [comment]
BTW, I'm not convinced we should have a "Search Ontobee" search box in the header. Normally one wouldn't have a search box in a header that searches some other site. Can we move this out of the header?

**Comment by matentzn** [comment]
@nlharris yes, I agree with you. Its odd to have that in the header. A prominent link "Search Terms" that brings you to ontobee would be better.

**Comment by nlharris** [comment]
I opened a new issue: Having a "Search Ontobee" search box in the header is weird #2033
