### ISSUE TITLE
Having a "Search Ontobee" search box in the header is weird

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2033]
(this came up in the discussion of #2027)
<img width="1099" alt="Screen Shot 2022-08-19 at 4 30 57 PM" src="https://user-images.githubusercontent.com/348704/185719249-0f3fdfcf-258c-494f-853b-ba5580ea7b27.png">
Normally one wouldn't have a search box in a header that searches some other site. Can we move this out of the header?

@matentzn agreed: "yes, I agree with you. Its odd to have that in the header. A prominent link "Search Terms" that brings you to ontobee would be better."

Yes; I would make the link "Search Ontobee" (and it should open a new tab to go to Ontobee - I realize that opening new tabs from links is controversial, but here we want to send a clear message that you're going to a different site).

**Comment by nlharris** [comment]
See also #1240 for more thoughts about search.

**Comment by nlharris** [comment]
So do we even need to have a Search Ontobee box on the home page, and if so, any good ideas about where it could go that makes it look less like it's searching obofoundry.org?

**Comment by erik-whiting** [comment]
do you have an idea of how often the search box is used? is it completely necssary?

**Comment by nlharris** [comment]
I'm not sure whether it's possible to determine how often it's used, and I'm sure it's not possible to determine how often it's used when that wasn't really what the user meant to do! It's weird to have a search box on the home page that searches some other site, when there is plenty of info right here to search!

**Comment by matentzn** [comment]
Here is my suggestion.

1. Remove OntoBee search from the front page
2. Add the search box at the top, on the left next to the buttons:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/7070631/207279332-5d9d4637-62be-4b6f-9fa3-ec4699b012de.png">

And redirect all of the buttons to the search pages of _any_ of the links there. So if you type:

`heart` in the search box, you can click on `OntoBee` to be redirected to the results on ontobee, same with OLS, same with any of the other links.

**Comment by nlharris** [comment]
That sounds awesome, but I'm not sure how much work it would be. In the meantime, while awaiting this improvement, can we remove the OntoBee search box or make it less prominent (e.g. move to end of page)? It just seems super-weird to have it where it is, looking like a search of obofoundry.org.

**Comment by erik-whiting** [comment]
@matentzn for putting the search box next to the buttons, is there already a component in which there is a small input box? When I do a simple copy and paste, it looks like this:
![image](https://user-images.githubusercontent.com/47164199/207510803-c03b3900-330d-43fa-8919-2fa52004c8bb.png)
I assume you meant the search box and "search" button would be next to the OntoBee button right? Or am I misunderstanding?

**Comment by matentzn** [comment]
This I dont know - I am not that knowledgeable in website stuff..

I was thinking more to have a generic search box component right next to the boxes like:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/7070631/207555867-3fd3967f-d57c-497f-99bb-f3b5a1c769da.png">


So when someone clicks on any of the buttons, they will be redirected either to the resource page (which is what it is doing right now), or, if the search box has content (and only then), redirect to the _search_ functionality of the page, e.g. the search results in that resource within the context of the ontology:

https://www.ebi.ac.uk/ols/search?q=limb&ontology=uberon

**Comment by nlharris** [comment]
I still think it's weird and misleading to have that Ontobee search box in the header. I like Nico's suggestion above but that would obviously be more difficult to implement than just moving the Ontobee search box elsewhere on the page so it's not in the header looking like it's a "search this site" box.

**Comment by zhengj2007** [comment]
Discussed on the call 2023-12-12. We agree to remove the Ontobee search box on the header.

**Comment by nlharris** [comment]
> Discussed on the call 2023-12-12. We agree to remove the Ontobee search box on the header.

So...can we do this?
