### ISSUE TITLE
Wrong version of MI ontology 

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#204]
Getting MI from the OBO PURL does not get the correct version from https://raw.githubusercontent.com/MICommunity/psidev/master/psi/mi/rel25/data/psi-mi25.obo despite the OBO config file containing the correct source URL.

**Comment by cmungall** [comment]
Should be fixed next nightly build of OBO, will check monday

(note that many ontologies are moving towards controlling their own build process and not using fallthrough purls, but mi is still legacy in this respect)

**Comment by cmungall** [comment]
btw the actual fix for mi is to add

```
ontology: mi
```

into their header

**Comment by simonjupp** [comment]
This has been added here MICommunity/psidev@2972967887ef17a250c726ebc551d138f661cc91

**Comment by cmungall** [comment]
update: fix not yet live, need to make a working version of owltools first, wil discuss with @hdietze today

**Comment by cmungall** [comment]
Fix is live
