### ISSUE TITLE
freeform markdown visualization 

### ISSUE THREAD

**Issue by raul-ortega** [OBOFoundry/OBOFoundry.github.io#2047]
Regarding PR [#2044](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2044) once I browse to [https://obofoundry.org/ontology/ontoavida.html](https://obofoundry.org/ontology/ontoavida.html) I don't see any margin between the new description and the top tab button section, nor between the image and the text, a bit different than shown when visualizing the ontoavida.md on GitHub web site.

![imagen](https://user-images.githubusercontent.com/12935392/186460604-11b5c5a3-217d-421b-8f80-795a35ad30ea.png)

It would be very easy to solve it in pure HTML using styles, e.g.:

![imagen](https://user-images.githubusercontent.com/12935392/186460190-81acdd11-83ff-4f5e-bbfe-c816ea03fc51.png)

and it introduces some margins:

![imagen](https://user-images.githubusercontent.com/12935392/186461488-6d4550f9-ad6e-4f03-9c1c-e2d95d2bcf85.png)

But I know that there are some limits when using HTML and styles within Markdown content, and that <p> section might be adding  by Obofoundry web app... 

I wonder if is there any way to  manage this.

Thanks so much.

**Comment by matentzn** [comment]
Trial and error. Just make a PR with the HTML and lets see if it works. 

If you have docker installed, you can test the changes yourself:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md#serving-with-docker

**Comment by cthoyt** [comment]
I already fixed this in #2042 but I still owe nico a PR deconstrution

**Comment by raul-ortega** [comment]
> Trial and error. Just make a PR with the HTML and lets see if it works.
> 
> If you have docker installed, you can test the changes yourself:
> 
> https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md#serving-with-docker

Running... Thanks so much.

**Comment by nlharris** [comment]
the PR has been merged, so can this issue be closed?

**Comment by cthoyt** [comment]
If @raul-ortega is happy with the spacing on the new https://obofoundry.org/ontology/ontoavida, then we should be done here:

<img width="1366" alt="Screen Shot 2022-08-31 at 20 50 43" src="https://user-images.githubusercontent.com/5069736/187759093-fb41f606-533c-46c2-91aa-a0ac4d2dcc75.png">

**Comment by raul-ortega** [comment]
Yes, I'm very happy. Good job!

**Comment by raul-ortega** [comment]
Yes, Young can close it. Good job!
