### ISSUE TITLE
Motion: Opening up OBO Operations Committee calls and meeting minutes

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2048]
I hereby motion to

- open up the OBO Operations Call Meeting minutes in read-only mode to the public
- open up the OBO Operations Call itself for non-members to listen

At the last OBO Operations Call (23 August) I put forward this motion and it was generally received well. Before documenting the valid concerns, I provide details of the Implementation of the motion, as well as concrete items of motivation.

## Motivation

1. **_Recruitement._** The OBO Operations Committee has had a set of about a dozen (mostly) steady members of the last decade, but, short of a few direct recruitments, few new members. To maintain the current workload performed by our working groups (TWG, EWG) and the ontology review processes, we need new recruits, in particular, in the early career stages, to manage day to day activities such as improving metadata, website issues and outreach activities. I believe that opening up the meetings could provide a low-barrier entry for people that just want to see "what we are up to", rather than committing, from the onset, to all the duties assigned to full OBO Ops Members. The idea is that they listen, learn, spread the word, and, eventually, volunteer to help with our day to day business.
2. **_Transparancy_**. As an _Open Science_ organisation, we make a lot of important decisions during our calls, and many of our decisions are never documented publicly (as part of issues on GitHub etc), but simply recorded in the minutes. Arguments for and against admitting certain ontologies are not the only important examples - others include new member admissions, details about SOPs and metadata policies. While we try to make the decisions themselves public (not even that very well I think), we almost never publish the decision making process. I believe that an Open Science organisation, committed to openness, should be entirely transparent about all the decisions they do, and any community member should be able to obtain some understanding of what is being discussed.

## Implementation

- As past meetings were held under the assumption of confidentiality, I do not advocate to publish past meeting minutes. I would simply suggest to start a new agenda (we are overdue a new doc anyways), making it readable to the public and sharing it on the website.
- Obviously allowing community members to join meetings my induce communication overhead. I am open to implement a rule that prevents non-OBO Ops members to talk during a meeting (they can use the chat).
- Only OBO Ops members are allowed to vote on OBO Ops decisions.

## Concerns

- Members at the last call suggest that our meetings are already not exactly the most efficient, and adding more people could make it worse. I agree, therefore I would suggest to implement the above rule that prevents non-Members from speaking.

**Comment by mellybelly** [comment]
I concur with this approach to inclusivity and transparency and it is a terrific precursor for planning OBO non-profit status. This will encourage necessary non-profit bylaws to be discussed and developed, wherein it is indicated how operations committee (e.g. board / exec) members are voted in, and other voting procedures that will be required. To the community -please come to the upcoming town hall to relate your ideas.

**Comment by cmungall** [comment]
Fully in favor

**Comment by matentzn** [comment]
@pbuttigieg lists the risk of zoombombing

**Comment by cthoyt** [comment]
Allow people to ask for invite link via OBO Foundry slack then?

Password protect then make the password available via slack?

**Comment by nataled** [comment]
Notes from Ops meeting 2022-09-06:

Nomi suggests that minutes could be published on github, affording the opportunity to redact.

Pier suggests we can use obo-discuss as the gatekeeper. James affirms that obo-discuss is vetted.
Pier also points out that things like an operations committee are - by definition - exclusive. We can be inclusive in terms of acquiring more members. If we want to do outreach, that's a separate thing. Bjoern concurs.

Björn points out the need to have some sort of privacy to discuss operational matters. Minutes etc can be open if we want transparency.

Darren points out that these meetings were held under the assumption of privacy, so regardless of future openness, changes shouldn't be retroactive. Several members concurred.

Bjoern mentions that we'll have to be diplomatic in our meeting minutes (at least).

Shawn points out that having a new ontology developer on calls could help Ops to have a direct understanding. Chris M concurs. Pier indicates that the committee needs to be able to deliberate internally before contact. It would be quite slow and inefficient to simultaneously deliberate and communicate to the submitter. We can separate the proceedings of a committee with communicating its decisions / positions to third parties.


Lynn raises the question of voting. Nico (and previous discussion) indicate that non-members would not vote.

**Comment by matentzn** [comment]
- @pbuttigieg argues that some pre-competitive information could not be shared in private.
   - @cmungall says that empirically speaking, we have not really shared such confidential information. 
- @bpeters42 Clear and open language may have to be muddled in politeness which hampers productive discussions
- @handemcginty also agrees that partial opening up seems better and trialling "openness" rather than all-out yes or no.
- @matentzn still believes that openness trumps the concerns of the rare cases where pre-competitive issues are shared. Plain language can be used to convey criticism in a more dispassionate fashion. Will a bit sceptically think about a more periodic openness as a compromise.

**Comment by matentzn** [comment]
## Vote 1: Opening up meeting minutes to the public

Suggestion: we create a new Google Doc starting from zero and give read access to the public. This increases transparency of the Operations and decision processes moving forward.

- 👍 : Yes, I am in favour of opening up _a new set of meeting minutes_ to the public.
- 👎 : No, I am against opening up meeting minutes to the general public at this stage.

**Comment by matentzn** [comment]
From January 10, we are switching to public meeting minutes.

**Comment by cthoyt** [comment]
In addition to just having this motion, it would be nice if there were a paragraph of somewhere in the SOPs that explains explicitly that meeting minutes are open and what the reasoning is behind this (e.g., transparency)

**Comment by matentzn** [comment]
You are right @cthoyt 

- [ ] Add paragraph SOP.md explaining that meeting minutes must be open, and why.

**Comment by nlharris** [comment]
I can work on that -- should I just create a new section at the end of https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/SOP.md?

**Comment by cthoyt** [comment]
Apparently, choosing the SOPs as a place to codify the reasoning for making meetings open got shot down, where else can this go?

**Comment by nlharris** [comment]
How about in the new newsletter? OBO Foundry Newsletter Q1 2023 #2272

**Comment by cthoyt** [comment]
no, this is not enough. A newsletter seems ephemera. This explanation MUST be front and center, available as high importance documentation on the OBO Foundry Site, for example, as a new page in the OBO Operations Committee called "Openness and Accountability Policy"

**Comment by matentzn** [comment]
I totally agree with @cthoyt here, I dont understand how this got "shot down". Maybe it just does not fit in the SOP section that well. Can we find a new place for documenting this?

What about

https://obofoundry.org/docs/OperationsCommittee.html

That is a top level page which seems to contain relevant content. I think a paragraph here would be visible and clear.

**Comment by matentzn** [comment]
Or actually yes, sorry, the `Openness and Accountability Policy` suggestion is actually better. Didnt read this clearly.

**Comment by nataled** [comment]
> I dont understand how this got "shot down". Maybe it just does not fit in the SOP section that well. Can we find a new place for documenting this?

This is precisely correct. In general, SOPs are for the Ps, presented without the reasons behind them. Indeed, the 'flavor' of the existing OBO SOPs was taken into account when asking why this SOP should differ. The closest any other SOP comes to providing background reasoning is when it's stated 'For discussion on this SOP, see <link>'. In this case, the above Policy document would serve as that link.

**Comment by cmungall** [comment]
It seems we are agreed we should add a section *Openness and Accountability Policy* https://obofoundry.org/docs/OperationsCommittee.html with the relevant text.

I suggest:

_The OBO Ops commitee is committed to openness and accountability. In this spirit, we make the meeting notes from OBO operation calls public (https://docs.google.com/document/d/1qhLFQL5IzTMUIBOtxJ5AqaEHcOCOQgNeXfvAb5O5P0A/edit). In addition, we strive to record decisions and action items as issues on the public OBO github tracker as far as possible_

This issue has been open for a year and a half. It would be great if we could be more agile with things like this. None of this should be controversial for an organization with "Open" in its title. Maybe SOP.md wasn't the perfect place but can we can do things incrementally here, it would be great if those shooting down proposals could proactively provide alternatives.

**Comment by nlharris** [comment]
Should I go ahead and add that as a PR?
