### ISSUE TITLE
minor layout issue on the new website

### ISSUE THREAD

**Issue by egonw** [OBOFoundry/OBOFoundry.github.io#2054]
When looking at https://obofoundry.org/ontology/cheminf.html# I notice the URL overflow the boundaries of the right hand side box into the margin:

![image](https://user-images.githubusercontent.com/26721/186976534-116cbb97-c620-4c8d-a6a4-d5e0113a5304.png)

This can be solved by wrapping (`word-break`ing the URLs).

**Comment by egonw** [comment]
@larsgw and I had a look, but the bootstrap version is really old, and it may not be easy to fix.

**Comment by cthoyt** [comment]
i have already started testing upgrading to Bootstrap 5, since there are several things that are hard to address as is

**Comment by cthoyt** [comment]
Should be closed by https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2057
