### ISSUE TITLE
Request OBO Foundry namespace: OMIABIS

### ISSUE THREAD

**Issue by mbrochhausen** [OBOFoundry/OBOFoundry.github.io#206]
requested prefix: OMIABIS
ontology title: Ontologized MIABIS
ontology download link: https://raw.githubusercontent.com/OMIABIS/omiabis-dev/master/BFO2%20omiabis/omiabis_merged.owl
ontology home page: https://github.com/OMIABIS/omiabis-dev
point person contact email: mbrochhausen@gmail.com
ontology issue tracker link: https://github.com/OMIABIS/omiabis-dev/issues
purl.org user ID - please register there if you don't have one: mbrochhausen

**Comment by jamesaoverton** [comment]
The OMIABIS namespace was registered on the OCLC PURL server in 2012. The ontology is listed on Ontobee, and has been discussed several times on the obo-discuss mailing list. By some sort of omission, it was never added to the OBO registry.

In this case, I think there's good reason to skip the usual two-week comment period on new ontologies, and add OMIABIS to the OBO registry immediately. Are there any objections?
