### ISSUE TITLE
Clarify UBERON funding sources

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2071]
UBERON lists the following free-text entries for its funding

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/94cfb4b920b490bd11ed353fd4306c284c09251a/ontology/uberon.md?plain=1#L45-L49

It's pretty non-obvious how to resolve these strings into something useful. Starting by googling `NSF DEB-0956049`, I found @keilbeck's page http://eilbeck-lab.genetics.utah.edu/?p=167 that also mentioned @mellybelly. With some more investigating, I figured out that the `DEB-` prefix was not informative

And ultimately I found that this number corresponds to the NSF awards namespace of https://www.nsf.gov/awardsearch/showAward?AWD_ID=0956049 (now in the Bioregistry at https://bioregistry.io/nsf.award, example resolution with https://bioregistry.io/nsf.award:0956049). can you confirm that's correct?

Is there also a proper NIH page to resolve the other funding numbers? Maybe:

- https://taggs.hhs.gov/Detail/AwardDetail?arg_AwardNum=R24OD011883&arg_ProgOfficeCode=205
- https://taggs.hhs.gov/Detail/AwardDetail?arg_AwardNum=P41HG002273&arg_ProgOfficeCode=55

note that these have different program office codes, meaning that these aren't really extensible.

**Comment by nlharris** [comment]
> Is there also a proper NIH page to resolve the other funding numbers? 

Not sure what you mean by "resolve". The NIH funding numbers are correct and unique. You want the NIH funding numbers to point to web pages? I'm also not sure what you mean here by "extensible".

**Comment by cthoyt** [comment]
By resolve, I mean there is a URI format string we can use to turn an NIH funding number into a URL that points to a web page (in the Bioregistry / OBO PURL system sense of the word)

The issue is people can write these funding numbers but it's almost impossible to learn anything about the project that these numbers correspond to. Google is pretty useless other than finding additional papers that have the number, because they're pretty unique across the web. So if we can figure out some secret website that lets us get information by constructing a URl from the funding number then that would be great. 

One thing already in the Bioregistry is for the NSF awards: https://bioregistry.io/registry/nsf.award

**Comment by keilbeck** [comment]
The NSF grant referred to was an NSF research coordination grant from 2013. https://www.nsf.gov/awardsearch/showAward?AWD_ID=0956049

**Comment by cthoyt** [comment]
Good, that's what we had already figured out. It actually occurred to me that the first few characters of the NIH grants might correspond to grant type, and I was able to realize that this site can resolve them if you put the appropriate dashes in: https://grantome.com/grant/NIH/R01-HG004838

**Comment by nlharris** [comment]
Great, so do you now have what you need, @cthoyt?

**Comment by nlharris** [comment]
I discovered that https://grantome.com/grant/NIH/HG004838 also works (resolves to https://grantome.com/grant/NIH/R01-HG004838-03S1) -- might that be a simpler formula?
