### ISSUE TITLE
Deselecting only "Hide Obsolete" doesn't show obsolete ontologies

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2078]
The new obofoundry.org ontology table is super-awesome and I love it. I just wanted to report a minor issue I observed with the "Hide Obsolete" button. A good test case is choosing "environment" as the domain; it has one inactive and one obsolete ontology.

By default, both inactive and obsolete ontologies are hidden. If you uncheck "Hide Obsolete", the obsolete ontology does not appear (first screenshot). If, however, you uncheck "Hide Inactive", the inactive ontology appears; if you also have Hide Obsolete unchecked, the obsolete one appears as well (second screenshot).

So "Hide Inactive" appears to be working correctly but "Hide Obsolete" doesn't...unless (this just occurred to me) you consider ALL obsolete ontologies to also be inactive. Maybe that is in fact the case, but the behavior is non-obvious (to me, anyway).

<img width="1079" alt="Screen Shot 2022-09-01 at 2 09 52 PM" src="https://user-images.githubusercontent.com/348704/188014138-c1c40a03-05e4-4188-b1d1-5b1b12b35755.png">

<img width="1063" alt="Screen Shot 2022-09-01 at 2 10 01 PM" src="https://user-images.githubusercontent.com/348704/188014153-83b364b5-3af8-45db-a9fd-f4e4a709b9dd.png">

**Comment by matentzn** [comment]
All obsolete ontologies are indeed inactive. It seems like there is no real case for having hide obsolete Switched off and hide inactive checked. There is a case for the converse though. Any idea how to improve this?

**Comment by nlharris** [comment]
Would it be hard to make "hide inactive" acquire a checkbox when you check "hide obsolete"?

**Comment by nlharris** [comment]
Or did we decide this isn't a logically valid thing to do?
