### ISSUE TITLE
ontology purl for MFO and DINTO

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#208]
We have two remaining ontologies for OLS where the ontology_purl in the YAML file doesn't resolve to an OWL file. 

http://purl.obolibrary.org/obo/mfo.owl
http://purl.obolibrary.org/obo/dinto.owl

Is it possible to get the redirect working?

**Comment by cmungall** [comment]
* mfo has been obsoleted
 * follow up with DINTO here: https://github.com/labda/DINTO/issues/1

**Comment by nlharris** [comment]
Seems like DINTO is also obsolete?

**Comment by cmungall** [comment]
It's been over 4 years, still no owl file, mark as obsolete

**Comment by nlharris** [comment]
What about MFO?

**Comment by cmungall** [comment]
mfo is already marked obsolete

**Comment by nlharris** [comment]
righto. i should have checked.
