### ISSUE TITLE
Principle #5 "Scope" - 

### ISSUE THREAD

**Issue by pbuttigieg** [OBOFoundry/OBOFoundry.github.io#2083]
Also relevant to Principle 16 "Maintenance"

Partially a consequence of https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2002 and derived from https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2002#issuecomment-1229430372

As discussed in todays Operations Committee call, there is a concern that we're losing modularity in OBO's holdings. If more narrowly focused ontologies subsume content that is generically useful, there's a risk it can become less generic and lead to proliferation/duplication.

Solutions proposed:
* Have more, and more modular, ontologies co-maintained by those interested in importing them: requires measures to reduce the editorial / technical overhead of maintaining more ontologies
* Allow generically useful modules to be maintained within larger, more narrowly scoped ontologies, *but* have a clear commitment to keep them generically useful by maintaining domain-neutral definitions, axiomatisation, etc

These issues are persistent, and having some sort of clearly stated sub-principle or note on Principles 5 and 16 would improve long-term evolution.

**Comment by matentzn** [comment]
I fully support this proposal.

**Comment by nataled** [comment]
Points from EWG discussion:

1) The first proposed solution falls outside the purview of this principle. However, the second solution can be addressed. P16 "maintenance" is not at all appropriate for either.

2) There was some uncertainty regarding the intended meaning of 'module'. On one hand it could be a set of related terms (such as a branch) that's part of the 'main' ontology. Alternatively it could mean a separate file that gets imported into the main ontology (or into another ontology that might need it). We have chosen the latter interpretation. However, it is also possible that both apply. That is, if there are two or more related sets of terms, they should each be in a separate importable file. Given the abilities of ROBOT and OntoFox, there are no technical impediments to any of these. However, which interpretation is intended will affect the wording, so please clarify (this might need further OFOC discussion).

3) We believe that sufficiently generic terms should go to COB, as appropriate, and would like to include wording to this effect.

cc: @cstoeckert @handemcginty (please add anything I missed)

**Comment by nataled** [comment]
Notes from OFOC meeting:
1) 'Module' should be interpreted more in line with the idea of 'branch' or 'set of terms' (with a set of one being acceptable for the purposes of the wording), but doesn't preclude the technical approach of a separate file (which doesn't need to be mentioned).
2) Accepted that wording should be included to the effect of encouraging COB submission for sufficiently generic terms.

**Comment by nataled** [comment]
Revised as per https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2164
