### ISSUE TITLE
Add link to SOP

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2084]
- [x] Link to [SOP](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/SOP.md) from some menu

- [x] Replace “instructions to chairs” in the meeting notes doc with a link to the SOP (so we don’t have to do updates in two places)

**Comment by nlharris** [comment]
I have a concern about info that is exposed in the SOP; I wrote a message in Slack about it.

**Comment by matentzn** [comment]
This link should be closed to the public! Isn't it?

**Comment by nlharris** [comment]
It was not closed until @balhoff made it so a few hours ago.

**Comment by nlharris** [comment]
Regarding the second thing ("Replace “instructions to chairs” in the meeting notes doc with a link to the SOP (so we don’t have to do updates in two places)"), what I'd like to do is create a fresh obo ops meeting doc that can be shared publicly and make this change in that new doc. I would then change the OBO Ops calendar event to point to the new doc. (Normally I would prefer to keep the URL of the meeting notes doc unchanged and move out the old notes to a new doc, but in this case, that would enable the general public to see the removed notes via doc history.)

Are we ready for this? @matentzn @bpeters42 @cmungall

**Comment by matentzn** [comment]
Yes, the current minutes have been overflowing anyways. New minutes I think is fine.

**Comment by nlharris** [comment]
Chris wants it to be in a new drive, and we decided not to do that yet. I did move the 2021 minutes into a new doc, and left the 2022 minutes in the current doc for now.
