### ISSUE TITLE
Ontologies without domain not displayed on homepage

### ISSUE THREAD

**Issue by allenbaron** [OBOFoundry/OBOFoundry.github.io#2107]
https://obofoundry.org/ does not display ontologies without domains even when all checkboxes are unchecked.
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/21225409/192851217-6e6b45ab-d6eb-4c0f-ab96-cfdeacf29ddd.png">

Examples of missing ontologies by prefix: aao, fix, gaz

**Comment by nlharris** [comment]
Hey @allenbaron thanks for reporting this (and thanks for giving specific examples of the issue -- always helpful!).

**Comment by erik-whiting** [comment]
Gave this one a try: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2114

**Comment by cthoyt** [comment]
Alternate solution to making a programmatic solution: require _all_ ontologies are annotated with a domain, do the annotation, and add a unit test.

**Comment by cthoyt** [comment]
All ontologies are required to have domains as of #2115, so this can be closed.
