### ISSUE TITLE
P20: Responsiveness: Remove mailing list requirement

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2118]
https://obofoundry.org/principles/fp-020-responsiveness.html

Says that mailing lists are required. I think this is both unrealistic and overkill - most communication about an ontology should happen on the issue tracker.

**Comment by cthoyt** [comment]
All of the discussion about issue trackers on this page should also be updated to say **public** issue tracker

**Comment by matentzn** [comment]
100% agreed.

**Comment by nataled** [comment]
I'm pretty sure the 'public' part is non-controversial, as that is how the tracker is understood to be. The mailing list part will need discussion within the Ops committee, as that requirement precedes the use of trackers on a wide scale in the Foundry, and was part of the original principle. Here I should note that, even though it looks 'new', P20 actually arises from a principle that previously merged two major ideas--one of those became (I think) P16, and the other P20. It just took longer to get P20 in shape (we have the same situation with P5 and the principle that would cover 'orthogonality', though the latter seems abandoned).

**Comment by nataled** [comment]
Discussed requirement for a mailing list used for the purpose of ontology discussion. This role has largely been supplanted by issue trackers. Vote: all who expressed an opinion were in favor of removing the requirement, demoting to the level of “it would be nice to use but not necessary to have”.

**Comment by nataled** [comment]
PR:  https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2187
