### ISSUE TITLE
Add GitHub handles to new OBO Metadata Pages

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2125]
@cthoyt gifted a great new overview page for OBO Ops members https://obofoundry.org/docs/Membership.html

I find myself looking for Ops GitHub handles all the time, and I would like to propose to add them to 

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml

I tagged this as good first issue, please do _not do this_ if your name is Charlie or you have completed more than 2 issues on this repo here in your life!

**Comment by cthoyt** [comment]
I already did this just didn't commit it yet :p

**Comment by matentzn** [comment]
... 😂 ok then. As a punishment for helping too much maybe help find another simple issue someone else could pick up... hahaha
