### ISSUE TITLE
Add remaining ORCID identifiers for Alumni

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2134]
The following three alumni of the OBO Operations committee are missing the ORCID identifiers in https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/alumni.yml. It would be great to add them!

- Eric Douglass (https://orcid.org/0000-0001-6946-1807, thanks @balhoff for finding this)
- Gareth Owen (https://orcid.org/0000-0001-7265-5776, thanks @balhoff for finding this)
- Carlo Tornial (https://orcid.org/0000-0002-3734-1859, thanks @wdduncan for finding this)

## ~Step 1: Internet Sleuthing and Reaching Out~ Done!

It's an internet detective mission to figure out who people are, especially if you haven't been an insider for the last 10+ years. The job here is to figure out who these people are by searching around google scholar, ORCID, by asking people who have been around for a long time to get email addresses, etc. (usually the best way is to [join the OBO Foundry slack workspace](https://join.slack.com/t/obo-communitygroup/shared_invite/zt-1ghuih22a-Sxo4bpSd167ik~q8UB9MFw), and ask someone like Chris Mungall via DM)

If these people don't have ORCIDs, then it would be good to ask them directly to make one.

**Comment by wdduncan** [comment]
I sent an email to Carlo asking for his ORCID and/or github handle.

**Comment by wdduncan** [comment]
Carlo's GH handle is @carlotorniai. He will let us know about the his ORCID.

**Comment by cthoyt** [comment]
Additionally, I think Eric Douglass is @dougli1sqrd.

**Comment by wdduncan** [comment]
Carlo's ORCID is https://orcid.org/0000-0002-3734-1859

**Comment by balhoff** [comment]
@cthoyt here's some info for Eric Douglass: https://github.com/geneontology/go-site/blob/3dbba4e8470200a6911c31165757433ac02ea451/metadata/users.yaml#L3516-L3526

**Comment by balhoff** [comment]
This looks like the right Gareth Owen: https://orcid.org/0000-0001-7265-5776

**Comment by balhoff** [comment]
A user @G-Owen commented in the ChEBI tracker: https://github.com/ebi-chebi/ChEBI/issues/3604

:-)
