### ISSUE TITLE
What to do about non-resolvable versionIRIs

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#214]
Some ontologies have unresolvable PURLs, e.g. CHEBI

See
https://github.com/ebi-chebi/ChEBI/issues/3135

as an aside, CHEBI uses a non OBO id-policy non ISO-8601 versionIRI - don't think this really matters so long as it resolves, but should be noted somewhere 

cc @mcourtot 

We can assist some groups to some extent (though providing the storage for large ontologies may be an issue), but should we have some flag?

Note also that chebi is foundry, and we have a policy http://obofoundry.org/principles/fp-004-versioning.html --- but chebi is not contravening this as written (no requirement to access previous versions)

**Comment by alanruttenberg** [comment]
We should consider taking on the task of preserving old versions as a foundry activity. Over the long term it may be difficult for individual ontologies to keep this up. Regarding the versionIRI, we should contact them and ask them to comply. They could be offered that another property could be used for their idea of version so as not to lose it.

**Comment by cmungall** [comment]
What are the negative impacts of an ontology using a non-date versionIRI scheme? If the versionIRIs satisfy more minimal MUST requirements (for example, extending their base IRI) is there any harm done if they use, say, semantic versioning, or a scheme like CHEBIs.

I like uniformity, particulary with ontologies I support as I can use more uniform tooling with less ontology-specific configuration. But this points to a SHOULD rather than MUST

**Comment by alanruttenberg** [comment]
It's documented as our standard. Uniformity in things like this improve predictability. What is the advantage of not following a standard convention?

**Comment by cmungall** [comment]
The CHEBI case. their versioning predated our scheme. Is it worth the churn to push for a change.

**Comment by alanruttenberg** [comment]
VersionIRI is a semweb thing, and OWL2 specifically, so it is hard to imagine it predates that much, if at all. 

IMO yes. It's not like they can't record that version information outside the version IRI.

**Comment by nlharris** [comment]
Is there still something here that needs to be addressed?

**Comment by nlharris** [comment]
can we close this?

**Comment by balhoff** [comment]
This works for CHEBI since last year. The overall question is too broad to keep open in this issue, I think. Many ontologies have resolvable version IRIs.

**Comment by nlharris** [comment]
Ok, so can we close this ticket?

**Comment by matentzn** [comment]
I will close this ticket with the comment that the general issue of a version registry is not resolved, and way beyond our resources, but we can come back to this issue when we have some money.
