### ISSUE TITLE
Text at the top of https://github.com/OBOFoundry has typo, needs improvement

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2158]
The text at the top of https://github.com/OBOFoundry says
"The OBO Foundry consists of developers of science-based ontologies creating of principles for ontology development in the biomedical domain"

At the very least, we should remove the "of" from "creating of principles", but overall it seems like that description could be improved.

I can't find where to edit it.

- [x] fix typo (extra "of")
- [ ] improve description

**Comment by nlharris** [comment]
Looks like I don't have enough privileges in the OBOFoundry org to see or edit that text.
<img width="795" alt="Screen Shot 2022-10-19 at 5 44 04 PM" src="https://user-images.githubusercontent.com/348704/196830490-bcf0f98a-ee95-42f8-9c7e-389a1d70f580.png">

**Comment by jamesaoverton** [comment]
Yeah, changing that description of the organization seems to require Owner permissions, which can be use to do dangerous things.

**Comment by nlharris** [comment]
Ok, thanks. How about "The Open Biological and Biomedical Ontology (OBO) Foundry is a nexus for community development of interoperable ontologies for the biological sciences"? (adapted from the text on obofoundry.org; open to other words besides "nexus" but I wanted to avoid any word that implied that we support such development, either financially or with person-time, even though in fact we do do a lot of the latter)

**Comment by nlharris** [comment]
@jamesaoverton 👆

**Comment by jamesaoverton** [comment]
Ok, done.
