### ISSUE TITLE
MFOMD purl cycle 

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#216]
http://purl.obolibrary.org/obo/mfomd.owl redirects to http://mental-functioning-ontology.googlecode.com/svn/trunk/ontology/MD.owl which then imports http://purl.obolibrary.org/obo/mfomd.owl

**Comment by cmungall** [comment]
invited @jannahastings

**Comment by jannahastings** [comment]
yes - @cmungall  how do I change / fix the PURL redirects? I used to go to purl.obolibrary.org and log in there but now I get redirected to a GitHub page?

**Comment by cmungall** [comment]
Need to add docs for this - for now the docs are in the README here https://github.com/OBOFoundry/purl.obolibrary.org/

It looks like there is no stub entry here:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/

You could start by editing this one, which is yours, and is pointing to googlecode:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/mfoem.yml

**Comment by cmungall** [comment]
remember and set your licenses in the main entry here too, see #34

**Comment by jannahastings** [comment]
ok thanks! will fix problem and update

**Comment by jannahastings** [comment]
I have created a YML file for MFOMD and fixed the redirects in MF and MFOEM (each in separate pull requests)

For the license, that is not something that should be added in the YML, right, but in the respective OWL files (with dc:license)?

**Comment by cmungall** [comment]
Can you add it to the yaml?

We have a process that checks it is synchronized with the ontology, but 
many ontologies don't or can't do this, yaml is easiest as anyone can do 
a PR

**Comment by nlharris** [comment]
is this still relevant? it was last commented on in 2016.

**Comment by jannahastings** [comment]
I believe this issue has been solved?

**Comment by balhoff** [comment]
The cycle issue is fixed.
