### ISSUE TITLE
CSS Issues after Bootstrap 5 migration

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2166]
- [x] links are all blue, bold and underlined - this looks a bit ugly
- [x] ordered and unordered lists should be indented a bit deeper under the headline
- [x] ids in table should not be bold/underlined and should probably be black?

cc @erik-whiting 

<img width="828" alt="image" src="https://user-images.githubusercontent.com/7070631/198368896-98b072ff-faaf-401c-8105-c5805245937b.png">

**Comment by matentzn** [comment]
@erik-whiting can you send me an email? I wanted to send you a few invites and questions :)

**Comment by erik-whiting** [comment]
@matentzn how do I find your email address?

**Comment by erik-whiting** [comment]
also, what do you want the links to look like (besides not blue, bold, and underlined)?

**Comment by matentzn** [comment]
I don't really know what's best here in terms of CSS.. Something more.. Modern? I only know that blue underlined Bold looks 90ies :) maybe black and not underlined? I don't know. Maybe you have better ideas?

**Comment by cthoyt** [comment]
@matentzn I totally get some of these stylistic concerns, but I see a lot of value in just using the default Bootstrap styles. This means we don't have to add in tons of custom styles, which create massive overhead in understanding and later maintaining the site (trust me, figuring out the existing site was a huge headache).

**Comment by erik-whiting** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2168

**Comment by matentzn** [comment]
@cthoyt normally I would agree with you on these kinds of issues, but even for me, a person with very little aesthetics, these issues noted here are too ugly - be they standard or not.. I think a little bit of CSS customizability is justifiable in this case.. I am very surprised the default bootstrap styles are so... old.. :P

**Comment by jamesaoverton** [comment]
In general, I agree with @cthoyt that we should save ourselves time and effort, and learn to live with the Bootstrap defaults. The one that kills me is the underlined links. Bootstrap 4 did not underline links, but they changed that in Bootstrap 5 (according to <https://stackoverflow.com/q/65480036>), and it looks so awful to me. So I guess I'm a hypocrite.

**Comment by matentzn** [comment]
@erik-whiting and @cthoyt thank you for your great minimal solution to this issue!
