### ISSUE TITLE
Reduce redundant text in OBO ops landing and mission statment page

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2167]
The text on the following two pages is almost the same:

1. OBO Ops landing page: https://obofoundry.org/docs/OperationsCommittee.html
2. OBO Ops mission statement: https://obofoundry.org/docs/MissionStatement.html

I suggest taking the text out of the mission statement page and putting it on the landing page, then deleting the dedicated mission statement page. This would make the burden of reading through the site on the reader much smaller.

**Comment by nlharris** [comment]
That sounds good to me! Should I do that (and the associated cleanup of menus or whatever is needed)?

**Comment by cthoyt** [comment]
I would have just done it directly but I’ve got so much Luke warm feedback from that way of approaching things I figured I better just ask first. If you want to do it then great

**Comment by cthoyt** [comment]
Tbh most of the pages about the ops committee are redundant so maybe you could even go further to collapse them together

**Comment by nlharris** [comment]
Discussion from PR #2178:

@cthoyt: While you're compressing things, can you also just combine the Mailing List (https://obofoundry.org/docs/MailingLists.html) into the main page?
Main reason is the OBO Site is currently too big and disorganized to maintain. I am trying to fix this!

@nlharris: How about instead if I merge https://obofoundry.org/docs/CommitteeMeetings.html, https://obofoundry.org/docs/OBOCalendar.html, and https://obofoundry.org/docs/MailingLists.html into one page? (Not sure what to call it -- OBO Operations Operations??)
I understand the desire to tighten things up, but adding lots of details (such as mailing lists) to the main page doesn't necessarily make it easier for people to navigate.

@cthoyt: Sure that’s fine, call it logistics or something like that
