### ISSUE TITLE
Add new members to OBO Operations Registry and upload photos

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2229]
TWG new members, to finalise onboarding please update the OBO Ops registry (different then roles!) and add photos, see below.

- [x] @anitacaron 
- [x] @rays22
- [x] @erik-whiting
- [x] @deepakunni3 
- [x] @pfabry 

- Registry: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml
- Photos: https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/images/ofoc

All photos must have the same dimensions (check which by look at example, but I think 220*280)

**Comment by rays22** [comment]
> * Should I assign the pull request to Ray? (provided i can assign a PR :) )

@pfabry , feel free to assign me as the reviewer of your PR.

**Comment by pfabry** [comment]
Sorry, disregard my comment, I just found out my university ror and wikidata...

**Comment by rays22** [comment]
> * Registry: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml

Hi @erik-whiting , 
I see that you have already added your photo. 
I am wondering if you wanted to add your details to the [operations.yml](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml) registry too for this ticket?

**Comment by erik-whiting** [comment]
> > * Registry: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml
> 
> Hi @erik-whiting , I see that you have already added your photo. I am wondering if you wanted to add your details to the [operations.yml](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml) registry too for this ticket?

good catch, will update soon
