### ISSUE TITLE
legacy wiki pages should redirect

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#223]
See #222 

E.g. http://wiki.obofoundry.org/wiki/index.php/FP_001_open

Should redirect for now. Also, can't guarantee permanence of the legacy wiki, so might be good to alert community (adding outreach label)

**Comment by nlharris** [comment]
The example legacy URL doesn't redirect, so it seems like maybe this never got done, but is it still relevant?

**Comment by nlharris** [comment]
Where would one could across these legacy URLs, anyway?

**Comment by nlharris** [comment]
I think this is covered by #1267; closing.
