### ISSUE TITLE
Add "how to cite an ontology" info page

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#224]
Discussed on operations meeting 2016.02.23

We agreed to add a new page with a citation policy and examples of how to cite some of our ontologies.

we can utilize the new data citation extension to JATS, see [https://peerj.com/articles/cs-1/]
for more info. Essentially this allows the citation of any identifier (so long as it meets standards as defined in the article) outside the paywall of the journal. This should probably be the version IRI but we should describe an example of what this should look like in a journal.

This can build on the text in the Open principle.

**Comment by jamesaoverton** [comment]
Added citation policy document with commit 49a80935282275559c94c4b8fef01f61678c04ab
