### ISSUE TITLE
Document update NOR dashboard automatic workflow better

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2243]
There is a GitHub action that automatically rebuilds all the metadata required for the functioning of the site.

Example https://github.com/OBOFoundry/obo-nor.github.io/pull/21/files

- [x] Make sure the github action that does this assigns @pfabry, not me
- [x] Document in the NOR manager SOP the following:

```
- When dashboard config is updated, and every Monday morning, the OBO NOR Dashboard is regenerated using [this](provide a link) GitHub action. The OBO NOR Manager should sanity check the diff for any oddities, in particular changes to the file `dashboard/dashboard-results.yml`.  This PR should always be reviewed by the NOR Manager and not be automatically merged into the main branch as part of the GitHub action.
```

**Comment by pfabry** [comment]
Just to be sure, I understand I must change the following [workflow](https://github.com/OBOFoundry/obo-nor.github.io/actions/runs/3676148304/workflow) and replace your github ID on the last line. However, I think I don't have write access on the NOR repo. Could that be a problem for the update action ?

**Comment by matentzn** [comment]
I gave everyone access to that repo now - was an oversight.

**Comment by pfabry** [comment]
cf. #2248

In addition, do we still want to ask new ontology requesstors to join the obo-discuss mailing list vs keeping all communications in the issue or using slack ?

**Comment by matentzn** [comment]
Great catch @pfabry, see https://obofoundry.org/faq/how-do-i-register-my-ontology.html, they absolutely have to announce their submission on obo-discuss as well. Can you add this to your duties:

- ensure that requestor has joined and send an appropriate email to the obo-discuss mailing list, see https://obofoundry.org/faq/how-do-i-register-my-ontology.html. If they have not, point them to the instructions and ask them to do so.

Slack: I think you can add this to your list:

- Invite the contact person (using the email listed in the metadata) to the OBO Foundry slack space

**Comment by pfabry** [comment]
cf. new commit on #2248

**Comment by pfabry** [comment]
#2248 has been merged.
