### ISSUE TITLE
Consider requiring release files to be in RDF/XML or RDF/Turtle formats (FP 002 Format)

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#226]
@cmungall says: We should probably recommend the release versions of OWL only use RDF/XML or RDF/turtle as that is consumable by a much wider range of tooling (I love some manchester internally). We should also have a policy on OWL/Zip when available. But all this can come later.

**Comment by alanruttenberg** [comment]
Consider releasing in multiple formats. Of the OWL syntaxes, functional syntax seems most amenable to scripted read/write for those not using OWLAPI and we considered using it as repo format to see whether diffs work better. If we do add this we want to avoid giving the impression they need to have the edit version be RDF/XML.

Regarding zip, I would suggest not. Fewer yet tools automatically unpack zip files. For transmission there is compression over the wire with the right apache settings. We can check if github does it but I'd be surprised if not. As far as local disk space goes, the capacities are enormous now. The only benefit might be marginally faster parsing by doing less i/o, but I expect other parts of parsing would take long enough we wouldn't notice.

**Comment by alanruttenberg** [comment]
@cmungall I do agree on minimally requiring RDF/XML. I think this comment:

If you intend to use your ontology for semantic web applications, it should be in OWL. OWL is part of the W3C's Semantic Web technology stack, which includes RDF (RDF Concepts) and SPARQL.

Should be removed. It's not what the developer is going to use the ontology for, its the consumers of it that matter. At this point we should assume (and advertise) that all our work is available for semantic web applications.

**Comment by nlharris** [comment]
What's the status of this issue?

**Comment by jamesaoverton** [comment]
Current status: Principle 2 requires RDF/XML format, and that is enforced by the dashboard checks.
