### ISSUE TITLE
New FAQ on addressing dashboard issues

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#2263]
From OBOFoundry/OBOFoundry.github.io#2254

Add to https://obofoundry.org/faq/dashboard.html a question on where to find directions for addressing dashboard issues.

Could be called "Where can I find information describing each Dashboard check and how to rectify issues?"

Note that this needs to await closure of OBOFoundry/OBO-Dashboard#83

**Comment by erik-whiting** [comment]
Since [OBOFoundry/OBO-Dashboard#83](https://github.com/OBOFoundry/OBO-Dashboard/issues/83) has been merged, I'd like to knock this out.

Can you give me the copy for the answer to that question? Or would you prefer I come up with something and submit it for review?

**Comment by nataled** [comment]
In this case the copy should come from the Technical Working Group; the Editorial Working Group will review, and revise if necessary.

**Comment by erik-whiting** [comment]
Is the TWG working on this? This is currently assigned to me, but @nataled last comment makes it sound like it's in the TWG's court right now. I'd like to reassign this if the copy isn't ready yet.

**Comment by nataled** [comment]
@erik-whiting When I wrote 'the copy should come from the Technical Working Group' that was not meant to indicate someone _other than_ you (since I'm of the impression that you are part of that group). I just meant that it didn't need to be you, or that it didn't need to be _only_ you. My guess is that there is a lot to cover in the FAQ answer. So, if you have the ability to do it, go for it, but if not, you should seek additional input from the TWG. Sorry for any confusion I caused!

**Comment by erik-whiting** [comment]
Oops, my bad, I forgot I was part of the TWG 😬

**Comment by nataled** [comment]
@erik-whiting any update on this?

**Comment by nataled** [comment]
@matentzn I think someone mentioned that Erik has moved on from the TWG. Is there someone you can recommend to provide the requested text?

**Comment by nlharris** [comment]
Here's some text as a starting point.

Q: Where can I find information describing each Dashboard check and how to rectify issues?
A: Please see https://dashboard.obofoundry.org/dashboard/about.html for general information about the Dashboard. To see information about what each Dashboard check is looking for, go to the Dashboard (https://dashboard.obofoundry.org/dashboard/index.html) and click a column header to learn more about that specific check. To see information about a specific ontology and any issues it had with the Dashboard checks, click the name of the ontology. A page will open showing more information about any checks that did not pass. If you see "See ROBOT Report for details", scroll down a bit for a link to the ROBOT report.

(I'm not sure what to say about "how to rectify issues". One of my questions, if I were an ontology owner, would be how to trigger a re-running of the Dashboard checks after I've tweaked my ontology to try to address the issues. How often is it automatically re-run?)

**Comment by nlharris** [comment]
I also suggest adding another question:

Q: What does it mean for an ontology to "pass" the Dashboard?
A: Each Dashboard check has four possible results: Pass - green check; Info - blue i; Warning - yellow exclamation point; Error - red x.

The last column of the Dashboard corresponds to the lowest result of all checks. For example, if there are any errors, this column will contain a red x. If there are any infos, but no errors or warnings, this column will contain a blue i.

To "pass" the Dashboard, this last column should be either green (everything passed) or blue (one or more checks returned info, but no warnings or errors).

[Is that correct? Yellow is not a pass, right?]

**Comment by nataled** [comment]
Thanks for the start, Nomi!

**Comment by matentzn** [comment]
cc @anitacaron

**Comment by anitacaron** [comment]
@nataled, I'm trying to run the 'regular' dashboard monthly by the end of the month. I'm running another release. I hope I can push it today.

**Comment by nataled** [comment]
@anitacaron thanks!

**Comment by pfabry** [comment]
> @pfabry how often is the NOR dashboard run? How about the 'regular' dashboard?

@nataled Generally, once a week for the NOR dashboard.

**Comment by nataled** [comment]
@pfabry thanks!
