### ISSUE TITLE
Autogenerate copyable citation

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#227]
We will have something like this on the Citation information page:
The order of authors is not important, though you can use the primary contact listed on the OBO site as the first author as a default. Here is an example citation:

Mungall, C., Haendel, M., Dahdul, W., Ibrahim, N., Segerdell, E., Blackburn, D., Comte, A., Niknejad, A., and Decechi, A. (2016), Uberon Ontology, http://purl.obolibrary.org/obo/uberon/releases/2016-01-26/uberon.owl

It would be great if we could autogenerate a copyable citation of this nature, that includes all the creators in the file, with the "owner" as the first author, and the latest version IRI. 

Even better might be to have a doi with a landing page for such citations, these could be generated as part of the release process and appended in the above citation format.

@cmungall @jamesaoverton ideas for how to implement?

**Comment by nlharris** [comment]
Is this done?
#220 seems to address most of this.
Ontology pages such as Uberon (http://www.obofoundry.org/ontology/uberon.html) have publications under "cite".
There's also a citation info page at http://www.obofoundry.org/docs/Citation.html
What else is needed?

**Comment by nlharris** [comment]
can this be closed?

**Comment by nlharris** [comment]
Closing; please open new issue(s) if needed
