### ISSUE TITLE
OBO Foundry Newsletter Q1 2023

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2272]
For now we can use this ticket to collect issues for the first great OBO Q1 newsletter!

### COB

- https://github.com/OBOFoundry/COB/pull/226
- https://github.com/OBOFoundry/COB/pull/225

**Comment by nlharris** [comment]
OBO Operations Committee meeting notes now publicly viewable: https://docs.google.com/document/d/1qhLFQL5IzTMUIBOtxJ5AqaEHcOCOQgNeXfvAb5O5P0A/edit

**Comment by nlharris** [comment]
Statement about why OBO Ops meetings are not open to the public (as requested by @cthoyt)

**Comment by cthoyt** [comment]
> Statement about why OBO Ops meetings are not open to the public (as requested by @cthoyt)

You mean "now" and not "not", right ;)

**Comment by nlharris** [comment]
Haha, no, I mean "not", but I realize the phrasing is confusing. I meant that you requested a statement, not that you requested the meetings not be open. 🤪

The meeting NOTES are open to the public. The meetings themselves are not.

**Comment by cthoyt** [comment]
Oops,  I misread this. I think both an explanation of:

1. Why meeting notes **must** be open to the public for OBO Operations Committee to be trustworthy and accountable
2. Why meetings themselves are not open

are both important. For now, I agree with both of these choices as they are a nice compromise.

**Comment by nlharris** [comment]
Yes. I meant that both of those should be included in the newsletter. Sorry to be unclear.

**Comment by matentzn** [comment]
Past newsletter
