### ISSUE TITLE
SOP for "activating" a new OBO Priniciple

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2273]
The act of "making the principle public" should be done more formally than just a PR IMO. Here is a basic suggestion

At least:

1. EWG creates a draft of the principle, involving the OFOC as needed 
1. Once the draft is finished, EWG sends an email to obo-discuss to invite comments (Email subject should be: "New OBO Principle: Request for Comments")
1. Present the finished wording to OFOC at least 3 weeks after the email to and obtain a unanimous vote to pass it
1. Have 2 or more OFOC members confirm the "make public" PR: is the to be published text exactly what was agreed?

@nataled what do you think?

**Comment by nataled** [comment]
I agree that we should replace the current process with something like what you suggest. I don't imagine there will be any push-back for this by the OFOC, but it will need to be discussed there since the current process was originally vetted by that committee. If adopted, the EWG can fill in any missing parts of the procedure described above.

@cstoeckert @hoganwr additional comments welcome.

Then the question becomes one of whether or not we delay this principle until the SOP is discussed.

**Comment by matentzn** [comment]
I think we should at least do 2 and 3. Adding new principles seems too much of a big deal know to do it in relative stealth..

**Comment by matentzn** [comment]
- [ ] Should result in a revision of https://obofoundry.org/docs/OperationsCommitteePolicyDecisions.html

**Comment by nataled** [comment]
Per discussion in OFOC meeting 2023-02-21:
Announce obo-discuss and Slack (general OBO channel), request feedback, and re-discuss in OBO-Ops meeting

**Comment by nataled** [comment]
@matentzn the EWG part of this is done (see http://obofoundry.org/docs/PrinciplesReviewWorkflow.html). Not sure how this fits into the Policy doc you refer to, as the scope of that is far broader than just principles. I note that the text of the SOP allows for a longer commenting period than the Policy doc.

**Comment by nataled** [comment]
@matentzn can this be closed? No update was made to the document [OperationsCommitteePolicyDecisions](https://obofoundry.org/docs/OperationsCommitteePolicyDecisions.html) as that document is higher level than principles creation/revision (covered in depth in [PrinciplesReviewWorkflow](http://obofoundry.org/docs/PrinciplesReviewWorkflow.html)). The latter document is visible from all documents on the 'About' menu except for the github links, where it is shown under the EWG heading. Other potential places to link from are the SOP, the doc you indicated, and the FAQ.

**Comment by matentzn** [comment]
@nataled I am happy if you are! Feel free to close, I have no further action items for this issue.
