### ISSUE TITLE
Request for new ontology BRYO

### ISSUE THREAD

**Issue by megbalk** [OBOFoundry/OBOFoundry.github.io#2275]
### Title

Bryozoan Attribute Ontology

### Short Description

An ontology for describing Bryozoa anatomy and traits.

### Description

The Bryozoan Attribute Ontology is to describe Lophophorata anatomy and traits. The ontology uses terms from UBERON, OBA, PATO, and BSPO to expand and build out the knowledge domain for Lophophorates. The goal is to ultimately put anatomical terms into UBERON and trait terms into OBA. The ontology will serve as an application ontology for ingesting presence/absence, qualities, and metric traits of individual specimens into knowledges base or data stores.

### Identifier Space

bryo

### License

CC0

### Domain

phenotype

### Source Code Repository

OBOFoundry.github.io

### Homepage

https://github.com/megbalk/bryo

### Issue Tracker

https://github.com/megbalk/bryo/issues

### Ontology Download Link

https://github.com/megbalk/bryo/blob/main/bryo.owl

### Contact Name

Meghan A. Balk

### Contact Email

meghan.balk@gmail.com

### Contact GitHub Username

megbalk

### Contact ORCID Identifier

0000-0003-2699-3066

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### Dependencies

- ro
- pato
- bco
- bfo
- bspo
- clyh
- iao
- ncbitaxon
- oba
- uberon

### Related

UBERON; OBA

### Intended Use Cases and/or Related Projects

We hope that other Bryozoan researchers will participate in this endeavor and help understand core developmental similarities among life. We also hope that the traits will be used as input into the Phenoscape Knowledgebase and the Functional Trait Resource for Environmental Studies datastore.

### Data Sources

We are using a combination of literature and experts.

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [ ] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by cmungall** [comment]
I think something went wrong with your release process

there is one class in the BRYO namespace:

```
<!-- http://purl.obolibrary.org/obo/BRYO_0000000 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/BRYO_0000000">
        <rdfs:label xml:lang="en">root node</rdfs:label>
    </owl:Class>
    
```

**Comment by cmungall** [comment]
I looked at the edit file and it looks like there are unsats that need resolved, so in theory it should be impossible for you to make a release with odk:

## [pore chamber plate](http://purl.obolibrary.org/obo/BRYO_0000003) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [pore chamber plate](http://purl.obolibrary.org/obo/BRYO_0000003) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001)
    - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [organ part](http://purl.obolibrary.org/obo/UBERON_0000064)
      - [organ part](http://purl.obolibrary.org/obo/UBERON_0000064) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
        - [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
          - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465)
            - [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)
    - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore](http://purl.obolibrary.org/obo/UBERON_0008915)
      - [pore](http://purl.obolibrary.org/obo/UBERON_0008915) SubClassOf [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464)
        - [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) SubClassOf [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466)
          - [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466) SubClassOf [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)
  - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)


## [pore chamber cavity](http://purl.obolibrary.org/obo/BRYO_0000002) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [pore chamber cavity](http://purl.obolibrary.org/obo/BRYO_0000002) EquivalentTo [anatomical cavity](http://purl.obolibrary.org/obo/UBERON_0002553) and ([luminal space of](http://purl.obolibrary.org/obo/RO_0002572) some [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001))
    - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [organ part](http://purl.obolibrary.org/obo/UBERON_0000064)
      - [organ part](http://purl.obolibrary.org/obo/UBERON_0000064) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
        - [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([has quality](http://purl.obolibrary.org/obo/RO_0000086) some [multicellular](http://purl.obolibrary.org/obo/PATO_0001993))
          - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465)
            - [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)
    - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore](http://purl.obolibrary.org/obo/UBERON_0008915)
      - [pore](http://purl.obolibrary.org/obo/UBERON_0008915) SubClassOf [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464)
        - [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) SubClassOf [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466)
          - [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466) SubClassOf [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)
  - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)


## [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [organ part](http://purl.obolibrary.org/obo/UBERON_0000064)
    - [organ part](http://purl.obolibrary.org/obo/UBERON_0000064) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
      - [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)
        - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465)
          - [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040)
  - [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore](http://purl.obolibrary.org/obo/UBERON_0008915)
    - [pore](http://purl.obolibrary.org/obo/UBERON_0008915) SubClassOf [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464)
      - [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) SubClassOf [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466)
        - [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466) SubClassOf [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)
  - [material entity](http://purl.obolibrary.org/obo/BFO_0000040) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141)

# Axiom Impact 
## Axioms used 3 times
- [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [organ part](http://purl.obolibrary.org/obo/UBERON_0000064) [bryo.owl]
- [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore](http://purl.obolibrary.org/obo/UBERON_0008915) [bryo.owl]
- [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [organ part](http://purl.obolibrary.org/obo/UBERON_0000064) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) SubClassOf [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) SubClassOf [material entity](http://purl.obolibrary.org/obo/BFO_0000040) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [immaterial anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000466) SubClassOf [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [pore](http://purl.obolibrary.org/obo/UBERON_0008915) SubClassOf [anatomical space](http://purl.obolibrary.org/obo/UBERON_0000464) [uberon_import.owl]
- [material entity](http://purl.obolibrary.org/obo/BFO_0000040) DisjointWith [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [immaterial entity](http://purl.obolibrary.org/obo/BFO_0000141) [oba_import.owl,ro_import.owl,pato_import.owl,bspo_import.owl,uberon_import.owl]

## Axioms used 2 times
- [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) [oba_import.owl,pato_import.owl,uberon_import.owl]

## Axioms used 1 times
- [pore chamber cavity](http://purl.obolibrary.org/obo/BRYO_0000002) EquivalentTo [anatomical cavity](http://purl.obolibrary.org/obo/UBERON_0002553) and ([luminal space of](http://purl.obolibrary.org/obo/RO_0002572) some [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001)) [bryo.owl]
- [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([has quality](http://purl.obolibrary.org/obo/RO_0000086) some [multicellular](http://purl.obolibrary.org/obo/PATO_0001993)) [oba_import.owl,pato_import.owl,uberon_import.owl]
- [pore chamber plate](http://purl.obolibrary.org/obo/BRYO_0000003) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [pore chamber](http://purl.obolibrary.org/obo/BRYO_0000001) [bryo.owl]



# Ontologies used: 
- ro_import.owl (http://purl.obolibrary.org/obo/bryo/imports/ro_import.owl)
- pato_import.owl (http://purl.obolibrary.org/obo/bryo/imports/pato_import.owl)
- uberon_import.owl (http://purl.obolibrary.org/obo/bryo/imports/uberon_import.owl)
- oba_import.owl (http://purl.obolibrary.org/obo/bryo/imports/oba_import.owl)
- bryo.owl (http://purl.obolibrary.org/obo/bryo.owl)
- bspo_import.owl (http://purl.obolibrary.org/obo/bryo/imports/bspo_import.owl)

**Comment by JCGiron** [comment]
I would suggest to consider the name space to be BRYOZ, to avoid ambiguity with Bryophytes if that's created in the future?

**Comment by megbalk** [comment]
based on feedback, I will create a new issue when it's ready! Thank you!

> I think something went wrong with your release process
> 
> there is one class in the BRYO namespace:
> 
> ```
> 
> 
>     <owl:Class rdf:about="http://purl.obolibrary.org/obo/BRYO_0000000">
>         <rdfs:label xml:lang="en">root node</rdfs:label>
>     </owl:Class>
>     
> ```

@cmungall what is that and how do I fix it?

**Comment by matentzn** [comment]
@megbalk > ODK created this in your edit file.. You can delete it from your edit file.
