### ISSUE TITLE
Make usage required for new ontology requests?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2281]
[It's a bit unsatisfying](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2279) to not have the usage being required for NORs IMO. 

Usage is required for full-fledged OBO ontologies - and since we have apparently opted for a more "high quality in" approach, maybe we can revisit this. We have determined repeatedly in OFOC meetings that the bar for usage is too high for OBO NORs. I think there are two way we could make `usage` mandatory for NORs:

1. We change our attitude to be entirely about mature, high-quality submissions, and explicitly move away from permitting new, under development ontologies. Namespace reservations can be done much more easily in bioregistry. So we are saying: Let's see if your ontology gets used in production systems first before we give you a PURL and a place in OBO Library.
2. We lower the bar for usage evidence a bit and say: if you can show us any website that explicitly lists your ontology as a component of the infrastructure, its fine. Anyone should be able to do that. It waters down the meaning of the principle, but it gets people to at least make their usage explicit. (remember, use previously required proof of _term ID usage_).

I don't feel too strongly about any of this, but just for the record, I am a bit in favour for making usage mandatory in NOR submissions. I think argument 1 convinces me a tiny bit more than 2 (which means I made a 180 degree pivot on my position 1 year ago, sorry).

**Comment by pfabry** [comment]
Regarding argument 1: Is there a policy on using OBO Foundry PURLs for new ontology requests? It seems to me that access to OBO PURL is an big incentive to submit an ontology. All new ontologies already use IRIs like http://purl.obolibrary.org/obo/XXX, which results in OBO PURLs that do not resolve if the ontology is not ultimately accepted (see issue #1338 for example). Could we offer an alternative to applicants (or direct them to another service)? It might limit their need to submit it too quickly to the OBO Foundry.

**Comment by matentzn** [comment]
@pfabry the alternative is to use a public service like https://github.com/perma-id/w3id.org, which we use for many of our projects - in fact, many vocabularies do that! So we can say: of you want to reserve a prefix (like OBI or MONDO) you can go register it at bioregistry, and if you want resolvable PURLS, go to w3id.org. So there are alternatives.

**Comment by pfabry** [comment]
Should it be a requirement for a new ontology request: having already a prefix registered and resolvable PURLs ? On the other hand, it would imply changing all IRIs if the ontology is accepted.
As you said, this comes back to the more fundamental question of which ontologies should be part of the OBO Foundry.

**Comment by matentzn** [comment]
No, definitely not - that is too much of a burden.. They do not need resolvable PURLs. Let's focus the discussion in this issue only about the question whether usages are required. Can you open a new issue with your questions?

**Comment by nlharris** [comment]
See also #2300

**Comment by nataled** [comment]
From OFOC meeting 2023-03-07:

Nico: let’s document once and for all what exactly constitutes an acceptable evidence for the Usage Principle

- Nico suggests making it more explicit that the description field for a usage metadata entry includes concrete way to verify that terms of the ontology are being used in the particular external resource
- Can be verified by PR review of metadata steward; if there is question, can be brought to OBO operations meeting
- Not part of new ontology request

Consensus vote approved for Editorial WG to update the principle to reflect Nico’s suggestion

**Comment by nataled** [comment]
Unfortunately neither @cstoeckert nor I were able to make the Ops call when this was discussed, so there are a few things for which we are unclear (referencing here the notes from that Ops call, reproduced in the comment directly above):

1) It appears that 'Not part of new ontology request' pertains to a decision to keep this principle exclusively for accepted ontologies, in contrast to this tracker proposal. Is that correct? If so, this issue should be closed with a 'Wont do' label.

2) Regarding the consensus vote to update the principle to reflect Nico's suggestion, it isn't clear what that suggestion is. It appears from the notes to refer to the first bullet point given in the Ops call minutes; that is, 'making it more explicit that the description field for a usage metadata entry includes concrete way to verify that terms of the ontology are being used in the particular external resource'. Is that the suggestion referred to? If so, what concrete ways were mentioned, and in what way do they differ from the examples already provided in the principle?
