### ISSUE TITLE
MS OBO and OWL versions 

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#229]
The OBO and OWL files are different versions of MS

http://obofoundry.org/ontology/ms.html
The OBO file is correct  http://www.berkeleybop.org/ontologies/ms.obo

The OWL file is out of date  http://www.berkeleybop.org/ontologies/ms.owl.

Can this be fixed?  Shouldn't this be automated?

**Comment by nlharris** [comment]
is this still relevant?

**Comment by nlharris** [comment]
Can we close this?

**Comment by balhoff** [comment]
Both the OBO and OWL files available at the PURL have the same date, 17:02:2020.
