### ISSUE TITLE
Request: Access to the slack workspace

### ISSUE THREAD

**Issue by crisely09** [OBOFoundry/OBOFoundry.github.io#2301]
Hi, on the OBO foundry website I didn't find a place where I could ask to be invited to the slack workspace, is there a form for this?
Thank you.

**Comment by nlharris** [comment]
There's a link to the Slack workspace on the home page and also in the "Participate" menu.
<img width="868" alt="Screen Shot 2023-02-19 at 10 25 41 PM" src="https://user-images.githubusercontent.com/348704/220028308-645ae167-40aa-40f1-a114-6e7113bea4d2.png">

**Comment by crisely09** [comment]
Hi, when I use the link and give my email it doesn't work as my email is not registered, so could you please give me access (crisbeth46@gmail.com)
<img width="538" alt="Screenshot 2023-02-20 at 10 30 50" src="https://user-images.githubusercontent.com/3536415/220067006-8ecf69d7-054d-4fe2-89e1-6fa2182e6381.png">

**Comment by matentzn** [comment]
I sent you a link :) welcome!

**Comment by crisely09** [comment]
Great, thank you!
