### ISSUE TITLE
Request for new ontology CDMO

### ISSUE THREAD

**Issue by HuJieNJ** [OBOFoundry/OBOFoundry.github.io#2302]
### Title

Chinese Diabetes Mellitus Ontology

### Short Description

CDMO

### Description

CDMO is a Chinese diabetes ontology, classes cover all aspects of diabetes, such as symptoms, medications, tests, body structure, social background, etc. Most of these classes have been mapped to existing classes in the OBO, and these mappings are represented by annotation properties. Our motivation is to apply this ontology to the construction of Chinese diabetes knowledge graph, natural language processing and medical question answering, which are all application scenarios closely related to language. We hope that this ontology can be adopted by researchers and developers of the above application systems.

### Identifier Space

CDMO

### License

CC0

### Domain

health

### Source Code Repository

https://github.com/HuJieNJ/CDMO

### Homepage

https://github.com/HuJieNJ/CDMO

### Issue Tracker

https://github.com/HuJieNJ/CDMO/issues

### Ontology Download Link

https://github.com/HuJieNJ/CDMO/raw/main/cdmo20230218.owl

### Contact Name

Hu Jie

### Contact Email

hujie@njmu.edu.cn

### Contact GitHub Username

Hu Jie

### Contact ORCID Identifier

0000-0002-4634-9406

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [ ] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [ ] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [ ] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by HuJieNJ** [comment]
> ### Title
> Chinese Diabetes Mellitus Ontology
> 
> ### Short Description
> CDMO
> 
> ### Description
> CDMO is a Chinese diabetes ontology, classes cover all aspects of diabetes, such as symptoms, medications, tests, body structure, social background, etc. Most of these classes have been mapped to existing classes in the OBO, and these mappings are represented by annotation properties. Our motivation is to apply this ontology to the construction of Chinese diabetes knowledge graph, natural language processing and medical question answering, which are all application scenarios closely related to language. We hope that this ontology can be adopted by researchers and developers of the above application systems.
> 
> ### Identifier Space
> CDMO
> 
> ### License
> CC0
> 
> ### Domain
> health
> 
> ### Source Code Repository
> https://github.com/HuJieNJ/CDMO
> 
> ### Homepage
> https://github.com/HuJieNJ/CDMO
> 
> ### Issue Tracker
> https://github.com/HuJieNJ/CDMO/issues
> 
> ### Ontology Download Link
> https://github.com/HuJieNJ/CDMO/raw/main/cdmo20230218.owl
> 
> ### Contact Name
> Hu Jie
> 
> ### Contact Email
> [hujie@njmu.edu.cn](mailto:hujie@njmu.edu.cn)
> 
> ### Contact GitHub Username
> Hu Jie
> 
> ### Contact ORCID Identifier
> 0000-0002-4634-9406
> 
> ### Formats
> * [x]  OWL RDF/XML (.owl)
> * [ ]  OBO (.obo)
> * [ ]  OBO Graph JSON (.json)
> 
> ### Dependencies
> _No response_
> 
> ### Related
> _No response_
> 
> ### Usages
> _No response_
> 
> ### Intended Use Cases and/or Related Projects
> _No response_
> 
> ### Data Sources
> _No response_
> 
> ### Additional comments or remarks
> _No response_
> 
> ### OBO Foundry Pre-registration Checklist
> * [x]  I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
> * [x]  There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
> * [ ]  My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
> * [ ]  I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
> * [x]  For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
> * [x]  For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
> * [x]  For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
> * [ ]  If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
> * [x]  The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

[cdmo20230218.owl.zip](https://github.com/OBOFoundry/OBOFoundry.github.io/files/10774503/cdmo20230218.owl.zip)

**Comment by pfabry** [comment]
Dear @HuJieNJ,
    
  Thank you for your submission. The review will be executed as a two stage process. 
  First, you will have to pass [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check _apart from `Users` may be red_.
  After you have successfully passed the Dashboard you will be assigned an OBO Operations committee member to review the ontology.
    
  Usually, the review will result in an opportunity for you to improve the ontology.
  When the reviewer believes the ontology is ready for presentation to the OBO Operations Committee, they will present
  your ontology during an OBO Operations Call. This gives other members of the
  committee the opportunity to assess your work.
    
  When a decision is reached by the committee you will be informed here on the issue tracker.
  The process can take any number of weeks or months, depending on the case at hand.
  Please inform us about any reasons you might have for increased urgency.
    
  You will be informed once your ontology is loaded in the OBO NOR Dashboard.
    
  Good luck.

**Comment by matentzn** [comment]
@HuJieNJ thank you for your submission. We have discussed your case, and there are two main issues to prevent us accepting CDMO into OBO.

1. We do need the ontology to provide english language label, so we can review it and provide feedback. While we realise this is not explicitly stated anywhere, it is an unfortunate necessity due to our detailed review process which we cannot perform in any other language. We would like to invite you though to consider, instead of submitting an entire ontologies, submit a language profile like https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/3bb24f3505efd9fe9cdf99e09390bd936a1b796c/src/ontology/translations/hp-cs.babelon.tsv which we could use to include your valuable translations into the respective OBO ontologies
2. You are creating CDMO identifiers for all classes, and then provide a link to an existing OBO (and non-OBO) class, which is fundamentally against OBO Foundry practices: We should always re-use the term IRIs directly, to make our vision for data and knowledge integration feasible.

Please feel free to address these two issues above and make a new ontology request here, or reach out to us (again here on the issue tracker) to talk about how we can add your translations to their respective ontologies in OBO.

Again, thank you for you work and apologies for the negative response! We are looking forward for your future submissions.
