### ISSUE TITLE
Need Slack link that allows new people to join our workspace

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2303]
See #2301

I thought we had set up a Slack link that let anyone join our obo-community workspace. Turns out that we did, for #linkml-community (which is also in the obo-community slack). https://linkml.io/linkml/faq/contributing.html has a link that gets you to a "join" page that lets you sign up.

The Slack link on obofoundry.org goes to https://obo-communitygroup.slack.com/, which goes to a "sign in" page.

I think we can just change that link to the shared_invite one used for #linkml-community (though I'm not sure whether that one sends you to that specific channel once you join -- I don't really want to create a new fake Slack account to check).

Or did we decide that to avoid spam/bots, if new people want to join the obo-community workspace, they should ask us for an invitation? I can't remember if we decided that.

**Comment by matentzn** [comment]
I think we should not open the slack up that much. Is there a way to:

1. Request people to join OBO discuss mailing list
2. And automatically send them a message to "join" the OBO slack when they become a member?

That way we can do at least some vetting that its not an obvious bot.

For those that are already on OBO discuss, they can simply send an email to obo discuss for requesting access? Or do you think that is too noisy for that mailing list?

**Comment by matentzn** [comment]
I removed the OFOC call tag for now, because this seems like an issue for the Technical Working Group to sort out.

**Comment by nlharris** [comment]
> 1. Request people to join OBO discuss mailing list
> 2. And automatically send them a message to "join" the OBO slack when they become a member?

Oh, good idea. Re #2, I changed the Welcome message for obo-discuss to add a sentence encouraging the new list member to also join the Slack (with the Slack link that should let anyone join).

Re #1, currently the Participate menu has an item "Join the OBO community Slack", which points to the Slack link that goes to the Slack but doesn't let you join if you're not already a member. Is that ok for now? Where were you thinking we should "Request people to join OBO discuss mailing list"? It would be awkward to try to put "We have a Slack channel, but join the obo-discuss mailing list first to get a link for that" into the menu. Should I make the Slack menu item point to a page that just says that?

**Comment by matentzn** [comment]
Just to double-check, don't these "join" links expire? 

The best solution would be to have a link that allows people to request to be added to a slack space, but requiring an admin to approve. Does that exist?

**Comment by nlharris** [comment]
Since there doesn't seem to be a way to let people request to be added to a Slack channel but require admin approval, and since I implemented the clever fallback solution that Nico suggested (I changed the Welcome message for obo-discuss to add a sentence encouraging the new list member to also join the Slack (with the non-expiring Slack link that should let anyone join)), is it ok to close this as done?

**Comment by matentzn** [comment]
Let's close it :)

**Comment by nlharris** [comment]
You closed it as not planned, but it's done! "Slack link that allows new people to join our workspace" <- DONE
