### ISSUE TITLE
Request clarification: Add English language requirements to NOR Review Process

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2304]
During the call today (21st February 2023) we have raised the issue again of a non-English ontology submission. While it is a very unfortunate practical requirement, I think we should officially codify that there must at least an English language label present for each class in the ontology. If there are definitions, these should be provided in English as well.

There are some practical issues with validating multi-language ontologies. Lets not make this about that. I think if we want to seriously do our jobs reviewing an ontology, we should be able to understand it, and therefore I advocate the above.

**Comment by nlharris** [comment]
I though we already had an English-language requirement for submitted ontologies. I was surprised not to find any mention of language in https://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html, nor do I see it on the dashboard checks.

**Comment by matentzn** [comment]
## VOTE: Submitted ontologies MUST provide english language labels

- 👍 Ontologies submitted to the OBO foundry must provide English language labels to make an effective manual review process possible
- 👎 We should consider submissions without English labels and use translation tools to aid in the review, or employ speakers of the language as reviewers

This vote closes on the 16th October.

**Comment by nlharris** [comment]
16th October? Like, 7 months from now?

**Comment by matentzn** [comment]
Sorry, 16th March, updated.

**Comment by matentzn** [comment]
@pfabry its a good point - I think we can fix this on Dashboard level; Its indeed a hairy issue, and we will should make some attempt to solve it on our end (reading only @en, or no language tag) and then requesting the community to provide a suitable version. Because we probably should not simply disallow multilanguage ontologies just because of the difficult of writing the tests correctly.

**Comment by matentzn** [comment]
Discussed [here](https://github.com/information-artifact-ontology/ontology-metadata/issues/100)

**Comment by nlharris** [comment]
What are the next steps for this?

**Comment by matentzn** [comment]
If @nataled feels that this requirement is sufficiently documented in the NOR document, it can be closed. From my perspective this is done

**Comment by nataled** [comment]
@matentzn the EWG hasn't been able to meet since we were tagged in this issue. However, it isn't clear which document you refer to. Can you point to 'the NOR document'? All the ones I found that could be relevant lack any indication of language requirement.

**Comment by matentzn** [comment]
Maybe not so clear yet:

In addition to (already done):

- https://obofoundry.org/principles/fp-006-textual-definitions.html
- https://obofoundry.org/principles/fp-012-naming-conventions.html

I would suggest we capture the outcome of this discussion here:

- https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/.github/ISSUE_TEMPLATE/new-ontology.yml
- https://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

**Comment by nataled** [comment]
I created a PR #2432 to handle the new ontology checklist. I don't see how this issue relates to the namespace and PURL request page though.
