### ISSUE TITLE
US BirthOnto - Ontology for Analyzing US Birth Data

### ISSUE THREAD

**Issue by abhilashcb8** [OBOFoundry/OBOFoundry.github.io#2309]
We want to add the ontology designed for analyzing the US Birth Dataset. 
The US Birth data is designed for the data that is made available by CDC.   
Link: https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm

**Comment by cthoyt** [comment]
hi @abhilashcb8 , have you seen the issue picker in this repo at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new/choose that has a specific issue for new ontology requests?

**Comment by cthoyt** [comment]
Closed in favor of #2310

**Comment by abhilashcb8** [comment]
I used this link to update my ontology request: 
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology.yml&title=Request+for+new+ontology+%5BNAME%5D

**Comment by abhilashcb8** [comment]
I have designed an Ontology for US birth dataset, and we want it to be added on OBO Foundary. Please guide us with the procedure.
