### ISSUE TITLE
US BirthOnto

### ISSUE THREAD

**Issue by abhilashcb8** [OBOFoundry/OBOFoundry.github.io#2310]
### Title

Ontology for analyzing the US birth Data 

### Short Description

The Birth Ontology - BirthOnto can be used to infer the interesting relationship from Birth data using the domain ontology. 

### Description

1. What complications can a pregnant woman experience during childbirth, and how are they related to the chosen delivery method?
2. What risk factors are associated with a preterm birth, and how do these factors affect the neonatal outcomes?
3. Which maternal factors most substantially impact fetal growth, and how can these factors be monitored to ensure optimal fetal development?
4. What are the differences in birth outcomes between singleton and multiple pregnancies, and how are these outcomes affected by maternal age and pre-existing medical conditions?
5. How can healthcare providers use information about the mother's health history and previous pregnancies to identify and manage potential risks during childbirth?

### Identifier Space

ubo

### License

CC0

### Domain

health

### Source Code Repository

https://koolgax99.github.io/abhilash-US-birth-onto/index-en.html

### Homepage

https://koolgax99.github.io/abhilash-US-birth-onto/index-en.html

### Issue Tracker

https://koolgax99.github.io/abhilash-US-birth-onto/index-en.html

### Contribution Guidelines

https://koolgax99.github.io/abhilash-US-birth-onto/index-en.html

### Ontology Download Link

https://github.com/abhilashcb8/US-BirthOnto

### Contact Name

Abhilash c b

### Contact Email

abhilashcb@iiitdwd.ac.in

### Contact GitHub Username

Abhilashcb8

### Contact ORCID Identifier

https://orcid.org/0000-0001-9596-6630

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [ ] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [ ] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [ ] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by nlharris** [comment]
> I have designed an Ontology for US birth dataset, and we want it to be added on OBO Foundary. Please guide us with the procedure.

Hi @abhilashcb8, thank you for submitting your ontology for consideration. In order for your ontology to be reviewed by OBO Foundry, you should first complete the items on the checklist above (see https://obofoundry.org/docs/NewOntologyRegistrationInstructions.html for more info) and then your ontology will need to pass minimum metadata requirements and will be checked on the dashboard, e.g. https://obofoundry.org/obo-nor.github.io/dashboard/mcro/dashboard.html.

**Comment by nlharris** [comment]
@abhilashcb8 just checking whether you intend to address the outstanding items in order for your ontology to be reviewed.

**Comment by handemcginty** [comment]
We will close this issue since we haven't heard back from you in two months, but if you respond back, we'll reopen it.
