### ISSUE TITLE
Add note to adding CONTRIBUTION.md "collaboration principle" page.

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2312]
@erik-whiting please make sure this is reflected in the "collaboration principle" page.

_Originally posted by @matentzn in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1836#issuecomment-1440088480_

**Comment by erik-whiting** [comment]
@matentzn is there any specific copy you want me to put into the collaboration principle page or do you want me to just come up with my own summary of Charlie's comment here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1836#issuecomment-1101314601 ?

**Comment by erik-whiting** [comment]
Closed by #2341
