### ISSUE TITLE
URI/Namespace request

### ISSUE THREAD

**Issue by mbrochhausen** [OBOFoundry/OBOFoundry.github.io#232]
requested prefix: OOSTT
ontology title: The Ontology of Organizational Structures of Trauma centers and Trauma systems
ontology download link: https://raw.githubusercontent.com/OOSTT/OOSTT/master/oostt.owl
ontology home page: https://github.com/OOSTT/OOSTT
point person contact email: mbrochhausen@gmail.com
ontology discussion mailing-list: -
ontology issue tracker link: https://github.com/OOSTT/OOSTT/issues
purl.org user ID : mbrochhausen

**Comment by mbrochhausen** [comment]
Here is the boo-discuss message i posted:
https://sourceforge.net/p/obo/mailman/message/34913917/

**Comment by cmungall** [comment]
14 days have passed with no objection, so we can go ahead and add

Sorry I don't have time to add right now, see http://obofoundry.org/ FAQ for adding an md file to this repo (first) and an entry to https://github.com/OBOFoundry/purl.obolibrary.org/

**Comment by mbrochhausen** [comment]
Chris,

excellent! Many thanks. I'll go forward and try to make the changes in the
next few days.

Best,
Mathias

**Comment by jamesaoverton** [comment]
Registry entry created in PR #242, an PURLs created in https://github.com/OBOFoundry/purl.obolibrary.org/pull/170.
