### ISSUE TITLE
Question: GEMO ontology

### ISSUE THREAD

**Issue by kehey** [OBOFoundry/OBOFoundry.github.io#2320]
Hi,

someone mentioned that the obo foundry had a Gene Editing and Gene Modification ontology (GEMO) but I can’t find any reference to it here.

Is this information wrong or has that ontology been removed?

Kind regards,

Ken

**Comment by matentzn** [comment]
I have checked on GEMO, but cannot find any evidence of it; maybe someone else knows?

**Comment by cthoyt** [comment]
Neither Bioregistry (https://bioregistry.io/gemo) nor BioPortal (https://bioportal.bioontology.org/ontologies/GEMO) has a reference to it, meaning it is either very obscure, or listed under a different name.
