### ISSUE TITLE
Principle #13 "Notification" : specify types of changes requiring notifications

### ISSUE THREAD

**Issue by sabrinatoro** [OBOFoundry/OBOFoundry.github.io#2322]
Thank you for this new principle. 
It would be helpful to specify the types of changes that require advance notifications as what might be "impactful" could be very subjective. 
For example, term obsoletion and big classification rearrangements should definitely be announced in advance. However, one might argue that the creation of new terms or small classification changes is not. 

This principle might affect the ontology editing workflow: for example, users ask for a new term to be added urgently, and a GitHub issue might be created and closed less than 7 days before a release. Also, many changes can happen during a workshop, also making the notification of changes less than 7 days before a release. 

It would be therefore helpful to have more specifics about the type of changes that we (the obo foundry) agree should require advance notifications.

**Comment by nataled** [comment]
My recollection of discussion of this principle is that it IS very subjective, and the guidelines were kept a bit vague to err on the side of flexibility (hence the clause "...and any other[types of change]s that are determined with stakeholder benefit in mind"). The major concern cited was that this can end up being a very heavy-weight principle for smaller ontologies. That being said, it is likely that we could come up with a minimum set of 'important' notifications.

**Comment by balhoff** [comment]
Discussed in OFOC call 2023-07-11: agreement that it would be useful to add examples to the principle page for the kinds of changes that it's useful to notify users about. Please add suggestions to this issue.

**Comment by matentzn** [comment]
The most important one is: planned obsoletions. This can help users to intervene if necessary. I would start with that and then add others if needed.

**Comment by matentzn** [comment]
Removed the OFOC call label as no clear action items for the Ops call. At the last meeting, 13 people did not have any further opinion about this.

**Comment by nlharris** [comment]
So what are the next steps here?

**Comment by nataled** [comment]
Done.
