### ISSUE TITLE
Request for new ontology [COVID-19 Epidemiology and Monitoring Ontology]

### ISSUE THREAD

**Issue by NuriaQueralt** [OBOFoundry/OBOFoundry.github.io#2332]
### Title

COVID-19 Epidemiology and Monitoring Ontology

### Short Description

The COVID-19 Epidemiology and Monitoring Ontology (CEMO) provides a model for describing, sharing and integrating of COVID-19 epidemiological data for outbreak monitoring and research. 

### Description

The COVID-19 Epidemiology and Monitoring Ontology (CEMO) is designed to make epidemiological quantitative data for monitoring the COVID-19 outbreak machine-readable and interoperable to facilitate its exchange, integration and analysis, to eventually support evidence-based rapid response. This ontology has built following knowledge-engineering standards and the OBO principles to bridge epidemiology into the semantic landscape of the biomedical sciences.

CEMO is designed to be an OBO ontology, i.e., founded on the [BFO](http://www.obofoundry.org/ontology/bfo.html) hierarchy. The taxonomic structure is mainly extended with [IDO](http://www.obofoundry.org/ontology/ido.html), a core ontology for infectious diseases, [STATO](http://www.obofoundry.org/ontology/stato.html), and [APOLLO_SV](http://www.obofoundry.org/ontology/apollo_sv.html) for epidemiology OBO ontologies terms necessary for epidemiology surveillance. The ontology is built in OWL 2, a DL-based formalism and semantic web standard for knowledge representation to enable data sharing and logic reasoning.

Our formal modeling followed a rationale already used in other studies: 1) determine the domain and scope of the ontology; 2) ontology reuse and addressing poor ontological coverage of COVID-19 epidemiology; and 3) development of a conceptual model for quantitative epidemiological terms. The potential users of the ontology are epidemiological and biomedical researchers.

### Identifier Space

CEMO

### License

CC0

### Domain

health

### Source Code Repository

https://github.com/NuriaQueralt/covid19-epidemiology-ontology

### Homepage

https://github.com/NuriaQueralt/covid19-epidemiology-ontology

### Issue Tracker

https://github.com/NuriaQueralt/covid19-epidemiology-ontology/issues

### Contribution Guidelines

https://github.com/NuriaQueralt/covid19-epidemiology-ontology#i-want-to-contribute

### Ontology Download Link

https://github.com/NuriaQueralt/covid19-epidemiology-ontology/blob/main/owl/cemo.owl

### Contact Name

Núria Queralt Rosinach

### Contact Email

nuria.q.rosinach@gmail.com

### Contact GitHub Username

NuriaQueralt

### Contact ORCID Identifier

0000-0003-0169-8159

### Formats

- [X] OWL RDF/XML (.owl)
- [X] OBO (.obo)
- [X] OBO Graph JSON (.json)

### Dependencies

- bfo
- ro
- ido
- stato
- iao
- appollo_sv
- obi
- ncit
- ogms
- pato

### Related

- genepio

### Intended Use Cases and/or Related Projects

To enable to enable the publication of aggregated health data and federated analysis on sensitive health data for projects such as [VODAN](https://www.vodan-totafrica.info/).

### Data Sources

We reviewed among other sources:
- Case report forms
- peer-reviewed publiations
- medrXiv

Please see more details [here](https://github.com/NuriaQueralt/covid19-epidemiology-ontology#references-for-curation-and-related-models).

### Additional comments or remarks

Note that CEMO is currently under development and subject to change.

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [ ] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [ ] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by cmungall** [comment]
I notice that your ontology injects a lot of axioms into existing ontologies:

* [] BFO:0000019 quality
    * [i] **obo:CEMO_0000126 ! quantitative quality**
        * [i] obo:VIDO_0001331 ! viral load
        * [i] obo:COVOC_0010003 ! confirmed cases
        * [i] obo:CEMO_0000125 ! quarantined cases
        * [i] obo:CEMO_0000122 ! new daily cases
        * ...
        * [snip]
        * ...
        * [i] obo:CEMO_0000004 ! quantity of infected population
        * [i] obo:CEMO_0000003 ! infection fatality rate
        * [i] obo:CEMO_0000002 ! hospital-wide nosocomial infection rate per 100 admissions
        * [i] obo:CEMO_0000001 ! number of cases removed from isolation this week
        * [i] VO:0000247 ! vaccine efficacy
        * [i] STATO:0000424 ! risk difference
        * [i] STATO:0000414 ! mortality rate
        * [i] STATO:0000412 ! prevalence
        * [i] STATO:0000245 ! relative risk
        * [i] STATO:0000233 ! sensitivity
        * [i] STATO:0000182 ! odds ratio
        * [i] STATO:0000134 ! diagnostic specificity
        * [i] STATO:0000088 ! study group population size
        * [i] PATO:0001415 ! morbidity
        * [i] ORDO:409966 ! point prevalence
        * [i] OBCS:0000064 ! period prevalence
        * [i] OBCS:0000052 ! incidence proportion ratio
        * [i] OAE:0001869 ! recovery rate
        * [i] NCIT:C67448 ! infectious dose
        * [i] NCIT:C17734 ! at-risk population
        * [i] NCIT:C164607 ! gene sequence identity
        * [i] NCIT:C164332 ! sequence identity of sample
        * [i] IDO:0001343 ! latency period
        * [i] IDO:0000519 ! incubation period
        * [i] IDO:0000484 ! infection incidence rate
        * [i] IDO:0000482 ! incidence proportion
        * [i] IDO:0000467 ! susceptibility
        * [i] IDO:0000466 ! virulence
        * [i] IDO:0000463 ! transmission probability
        * [i] GSSO:006827 ! fertility rate
        * [i] EFO:0004804 ! birth rate
        * [i] APOLLO_SV:00000569 ! total number of cases
        * [i] APOLLO_SV:00000568 ! total number of deaths
        * [i] APOLLO_SV:00000497 ! number of cases new this week
        * [i] APOLLO_SV:00000449 ! quarantine period
        * [i] APOLLO_SV:00000163 ! recovered cases
        * [i] APOLLO_SV:00000140 ! infectious period
        * [i] APOLLO_SV:00000002 ! basic reproduction number
        * [i] <http://purl.unep.org/sdg/SDGIO_00020030> ! neonatal mortality rate

OBO operations has not yet achieved consensus on best practices for axiom injection (#1443), so my comments do not reflect official OBO views. In the past this has caused a lot of issues as it is easy to arrive at a situation with conflicts. 

For example, you inject APOLLO_SV:00000569 under BFO quality, but this conflicts with what is in APOLLO_SV:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/50745/227044535-36000be8-ca88-4173-bc84-5333a557aaf9.png">

so merging these ontologies results in a conflict:

```
robot merge -i cemo.owl -I $OBO/apollo_sv.owl reason -r elk
2023-03-22 14:40:22,622 ERROR org.obolibrary.robot.ReasonerHelper - There are 23 unsatisfiable classes in the ontology.
2023-03-22 14:40:22,627 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl#APOLLO_SV_00000002
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl#APOLLO_SV_00000001
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/apollo_sv/dev/apollo_sv.owl#APOLLO_SV_00000003
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000449
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000568
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000569
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/CEMO_0000064
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/IDO_0000519
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000002
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/STATO_0000088
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000140
2023-03-22 14:40:22,628 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000382
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000163
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000383
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/STATO_0000245
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/IDO_0001343
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000381
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000016
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000277
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000497
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/APOLLO_SV_00000498
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/STATO_0000134
2023-03-22 14:40:22,630 ERROR org.obolibrary.robot.ReasonerHelper -     unsatisfiable: http://purl.obolibrary.org/obo/STATO_0000233
```

I would recommend that you have transparent (i.e github issue) bilateral discussions with the relevant ontologies where if you either disagree with their placement or want to otherwise inject there is clear ongoing discussion about this.

I note you have also injected an axiom subClassOf 'quality of' some 'spatial region' into [IDO infection incidence rate](http://purl.obolibrary.org/obo/IDO_0000484). This is a pretty odd axiom, it didn't seem to original with IDO, and it will also cause inference issues.

I also note that that many of your terms seem out of scope for a covid ontology. What happens if say apollo sv or IDO or another ontology wants to add a term "infection fatality rate"? Are they obliged to check all ontologies in OBO including CEMO? What is the SOP if it is determined it is in scope for apollo_sv? Is the term adopted or is the CEMO term obsoleted and replaced by an apollo_sv term?

I want to be clear to other members of OBO-operations here though that the problems I note are prevalent with many other OBO ontologies, so I don't think CEMO should be held to a different standard. But I want to underscore the importance of other members of OBO being supportive of proactively solving some of these issues

**Comment by linikujp** [comment]
I agree that CEMO's focus on COVID-19 can be seen as a use case of epidemiological and monitoring ontology in COVID-19. 
@NuriaQueralt Can we change the name to Community or Common Epidemiology and Monitoring Ontology? You could keep the CEMO, but transform it to a broader sense. 
I am the part of the team of this ontology. I agree that @cmungall comments make sense.
We'd like to reserve the namespace CEMO while we are reaching out other ontologies and coordinate.

**Comment by pfabry** [comment]
Hi @NuriaQueralt,

Thank you for your submission. The review for new ontologies will be executed as a two stage process. 
  First, you will have to pass [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check _apart from `Users` may be red_.
  After you have successfully passed the Dashboard you will be assigned an OBO Operations committee member to review the ontology.

You will be informed once your ontology is loaded in the OBO NOR Dashboard. All communications should take place in the present issue.

I see that you have already reserved the namespace with Bioregistry. Please let me know if you want to postpone your submission to the NOR dahsboard considering the issues raised by above.

**Comment by NuriaQueralt** [comment]
Hi @cmungall @linikujp @pfabry,

Thank you very much for your fast feedback.

@cmungall your analysis is super useful! we are currently drafting a more accurate modelling of domain knowledge that have already addressed some of these logical inconsistencies. When finished, we think that will resolve them. 

@linikujp this is a great idea and we support it.

@pfabry I am asking the CEMO team about postponing our submission to the NOR dashboard. I will get back to you asap.

**Comment by NuriaQueralt** [comment]
Hi @pfabry 

We would like to postpone our submission to the NOR dahsboard considering the issues raised above. How should I proceed once we address the issues and feel ready to restart the submission?

**Comment by pfabry** [comment]
Hi @NuriaQueralt 

I would advise you to close this issue and open a new one once you're ready.

**Comment by NuriaQueralt** [comment]
Hi @pfabry ,

Thank you very much!

**Comment by pfabry** [comment]
Feel free to reopen this issue or create a new one when you are ready to submit.
