### ISSUE TITLE
Typo: "Resouces" instead of "Resources"

### ISSUE THREAD

**Issue by cmrn-rhi** [OBOFoundry/OBOFoundry.github.io#2333]
> If you are reporting an issue with our website, please specify the URL you were looking at, which browser and OS you are using, and if possible, include a screenshot showing the problem.

It is in the navigation menu and thus viewable across the site, but I first noticed when navigating from: https://obofoundry.org/principles/fp-000-summary.html
**Browser:** Chrome
**OS:** Windows 10

**Issue:** Navigation menu item says "Resouces" instead (I assume) "Resou**r**ces"
**Navigation:** _hamburger menu_ > About > Resouces

![image](https://user-images.githubusercontent.com/48695054/228378280-38ffec46-1738-4a93-bc10-25d82048c22a.png)

**Comment by nlharris** [comment]
Hi Rhiannon, thanks for noticing that typo! I can fix it, but first I wanted to check whether you'd like to fix it yourself by submitting a Pull Request! We welcome contributions from the community, and this is an easy way to dip your toe into the GitHub water.

The file that needs to be changed is https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/_includes/header.html

If you've never made a PR before, it's straightforward! Just make the edit, and then click "Propose changes" at the bottom and we'll review your change and then merge it in.

**Comment by nlharris** [comment]
I went ahead and put in the PR; you can take a look at it in case you want to do a PR yourself in the future! #2334

**Comment by cmrn-rhi** [comment]
Thanks @nlharris! I wasn't sure the etiquette around PRs, next time I'll include a PR issue requests like this.
