### ISSUE TITLE
using IRIs as URLs -- http:// in a world that wants https://

### ISSUE THREAD

**Issue by melissaclarkson** [OBOFoundry/OBOFoundry.github.io#2346]
Here is an issue that has come up in my team's work to develop interfaces that use ontology classes and link out to further information about those classes:

Web browsers are increasingly not following links with "http://" and allowing only "https://" unless the user overrides this security precaution.  OBO purls use the form "http://purl.obolibrary.org/", as do many other terminology purls. Therefore the convenience of using IRIs as URLs is now in question in interface designs that make use of this dual role.

Thoughts on how the OBO Foundry will handle this?

**Comment by nlharris** [comment]
I had this vague memory that there was some other open issue regarding http vs https but I can't find it...

**Comment by cmungall** [comment]
There is an entire channel dedicated to this in slack. We need to surface
some of these conversations and add to faq

**Comment by matentzn** [comment]
Some more context https://github.com/OBOFoundry/purl.obolibrary.org/issues/705

But a bit out of date compared to slack; please @melissaclarkson can you move your question to that issue tracker item?

**Comment by matentzn** [comment]
Lets close this issue here and continue in https://github.com/OBOFoundry/purl.obolibrary.org/issues/705
