### ISSUE TITLE
NCIT (national cancer institute thesaurus) OBO Edition Links are broken for Chrome

### ISSUE THREAD

**Issue by plbremer** [OBOFoundry/OBOFoundry.github.io#2354]
Those URLs associated with this Ontology
https://obofoundry.org/ontology/ncit.html

such as http://purl.obolibrary.org/obo/ncit.obo
do not trigger a download when clicked. 

Failed: Chrome - Version 112.0.5615.165 (Official Build) (64-bit)

but it worked for Mozilla Firefox

**Comment by balhoff** [comment]
@plbremer we have a couple of other issues related to this: #2346 and https://github.com/OBOFoundry/purl.obolibrary.org/issues/705

Chrome no longer likes to allow file downloads via HTTP from an HTTPS page. The ontology PURLs act as both URLs and identifiers, so it makes decisions on switching to HTTPS a little more complicated.

**Comment by plbremer** [comment]
gotcha, thanks.

**Comment by plbremer** [comment]
i closed, but maybe you want it open for others to see
