### ISSUE TITLE
Game plan: What should happen on 01.01.2024 when passing Dashboard becomes mandatory?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2360]
- As per OBO Foundry operations call, we have decided that passing the OBO Dashboard will be mandatory by 01.01.2024. 
- "Passing the dashboard" means that there are no errors listed (no "red X" ❌ )
- The process of "fixing an error" can be achieved in two ways:
    1. An error in the metadata and ontologies are fixed by the ontology maintainer
    2. An error is deemed unfixable with a reasonable amount of resources. In this case, any affected community member may request the test to be weakened using a GitHub issue. That request is addressed by OBO Operations Committee during a OFOC call and voted on.

The last remaining issue we need to determine is **what should happen when an ontology does not pass the dashboard**. I propose the following for now:

1. The [dashboard overview table](http://dashboard.obofoundry.org/dashboard/index.html) is split in two, "passing" and "not passing".
2. The https://obofoundry.org/ ontology overview gets a clear visual separation between passing and not passing ontologies. (we can discuss the details of that in a separate issue, for now, lets just agree first that we should do this. Examples of clear visual separation are: (1) prominent display of a dashboard badge, (2) sort order that favours passing the dashboard over other features, (3) a shading of the rows containing passing ontologies in a prominent colour, etc etc.).

These two are in my opinion the minimal ways in which we can enact this change. We can revisit the introduction of more severe ones (e.g. hiding non-passing ontologies from the default view) later if necessary. Ideally, other services like Ubergraph and OLS will also implement schemes to favour passing ontologies, maybe we can promote that as well as further incentive.

What do you think?

**Comment by matentzn** [comment]
Personally, I think the 6 year grace period with huge red X's on the dashboard, and all ontologies already have a OBO Dashboard badge on their site: https://obofoundry.org/ontology/cob.html. But yeah, if there is a majority that wants this a bit more gentle I guess we can wait a bit longer. Just for the record, we have given 3-4 presentations about the OBO Dashboard and told people about the deadline (Town Hall, Ontology Summit, ICBO Workshops); we will add this as a major item to the newsletter as well.

**Comment by pfabry** [comment]
I think the passing/not passing dichotomy is too coarse. Some red crosses are redder than others, and splitting the dashboard along those lines would put in the same category an ontology that can't be reasoned on with one that has multiple labels for a term (Granted, multiple labels is an easy fix and shouldn't be a problem). 
I would lower the threshold on what is passing, but I would be more strict when an ontology fails it (cf. issue #2348 )
Ultimately the question is what is the purpose of the OBO Foundry? Is it a biomedical ontologies repository or a biomedical ontologies standard organization ? Because IMHO it can't be both.

**Comment by matentzn** [comment]
> I think the passing/not passing dichotomy is too coarse. 

We do need some kind of threshold to develop "carrots and sticks".

> Some red crosses are redder than others, and splitting the dashboard along those lines would put in the same category an ontology that can't be reasoned on with one that has multiple labels for a term (Granted, multiple labels is an easy fix and shouldn't be a problem).

It's true that some crosses are redder than others. But we have with year long deliberation set a very very small bar for stuff that is _fail_. I think we can debate certain determinations on a case-by-case basis. Maybe we need to relegate some tests that are currently "errors" to "warning" - and I 100% think this should be done.

> I would lower the threshold on what is passing, but I would be more strict when an ontology fails it (cf. issue https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2348 )

Yes, but on a test by test basis. Right now, what is considered an error has been determined by the OBO operations committee in the last year as _minimal_. If you see specific red things you do not want to be considered as errors, you should report them on individual issues.

> Ultimately the question is what is the purpose of the OBO Foundry? Is it a biomedical ontologies repository or a biomedical ontologies standard organization ? It can't be both in my opinion, and I think there is a bit of "schizophrenia" right now between the standards we enforce for the new ontologies (which is a good thing) and the ones we adopt for the ontologies already accepted.

I think we are and should be the latter - a standards organisation. Our goal should be to promote standard practices and make ontologies more interoperable. Some of us also are ontology providers and build repositories, but that is separate from the OBO mandate. I believe we should consider ourselves a bottom up standard body.

**Comment by balhoff** [comment]
OFOC call 2023-07-11: we will make an active effort to work through the principles (dashboard columns) and reach out the the ontologies that need help.

**Comment by matentzn** [comment]
Action item for next OFOC call:

1. Formally agree that the above will happen.
1. Decide if a colour scheme or a badge scheme should be used to "highlight favourably"
1. Assign a suitable developer if @erik-whiting is unable to do this (@erik-whiting, would you consider to implement this for the first of January 2024?)

We can then close this issue with the result of the decision.

**Comment by handemcginty** [comment]
During the meeting on 8/22/23

Everyone agreed to:

- Highlight passing ontologies favourably on the OBO Foundry front page: It was suggested that we can use both a color (maybe white for passing and gray for ontologies that failed) and add a badge to note that an ontology passed. Noone opposed the idea of having both.
- Sort them to the top of each domain (default grouping by domain remains the same).
- Nico will sort out the assignment of a suitable developer.
