### ISSUE TITLE
Links to OntoBee fail to land at appropriate page

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#2362]
For example, if looking at the Foundry page for CL, clicking the OntoBee link (blue rounded rectangle) first sends to https://ontobee.org/browser/index.php?o=cl, which then forwards to https://ontobee.org/ontology/cl%3f (doesn't work).

While the issue can be fixed at the OntoBee end (cc: @yongqunh), it would actually be a bit cleaner to go directly to the landing page for the ontology in OntoBee, the URL of which is the same as the forwarded-to destination without the trailing '%3f'. That is, the generalized URL will be https://ontobee.org/ontology/<ontology prefix in lowercase>

**Comment by nataled** [comment]
Yes, I tried about half a dozen.

**Comment by erik-whiting** [comment]
Jumping on this, I think it should be an easy fix. Can either of you just confirm for me real quick that this is the right page for the example CL?
![image](https://github.com/OBOFoundry/OBOFoundry.github.io/assets/47164199/10ccd621-2982-4cd7-aa30-1b039d30d632)

**Comment by nataled** [comment]
@erik-whiting Yes, that's it. Thanks!

**Comment by erik-whiting** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2364

**Comment by erik-whiting** [comment]
I merged #2364, can someone confirm this issue is fixed and then close it if so
