### ISSUE TITLE
Question about MIREOT and two closely related domain ontologies

### ISSUE THREAD

**Issue by ddooley** [OBOFoundry/OBOFoundry.github.io#2379]
Pitched here in OBO because its a general pattern question that we've encountered with other ontologies.  In an application ontology we are creating a phenotype hierarchy for functional behaviour arising from virus mutations.  We're reusing terms from two closely related ontologies, PHIPO and VIDO:

<img width="319" alt="image" src="https://github.com/OBOFoundry/OBOFoundry.github.io/assets/4000582/bee729a4-3df7-4403-ada2-c2eaff64448b">

I'm mindful of the recommendation not to place one ontology's term under the hierarchy of another, for possible logical issues. Yet we want to express "viral load" (increasing or decreasing phenotype) is a subclass of "pathogen host interaction phenotype" in our application ontology.  Which ontology should we turn to to resolve this? 

Questions:

A) Its not ok to ask that PHIPO import "viral load" and subclass it under "pathogen host interaction phenotype"? 
C) Its not ok for VIDO to import PHIPO down to "pathogen host interaction phenotype" and subclass "viral load"?
D) That suggests one of them should mint the new necessary child or parent, and the other to deprecate their version?  Do we have to have them sort out essentially a partial merger before we can position their terms? Yet that can take years, so what do we do right now?

Thanks for advice!

**Comment by nlharris** [comment]
Has this been answered sufficiently?

**Comment by ddooley** [comment]
Yes, thanks!
