### ISSUE TITLE
License recommendation for ECO

### ISSUE THREAD

**Issue by mchibucos** [OBOFoundry/OBOFoundry.github.io#239]
Previously ECO license was CC BY-SA 2.0 (instituted when we were developing on Google Code). Chris Mungall has recommended CC-BY, per OBO Foundry guidelines. Is it a problem to keep it the slightly more restrictive CC BY-SA 2.0, as I tend to favor the ShareAlike model. Please advise. If it is _not_ recommended, can someone with more expertise in licensing please explain why, i.e. implications for reuse, etc.? Thank you! See here: https://github.com/evidenceontology/evidenceontology/issues/65

**Comment by cmungall** [comment]
Looks like ECO is now CC-BY, closing this.
