### ISSUE TITLE
OAE purl does not resolve

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#240]
Currently redirects to SF

http://purl.obolibrary.org/obo/oae.owl --> http://svn.code.sf.net/p/oae/code/trunk/src/ontology/oae.owl

SF appears to be down... temporarily? Move to GH essential if OAE is to stay here

**Comment by yongqunh** [comment]
It was temporary. It works now.
Yes. We should consider moving OAE to GitHub.
Thanks,
Oliver
