### ISSUE TITLE
Communicate with member ontologies about how to pass Open Principles on Dashboard

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2401]
@lschriml suggests we should have a specific effort to get people fixing the principles in preparation for #2360.

OFOC largely agrees.

- We should publish this stuff in newsletter. 
- We should send messages to people that are not-compliant and offer them concrete guidance on how to be "more open".

The message should mention the 01. January 2024, but should be written in `carrot` rather than `stick` language.

**Comment by nlharris** [comment]
can i make the title of this issue more descriptive? like, "Communicate to OBO Community how to follow the principles (before 2024-01-01)."
(BTW, who decided that Jan 1 is a good deadline for anything? Do we really want people frantically editing their ontologies on Dec 31, and are we really going to check them on Jan 1? Or do we assume that most people will correctly surmise that this is actually a soft deadline and that nothing is going to be checked before Jan 2, 3, 4...?)

**Comment by matentzn** [comment]
Feel free to rename issue. No it's an arbitrary date - you won't fix anything in the Christmas holidays, the idea is you have that done months earlier!

**Comment by matentzn** [comment]
I think we know now that we have a Spotlight on principles in ever newsletter, and that we provide some instructions on how to deal with Dashboard failures. So many ontologies have already fixed up their stuff!
