### ISSUE TITLE
Principle #9 "Users" what can be considered valid/validatable evidence?

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#2402]
Summarizing from #2281

During the 2023-03-07 OFOC meeting @matentzn suggested that we document once and for all what exactly constitutes an acceptable evidence for the Usage Principle:
 -     Principle should be more explicit that the description field for a usage metadata entry includes a concrete way to verify that terms of the ontology are being used in the particular external resource
 -   Can be verified by PR review of metadata steward; if there is question, can be brought to OBO operations meeting

Question from EWG: What concrete ways were mentioned? Do they differ from the Recommendations already provided in the principle? NOTE: Much of the existing text has already been modified to make things more explicit, but it's unclear if the changes are satisfactory.

**Comment by matentzn** [comment]
I think I got my wires crossed with some of your edits: https://obofoundry.org/principles/fp-009-users.html

This looks actually pretty good to me. TBH its not worth iterating on this further, I would say lets close both issues now and come back to it when a concrete lack of text is being identified. (Originally I think some people wanted to make the guidelines stricter on what counts as usage, but that is a bit of an orthogonal issue).

**Comment by matentzn** [comment]
I added a [sentence here](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2404) to the metadata stewards specific SOP, so that they don't forgot to consult the principle when evaluating the evidence level of a proposed documentation for a usage.
