### ISSUE TITLE
Proposal: improve the user experience on the front page

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#241]
I personally loathe the Wall Of Text (WOT) on the front page:

<img width="1195" alt="screen shot 2016-03-31 at 4 32 14 pm" src="https://cloud.githubusercontent.com/assets/50745/14193938/310898f0-f75e-11e5-928d-6e82f2578f2d.png">

I vote for either:
1. Showing only the 1st line and allowing the curious user see the full WOT with a "more" button that expands in place
2. Replacing this with a concise mission statement or similar, with the WOT available on a separate About page
3. Redesigning the front page to be a modern text-light splash screen with clear links to obtain the various pieces of information currently in the WOT

3 would obviously take a bit more effort

Indicate preference below, with `0` for the status quo, let's say `(-10,10)`, e.g
1. -10
2. +2
3. +2
4. +10

**Comment by jamesaoverton** [comment]
I put the WOT there, but I agree that it's too much. What's option 4 that you gave +10 preference points?

**Comment by cmungall** [comment]
It's secret!

Actually no, I obviously don't know how to count from zero. As a long standing advocate of zero-based genome coordinates and the non-US system of ground floor == 0, I am ashamed..

**Comment by jamesaoverton** [comment]
Ok, now I get it.

0. (status quo) -5
1. -3
2. +3
3. +5 (or +10 if somebody else does all the work)

**Comment by mchibucos** [comment]
-8, -5, +2, +10
not sure I have any business voting on this, but I was drawn in by this WOT discussion.

**Comment by cstoeckert** [comment]
Need to create an About OBO Foundry page for the Wall of Text

**Comment by nataled** [comment]
The last part of this WOT refers to a non-working email: obo-discuss@sourceforge.net (it bounces). However, obo-discuss@lists.sourceforge.net seems to work. Shouldn't we be directing users to obo-discuss@googlegroups.com though? Instructions to post to sourceforge also appears here:

http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

**Comment by cmungall** [comment]
Yes we should. This illustrates that even we don't read the WOT, given no
one has noticed til now.

**Comment by cmungall** [comment]
The incorrect email address was fixed in its own ticket: #1047 

We shouldn't even be directing people to an email address, it's not like a help email, if people aren't subscribed it will bounce! If we want people to communicate with the list via email we need to direct people to the groups page to sign up!

**Comment by cmungall** [comment]
OK, given we don't have resources for a modern website, we will go with:

 * Replacing this with a concise mission statement or similar, with the WOT available on a separate About page

Any volunteers?

**Comment by nlharris** [comment]
no one volunteered?

**Comment by nlharris** [comment]
During the OBO Operations Meeting on 28-July-2020, we discussed this issue (too much introductory text on the obofoundry.og home page). @mellybelly and I volunteered to propose a more streamlined version. Please see https://docs.google.com/document/d/1_XwrUSGx8aGBIZ6fPXGxpilyfJGIKAP01izAbVpFIcM/edit for our proposed revsion (still in development). We propose to greatly shorten and simplify the text on the home page and create a new About page (as suggested by Chris above) with an edited version of the text that's currently on the home page. We can discuss this during the next meeting.

**Comment by nlharris** [comment]
I fleshed out the proposed text for the Home and About pages. (Formatting is in a mix of markdown and html--I think that's ok, but will of course check once it's published, and adjust as needed.)
I think it would be easier for the OBO Operations Committee to look at the proposed text on the google doc, since making detailed comments on a PR is fiddly, but if I don't hear any objections, I may just go ahead and make PRs.

**Comment by jamesaoverton** [comment]
@nlharris This was on the agenda for today's call, but I did a poor job as chair of allocating our time, and we did not get to it today. I apologize.

**Comment by nlharris** [comment]
The proposed text is here: https://docs.google.com/document/d/1_XwrUSGx8aGBIZ6fPXGxpilyfJGIKAP01izAbVpFIcM/edit
After it's approved, I'll do a PR (and then when it's merged I'll adjust any formatting as needed).

**Comment by nicolevasilevsky** [comment]
I read through the proposed text above and it looks great, thanks @nlharris and @mellybelly!
