### ISSUE TITLE
JSON-LD context does not expand as intended

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#2410]
https://purl.obolibrary.org/meta/obo_context.jsonld

We can't have trailing underscores on expansions (and have it behave as expected). Sorry, I don't make the rules

More context here:

- https://github.com/w3c/json-ld-syntax/issues/329

These would all have to be modified to be nested

```json
      "RO": {
         "@id": "http://purl.obolibrary.org/obo/RO_",
         "@prefix": true
      }
```

**Comment by matentzn** [comment]
@erik-whiting do you feel comfortable taking this on?

**Comment by cmungall** [comment]
There’s a few design decisions here. Do we continue my original path of
hacking this with Perl? Switch to a more robust approach with rdflib?

**Comment by cthoyt** [comment]
@erik-whiting see https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2483
