### ISSUE TITLE
adding a video for the Newsletter

### ISSUE THREAD

**Issue by LK112019** [OBOFoundry/OBOFoundry.github.io#2416]
@matentzn Could you please start adding a few bullet points for the OBO newsletter explaining the principles? Maybe a video!?
Thanks so much!

**Comment by nlharris** [comment]
Do we really need a video? I can write some bullet points.
I found this short talk by Nico: https://summerofknowledge.inf.unibz.it/aiovg_videos/obo-foundry-in-2021-operationalizing-open-data-principles-to-evaluate-ontologies-nicolas-matentzoglu/
but it doesn't play very well (it keeps pausing).

**Comment by matentzn** [comment]
I had already started making recordings, but they were a bit too noisy (I had the AC on). I will make 1, 2 for the newsletter!

**Comment by matentzn** [comment]
@anitacaron wrote a great section in the newsletter, so no video required.
