### ISSUE TITLE
Track information about edit files

### ISSUE THREAD

**Issue by cthoyt** [OBOFoundry/OBOFoundry.github.io#2422]
# Problem

Contribution to OBO foundry ontologies would be easier with two pieces of structured information (which basically never changes):

## Which file should I edit?

What is URL pointing to the "edit" file for the ontology. In ODK formatted ontologies, this is usually pretty obvious since it lives in `src/ontology/{NAME}-edit.{EXTENSION}` such as https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon-edit.obo for UBERON. However, some ontologies version control both e.g., an OBO flat file and an OWL file and don't make it clear which one should be contributed to.

## What format is the file?

What is the format of the edit file (OBO flat file format, Functional OWL, RDF/XML). This can't be inferred from the extension in all cases since ontologies encoded in Functional OWL often has `.owl` extension instead of `.ofn` (e.g., CL https://raw.githubusercontent.com/obophenotype/cell-ontology/master/src/ontology/cl-edit.owl)

This would be particularly helpful for making automated contributions.

# Solution

I propose adding a new optional field to the ontology metadata that would look like this:

```yaml
edit:
    path: src/ontology/apollo_sv-edit.owl
    format: ofn
```

Where format has to come from an enumeration (suggestions welcome on what the entries in this enumeration would be).

It's also up for debate whether the path should be relative within the repository or absolute with a URL. I prefer relative since the information about the repository is already available elsewhere in the schema and this is more robust towards changes in the name or organization of the repository.

Ideally, all OBO Foundry ontologies version control their ontology in a way such that it can be contributed to, so this annotation can cover 99% of OBO Foundry ontologies. One caveat pointed out by Nico is that some ontologies partially use curation templates, which means there could potentially be multiple places to contribute. In these cases, hopefully there are carefully written contribution guidelines from the maintainers!

## How to accomplish this

I can volunteer to do the following:

1. Update the schema
2. Add unit tests
3. Write a script that infers this information where possible and automatically add it to the correct metadata markdown files
4. Update website format to show this information (if desired)

# Afterthoughts

My personal goal is to make it easier to automate contributing high-quality semantic mappings curated in [Biomappings](https://github.com/biopragmatics/biomappings) to upstream ontologies. I've already started writing a workflow in https://github.com/biopragmatics/biomappings/pull/149 and made a contribution in https://github.com/obophenotype/uberon/pull/2950, but this requires a lot of manual configuration (which I would like to structure and upstream into OBO Foundry with this proposal)

More generally, this kind of annotation makes it more transparent for OBO Foundry ontologies how to contribute, which is already implicit in the [OBO Foundry Principle 10 "Commitment to Collaboration"](https://obofoundry.org/principles/fp-010-collaboration.html)

**Comment by matentzn** [comment]
I think this is a good idea. Two caveats:

1. Some ontologies (e.g. VBO, OBA, UPHENO, OBI, and others) are partially or mainly curated using template TSVs, which means it may not always be clear where a PR would be made. In this sense, there are multiple editors sources.
2. Curating this information will require a significant about of manual labour.

**Comment by cmungall** [comment]
I worry about packing too much information in to the OBO metadata here.

**Comment by cthoyt** [comment]
I understand why the OBO operations group might be hesitant. Unfortunately, most repositories in OBO Foundry don't have a CONTRIBUTING.md. Further, most ontologies are unresponsive to any proactive updates to include more information from the ground up (remember how slow https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2149 was, even when we made PRs?). Therefore I am still leaning towards central ways of curating this kind of content. Maybe it ends up in the Bioregistry, but then it's sad since it is not directly available to potential OBO Foundry website readers

**Comment by matentzn** [comment]
Just to say my piece here: Edit files are constantly changing. Ontologies like Uberon, CL, OBI, and Mondo have dozens of edit sources. They change on a quarterly basis (new components are added, others removed). I doubt we can realise this beautiful heaven you have in mind where there is a single file we can have a bot make edits to reliably. At best we can have that for core ontology metadata like license/description, but if we are restricted to that sort of metadata, the value of curating all the edit files becomes too low IMO..
