### ISSUE TITLE
AfPO

### ISSUE THREAD

**Issue by Melek-C** [OBOFoundry/OBOFoundry.github.io#2461]
### Title

African Population Ontology

### Short Description

An ontology who describes the African population

### Description

AfPO is a tool which enables to annotate the African individuals, and brings together knowledge accumulated about existing populations with their genetic fingerprint in a standardized format. The AfPO can be employed to comprehensively classify African study participants in prospective research studies. It can also be used to classify study participants of past studies, by mapping participants using a language or ethnicity identifier or synonyms.

### Identifier Space

AfPO

### License

CC0

### Domain

organisms

### Source Code Repository

https://github.com/h3abionet/afpo

### Homepage

https://github.com/h3abionet/afpo

### Issue Tracker

https://github.com/h3abionet/afpo/issues

### Contribution Guidelines

https://github.com/h3abionet/afpo/blob/main/CONTRIBUTING.md

### Ontology Download Link

https://github.com/h3abionet/afpo/archive/refs/heads/main.zip

### Contact Name

Melek Chaouch

### Contact Email

mcmelek@msn.com

### Contact GitHub Username

Melek-C

### Contact ORCID Identifier

0000-0001-5868-4204

### Formats

- [X] OWL RDF/XML (.owl)
- [x] OBO (.obo)
- [x] OBO Graph JSON (.json)

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [x] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [X] My identifiers (classes and properties IRIs) are formatted according to the [OBO Foundry Identifier Policy](http://obofoundry.org/id-policy)
- [X] My term labels are in English and conform to the OBO Foundry [Naming Conventions](http://obofoundry.org/http://obofoundry.org/principles/fp-012-naming-conventions.html)
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, in English, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [x] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [x] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [x] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by pfabry** [comment]
Dear @Melek-C , 

Thank you for your submission. The review will be executed as a two stage process. 

- First, you will have to pass the new ontology precheck, including the [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check _apart from `Users` may be red_.
- After you have successfully passed these verfications, you will be assigned an OBO Operations committee member to review the ontology.

Usually, the review will result in an opportunity for you to improve the ontology. When the reviewer believes the ontology is ready for presentation to the OBO Operations Committee, they will present your ontology during an OBO Operations Call. This gives other members of the committee the opportunity to assess your work.

When a decision is reached by the committee you will be informed here on the issue tracker. The process can take any number of weeks or months, depending on the case at hand. Please inform us about any reasons you might have for increased urgency. You will be informed once your ontology is loaded in the OBO NOR Dashboard.

Good luck!

**Comment by pfabry** [comment]
@Melek-C 

As you are using ODK for developing your ontology you should do a release `make prepare_release`, because the released ontologies (afpo-full.owl, afpo-base.owl, etc.) in your repository are currently empty. The `src/ontology/afpo-edit.owl` file is for developers use only.
In addition, you should finalize the pre-registration checklist.
Thank you.

**Comment by Melek-C** [comment]
Dear @pfabry,

Here the relase: https://github.com/h3abionet/afpo/releases/tag/v2023-10-30

Thank you

**Comment by pfabry** [comment]
Dear @Melek-C,

Thank you for the update. Could you please also finalize the preregistration checklist ? To do this, you may wish to consult ontologies such as [ENVO](https://github.com/EnvironmentOntology/envo) or the [Gazetteer subset](http://ontologies.berkeleybop.org/gaz.owl), which have classes and instances for geographic and geopolitical entities such as countries or regions.

**Comment by Melek-C** [comment]
Thank you @pfabry! 
It should be ok with the preregistration checklist.
Please do not hesitate to conatct me in case of issues.
Best

**Comment by pfabry** [comment]
@Melek-C ,

Your ontology has been added to the [NOR dahsboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html) and has passed the technical review. @lschriml has been assigned as reviewer. Thank you.

**Comment by lschriml** [comment]
Following the review SOP: http://obofoundry.org/docs/SOP.html#ROOM

I have identified a number of items to be worked on for this review process: 

-- Not sure the reason, but the files (e.g., afpo.owl (1.1 M), afpo-full.owl, afpo.obo) is not loading easily in Protege, taking 10-20 minutes to load. And then Protege is freezing. 
I checked that this was not a Protege issue, and my doid.owl file, which is 15x larger, loads in seconds. 

1. Ontology Scope
      As stated in this ticket: AfPO is a tool which enables to annotate the African individuals, and brings together knowledge accumulated about existing populations with their genetic fingerprint in a standardized format. The AfPO can be employed to comprehensively classify African study participants in prospective research studies. It can also be used to classify study participants of past studies, by mapping participants using a language or ethnicity identifier or synonyms.
     **Domain**: is listed as Phenotype. 
                    I do not see how the content of this ontology 
                    The 'environment' or 'organisms' domain may be a better fit.

2. Terms with the new ontology prefix.
       --> All terms follow the correct OBO identifier scheme
                "http://purl.obolibrary.org/obo/AfPO_0000089
    - [ ] TODO --     Check to see if there are terms in other OBO Foundry ontologies that could be reused 
                                here. ENVO and GAZ were mentioned in a previous comment.
3. Correct use of imported terms
       - no imports included 
4. **Basic review of axiomatic patterns:**
       -- The formatting of the axioms seems fine.

                  The axioms are built to define 'Population_group' or 'Country of Origin' using AfPO relation terms
 - [ ] TODO -- utilize the Relation Ontology, RO, terms to define axioms

5. **Appropriate use of object properties**
       Two upper level classes, Continent and Population.
          For each Class, I would expect to see, in addition to label, Annotations for ID, definition, 
          obo_namespace 

 - [ ] TODO  **Definition formatting**: should follow standard formatting. Beginning with the parent term.
            E.g., the definition for Eastern Africa (AfPO:0000188), which currently begins with: 
                        People living in: Birundi OR Cosmoros OR Djibouti OR 
               The definition sentence structure should be grammatically correct.
               This definition could begin: 
                      A population which includes people living in Birundi, Cosmoros or Djibouti ...

       This ontology is using the **property "see Also"** for sources of the Class data/information. 
           http://www.w3.org/2000/01/rdf-schema#seeAlso

                        --> I would expect to see this kind of information under 'definition_source'

- [ ] TODO -- Consult IAO (Information Artifact Ontology)  https://www.ebi.ac.uk/ols4/ontologies/iao
        There are many **AfPO specific properties,** e.g., AfPO:0000152, which is annotated 
                         with a PubMed URL.
           Instead of the AfPO property, the ontology could use hasDbXref
               e.g., AfPO:0000566 which looks to be used for synonyms

- [ ] TODO. - review duplications in property annotations:
             Class labels:            
        In the afpo.owl file: 
            for:  http://purl.obolibrary.org/obo/AfPO_0000010
             I am seeing what looks like duplications of the label annotation: 
                            <obo:AfPO_0000569>Central Africa</obo:AfPO_0000569>
                                              <rdfs:label>Central Africa</rdfs:label>

            - [ ] TODO -- Please identify if both annotations are needed



6. Responsiveness to fixing changes.
        - as seen in this ticket, the AfPO developers are responsive in a timely fashion.

Regards,
Lynn Schriml

**Comment by Melek-C** [comment]
Dear @lschriml,

Thank you very much for your valuable comments, we will be back to you as soon as possible.

Best,
Melek

**Comment by Melek-C** [comment]
Dear @lschriml,
The Ontology Scope was changed to Organisms.
Were are going to work on the axiomatic patterns on in the next steps.
For the remaining comments "Issues" were post on the AfPO repository:
- https://github.com/h3abionet/afpo/issues/16
- https://github.com/h3abionet/afpo/issues/15

Best Regards

**Comment by matentzn** [comment]
@lschriml please advice on the process of AfPO.

**Comment by lschriml** [comment]
Hello Nico,So far I have not received any updates. I will ping the developers.Cheers,LynnSent from my iPhoneOn Mar 4, 2024, at 12:01 AM, Nico Matentzoglu ***@***.***> wrote:﻿
@lschriml please advice on the process of AfPO.

**Comment by Melek-C** [comment]
Hi @lschriml @pfabry and @matentzn, we are done with the ontology updates please find the link to the last release: https://github.com/h3abionet/afpo/releases/tag/v2024-03-21

Best,
Melek

**Comment by lschriml** [comment]
Great, thank you Melek !!

**Comment by lschriml** [comment]
@melek-C 
Hello Melek,
  Thank you again for your ontology submission to the OBO Foundry. We are happy to inform you that your ontology (African Population Ontology, AfPO) has been accepted following discussion in the OBO Operations Committee meeting (April 02, 2024). 

Please complete the following steps to add your ontology to the OBO ontology registry. 

Create a metadata record for your ontology to be included in the registry:

Create a new file in https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology, called AdPO.md (there is an “Add file” button in the top right).
Obtain the already curated metadata that relates to your ontology from https://github.com/OBOFoundry/obo-nor.github.io/blob/master/dashboard-config.yml (you’ll need to scroll down to locate yours; it will have your prefix in the “ - id:” field.)
Create a pull request to add the metadata record. This pull request should include a link to this issue (the New Ontology Request issue).
Here is an example record for the PATO ontology: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/pato.md?plain=1

Your metadata will be reviewed and merged by a member of the OBO Foundry Operations Committee. Permissible content for fields is being documented [here](https://obofoundry.org/faq/permissible-metadata-content.html).

To create a PURL registry entry for your ontology:

Go to https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config, click “Add file” and add a file named AfPO.yml.
Add the desired configuration.
Make a pull request with a link to this issue See here for an example of a PURL yml file: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pato.yml “
Cheers,
Lynn

**Comment by Melek-C** [comment]
Hello everyone,

Glad that the ontology is officially accepted into OBO.
I think that we should plan a meeting to do the final step and discuss our next moves.
Waiting for you availability.

Best,
Melek

Melek Chaouch (Phd)
Postdoctoral Fellow
Institut Pasteur de Tunis
H3ABioNet Node Ambassador
***@***.***
***@***.***
Address: 13, Place Pasteur-B.P 74
1002 Tunis Belvédère

________________________________

**Comment by lschriml** [comment]
Hello Malek,  Can you join the next OBO Operations call on April 30th ?Cheers,LynnSent from my iPhoneOn Apr 17, 2024, at 6:57 AM, Melek-C ***@***.***> wrote:﻿
Hello everyone,



Glad that the ontology is officially accepted into OBO.

I think that we should plan a meeting to do the final step and discuss our next moves.

Waiting for you availability.



Best,

Melek



Melek Chaouch (Phd)

Postdoctoral Fellow

Institut Pasteur de Tunis

H3ABioNet Node Ambassador

***@***.***

***@***.***

Address: 13, Place Pasteur-B.P 74

1002 Tunis Belvédère



________________________________

From: lschriml ***@***.***>

Sent: Tuesday, April 16, 2024 5:21 PM

To: OBOFoundry/OBOFoundry.github.io ***@***.***>

Cc: Melek-C ***@***.***>; Assign ***@***.***>

Subject: Re: [OBOFoundry/OBOFoundry.github.io] AfPO (Issue #2461)





@Melek-C<https://github.com/Melek-C>

Hello Melek,

Thank you again for your ontology submission to the OBO Foundry. We are happy to inform you that your ontology (African Population Ontology, AfPO) has been accepted following discussion in the OBO Operations Committee meeting (April 02, 2024).



Please complete the following steps to add your ontology to the OBO ontology registry.



Create a metadata record for your ontology to be included in the registry:



Create a new file in https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology, called AdPO.md (there is an “Add file” button in the top right).

Obtain the already curated metadata that relates to your ontology from https://github.com/OBOFoundry/obo-nor.github.io/blob/master/dashboard-config.yml (you’ll need to scroll down to locate yours; it will have your prefix in the “ - id:” field.)

Create a pull request to add the metadata record. This pull request should include a link to this issue (the New Ontology Request issue).

Here is an example record for the PATO ontology: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/pato.md?plain=1



Your metadata will be reviewed and merged by a member of the OBO Foundry Operations Committee. Permissible content for fields is being documented here<https://obofoundry.org/faq/permissible-metadata-content.html>.



To create a PURL registry entry for your ontology:



Go to https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config, click “Add file” and add a file named AfPO.yml.

Add the desired configuration.

Make a pull request with a link to this issue See here for an example of a PURL yml file: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pato.yml “

Cheers,

Lynn

**Comment by Melek-C** [comment]
Dear @lschriml,

We just created the afpo.md and afpo.yml files.

Best,
Melek

**Comment by jamesaoverton** [comment]
The PURL config has now been merged: https://github.com/OBOFoundry/purl.obolibrary.org/pull/990

**Comment by Melek-C** [comment]
Thank you @jamesaoverton !
