### ISSUE TITLE
CIO Confidence Information Ontology discussion 

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#248]
The OBO Operations committee needs to contact Frederic Bastian to discuss inclusion of CIO into the OBO Library. 
Bjoern and Alan: can you please with Frederic. 
@alanruttenberg @bpeters42 

**Background: **a response from Frederic: [provided by Darren]
Dear OBOFoundry,
thank you for your feedback (and for the feedback from an anonymous 
reviewer who probably follows this list).
We have updated the ontology (URL reminder: 
https://github.com/BgeeDB/confidence-information-ontology): we now distinguish between 'confidence information elements', and 'confidence information statements', the latter being pre-composed terms using the 'CI elements'; we also have added object properties to relate 'CI statements' to 'CI elements' (draft documentation: 
https://github.com/BgeeDB/confidence-information-ontology/wiki/ontology-design). 
 	This raises several questions:

1) It seems to me that the 'CI elements' might be in the scope of IAO or OBI (mostly IAO I think?).
Would it be possible to get feedback from some OBI/IAO folks, to see if we can improve the declarations for these 'CI elements'?

2) Object properties to relate 'CI statements' to 'CI elements': We use 3 types of 'CI elements', and a 'CI statement' can be related to at most one element of each type. We have thus defined 3 object properties to point to these element types, and one parent object property: 'has confidence element', 'has confidence level', 'has evidence concordance', and 'has evidence type concordance'.
Looking at the RO, I can't find any object property similar to these concepts. 
Would you have suggestions of existing relations that we could use?

3) Object property to order confidence levels:
We have created an object property 'provides_greater_confidence_than' to order confidence levels. Is there any existing relation suitable for this, or should we keep it that way in the CIO?
I would appreciate any remark you may have.
Thank you for your help,
Best regards,
Frederic.

**Comment by cmungall** [comment]
cc @fbastian

**Comment by bpeters42** [comment]
Sorry, I am confused by this. Is there another thread in which CIO
inclusion in the OBO library is requested? And in that context a 'reviewer'
responded with questions such as this? I thought we would just accept
people into the OBO library? I certainly did not object.

If the goal is to get alignment of CIO as existing with OBI / IAO, then it
would also need to be aligned even more urgently with ECO. And given that
OBI/IAO is not yet perfectly aligned with ECO either, this seems to be an
unrealistically high bar to impose?

- Bjoern

On Tue, Apr 19, 2016 at 8:12 AM, lschriml <notifications@github.com> wrote:

> The OBO Operations committee needs to contact Frederic Bastian to discuss
> inclusion of CIO into the OBO Library.
> Bjoern and Alan: can you please with Frederic.
> @alanruttenberg <https://github.com/alanruttenberg> @bpeters42
> <https://github.com/bpeters42>
>
> **Background: **a response from Frederic: [provided by Darren]
> Dear OBOFoundry,
> thank you for your feedback (and for the feedback from an anonymous
> reviewer who probably follows this list).
> We have updated the ontology (URL reminder:
> https://github.com/BgeeDB/confidence-information-ontology): we now
> distinguish between 'confidence information elements', and 'confidence
> information statements', the latter being pre-composed terms using the 'CI
> elements'; we also have added object properties to relate 'CI statements'
> to 'CI elements' (draft documentation:
>
> https://github.com/BgeeDB/confidence-information-ontology/wiki/ontology-design).
>
> This raises several questions:
>
> 1) It seems to me that the 'CI elements' might be in the scope of IAO or
> OBI (mostly IAO I think?).
> Would it be possible to get feedback from some OBI/IAO folks, to see if we
> can improve the declarations for these 'CI elements'?
>
> 2) Object properties to relate 'CI statements' to 'CI elements': We use 3
> types of 'CI elements', and a 'CI statement' can be related to at most one
> element of each type. We have thus defined 3 object properties to point to
> these element types, and one parent object property: 'has confidence
> element', 'has confidence level', 'has evidence concordance', and 'has
> evidence type concordance'.
> Looking at the RO, I can't find any object property similar to these
> concepts.
> Would you have suggestions of existing relations that we could use?
>
> 3) Object property to order confidence levels:
> We have created an object property 'provides_greater_confidence_than' to
> order confidence levels. Is there any existing relation suitable for this,
> or should we keep it that way in the CIO?
> I would appreciate any remark you may have.
> Thank you for your help,
> Best regards,
> Frederic.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OBOFoundry/OBOFoundry.github.io/issues/248>
>



-- 
Bjoern Peters
Associate Professor
La Jolla Institute for Allergy and Immunology
9420 Athena Circle
La Jolla, CA 92037, USA
Tel: 858/752-6914
Fax: 858/752-6987
http://www.liai.org/pages/faculty-peters

**Comment by mchibucos** [comment]
I agree with Bjoern's comments. FYI, ECO and CIO recently kick-started our
prior discussions.
- Marcus

**Comment by fbastian** [comment]
Sorry, I missed this github notification. Hopefully I'm on time before the ECO/OBI meeting ;)

The reply you quoted includes responses addressing comments from an anonymous reviewer of the CIO paper (www.ncbi.nlm.nih.gov/pubmed/25957950). I thought it would be relevant to our discussion.

As Marcus said, we'd like CIO to be a community effort, that could be part of the ECO framework. I'd really like to know what other OBO folks think about the principles underlying the ontology, described in the paper (notably, the concept of summarizing several lines of evidence under a same confidence statement).

**Comment by zhengj2007** [comment]
The CIO has been registered to OBO and its PURLs have been set.

See: http://www.obofoundry.org/ontology/cio.html

**Comment by jamesaoverton** [comment]
The PURLs for CIO aren't quite finished. I'd like @fbastian to get back to me about this Pull Request: https://github.com/OBOFoundry/purl.obolibrary.org/pull/201

**Comment by zhengj2007** [comment]
Sorry. I missed it.

**Comment by fbastian** [comment]
The PURLs correctly redirect to berkeleybop, but at this moment I have a 404 not found error for these links: 
http://www.berkeleybop.org/ontologies/cio.owl
http://www.berkeleybop.org/ontologies/cio.obo

**Comment by jamesaoverton** [comment]
@fbastian: There are currently some problems with the berkeleybop.org server. However your PURLs are now live (e.g. <http://purl.obolibrary.org/obo/cio.owl>), and they redirect to GitHub, not to berkeleybop.org. Does that solve your problem, or do you rely on <http://www.berkeleybop.org/ontologies/cio.owl>?

**Comment by cmungall** [comment]
See http://obofoundry.org/faq/what-is-the-build-field.html

@fbastian - you don't need this or the central obo build server as you 
make your own owl

AFAICT the server itself is absolutely fine. However, if you don't see 
your owl being built there there may be an issue with your build flag or 
your ontology. The only way to see this at the moment is the jenkins 
job. 
http://build.berkeleybop.org/job/simple-build-obo-all/lastBuild/consoleFull 
(large, sorry)

**Comment by jamesaoverton** [comment]
@cmungall: Sorry, I saw a related bug report and over-generalized. Thanks for clarifying.

**Comment by fbastian** [comment]
Hmm, I only find: 

    Thu Jun  9 01:08:35 PDT 2016 :: Missing obo or owl files for cio

**Comment by jamesaoverton** [comment]
@fbastian: These are the official PURLs and they are working for me:

- http://purl.obolibrary.org/obo/cio.owl
- http://purl.obolibrary.org/obo/cio.obo
- http://purl.obolibrary.org/obo/cio/cio-simple.obo

If there's still a problem, please let us know, and describe the problem as precisely as possible.

**Comment by fbastian** [comment]
OK, I thought I needed to investigate a problem with the ontology. Everything looks fine, thanks.
