### ISSUE TITLE
Add a FAQ item about submitting tickets

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#249]
For many people it may not be clear how to make requests regarding specific ontologies - adding new terms, asking questions etc.

We should have something in the FAQ about "how do I make requests to an ontology". On the OBO call we decided to use RO as an example

**Comment by jamesaoverton** [comment]
@zhengj2007 Sorry, I forgot that you were assigned to this, so I went ahead to make a Pull Request. You can use it as an example of adding a FAQ.

**Comment by jamesaoverton** [comment]
Close by 439f48b260c87f382ea005db62160402d2a3b701
