### ISSUE TITLE
Website updates: dashboard status indicator

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2499]
in #2360 we have determined how to indicate OBO Dashboard status on the OBO Foundry front page table:

> Highlight passing ontologies favourably on the OBO Foundry front page: It was suggested that we can use both a color (maybe white for passing and gray for ontologies that failed) and add a badge to note that an ontology passed. Noone opposed the idea of having both.
Sort them to the top of each domain (default grouping by domain remains the same).
Nico will sort out the assignment of a suitable developer.

@erik-whiting has agreed to implement this.

Concretely I would suggest the following three interventions:

- [ ] Shade all rows on the front page https://obofoundry.org/ in a light, but visible, gray tone where the ontology is not passing the dashboard
- [ ] Sort ontologies to the top of each group where ontologies are passing the dashboard (sort order: first dashboard pass status, second alphabetical).
- [ ] See if we can somehow without creating an eye-sore add the OBO Foundry dashboard passing badge:

<img width="258" alt="image" src="https://github.com/OBOFoundry/OBOFoundry.github.io/assets/7070631/6cd75b1c-dedf-4687-8b4f-18f626216b36">

I think we may have to create a simplified version of this with just green and yellow (pass, or not) without the details on errors to fit. I think this can go underneath the license in the re-use column. @erik-whiting you can see on the ontology specific pages like https://obofoundry.org/ontology/bfo.html how to add these dynamically.

- [ ] I would like, optionally, to have a checkbox (off by default) "Hide Failing QC" which can be used to filter the view for only those ontologies that actually pass the test.
- [ ] Make the Dashboard badge we currently have on the ontology specific pages more prominent / central.

The central results are here:

https://github.com/OBOFoundry/obo-dash.github.io/blob/gh-pages/dashboard/dashboard-results.yml

**Comment by matentzn** [comment]
@jsstevenson this is the corresponding issue.

**Comment by nlharris** [comment]
Should we unassign Erik from this (and other issues)?
