### ISSUE TITLE
Decide what to do about legacy pages

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#25]
The old http://obofoundry.org site had a lot of pages that haven't been touched since 2007ish

These are currently in the navbar under "LEGACY"

I suggest removing forever

**Comment by cmungall** [comment]
The exception is id-policy, this is already migrated, see #1

**Comment by nlharris** [comment]
There's still a lot of stuff in the Legacy menu--maybe it's time to retire some of it?

**Comment by nlharris** [comment]
It would be good if legacy pages (e.g. http://obofoundry.github.io/legacy/participate.html) were visibly designated as such, perhaps with something in the header.
