### ISSUE TITLE
Update the list of members of the Editorial Working Group

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2549]
https://obofoundry.org/docs/EditorialWG.html

It seems many people on that WG are not member anymore, like @lschriml and @wdduncan, so it would be good to go through the motion to update this list so we know who to contact when @nataled is out of office.

**Comment by nataled** [comment]
I usually remove those people who've explicitly stated that they can no longer serve, and dropped the ball only for Chris Stoeckert. Everyone else is, technically, still part of the EWG as far as I'm concerned. I can whittle it down to those that are active, but this is very difficult to pin down for some who tend to join only occasionally. For that, I'd include myself, Bill Hogan, and (very occasionally) Hande.

**Comment by nataled** [comment]
Sorry, I responded incorrectly. I don't edit the members on the indicated page. It's actually not even possible from there. What I edit is the membership of the mailing list. So far as I can tell, the editing would have to be on something called "site.data.operations.members".

That being said, there are definitely more members receiving messages than are active. From time to time I send an email to those still getting them to check if they want to cease participation. I'll run that again.

**Comment by nataled** [comment]
Oh, the current list of those that still get emails (and haven't complained about it) are:
Me
Bill Hogan
Hande
Lynn
Bjoern

**Comment by wdduncan** [comment]
Hi @nataled. Sadly, I am not able to participate in the EWG. You can remove me from the list.

**Comment by nataled** [comment]
Found the source document: operations.yml
#2551 removes the currently known set of Ops members that have indicated non-participation. Others that are not active but chose to stay in the loop are still included, pending response to my query email.

**Comment by nataled** [comment]
@wdduncan thanks, I already have you as non-participant in terms of the mailing list. But the list in question is something else. My (failing) PR already removes you from the list in question.

**Comment by wdduncan** [comment]
Thanks @nataled

**Comment by nataled** [comment]
PR is failing with the messages:

<html><body>
<div class="mt-1 mb-3 px-3">
          <div class="mx-0 mx-md-1">
            <h2 class="text-bold h4">Annotations</h2>
            <div class="color-fg-muted text-small">1 error and 2 warnings</div>
          </div>
        </div>
        
 
--



                      <a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/OBOFoundry/OBOFoundry.github.io/actions/runs/8348583161/job/22851047148">
                          <strong>test</strong>
                        
                      </a>
                      <div class="color-fg-muted">
                        <div data-target="annotation-message.annotationContainer" class="text-small text-mono annotation--expanded">
                          <div>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/</div>
                        </div></div>
</body>
</html>

@matentzn @anitacaron any ideas? Looks like something global is the problem.
