### ISSUE TITLE
Consider JOSS as a model for how to do ontology review

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#256]
@balhoff alterted me to the Journal of Open Source Software 
http://joss.theoj.org/

I believe we should consider this kind of lightweight open review system for OBO (or it could be generalized to all ontologies, with OBO being a layer on top).

I like how they are leveraging github for this. There are a lot of technical similarities to how we manage metadata (e.g. markdown for narrative text with structured YAML metadata in the header)

Note the entire journal workflow system appears to itself be in github, and can thus be forked and adapted. In theory we could do this. Would need adapting as we would not be minting JOSS DOIs (we could use versioned purls here, or have our own DOI block).

**Comment by selewis** [comment]
+1

**Comment by lschriml** [comment]
Note: Editorial group reviewed this previously, we determined that our review process needs to be finalized first, we are not at this time ready to implement this software.

**Comment by balhoff** [comment]
@lschriml @cmungall are there any existing notes on plans for a new review process? I think it would be great if something like the JOSS system could be implemented.

**Comment by nataled** [comment]
This appears to be something that might be appropriate only for the initial part of the review process (the self review), which is when the submitter answers a series of questions regarding metadata and adherence to principles.

**Comment by balhoff** [comment]
By the way, here's a recent extended description of the system: https://peerj.com/articles/cs-147/

**Comment by mellybelly** [comment]
Hi all, 
JOSS is very well regarded in our community and will be a primary feature of our work on software citation and attribution in our new Center for Data to Health, as well as the Software Sustainability institute. I think that it would be a fantastic idea to use for ontologies, which in some ways are even more amenable to such an approach. I would be in high favor of such an approach for the Foundry. +1000

@kristiholmes may be interested in commenting.
