### ISSUE TITLE
How to obtain the gene annotations of the ontology file

### ISSUE THREAD

**Issue by mumdark** [OBOFoundry/OBOFoundry.github.io#2566]
Thank you for your sharing platform!

My question is, **how to obtain the gene annotations of the ontology file on the OBO Foundry**? For example, AKR1C4, AKR1D1 belongs to the PW:0002168 pathway,

**Comment by nataled** [comment]
Hi @mumdark,

Thanks for your question. Unfortunately, you will not be able to obtain gene annotations *within* an ontology file. Certain ontologies are used to annotate genes, though, so you will be able to obtain the annotations by looking within gene or protein databases. [UniProtKB](https://www.uniprot.org/) is a good place to start, as is [GOA](https://www.ebi.ac.uk/GOA/index).

Best regards,
Darren Natale

**Comment by mumdark** [comment]
> Hi @mumdark,
> 
> Thanks for your question. Unfortunately, you will not be able to obtain gene annotations _within_ an ontology file. Certain ontologies are used to annotate genes, though, so you will be able to obtain the annotations by looking within gene or protein databases. [UniProtKB](https://www.uniprot.org/) is a good place to start, as is [GOA](https://www.ebi.ac.uk/GOA/index).
> 
> Best regards, Darren Natale

Thanks for your reply, best regards!
mumdark
