### ISSUE TITLE
help updating my affiliation on OBO Foundry membership page

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#2575]
My affiliation is out of date but it's not obvious to me how to update it in GitHub, can anyone help?

@mellybelly and @mbrush may want to update their affiliations too.

Thanks!

**Comment by rays22** [comment]
@nicolevasilevsky , I think you can update [your affiliation](https://obofoundry.org/docs/OutreachWG.html) in the file [operations.yml]( https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml).

**Comment by nicolevasilevsky** [comment]
Thank you @rays22!
