### ISSUE TITLE
Strengthen need to have capitalised ID space prefixes

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#2596]
We just admitted an ontology #2461 which has a lower case letter in the ID space. Since we do have a few mixed case ID prefixes this is not a disaster, but moving forward we should make sure that all new idspaces are simply capitalised, to make it easier for tools to process them. I think we should:

1. Strengthen https://obofoundry.org/principles/fp-003-uris.html#recommendations-and-requirements which says "should generally be capitalized" to "all newly requested prefixes MUST be capitalised.
2. Add a note to this to the Ontology reviewer docs.

**Comment by wdduncan** [comment]
Personally, I prefer that we require upper case moving forward. I creates less hassle (IMHO).

**Comment by ddooley** [comment]
In favour of simplification wherever we can, and caps IDs would be a small gesture in this way in uniformity.

**Comment by lschriml** [comment]
Human readability was also discussed on the call.

**Comment by shawntanzk** [comment]
My preference is also all upper or all lower. I can't remember where but I have had to write around this before, which is not a problem, just slightly annoying :)

**Comment by matentzn** [comment]
Very important note towards @hoganwr comment above: there are two distinct concepts in OBO: 

1. Preferred prefixes for CURIEs. `http://purl.obolibrary.org/obo/NCBITaxon_123` is the IRI, `NCBITaxon:123` is the CURIE, and `NCBITaxon` is the _prefix_.
2. Ontology ids. These are _always lowercase_. An `ontology id` in this case is a string that allows us to look-up an ontology on the obofoundry website, for example, or the "ontology id part" of the purl string, like: `ncbitaxon` in `http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxonslim.owl` or `https://obofoundry.org/ontology/ncbitaxon.html`. 

This situation is of course very confusing. Truth be told, the ideal, cleanest solution would be to make absolutely everything lowercase, but that ship has sailed (by sailed I mean "the effort of changing that infrastructure is in no relation to the benefit on the other end). If we start mandating lowercase prefixes from new ontologies, our tools like ODK need to be updated, a completely new thing is being introduced that was not there before (i.e. `http://purl.obolibrary.org/obo/ncbitaxon_123` - we did have upper and mixed case, but never lower case in PURLs). 

I will include this option in the vote, but I am not volunteering to enacting that change (everything lowercase) if it then gets the most votes!

## Vote

👍: I think we should mandate capitalized prefixes for new ontologies. This is in line with some of the current assumptions of standard tools (ODK etc), it makes it easier to "guess" the correct capitalisation (less "hassle"), and creates "some level of uniformity", at least for future ontologies.
👎: I think we should not mandate capitalized prefixes and allows mixed case prefixes like NCBITaxon. This is in line with historical decisions (there are a number of mixed case prefixes in OBO already) and this makes prefixes more readable for humans (example "_Af_rican _P_opulation _O_ntology" --> AfPO).
👀 : I think we should, since we are creating a new rule, go all in, despite the large effort involved and the lack of a precedence, and mandate an _all lowercase_ solution for future submissions. This will unify the concepts of "ontology ID" and "CURIE prefix".

**Comment by rays22** [comment]
The vote will be closed on 31th of May, 2024.

**Comment by matentzn** [comment]
The vote is now closed (no more changes will be accepted):

<img width="1023" alt="image" src="https://github.com/OBOFoundry/OBOFoundry.github.io/assets/7070631/88b8bbe1-65f3-42a0-8460-700284b1e966">

The majority is mandating upper case prefixes _moving forward_. Thanks for the vote.

@nataled I made this edit here #2605 to close this issue.
