### ISSUE TITLE
Organize documentation

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#26]
Our documentation is spread in multiple places: 
1. On the old obofoundry.org site, mostly stale. See: #25
2. On the wiki running at berkeley, http://wiki.obofoundry.org/wiki/index.php/Main_Page (the principles are here) 
3. On the obo operations google code wiki. See #23
4. In the obo operations google drive https://drive.google.com/drive/u/0/folders/0B8x6Blq96uycalZvM1BLRjJmb2c - mostly meeting notes, but other stuff too
5. other google docs. E.g. I see lots of outreach meeting notes but no parent folder shows up for me

In addition to being spread out, much of it is confusing and stale.

I recommend consolidating as much as possible into github pages - meeting agendas and notes are best left in google docs, but for anything else, one place.

There is an argument to use the github wiki for some purposes, this has some advantages over jekyll/gh pages: easier to create new pages (but how often do we do that?), slightly easier to interlink. My vote would still be for pages

**Comment by cmungall** [comment]
Most of this is done. Some tidying would still be good but removing this from the 1.0 milestone as it's good enough for release

**Comment by nlharris** [comment]
What still remains to be done, and who could do it?

**Comment by nlharris** [comment]
can we close this?

**Comment by nlharris** [comment]
since this is 5 years old and the documentation has been changed extensively since then, i'm going to close it, and if there are still improvements to be made in documentation, new ticket(s) can be opened.
