### ISSUE TITLE
Minor tweaks to last two columns in ontology table on home page

### ISSUE THREAD

**Issue by nlharris** [OBOFoundry/OBOFoundry.github.io#2611]
The new home page ontology table looks amazing! 🙌

I have some suggestions for the last two columns (discussed in Slack with @nataled):
- [ ] The second-to-last column is labeled "Re-Use", but it contains both the dashboard results and the license. Keep the license, remove the dashboard results, and relabel the column "License".
- [ ] Add a new column with the dashboard result badges, with the column header "QC"
- [ ] Remove the not-very-useful "Social" column (see https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2408 where this was already requested)

@jsstevenson

**Comment by nlharris** [comment]
Currently it looks like this:
![Screenshot 2024-06-20 at 11 45 17 AM](https://github.com/OBOFoundry/OBOFoundry.github.io/assets/348704/b219a50b-ec05-43bc-b9b5-436f70f877d3)

**Comment by jsstevenson** [comment]
>  The second-to-last column is labeled "Re-Use", but it contains both the dashboard results and the license. Keep the license, remove the dashboard results, and relabel the column "License".

Might be less of an issue with the pending work over on the dashboard to slim down to badge width, but the original intent here was to avoid packing in too many columns. Agree that the current configuration is imperfect, though.

**Comment by matentzn** [comment]
I personally dont agree with suggestions two (add column makes the table too wide) and three (removing the social column should be done independently of this question here). What about renaming the "Re-use" to "Interoperability" or "OBO Principles"? Both the Dashboard checks and the license pertain to that..

**Comment by nlharris** [comment]
> add column makes the table too wide

Add one, remove one, relabel one! But, ok, fair point that removing the social column should be a separate decision.

> What about renaming the "Re-use" to "Interoperability" or "OBO Principles"?
