### ISSUE TITLE
Request for new OBO ontology HED (Hierarchical Event Descriptors)

### ISSUE THREAD

**Issue by VisLab** [OBOFoundry/OBOFoundry.github.io#2612]
### Title

Hierarchical Event Descriptors

### Short Description

A system for annotating experimental time lines

### Description

HED (Hierarchical Event Descriptors) is a standardized vocabulary for describing what happens during experiments and a framework for mapping these terms and other metadata onto the experimental timeline to enable analysis.  HED is a subtag system organized by the top-level categories: `Event`, `Agent,` `Action`, `Item`, `Property`, and `Relation`. Users create HED annotations as comma-separated, parenthesized lists of terms. See [https://www.hed-resource.org](https://www.hed-resource.org) for documentation, tutorials and other resources.

Recently we have created an ontology representation of the HED vocabulary (HED schema) to provide a better mechanism for linking the HED terms to terms from other ontologies and to provide better provenance information. While the HED ontology currently has few links to other OBO ontologies, we have an internal table of potential relationships which can be added in the future.

The HED tags as well as auxiliary information such as types of units and types of values are represented as classes. The HED schema attributes are represented either as `DataProperty` or `ObjectProperty` depending on their range. Some additional attributes that are not inherited are represented as `AnnotationProperty`.

HED is the standard used for event annotation in [BIDS](https://bids.neuroimaging.io/) (Brain Imaging Data Structure) a standard for storing neuroimaging repository and is used by datasets on several repositories such as [openNeuro](https://openneuro.org/) and [Nemar](https://nemar.org//).

### Identifier Space

HED

### License

CC0

### Domain

investigations

### Source Code Repository

https://github.com/hed-standard

### Homepage

https://www.hedtags.org

### Issue Tracker

https://github.com/hed-standard/hed-schemas/issues

### Contribution Guidelines

https://github.com/hed-standard/hed-schemas/blob/main/CONTRIBUTING.md

### Ontology Download Link

https://raw.githubusercontent.com/hed-standard/hed-ontology/main/hed.owl

### Contact Name

Kay Robbins

### Contact Email

kay.robbins@utsa.edu

### Contact GitHub Username

VisLab

### Contact ORCID Identifier

0000-0002-7147-5797

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### Dependencies

-iao
-dc
-foaf

### Related

Most closely related terms are from NCBI thesaurus. We have identified a few potential links to IAO, GSSO, UBERON, OMIT, SIO, MFOEM, PATO, STATO, NBO.

The partOf schema attribute can be identified with Part-of BFO:0000050.

### Usages

```yaml
- user: https://bids.neuroimaging.io/
  description: "BIDS uses HED as its annotation standard for events."
  examples:
    - url: https://bids-specification.readthedocs.io/en/stable/appendices/hed.html
      description: "Specification of how HED annotations work in BIDS."
- user: https://nemar.org/
  description: "NEMAR repository automatically generates summaries for datasets that are HED annotated."
  examples:
    - url: https://nemar.org/dataexplorer/detail?dataset_id=ds003645
      description: "Word cloud visualization generated based on HED tags.
```

### Data Sources

Literature, dictionary, Wikipedia, expert interviews.

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [X] My identifiers (classes and properties IRIs) are formatted according to the [OBO Foundry Identifier Policy](http://obofoundry.org/id-policy)
- [X] My term labels are in English and conform to the OBO Foundry [Naming Conventions](http://obofoundry.org/http://obofoundry.org/principles/fp-012-naming-conventions.html)
- [X] I understand that term definitions are key to understanding the intentions of a term, especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology--and all top level terms--have definitions, in English, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by cmungall** [comment]
This looks like a very practical vocabulary and it would be great to map the terms to OBO ontologies. However it is quite different from a lot of existing OBO ontologies. Are you sure you want to register with OBO rather than with Bioportal?

For example, you have a lot of classes that have equivalents in OBO

- Anatomical-item: UBERON
- Organism: NCBITaxon
- Action: NBO
- Language Item: IAO
- Sensory-attribute: sensory perception branch of GO

These have axioms that would render them hard to use in other OBO ontologies:

`Animal SubClassOf HedEntity and (inHedSchema exactly 1 HedSchema)`

You have some unique concepts in the neuro-cognitive domain, e.g. those under Task-property, it would be good to figure a way to include these in the relevant place in OBO

**Comment by VisLab** [comment]
I think we need your advice on what the best way to proceed.  We would like to have the HED ontology registered somewhere appropriately.  A goal of HED is to present an easy-to-use view of needed terminology for annotators and analysts. We have read over the OBO documentation and are not completely sure what the consequences of becoming an OBO ontology are -- particularly after we put in the equivalencies (from our internal spreadsheet) to terms in OBO (particularly NCBITaxon). I can see that the equivalencies may lead to some downstream issues with the `HedSchema` structure elements.  

If we register with Bioportal does that preclude registration with OBO.  Is there some other direction we should consider?

**Comment by cmungall** [comment]
Registering with Bioportal doesn't preclude registering with OBO at some later date, and is a great option for many vocabularies!

You may want to consider putting mappings in as simple skos annotations; you are right that when you put in equivalence axioms you start getting conflicts or unusual assertions. 

The OBO team will also put the ontology into the OBO dashboard to give a more formal analysis, you can consider my comments less formal general advice.

**Comment by shawntanzk** [comment]
Hi @VisLab, as @cmungall mentioned, we will place this in the OBO dashboard which has some automated checks that could be of help. @pfabry - could you help with this please. From here you will get a report on some items that need to be addressed before we consider registering this ontology to the OBO foundry. However, as @cmungall  mentioned, you are can first place this in places like Bioportal to start and it definitely does not preclude registration with OBO foundry in the end, in fact many OBO foundry ontologies are also in Bioportal :) do feel free to reach out here if you have any other questions.

**Comment by anitacaron** [comment]
Hi @VisLab, you can check the OBO NOR Dashboard results [here](https://obofoundry.org/obo-nor.github.io/dashboard/hed/dashboard.html)

**Comment by anitacaron** [comment]
@VisLab Please note that there's another step that runs a lexical matching tool to check for lexical overlap with existing OBO ontologies. The results will be available soon after 22 July.

**Comment by pfabry** [comment]
@VisLab 
The result of the lexical matching is available here:
[HED lexmatch 20240723.txt](https://github.com/user-attachments/files/16350400/HED.lexmatch.20240723.txt)
Please note that classes and properties' URI need to follow the OBO Foundry [standard](http://obofoundry.org/id-policy).

**Comment by pfabry** [comment]
Hi @VisLab
Your ontology was discussed at the last OBO operations call. Unfortunately, we believe that your ontology cannot be accepted in its current state in the OBO Foundry. In fact, as the lexical match shows, its [scope is too broad, not clearly delineated](http://obofoundry.org/principles/fp-005-delineated-content.html) and overlaps that of several core ontologies of OBO.
You may want to consider registering your ontology with [Bioportal](https://bioportal.bioontology.org/) instead. We are closing this issue, but please feel free to let us know if you have questions.
