### ISSUE TITLE
Request for new ontology [FATO]

### ISSUE THREAD

**Issue by gmparg** [OBOFoundry/OBOFoundry.github.io#2620]
### Title

Food Allergen Traceability Ontology

### Short Description

An ontology that captures information on food products, allergens, and related management and traceability processes

### Description

FATO includes the following main entities:  products and product batches, allergens, allergen declarations, tests, allergen management, food safety, consumer groups, label claims, and nutrition information.

The overall motivation for the development of FATO is to help food businesses improve food allergen management. This motivation is primarily linked to three main needs/use cases: (1) capture essential food product information required by food safety regulations; (2) identify common operational errors in food allergen management; (3) facilitate automation of food data exchange between businesses.

FATO imports a subset of the FoodOn ontology, a subset of the Global Product Classification (GPC) and the EPCIS 2.0 ontology.

Intended users of FATO include the following: (1) internal auditors who are responsible for auditing the compliance with food safety requirements at a production site; (2) food production operators; (3) food product and recipe developers.

### Identifier Space

FATO

### License

CC-BY 4.0

### Domain

diet, metabolomics, and nutrition

### Source Code Repository

https://github.com/gmparg/FATO

### Homepage

https://gmparg.github.io/FATO/

### Issue Tracker

https://github.com/gmparg/FATO/issues

### Contribution Guidelines

https://github.com/gmparg/FATO/blob/main/CONTRIBUTING.md

### Ontology Download Link

https://gmparg.github.io/FATO/ontologies/FATO.owl

### Contact Name

George Bargiannis

### Contact Email

g.bargiannis@hud.ac.uk

### Contact GitHub Username

gmparg

### Contact ORCID Identifier

0000-0002-2118-5812

### Formats

- [X] OWL RDF/XML (.owl)
- [ ] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### Dependencies

foodon

### Intended Use Cases and/or Related Projects

SEEBEYOND project (https://consult.environment-agency.gov.uk/environment-and-business/seebeyond/)

Intended use cases include: (1) capture essential food product information required by food safety regulations; (2) identify common operational errors in food allergen management; (3) facilitate automation of food data exchange between businesses.

### Data Sources

Food safety regulators and food companies, food allergen management literature on historical food allergy recalls and common root causes, food product information forms in UK, Australia and New Zealand.

### Additional comments or remarks

The ontology has been submitted to the Journal of Web Semantics and is currently under review. The submission to OBO Foundry was actually a suggestion of reviewers of a previous version of the ontology.

### OBO Foundry Pre-registration Checklist

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [X] My identifiers (classes and properties IRIs) are formatted according to the [OBO Foundry Identifier Policy](http://obofoundry.org/id-policy)
- [X] My term labels are in English and conform to the OBO Foundry [Naming Conventions](http://obofoundry.org/http://obofoundry.org/principles/fp-012-naming-conventions.html)
- [X] I understand that term definitions are key to understanding the intentions of a term, especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology--and all top level terms--have definitions, in English, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [X] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by pfabry** [comment]
Dear @gmparg 
  
Thank you for your submission. The review will be executed as a two stage process: 
- First, you will have to pass [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check _apart from `Users` and `Versioning` may be red_.
- After you have successfully passed the Dashboard you will be assigned an OBO Operations committee member to review the ontology. _The assigned reviewer is to be considered the final arbiter of requirements_; look to that reviewer's guidance regarding which suggestions made by other reviewers must be done, which suggestions are simply good to do but not required, and which should not be done.
  
Usually, the review will result in an opportunity for you to improve the ontology. When the reviewer believes the ontology is ready for presentation to the OBO Operations Committee, they will present your ontology during an OBO Operations Call. This gives other members of the committee the opportunity to assess your work.
  
When a decision is reached by the committee you will be informed here on the issue tracker. The process can take any number of weeks or months, depending on the case at hand.
Please let us know about any reasons you might have for increased urgency.
  
You will be informed once your ontology is loaded in the OBO NOR Dashboard.
  
Good luck!

**Comment by pfabry** [comment]
@gmparg 
In order to load your ontology in the dashboard, could you provide a link to a fully merged (no import) version?
