### ISSUE TITLE
MONDO download files no longer working

### ISSUE THREAD

**Issue by plweller3** [OBOFoundry/OBOFoundry.github.io#2629]
There appears to be a problem with the generated MONDO download files for the past few days.  The path:

http://purl.obolibrary.org/obo/mondo/mondo-with-equivalents.json

No longer resolves.  Nor does the link on the ontology page.  https://obofoundry.org/ontology/mondo.html

I’m contacting you since you are listed as the contact on the page.  If there is a different contact, please let me know.

Thanks!

Regards,

Phil Weller

**Comment by nicolevasilevsky** [comment]
cc @twhetzel @sabrinatoro

**Comment by matentzn** [comment]
@plweller3 Thank you for the report! The `mondo-with-equivalents` release was recently discontinued, see https://github.com/monarch-initiative/mondo/issues/7912.

I have opened #2630 to remove the erroneous link! Thanks a ton.

**Comment by plweller3** [comment]
Really, the only notice of this was a post in the Issues section?

Removing this file breaks a lot of ClinGen apps.

What are we supposed to use as a replacement?

**Comment by matentzn** [comment]
@plweller3 

Ahhhhh, that is very different situation - sorry about that! I didn't understand that you were a user of this file - I thought you mere stumbled across the documentation! In this case, we need to move this to the Mondo issue tracker! 

We will sort it out, dont worry - its not difficult to add this release back - we had asked  on the Mondo users list who needs this file, and didnt get a response..

In any case, will open a new issue in Mondo.

**Comment by matentzn** [comment]
Closing in favour of https://github.com/monarch-initiative/mondo/issues/8050, see you there @plweller3
