### ISSUE TITLE
Protect master branch?

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#264]
For our [PURL repository](https://github.com/OBOFoundry/purl.obolibrary.org) we've had some success using GitHub settings to "protect" the "master" branch, forcing most changes to go through the Pull Request mechanism and the Travis tests. I suggest using a similar approach on this repository.

**Comment by cmungall** [comment]
Seems OK. It will mean one extra step when regenerating site docs using 
`make`, but I think that's OK

**Comment by zhengj2007** [comment]
Sounds good to me.

**Comment by jamesaoverton** [comment]
I'm undecided about this. I want the process of making changes to be as simple as possible, so more people are confident in making changes by themselves.

For the PURLs, it's easy to break things in serious ways, but we also have pretty comprehensive tests. So requiring Pull Requests and Travis CI checks makes good sense.

I'm less sure about this site. We can preview changes on a local machine with `jekyll server` but I bet only Chris and I do that. There are also some automated tests. But local preview and the automated tests didn't catch bug #263, and a Pull Request requires at least one extra (somewhat confusing) step.

Any suggestions/opinions? If not, on second thought I'm leaning toward doing nothing, and I'll just close this issue in a couple of days.

**Comment by cmungall** [comment]
I suggest we do nothing until someone has the time (ha!) to write some 
behave tests for the front end. Otherwise we'd be adding an extra 
futzing step with no real gain.

The behave framework is very nice, I don't think it's too hard to get up 
and running, @kltm has lots of experience but we don't have the 
bandwidth right now

**Comment by kltm** [comment]
Travis machines are pretty straight-forward Ubuntu instances. Some notes from out behave setup for people new to (python) behave: https://github.com/geneontology/amigo/blob/master/test-app/behave/README.org . While we use Jenkins right now for our tests (github hook), Monarch uses xvfb in their travis for tests, which works quite well.

**Comment by cmungall** [comment]
Cloning the monarch setup may be easier then:
https://github.com/monarch-initiative/monarch-app/tree/master/tests/behave

**Comment by jamesaoverton** [comment]
Ok. We won't do anything about protecting the master branch right now, but we'll look into better automated tests: #265.

**Comment by cmungall** [comment]
I would like to reconsider this - we have a build fail on master just now

**Comment by jamesaoverton** [comment]
I'm now strongly in favour of protecting the master branch for any repo with more than two committers. The benefits are big and outweigh the minor inconveniences.

**Comment by nlharris** [comment]
sounds reasonable

**Comment by matentzn** [comment]
Agreed if we ensure that more than one person can unprotect it if necessary.

**Comment by jamesaoverton** [comment]
I looked into this, and it seems like this change was made but we forgot to close this issue.

The OBO-Admin Team has permission to change these settings. There are 22 people on that team (that membership list is not public, although I'm not sure why): https://github.com/orgs/OBOFoundry/teams/obo-admin

It turns out that branch protection was already on, but administrators (those 22 people) can override it by clicking a big red button. In my opinion this pretty much defeats the purpose, but on the other hand the preferred workflow for regenerating the derived files is to push them directly to `master`.

I'll close this issue now. If someone wants to propose a change, please also account for how the generated files should be updated.
