### ISSUE TITLE
AGRO Prefix/Domain creation request

### ISSUE THREAD

**Issue by celineaubert** [OBOFoundry/OBOFoundry.github.io#266]
Title: Agronomy Ontology

AGRO, the AGRonomy Ontology, describes agronomic practices, agronomic techniques, and agronomic variables used in agronomic experiments. AGRO is being built using traits identified by agronomists, the ICASA variables, and other existing ontologies such as ENVO, UO, and PATO, IAO, and CHEBI. Further, AGRO will power an Agronomy Management System and fieldbook modeled on a CGIAR Breeding Management System to capture agronomic data. 

- Download link: https://raw.githubusercontent.com/AgriculturalSemantics/agro/master/agro.owl
- Home page: https://github.com/AgriculturalSemantics/agro
- Contact: c.aubert@cgiar.org
- Mailing-list: https://groups.google.com/group/agronomyOntology
- Tracker link: https://github.com/AgriculturalSemantics/agro/issues
- PURL username: caubert

Best,
Céline Aubert

**Comment by cmungall** [comment]
Thanks Celine,

See #267 for your md file. This is a placeholder until the community has had time to comment. I took the liberty of suggesting a CC-BY license, if this is agreeable you may also want to add a LICENSE file to your gh repo

**Comment by celineaubert** [comment]
Thanks Chris for your answer and suggestion. I added a license section in the README of our gh repo.
