### ISSUE TITLE
How to pick an ontology domain?

### ISSUE THREAD

**Issue by DominikMartinat** [OBOFoundry/OBOFoundry.github.io#2660]
Hello everyone!

I am building ontology of [biological membranes and their models](https://github.com/DominikMartinat/membrane_ontology). Its should include terms useful for description and categorization of experimental and computational models used in biological membrane research. Terminology should allow for description of what are chemical components in membrane model and which type of biological membrane is modelled by it.

Intended use is annotation of membranes and their models in datasets and connecting the data where membranes are similar, or where the model simulates the relevant biological membrane. For example we would like to connect permeability data from [MolMeDB](https://molmedb.upol.cz/detail/intro) to relevant metabolic pathways in [WikiPathways](https://www.wikipathways.org/).

I would like to register the ontology in OBO foundry, but I don't know which domain to pick and I believe there is not clear definition of them. I am trying to decide between biological systems OR chemistry and biochemistry.

Biological systems make sense to me as membranes can be seen as dynamic systems consisting of different lipids, proteins and other molecules.

Chemistry and biochemistry would make sense as we deal with chemical composition of membranes and their models for description and similarity.

Any advice is welcome.

**Comment by ashkotin** [comment]
Hi Dominik! Let me vote for biological systems, as chemistry and biochemistry have methods for this kind of systems to work with.
Where is this list of domains?

**Comment by DominikMartinat** [comment]
Hi @ashkotin! When you start issue to add new ontology, there is form and part of it is list of domains and you must pick one of them. You can see the same if you go for [OBO foundry website](https://obofoundry.org/), where you can sort ontologies according to ontology domain. I will list them for convenience.

* agriculture
* anatomy and development
* biological systems
* chemistry and biochemistry
* diet, metabolomics and nutrition
* enviroment
* health
* information
* information technology
* investigations
* microbiology
* organisms
* phenotype
* simulation
* upper

**Comment by ashkotin** [comment]
looking at https://molmedb.upol.cz/detail/intro "chemistry and
biochemistry" would be better.

вт, 10 дек. 2024 г. в 12:23, DominikMartinat ***@***.***>:

**Comment by DominikMartinat** [comment]
Thank you. I got opinions from some other people that also think I should go for chemistry and biochemistry. I will leave the issue open for the rest of the day, in case someone will come up with good argument why it should be else where and if not, I will close it and send application to chemistry and biochemistry domain.
