### ISSUE TITLE
Contact information for FMA subset

### ISSUE THREAD

**Issue by cuboideum** [OBOFoundry/OBOFoundry.github.io#273]
The [page of the Foundational Model of Anatomy (subset)](http://obofoundry.github.io/ontology/fma.html) currently has contact information for Onard Mejino, giving the email address 'mejino@comcast.net'. This address does no longer exist.

According to the [FMA developers list](http://si.washington.edu/content/developers), an active address of Mr Mejino could be mejino@u.washington.edu.

Is Mr Mejino still the maintainer and how is he to be contacted?

**Comment by cmungall** [comment]
Thanks for pointing this out. You have the correct email, we'll update 
the record
