### ISSUE TITLE
Request FOODON Purl

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [OBOFoundry/OBOFoundry.github.io#277]
We'd like to request a new FOODON purl.  Here's the blurb:

**- Title: the title of the resource**
The FOODON food ontology project

**- Short description:**
A consortium of ontology developers has come together to do a broadly scoped food ontology to represent entities which bear a “food role”.  It encompasses materials in natural ecosystems and food webs as well as human-centric categorization and handling of food. The latter will be the initial focus of the ontology, and we aim to develop semantics for food safety, food security, the agricultural and animal husbandry practices linked to food production, culinary, nutritional and chemical ingredients and processes. 

**- Download link:**
https://raw.githubusercontent.com/FoodOntology/foodon/master/foodon.owl

**- Requested prefix:** 
FOODON

**- Home page:**
http://foodontology.github.io/foodon/

**- Contact:**
damion.dooley@bccdc.ca

**- Mailing-list**
https://groups.google.com/forum/#!forum/foodon-consortium/join

**- Tracker link**
https://github.com/FoodOntology/foodon/issues

**- PURL username:**
damion

**Comment by mcourtot** [comment]
Damon created md file in July, https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/foodon.md
