### ISSUE TITLE
A request for the GENEPIO Purl

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [OBOFoundry/OBOFoundry.github.io#278]
We'd like to request a new GENEPIO purl.  Here's the blurb for our DRAFT ontology.  Feedback welcome!  There may be some include file linking issues with live genepio.owl since they reference GENEPIO purl itself. 

**- Title: the title of the resource**
Genomic Epidemiology Ontology

**- Short description:**
The Genomic Epidemiology Ontology covers vocabulary necessary to identify, document
and research food-borne pathogens and associated outbreaks.

**- Download link:**
https://raw.githubusercontent.com/GenEpiO/genepio/master/genepio.owl

**- Requested prefix:** 
GENEPIO

**- Home page:**
http://genepio.github.io/genepio/

**- Contact:**
damion.dooley@bccdc.ca

**- Mailing-list**
https://groups.google.com/forum/#!forum/genepio/join

**- Tracker link**
https://github.com/GenEpiO/genepio/issues

**- PURL username:**
damion

**Comment by cmungall** [comment]
Looks like this was done. Apologies for leaving the ticket open

**Comment by mcourtot** [comment]
Sorry - my fault. I had asked Damion to create the PRs and merged them in but forgot to close. (this and FOODON).
