### ISSUE TITLE
include NCBO Bioportal as possible Ontology Browser, (and later the new OLS)

### ISSUE THREAD

**Issue by proccaserra** [OBOFoundry/OBOFoundry.github.io#28]
as per the discussion on OBO foundry operation call on August 11th, 2015.

**Comment by cmungall** [comment]
There is currently no way to do this globally as there is no deterministic procedure to translate an official OBO ontology id / IRI into a biioportal URL

In some cases we can guess:

 * upcase(uberon) = http://bioportal.bioontology.org/ontologies/UBERON *RESOLVES*

But this doesn't always work. Consider the obo library ontology fbbt (which uses FBbt as a prefix)

This has the bioportal URL: http://bioportal.bioontology.org/ontologies/FB-BT

However, it's possible to do this on a per-ontology basis. I will demonstrate with fbbt

**Comment by cmungall** [comment]
@mmc64 @dosumis do you approve of the 3 browsing options I added here: 
http://obofoundry.github.io/ontology/fbbt.html
(the 4 buttons on the main panel)

@proccaserra I'll leave this open pending decision / or until bioportal URLs have been added for all ontologies. Alternatively someone may want to reach out and figure out if they can resolve using our prefixes

**Comment by proccaserra** [comment]
@cmungall: +1 but should the OBOfoundry come with a specification/requirement for creating predictible variations (e.g.  use lc(OBOFoundry ontology prefix) or uc(OBOFoundry  ontology prefix) or concat(OBOF.OBOFoundry ontology prefix) ? 
I presume Bioportal needs to deal with other prefixes which may collided with OBOF ones.

**Comment by dosumis** [comment]
On Aug 11, 2015, at 7:22 PM, Chris Mungall <notifications@github.com> wrote:

> @mmc64 @dosumis do you approve of the 3 browsing options I added here: 
> http://obofoundry.github.io/ontology/fbbt.html
> (the 4 buttons on the main panel)
> 
> 
Looks good to me.

Have sent pull request to update details:

https://github.com/OBOFoundry/OBOFoundry.github.io/compare/master...dosumis:patch-1

Cheers,
David

**Comment by mmc46** [comment]
Looks good to me too. Thanks.

Marta

**Comment by cmungall** [comment]
@proccaserra I think we would recommend that any external resource not introduce arbitrary changes - e.g introducing a dash; need to uniquify across broader set understood but ideally we'd all coordinate on this, with other stakeholders like identifiers.org too to avoid situations like what we have now with an OBO ontology called GEO that has nothing to do with *the* GEO (NCBI)

**Comment by cmungall** [comment]
@dosumis you needed to make one more click to make it a bona fide PR, no worries I did it and merged the changes in

**Comment by cmungall** [comment]
cc @graybeal

**Comment by nlharris** [comment]
What's the status of this?

**Comment by graybeal** [comment]
The mapping Jennifer mentions in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/80#issuecomment-359910978 (and further documented in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/80#issuecomment-522160194) seems like the answer to the question above in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/28#issuecomment-130000219. Yes?

**Comment by nlharris** [comment]
So can this ticket be closed?

**Comment by nlharris** [comment]
closing, please reopen or create a new ticket if there are still things to be done on this.
