### ISSUE TITLE
add reference publication as annotation?

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#280]
I was trying to find the reference citation for CL at http://obofoundry.org/ontology/cl.html and couldn't - it would be useful to have an 'how-to-cite' property.
Somewhat related to #227, but I'm looking for the way the ontology authors want the resource to be cited rather than a citation of the github repo.

**Comment by nlharris** [comment]
CL doesn't list a publication, but (for example) Uberon does--see the "cite" items in the sidebar on http://www.obofoundry.org/ontology/uberon.html

So it seems like this is solved as a general thing, and the remaining to-do is to add a publication for CL?

**Comment by rvita** [comment]
also note that this is something we were working on for all ontologies as part of the metadata clean up & we just have not gotten to it yet.

**Comment by addiehl** [comment]
Probably the 2016 CL paper is the best recent paper to cite:
https://www.ncbi.nlm.nih.gov/pubmed/27377652

Alex
