### ISSUE TITLE
Request for 'SEPIO' purl / prefix

### ISSUE THREAD

**Issue by mbrush** [OBOFoundry/OBOFoundry.github.io#281]
**Ontology Title:** The Scientific Evidence and Provenance Information Ontology (SEPIO)

**Requested Prefix:** SEPIO

**Description:** The Scientific Evidence and Provenance Information Ontology (SEPIO) was developed to support the description of evidence and provenance information for scientific claims. The core model represents the relationships between claims, their lines of evidence, and the data items that comprise this evidence, as well as the methods, tools, and agents involved in the creation of these artifacts. SEPIO was initially developed to support the data integration and analysis efforts of the Monarch Initiative, where it provides a unified and computable representation of evidence and provenance metadata for genotype-phenotype associations aggregated across diverse model organism and clinical genetics databases. However, additional requirements were collected from diverse community partners in an effort to provide a shared community standard, with a core model that is domain independent and extensible to represent any type of claim and its associated evidence. In this report we describe the structure and principles behind the SEPIO model, and review its applications in support of data integration, curation, knowledge discovery, and manual and computational evaluation of scientific claims.  

**Download link:** 
http://github.com/monarch-initiative/SEPIO-ontology/blob/master/src/ontology/sepio.owl

**Home page:** 
https://github.com/monarch-initiative/SEPIO-ontology

**Contact:** Matthew Brush

**Mailing-list (if any):** 
none yet

**Tracker link:** 
https://github.com/monarch-initiative/SEPIO-ontology/issues

**Publication (if any):** Conference paper accepted for ICBO2016, but not yet 'published' (see "ICBO_2016_SEPIO_paper" in repo docs folder: https://github.com/monarch-initiative/SEPIO-ontology/tree/master/docs 

**PURL user name:** mbrush

**Comment by cmungall** [comment]
Seems like you can go ahead and add this @mbrush  - do you want to make the PR?

**Comment by mcourtot** [comment]
Hi @mbrush - do you want to create the PR for this? Or let me know if you need help doing so.

**Comment by cmungall** [comment]
pinging @mbrush

**Comment by mbrush** [comment]
closed with pr #442
