### ISSUE TITLE
Naming Conventions Link broken

### ISSUE THREAD

**Issue by heineroberkampf** [OBOFoundry/OBOFoundry.github.io#282]
At
http://www.obofoundry.org/principles/fp-012-naming-conventions.html 
the link
http://www.obofoundry.org/principles/Naming
does not resolve.
Where can naming conventions be found?

**Comment by cmungall** [comment]
Can't find the oldpage on wayback, just the parent

http://web.archive.org/web/20150828031534/http://wiki.obofoundry.org/wiki/index.php/FP_012_naming_conventions

I suggest removing this link. The conventions can be found in the paper (tho it would be nice to have a concise summary)
