### ISSUE TITLE
Request for PURL: PDRO

### ISSUE THREAD

**Issue by rtaseen** [OBOFoundry/OBOFoundry.github.io#283]
**Title:**
The Prescription of Drugs Ontology

**Requested prefix:**
PDRO

**Description**
PDRO is a realist ontology that aims to represent the domain of drug prescriptions. Such an ontology is currently missing in the OBOFoundry and is highly relevant to the domains of existing ontologies like DRON, OMRSE and OAE. PDRO's central focus is the structure of a drug prescription, which is represented as a mereology of informational entities. Our current use cases are (1) refining this structure (e.g., adding closure axioms, cardinality, datatype bindings, etc) for prospectively standardizing local electronic prescriptions and (2) annotating prescription data of differing EHRs for detecting inappropriate prescriptions using a central semantic framework. Future ontological work will include aligning PDRO more closely with the Document Acts Ontology.

**Download link:**
https://raw.githubusercontent.com/OpenLHS/PDRO/master/PDRO.owl

**Tracker:**
https://github.com/OpenLHS/PDRO/issues

**Homepage:**
https://github.com/OpenLHS/PDRO

**Contact:**
ryeyan.taseen@gmail.com

**PURL username:**
rtaseen

Paper accepted for ICBO 2016: not yet published.

**Comment by rtaseen** [comment]
bump
Is there anything missing in the request?
Do we need to register a PURL domain or is that done after review?
Thanks,
Ryeyan

**Comment by mcourtot** [comment]
Apologies for delay. PR at https://github.com/OBOFoundry/OBOFoundry.github.io/pull/332 waiting for second pair of eyes.
@cmungall, @jamesaoverton : can you review/merge?

**Comment by mcourtot** [comment]
Hi @rtaseen - the PR has been merged in and can be seen at http://obofoundry.org/ontology/pdro.html
I'm dealing with a few requests at the same time, and will update when the front page table has been updated and the PURL created.

**Comment by mcourtot** [comment]
hi @rtaseen : looking at the raw OWL file, https://raw.githubusercontent.com/OpenLHS/PDRO/master/PDRO.owl

Your URIs are of the form http://purl.obolibrary.org/obo/PDRO/PDRO.owl#PDRO_0000007; if you want to enable term by term retrieval/browsing you would need to switch to / based URIs, similar to ttp://purl.obolibrary.org/obo/PDRO_0000007 instead. See for example the URIs used in CVDO, https://raw.githubusercontent.com/OpenLHS/CVDO/master/cvdo.owl

**Comment by mcourtot** [comment]
Website all done - any problem please let me know.
Still waiting on PURL response re IRIs format; please follow up there.
