### ISSUE TITLE
Create a review-helper

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#288]
Foundry reviews are glacially slow. In the past they have also been subjective in areas where they should be objective.

We should make a review seeder. It would do things like
- lint check labels for naming conventions
- check for presence of license
- calc for % of definitions
- etc

These should then feed into a standard form for a review (my preference would be yaml). The reviews could then be annotated with subjective comments by reviewers

Much of this could be done with SPARQL, perhaps augmented with SHACL (cc @balhoff ). We do some of this already - e.g. check the license in the obo md conforms to what is declared in the ontology, see https://github.com/OBOFoundry/OBOFoundry.github.io/blob/dd5ef3e04d7bb85145a87da4595250d9b08e1508/Makefile#L108-L109

**Comment by nataled** [comment]
We strongly desire a way to conduct at least part of the reviews automatically, including what you list above. If you have pointers to tools that can do it, please do share. Otherwise, we need to develop them. And find people capable of doing so.

**Comment by cmungall** [comment]
Test run:

## SUCCESS
 * bfo
 * doid
 * go
 * po
 * zfa
 * cl
 * dpo
 * eco
 * envo
 * eo
 * fbbt
 * fbcv
 * fypo
 * ro
 * to
 * uberon
 * vto
## FAILS
 * chebi FAILS: ['license not CC-BY or CC-0', 'No real users'] *CONFLICT*
 * obi FAILS: ['No real users'] *CONFLICT*
 * pato FAILS: ['No real users'] *CONFLICT*
 * pr FAILS: ['No real users'] *CONFLICT*
 * xao FAILS: ['No real users'] *CONFLICT*
 * aeo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * aero FAILS: ['No tracker for community requests', 'No real users'] 
 * agro FAILS: ['No real users'] 
 * apo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * bcgo FAILS: ['No real users'] 
 * bco FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * bspo FAILS: ['No real users'] 
 * bto FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * caro FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * cdao FAILS: ['No tracker for community requests', 'No real users'] 
 * ceph FAILS: ['No real users'] 
 * cheminf FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * chmo FAILS: ['No real users'] 
 * cio FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * clo FAILS: ['No tracker for community requests', 'No real users'] 
 * cmf FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * cmo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * cro FAILS: ['No real users'] 
 * cteno FAILS: ['No real users'] 
 * cvdo FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ddanat FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ddpheno FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * dideo FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * dinto FAILS: ['No real users'] 
 * dron FAILS: ['No real users'] 
 * duo FAILS: ['No real users'] 
 * ehdaa2 FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * emap FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * emapa FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests'] 
 * epo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * ero FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * exo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * fao FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * fbbi FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * fbdv FAILS: ['No real users'] 
 * fix FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * flopo FAILS: ['No real users'] 
 * fma FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * foodon FAILS: ['No real users'] 
 * gaz FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * genepio FAILS: ['No real users'] 
 * geno FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * geo FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * hao FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * hom FAILS: ['No real users'] 
 * hp FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * hsapdv FAILS: ['No tracker for community requests', 'No real users'] 
 * iao FAILS: ['No real users'] 
 * ico FAILS: ['No real users'] 
 * ido FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * idomal FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * kisao FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * ma FAILS: ['license not CC-BY or CC-0'] 
 * mamo FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * mf FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * mfmo FAILS: ['No real users'] 
 * mfoem FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * mfomd FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * mi FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * miapa FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * micro FAILS: ['No tracker for community requests', 'No real users'] 
 * mirnao FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * miro FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * mmo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * mmusdv FAILS: ['No tracker for community requests', 'No real users'] 
 * mod FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * mondo FAILS: ['No real users'] 
 * mop FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * mp FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * mpath FAILS: ['No real users'] 
 * mro FAILS: ['No real users'] 
 * ms FAILS: ['No tracker for community requests', 'No real users'] 
 * nbo FAILS: ['No real users'] 
 * ncbitaxon FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ncit FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * ncro FAILS: ['No real users'] 
 * oae FAILS: ['No tracker for community requests', 'No real users'] 
 * oarcs FAILS: ['No real users'] 
 * oba FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * obcs FAILS: ['No real users'] 
 * obib FAILS: ['No real users'] 
 * ogg FAILS: ['No real users'] 
 * ogi FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ogms FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ogsf FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ohd FAILS: ['No real users'] 
 * ohmi FAILS: ['No real users'] 
 * olatdv FAILS: ['No tracker for community requests', 'No real users'] 
 * omiabis FAILS: ['No real users'] 
 * omit FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * omp FAILS: ['No real users'] 
 * omrse FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * ontoneo FAILS: ['No real users'] 
 * oostt FAILS: ['No real users'] 
 * opl FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * ovae FAILS: ['No tracker for community requests', 'No real users'] 
 * pco FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * pdro FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * pdumdv FAILS: ['No tracker for community requests', 'No real users'] 
 * plana FAILS: ['No real users'] 
 * poro FAILS: ['No real users'] 
 * ppo FAILS: ['No real users'] 
 * pw FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * rex FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * rnao FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * rs FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * rxno FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * sbo FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * sep FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * sepio FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * sibo FAILS: ['No real users'] 
 * so FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * spd FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * stato FAILS: ['No real users'] 
 * swo FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * symp FAILS: ['No real users'] 
 * tads FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * taxrank FAILS: ['No real users'] 
 * tgma FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * trans FAILS: ['No real users'] 
 * tto FAILS: ['No real users'] 
 * uo FAILS: ['No real users'] 
 * upheno FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * vario FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * vo FAILS: ['No real users'] 
 * vt FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * wbbt FAILS: ['license not CC-BY or CC-0', 'No real users'] 
 * wbls FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * wbphenotype FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * xco FAILS: ['license not CC-BY or CC-0', 'No tracker for community requests', 'No real users'] 
 * xl FAILS: ['No tracker for community requests', 'No real users'] 
 * zeco FAILS: ['No real users'] 
 * zfs FAILS: ['No tracker for community requests', 'No real users']

**Comment by nataled** [comment]
Here is a link to the Editorial Working Group discussion notes regarding principles that we (at the time) thought could (or not) be amenable to automated check:

https://docs.google.com/document/d/1cQwC1njphrXLiE514nSdVUYc1PTs5lTlvVeBKUM4vq0/edit

**Comment by cmungall** [comment]
made some comments on the google doc

**Comment by nlharris** [comment]
what is the status of this?

**Comment by nataled** [comment]
@nlharris I'd say it's basically done, as this is precisely what the dashboard was designed to do. @cmungall please confirm.

**Comment by nlharris** [comment]
i agree, the dashboard does this, and if there are specific points here that the dashboard doesn't yet cover, we should open new more specific ticket(s).
