### ISSUE TITLE
Deploy central OBO build to S3/cloudfront, and create howtos for ontologies wishing to use this mechanism

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#290]
Background: http://obofoundry.org/faq/what-is-the-build-field.html

The central build run by the berkeley jenkins job currently deploys to berkeleybop.org/ontologies

This should be changed to S3. Also, set up cloudfront CDN to make access fast from anywhere.

Just like the existing setup, this would be opt-out, or explicitly opt-in. Anyone can point their purls anywhere, but the fall-through would be to the cdn rather than berkelely. For opt-outters, we can provide howtos for anyone who wants to manage their own bucket.

To investigate
- this should be easy. We'll need a obo bucket. Just change the existing rsync to go to this bucket using s3cmd
- investigate compression options. The major mode of consuming these files will be via the OWLAPI.
- investigate options for versioning. glacier?

cc @kltm @jamesaoverton

**Comment by cmungall** [comment]
This is now done; see also #257

**Comment by cmungall** [comment]
Reopening as I realize we have this stale folder served from berkeley:
http://berkeleybop.org/ontologies/

Potentially confusing. Many people erroneously hardcoded these URLs rather than using the PURLs.

I will coordinate with @kltm to wipe this out. It may break some people's pipelines, but better to do this and force a fix than serve stale info.

**Comment by kltm** [comment]
Wiping that out as in taking it down? Is there anything in particular you want in its place?

**Comment by cmungall** [comment]
We should do a 301 to ontologies.berkeleybop.org

**Comment by kltm** [comment]
@cmungall 
Just to confirm that action, http://ontologies.berkeleybop.org is likely going to be a cranky AWS XML message of some kind. Are you okay with that, or do you want us to create an index there, or at least an html page explaining that people need to update?

**Comment by kltm** [comment]
Well, looking at it, it *does* seem to be a bucket list, so it is informational if nothing else...

**Comment by cmungall** [comment]
Yes, am OK with this. There is no need for anyone other than us to be able to browse the directory.

**Comment by kltm** [comment]
@cmungall 
Right, top-level taken care of, what about things like: 
```
    RewriteRule ^/ontologies/\w+/about/(\w+)_([A-Za-z0-9\-]+) http://www.ontobee.org/browser/rdf.php?o=$1&iri=http://purl.obolibrary.org/obo/$1_$2
    RewriteCond %{REQUEST_URI} !^/ontologies/.*/ro_bfo_bridge1_1
    RewriteRule ^/ontologies/(\w+)_([A-Za-z0-9\-]+) http://purl.obolibrary.org/obo/$1/about/$1_$2  [R=303,L]
```
Keep? Remove? Redirect?

**Comment by cmungall** [comment]
Can we temporarily kill and test some class purls? I'm sure it's 
killable

**Comment by kltm** [comment]
All rules mentioned above (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/290#issuecomment-275563447) are killed.

**Comment by cmungall** [comment]
all good it seems
