### ISSUE TITLE
Minting of new URIs in Wikidata

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#298]
Wikidata mints new URIs for entities.
Consider 
https://www.wikidata.org/wiki/Q14331103, NMDA glutamate receptor clustering
vs
http://purl.obolibrary.org/obo/GO_0097114, NMDA glutamate receptor clustering

**Comment by goodb** [comment]
Yes.  And this is 100% unavoidable given the scope of its mission. Wikidata
(meaning the people that work on it like us) will do its best to maintain
alignment between the concepts and URIs within it and relevant
corresponding nodes in other parts of the semantic web such as the obo
purls.  Hopefully the obo community will help to maintain those
relationships, therebye benefiting from the powerful interlinkage provided
by the wikidata knowledge graph.

**Comment by Public-Health-Bioinformatics** [comment]
I'm looking at what Wikidata has for this term, its definition, and its parent/ancestor classes, and what GO has.  Seems they are identical.  I appreciate Wikidata combining different ontologies under one roof - in the same way that I appreciate OBOFoundry / OLS / Ontobee etc. gathering them together for consistency.  Technically - for these different curation efforts that are making use of each others resources on a 1-to-1 concept/term basis - I would advocate use of originating curator's ID.  It simplifies data extraction in the short term and long term.  Otherwise for a given term we're always asking the question "is this one to one" with some other term used in some other database.

But is the problem for Wikidata that one doesn't know what its editorial/curator community will do in layering other relations and mappings onto an externally defined term?  So Wikidata is saying "here's a term that is being crowdsource defined; and here's the original ontology ID?", i.e. because of the curation functionality Wikidata must sever the 1-1 term id and relationship?

**Comment by goodb** [comment]
A couple points to keep in mind.  

1. Wikidata is general purpose infrastructure that is not specific to biology.
2. It is meant to handle situations where there may be no existing ontology in play hence it needs to have the capacity to mint its own URIs.  Further, it needs a URL that it owns for each concept it represents where people can edit it.  
3. The closest thing to wikidata in the biomedical ontology world is the UMLS, with the wikidata URIs corresponding to the CUIs.  (with of course polar opposite curation models).  

The goal is one wikidata item (with one URI) per concept with as many links out to other identifiers for each concepts as are useful.

**Comment by Public-Health-Bioinformatics** [comment]
Totally understood that WikiData will be canvassing concepts from other domains besides biology (one of our own project will be looking at how to use WikiData for culinary food aspects!); and that it will have to mint its own URIs for concepts that aren't already formulated elsewhere.  I'm just exploring the tighter 1-1 concept mappings where the core concept is in fact being imported from elsewhere - word for word.  The idea of adding annotations to one's heart's content - the crowdsourcing model - I encourage; However, I don't see a technical issue with being able to annotate a term via an https://www.wikidata.org/wiki/GO_1234 type url in this case?

Just thinking about ways to reduce computational complexity of querying against a potpourri of Wikidata ids, chemical, cellular, genomic, etc. ontology ids and data out there, which the use of orthogonal ids was supposed to solve ... I suppose in lieu of that, to query WikiData against the potpourri we'd first have a WikiData transform that converted concept ids with known "imported from" identifiers (at most one per concept I presume?).  Same for http://eol.org/ etc... 

Reminds me of a question: does Wikidata automatically update its concept definition (and even hierarchy) based on changes in original source of a concept (like the GO ontology)?  Or are subsequent source database changes all manually curated back into WikiData?

**Comment by goodb** [comment]
Basically nothing like that happens automatically on Wikidata.  Everything
is maintained by bots like ours.  We are working hard to establish patterns
that keep the resources we are maintaining (e.g. the GO and the DO parts of
wikidata as well as most of the genes and proteins in there..) in sync with
the original sources as they change.  I think that for wikidata we pretty
much need to accept and work with it as a potpourri, but, if you have a
really strong argument for making a fundamental change I'm sure the
community would be happy to discuss it.  The only thing preventing or
fostering any change is the will of the community.  The best place to get
started is probably the mailing list:
https://lists.wikimedia.org/mailman/listinfo/wikidata

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I'll have a comb through the mailing list to get my bearings and see what's been said on the topic. Thanks for your description about WikiData mechanics.  I know Melanie has the interests of the broad OBOFoundry community in mind; I'm just starting to get engaged in that too.

**Comment by Public-Health-Bioinformatics** [comment]
p.s. Ah, goodb, I just realized with Will's help that we just met in Corvallis ICBO conference, so nice to get a conversation going... 
Damion

**Comment by goodb** [comment]
Aha, so you are that "Public Health Informatics" ;).  Nice to re, e-meet you here.

**Comment by Public-Health-Bioinformatics** [comment]
@goodb what do you think about the idea of designating some kinds of 1-1 imported WikiData content (like from GO ontology) as crowd-source annotated "Reference" resources, whereby the resource items keep their original (purl) ids on WikiData, and also WikiData would (eventually) commit to having an automated synchronization with the reference resource.  This type of resource should clearly isolate (separate in visual display) what axioms/labels/definitions were imported vs what have been crowdsource annotated.  Wouldn't that address the concern raised on OBI licensing discussion thread about not being able to distinguish HPO data from augmented WikiData?  I think it would clarify the basic layering of data from source to consumer?

**Comment by Public-Health-Bioinformatics** [comment]
(P.s. I see now that bots are the script mechanism for implementing periodic updates; and so say a food ontology import would be managed using one as a community project.).

**Comment by goodb** [comment]
@Public-Health-Bioinformatics For URIs, the pattern we are putting into place now links the wikidata items to the external (e.g. obo, uniprot) URIs via the wikidata property 'exact match' https://www.wikidata.org/wiki/Property:P2888 which is meant to match up with skos:exactMatch.  This can be used in SPARQL queries to support easy mapping of matching resources as well as to track connections to external ontologies.

I don't believe its possible to add references for a label or a textual definition in wikidata.  Its also doubtful whether class defining axioms could realistically be represented there.  For triple-like claims, e.g. annotations of genes with GO terms, or assertions about classes (e.g. narrower-than), wikidata imports should always be tracking the original resource(s) where the claims was imported from in the references for the claim.  The community handling biomedical data imports recognizes how important this is, by and large, and is working to keep it in place.  The tricky part here is that it cannot be guaranteed.  We can develop bot-level contracts, but we can't implement system-level contracts unless you can convince the WMF people of the value of the change.

**Comment by Public-Health-Bioinformatics** [comment]
Right, I suppose importing class axioms would be unhelpful too insofar as it takes a particular class of logic engine to reason with them, but for WikiData the focus is on properties & querying without reasoner products in the fray.  

As for label & textual definition (and perhaps a few other OBI curation annotations) I see then that to control them so they update automatically from source "reference" ontology content via a bot is possible if bot was tasked to sync them via a classes 'exact match' property, but there wouldn't be a mechanism to "lock down" their content between sync. updates.  

So OBI community (say) would have to convince WikiData community that there's no harm done in using OBI URI's as primary editing URI, and would have to come up with the bot that did above work.  Sounds like the bot part would be a more standard proposal but first part remains a harder sell in the face of the 'exact match' relation.

**Comment by nlharris** [comment]
Is this still relevant? Is it actionable?

**Comment by goodb** [comment]
@nlharris to my understanding, this is not actionable and the issue could be closed.
