### ISSUE TITLE
Attribution of data in Wikidata

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#299]
Consider the Reelin example from https://www.wikidata.org/wiki/Q13561329

![screen shot 2016-08-12 at 14 12 21](https://cloud.githubusercontent.com/assets/2214135/17623221/d70bfe44-6096-11e6-92be-35e8ee05601c.png)

There are a few issues with this:
- there is no provenance information indicating based on which publication or existing information the annotations were made
- there is no attribution to the group who made the annotation

When we discussed this in Geneva an objection to creating specific group (e.g. WormBase, BHF-UCL...) was raised as "Wikidata doesn't do attribution at a group level and wouldn't create groups"

**Comment by goodb** [comment]
Who are you quoting?  This is not the conversation that I was a part of.
We worked out several different patterns whereby attribution to a specific
annotation center (e.g. PantherDB or Wormbase etc.) could be recorded.  I
think that this can and should be a part of the wikidata model for these
annotations.

Wikidata is an open system just like Wikipedia.  If you don't like the way
something is represented, change it.  Join the discussions there.

**Comment by nlharris** [comment]
what is the status of this?

**Comment by nlharris** [comment]
i'm thinking maybe this can be closed, since it's not an obo foundry issue?
