### ISSUE TITLE
Hide display of obsolete ontologies on home page by default. Offer switch or other UI element to show it

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#300]
A not uncommon operation is to go to the site and do a page text search for something. In the most common case you aren't interested in the obsolete ontologies, and so I think these should not be visible, by default. 

There are a number of alternatives
1) Have a checkbox at the top of the page, initially checked, "Hide obsolete ontologies"
2) At the end of the page have a "More (obsolete) ontologies", pressing of which would add the entries back
3) Have a note in the prefatory text along the lines of "This page lists all ontologies that are not obsolete. You can get a page with the complete list (including obsolete ones) <href>here</href> 

Could also have a search box immediately above the list to narrow the list incrementally as you type, with a checkbox there indicating whether you want to see obsolete ontologies (default "no").

**Comment by nlharris** [comment]
This sounds like a nice (if not super-critical) usability feature. In order to test how the search currently works, I went to obofoundry.org and typed text into the "Search ontobee" search box (which was the only search box I saw) and it just spun and never returned. Should I create a ticket about that? @jamesaoverton

**Comment by jamesaoverton** [comment]
The Ontobee search box worked for me.

This issue is still relevant, and well-described, so I think it should stay open.

**Comment by nlharris** [comment]
> The Ontobee search box worked for me.

Aha--I figured out what happened. I was searching for "mouse gross" and there were a lot of hits so it took a long time to return the results, and I was too impatient.

**Comment by nlharris** [comment]
I believe this is now fixed by the home page redo, which now offers checkboxes "Hide Inactive" and "Hide Obsolete".

**Comment by nlharris** [comment]
Actually, after doing some testing, I don't think these checkboxes are quite working yet. I will open a new issue about that.

**Comment by cthoyt** [comment]
From my usage, this seems to be complete. I think it makes sense to consider inactive/orphaned/obsolete all together for these purposes. What did you expect that wasn't happening?

**Comment by nlharris** [comment]
see issue #2078

**Comment by cthoyt** [comment]
I think it's time to close this issue then in favor of https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2078

**Comment by nlharris** [comment]
Ok
