### ISSUE TITLE
Requesting update to OMRSE page

### ISSUE THREAD

**Issue by aellenhicks** [OBOFoundry/OBOFoundry.github.io#301]
The Google Code page is still linked to the OMRSE page. We have requested the appropriate change here. https://github.com/OBOFoundry/OBOFoundry.github.io/compare/master...aellenhicks:patch-1

**Comment by aellenhicks** [comment]
Following up on this issue. Is there a chance to have it resolved soon?  Thanks.

**Comment by cmungall** [comment]
Sorry, didn't notice this - in future would you mind making a pull requests? This is just one extra click. It makes it more visible for us if we're reviewing open PRs. Also, we can immediately tell if the change validates

I made a PR for it: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/319

And merged it

**Comment by aellenhicks** [comment]
Thank you. Yes, in the future I will make a pull request.


cheers,

Amanda


Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932<tel:%28352%29%20294-4197>
f: (352) 273-8703<tel:%28352%29%20273-8703>
aehicks@ufl.edu<mailto:hoganwr@ufl.edu>
________________________________
