### ISSUE TITLE
On pages with edit button, include link to markup instructions

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#302]
For example, I was looking to increase the size of the Principle Name on principle pages but don't know how to do that (The words "Principle Name" are very large, compared to the actual principle name which is very small - oops)

There are what seem to be glitches on http://obofoundry.org/docs/EditorialWG.html due to not understanding how to create a bulleted list.

**Comment by cmungall** [comment]
I suspect glitches are to do with the initial migration. I don't think the pages have seen a lot of editing activity since then.

We could do a link, or I could also do a tutorial for members of the Editorial WG. Everyone closely involved with OBO should be familiar with md, PRs, the CONTRIBUTING.md etc

**Comment by alanruttenberg** [comment]
Let's, at least, have the link that is informative regarding editing mechanics, since it is easy to forget the specifics. 

So how *do* I edit the principle page. Think it should be that we just remove "Principle Name" as a heading and have the principle name itself be the heading. (Discovered the issue when I wanted to use a screen snap in a presentation)

**Comment by cmungall** [comment]
It sounds like we need our own style guide as much as or even more than we need generic markdown instructions. Yes, at the moment it requires either guesswork or knowledge of how the template is rendered to avoid annoying things like duplicate headings, which is not ideal.

**Comment by cmungall** [comment]
We currently have http://obofoundry.org/faq/how-do-i-modify-website.html

Which links to https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md

But this is aimed at the TWG who might be making major changes to the look and feel or layout or functionality of the site, and may be running a local jekyll instance. We need something for general members of the OBO WGs who want to edit content only purely via the website

**Comment by alanruttenberg** [comment]
If there is a template involved, including a link to the template is a good idea as well. I think I did a patch to Neurocommons wiki at some point that did this.

**Comment by alanruttenberg** [comment]
There are some broken links on https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md. I fixed _layouts but not sure about the others:

_site
_assets
registry/ontologies.yaml

**Comment by alanruttenberg** [comment]
Was going to add a link to some reasonable doc page about Jekyll, but will leave it to you for the moment. After your next edit I'll see if there are other links that might be helpful to add to that doc.

**Comment by alanruttenberg** [comment]
Missed (broken)

registry/ontologies.rdf

**Comment by alanruttenberg** [comment]
typo: http:/oobofoundry.org

**Comment by alanruttenberg** [comment]
Lot's o warnings when running jekyll:

    Liquid Warning: Liquid syntax error (line 1): [:end_of_string] is not a valid expression in "{{ }}" in /_layouts/ontology_detail.html
...

Should I care?

**Comment by nlharris** [comment]
This is quite old--is it still relevant, and if so, can it be assigned to someone other than @cmungall? Let's save his limited time for higher-level questions that require his expertise.

**Comment by nlharris** [comment]
i'm unassigning chris. this still seems worth doing, but chris isn't the one to do it.

**Comment by nlharris** [comment]
> There are some broken links on https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/README-sitedev.md. I fixed _layouts but not sure about the others:
> ...
> _site _assets registry/ontologies.yaml

Fixed in #1772

registry/ontologies.rdf is still missing but I'm not sure how to fix that.

**Comment by nlharris** [comment]
I'm going to close this -- if there are things in this ticket that are actionable, please open new tickets with specifics.
