### ISSUE TITLE
 OBOFoundry.github.io/README-sitedev.md needs doc on dependencies riot, rdfcat

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#304]
Make fails without these installed.

**Comment by cmungall** [comment]
I wonder if it would make the whole pipeline more straightforward to use python3+rdflib in place of jena  - @kshefchek was doing this for another project, would that work Kent?

**Comment by nlharris** [comment]
What is the status of this?

**Comment by jamesaoverton** [comment]
`riot` is part of Apache Jena. That doc and the Makefile explain that Jena is required and provide a link. So I'll close this.
