### ISSUE TITLE
principle 1 lists minimum CC-BY 4.0

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#306]
I think it should be listed as minimum 3.0, with encouragement to use the latest version at a time. The problem is that many ontologies were published under 3.0 before 4.0 even existed. While 4.0 is an improvement over 3.0, the changes tend to be things that I don't think substantively effect us (e.g. moving from jurisdiction-specific version to a single international version).

The consequence of leaving it as is is that critical reviewers will (and have) considered using CC-BY 3.0 as inconsistent with the principle.

**Comment by cmungall** [comment]
+1

**Comment by zhengj2007** [comment]
+1

**Comment by nataled** [comment]
Revised as suggested for the requirement part. Examples were left as CC-BY 4.0.
