### ISSUE TITLE
Add LICENSE file to repo

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#31]
How should this repo be licensed?

Should different components be licensed differently? How do we indicate this with a LICENSE file?

Some suggestions:
1. ontology metadata CC-BY or CC-0
2. Site tooling and web interface: python script to make yml; jekyll HTML templates: BSD3
3. content authored primarily by OBO Foundry (FAQs, principles, id-policy, how-tos, etc): CC-BY

The authors of 2-3 are primarily members of the OBOF. For 1 could be considered joint authorship between individual ontology maintainers and OBOF.

**Comment by cmungall** [comment]
Upping the priority of this

**Comment by cmungall** [comment]
My revised preferences:

 1. ontology metadata CC-0
 2. Site tooling and web interface: python script to make yml; jekyll HTML templates: BSD3
 3. content authored primarily by OBO Foundry (FAQs, principles, id-policy, how-tos, etc): CC-BY

The metadata should be CC-0 otherwise it potentially causes problems for aggregators like @graybeal

**Comment by ramonawalls** [comment]
+1 for Chris's preferences, although I would also be fine with CC0 for content.

**Comment by selewis** [comment]
Same as Ramona.

**Comment by bpeters42** [comment]
Same as Suzi

**Comment by nataled** [comment]
Same as Bjoern

**Comment by cmungall** [comment]
Same as @nataled. Oh no, cycle!

Actually I agree with Ramona that CC-0 for content is perfectly fine. In fact, in retrospect I think extending this to code too makes sense. Then there would be once LICENSE file for the whole repo.

If the other main code contributors (I think @jamesaoverton and @mcourtot) agree with this minor amendment I'll go ahead and do that.

**Comment by nlharris** [comment]
Did this happen?

**Comment by matentzn** [comment]
Not really: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/LICENSE.md
I guess this is a 3 min thing for Chris to phrase correctly..

**Comment by nlharris** [comment]
Not sure whether Chris has 3 minutes...
Maybe @kltm could do this?

**Comment by kltm** [comment]
I have no idea what current desires or strategy is, but I have a PR (https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1168) for review for CC0 for data and BSD 3-clause for software.

**Comment by nlharris** [comment]
#1168 was approved and merged...

**Comment by nlharris** [comment]
So can we close this issue?

**Comment by nlharris** [comment]
this must be done, right? i'm closing, can reopen if there's a specific change needed.
