### ISSUE TITLE
Wikipedia page is out of date

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#310]
https://en.wikipedia.org/wiki/Open_Biomedical_Ontologies

**Comment by nlharris** [comment]
https://en.wikipedia.org/wiki/Open_Biomedical_Ontologies was last updated just a few days ago. Can we close this ticket, or are there still things there that need to be fixed?

**Comment by lubianat** [comment]
Hello,
@nlharris  and @mcourtot,

I have been working on OBO Foundry Wikipedia pages for the past few months. 

There are still some things that should be fixed there. Mainly:

1) The difference between OBO and OBO Foundry is subtle, and perhaps these two pages should be merged:
https://en.wikipedia.org/wiki/OBO_Foundry
https://en.wikipedia.org/wiki/Open_Biomedical_Ontologies

I can do this right away if that makes sense to you too. Also,  a clarification of the difference between these 2 resources would be very welcome.

2) There are no images on the page. That makes it less appealing. It would be nice to add the foundry logo, but it to be added to Wikipedia, I would need a version of it in Creative Commons, or similar, and the original authors. Would you know how could I get these information on the logo? Or who would be able to authorize it? 

There has been a brief discussion about it with @matentzn [in the OBO forum ](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/obo-discuss/U5Nz1oCn0c0/9Soxy8B3AgAJ).

Thanks!
Tiago

**Comment by mellybelly** [comment]
+1 to merging. I prefer "Open Biological Ontologies" but not sure what is canonical now.

**Comment by matentzn** [comment]
`The Open Biological and Biomedical Ontology (OBO) Foundry is a collective of ontology developers ...`

http://obofoundry.org/

+1 for merging

**Comment by lubianat** [comment]
Thanks @mellybelly  and @matentzn. 

I am starting to merge them under the OBO Foundry page. It seems logical to me, as OBO today seems to be mostly OBO Foundry. 

This can be changed later, if needed and/or wanted.

Thanks again!

**Comment by nlharris** [comment]
thank you for doing this, @lubianat!

**Comment by lubianat** [comment]
Hello, @nlharris, @mellybelly and @matentzn. 

The updates on the [OBO Foundry page on Wikipedia](https://en.wikipedia.org/wiki/OBO_Foundry) were awarded 2nd place in the [International Society for Computational Wikipedia Competition] (https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Molecular_Biology/Computational_Biology/9th_ISCB_Wikipedia_competition_announcement) .

I just wanted to share this with you and thank you for your help! :)

**Comment by nlharris** [comment]
Wow, that's great, congratulations!

We can definitely close this ticket now!

**Comment by matentzn** [comment]
Very nice!!! Thanks @lubianat !!! Good one!
