### ISSUE TITLE
Request for ' TCMDPO ' namespace /prefix

### ISSUE THREAD

**Issue by TCMOntology** [OBOFoundry/OBOFoundry.github.io#317]
**Ontology Title:** Traditional Chinese Medicine Decoction Pieces Ontology
**Requested Prefix:** TCMDPO
**Description:**
As one of Traditional Chinese Medicine(TCM) ontologies, Traditional Chinese Medicine Decoction Pieces Ontology(TCMDPO) was developed by Institute of Information on Traditional Chinese Medicine (IITCM), China Academy of Chinese Medical Sciences(CACMS). This project is to eliminate the communication barriers in different fields, facilitate data modeling, and promote the sharing of data in TCM clinical practice. The onotolgy includes description of knowledge system structure and related properties for TCM decoction pieces in clinical use.
**Download link:** 
https://github.com/TCMOntology/TCMDPO/blob/master/TCMDPO.owl
**Home page:** 
https://github.com/TCMOntology/TCMDPO
**Contact:** Yan Zhu, zhuy@mail.cintcm.ac.cn
**Mailing-list (if any):** 
none yet
**Tracker link:** 
https://github.com/TCMOntology/TCMDPO/issues

**PURL user name:** zhuyan166

**Comment by mcourtot** [comment]
Dear Zhu Yan,

Thank you for you request. We are unfortunately having trouble assessing whether the resource is in scope for the OBO Foundry, as there is no english content. It would be very helpful if you could add an english label/definition to classes, as well as perhaps identify whether some of them re already present in some OBO resources.

**Comment by TCMOntology** [comment]
Dear Melanie Courtot,

Thanks for your response.

Our group has been working on ontology construction for many years.  Inspired by the spirits and foresight of OBO community, we wish to share and map the TCM knowledge with Modern Medicine, and get theoretic and technical supports from the community. 

The TCMDPO is our first ontology to summit to the OBO Foundary. It represents the knowledge structure of TCM decoction pieces which are used in TCM clinical practice. Later it will also include code information from ISO standard(http://www.iso.org/iso/catalogue_detail.htm?csnumber=64958). As far as I know, there is NO OBO resource representing TCM decoction pieces until now. Subsequently, we will release Acupuncture Point Ontology and Medicinal Materials Ontology, which refer to anatomy and plant knowledge from other OBO resources  respectively. 

Our group built a series ontologies of Traditional Chinese Medicine(TCM) with Chinese language. The translation works are under way. I will upload a bilingual preview-version of TCMDPO  in few days, and hope it will be helpful for your investigation.

Best wishes,


朱彦(Zhu, Yan) 




发件人：Melanie Courtot <notifications@github.com>
发送时间：2016-10-18 02:54
主题：Re: [OBOFoundry/OBOFoundry.github.io] Request for ' TCMDPO ' namespace /prefix (#317)
收件人："OBOFoundry/OBOFoundry.github.io"<OBOFoundry.github.io@noreply.github.com>
抄送："TCMOntology"<zhuy@mail.cintcm.ac.cn>,"Author"<author@noreply.github.com>

Dear Zhu Yan,
Thank you for you request. We are unfortunately having trouble assessing whether the resource is in scope for the OBO Foundry, as there is no english content. It would be very helpful if you could add an english label/definition to classes, as well as perhaps identify whether some of them re already present in some OBO resources. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

____ KILL Mail Shield Gateway scanned ____

____ KILL�ʼ���ȫ��� �Ѿ�ɨ��������ʼ� ____

**Comment by TCMOntology** [comment]
Dear Melanie Courtot,
Please check the latest version of the TCMDPO(https://github.com/TCMOntology/TCMDPO/blob/master/TCMDPO.owl), and continue the assessment. Thank you!

**Comment by lschriml** [comment]
Dear Zhu Yan,
  We thank you for submitting your ontology for submission to the OBO Foundry library.   After much discussion, across the OBO Foundry operations committee members, we have determined that the TCMDPO is out of scope for the OBO Foundry, as the OBO Foundry's library is limited to  biological, biomedical and medical sciences.  For example, an ontology about astrology would be out of scope.
      However, we would suggest that you consider submitting your ontologies to the NCBO BioPortal, as the BioPortal has a broader scope of content.  
https://bioportal.bioontology.org/help#Submitting_an_ontology

Regards,
Lynn Schriml
on behalf of the OBO Foundry Operations Committee
