### ISSUE TITLE
Move across any still-valid tickets from old Operations-Committee tracker

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#321]
See https://github.com/OBOFoundry/Operations-Committee/issues/194

It should take about 20 mins using https://github-issue-mover.appspot.com/

Any comments before this is done?

**Comment by lschriml** [comment]
Tickets from: https://github.com/OBOFoundry/Operations-Committee-RETIRED/issues

Volunteering to review 10 of these tickets in the next two weeks, assess their status, move them to this repository.
