### ISSUE TITLE
Language requirement for new resources

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#325]
Following up on https://github.com/OBOFoundry/OBOFoundry.github.io/issues/317

We discussed the need to make more explicit the requirement for english language description (labels, definitions) to enable review of resources before inclusion in the OBO library.

**Comment by nlharris** [comment]
Does this still need to be done?

**Comment by matentzn** [comment]
No I dont think so.. I will try to work out a more general solution for languages at some point, but right now, these language tickets will just stay open and lag behind. Its good you link them together though :)

**Comment by nlharris** [comment]
Can this issue be closed?

**Comment by matentzn** [comment]
Yes, cant see any more action items right now.
