### ISSUE TITLE
Fork Request

### ISSUE THREAD

**Issue by jaygray0919** [OBOFoundry/OBOFoundry.github.io#327]
We would like to include several OBO hosted ontologies on https://github.com/afdsi.
Please note that our GitHub site is under construction; there are several 'stub' files that play the role of "Lorem Ipsum."
Rather than download an OBO instances and then upload to AFDSI, we'd like to fork a specific instance to a directory in our classification structure.
Is that possible? If yes, would you point us to instructions about doing so?
We don't plan to make a pull request to propose changes; this is a read-only exercise.

/jay gray

**Comment by cmungall** [comment]
Hi Jay,

Just to clarify, you are interested in pulling the ontology itself, rather than the registry metadata from this repo?

This is certainly possible with any OBO ontology that chooses to use GH for its management (most). But the main reason to do this would be if you planned to make local edits and PRs. This is best discussed on a case by case basis with individual ontology contacts. PRs in OWL require additional coordination beyond diffable software source, each ontology has its own design patterns, style guides etc.

I think there may be a better way of doing what you want to do but we'd have to know more about the intended end result.

**Comment by jaygray0919** [comment]
Hey Chris.

Some background:
When defining foods, we 'owl:import' several OBO-hosted ontologies (e.g. ChEBI, PATO, PO).
This is part of a 5+ year project that may be publicly available soon.
If you are interested, we will brief you on that process at a later time; it's been a VERY difficult journey.

Per the above request:
On the GitHub AFDSI site, we want to classify the ontologies that we use to describe food.
However, ontologies posted to the AFDSI GitHub classification will be 'read-only' - meaning that we will not propose changes to any OBO-hosted ontologies.
Rather than doing a clean upload of an ontology downloaded from a source site (like OBO), we'd like to fork the relevant OBO-hosted ontologies so that visitors see the source of the ontologies (OBO).
We have other non-OBO-hosted ontologies that we also will upload to the GitHub AFDSI classified directories, together with food-specific ontologies we have developed over the last several years.

We don't want to fork the entire OBO repository because we only use a subset of OBO-hosted ontologies.
But we want to ask permission first, and also ask how to fork a specific ontology to a specific GitHub/AFDSI classification directory.

Ping me back if more information is needed.

/jay

**Comment by jamesaoverton** [comment]
Hi Jay. When you say "fork the entire OBO repository", I think there might be a misunderstanding. This repository (OBOFoundry/OBOFoundry.github.io) only contains metadata and the OBO website. Each ontology project maintains its own repository with its own OWL files. For instance:

- PATO: https://github.com/pato-ontology/pato
- ChEBI: I don't think their repository is public, but files are available from https://www.ebi.ac.uk/chebi/downloadsForward.do
- PO: https://github.com/Planteome/plant-ontology

Many projects are on GitHub, but many are not. As Chris said, projects differ widely in how their repositories are laid out, their design patterns, etc. The consistent interface to our ontologies is our PURL system, which points to each published version of each ontology.

My initial thought is that forking is not the right approach. Let us know a little more about what you want to accomplish and what the problems are, and we'll try to help.

**Comment by jaygray0919** [comment]
Thanks for the additional information James.  I did not look at this as carefully as I should have.

I thought that, somewhere, there was an OBO-hosted `.owl` file for [https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/chebi.md](url). I saw  http://obofoundry.github.io/ontology/chebi.html and went looking for its copy on OBO.

Longer term, we want to do for `food` what you chaps have done for `bioinformatics`.
Short term, we want to show the specific ontologies, lightly classified by subject, that we import when defining foods.

My conclusion here is that we should upload the .owl version we use for `owl:import` to the ontology classification structure we're using on GitHub.

Let me know if I'm still off-base or missing an opportunity to synchronize our work with yours.

/jay

**Comment by jamesaoverton** [comment]
Keeping dependencies in version control is a fairly common practise for software development (although there are arguments against), and can work fine for ontology development. GitHub has file size limits that are too small for some of the OWL files published by OBO projects, in which case you could compress the versions that you store.

**Comment by cmungall** [comment]
Another thing to bear in mind is that you may not need the complete contents of CHEBI, etc. A common practice is to extract a subset using modularizaton techniques, or to MIREOT a subset into your ontology. [robot](https://github.com/ontodev/robot/) can help with some of this.
