### ISSUE TITLE
Sort out metadata for contributors within ontologies, and align with what is in OBO metadata

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#329]
This queries for contributor and creator:

http://sparql.hegroup.org/sparql?default-graph-uri=&query=prefix+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+prefix+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0A%0D%0A%0D%0ASELECT+DISTINCT+%3Fc+WHERE+%7B%0D%0A%7B+%3Font+dc%3Acontributor+%3Fc+%7D%0D%0AUNION%0D%0A%7B+%3Font+dc%3Acreator+%3Fc+%7D%0D%0A%7D&format=text%2Fhtml&debug=on&timeout=

Some interesting entries there.

We also have this way of querying our metadata:

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/sparql/ontology-contact.sparql

**Comment by mcourtot** [comment]
which sparql endpoint do you use for the second query?

**Comment by cmungall** [comment]
@mcourtot - no endpoint, these queries are executed directly over the generated ttl using jena/arq https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/Makefile#L117-L118

**Comment by zhengj2007** [comment]
This issue was moved to information-artifact-ontology/ontology-metadata#2
