### ISSUE TITLE
Need contact for SWO

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#33]
http://obofoundry.github.io/ontology/swo.html

James has left the EBI

@helenp should this be you?

**Comment by helenp** [comment]
Hi

Robert Stevens and me -

parkinson@ebi.ac.uk

thanks

Helen


On 12/08/2015 00:48, Chris Mungall wrote:
>
> http://obofoundry.github.io/ontology/swo.html
>
> James has left the EBI
>
> @helenp <https://github.com/helenp> should this be you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OBOFoundry/OBOFoundry.github.io/issues/33>.
>

-- 
Helen Parkinson, PhD
Team Leader
Samples, Phenotypes and Ontologies Team
-------------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

EBI 01223 494672
For scheduling assistance please contact Lynn French lfrench@ebi.ac.uk, 01223 494 453
Skype: helen.parkinson.ebi
http://www.ebi.ac.uk/about/people/helen-parkinson
