### ISSUE TITLE
OntoNeo prefix request

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#334]
I want to register my ontology at OBO Foundry.

It is the Obstetric and Neonatal Ontology (ONTONEO). The ontology home page is https://ontoneo.com/ in the case to get more information about that.
Information needed for a prefix request: 
requested prefix: ontoneo
ontology title: Obstetric and Neonatal Ontology
ontology download link: https://ontoneo.com/products/
ontology home page: ontoneo.com
point person contact email: Fernanda Farinelli (fernanda.farinelli@gmail.com) or ontoneoontology@gmail.com
ontology discussion mailing-list: ontoneo-discuss@googlegroups.com
ontology issue tracker link at https://github.com/ontoneo-project/Ontoneo
purl.org user ID: Ontoneo Admin

Can I request a PURL and the registry?
Let me know.

Thank you,

from @FernandaFarinelli on the OBO list

**Comment by mcourtot** [comment]
Hi @FernandaFarinelli - I saw you had an antenna.md file ready to go in your GH repo - would you mind using it to create a pull request here?

Thanks,
Melanie

**Comment by FernandaFarinelli** [comment]
Hi @mcourtot 
I submitted a pull request named "New ontology: Ontoneo" in which I uploaded my ontoneo.md file.
Thanks
Fernanda

**Comment by mcourtot** [comment]
HI @FernandaFarinelli - I couldn't see anything under https://github.com/OBOFoundry/OBOFoundry.github.io/pulls so just created one now.

**Comment by mcourtot** [comment]
Merged request. Result at http://obofoundry.org/ontology/ontoneo.html

I'm dealing with a few other prefixes, when all done I'll regenerate the front page table.

**Comment by mcourtot** [comment]
All done - any problem please let me know.

**Comment by mcourtot** [comment]
Note: I still need to create the PURL entry.
