### ISSUE TITLE
Update documentation about registration requirements: English required; scope of OBO limited to biological / medical

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#335]
As discussed during OBO call on Nov 15 2016. Update FAQ at http://obofoundry.org/faq/how-do-i-register-my-ontology.html

1. We need english for both label and definition at a minimum. Additional language are encouraged, but should be in addition to english.

2. The scope of the OBO library is limited to resources supporting biological and medical science. For example, an ontology about astrology would be out of scope.

**Comment by nlharris** [comment]
I think this is now superseded by other policy discussions and can be closed?

**Comment by nlharris** [comment]
http://obofoundry.org/faq/how-do-i-register-my-ontology.html now simply points to http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

regarding 1 (above), that page does not mention english.
regarding 2, it does say "A project must be doing original work within the biological ontology community" -- is that good enough?

**Comment by nlharris** [comment]
http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html doesn't mention english. add that?

**Comment by nlharris** [comment]
Related issues: #325 #1015

**Comment by nlharris** [comment]
http://obofoundry.org/faq/how-do-i-register-my-ontology.html no longer gives any details about ontology requirements. Is this issue now obsolete?

**Comment by matentzn** [comment]
I think these two bullet points up top need to be reflected somewhere. There must be 100 places by now where we have criteria for acceptance of an ontology. One that comes to mind is the issue template.

**Comment by nlharris** [comment]
i changed the title of this issue to make it better reflect what needs to be done.

**Comment by nlharris** [comment]
Seems like we could add the English language requirement to the list on https://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

**Comment by nlharris** [comment]
This is now done: [Principle 6](https://obofoundry.org/principles/fp-006-textual-definitions.html) now mentions the English language requirement, as does the [new ontology submission form.](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&projects=&template=new-ontology.yml&title=Request+for+new+ontology+%5BNAME%5D)

In the process of checking the latter, I discovered that on the FAQ page, it says
> Submit your request to our GitHub tracker, using the [New Ontology Request template](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/new?assignees=&labels=new+ontology&template=new-ontology-request.md&title=)

but that's not the right URL to invoke the new ontology submission form. I will create a separate ticket for that (and then try to fix it).
