### ISSUE TITLE
OBO PURL for PPO

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#340]
I would like to request the namespace "PPO" in the OBO Foundry Libarary and the corresponding set of PURLS.

    requested prefix: PPO
    ontology title: Plant Phenology Ontology
    ontology download link: https://raw.githubusercontent.com/PlantPhenoOntology/PPO/master/ontology/ppo.owl
    ontology home page: https://github.com/PlantPhenoOntology/PPO
    point person contact email: rlwalls2008@gmail.com
    ontology discussion mailing-list: ppo-discuss@googlegroups.com
    ontology issue tracker link: https://github.com/PlantPhenoOntology/PPO/issues

I have right permission to this repo, so once the YAML file is created, I can enter the needed information.

**Comment by ramonawalls** [comment]
Just a ping to say I hope we can get this PURL soon. If there are instructions somewhere on what needs to be done, I'm happy to fork the repo, make the changes, and do a pull request.

**Comment by jamesaoverton** [comment]
I updated the site and PPO is now visible on the main list and it's own page: http://obofoundry.org/ontology/ppo.html

**Comment by ramonawalls** [comment]
Thank you James!
