### ISSUE TITLE
Fix ontoneo

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#341]
This is invalid:

```
build:
  source_url: 
  method: owl2obo
```

cc @FernandaFarinelli @mcourtot 

Either delete the entire build blob OR put the source URL in there.

You also need a PURL entry

**Comment by FernandaFarinelli** [comment]
Hi Melanie @mcourtot ,

Just let me know if I need to do something.

**Comment by cmungall** [comment]
Is this fixed yet?

**Comment by FernandaFarinelli** [comment]
@mcourtot 
I submitted the Update to ontoneo.md (#369) right now.

**Comment by cmungall** [comment]
See my comments in the PR, not sure what happened here

**Comment by mcourtot** [comment]
Fixed.
