### ISSUE TITLE
Fix pdro.md

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#342]
```
build:
  source_url: http://purl.obolibrary.org/obo/pdro.owl
  method: owl2obo
```

However, this does not resolve as there is no PURL registered.

The source appears to be

https://raw.githubusercontent.com/OpenLHS/PDRO/master/PDRO.owl

We could add this as source. But better if PDRO takes control over all PURLs

**Comment by mcourtot** [comment]
See https://github.com/OBOFoundry/purl.obolibrary.org/pull/260. The PR was created, but there are issues with the IRIs in the file as mentioned at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/283#issuecomment-260918073

Waiting on response from @rtaseen

**Comment by rtaseen** [comment]
Sorry for delay. IRI's in [PDRO.owl](https://raw.githubusercontent.com/OpenLHS/PDRO/master/PDRO.owl) should be correctly formatted now.

**Comment by matentzn** [comment]
The purl is still pointing to http://www.berkeleybop.org/ontologies/pdro.owl
(http://www.obofoundry.org/ontology/pdro.html)

**Comment by rtaseen** [comment]
If I understand correctly, I believe [this patch](https://github.com/OBOFoundry/purl.obolibrary.org/pull/260) needs to be pulled into master for the PURL to resolve.

**Comment by mcourtot** [comment]
Done.
