### ISSUE TITLE
Proposal: obsolete ontologies with dead purls

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#344]
(also sent to obo-discuss)

If you have an ontology registered with OBO, then there should be a working purl for your ontology. There should be at least one purl for the canonical OWL edition of your ontology, which will look like this:

http://purl.obolibrary.org/obo/envo.owl
Many ontologies also make other editions/products available, for example an obo format edition, or editions for subsets

The list of such artefacts can be seen on your OBO page under 'products', e.g.

http://obofoundry.org/ontology/envo.html
Note that if you edit your ontology in OBO-Edit, and have not yet figured out how to make OWL releases, don't worry. We provide a central build as a free service: http://obofoundry.org/faq/what-is-the-build-field.html (but really you should be looking to make your own releases, we have good tutorials on this).

__IMPORTANT__

A number of PURLs are no longer functional. In some cases this is due to an ontology being abandoned on googlecode (see the archives of this list for repeated messages to migrate from google code). Or in some cases a sourceforge URL that no longer works.

Non-functional PURLs cause a great deal of problems with groups who consume the OBO library ontologies programatically. Previously we've tried to be proactive and chase up and help fix these issues, but some responsibility rests with the ontology producer.

I propose that if you have previously submitted an ontology to OBO, and the PURL for it no longer works (or never worked) then it is considered abandoned, and is obsoleted after an initial warning period.

If you produce an ontology, please take a look at the list here:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/257#issuecomment-264242016

If your ontology is on the list and you are committed to OBO, don't panic! -- we'll work with you to fix this. Please comment either in this ticket (or the linked ticket that pertains to your ontology).

However, if the ontology PURL doesn't resolve and no one cares about it, I propose it be obsoleted, after which it will cease to cause problems for downstream consumers.

**Comment by caripark** [comment]
For VT, we've done everything in OBO--I'd be interested in getting some help with this issue. Thanks!

**Comment by cmungall** [comment]
Great - I sent you an email earlier, we can follow up there

**Comment by ramonawalls** [comment]
At the OBOF operations meeting on 3/21, we agreed that this can be implemented as policy and promoted on website, on the page that describes PURL policies.

See also issue #257

**Comment by nlharris** [comment]
Does this still need to be completed? Chris noted in the merge of #407 

> I'm merging as this is a good incremental improvement, leaving the parent ticket open

**Comment by nlharris** [comment]
can this be closed?

**Comment by matentzn** [comment]
We can close this ticket, as this is now the relevant one: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/546
