### ISSUE TITLE
TTO ontology header does not conform

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#345]
The ontology PURL is teleost_taxonomy.owl -- should be tto.owl 

This causes issues for the central build (which TTO relies on as it doesn't make it's own)

Either:

 1. change to tto
 2. Inject correct header in build tag (see ma.md for example)
 3. Control builds

cc @balhoff

**Comment by balhoff** [comment]
I'm trying to move this into GitHub and preserve the history. It's not a big deal but thought I might as well. @cmungall do you have a backup of the OBO CVS repo from SourceForge? (not the checkout, but the server repository). I tried following [these backup instructions](https://sourceforge.net/p/forge/documentation/CVS/), but  can't get the rsync command to work.

**Comment by cmungall** [comment]
No, I don't think I ever did a full transfer.

I'm trying to recall if I ever did any transfers of CVS at all, I think I only did SVN repos

**Comment by balhoff** [comment]
I was able to download the OBO CVS repo, see here: https://sourceforge.net/p/forge/site-support/14071/

I'll try the git conversion for TTO sometime soon.

**Comment by balhoff** [comment]
I moved the version control for TTO to the Phenoscape GitHub org: https://github.com/phenoscape/teleost-taxonomy-ontology

I created an OWL version there, so this doesn't need to be part of the central build anymore.

**Comment by cmungall** [comment]
Thanks @balhoff!
