### ISSUE TITLE
Vectorbase source URLs do not work (idomal, miro, tads, tgma)

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#346]
```
$ grep source_url: ontology/*md | grep vectorbase.org 
ontology/idomal.md:  source_url: http://anobase.vectorbase.org/idomal/IDOMAL.obo
ontology/miro.md:  source_url: http://anobase.vectorbase.org/miro/miro_release.obo
ontology/tads.md:  source_url: http://anobase.vectorbase.org/anatomy/tick_anatomy.obo
ontology/tgma.md:  source_url: http://anobase.vectorbase.org/anatomy/mosquito_anatomy.obo
```

None of these work.

**Comment by cmungall** [comment]
From Pantelis:

IDOMAL: https://www.vectorbase.org/download/malariaidomal1392015-03obogz

MIRO: https://www.vectorbase.org/download/irmiro20201501obogz

TADS: https://www.vectorbase.org/download/anatomytads1222013-04obogz

TGMA: https://www.vectorbase.org/download/anatomytgma1122013-06obogz


There is also IDODEN (for Dengue Fever) https://www.vectorbase.org/download/dengueidoden102014-08obogz

actually developed by @elviram while she was in our lab.

**Comment by elviram** [comment]
@cmungall would it make sense to put all of these in a github repo?

**Comment by cmungall** [comment]
Each of these needs to be added to the build file in the corresponding .md file

Each http://obofoundry.org/ontology/tads.html

click edit

See http://obofoundry.org/faq/what-is-the-build-field.html

**Comment by cmungall** [comment]
I favor placing each of these in their own repo as @elviram suggests. This will give each one its own tracker.

Alternatively we can update the source for each of these ontologies, and mark them as deprecated.

**Comment by rvita** [comment]
will be fixed via OBO services work, idomal done, rest will get done.

**Comment by cmungall** [comment]
@rvita any update on this? 

I think it's misleading when users arrive here:
http://obofoundry.org/ontology/idomal.html

The OWL link is dead.

Note this paper counts it as inactive: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6371329/

**Comment by rvita** [comment]
I am sorry, but  I am not sure I am following you. For idomal's homepage, we have https://www.vectorbase.org/ontology-browser which does resolve and the link on that page for downloading the idomal file is https://www.vectorbase.org/download/malariaidomal1392015-03obogz which also works, so for my metadata "clean up" I have marked idomal as approved & it also validates.
for the others mentioned : miro - I have been emailing them without a response and followed up again today, we may have to make them orphaned. tads- is all up to date and validates. tgma-the homepage needs to be updated to https://www.vectorbase.org/ontology-browser. I can do this.

**Comment by cmungall** [comment]
http://obofoundry.org/ontology/tads

http://purl.obolibrary.org/obo/tads.owl <-- 404

If there is no ontology then it shouldn't be declared active! See email thread.

**Comment by rvita** [comment]
Daniel Sonenshine dsonensh@odu.edugave himself as the contact & stated the ontology as existing at https://www.vectorbase.org/downloads?field_download_file_type_tid[]=470&field_download_file_format_tid=All&field_status_value=Current
we can update the location?

**Comment by cstoeckert** [comment]
I've brought this issue to the attention of the VectorBase (and EuPathDB) PIs and managers. Dan Lawson, Jie Zheng, and I will work on addressing this ticket.

**Comment by cmungall** [comment]
@zhengj2007 @cstoeckert any update on this?

I recommend marking ontology as inactive until we have a download

**Comment by cstoeckert** [comment]
We are actively working on finding alternative OBO Foundry terms or submitting new term requests to appropriate ontologies for terms needed by VectorBase. We could post them at the VEuPathDB ontology GitHub site in the interim. VEuPathDB however is not planning to develop them further.

**Comment by cmungall** [comment]
Correspondence from @cstoeckert

> Marking them as inactive makes sense since they are not being actively developed.

**Comment by zhengj2007** [comment]
I added IDOMAL and MIRO repositories on VEuPathDB ontology GitHub site and edited the idomal.yml and miro.yml files by adding working URLs for downloading the ontologies.
