### ISSUE TITLE
Is there a recommended version of the OWL API that is guaranteed to be able to parse all obofoundry ontologies (OWL versions)?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#352]
We used to get better "parseability" with some old versions of the OWL API.. I am just wondering whether you have any particularly good experiences with a specific version. If not, you can close the issue again immediately. Thanks.

**Comment by cmungall** [comment]
> We used to get better "parseability" with some old versions of the OWL 
> API.. I am just wondering whether you have any particularly good 
> experiences with a specific version. If not, you can close the issue 
> again immediately. Thanks.

Most code I am aware of uses owlapi v4 with no problems. Parseability 
shouldn't be a continuum - if it's valid it should parse, if it's 
invalid an error should be thrown.

Parser implementation errors should be reported on 
https://github.com/owlcs/owlapi/issues/new

Oe slight greivance with owlapi v4 is it cycles through a larger list of 
parsers which can make debugging mildly more annoying. And in theory 
more prone to false positive parses with the wrong parser
