### ISSUE TITLE
Request for CRO purl/prefix

### ISSUE THREAD

**Issue by marijane** [OBOFoundry/OBOFoundry.github.io#355]
**Requested Prefix:** CRO
 
**Ontology Title:** The Contributor Role Ontology
 
**Download link:** https://github.com/openrif/contributor-role-ontology/blob/master/cro.owl
 
**Home page:** https://github.com/openrif/contributor-role-ontology
 
**Contact:** whimar@ohsu.edu
 
**Mailing-list:** https://groups.google.com/forum/#!forum/openrif-dev
 
**Tracker link:** https://github.com/openrif/contributor-role-ontology/issues
 
**PURL user id:** whimar@ohsu.edu
 
 
This ontology is an OWL implementation of and eventual expansion of the CASRAI Contributor Roles Taxonomy (CRediT), which is a high-level classification of the diverse roles performed in the work leading to a published research output in the sciences. Its purpose to provide transparency in contributions to scholarly published work, to enable improved systems of attribution, credit, and accountability.

**Comment by mellybelly** [comment]
Note that we intend to use this for contributions to ontologies and datasets within the OBO community, similar to IAO use for information artifact descriptions.

**Comment by nataled** [comment]
(Closing old tickets) Prefix and PURL has been added.
