### ISSUE TITLE
Add prominent link to obo tutorial

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#356]
Many of the Qs people coming to the site have are answered in:

https://github.com/jamesaoverton/obo-tutorial

so far we have no links other than one buried in a faq entry (how-do-i-request-a-term.html).

I suggest both a top level faq 'how do I get started', and also its own menu item

See also #183

**Comment by nlharris** [comment]
This still seems like a good idea. Can someone other than @cmungall tackle it?
