### ISSUE TITLE
Are there any constrains on Principle: Textual Definitions

### ISSUE THREAD

**Issue by stopopol** [OBOFoundry/OBOFoundry.github.io#358]
http://www.obofoundry.org/principles/fp-006-textual-definitions.html

Is there any constrain on the metadata schema used for the definition? RDFS:isDefinedBy or any other specifically. Or is it just free text?

**Comment by cmungall** [comment]
All OBO ontologies use http://purl.obolibrary.org/obo/IAO_0000115

There is no principle stating this must be used, but everything will go more smoothly for interoperation of the same property is used here.

**Comment by nataled** [comment]
Closing since question was answered. However, this does raise a discussion point for the relevant principle, so this will be followed up by the Editorial Working Group.
