### ISSUE TITLE
Proposed change to fp-002, .owl should always resolve to an RDF syntax

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#360]
http://obofoundry.org/principles/fp-002-format.html

I think this is anti-user and bad. If an ontology is available only as manchester syntax, it forces the consumer to use the java OWLAPI as there is no other parser that will consume omn. Same goes for OWL/XML (not OWL/RDF-XML).

By all means keep the source in omn (or obo, or howl). But the main release purl for the .owl should be rdf-ttl or rdf-xml. These can be consumed by a wide variety of stacks in different languages.

**Comment by cmungall** [comment]
In https://github.com/PopulationAndCommunityOntology/pco/issues/43, @alanruttenberg suggests limiting to RDF/XML.

**Comment by jamesaoverton** [comment]
I agree. RDF/XML is the oldest and best supported of the relevant formats, and almost all of our projects are already using it for their releases. Making this *de facto* standard practise into a *de jure* standard practise would make our projects that much more consistent, which helps our users.

**Comment by mcourtot** [comment]
I agree. Do we have an idea of the number of projects *not* distributing rdf/xml? I'm sure there is a smart way to find this out that someone else will know...

**Comment by cmungall** [comment]
I think just sniffing the first 10 lines of every owl purl and manually 
examining is the fastest way. If we want a check we can try running 
through a jena script which will reject non-RDF formats.

**Comment by balhoff** [comment]
I agree that RDF/XML may be more widely supported than Turtle, but at the same time I think its horribleness has soured some people's perception of RDF. Turtle is so much better and also actively discourages poor practices like relying on specific RDF/XML structures within XML tools. However I suppose there is the chance people could also mistakenly rely on how particular triples in Turtle are clumped by subject...

**Comment by cmungall** [comment]
Yeh, I'm not sure that any of the non-RDF formats would be that much friendlier to many bio users.

This is intended to be more friendly: https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

but this would never be the canonical format from the `.owl` obviously, this would be a separate `.json`

**Comment by jamesaoverton** [comment]
If possible, we should pick one format. The current PR mentions both RDF-XML and OWL-XML, which are very different. I think RDF-XML is more common and better supported, but I don't have data to support that claim. While Turtle is nicer than both, I don't think we should start allowing it for the primary representation.

I agree with the rest of the PR.

**Comment by cmungall** [comment]
Concrete proposal: Change wording to say "the main `.owl` PURL MUST resolve to a valid RDF/XML file"

Indicate approval +1/-1 below

**Comment by nataled** [comment]
Principle has been revised as discussed, PR made and accepted. Changes are now public.
