### ISSUE TITLE
Noting which files merged into merged release

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#365]
_From @alanruttenberg on January 4, 2017 17:0_

Currently these are not noted. I suggest using annotation property "imported from" in an ontology annotation for each merged ontology, using the appropriate versionIRI. 

Adding ontology properties using the OWLAPI is ... not intuitive. Code available on request.

_Copied from original issue: OBOFoundry/Operations-Committee#196_

**Comment by nlharris** [comment]
Seems like maybe this was fixed and can be closed?

**Comment by jamesaoverton** [comment]
This is a better issue on the ROBOT tracker: https://github.com/ontodev/robot/issues/655
