### ISSUE TITLE
Hyperlink in left frame are cut short

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#37]
See for example http://obofoundry.github.io/ontology/chebi.html

Is there a way to have wrap around or something similar that would display the full link instead of cutting with '...'

cc @zhengj2007

**Comment by cmungall** [comment]
I couldn't figure out an immediate way to do it

Maybe there's a more optimal way to organize the information. Perhaps 
the PURL should be front an center in the header or in the right panel, 
with other URLs show with mouseover? Maybe two panels isn't the way to 
go? Feel free to experiment with different layouts (but major refactors 
should be done on a branch)

**Comment by mcourtot** [comment]
Do you know where the layout is configured? It seems to come from a css,
but I'm not sure which one and looking through is a bit tedious.

**Comment by cmungall** [comment]
it's a standard bootstrap grid, look for divs with classes col-md-NN, 
they should sum to 12 in each "row" class div.

**Comment by nlharris** [comment]
is this still relevant?

**Comment by nlharris** [comment]
i don't think this is an issue anymore.
