### ISSUE TITLE
New Planarian Ontology

### ISSUE THREAD

**Issue by srobb1** [OBOFoundry/OBOFoundry.github.io#377]
Hello,
I would like to submit a new anatomy and developmental stages ontology for planarians. Here is the github repository: https://github.com/obophenotype/planaria-ontology

**Comment by mcourtot** [comment]
HI @srobb1 - could you create a pull request as described at http://obofoundry.org/faq/how-do-i-edit-metadata.html?

You would also need to send an email to obo-discuss as described at http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html (note you don't need a PURL account anymore, so you can ignore that line), to allow a 2 weeks review by the community.

**Comment by srobb1** [comment]
Hi Melanie!

Thanks! i think I followed the instructions. Please let me know if I need
to do something differently or in addition to what I  have done. We are
really excited about getting our ontology out into the world in the right
way.

Thanks for you email!!
Sofia

**Comment by mcourtot** [comment]
Thanks Sofia - looks great. I'll set a reminder to check back in 2 weeks.

**Comment by jamesaoverton** [comment]
This was merged a long time ago as PLANA.
