### ISSUE TITLE
List of OWL links that not working at http://www.obofoundry.org/

### ISSUE THREAD

**Issue by weasteam** [OBOFoundry/OBOFoundry.github.io#380]
The link for these owl files does not work:

'http://purl.obolibrary.org/obo/bto.owl', 
'http://purl.obolibrary.org/obo/cheminf.owl', 
'http://purl.obolibrary.org/obo/ddanat.owl', 
'http://purl.obolibrary.org/obo/epo.owl', 
'http://purl.obolibrary.org/obo/exo.owl', 
'http://purl.obolibrary.org/obo/fix.owl', 
'http://purl.obolibrary.org/obo/idomal.owl', 
'http://purl.obolibrary.org/obo/mirnao.owl', 
'http://purl.obolibrary.org/obo/miro.owl', 
'http://purl.obolibrary.org/obo/mp.owl', 
'http://purl.obolibrary.org/obo/ogi.owl', 
'http://purl.obolibrary.org/obo/ogsf.owl', 
'http://purl.obolibrary.org/obo/sbo.owl', 
'http://purl.obolibrary.org/obo/sep.owl', 
'http://purl.obolibrary.org/obo/tads.owl', 
'http://purl.obolibrary.org/obo/tgma.owl'

**Comment by cmungall** [comment]
Some redundancy with #257, some are new

It's troubling that mp.owl does not work - it looks their ftp site is broken. @sbello do you know what is happening here?

**Comment by cmungall** [comment]
Ah, it looks like jax may have deprecated their ftp server, everything is served via http now. This is an improvement.. but our config needs updated, I will fix.

**Comment by cmungall** [comment]
* [ ] http://purl.obolibrary.org/obo/bto.owl - #381, #257
 * [x] http://purl.obolibrary.org/obo/cheminf.owl - #382, #257
 * [ ] http://purl.obolibrary.org/obo/ddanat.owl 
 * [ ] http://purl.obolibrary.org/obo/epo.owl 
 * [ ] http://purl.obolibrary.org/obo/exo.owl 
 * [ ] http://purl.obolibrary.org/obo/fix.owl 
 * [ ] http://purl.obolibrary.org/obo/idomal.owl 
 * [ ] http://purl.obolibrary.org/obo/mirnao.owl 
 * [ ] http://purl.obolibrary.org/obo/miro.owl 
 * [x] http://purl.obolibrary.org/obo/mp.owl - https://github.com/OBOFoundry/purl.obolibrary.org/pull/300
 * [ ] http://purl.obolibrary.org/obo/ogi.owl 
 * [ ] http://purl.obolibrary.org/obo/ogsf.owl 
 * [ ] http://purl.obolibrary.org/obo/sbo.owl 
 * [ ] http://purl.obolibrary.org/obo/sep.owl 
 * [ ] http://purl.obolibrary.org/obo/tads.owl 
 * [ ] http://purl.obolibrary.org/obo/tgma.owl

**Comment by cmungall** [comment]
Consolidating here: #257
