### ISSUE TITLE
Server Error on fetch

### ISSUE THREAD

**Issue by TomConlin** [OBOFoundry/OBOFoundry.github.io#386]
curl -L -v http://purl.obolibrary.org/obo/SO_0001483
    *   Trying 52.3.123.63...
    * Connected to purl.obolibrary.org (52.3.123.63) port 80 (#0)
    > GET /obo/SO_0001483 HTTP/1.1
    > Host: purl.obolibrary.org
    > User-Agent: curl/7.47.0
    > Accept: */*
    > 
    < HTTP/1.1 303 See Other
    < Date: Fri, 10 Feb 2017 06:00:25 GMT
    < Server: Apache/2.4.7 (Ubuntu)
    < Location: http://www.ontobee.org/browser/rdf.php?o=SO&iri=http://purl.obolibrary.org/obo/SO_0001483
    < Content-Length: 384
    < Content-Type: text/html; charset=iso-8859-1
    < 
    * Ignoring the response-body
    * Connection #0 to host purl.obolibrary.org left intact
    * Issue another request to this URL: 'http://www.ontobee.org/browser/rdf.php?o=SO&iri=http://purl.obolibrary.org/obo/SO_0001483'
    *   Trying 141.211.109.49...
    * Connected to www.ontobee.org (141.211.109.49) port 80 (#1)
    > GET /browser/rdf.php?o=SO&iri=http://purl.obolibrary.org/obo/SO_0001483 HTTP/1.1
    > Host: www.ontobee.org
    > User-Agent: curl/7.47.0
    > Accept: */*
    > 
    < HTTP/1.1 301 Moved Permanently
    < Date: Fri, 10 Feb 2017 06:00:25 GMT
    < Server: Apache/2.2.15 (Red Hat)
    < Location: http://www.ontobee.org/ontology/SO?iri=http://purl.obolibrary.org/obo/SO_0001483
    < Content-Length: 370
    < Connection: close
    < Content-Type: text/html; charset=iso-8859-1
    < 
    * Closing connection 1
    * Issue another request to this URL: 'http://www.ontobee.org/ontology/SO?iri=http://purl.obolibrary.org/obo/SO_0001483'
    * Hostname www.ontobee.org was found in DNS cache
    *   Trying 141.211.109.49...
    * Connected to www.ontobee.org (141.211.109.49) port 80 (#2)
    > GET /ontology/SO?iri=http://purl.obolibrary.org/obo/SO_0001483 HTTP/1.1
    > Host: www.ontobee.org
    > User-Agent: curl/7.47.0
    > Accept: */*
    > 
    * HTTP 1.0, assume close after body
    < HTTP/1.0 500 Internal Server Error
    < Date: Fri, 10 Feb 2017 06:00:26 GMT
    < Server: Apache/2.2.15 (Red Hat)
    < X-Powered-By: PHP/5.3.3
    < Content-Length: 0
    < Connection: close
    < Content-Type: text/html; charset=UTF-8
    < 
    * Closing connection 2

**Comment by mcourtot** [comment]
Seems to be an issue with Ontobee being down: https://github.com/OntoZoo/ontobee/issues/101
