### ISSUE TITLE
OWL Link error

### ISSUE THREAD

**Issue by weasteam** [OBOFoundry/OBOFoundry.github.io#388]
I have seen this error in multiple owl files but I am not sure how many of them:

This is the error from omit.owl

```
    <!-- http://purl.obolibrary.org/obo/OMIT_0001016 -->

    <owl:Class rdf:about="&obo;OMIT_0001016">
        <rdfs:label rdf:datatype="&xsd;string">Geographicals Category</rdfs:label>
        <rdfs:subClassOf rdf:resource="&obo;OMIT_0000110"/>
    </owl:Class>
```

These two lines are not correctly replaced:
<owl:Class rdf:about="`&obo;`OMIT_0001016">
<rdfs:subClassOf rdf:resource="`&obo;`OMIT_0000110"/>

**Comment by weasteam** [comment]
Ok, it is happening to ['agro', 'cdao', 'clo', 'cvdo', 'flu', 'genepio', 'geo', 'geo.owl/geo', 'mfmo', 'mfmo.owl#mfmo', 'mfoem', 'miapa', 'oae', 'ogg', 'ogms', 'omit']

**Comment by balhoff** [comment]
Hi @weasteam what do you mean "not correctly replaced"? Are you referring to the `&obo;`? That's an XML entity and is defined at the top of the file as `<!ENTITY obo "http://purl.obolibrary.org/obo/" >`. This file is parsed correctly by OWL API and Protege.

**Comment by weasteam** [comment]
Oh really?

I think it suppose to be `<owl:Class rdf:about="http://purl.obolibrary.org/obo/OMIT_0001016OMIT_0001016">` not `<owl:Class rdf:about="&obo;OMIT_0001016">`

**Comment by balhoff** [comment]
Those are equivalent. The entity substitution will be handled by an XML parser.

**Comment by weasteam** [comment]
I see, then please close the issue. I write my own parser and this give me a error. I will fix my code.

Thanks @balhoff

**Comment by balhoff** [comment]
Great, no problem. I avoid writing XML parsers whenever I can! :-)

**Comment by cmungall** [comment]
Please @weasteam don't write your own parser, that path will only end in pain. What language are you using?
