### ISSUE TITLE
ontologies missing products

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#391]
This dump is taken from the failed build once implementing the products check as per PR #390 
(checks are made only on non-obsolete ontologies)

- [ ] ERROR:No product tag: cmf -- a product is required for loading on OLS
- [x] ERROR:No product tag: mfomd -- a product is required for loading on OLS
- [x] ERROR:No product tag: micro -- a product is required for loading on OLS
- [x] ERROR:No product tag: ncit -- a product is required for loading on OLS
- [x] ERROR:No product tag: upheno -- a product is required for loading on OLS

**Comment by mcourtot** [comment]
Additional info for documentation: ontologies need a product tag, which then generates an ontology_purl stanza when the makefile is ran. OLS looks for the ontology_purl value in registry/ontologies.yml to load resources.

**Comment by nlharris** [comment]
What is the status of this?

**Comment by matentzn** [comment]
Its done. CMF does not have a products: section, but is marked as obsolete, so I will close.
