### ISSUE TITLE
New Sickle Cell Disease Ontology

### ISSUE THREAD

**Issue by JadeHotchkiss** [OBOFoundry/OBOFoundry.github.io#392]
Hi

I have already emailed obo-discuss for feedback about our ontology.
Here is our information again:

Prefix: SCDO

Title: Sickle Cell Disease Ontology

Short description: The purpose of the SCDO is to establish community standardized SCD terms and descriptions, establish canonical and hierarchical representation of knowledge on SCD, link to other ontologies and bodies of work.
We anticipate that the ontology will be the most comprehensive collection of knowledge in the SCD and will facilitate exploration of new scientific questions and ideas, facilitate seamless data sharing and collaborations including meta-analysis within the SDC community, support the building of databasing and clinical informatics in SCD.

Download link: https://github.com/scdodev/scdo-ontology/blob/master/data/scdo.owl

Home page: https://github.com/scdodev/scdo-ontology

Contact e-mail: Jade Hotchkiss, giant.plankton@gmail.com

Mailing list: scdodev@gmail.com

Tracker link: https://github.com/scdodev/scdo-ontology/issues

PURL user ID: scdodev

Our Website is available at: http://tesla.pasteur.tn/wordpress/

Thanks!
Jade Hotchkiss
(Curator for the SCDO)

**Comment by scdodev** [comment]
Hi
Please do re-look at the SCDO (see previous comment) in order to provide us with an OBO prefix.
Download owl file here: https://github.com/scdodev/scdo-ontology/blob/master/scdo.owl
Let me know if I need to email the obo-discuss list again as well.
Many thanks!
Jade

**Comment by nlharris** [comment]
somehow this never seems to have been looked at.

**Comment by bpeters42** [comment]
Dear Jade Hotchkiss, 

We want to apologize that this fell through the cracks on our side, which is completely our fault. Are you still interested in this namespace request? If so, is there updated information, or should we look at the original ticket? 

- Bjoern

**Comment by mellybelly** [comment]
Hi Jade, the OBO operations committee is hoping to assist in supporting greater reuse of OBO ontological content. We've discussed this in the past. Perhaps we can schedule a call to make a plan? @nicolevasilevsky may have been in touch regarding such an initiative more recently.

**Comment by ramonawalls** [comment]
I had a quick look through the ontology and below are a few suggestions. @mellybelly and her group can provide more detailed input.

1. Replace `SDCO` as the root class. The root should be OWL:think or draw from a more foundational ontology.

2. Disease term should come from existing ontologies such as DO or IDO.

3. Consider rooting your phenotype terms in PATO:quality for interoperability with other ontologies.

**Comment by JadeHotchkiss** [comment]
Thank you immensely for looking at it! I think you might have looked at the
older version though as it does now have owl:Thing as the root. You can use
the updated link I shared on the 19th Aug.
I do hope you will look again!

**Comment by nlharris** [comment]
Reminder to OBO Operations to take a look at this tomorrow. (I will miss tomorrow's meeting as I have jury duty.)

**Comment by matentzn** [comment]
@nicolevasilevsky made a detailed review here:
https://docs.google.com/spreadsheets/d/13vOaibPpo2m4u8jKDjF5_Z7sP_o2igblNLSgVyKwQ2o/edit#gid=0

We will discuss SCDO again at the operations call today, and come up with a final set of suggestions.

**Comment by ddooley** [comment]
SCDO has been accepted into the OBO Foundry!

**Comment by nlharris** [comment]
great! so can this ticket be closed?

**Comment by matentzn** [comment]
Not yet, as we still need to add the purl and metadata files.

**Comment by matentzn** [comment]
Alright, after some fun work with @JadeHotchkiss we
1) Migrated SCDO to using OBO style IDs
2) Replaced more than 680 terms that could be securely replaced with OBO ids (HP, DOID, etc)

Our work here is done I think, so I will close the ticket! There is still much more that could be done to make SCDO even more aligned - @JadeHotchkiss will continue to curate mappings to OBO ontologies, and eventually, we should look into helping SCDO setting up dynamic imports - but for now, this is a good start.

**Comment by nicolevasilevsky** [comment]
Nice work @JadeHotchkiss and @matentzn!
