### ISSUE TITLE
XAO OWL link not working

### ISSUE THREAD

**Issue by seger** [OBOFoundry/OBOFoundry.github.io#395]
The link provided at http://www.obofoundry.org/ontology/xao.html is not going to the ontology. Please note - a new version of the XAO was released 13 Jan 2017 and can be found at the same location as the previous one: https://raw.githubusercontent.com/xenopus-anatomy/xao/master/xenopus_anatomy.obo

**Comment by cmungall** [comment]
Looks like you build both obo and owl yourself. Click on the PURL link on your page and make  a pull request to go direct there rather than via the berkeley central build server

**Comment by cmungall** [comment]
Ah I see what the issue was. Follow the link above, a typo.

You can still redirect to yr github raw if you prefer, see obofoundry.org/faq/what-is-the-build-field.html for more docs

**Comment by cmungall** [comment]
Fixed!
