### ISSUE TITLE
Request for OHMI prefix and PURL 

### ISSUE THREAD

**Issue by yongqunh** [OBOFoundry/OBOFoundry.github.io#397]
Requested Prefix: OHMI 

Ontology Title: Ontology of Host-Microbiome Interactions

Download link: https://raw.githubusercontent.com/OHMI-ontology/OHMI/master/src/ohmi_merged.owl 
 
Home page: https://github.com/ohmi-ontology/ohmi   

Contact e-mail: yongqunh@med.umich.edu 

Mailing-list: ohmi-discuss@@googlegroups.com  

Tracker link: https://github.com/ohmi-ontology/ohmi/issues 

PURL user ID: yongqunhe 

Description: 
The purpose of the Ontology of Host-Microbiome Interactions is to ontologically represent and standardize various entities and relations related to microbiomes, microbiome host organisms (e.g., human and mouse), and the interactions between the hosts and microbiomes at different conditions.

**Comment by zhengj2007** [comment]
The request has been posted over a month. Since there is no objection, I'd like to add it in. Is it OK? @cmungall @jamesaoverton

**Comment by cmungall** [comment]
+1

**Comment by nataled** [comment]
(Closing old tickets) Prefix and PURL has been added.
