### ISSUE TITLE
Request for OARCS purl/prefix 

### ISSUE THREAD

**Issue by TGoepel** [OBOFoundry/OBOFoundry.github.io#399]
I have already emailed obo-discuss for feedback about our ontology.
I thus request prefix/purl for our Ontology of Arthropod Circulatory Systems - OArCS:

Prefix: OARCS

Title: Ontology of Arthropod Circulatory Systems

Short description: We present our Ontology of Arthropod Circulatory Systems (OArCS) which contains a comprehensive collection of 383 terms (i.e., labels) tied to 297 classes collected from the literature on
phenotypic aspects of circulatory organ features in arthropods. All of the concepts used in OArCS are based exclusively on structural features, and in the context of the ontology are independent of homology and functional assumptions. 

Download link: https://github.com/aszool/oarcs

Home page: http://oarcs.speciesfilegroup.org/

Contact e-mail: Torben Göpel, torben.goepel@googlemail.com

Mailing list: oarcs@googlegroups.com

Tracker link: https://github.com/aszool/oarcs/issues

PURL user ID: TGoepel

Best regards
Torben Göpel
(curator of OArCS)

**Comment by cmungall** [comment]
I merged #387 and we merged in the purl entry https://github.com/OBOFoundry/purl.obolibrary.org/pull/305, so we're done!

**Comment by cmungall** [comment]
by the way, you don't need a PURL-OCLC user ID anymore.

**Comment by nataled** [comment]
(Closing old tickets) Prefix and PURL has been added.
