### ISSUE TITLE
ontology term metadata

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#404]
Discussed on Mar 7, 2017 OBO operations committee meeting, it is proposed to create an ontology metadata file that include all the annotations (combine IAO ontology metadata and OBO format ontology metadata) that used by OBO Foundry community. It will improve ontology inoperable of OBO Foundry ontologies.

Current a subset of IAO, ontology-metadata.owl is created that has been used by some OBO Foundry ontologies to annotate an ontology terms.
http://purl.obolibrary.org/obo/iao/ontology-metadata.owl

However, there is a couple of issues:
1. not include all the annotations that ontologies developed in OBO format, such as exact synonym, related synonym, etc. 
2. the ontology metadata are intended for OBO Foundry community. So, it should be not under IAO domain.

Besides, it should also provide a user guide document associated with the metadata ontology.

Related document:
https://github.com/information-artifact-ontology/IAO/wiki/OntologyMetadata

**Comment by cmungall** [comment]
Should we start by making a branch in IAO? Or should this be managed outside IAO?

**Comment by zhengj2007** [comment]
Do you have any suggestion? If we want to manage it outside IAO, shall we create a repository under OBOFoundry github site?

**Comment by cmungall** [comment]
Separate for now, can always be folded in later?

**Comment by zhengj2007** [comment]
IAO ontology metadata:
      http://purl.obolibrary.org/obo/iao/2017-03-24/ontology-metadata.owl
with following commonly used OBO ontology metadata:
       has_broad_synonym
       has_exact_synonym
       has_narrow_synonym
       has_related_synonym
       in_subset
       database_cross_reference

The ontology metadata owl file is available on:
https://raw.githubusercontent.com/zhengj2007/obo-ontology-metadata/master/iao_ontology-metadata_obo.owl

Some IAO annotationProperties can consider to remove: such as antisymmetric property, editor preferred term.

Questions:
IAO: alternative term ?= oboInOwl:has_exact_synonym
IAO:in branch ?=  OBOinOWL:in_subset

**Comment by bpeters42** [comment]
Given that we as the OBO:operations group want to be able to implement whatever is decided by the OBO community, it seems wrong to rely on a single project as the distributor (=IAO)? But at the same time we want to continue using existing IRIs, which are in IAO. So just re-distribute existing classes, ask IAO for inclusion of new ones, but remain open to moving beyond IAO in case of conflicts? 

- Bjoern

**Comment by mellybelly** [comment]
imho:
IAO: alternative term != oboInOwl:has_exact_synonym
IAO:in branch != OBOinOWL:in_subset
though they may be used this way sometimes, I don't think one could guarantee it? Would be worthwhile to more of a usage review

**Comment by zhengj2007** [comment]
Thanks, Melissa.

Chris mentioned that:
IAO:alternative term = oboInOwl:has_synonym, will set other specific kinds of synonyms as its subProperty

**Comment by cmungall** [comment]
Note also that has_synonym is never asserted, one of the subproperties 
is always asserted.

**Comment by zhengj2007** [comment]
We also need to consider the language support in this discussion.

**Comment by zhengj2007** [comment]
This issue was moved to information-artifact-ontology/ontology-metadata#1
