### ISSUE TITLE
Guidelines for bundled ontologies, such as planteome.owl

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#405]
Planteome is a project that develops multiple ontologies for plants, including OBO ontologies like po, to, eo, as well as some not yet registered with OBO (species specific crop ontologies from bioversity). Of course, the ontologies also import portions of other OBO ontologies like CHEBI

We have an internal OWL file:
https://github.com/Planteome/planteome-core/blob/master/planteome.owl
(small, can be opened in a browser)

That imports this suite (directly or indirectly). The intent is that ontology portals that want a plant 'suite' can simply use this pre-collected set (Aber-OWL want this, cc @gkoutos, @leechuck).

Currently we don't have a purl for this. We could place this under any of our existing purls, e.g. `obo/{po,to}/planteome.owl` (we would then have this purl redirect to the raw file in github). This doesn't seem quite satisfactory, as the ontology 'sits above' these other ontologies and doesn't belong under any one of them. However, it's not a major issue and we could just have it live here. There is an argument that the trait ontology `to` is the correct space since it existentially depends on the others.

Another option is that we register a new OBO top level called 'planteome'. There is a precedent for these kinds of 'bundled' ontologies (which can be seen as a subset of what is sometimes called 'application ontologies'). E.g. bcgo. The purls would be /obo/planteome.owl (and the contents the same). New IDs could be minted in this space (for example, for bridging entities, but this may not be necessary here). The problem I see with this approach is that we end up cluttering and confusing the top level with these kinds of 'compilation' ontologies, but there would be a good argument for policing this space in an effective way, and worries may be mitigated by sufficient metadata. Portals should weight in here, as the presence of compilation ontologies can lead to duplication in loading, confusion in search etc, cc @simonjupp 

cc @jaiswalp @marieALaporte @cooperl09

**Comment by mellybelly** [comment]
Should do same for Monarch.owl!

**Comment by jaiswalp** [comment]
I like the top level approach. The question is shall we go by project name or by clade/species.

**Comment by cmungall** [comment]
I think project name, but any one project can choose to make as many 
species subsets as they like in their namespace.

Thus planteome may choose to have planteome/subsets/angiosperm/...

(we already do something like this for uberon, but just for anatomy)

**Comment by nlharris** [comment]
Is this done?

**Comment by cooperl09** [comment]
@nlharris  Yes this was done for Planteome back in 2017:
https://github.com/Planteome/planteome-core
I will work on updating it- It should be updated with each release
https://github.com/Planteome/planteome-core/issues/27
But, I wasn't sure if you are referring to the similar product for Monarch?

**Comment by nlharris** [comment]
I was just asking if this ticket can be closed, as part of my general ticket-cleanup campaign.

**Comment by cooperl09** [comment]
Yes, as far as I am concerned, it can be closed.

**Comment by cmungall** [comment]
OK for this to be closed but it's not fully resolved.

The question was whether to register an OBO namespace for planteome as a whole. This would be an application ontology that imports PO, TO, etc, but introduces no terms in the planteome namespace. Same for monarch, which would point to monarch.owl that imports various ontologies.

This would have a lot of advantages for the groups in question. There would be a convenient browsable endpoint for their bundle on OLS etc. Many groups (planteome, monarch) get around this by having their own amigo/OLS instance, but it would still be useful. 

There is obviously precedent for this as there are "application" ontologies that just combine existing ontologies into a convenient bundle. I don't know whether to encourage this as we could see an explosion of 100s of ontologies for different applications, but maybe not.

Anyway, fine for this to remain closed as it is subsumed by the current discussion led by @matentzn on obo-operations about application ontologies

**Comment by alanruttenberg** [comment]
My gut is to allocate the namespace. If we get a lot of these then we can
worry then about how to organize and present them.

Earlier I was thinking about landing pages that present various statements
where you proceed by clicking on the statement you identify as. In this
context I can think of statements like:

I plan to develop an ontology and want to learn. More about OBO principles.

I have data and am looking for an apporpriate ontology to help annotate or
structure it.

I am using an ontology but need to add terms related to ____

etc.

Depending on the statement chosen a suitable presentation style is chosen.

On Tuesday, December 1, 2020, Chris Mungall <notifications@github.com>
wrote:
> OK for this to be closed but it's not fully resolved.
>
> The question was whether to register an OBO namespace for planteome as a
whole. This would be an application ontology that imports PO, TO, etc, but
introduces no terms in the planteome namespace. Same for monarch, which
would point to monarch.owl that imports various ontologies.
>
> This would have a lot of advantages for the groups in question. There
would be a convenient browsable endpoint for their bundle on OLS etc. Many
groups (planteome, monarch) get around this by having their own amigo/OLS
instance, but it would still be useful.
>
> There is obviously precedent for this as there are "application"
ontologies that just combine existing ontologies into a convenient bundle.
I don't know whether to encourage this as we could see an explosion of 100s
of ontologies for different applications, but maybe not.
>
> Anyway, fine for this to remain closed as it is subsumed by the current
discussion led by @matentzn on obo-operations about application ontologies
