### ISSUE TITLE
How should OBO be cited?

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#409]
There is obviously the Smith et al 2007 paper, but this is 10 years old and predates the volunteer efforts of many people.

Should we encourage simply citing the URL obofoundry.org?

We could also make zenodo releases for snapshots of the registry

Once decided we should add a FAQ entry next to this one: http://obofoundry.org/docs/Citation.html

**Comment by matentzn** [comment]
This would be really amazing. I have created a snapshot that we are using for at least 2, perhaps 3 papers at the moment, and having a Zenodo way to just grab a snapshot of Zenodo would be a great help.

**Comment by matentzn** [comment]
Update: I have created a snapshot for our purposes.
https://doi.org/10.5281/zenodo.438635

You should also consider the appropriate license. I picked the most restrictive CC one (no deriv, no commercial). Let me know how it is preferred. If you started doing this yourself, which would be amazing, I would suggest to restrict yourself to one or maximum two snapshots per year. In the Empirical OWL community, we prefer to study one snapshot in depth rather than having to consider fresh ones all the time.

**Comment by mellybelly** [comment]
Lets also ensure that the relevant identifiers are up to date: Wikidata, GRID organizational IDs, BioSharing. Maybe we need to also write an NAR paper and/or get registered there? 

+1 on the citation policy

**Comment by cmungall** [comment]
Note my zenodo snapshot idea was just about the metadata - e.g. by doing a github release of this rpeo, tying it to zenodo (tho this would only have the source yaml metadata, if people wanted the derived rdf metadata then we'd go another route)

@matentzn made a snapshot of all ontologies, which is awesome. I will follow up on the separate ticket, and leave this one open for the citation Q

**Comment by nlharris** [comment]
see also #227

**Comment by nlharris** [comment]
We now have an OBO Foundry paper in biorxiv:
Jackson RC, Matentzoglu N, Overton JA, Vita R, Balhoff JP, Buttigieg PL, Carbon S, Courtot M, Diehl AD, Dooley D, Duncan W, Harris NL, Haendel MA, Lewis SE, Natale DA, Osumi-Sutherland D, Ruttenberg A, Schriml LM, Smith B, Stoeckert CJ, Vasilevsky NA, Walls RL, Zheng J, Mungall CJ, Peters B. OBO Foundry in 2021: Operationalizing Open Data Principles to Evaluate Ontologies. bioRxiv. 2021. p. 2021.06.01.446587. https://www.biorxiv.org/content/10.1101/2021.06.01.446587v1

Hopefully it will soon be accepted as a "real" publication, and then we can add it to the website! (Or we could add the preprint now.)

**Comment by cmungall** [comment]
https://academic.oup.com/database/article/doi/10.1093/database/baab069/6410158
