### ISSUE TITLE
OBO ontologies OWL 2 specification adherence

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#411]
Perhaps this is of low to no interest to you, but in case it is: 

I maintain an analysis of the OBO repository in [rpubs](http://rpubs.com/matentzn/obo). Apart from parsing errors and the likes, I also include an analysis of ontology sizes, levels of expressivities etc. I noticed that a large number of ontologies do not confirm to the OWL 2 DL spec, and fall under OWL Full. The analysis includes a breakdown of the violations of the OWL 2 specification. As far as I can see, fixing the most prominent violation should be fairly easy (version IRI not absolute), and push a majority of the Full ontologies back under DL..

**Comment by alanruttenberg** [comment]
Hey, this is very helpful!

I was looking at IAO, since I just did a release. (as usual at
http://purl.obolibrary.org/obo/iao.owl)

The complaint is:  UseOfUnknownDatatype:1 and the logic is given as OWL
full (presumably because of the datatype use?)
Could you let me know what the datatype in question is?

Unfortunately the profile checker is broken in the OWLAPI version I'm using
or I'd check it myself.
(https://github.com/owlcs/owlapi/issues/650)

A grep to find uses of datatypes finds:
- string
- anyURI
- boolean
- nonNegativeInteger

all of which are supposedly in the datatype map for OWL DL.

Thanks,
Alan

**Comment by alanruttenberg** [comment]
I note similarly that ncro gets the same report, and I similarly don't find the rogue datatype.

**Comment by matentzn** [comment]
Yeah, you are right! These profile checks are occasionally broken, therefore I would not say that they should be blindly fixed. A profile violation according to the OWL API is not necessarily a violation of the OWL 2 recommendation, only a strong piece of evidence towards it. There are also a number of almost irrelevant profile violations, such as missing declarations and so on.  We once tried to classify the violations (http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf).  I will generate a log file with all the details now (note that I am operating on a december snapshot of OBO).

With respect to  IAO, I have a xsd:date in there, perhaps derived from the this annotation:
<dc:date rdf:datatype="http://www.w3.org/2001/XMLSchema#date">2009-07-31</dc:date>

OWL2 does not have xsd:date: https://www.w3.org/TR/owl2-syntax/#Datatype_Maps (Table 3).
But I am not sure.

**Comment by matentzn** [comment]
Actually, thats it. You can replace the annotation like that: 

> <dc:date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2002-05-30T09:00:00</dc:date>

and you would be fine (remember to reformat the date so it is in the correct lexical space, as indicated above. So 2001-11-02 is not enough. However, I find this kind of an irrelevant violation, as this is about an ontology annotation. Up to you!

**Comment by alanruttenberg** [comment]
Thanks, I'll drop you a note to get a link to the log, as you suggest. 
Regarding xsd:date, it's used only in an ontology annotation, not in any axiom, so it wouldn't be considered a profile violation. If the OWLAPI is reporting it as so, then it would be good to file a bug report.  
The missing declarations are an interesting case. If the ontology is being written by the OWLAPI, I don't think that should happen. Worth checking if that's the case. When I looked at this last night I had some ideas about how the report might be made more useful for the developers. I'll try to organize my thoughts later and send you a note.

**Comment by matentzn** [comment]
Amazing. Lets do that. I should have said that I apply a minimum of fixing (like injecting missing declarations) before checking violations, but perhaps it would be better to just check the raw files. Let me know about what your ideas, and we will pull it off. With regard to the annotations, are you certain that ontology annotations are allowed to reference non owl datatypes? If you know a suitable passage in the spec, I will drive the issue with the OWL API developers.

**Comment by alanruttenberg** [comment]
Well, for example in [Datatype Maps](https://www.w3.org/TR/owl2-syntax/#Datatype_Maps) second paragraph, "A set of datatypes supported by a reasoner is called a datatype map." But the ontology axioms are extra-logical and so aren't seen by the reasoner. Or in [The Restrictions on the Axiom Closure], (https://www.w3.org/TR/owl2-syntax/#The_Restrictions_on_the_Axiom_Closure)"

>The set of axioms Ax satisfies the global restrictions of OWL 2 DL if all of the following conditions hold.

[snip]

>*Restrictions on Datatypes.*
>Each datatype occurring in Ax satisfies exactly one of the following conditions: it is rdfs:Literal, or it is  contained in the OWL 2 datatype map, or it is defined by a single datatype definition axiom in Ax.
>The conditions from the previous paragraph and the restrictions on datatypes in Section 11.2 require each datatype in an OWL 2 DL ontology to be rdfs:Literal, one of the datatypes from Section 4, or a datatype defined by means of a datatype definition (see Section 9.4).

On the other hand, there's "The rest of this section defines a particular datatype map called the OWL 2 datatype map, which lists the datatypes that can be used in OWL 2 ontologies",  which sounds like it might be restrictive, but it doesn't say "OWL 2 DL ontologies", and certainly it can't refer to OWL Full, so it can't be interpreted in a straightforward way.

Worse, perhaps in [Datatypes](https://www.w3.org/TR/owl2-syntax/#Datatypes) it says:

> An IRI used to identify a datatype in an OWL 2 DL ontology must be rdfs:Literal, or identify a datatype in the OWL 2 datatype map (see Section 4), or not be in the reserved vocabulary of OWL 2 (see Section 2.4).

> The conditions from the previous paragraph and the restrictions on datatypes in Section 11.2 require each datatype in an OWL 2 DL ontology to be rdfs:Literal, one of the datatypes from Section 4, or a datatype defined by means of a datatype definition (see Section 9.4). 

However xsd:date isn't in the reserved vocabulary, so the second second doesn't follow from the first.

I don't think that that the intention was that annotation values be constrained by the datatype map, but it might be an interesting discussion to have on https://lists.w3.org/Archives/Public/public-owl-comments/ if the OWLAPI devs don't agree. I did a quick search and didn't find any comments that addressed this particular question.

**Comment by alanruttenberg** [comment]
Maybe this will be answered by the devs as it interacts with an already filed OWLAPI bug report  https://github.com/owlcs/owlapi/issues/650

**Comment by sesuncedu** [comment]
There's a definition of datatype map that defines it as the types supported by a reasoner, and different reasoners support different types (to different degrees, even).
 Hermit is particularly strict on checking this, but the datatype map is not massively helpful, since owl and rdf 1.1 have diverged on literals. 

I still don't fully understand why the OWL WG was kept in being to wait for the xsd revisions but then wasn't allowed to add more of the types that could be given a usable interpretation, because process.

**Comment by alanruttenberg** [comment]
@sesuncedu Yes, the datatype map support can vary from reasoner to reasoner. The question here is whether it is ever applicable to *annotations*, which the reasoner never sees.

**Comment by sesuncedu** [comment]
I think that they are subject to profile restrictions, despite not being
officially visible to reasoners (though some have used annotations as
extension markers).

There are (eg) declaration requirements  on DL that are required to be
checked for profiles, which are non-logical and only required for rdf
parsing. So being logical isn't necessarily obligatory.

**Comment by matentzn** [comment]
I think we need to gather a list of the potentially problematic issues and then discuss them one by one. Perhaps we can get the OWL 2 editors to provide some clarification if we send all these issues as bulk. Another problem are repair strategies: Should we produce a recommendation for safe repairs? Or at least a tool that allows applying repairs one by one?

**Comment by alanruttenberg** [comment]
Good point about the non-logical requirements. I still have doubts about the annotations. Even if they are, I doubt that was what was intended.

**Comment by cmungall** [comment]
> I think we need to gather a list of the potentially problematic issues 
> and then discuss them one by one. Perhaps we can get the OWL 2 editors 
> to provide some clarification if we send all these issues as bulk. 
> Another problem are repair strategies: Should we produce a 
> recommendation for safe repairs? Or at least a tool that allows 
> applying repairs one by one?

We can add a repair command to ROBOT

**Comment by matentzn** [comment]
I have been trying to drive this issue forward for a [long time](http://ceur-ws.org/Vol-1265/owled2014_submission_9.pdf) now..

I suggest to move the discussion about the exact repair strategies to [here](https://github.com/owlcs/argo). Once we have a recommendation together plus a set of accepted safe repairs, we can put if forward to be included in ROBOT.

**Comment by matentzn** [comment]
@sesuncedu @alanruttenberg Opened a new threat for the [unkown datatypes in annotations](https://github.com/owlcs/argo/issues/2) discussion.

**Comment by nlharris** [comment]
Maybe now covered by dashboard?

**Comment by matentzn** [comment]
It is!
