### ISSUE TITLE
Supplying a regular snapshot of the OBO registry.

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#412]
In reference to [this issue](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/409) (comment 1), I would really appreciate regular (annual, bi-annual) obo registry snapshots on Zenodo. 

In the meantime, what is the absolute easiest way at the moment to get ALL OBO foundry ontologies (including previous versions, if any)?

**Comment by cmungall** [comment]
@simonjupp may have a way via OLS. You might also want to ask ontobee folks.

We should start making the snapshots. Note that we have mixed licenses to no license registered (sigh, #34). The global release would be unlicensed, but we could also make a CC-0 package and a CC-BY package (that subsumes the CC-0) package.

I hope to have a more definitive answer for you on our strategy in a month or two.

**Comment by cmungall** [comment]
@matentzn if you are connected with ORE, one thing to be aware of is that sometimes the default product is not the most expressive one. For example, with @dosumis I'm responsible for dictating the axiomatic subset of go.owl. We have opted to put the more expressive go-plus.owl as a separate product, for various reasons (e.g. import modules can get out of sync).

We're always looking for better solutions here.

One possibility is to mark some products as being the most expressive. We can imagine then building an OBO-ORE.owl

**Comment by nlharris** [comment]
Is this still needed, and if so, is there someone other than @cmungall who could work on this?

**Comment by matentzn** [comment]
I think we have other priorities now; it’s very easy to create a snapshot using the obofoundry yaml file, so let’s close this for now and revisit when it becomes interesting again!
