### ISSUE TITLE
Proposed Obsoletion: OMIT

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#418]
This ontology has very little metadata http://obofoundry.org/ontology/omit.html

No tracker

Does not parse with OWLAPI: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/410#issuecomment-296842404

**Comment by alanruttenberg** [comment]
Contact is Jingshan Huang. huang@southalabama.edu @Huang-OMIT ? You may want to talk with him about his future plans. I have helped maintain this ontology in the past and will look into the parsing issue.

**Comment by alanruttenberg** [comment]
The broken import has been fixed https://github.com/OmniSearch/omit/commit/eaad11c7bdc3914e26b0a78c5854a0e1f70ef0c5

I propose removing this ontology from the obsoletion list, pending discussion with Huang. 

http://purl.obolibrary.org/obo/omit.owl now loads without error.

**Comment by cmungall** [comment]
Thanks! It was never obsoleted. But it would be good to get confirmation from  @Huang-OMIT that the ontology is still active, and to update our metadata.

**Comment by alanruttenberg** [comment]
I have asked him to do so.

**Comment by Huang-OMIT** [comment]
@cmungall Chris: Nice to meet you here. Yes, the OMIT ontology is still active. And, I will work with Alan to update the metadata soon.

@alanruttenberg Thanks Alan for helping out!

**Comment by cmungall** [comment]
Can someone update the metadata here: http://obofoundry.org/ontology/omit.html

**Comment by Huang-OMIT** [comment]
@alanruttenberg Alan, could take care of the metadata? Thanks!

**Comment by cmungall** [comment]
If you can provide info here any of us can add:

Textual description, license, link to any papers, who is using it, link to repo and trackers

**Comment by Huang-OMIT** [comment]
Textual description: The purpose of the OMIT ontology is to establish data exchange standards in the microRNA (a.k.a. miR or miRNA) domain. Being an application ontology for miR regulation mechanisms in human disease including cancers, OMIT has the goal of serving as a common resource for annotations of diverse miR research, thus significantly enhancing integrative and comparative analysis of the myriad resources currently housed in disparate sources. The ontology development has strictly conformed to the biomedical ontology community standards, i.e., a set of OBO Foundry principles.

License: N/A

Link to papers: (1) http://www.jbiomedsem.com/content/7/1/25 (2) http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0100855

Who is using it: Biologists and bioinformaticians can make use of OMIT to leverage emerging semantic technologies in knowledge acquisition and discovery for more effective identification of important roles performed by miRs in human disease. Current users of OMIT are distributed among numerous institutions nationwide, including but not limited to: University of South Alabama, University of Utah School of Medicine, Georgetown University Medical Center, Mayo Clinic, Pennsylvania State University College of Medicine, University of Central Florida, and University at Buffalo.

Link to repo and trackers: https://github.com/OmniSearch/omit

@cmungall Thanks a lot!

**Comment by nlharris** [comment]
Is there anything else that needs to be addressed here, or can this issue be closed (as no longer relevant -- it seems that OMIT is not obsolete).
