### ISSUE TITLE
Changes to Foundry Page Main Heading - FAQ

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#426]
‘FAQ menu’: Add subheading for “Participate” (or other suitable name like ‘Register / Review my ontology’)
Place “How to register my ontology” there, and remove from ‘Metadata’ heading
Add “How do I request a review of my ontology”
Add “Where can I find ontology reviews”
Rename ‘Metadata’ with ‘Ontology display’

**Comment by nataled** [comment]
The link for "How do I request a review of my ontology" is http://obofoundry.org/docs/ReviewProcessGuidelines.html

The link for "Where can I find ontology reviews" is https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/CompletedReviews.md
(not sure how to make it go 'live' like other .md files)

**Comment by cmungall** [comment]
If anyone wants to take a crack at it: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_includes/navbar.html#L83-L108

**Comment by nataled** [comment]
Addressed during EWG call 2017-06-20.

**Comment by cmungall** [comment]
Thanks!

Remember

 - always link your commits to a ticket using `#NUMBER`
 - work on branches and make pull requests rather than directly to master

**Comment by nataled** [comment]
I'm confused as to the meaning of your first reminder. The second we debated about, and since none of us knew how to do pull requests but *did* know how to commit directly, we took the path of least resistance ;)

**Comment by cmungall** [comment]
> always link your commits to a ticket using #NUMBER

https://github.com/blog/957-introducing-issue-mentions
https://help.github.com/articles/closing-issues-via-commit-messages/

> and since none of us knew how to do pull requests

we have instructions here:
http://obofoundry.org/faq/how-do-i-edit-metadata.html

doesn't matter what content you're editing, same workflow if editing from the web.

If you're doing this from a git client and are running jekyll locally to test changes (not really necessary for things like this), then instructions will vary depending on what git client you're using. If you use the standard git command line client, you can consult the go editors guide: http://go-ontology.readthedocs.io/en/latest/

But really most of the time editing via the github web interface is totally fine and very easy. We can walk through this on a future call
