### ISSUE TITLE
Request for NCIT prefix

### ISSUE THREAD

**Issue by balhoff** [OBOFoundry/OBOFoundry.github.io#449]
Requested Prefix: NCIT
Ontology Title: NCI Thesaurus
Download link: work in progress

Home page: https://github.com/NCI-Thesaurus/thesaurus-obo-edition

Contact e-mail: balhoff@renci.org
Tracker link: https://github.com/NCI-Thesaurus/thesaurus-obo-edition/issues

Description:
This project aims to develop an OBO Library-friendly release of the NCI Thesaurus. Goals include adopting OBO conventions for term identifiers and ontology dereferencing, as well as improved semantic integration with existing OBO ontologies.

**Comment by balhoff** [comment]
cc @mellybelly

**Comment by balhoff** [comment]
Hi, I just wanted to follow up on the status of this request since it's been two weeks.

**Comment by zhengj2007** [comment]
@cmungall @jamesaoverton 
There is no objection. Shall we add it in? I can add yml and md file for it.

**Comment by cmungall** [comment]
+1

**Comment by jamesaoverton** [comment]
+1

**Comment by zhengj2007** [comment]
OK. I will work on it today.

**Comment by balhoff** [comment]
Hi @zhengj2007 I can make pull requests and have you check them if you like.

**Comment by balhoff** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/455

https://github.com/OBOFoundry/purl.obolibrary.org/pull/345

**Comment by zhengj2007** [comment]
@balhoff Thanks for working on it.

I found NCIT has been registered on OBO Foundry. Please see:
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/ncit.md

and related file on OBO website: http://www.obofoundry.org/ontology/ncit.html

It used different homepage. Is it the same one as you requested? If it is, you may consider to change the prefix.

**Comment by balhoff** [comment]
Hi @zhengj2007 it is the same project. I didn't realize there was already an entry for the "non-OBO" OWL version. But we are creating an official "OBO Library edition" for the NCIt, so it should be the one registered here.

**Comment by zhengj2007** [comment]
So we are done with the tracker since the registy is in OBO and @balhoff have added PURL.

@cmungall @jamesaoverton: shall we close it?
