### ISSUE TITLE
Create a PURL for derived metadata and obo_context.json file

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#452]
Would like to register
https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/obo_context.jsonld

Here
https://github.com/json-ld/json-ld.org/wiki/existing-contexts

But we should have a purl for the obo artefacts themselves, e.g. purl.obolibrary.org/registry/...

**Comment by nlharris** [comment]
https://github.com/OBOFoundry/purl.obolibrary.org/ exists -- does that mean this issue can be closed?

**Comment by jamesaoverton** [comment]
Fixed by https://github.com/OBOFoundry/purl.obolibrary.org/pull/428
