### ISSUE TITLE
gene ontology obo file served with wrong media type

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#454]
Reported at the gene ontology helpdesk but might be more appropriate here. It's served with content type rdf/xml. I wonder if this is an issue with any obo file served from S3.

https://github.com/geneontology/helpdesk/issues/44

**Comment by mcourtot** [comment]
See follow up at https://github.com/geneontology/pipeline/issues/8

**Comment by mcourtot** [comment]
An issue with GO and ticket is there - closing here.
