### ISSUE TITLE
Request for PURL: ECOCORE

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#459]
We would like to request the namespace "ECOCORE" in the OBO Foundry Library and the corresponding set of PURLS. 
requested prefix: ECOCORE
ontology title: Ecology Core Ontology
ontology download link: https://raw.githubusercontent.com/EcologicalSemantics/ecocore/master/ecocore.owl 
ontology home page: https://github.com/EcologicalSemantics/ecocore 
point person contact email: p.buttigieg@gmail.com  
ontology discussion mailing-list: ecology-core-ontology@googlegroups.com 
Ontology forum: https://groups.google.com/d/forum/ecology-core-ontology 
ontology issue tracker link: https://github.com/EcologicalSemantics/ecocore/issues 

The Ecology Core Ontology (ECOCORE) aims to provide core semantics for ecological entities, such as ecological functions (for predators, prey, etc), food webs, and ecological interactions. 

The need for ECOCORE has been expressed repeatedly over the past few years at workshops focused on ecological, environmental, and population-based semantics. Although several OBO library ontologies house terms that are important for ecology -- especially the Environment Ontology (ENVO), the Population and Community Ontology (PCO), and the Neuro-behavior Ontology (NBO) -- none of them fully covers the needed domains. ECOCORE not only provides a home for ecological interaction terms that fit poorly within PCO or other existing ontologies, but also serves as a single resource where ecologists can come to search for relevant terms.

Naturally, the ontology is importing existing semantics where relevant, and has begun to channel requests for improvement to the hosting ontologies to promote collaboration.

The first version of ECOCORE was built at the ClearEarth Hackathon, with input from ecologists, ontologists, and experts in natural language processing. The ontology was seeded with lists of terms generated as part of the hackathon. Refinement and curation of these initial terms is ongoing. We are happy to receive input from anyone wishing to use or contribute to ECOCORE via our issue tracker, mailing list, or forum.

Ramona Walls and Pier Luigi Buttigieg

**Comment by ramonawalls** [comment]
I have submitted pull requests for the ecocore.md and ecocore.yml files. I send an email to obo-discuss, but it got bounced back. I seem to recall that we are not using SourceForge for email any more, though.

**Comment by cmungall** [comment]
The sf list should be mirrored on the google group, but it's possible sf auto kicked you off.

**Comment by ramonawalls** [comment]
Hi technical WG members! It has been almost two weeks and no one has objected to this PURL request on obo-discuss. Well, it's true that no one has said anything, but I will take that as consent. Can I pull my own branch, or should someone else do it in this case for propriety's sake?

**Comment by mcourtot** [comment]
Hi Ramona,

I did the merge (I also prefer when someone else does it on records I
create)

Cheers,
Melanie

**Comment by ramonawalls** [comment]
Thanks, Melanie!
