### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#46]
Suggested by Erick Antezana on obo-discuss:
- add an extra button to retrieve metrics for a selected ontology: number of entries/classes, number of relationshios/properties, depth, ...

**Comment by mcourtot** [comment]
Would we be able to get that info from ontobee? Even if we were, is it worth maintaining on our side in addition?

**Comment by cmungall** [comment]
perhaps we could include some javascript widget that would query ontobee via sparql... but in short term I think we should leave dynamic derviced stats to the ontobee page itself, and encourage users to follow the link

**Comment by cmungall** [comment]
cc @easr

**Comment by cmungall** [comment]
Example on ontobee: http://www.ontobee.org/ontostat.php?ontology=GO

**Comment by nlharris** [comment]
this sound like it would be a nice feature, but not clear that anyone has time to implement it?

**Comment by nlharris** [comment]
see also #172

**Comment by nlharris** [comment]
I suggest closing this as "won't do" - ok?

**Comment by matentzn** [comment]
The Dashboard has ontology metrics https://dashboard.obofoundry.org/dashboard/cl/dashboard.html

I will close it and demand a chase to implement a solution!
