### ISSUE TITLE
Update metadata for OGMS

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#467]
http://obofoundry.org/ontology/ogms.html

 * [x] No license entered in the metadata, or in the ontology annotations. DONE #501 
 * [ ] Homepage listed as https://code.google.com/archive/p/ogms/, consider pointing to GH
 * [ ] The gcode homepage points to a dev version http://purl.obolibrary.org/obo/ogms/dev/ogms.owl this redirects to a 404 on google code
    * To fix: Click on the PURL link on the page to edit the PURL
 * [ ] Albert is listed as contact but Albert suggested it should be Sagar
 * [ ] The tracker is listed as github. I assume this is correct but there was some question on the list.

**Comment by alanruttenberg** [comment]
There is a meeting today to talk about OGMS management. I've just pointed out these issues as well, so someone, me if necessary, will fix them.

**Comment by zhengj2007** [comment]
Issues have been fixed:
1. homepage link pointed to git
2. tracker link pointed to git issue
3. contact person: Brian Aevermann
4. license added: cc-by 4.0
