### ISSUE TITLE
obo-discuss email lost between SF and Google?

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#469]
As mentioned in #459 

@ramonawalls sent an email to obo-discuss on SF and she said it bounced back. I do see it browsing obo-discuss google group at https://groups.google.com/d/msg/obo-discuss/uG1ETKYPfDA/V-qJ33BbBwAJ, but didn't get a copy in my mailbox. Could someone else check if they received it? @cmungall @jamesaoverton @zhengj2007 

Subject is "Request for PURL: ECOCORE" and it is dated August 19.

**Comment by zhengj2007** [comment]
I did not get a copy of it either. But I got the email that Ramona asked 
to get the ECOCORE in since she sent the request about 2 weeks ago.

Jie

**Comment by mcourtot** [comment]
Yes - I received the latter too, which came directly from github as it was with her PR. Thanks for checking @zhengj2007!

**Comment by cmungall** [comment]
Odd.

@ramonawalls did send an email to obo-discuss-sf, it was blocked my mailman as expected:

```
From: rlwalls2008@gmail.com on Thu Aug 17 22:37:09 2017
Subject: Request for PURL: ECOCORE
Cause: Post by non-member to a members-only list
```

This would have prevented it being mirrored. I just accepted it just now, so you should see something in your inboxes now with the sf-added prefix `[obo-discuss]`.

but as you point out it did go to obo-discuss-gg on Aug 18 as it's visible here: https://groups.google.com/forum/#!topic/obo-discuss/uG1ETKYPfDA

So I assume Ramona re-sent direction to the google group. However, I don't see the Aug 18 email in my own inbox, despite being subscribed to the google group.

**Comment by mcourtot** [comment]
I also didn't receive Robert's email at https://groups.google.com/forum/#!topic/obo-discuss/LCk_TathLAk

Not sure what is happening; nothing seemed amiss in the settings. Suggestions?

**Comment by mcourtot** [comment]
It seems both Robert and Ramona posted directly to the google group, while other messages I received went through the SF mirror.
Looking at permissions, we all seem to be subscribed with the "no email" flag, https://groups.google.com/forum/#!managemembers/obo-discuss/members/active

Great (not)... it seems that by default new members are set as 'no emails': https://productforums.google.com/forum/#!topic/apps/3OUlPmzKCi8 (just verified this with another one of my account)

So you think you're subscribed but you don't receive any email...

**Comment by mcourtot** [comment]
One workaround would be:
- ask people to join via https://groups.google.com/forum/#!forum/obo-discuss/join
- ask them to pay attention to email delivery option and set it to "receive all emails"

For existing users:
- those that are "no email" are switched to "all emails"
- those that are "abridged" remain as is

Thoughts?

@cmungall: you'll probably have the same issue with other G groups

**Comment by zhengj2007** [comment]
Sounds good to me.

I just realized that I have not joined obo-discuss google group yet and 
did it today.

Thanks, Melanie for checking it.

Jie

**Comment by cmungall** [comment]
@mcourtot - thanks, yes this was my problem (doh).

Is this really a new member setting? For me I explicitly switched off receiving emails many years ago because the mirroring was reciprocal and I chose to receive the emails via sf.

**Comment by mcourtot** [comment]
Yes I had the same 'no email' due to mirroring, butbin addition there is the issue that new members are 'no email' by default. As per Google 'to prevent spam' (see links above). I verified this by signing in with another of my account.

**Comment by ramonawalls** [comment]
This all makes sense now. Yes, I reposted the message directly in google
groups.

------------------------------------------------------
Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by nlharris** [comment]
i'm guessing this is no longer relevant?

**Comment by nlharris** [comment]
closing; reopen if needed
