### ISSUE TITLE
Add additional products for CHEBI

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#472]
We have this ticket to ensure all subsets are documented: #466 

Chebi produces different subset products (e.g. lite, core):

ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

These aren't described in the README:
ftp://ftp.ebi.ac.uk/pub/databases/chebi/README.txt

@G-Owen should these be registered? Do you have a description of the contents?

Chebi also produces a nightly snapshot, we can register this as a distinct product/PURL

**Comment by nlharris** [comment]
is this done? if not, does it still need to be done?

**Comment by matentzn** [comment]
It would make sense! I would not close it.

**Comment by nlharris** [comment]
but isn't this about an external ontology? should we flag @G-Owen again?

**Comment by cthoyt** [comment]
@matentzn note that there are now annotations for closed reasons - you can "close as completed" or "close as not planned"

**Comment by matentzn** [comment]
Thanks @cthoyt
