### ISSUE TITLE
slide documenting OBO Foundry governance practices

### ISSUE THREAD

**Issue by graybeal** [OBOFoundry/OBOFoundry.github.io#475]
For provision at the opening meeting of the Vocabulary and Semantics Special Interest Group of Research Data Alliance, can someone (like Chris :->) provide a slide showing an overview of the OBO Foundry governance practices?  This would be shown along with similar slides for other vocabularies and community models, as a way to encourage interest in the topic and get a Working Group started to consider in more detail.

**Comment by mcourtot** [comment]
Tagging @cmungall as per suggestion ;)

@graybeal: if you have an example/template from others that may help; afaik we don't have anything ready to go.

**Comment by graybeal** [comment]
I don't have an example so far; Chris and I spoke before I entered that, he expressed willingness to provide. As soon as I have an example in hand I will provide it.

**Comment by graybeal** [comment]
Here's an example. It's maybe not a current slide but gives a flavor. The OBO-flavored slide would have much more rigor, perhaps.

<img width="1036" alt="screen shot 2017-09-19 at 12 28 43 am" src="https://user-images.githubusercontent.com/1266896/30575843-8cf9c480-9cd1-11e7-8478-652c56c52ab6.png">

**Comment by graybeal** [comment]
Needed by end of day Tuesday, Europe time, in order to be useful. Thanks.

**Comment by cmungall** [comment]
I emailed you and Simon (having trouble uploading to google docs on a slow train wifi connection)

**Comment by cmungall** [comment]
![image](https://user-images.githubusercontent.com/50745/30602490-97eac4da-9d5c-11e7-8e35-d8cfdf5f5f49.png)

**Comment by cmungall** [comment]
I didn't have time to clarify exactly what you meant by governance - e.g. technical or managerial, governance of individual ontologies vs governance of foundry. Just went with high level overview going by your ICD example, HTH

**Comment by graybeal** [comment]
I think it is great -- I assume the GitHub process is included in 'maintenance'?

**Comment by cmungall** [comment]
On 19 Sep 2017, at 20:19, John Graybeal wrote:

> I think it is great -- I assume the GitHub process is included in 
> 'maintenance'?

Nah, the maintenance principle is more about no abandonware. Formally we 
don't have any principle that states you can't manage your ontology on a 
floppy disk -- but we'd advise strongly against it.

I added something on the google slide under the activities of the 
Technical WG, we provide assistance in tools, workflows, etc, 
encompassing github. Basically all the stuff I presented at ICBO: 
https://docs.google.com/presentation/d/1JPAaDl6Nitxet9NVqWI30eIygcerYAjdMIGmxbRtIn0/edit?usp=sharing

**Comment by mcourtot** [comment]
Looks great! Do we have numbers to add, e.g., number ontologies, classes? May not be needed for this , but it'd be good to have somewhere.

**Comment by zhengj2007** [comment]
+1 Melanie.

**Comment by cmungall** [comment]
I'll close this for now, open another ticket for generating stats (which will obviously change over time)
