### ISSUE TITLE
Retire SettingUpProtege page

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#476]
is outdated, has broken links.

http://obofoundry.org/docs/SettingUpProtege.html

Consider instead just linking to: http://go-protege-tutorial.readthedocs.io/en/latest/Entities.html#new-entities

or: https://github.com/jamesaoverton/obo-tutorial/blob/master/docs/names.md

**Comment by mcourtot** [comment]
I think this is outside our scope - maybe a general page with useful links?

**Comment by nlharris** [comment]
See also #114

**Comment by nlharris** [comment]
I agree with @mcourtot -- we aren't responsible for providing Protege documentation. In two PRs, replaced the link (in the two places I found it) with a link to our resources page.
