### ISSUE TITLE
Define a distinct ontology product that includes all axioms for an ontology but no external axioms

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#483]
See comments from @balhoff here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/482#issuecomment-329517023

OBO should formally define this type of product and have a recommended standard PURL for this.

**Comment by matentzn** [comment]
This has been specified in https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md

as the base release. Already implemented widely. Closing
