### ISSUE TITLE
Proposed: Policy to help avoid losing access to an ontology repository

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/OBOFoundry.github.io#485]
@jonathanbona wanted to edit on the OGMS repository and so asked me for access. While I used to have at least write access, that was removed for reasons unknown, and there's been some trouble finding who has enough permission to add new editors.

Github doesn't make it possible to email or know who owners are, AFAIK, and this suggests a real possibility of project repositories becoming inaccessible when project members go on.

I think it would be good to draft some guidelines around this. Some ideas:
 - Have an OBO technical committee generic user on Github, with at least a couple of active members of the working group having access to it. We have obofoundry.operations@gmail.com, which can be the user name/email.
- Recommend, for new OBO ontologies, that this user be one of the owners on repositories, and require it for Foundry ones, as a failsafe for cases where access to a repo becomes problematic.
- Advertise, on the Readme, how administration of the repo works and who the relevant contacts are.

While losing access to a repository doesn't have to get in the way of development - purls are administered by separate authentication, and one can always fork the repository, having the old repository present can confuse users who search for a repository or submit issues, and without write access we can't even add a banner telling them where the currently active repository is.

**Comment by cmungall** [comment]
This is the OGMS issue: #467 -- so far no one from OGMS has commented on it, still don't know who the contact is.

We want to avoid people doing routine operations using a generic user. Do you want to amend your proposal to make it clear that this is only to be used for 'emergency rescue'? After that, ping the list for comments?

**Comment by alanruttenberg** [comment]
Richard Scheuermann has a new hire who will manage the repo, and he has fixed the permissions issue, adding several owners and members to the organization.

Intention was emergency use, yes, so no problem making that explicit. Do you mean obo-discuss?

**Comment by cmungall** [comment]
> Do you mean obo-discuss?

I meant obo-coordinators but happy for more transparency

**Comment by nlharris** [comment]
do we want to keep this issue open?

**Comment by nlharris** [comment]
no one said yes when i asked nearly two years ago, so i'm closing.
