### ISSUE TITLE
Switching BioPortal's OBO Library ontologies from OBO to OWL

### ISSUE THREAD

**Issue by jvendetti** [OBOFoundry/OBOFoundry.github.io#491]
[BioPortal](http://bioportal.bioontology.org/) is currently serving quite a few OBO Foundry / Library ontologies in OBO format (complete list provided below). Should any of these ontologies be modified in BioPortal to serve OWL format instead?

aeo
apo
bspo
bto
caro
chebi
cml
ddanat
eco
ehdaa2
eo
exo
fao
fbbi
fbbt
fbdv
fix
fypo
gaz
go
hom
hp
idomal
ma
miro
mmo
mod
mp
mpath
ms
omp
pato
po
pr
pw
rex
rnao
rs
rxno
sbo
sep
spd
tads
taxrank
tgma
trans
tto
uo
vario
vt
wbbt
wbls
wbphenotype
xao
xco
zfa

**Comment by mcourtot** [comment]
Hi @jvendetti - it would probably be better to send an email out to obo-discuss@googlegroups.com as not all ontology providers monitor this git repo AFAIK.

**Comment by jvendetti** [comment]
Thanks for the feedback @mcourtot. My manager @graybeal will post to obo-discuss.

**Comment by graybeal** [comment]
emailed per above. comments welcome to this list or to me and @jvendetti personally.

**Comment by cmungall** [comment]
I suggest we add an optional tag `preferred_for` in the yaml, with an extensible set of possible values, starting with `bioportal`

**Comment by graybeal** [comment]
Sorry, not sure about the purpose of this tag. A little more detail?

**Comment by cmungall** [comment]
The idea is that bioportal (and all portals would default to the canonical PURL (ie OWL)), but this would provide an exception mechanism. Of course you could manage the exceptions at the bioportal level which would be fine too.

**Comment by nlharris** [comment]
Is this still something that should be done?

**Comment by graybeal** [comment]
It might be useful, but I confess I'm still not clear on the following:

> The idea is that bioportal (and all portals would default to the canonical PURL (ie OWL)), but this would provide an exception mechanism. Of course you could manage the exceptions at the bioportal level which would be fine too.

I don't know what the 'canonical PURL' means. (This is likely because I'm a little unsure how the OBO pipeline works, and whether it's the same for all ontologies or different for ones that are managed independently of the pipeline.) In my world either there's an ontology or some other mechanism in the artifact) that defines its namespace, in which case that's the canonical IRI, but any PURL creation by repos is not part of that spec; or the artifact doesn't define its namespace, in which case it's the wild west, and there's still no 'canonical PURL', or any other canonical IRI.

Perhaps some example(s) could illustrate the idea Chris is describing?

**Comment by matentzn** [comment]
The way that I read this issue, the idea is this:

OBO foundry is now defaulting to OWL, so the 'canonical purl' is 

http://purl.obolibrary.org/obo/hp.owl
http://purl.obolibrary.org/obo/go.owl
http://purl.obolibrary.org/obo/pato.owl

This is what any tool that handles the entirety of the OBOFoundry, including OLS and Bioportal, should use by default for their browsers (as opposed to: `http://purl.obolibrary.org/obo/hp.obo`).

The @cmungall suggestion here is that ontology owners can say:

"For my ontology, please use obo format on bioportal". The mechanism (which is probably not set in stone) would be to say:

item: http://purl.obolibrary.org/obo/pato.obo
          preferred_for: 
                    - bioportal
                    - ols

My opinion is that this puts an undue burden on the maintenance of the OBO metadata, which is already rich, and this is better handled at application (OLS, Bioportal) level. OLS for example has its own configs, that allows to overwrite the default http://purl.obolibrary.org/obo/pato.owl OBO PURL with something else (like http://purl.obolibrary.org/obo/pato.obo). So a user that does not like the display in OLS contacts OLS directly and they change the ontology URL to wherever the user says. But this is my two cents - my opinion here is only very weakly in support of itself.

**Comment by graybeal** [comment]
Thanks @matentzn  with that explanation it makes perfect sense to me now.

I appreciate your reasoning, and like you I don't have a strong conviction here. The attractive thing about Chris's proposal is that it provides a point of documentation that everyone can refer to, which helps resolve questions about "why is this not represented consistently?", even within each repository support team. 

Given your point about burdening of OBO metadata, there's a lot to be said for documenting it within each presenting repository. Ideally that would be a publicly visible document for all the ontologies, like https://github.com/ncbo/ncbo.github.io/blob/master/oboids_to_bpacronyms.json. But it does mean the owner has to express a preference to each of the repositories. 

In the end, it's probably impossible for the owner to know the best presentation in each repository while he or she is working on the ontology, as the repos evolve over time. So at most the owner could express a general preference in the OBO metadata. 

In the end, my two cents is that this doesn't add enough value to be worth the implementation cost. It affects too few people/ontologies.

**Comment by matentzn** [comment]
Sounds we agree @graybeal So do you think we should close the issue for now? We can always revisit this when there is a more compelling user request or use case scenario?

**Comment by graybeal** [comment]
I'm OK with that, if @cmungall doesn't have an issue.
