### ISSUE TITLE
Monitor resources

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#493]
Possible to ping PURLs to check if they're up on a regular basis?

**Comment by jamesaoverton** [comment]
Yes, it's possible, and it's a good idea. See https://github.com/OBOFoundry/purl.obolibrary.org/issues/104

**Comment by nlharris** [comment]
This issue seems very stale; ok to close?

**Comment by matentzn** [comment]
Its ok to close, as the functionality is now covered by the OBO Dashboard, at least for the main ont.owl PURLs. This is as much as we can cover as OBO Foundry I think!
