### ISSUE TITLE
Add principles

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#5]

**Comment by cmungall** [comment]
On the ops call today we decided to try and aggregate information from multiple places, e.g. the old wiki, try having principles integrated with main site.

Will see if it is possible to pull wiki history for each principle, if not, top skim

**Comment by cmungall** [comment]
To export
http://wiki.obofoundry.org/wiki/index.php?title=Special:Export&action=submit

in category box, enter "Principles"

Can then be converted with:
https://github.com/philipashlock/mediawiki-to-markdown

**Comment by cmungall** [comment]
First pass:
http://obofoundry.github.io/principles/fp-001-open.html

did not seem to be easy way to capture history; top skimmed

todo:

 * fix blockquotes
 * concat pages into summary table
 * make it look more attractive. Consider having all principles listed in left panel.
 * consider enabling disqus for each page

**Comment by cstoeckert** [comment]
A prominent link to the Principles should be provided either from the Project Home (e.g., on left panel) or included in the top menu with About, Ontologies, Participate, etc. (drop down menu could list all principles) or both.

**Comment by cmungall** [comment]
Calling this done
