### ISSUE TITLE
Foundry web site OFOC "Membership" page text

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#514]
Proposed new text for the Membership.md page (to replace the introductory blurb):

“The OBO Foundry Operations Committee discusses, oversees, and--in concert with the working groups--ensures the completion of the fundamental day-to-day activities of the Foundry. Anyone who is active in a working group (active being based on both attendance at WG meetings and actual work done for working groups) is considered a member of the Operations Committee.”

Comments and revisions welcome. Will be discussed and finalized at next OC meeting.

**Comment by ramonawalls** [comment]
Possible change:

“The OBO Foundry Operations Committee discusses, oversees, and ensures the completion of the fundamental day-to-day activities of the Foundry. The Operations is composed of three working groups. Anyone who is active in a working group (active being based on both attendance at WG meetings and actual work done for working groups) is considered a member of the Operations Committee.”

**Comment by cmungall** [comment]
I suggets going to 
http://obofoundry.org/docs/Membership.html

click Edit and make a PR

**Comment by lschriml** [comment]
OBO Operations committee meeting, on Jan 23rd, 2018 approves this wording, the latest variants: 
  Action Item: Darren will make this update.

**Comment by nataled** [comment]
Turns out the update was already done some time ago.
