### ISSUE TITLE
Request for ARO prefix and Purl

### ISSUE THREAD

**Issue by arpcard** [OBOFoundry/OBOFoundry.github.io#516]
We’d like to request a new PURL and prefix for the Antibiotic Resistance Ontology (ARO). Here is the information: 

**Ontology title:** Antibiotic Resistance Ontology
**Requested prefix:** ARO
**Download link:** https://raw.githubusercontent.com/arpcard/aro/master/aro.owl
**Homepage:** https://github.com/arpcard/aro
**Contact email:** card@mcmaster.ca
**Mailing-list:** https://mailman.mcmaster.ca/mailman/listinfo/card-l
**Tracker link:** https://github.com/arpcard/aro/issues
**PURL username:** arpcard

**Description:** 
The Antibiotic Resistance Ontology describes antibiotic resistance genes and mutations, their products, mechanisms, and associated phenotypes, as well as antibiotics and their molecular targets. It is integrated with the Comprehensive Antibiotic Resistance Database (https://card.mcmaster.ca), a curated resource containing high quality reference data on the molecular basis of antimicrobial resistance.

Thanks!

**Comment by tophat8855** [comment]
Hi @arpcard ! I saw this issue and made a [PR](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/518). Let's hope they accept and merge. 👍

**Comment by mcourtot** [comment]
Great to see the request!
I don't anticipate an issue but we need to wait 2 weeks before merging to allow comments from the community. I'll set a reminder to merge on Nov 29th. 

Thanks for creating a PR; could you please update it to match existing format? See for example https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/ontology/iao.md
I don't think ontology_purl will work for example - you could use source_url or the products type of construct . Also, it'd be great to include license information if possible.

**Comment by mcourtot** [comment]
@tophat8855: would you mind creating a PR for the PURL as well? See for example https://github.com/OBOFoundry/purl.obolibrary.org/pull/348/files

Thanks!

**Comment by cmungall** [comment]
Thanks for your request.

I note that the ontology contains many entities described in other ontologies or databases. Do you have a reason for not importing e.g. CHEBI:7507 for neomycin?

Much of the ontology appears to be a knowledge base of genes and their interactions. This seems very useful. Have you considered cross-referencing your gene/protein entries to standard gene/protein databases, or even reusing the IDs?

**Comment by tophat8855** [comment]
@mcourtot Will do! Thanks for the links.

**Comment by arpcard** [comment]
@cmungall Replacing these terms with CHEBI accessions is one of our top priorities; I would anticipate this happening in January. We have not looked into cross-referencing our gene entries to gene databases.

**Comment by arpcard** [comment]
Is this now eligible to be merged?

**Comment by mcourtot** [comment]
Can you discuss/agree on a license? See http://obofoundry.org/principles/fp-001-open.html

**Comment by arpcard** [comment]
Working on it! We will move the ARO out of McMaster’s standard license to one of the options in http://obofoundry.org/principles/fp-001-open.html shortly.

**Comment by arpcard** [comment]
@mcourtot the Antibiotic Resistance Ontology at the Comprehensive Antibiotic Resistance Database is now freely available under the Creative Commons CC-BY license version 4.0, including the copy available at GitHub. We have also updated the obo and owl files at GitHub for the February 2018 release.

**Comment by mcourtot** [comment]
Fantastic news! I have updated the file at https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/aro.md
