### ISSUE TITLE
CHEMINF repository links moved

### ISSUE THREAD

**Issue by donpellegrino** [OBOFoundry/OBOFoundry.github.io#519]
It seems that the CHEMINF repository was moved from a user repository at https://github.com/egonw/semanticchemistry to an organization repository at https://github.com/semanticchemistry/semanticchemistry. The OBOFoundry metadata and source links (http://obofoundry.org/ontology/cheminf.html) need to updated to point to the organization repository.

**Comment by egonw** [comment]
https://github.com/egonw/semanticchemistry was just a temporary thing to test the migration...
