### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by nalishan** [OBOFoundry/OBOFoundry.github.io#522]
hi
As a student interested in developing biomedical ontologies, I'm going to introduce OBO Foundry in a paper in Persian language. On the home page of the foundry, there are three background colors for the ontologies listed in a table. As far as I could guess, the light blue background is for members of the Foundry which fully met the principles, the gray background is for obsolete ontologies. However, I am not sure about the ontologies with white background?! There is a long list of ontologies in the white background area!
I would like somebody to show me the ropes! 
I may also need to have a co-author to support me in writing the paper! 
Best regards
Nader Alishan

**Comment by cmungall** [comment]
My personal recommendation would be to ignore the difference between blue and white for now, and treat the full set of non-obsolete ontologies as OBO library ontologies. At some point the review process will start again and the foundry/non-foundry distinction may become meaningful.

**Comment by nalishan** [comment]
Thanks!

**Comment by nalishan** [comment]
There's a newly published work entitled **Preliminary Analysis of the OBO Foundry Ontologies and Their Evolution Using OQuaRE** which says: "The ontologies of the OBO repository are either member or
candidate ontologies". is it true?

However, I do accept your recommendation!
Cheers!
Nader

**Comment by cmungall** [comment]
It's not inaccurate
