### ISSUE TITLE
update principle 1 (open) text to ensure license is in ontology header

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#523]
The text of http://www.obofoundry.org/principles/fp-001-open.html needs to be updated to state that the ontology license should be both in the ontology header (for OWL ontologies - can't do for OBO) and un the ontology metadata at https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology. 

Ontologies are responsible for maintaining their .md file, but can ask for help.

**Comment by ramonawalls** [comment]
We discussed this today at the Editorial call, and we aren't convinced of the value of having people provide the information in two places. How hard would it be to automate providing the information in the metadata file?

**Comment by mellybelly** [comment]
This is what I suggested in the email thread, +1 to automating population of the website/metadata file

**Comment by cmungall** [comment]
When I get a chance I will make a PR to http://www.obofoundry.org/principles/fp-001-open.html

because this isn't very clear at the moment, especially those who keep source in obo

E.g.

"the license in a separate annotation, which can be converted to a dc:license statement if the ontology is converted to OWL - see Examples (below)"

no example is given.

I think just providing links to versioned source code in github of actual ontologies is best. Easiest to lead by example.

**Comment by cmungall** [comment]
Automating population of metadata: see #515

**Comment by jonquet** [comment]
To me, using the ontology file is the best place to store the metadata. Especially with OWL ontologies. 
Especially, it would allow all the libraries and repositories that automatically pull ontologies from the Foundry to populate automatically their metadata by extracting them all from the ontology file. 

I know this this not the current practice for the OBO Community that edit the metadata on the side in the .md file but honestly this would be the best way to be sure the metadata is :

- not separated from the main data (i.e. the ontology);
- not repeated in multiple places (with the risk of being inconsistent);
- semantically consistent throughout the different libraries and ontologies.

You gonna tell me: "But we do not always know which semantic web property to use to describe this and that about our ontology" YES, it might be true and there is a lot of metadata vocabularies relevant for ontologies (we recently identified 23). You can refer to that list 
https://github.com/agroportal/documentation/tree/master/metadata
to pick up metadata properties. 
Or simply use the ones suggested in: http://obofoundry.github.io/registry/context.jsonld

In AgroPortal we have been working on this over the last 2 years. We parse now more than 350 properties and will populate a model of 124 properties with them. The metadata is then automatically added to the record in AgroPortal (call the ontology submission) and you can complete it manually with a new UI
 If you edit manually the metadata, you can click a "Get my metadata back" and get a chunk of code to copy/paste directly in your ontology file, for other libraries to benefit from it when parsing the next version.

Check out GO for instance: http://agroportal.lirmm.fr/ontologies/GO
And the automatically built Landscape page: http://agroportal.lirmm.fr/landscape

For more information see : https://github.com/agroportal/documentation/wiki/Ontology-metadata

**Comment by jonquet** [comment]
I forgot: 
Ultimalty we are working with the Protégé folks to incorporate more metadata edition feature within Protégé. 

We are also working now on a new metadata vocabulary that will harmonize, and choose the properties: 
https://github.com/sifrproject/MOD-Ontology
and
http://www.lirmm.fr/~jonquet/publications/documents/Article_MTSR-2017_MOD1.2.pdf

And finally, we are having a Task group under the umbrella of the RDA VSSIG to work on ontology metadata standardization. This is currently getting started:
https://www.rd-alliance.org/groups/vocabulary-services-interest-group.html

**Comment by cmungall** [comment]
> To me, using the ontology file is the best place to store the metadata. Especially with OWL ontologies.

Yes, but I anticipate OBO keeping our own metadata for these fields for the immediate future. It will take a long time for people to switch over, and even when they do there is no guarantee that this will be maintained or errors stopped from being introduced etc. We'll need a suite e.g. in robot that people can use locally.

For now it's easy to check for asynchronies and we can follow up on the OBO site. We have a script in the repo to do this, we just need to set up a jenkins job: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/515

**Comment by cmungall** [comment]
We need to improve the docs for people with .obo source on how to fix their metadata. Some will be using Protege where this will be easy, others will use OE still, where hand-edits are necessary.

I provided an example of how to do this using the GO source:
https://github.com/geneontology/go-ontology/pull/14624

One thing we could do to help is go and make PRs on individual ontology repos

**Comment by cmungall** [comment]
We have a FAQ entry for editing in the metadata on the obo site: http://obofoundry.org/faq/how-do-i-edit-metadata.html

We can add on to this info on how to update the metadata at source

**Comment by cmungall** [comment]
The text of fp1 needs to be updated to take into account #540

**Comment by nataled** [comment]
Documentation at http://www.obofoundry.org/principles/fp-001-open.html has been updated to reflect the correct prefix and purls. Also noted on ticket #540
