### ISSUE TITLE
Custom pages in GitHub Pages should be used for 404s

### ISSUE THREAD

**Issue by kltm** [OBOFoundry/OBOFoundry.github.io#524]
Given that there are many URLs in the wild like
http://www.obofoundry.org/cgi-bin/detail.cgi?id=brenda ,
it would be best to configure the GitHub Pages 404s to either contain a search, an explanation and link, or to forward to the top-level page with a warning.
E.g.: https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by jamesaoverton** [comment]
See also https://github.com/OBOFoundry/purl.obolibrary.org/issues/7

**Comment by nlharris** [comment]
yes, this would be nice...but is it ever going to percolate to the top of anyone's to-do list?

**Comment by nlharris** [comment]
honestly, most websites don't have custom pages for 404s. in fact, if you go to a github URL that you don't have access to, you don't even get an "access denied" message -- you get a generic 404! so you can't tell whether the URL was wrong or whether you don't have the necessary permissions to see it.

given that, i can't imagine we're going to ever devote the resources to implementing this improvement. i will leave this issue open for now but if no one defends it, i'll close it next time i do a sweep of old issues.
