### ISSUE TITLE
Orphanet PURLs not resolving?

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#526]
http://purl.obolibrary.org/obo/Orphanet_768

**Comment by jamesaoverton** [comment]
There's no "Orphanet" project in the [OBO registry](https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology) or our [PURL system](https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config).

**Comment by mcourtot** [comment]
That would explain it. I need to find out where that IRI comes from - may
be on my side. thanks James!

**Comment by cmungall** [comment]
I'll bet this is to do with the fact that OLS uses

**Comment by mcourtot** [comment]
Happy to blame you if it helps ;) To be fair I'm sure it is an issue somewhere in the BioSamples pipeline which means we end up with 2 different IRIs for Orphanet terms, the official one and the "OBO style" one. I'll follow up on our side and will make sure to report to you if it needs be.
