### ISSUE TITLE
Page not showing for FBdv

### ISSUE THREAD

**Issue by mmc46** [OBOFoundry/OBOFoundry.github.io#53]
Clicking on details for FBdv shows only this sentence at the top of the page

"A structured controlled vocabulary of the development of Drosophila melanogaster."

http://obofoundry.github.io/ontology/fbdv.html

I'd like to update the details, but I'm not able to.

**Comment by mcourtot** [comment]
Hi Maria - please try again; I added the layout declaration for the fbdv.md file and it seems to show up properly now.
Cheers,
Melanie
