### ISSUE TITLE
Request for EUPATH prefix and Purl 

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#532]
We’d like to request a new PURL and prefix for the EuPath Ontology (EUPATH) in the OBO Foundry Library. Here is the information:

Ontology title: EuPath Ontology
Requested prefix: EUPATH
Download link: https://raw.githubusercontent.com/EuPath-ontology/EuPath-ontology/master/ontology/src/eupath.owl 
Homepage: https://github.com/EuPath-ontology/EuPath-ontology 
Contact person: Chris Stoeckert
Contact email: stoeckrt@pennmedicine.upenn.edu
Issue Tracker: https://github.com/EuPath-ontology/EuPath-ontology/issues 
Description:
The EuPath ontology is an application ontology developed to encode our understanding of what data is about in the public resources developed and maintained by the Eukaryotic Pathogen Database Bioinformatics Resource Center (EuPathDB; http://eupathdb.org). The EuPath ontology was built based on the Ontology of Biomedical Investigations (OBI) with integration of other OBO ontologies such as PATO, OGMS, DO, etc. as needed for coverage. Currently the EuPath ontology is primarily intended to be used for support of the EuPathDB sites. Terms with EuPath ontology IDs that are not specific to EuPathDB will be submitted to OBO Foundry ontologies for subsequent import and replacement of those terms when they are available.

Thanks!

**Comment by zhengj2007** [comment]
@cmungall @jamesaoverton @mcourtot  
Since no objection on adding it in, can I go ahead?
Thanks!

**Comment by zhengj2007** [comment]
@cmungall @jamesaoverton 

Created pull requests for EuPath prefix and PURL:
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/537
https://github.com/OBOFoundry/purl.obolibrary.org/pull/390

Please let me know if anything I need to change.

Thanks!

**Comment by mcourtot** [comment]
All done by @jamesaoverton

**Comment by jamesaoverton** [comment]
Yes, I forgot to close the issues. Thanks!

**Comment by zhengj2007** [comment]
Thanks @jamesaoverton 

The purl redirect is working. However, the eupath has not shown up on the obofoundry.org.

Anyone can help on it? @mcourtot @jamesaoverton @cmungall

**Comment by jamesaoverton** [comment]
You're right, some of the index files had to be regenerated. Fixed by commit e4438fa6c2ac0b291f4c6d38f40426db7d3aa0dc

**Comment by cmungall** [comment]
There is a step that currently needs to be manually executed via the 
makefile, it's described in the README, I can do this later but we're 
interested in making this easier for others in the OBO group to be able 
to perform or to automate this

**Comment by zhengj2007** [comment]
Thanks @cmungall
