### ISSUE TITLE
Define what an "inferred" file is

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#542]
_From @GoogleCodeExporter on August 12, 2015 2:4_

```
We advertise distributing "inferred" files, but we never explicitly define what 
inferred means. It would be useful to have a document describing what reasoning 
is being done on our side and what we expect users to do on theirs.

```

Original issue reported on code.google.com by `mcour...@gmail.com` on 4 Jul 2015 at 7:33

_Copied from original issue: OBOFoundry/Operations-Committee-RETIRED#180_

**Comment by zhengj2007** [comment]
_From @GoogleCodeExporter on August 12, 2015 2:4_

```
See also

https://github.com/ontodev/robot/issues/13

I think the formal specs should be consolidated in the robot project as far as 
possible
```

Original comment by `cmung...@gmail.com` on 4 Jul 2015 at 10:09

**Comment by balhoff** [comment]
Is this promoted in any of the current documentation? I'm interested in conventions for distribution of both inferred and non-inferred files, but I can't find this in any of the current docs.

**Comment by cmungall** [comment]
No, we need this for https://github.com/ontodev/robot/issues/6

I think we're going to need a few different classes here. There are a few orthogonal axes

 - direct v indirect
 - OWL Profile
 - just SubClassOf vs other axioms
 - for subClassOf, are existentials inferred?

not sure if it makes sense to precompose for a subset of these combinations.

For the main release, obviously direct is appropriate

**Comment by matentzn** [comment]
There are also a bunch of other considerations to be made if you want this perfect. Apart from specifying the entailment set (atomic subsumption, subconcept subsumption, subproperty hierarchies, incl. simple existentials or not (super expensive), etc), you will need to decide a number of properties of the target class graph. I can dig out a paper about this I have somewhere if you want the full thing:

1. Thing superclass of everything that does not have another superclass?
2. Nothing subclass of everything that does not have another subclass?
3. If A sub B and B sub A, add equivalent class axiom?
4. Unsatisfiable classes subclasses of Nothing, but nothing else (lower case nothing)
5. If you have A sub B and C asserted, do you really want A sub B to be added as an additional subclass axiom?

The reason why this should be made explicit is that every reasoner has their own way to represent the class hierarchy (I think for example that HermiT always includes Nothing as subclass of leaf nodes, while ELK doesnt, not sure though). You probably dont want the inferred files to look different each time you switch reasoners.

I would also like to comment, a comment which I hope is ignored by everyone, that I am not a fan of the fact that the OBO foundry promotes the shipping of inferred files. :P I would rather see a simple docker container with an owlery instance that allows folks to interrogate the ontology properly and easily, and reasoner agnostic folks to make use of the ontology in applications. I can't really see why anyone who would interact with an OWL ontology should be spared to look at reasoners; but that's just my two cents, and I am sure you have been through this many, many times. :) So please ignore.

**Comment by cmungall** [comment]
+1 to making this more explicit.

Especially behavior with Nothing. I strongly believe that for 2 we don't include these axioms.

Most consumers of ontologies are naive and don't expect a bottom class. We consider ourselves pretty good with OWL, but we have been burned on two separate occasions by a graph indexer iterating over all nodes and caching the ancestor graph - for Nothing this is the whole ontology...

We need to make the main releases idiotproof. I don't see any need for an explicit Nothing in any release file (they are obviously useful for making unsatisfiables explicit, but all released ontologies should be coherent)

**Comment by cmungall** [comment]
For 5. Yes, definitely. We generally wanted all axioms to be relaxed (http://robot.obolibrary.org/relax) as naive consumers may only use SubClassOf and SomeValuesFrom constructs.

I would go further and suggest that `A SubClassOf (A and B)` is directly transformed rather than adding redundant axioms. I suppose there may be a use case, e.g. relaxing the conditions of an over-strong equivalence axiom where we want to retain a single structure. But usually when I have seen this pattern in the wild, it's arbitrary and confuses people and should be discouraged.

**Comment by nlharris** [comment]
This is very old -- can we close?

**Comment by matentzn** [comment]
This is still relevant, but is basically operationalised as a ODK question: "What is the "full" variant of the ontology?".

This is the current situation:
https://oboacademy.github.io/obook/reference/release-artefacts/#release-artefact-2-full-required

I would say for anything more actionable, just make an issue here: https://github.com/INCATools/ontology-development-kit/issues
