### ISSUE TITLE
A spreadsheet documenting usage of OBO Foundry ontologies

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#543]
_From @cstoeckert on September 28, 2015 19:18_

OBO Foundry ontologies are gaining impact in their usage by other ontologies, major projects, and major institutions. Barry Smith and I propose we generate a spreadsheet to publicize the breadth of the OBO Foundry community and to help make the case to get others to adopt usage of OBO Foundry ontologies and principles. It will also be useful for our manuscript in progress. I should note that OBI is doing this for its manuscript in publication. We might be able to get this going by collecting info off the BioPortal as well as asking individual ontology groups for their lists.

_Copied from original issue: OBOFoundry/Operations-Committee-RETIRED#187_

**Comment by cmungall** [comment]
* +1 to general idea
 * -1 to spreadsheet
 * we have a PR open where we clearly document usage in the metadata: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/453

this would be co-maintained by OBO and the individual ontology maintainers. We (OBO) would be rigorous about following up on each usage claim. There is a tendency to say an ontology is used when in fact the evidence for actual usage is weak

**Comment by nlharris** [comment]
See also #607

**Comment by nlharris** [comment]
Is this ticket subsumed by #607, and if so, can this ticket be closed?

**Comment by matentzn** [comment]
I think there are no action items here right now. I would close: we should all document usage in the obo metadata files!

**Comment by jonquet** [comment]
Personally, I will not  just "get this going by collecting info off the BioPortal" but I would use BioPortal to store the information. This is why the "projects" feature in BioPortal is here for. 

Then this information becomes  "semantically represented", publicly available, and automatically query-able. 
E.g., https://data.bioontology.org/projects/NIDM
=> 
"ontologyUsed": [
"https://data.bioontology.org/ontologies/COGAT",
"https://data.bioontology.org/ontologies/COGPO",
"https://data.bioontology.org/ontologies/PROVO",
"https://data.bioontology.org/ontologies/NIDM-RESULTS",
"https://data.bioontology.org/ontologies/STATO",
"https://data.bioontology.org/ontologies/FMA"
],

I do not say that a little curation does not need to be done here. 

For a subset of OBO ontologies, we do it in AgroPortal.
