### ISSUE TITLE
Failed links on individual ontology pages

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#547]
On each individual page for ontologies listed on the OBO Foundry page, such as:

http://obofoundry.org/ontology/pr.html
http://obofoundry.org/ontology/obi.html

Within the right hand navigation area you'll see "ID Space" and "Domain" (among others). Oddly, each of these are filled with metadata that is hyperlinked (in the case of PRO, 'pr' and 'proteins' respectively). Neither of these links work (nor do they for any of the ontologies I looked at). So far as I can tell, what they link to is not editable by anyone on an individual ontology basis. Probably they should either not be linked at all, or (with some extra work) they should link to pages that show a list of ID spaces (which would be redundant with the Foundry home page) and domains (does that exist?). I would recommend changing the default behavior to not linked at all.

P.S. For some reason, the link for ID Space does different things depending on the ontology. For example, for PRO it attempts to go to purl.oclc.org but others go to github. The domain link seems to always go to a not-found page on github.

**Comment by nlharris** [comment]
This doesn't seem to have been fixed. Seems like the easiest fix would be (as Darren suggested) just don't hyperlink those fields.

**Comment by nicolevasilevsky** [comment]
I would volunteer to take care of this, but realized I don't know how to fix this.

From what I can tell, the domain field is automatically creating a hyperlink in the format: http://obofoundry.org/domain/[domain name].html.

For example, the 'protein' domain links to: http://obofoundry.org/domain/proteins.html

If anyone knows how to fix this, I would be happy to help.

**Comment by erik-whiting** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2367

**Comment by erik-whiting** [comment]
fixed by https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2367
