### ISSUE TITLE
INO (Interaction Network Ontology) disappeared from OBO Foundry 

### ISSUE THREAD

**Issue by yongqunh** [OBOFoundry/OBOFoundry.github.io#548]
As I remember, OBO Foundry at least once included INO (Interaction Network Ontology) in OBO ontology library. However, INO is not in OBOFoundry list any more.

I checked the records. In 2014, I requested the INO namespace for Interaction network ontology as shown: https://sourceforge.net/p/obo/mailman/message/32061894/

As shown here: http://www.ontobee.org/ontology/INO, 
INO owl file has the PURL direct: 
http://purl.obolibrary.org/obo/in/ino.owl
this direct still works. However, I don't know why INO is not in OBO Foundry.

INO updates:
Currently INO gets more and more attention, and people are using it for different purposes (e.g., literature mining). 
The following 2015 paper first systematically introduces INO ontology:
https://www.ncbi.nlm.nih.gov/pubmed/25785184
Some papers using and/or citing INO:
https://www.ncbi.nlm.nih.gov/pubmed/?term=28365720 
https://pdfs.semanticscholar.org/ad58/5f25747dcc0f5a130589521c4306229f7297.pdf
https://www.hindawi.com/journals/ijg/2017/6213474/ 
https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-017-0172-7 (Note: this is Chris' paper. @cmungall ) 

A couple days ago, a researcher asked me why INO term PURL dereference did not work out. So I realized that INO is not listed in OBOFoundry: http://obofoundry.org/ . 

Therefore, I would like to request adding back INO to OBOFOundry.
Oliver He 

@cmungall : Chris, could you help me with this? Thanks!

**Comment by cmungall** [comment]
See also: https://github.com/OBOFoundry/purl.obolibrary.org/issues/353

**Comment by yongqunh** [comment]
Thanks, Chris.
I will do as instructed.
Oliver

**Comment by nlharris** [comment]
INO is visible on the OBOFoundry page, so can this issue be closed?

**Comment by yongqunh** [comment]
Yes. It can be closed.
