### ISSUE TITLE
Update ID policy document

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#550]
Some of the content is out of date. It should be converted to Markdown.

**Comment by Public-Health-Bioinformatics** [comment]
Specifically "Resources at Known locations" and "Current ontology document" section links are broken.  As well, "To protect ourselves against a future time when purl.org might not be as reliable, or in case we wish to substitute a different technology for resolving term requests, we use our own domain name, and have the DNS [5] point to purl.org." can be removed as there is no longer synchronization to purl.org.

**Comment by nlharris** [comment]
Which page is this on?  When noting issues on a document (whether it's a web page or something in github) it seems like good practice to include the URL in the issue.

**Comment by jamesaoverton** [comment]
The relevant page is http://obofoundry.org/id-policy.html

It looks like this was resolved by #805 and maybe #946, so I'll close.
