### ISSUE TITLE
Incorrect "metadata guide" link

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#554]
The link to the metadata guide (shown below the View|Edit|PURL buttons on each ontology page) is incorrect. It currently is:

http://obofoundry.org/ontology/faq/how-do-i-edit-metadata.html

but should be:

http://obofoundry.org/faq/how-do-i-edit-metadata.html

**Comment by cmungall** [comment]
huh, baseurl seems to work differently on a local jekyll than live..
