### ISSUE TITLE
CRO PURL not redirecting 

### ISSUE THREAD

**Issue by simonjupp** [OBOFoundry/OBOFoundry.github.io#558]
http://purl.obolibrary.org/obo/cro.owl doesn't work but http://purl.obolibrary.org/obo/cro does

**Comment by mcourtot** [comment]
Not in our registry at https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config, handled by purl.org directly: https://archive.org/services/purl/purl/obo/cro

@cmungall merged the PR, not sure if it was on purpose done via PURL but maybe he can help

**Comment by cmungall** [comment]
I don't recall the PR, but it looks like there was only one for the main md and not the separate yml for the PURL? Do you want to make a new PR for the purl?

**Comment by nlharris** [comment]
http://purl.obolibrary.org/obo/cro.owl now works, so can this issue be closed?

**Comment by jamesaoverton** [comment]
Closed by https://github.com/OBOFoundry/purl.obolibrary.org/pull/454
