### ISSUE TITLE
Standardize naming conventions for OBOF products

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#560]
From a different conversation between @cmungall and @balhoff 

@cmungall: we (OBO) need to standardize ASAP the naming conventions for different products. @balhoff proposes raw for (1) no-inference (2) no-imports (3) no-external-classes

@balhoff: Lately I was thinking atomic rather than raw. Need to make some time to create some tools for creating & working with those.

**Comment by nataled** [comment]
The list below is based on declared PURLs in *.yml files. For the below, <lowercase> indicates a generic file name (appended with .obo or .owl) while <ONTOLOGY> indicates a specific ontology prefix or name. In cases where a folder name is used to partition files of a certain type, that folder name will be within slashes. Only cases that could be generalized were considered. Note that some ontologies provide combinations of the below (such as ido-main-asserted.owl). This list needs to be supplemented with searches into destination folders for ontologies. For example, DOID uses <ONTOLOGY>-non-classified as a file name but does not declare a PURL for it and thus it is not on this list.

** versions without reasoning pre-applied

<ONTOLOGY>-asserted				PR, IDO
<ONTOLOGY>-stated				IAO
<ONTOLOGY>-unreasoned			ERO
<ONTOLOGY>-simple				CIO
<ONTOLOGY>-non-classified			BCO

** development/pre-release files

<ONTOLOGY>-dev					PR		# NOTE:  the between-releases manually-curated subset
/internal/<ONTOLOGY>				MF, CHEBI	
/prebuild/<ONTOLOGY>			NCRO
/pre/<ONTOLOGY>				MONDO
/dev/<ONTOLOGY>				ERO, GEO, FLU, CL, MPIO, DIDEO, OMIABIS, OMRST, OOSTT, 
								OGMS, BFO, IDO, APOLLO_SV

** "metadata"    # None of the below are metadata only but are included here in case '-metadata' or similar is considered for such
/metadata/<metadata>.ttl			GO		# Turtle files only
<ONTOLOGY>-metadata			ERO		# PURL non-functional
ontology-metadata					IAO

** subsets/slims/instances
/external/<subsetname>-slim		MF
/dev/<subsetname>				GEO
<ONTOLOGY>-core				MF, OBI	# NOTE: ERO uses -core to refer to a version without 
										imports
core-<subsetname>				BFO
<subsetname>-instances			GEO		# NOTE: this is specific to instances

** core version, no imports
/dev/<ONTOLOGY>-core			ERO		# NOTE: Both MF & OBI use "-core" but to refer to 
										something akin to a minimal subset of terms
<ONTOLOGY>-basic				CL

** "full" version, via imports declarations
<ONTOLOGY>-extended			ERO
<ONTOLOGY>-full					DRON      

** imported ontologies only (or import declarations)
/external/<ONTOLOGY>_import		MF
/external/<ONTOLOGY>_imported	MFOEM
/dev/<EXT-ONTOLOGY>-imports		ERO
/dev/<ONTOLOGY>-import			ERO
/dev/external						FLU
<ONTOLOGY>-external				IDO		# this is an assumption, as the purl for this and many 
										other IDO purls don't work
external							AERO	# simply called 'external.owl'
ext								DOID	# simply called 'ext.owl'
external-by-hand					AERO	# presumably manually-imported terms
/dev/externalByhand				OBIB, OMIABIS	# presumably manually-imported terms
external-byhand					OBI		# presumably manually-imported terms
import_<EXT-ONTOLOGY>			OMIABIS
/dev/import_<importname>			OBIB

** obsolete terms only
<ONTOLOGY>-obsolete				IDO
obsolete							IAO

** ontology without obsolete terms
<ONTOLOGY>-main				IDO, IAO

** ontology without axioms
<ONTOLOGY>-base				IDO

**Comment by nataled** [comment]
I'd also like to suggest, in addition to the PURLs suggested under "Resources at Known locations" in the ID policy document (http://obofoundry.org/id-policy.html), that we use following:
http://purl.obolibrary.org/obo/<id>/<id>-readme to point to the current README file
http://purl.obolibrary.org/obo/<id>/<id>-license to point to the current LICENSE file
with the release-specific ones modified accordingly.

**Comment by cmungall** [comment]
This is great thanks. I'm posting your list in verbatim as it's easier to see it inline:

```
** versions without reasoning pre-applied

<ONTOLOGY>-asserted		PR, IDO
<ONTOLOGY>-stated		IAO
<ONTOLOGY>-unreasoned		ERO
<ONTOLOGY>-simple		CIO
<ONTOLOGY>-non-classified	BCO

** development/pre-release files

<ONTOLOGY>-dev			PR		# NOTE: this is the between-releases manually-curated subset
/internal/<ONTOLOGY>		MF, CHEBI	
/prebuild/<ONTOLOGY>		NCRO
/pre/<ONTOLOGY>			MONDO
/dev/<ONTOLOGY>			ERO, GEO, FLU, CL, MPIO, DIDEO, OMIABIS, OMRST, OOSTT, OGMS, BFO, IDO, APOLLO_SV


** "metadata"    # None of the below are metadata only but are included here in case '-metadata' or similar is considered for such
/metadata/<metadata>.ttl	GO		# Turtle files only
<ONTOLOGY>-metadata		ERO		# PURL non-functional
ontology-metadata		IAO

** subsets/slims/instances
/external/<subsetname>-slim	MF
/dev/<subsetname>		GEO
<ONTOLOGY>-core			MF, OBI		# NOTE: ERO uses -core to refer to a version without imports
core-<subsetname>		BFO
<subsetname>-instances		GEO		# NOTE: this is specific to instances

** core version, no imports
/dev/<ONTOLOGY>-core		ERO		# NOTE: Both MF & OBI use "-core" but to refer to something akin to a minimal subset of terms
<ONTOLOGY>-basic		CL

** "full" version, via imports declarations
<ONTOLOGY>-extended		ERO
<ONTOLOGY>-full			DRON      

** imported ontologies only (or import declarations)
/external/<ONTOLOGY>_import	MF
/external/<ONTOLOGY>_imported	MFOEM
/dev/<EXT-ONTOLOGY>-imports		ERO
/dev/<ONTOLOGY>-import		ERO
/dev/external			FLU
<ONTOLOGY>-external		IDO		# this is an assumption, as the purl for this and many other IDO purls don't work
external			AERO		# simply called 'external.owl'
ext				DOID		# simply called 'ext.owl'
external-by-hand		AERO		# presumably manually-imported terms
/dev/externalByhand		OBIB, OMIABIS	# presumably manually-imported terms
external-byhand			OBI		# presumably manually-imported terms
import_<EXT-ONTOLOGY>		OMIABIS
/dev/import_<importname>	OBIB

** obsolete terms only
<ONTOLOGY>-obsolete		IDO
obsolete			IAO

** ontology without obsolete terms
<ONTOLOGY>-main			IDO, IAO

** ontology without axioms
<ONTOLOGY>-base			IDO

```

**Comment by cmungall** [comment]
The ymls may not be exhaustive as some ontologies use partial redirects.

E.g. many ontologies have a `basic` version in their subsets folder or similar. This has a very specific meaning, defined in the obo format spec http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.2

I would like to formally reserve the name `basic` here for artefacts of this type

**Comment by cmungall** [comment]
@balhoff's proposal:
https://docs.google.com/document/d/1eCo5C3aZ9kjhBu98-24c2FHZIHEeFV7I2TJ4Vd6qw6k/edit#

vote on name of building block module here: https://doodle.com/poll/pkk8vyxmwu53iva5

**Comment by jamesaoverton** [comment]
See https://github.com/information-artifact-ontology/ontology-metadata/pull/36

**Comment by balhoff** [comment]
Re: the "building block module" type, the conclusion based on the Doodle poll and other discussions is that we can call this the **"base"** file for the ontology project. I.e. it is the base from which other ontology products are derived (such as by applying inference, importing content from other ontologies, etc.).

So for a given project, for example GO, I suppose you would expect to find the file at `http://purl.obolibrary.org/obo/go/go-base.owl`.

**Comment by cmungall** [comment]
Closing this as it's in IAO's hands now
