### ISSUE TITLE
FBcv tagged as deprecated

### ISSUE THREAD

**Issue by mmc46** [OBOFoundry/OBOFoundry.github.io#57]
FBcv (FlyBase controlled vocabulary) is tagged as deprecated. 

http://obofoundry.github.io/ontology/fbcv.html

I would say this is not the case. Although the Drosophila Phenotype Ontology, which is included in FBcv, is released separately, the whole of FBcv is still updated regularly.

**Comment by cmungall** [comment]
apologies, it seemed at some point fbcv would deprecate itself into multiple other vocabs, but should definitely not be deprecated, especially as it is the 'parent' of dpo
