### ISSUE TITLE
fairsharing collection records

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#586]
From Peter McQ:

"Could you take a look and claim the record, either as an individual or using a group email/profile?"

https://fairsharing.org/biodbcore-001083
https://fairsharing.org/collection/OBOFoundry

We would not do this as individuals as we share admin tasks

See also #79

**Comment by mellybelly** [comment]
As agreed upon, FAIRsharing will pull the metadata from the OBO metadata registry. This will ensure that FAIRsharing can stay consistent with the authoritative source in https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/registry, where all OBO ontologies have committed to maintaining their metadata as part of OBO membership.

We should also remove FAIRsharing DOIs for the OBO ontologies and instead have FAIRsharing display the OBO Foundry citation best practices information as described in:
http://www.obofoundry.org/docs/Citation.html
as part of this interoperability effort.

**Comment by nlharris** [comment]
Is this something that still needs to be addressed?

**Comment by nlharris** [comment]
Can we close this?

**Comment by matentzn** [comment]
Let's close for now and have people reopen with concrete action items where necessary.
