### ISSUE TITLE
Is the googlecode email on the https://github.com/OBOFoundry page the correct email?

### ISSUE THREAD

**Issue by cerivs** [OBOFoundry/OBOFoundry.github.io#589]
https://github.com/OBOFoundry  list the contact email as  obo-foundry-operations-committee@googlecode.com.  Should this be updated?

**Comment by cmungall** [comment]
Thanks, can't believe it took us so long to fix this! I actually went ahead and changed to obo-discuss as well, as I don't think it was useful to list obo-operations
