### ISSUE TITLE
Review OFOC membership lists

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#599]
We've recently added members, so the pages have to be updated. We should take this opportunity to set a policy or assign someone to keep this up to date.

**Comment by jamesaoverton** [comment]
Also review the alumni list and policy.

**Comment by nlharris** [comment]
I did a bunch of updating of the membership lists on the website last Aug: https://github.com/OBOFoundry/OBOFoundry.github.io/commits?author=nlharris
Does that resolve this issue, or is there still the policy issue to discuss?

**Comment by nlharris** [comment]
is there more to be done here or can we close this issue?

**Comment by nlharris** [comment]
Superseded by #1278; closing.
