### ISSUE TITLE
COLL prefix and PURL request

### ISSUE THREAD

**Issue by luis-gonzalez-m** [OBOFoundry/OBOFoundry.github.io#610]
Requested Prefix: CAO
Ontology Title: Collembola Anatomy Ontology
Download link: https://github.com/luis-gonzalez-m/Collembola/blob/master/CAO.owl
Contact e-mail: lagonzalezmo@unal.edu.co
Description:
CAO is an anatomical ontology for taxonomic descriptions. Also, the purpose is translating RDF statement to taxonomic character statement, and creating a description template for Collembola.

**Comment by pbuttigieg** [comment]
@luis-gonzalez-m 

On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.

**Comment by jamesaoverton** [comment]
Closed in favour of #1189
