### ISSUE TITLE
Update the MP license 

### ISSUE THREAD

**Issue by sbello** [OBOFoundry/OBOFoundry.github.io#613]
We have updated the MP license (http://www.informatics.jax.org/mgihome/other/Ontology_Licenses.shtml). We have adopted a CC-BY license. Please update the information on this page http://www.obofoundry.org/ontology/mp.html
Thanks,
Sue

**Comment by nicolevasilevsky** [comment]
I created a PR for this: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/615
