### ISSUE TITLE
Removing any links to sourceforge in registration process

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#614]
From a user trying to register an ontology:

> I followed instructions from The OBO Foundry. This site has other links and
> I was directed to sourceforge and github during the requesting
> registration.

We should not be pointing anyone at sourceforge

We have various mentions of SF on the site:

https://github.com/OBOFoundry/OBOFoundry.github.io/search?utf8=%E2%9C%93&q=sourceforge&type=

Some of these are in ontology metadata (this is often a proxy for an ontology being abandoned, if content is still on SF), some is our legacy docs

**Comment by luis-gonzalez-m** [comment]
It's correct. The sourceforge registration happens in step 2 of "requesting the prefix" (The OBO Foundry). It is a requirement previous to obo-discuss registration.

**Comment by luis-gonzalez-m** [comment]
Hi,
This is the URL currently but now there is no link to the sourceforge. Thanks

http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

**Comment by nlharris** [comment]
I will look for links to sourceforge and see if I can fix them.
There are also links to svn, such as the broken image links in http://www.obofoundry.org/docs/SettingUpProtege.html (see #953) like http://obo-foundry-operations-committee.googlecode.com/svn/wiki/img/SettingUpProtege4.png

**Comment by nlharris** [comment]
The page mentioned above was retired. Here are obofoundry pages that have the string "sourceforce":
https://github.com/OBOFoundry/OBOFoundry.github.io/search?p=1&q=sourceforge
Almost all of them are specific ontology pages. I guess we could create tickets for each of those asking the ontology owners to update the old sourceforge links, but that seems out of scope.
I found and fixed one instance in #1340 
I don't see any others to fix.
