### ISSUE TITLE
purl.org ID registration

### ISSUE THREAD

**Issue by citmejia** [OBOFoundry/OBOFoundry.github.io#619]
Hi, 

I'm not clear about how to register to get a purl.org ID. I clicked on the indicated link and created an archive.org user. Is that the same as de purl.org ID?

Best regards,
Citlalli

**Comment by zhengj2007** [comment]
Hi Citlalli,

You need to register your ontology to OBO Foundry for getting a purl ID. Here is the page and guideline on how to register an ontology to OBO Foundry:
http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html
http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

Best,

Jie


On May 31, 2018, at 11:25 AM, citmejia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I'm not clear about how to register to get a purl.org<http://purl.org> ID. I clicked on the indicated link and created an archive.org<http://archive.org> user. Is that the same as de purl.org<http://purl.org> ID?

Best regards,
Citlalli

**Comment by citmejia** [comment]
Hi Jie,

Thanks, for your quick response. I was following these guidelines and I
arrived to this
Information needed for a prefix request...

   - purl.org user ID - please register there <http://purl.org/> if you
   don’t have one


I clicked on "there" and created an archive.org account. My question is if
to make the request, what I have to provide is the archive user ID.


2018-05-31 10:58 GMT-05:00 jie zheng <notifications@github.com>:

> Hi Citlalli,
>
> You need to register your ontology to OBO Foundry for getting a purl ID.
> Here is the page and guideline on how to register an ontology to OBO
> Foundry:
> http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html
> http://www.obofoundry.org/docs/Policy_for_OBO_namespace_
> and_associated_PURL_requests.html
>
> Best,
>
> Jie
>
>
> On May 31, 2018, at 11:25 AM, citmejia <notifications@github.com<mailto:

**Comment by balhoff** [comment]
@citmejia can you point exactly to the page where it says to create a purl.org account? That used to be the case, but now this is all managed directly by OBO on GitHub (no dependency on purl.org). There must be some out-of-date content that you have found. Thanks!

**Comment by zhengj2007** [comment]
Hi Citlalli,

Sorry. The guide is out-of-date. You don’t need to provide purl.org<http://purl.org> user ID for registration now.

Best,

Jie

On May 31, 2018, at 12:04 PM, citmejia <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jie,

Thanks, for your quick response. I was following these guidelines and I
arrived to this
Information needed for a prefix request...

- purl.org<http://purl.org> user ID - please register there <http://purl.org/> if you
don’t have one


I clicked on "there" and created an archive.org<http://archive.org> account. My question is if
to make the request, what I have to provide is the archive user ID.


2018-05-31 10:58 GMT-05:00 jie zheng <notifications@github.com<mailto:notifications@github.com>>:

> Hi Citlalli,
>
> You need to register your ontology to OBO Foundry for getting a purl ID.
> Here is the page and guideline on how to register an ontology to OBO
> Foundry:
> http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html
> http://www.obofoundry.org/docs/Policy_for_OBO_namespace_
> and_associated_PURL_requests.html
>
> Best,
>
> Jie
>
>
> On May 31, 2018, at 11:25 AM, citmejia <notifications@github.com<mailto:notifications@github.com><mailto:

**Comment by citmejia** [comment]
Here is the page where I found this requirement:

http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

I was directed here from the page Jim just pointed:

http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html

2018-05-31 11:14 GMT-05:00 Jim Balhoff <notifications@github.com>:

**Comment by nlharris** [comment]
i think maybe this is now fixed?
