### ISSUE TITLE
Guide page for request a PURL and an entry in the registry need to be updated

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#620]
We don't need to provide purl.org ID for request a PURL and an entry in the registry. So, the guide page need to be updated:
http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

**Comment by cmungall** [comment]
wow, our docs are really out of date here

@nlharris and I will work on this

**Comment by nlharris** [comment]
Does Ramona's PR fix this issue?

**Comment by jamesaoverton** [comment]
It can always be better, but I think this issue is closed.
