### ISSUE TITLE
Request for MCO prefix and PURL

### ISSUE THREAD

**Issue by citmejia** [OBOFoundry/OBOFoundry.github.io#622]
Requested prefix: MCO
Ontology Title: Microbial Conditions Ontology
Download link: https://github.com/microbial-conditions-ontology/microbial-conditions-ontology/blob/master/src/ontology/mco-edit.owl
Home Page: https://github.com/microbial-conditions-ontology, http://regulondb.ccg.unam.mx/menu/tools/microbial-condition-ontology/
Contact e-mail: contact.mco.ontology@gmail.com
Mailing list: https://gitter.im/mco-ontology

MCO is a domain ontology that provides a controlled vocabulary for the description of microbial growth conditions. The purpose of this ontology is to set an standard for the structured annotation of the experimental conditions in public repositories.

**Comment by citmejia** [comment]
Hello,

I kindly request follow-up here.

**Comment by cmungall** [comment]
apologies for the delay. Are you able to make the pull request in this 
repo? This will help expedite. You already have the metadata file in 
your repo.

**Comment by citmejia** [comment]
Hello,

After months working to fix logical inconsistencies in MCO, I'm finally trying to follow the steps to incorporate the ontology to the OBO Foundry. I tried to do what is specified in the README in the metadata folder of the OSK. However, I could not make a commit, instead I "propose a new file".  I hope it is ok.

Cheers,

**Comment by cmungall** [comment]
Great, can you send an email to obo-discuss requesting the prefix, and
point at this pull request. Also include some detail in the email (the info
from your README is great)

**Comment by citmejia** [comment]
Hi Chris,

I'm not clear to which pull request I should point in the email. I did two pull requests: the mco.yml and the mco.md. Do you refer to one of them or should I do another one?

**Comment by cmungall** [comment]
Both is great, thanks!

**Comment by citmejia** [comment]
Hi Chris, 

I already sent the email to Obo-discuss@lists.sourceforge.net requesting the prefix and pointing to the pull requests.

**Comment by cstoeckert** [comment]
Listed on OBO Foundry page so appears to be addressed.
