### ISSUE TITLE
Ontology feedback

### ISSUE THREAD

**Issue by luis-gonzalez-m** [OBOFoundry/OBOFoundry.github.io#627]
I haven't receive feedback about the following ontology "Collembola Anatomy Ontology". This ontology is directed to generate templates to describe specimens in  taxonomy of Collembola. Also, this include terminology for chaetotaxy. What is the next step in the registration and request a prefix for my ontology? thanks for your comments.

**Comment by nataled** [comment]
Hello Luis,

Please see this page for guidance on registration:

http://obofoundry.org/faq/how-do-i-register-my-ontology.html

There is a link to follow there (linked to 'see this guide').

Best regards,
Darren Natale

**Comment by nlharris** [comment]
I think this can be closed?
