### ISSUE TITLE
Request to include xlmod ontology for cross-linking and derivatization reagents

### ISSUE THREAD

**Issue by germa** [OBOFoundry/OBOFoundry.github.io#628]
Hi all,

can we please add xlmod to OBOFoundry? I attached the xlmod.md and XLMOD.obo files.

Requested prefix: xlmod
Ontology Title: HUPO-PSI cross-linking and derivatization reagents controlled vocabulary
Download link: https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo
Home Page: https://github.com/HUPO-PSI/mzIdentML/tree/master/cv
Contact e-mail: gerhard.mayer@rub.de
Mailing list: psidev-msvocab@lists.sourceforge.net
PURL user ID: cross-linking-and-derivatization-reagents

Best regards
Gerhard Mayer
HUPO-PSI ontology coordinator

**Comment by nlharris** [comment]
Looks like this request fell through the carcks.

**Comment by jamesaoverton** [comment]
XLMOD is in the registry and has PURLs.
