### ISSUE TITLE
Updating location ontology in ExO

### ISSUE THREAD

**Issue by lancemckee** [OBOFoundry/OBOFoundry.github.io#631]
I'm advocating for an improved location ontology in ExO. 

Integrating exposure data with data about terrain, 3D city models, routes and corridors, etc. would be made easier if exposure data used the same OGC and ISO location model used in such geospatial data layers. W3C and OGC organized a joint "Spatial Data on the Web" working group and worked through the key obstacles. In September 2017 they arrived at a set of best practices (https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/). 

Can this be done? What is the best way to proceed? What information or resources would be needed? I know that a key factor is the location ontologies used by authors of exposomics studies. If standard location ontology and best practices can be established, I plan to work with editors and exposomics initiatives to encourage use of the standards and best practices.

Lance McKee
lmckee76@gmail.com
508-868-2295

**Comment by cmungall** [comment]
Lance,

You may want to make this request on the ExO tracker:

https://github.com/CTDbase/exposure-ontology

(normally we have links to all ontology trackers from the OBO top page but we seem to be missing this metadata for ExO)

Can I clarify what you are asking? Are there particular classes in ExO you would advocate removing? I think you are advocating that the ExO vocabulary could be used in conjunction with standard W3 schemas for specifying geolocations when encoding datasets in RDF? I think this is reasonable but I'm not sure what the action is.

Note there is a separate ontology in OBO called ENVO which includes classes for material entities such as roads and processes such as transportation. cc @pbuttigieg

**Comment by nlharris** [comment]
It looks like maybe this request was specific to Exo (http://www.obofoundry.org/ontology/exo.html)?

**Comment by nlharris** [comment]
Can we close this ticket?
