### ISSUE TITLE
Create a page listing and describing ontology tools

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#633]
@neilotte suggested that would be good to have a curated, up-to-date list of software tools that are especially useful for working with OBO. This could be a single page added to the obofoundry.org website. I'm willing to do the initial wrangling and maintenance.

There's a large number of general semantic web tools out there, but I think we should focus on tools that are either:

1. specifically designed for use with OBO ontologies (e.g. ROBOT)
2. that OBO developers and users use regularly (e.g. Protégé)

That said, I think we should lean toward including projects that want to be included, as long as they're still maintained.

Here's a very quick list to start with -- please suggest more:

- ROBOT
- Ontology Starter Kit
- Onto-Animals
- Protégé

**Comment by zhengj2007** [comment]
Bioportal

**Comment by selewis** [comment]
I would say not. It's more of a disservice than a service. No functionality
and poor representation of OBO ontologies

**Comment by zhengj2007** [comment]
I used Bioportal Rest API services quite a lot for searching and mapping OBO Foundry ontology terms. Like search/map terms to DOID, UBERON, and NCBITaxon, etc. That's why I think it is useful.

**Comment by jamesaoverton** [comment]
I wasn't thinking of the various portals, but I'm fine with including them: OntoBee, OLS, BioPortal, and AberOWL are the ones I use. When they have APIs, as @zhengj2007 mentions, we can include that too.

A long list is better than no list, I think.

**Comment by selewis** [comment]
We've found their mapping services too unreliable, in the sense of false
positives and false negatives. Plus they are not careful about keeping
their ontologies up to date. And perhaps most critically they condone and
encourage proliferation of overlapping ontologies which is antithetical to
OBO foundry principle of fostering consolidation to support
interoperability.

**Comment by neilotte** [comment]
Some additions

1. Joseph Utrecht and John Jenkins at the University of Arkansas Medical Center built this online platform, which can be helpful for quickly sharing terms and annotations with collaborators without having to write a SPARQL query: https://owl2tl.com

2. KARMA is used for mapping by a few people at NCOR. I'm not sure how many Foundry folks are using it. http://usc-isi-i2.github.io/karma/

3. CLAMP for nlp text annotation: https://clamp.uth.edu

**Comment by mellybelly** [comment]
Would could list the union of all of the links that everyone has provided to view the ontology in external systems. For example, for HPO we have: http://www.obofoundry.org/ontology/hp.html
Ontobee, AberOwl, Monarch, the HPO website, and OLS. This could be automated to populate the list with a listing of which ontologies can be viewed there? It might be a nice pivot view.

**Comment by mellybelly** [comment]
We also have the Monarch/SciGraph Annotation service https://monarchinitiative.org/annotate/text

**Comment by jamesaoverton** [comment]
We discussed this proposal on the OFOC call a few months ago. There was disagreement about what should be listed, but nobody objected to moving forward with this.

At ICBO we discussed creating an `obo-tools` mailing list, which would be a good addition to this proposal.

I'll push this back toward the top of my To Do list.

**Comment by rctauber** [comment]
Hi all - I just added a new doc page with the tools (see #734). This also includes an OBO-Tools mailing list, [located here](https://groups.google.com/d/forum/obo-tools).

**Comment by cstoeckert** [comment]
As discussed on the OBOF operations call (Oct. 2), the page title should be changed from OBO Tools (which implies an association) to better reflect that this is just a list of tools some of us have found useful. Something like 'Useful tools for ontologists' - we still would want to include a non-endorsement statement.

**Comment by jamesaoverton** [comment]
Thanks Chris. I'm going to change the title to simply "Ontology Tools" and add a non-endorsement note.

**Comment by nlharris** [comment]
i don't see a page called Ontology Tools, but that's a section on http://obofoundry.org/resources that lists some of the tools mentioned here. i don't see a non-endorsement statement.

Can we now close this issue?

**Comment by matentzn** [comment]
I think requests for adding any other tools should be done in a separate ticket, so I will close this. If someone feels their request was not heard, please open a new ticket with your tool. :)
