### ISSUE TITLE
Travis notifications should go to wider group

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#66]
```
notifications:
  email:
    - cjmungall@lbl.gov
```

happy to do this during the teething phase, but should go to wider group. Others should add emails here https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/.travis.yml -- or should we just use obo-operations list?

**Comment by mcourtot** [comment]
Added mine - somewhat unrelated, but I'm not sure how travis gets called upon commit? Is there some sort of hook and how is it created?

**Comment by cmungall** [comment]
.travis.yml is the hook - any github repo can add a file like this, 
travis will recognize it and run it, no additional configuration or 
setup required

**Comment by cmungall** [comment]
We have 3 watchers so I'll close this now
