### ISSUE TITLE
kisao issues

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#67]
Migrating from #18 cc @lenov 

kisao is still on SF - I strongly recommend migrating to GH. See https://docs.google.com/document/d/1iyVY8kDBJIEydoWFLG9j5BoO4VmdIXES95fVhIkFXfk/edit#

(there is no tracker enabled on SF, we used to have https://sourceforge.net/tracker/?group_id=293617 registered but this no longer works)

**Comment by mcourtot** [comment]
What's the solution here? Should we just create a PURL towards http://svn.code.sf.net/p/kisao/code/tags/kisao-owl-latest/kisao_full.owl? I'm not sure this makes too much sense if the owner of the PURL is not the group developing the resource. Should we just set the hyperlink to the SF site for now?

**Comment by cmungall** [comment]
I think this fixes it: https://github.com/OBOFoundry/OBOFoundry.github.io/commit/0b4071c753813750fedd3de5259e7735f45c901f
