### ISSUE TITLE
New entry: Pathogen Host Interaction Phenotype Ontology

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#681]
From June:

Dear OBO-Discuss

We at PHI-base http://www.phi-base.org/ are just starting to create a Pathogen Host Interaction Phenotype Ontology and would like to request a new OBO namespace.

The namespace requested is “PHIPO”, it seems it is not reserved yet and we would like to reserve it for when our ontology is ready to publish. The ontology does not currently contain logical definitions referencing external ontology terms as this is planned for the future using the Ontology Starter Kit. We are working on this with the University of Cambridge PomBase team members Val Wood, Midori Harris and Kim Rutherford.

Below is the basic information:

 

--

Requested Prefix: PHIPO

Ontology Title: Pathogen Host Interaction Phenotype Ontology

Download link: https://raw.githubusercontent.com/PHI-base/phipo/master/phipo.owl

Home page: https://github.com/PHI-base/phipo

Contact e-mail: Alayne.cuzick@rothamsted.ac.uk

Tracker link: https://github.com/PHI-base/phipo/issues

PURL user ID: ACuzick

Description: PHIPO is a formal ontology of species-neutral phenotypes observed in pathogen-host interactions.

--

**Comment by cstoeckert** [comment]
On OBO Foundry page so appears to be adressed.
