### ISSUE TITLE
TradeMarks and OBO licenses

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#693]
Can an ontology be __both__ CC-BY and have the name trademarked? I believe in general TMs are compatible with CC-BY.

**Comment by mcourtot** [comment]
Not sure anybody here would now. Maybe reach out to CC people?

**Comment by nlharris** [comment]
@kltm might have thoughts about this.

**Comment by kltm** [comment]
In my (not-a-lawyer) understanding, trademarks and copyright are quite different things. I would be surprised if an ontology had a trademark: who would bother registering it, or understanding if it was even applicable? (E.g. what is the good or service that you want your mark to cover?) Trademarks, I believe, involve attorneys and an application process, unlike copyrights which just "happen" naturally.
Copyrights and trademarks can bump against each other in interesting places though. For example, the Iceweasel debacle: https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian#History_and_origin_of_name

**Comment by alanruttenberg** [comment]
When I was at Science Commons we had suggested the approach of getting
trademark if desired and did not consider it incompatible with CC
licensing. It seemed reasonable to let people protect their good name that
way.
Alan

**Comment by nlharris** [comment]
Are there still questions to be answered here, or can this be closed?

**Comment by kltm** [comment]
Simply, "yes", they are compatible.
E.g. https://creativecommons.org/terms/

**Comment by nlharris** [comment]
Thanks; closing.
