### ISSUE TITLE
Ensure mailing list metadata is complete

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#695]
We have a mailing-list field but it's often incomplete

 * [x] https://groups.google.com/forum/#!forum/phenotype-ontologies for all pheno ontologies - @nicolevasilevsky 
 * [x] RO list @cmungall #692 
 * others?

**Comment by nlharris** [comment]
can this be closed?

**Comment by nicolevasilevsky** [comment]
yes, I think it can be closed
