### ISSUE TITLE
Ensure build metadata is correct for psidev vocabularies

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#71]
We are lacking this for ms, and it looks like the others use the old style sourceforge URLs

cc @germa @ontoden

**Comment by cmungall** [comment]
Also the psidev community is moving from SF to GH, so URLs will change:

https://github.com/MICommunity

**Comment by cmungall** [comment]
@germa, I added the build info for ms (this will have to changed when you move to gh from sf, but that's OK).

This means that the central OBO build which runs nightly will make the owl from your obo, and the official obo purl http://purl.obolibrary.org/obo/ms.owl will fall-through to this owl.

However, it won't work at the moment, as you need to do one thing to your ontology

Currently you have this in your header:
```
ontology: pato
ontology: uo
```

This is wrong, there should be a single ontology tag, and for you it must be:

```
ontology: ms
```

We can hack around this but I think it's better if it's fixed at source.

It looks like you're trying to do imports with oboedit. This is generally not recommended but if this is really necessary I can provide assistance, there are some tricks that will make this easier, you can email me or discussing in this ticket is fine as it may be of interest to other psidev ontologies.

**Comment by cmungall** [comment]
@colin-combe you have been migrating some of the vocabularies to github. We still have sourceforge URLs registered for the following:

 * http://obofoundry.github.io/ontology/mi.html
 * http://obofoundry.github.io/ontology/sep.html
 * http://obofoundry.github.io/ontology/mod.html
 * http://obofoundry.github.io/ontology/ms.html

Would you be able to help ensure these are up to date? You can just provide the URLs in this ticket, or you can click on any of the above links and click "Edit" to modify the metadata

**Comment by colin-combe** [comment]
OK, the "Edit" link does make that quite easy.

There should be pull requests for all of them except sep.html - I didn't know https://code.google.com/p/gelml/ was amongst the code we're looking after. I'll check whats happening with this.

Are the urls formatted how they are meant to be? I wasn't sure of best way to link to content in github.

**Comment by germa** [comment]
Here's my updated ms.md file:

[ms.md.txt](https://github.com/OBOFoundry/OBOFoundry.github.io/files/186195/ms.md.txt)

**Comment by cmungall** [comment]
Where is the correct download for MOD?

**Comment by nlharris** [comment]
can this be closed?

**Comment by nlharris** [comment]
i think this can be closed, right? if not, please reopen.

**Comment by cmungall** [comment]
Note this contains syntax errors
https://github.com/HUPO-PSI/mzIdentML/issues/117
