### ISSUE TITLE
PLANP prefix and purl request

### ISSUE THREAD

**Issue by srobb1** [OBOFoundry/OBOFoundry.github.io#712]
Hello All,

We are working on a planarian (nonparasitic flatworm) phenotype ontology. We would like to use the prefix PLANP. We currently have a planarian anatomy ontology (PLANA). It will be used by members of the planarian research community. It is in the beginning stages. I have used patterns for generating an "abnormal" term for each of the anatomical structures in PLANA. We are adding in behavior and abnormal behavior now.

- requested prefix: PLANP
- ontology title: Planarian Phenotype Ontology
- ontology download link: https://raw.githubusercontent.com/srobb1/planarian-phenotype-ontology/master/planp.owl
- ontology home page: https://github.com/srobb1/planarian-phenotype-ontology
- point person contact email: smr@stowers.org
- ontology discussion mailing-list: https://github.com/srobb1/planarian-phenotype-ontology/issues
- ontology issue tracker link: https://github.com/srobb1/planarian-phenotype-ontology/issues

Thank you,
Sofia

**Comment by cmungall** [comment]
There have been no objections in the 2 week period so you can go ahead and make a PR for both the md and the yml (these should already be prepared in the metadata folder, as odk was used), and these can be merged if they pass travis.

**Comment by matentzn** [comment]
@srobb1 Do you want to give this a shot? Just ping me on slack if you need help with this!

**Comment by cmungall** [comment]
this has been granted: http://obofoundry.org/ontology/planp
