### ISSUE TITLE
ECTO prefix and PURL request

### ISSUE THREAD

**Issue by diatomsRcool** [OBOFoundry/OBOFoundry.github.io#714]
We would like to request the namespace "ECTO" in the OBO Foundry Library and the corresponding set of PURLS.

- request prefix: ECTO
- ontology title: Environment/Exposures, Conditions and Treatments Ontology
- ontology download link: https://github.com/EnvironmentOntology/environmental-exposure-ontology/blob/master/ecto.owl
- ontology homepage: https://github.com/EnvironmentOntology/environmental-exposure-ontology/
- point person contact email: annethessen@gmail.com
- ontology issue tracker link: https://github.com/EnvironmentOntology/environmental-exposure-ontology/issues
- discussion in obo-discuss forum: https://groups.google.com/forum/#!topic/obo-discuss/Mfbrg5cJ2lM
- ECTO and OBI collaboration discussion: https://github.com/EnvironmentOntology/environmental-exposure-ontology/issues/34

The purpose of this ontology is to create compositional classes that assemble existing OBO ontologies such as ExO, CHEBI and ENVO to make ready-made precomposed classes for use in describing:

- experimental treatments of plants and model organisms (e.g. modification of diet, lighting levels, temperature)
- exposures of humans or any other organisms to stressors through a variety of routes, for purposes of public health, environmental monitoring etc
- stimuli, natural and experimental
- any kind of environmental condition or change in condition that can be experienced by an organism or population of organisms on earth

The scope is very general and can include for example plant treatment regimens, as well as human clinical exposures (although these may better be handled by a more specialized ontology)

**Comment by matentzn** [comment]
As there seem to be no objections to this, can you put on the agenda for our next meeting to create the relevant pull requests?

**Comment by ramonawalls** [comment]
This was approved during the operations committee today. Please create the appropriate YAML files in https://github.com/OBOFoundry/purl.obolibrary.org. If you need any guidance on how to do that, let us know.

**Comment by cmungall** [comment]
This has been added
