### ISSUE TITLE
Make OBO metadata is indexable by google dataset search

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#716]
Google are now indexing datasets
https://www.blog.google/products/search/making-it-easier-discover-datasets/

I tried ontology search
https://toolbox.google.com/datasetsearch/search?query=ontology

It looks like it is getting ontologies from datahub.io

Look at the OBI entry:
https://toolbox.google.com/datasetsearch/search?query=ontology&docid=AkOH6q%2FDwtfFIaOsAAAAAA%3D%3D

```
Latest version (2011-07-20, OBI ICBO 2011 release): http://purl.obolibrary.org/obo/obi.owl
2011-04-20, OBI San Diego 2011 release: http://purl.obolibrary.org/obo/obi/2011-04-20/obi.owl 
RC2 2010-10-26: http://purl.obolibrary.org/obo/obi/2010-10-26/obi.owl
RC1 2009-11-09: http://purl.obolibrary.org/obo/obi/2009-11-09/obi.owl
```

this is out of date.

Same for the GO entry:
https://toolbox.google.com/datasetsearch/search?query=gene%20ontology&docid=LDaUvZbh12kU%2Be0cAAAAAA%3D%3D

We should make sure that the canonical records in obofoundry.org are indexable. Google provides good documentation on how to embed schema.org markup. We should do this.

@simonjupp - is this something you have been thinking from an OLS perspective?

**Comment by simonjupp** [comment]
We have schema.org markup in OLS on both the ontology page and individual term page. At the time I hijacked the existing medical code section of schema.for terms and the ontologies themselves are types of creative work. 

 * Markup in ontology pages: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.ebi.ac.uk%2Fols%2Fontologies%2Fobi
 * Markup in term pages:  https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.ebi.ac.uk%2Fols%2Fontologies%2Fobi%2Fterms%3Firi%3Dhttp%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBI_0000070

We've revisited this a bit for bioschemas.org and think the pending extensions for  https://pending.schema.org/CategoryCode and https://pending.schema.org/CategoryCodeSet are a better fit. For the biosamples database we use the combination of PropertyValue and CategoryCode to capture how data is annotated with an ontology term https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.ebi.ac.uk%2Fbiosamples%2Fsamples%2FSAMN03975629. 

I guess what we've done doesn't really fit with describing an ontology as a dataset, but google have a fairly broad definition of dataset so maybe it's ok to mark them up as such on the OBO site.

**Comment by cmungall** [comment]
Thanks, very helpful. I guess google isn't picking this up yet?

ontology:

Looks like you are missing some fields like license, homepage, ...

What should our strategy be for helping search? Should we just have a keywords field that is crammed full of possible search terms? AFAICR you were working on annotating the ontologies with edam?

codingSystem/value: we should probably have OBO recommendations here or else we will see people doing all permutations of OBI_nnn, OBI:nnn, nnn, ... does it make sense to have the coding system be "obo" and the value be a CURIE? Or duplicate the prefix in the coding system (which could lead to clashes)?

**Comment by simonjupp** [comment]
Given we've just typed the ontologies as creative works, I don't expect them to be indexed in any meaningful way yet. 

I've started a fork of the bioschemas repo to add a spec for ontologies. We should decide if CategoryCodeSet or DefinedTermSet are a good fit for ontologies, I think it's good to go with something broad/inclusive. https://github.com/simonjupp/specifications/tree/master/Ontology

**Comment by cmungall** [comment]
+1 for broad

indexing: I assume there is basic text search happening, so I was just thinking of something dumb like a keyword field and populating it with everything a user might search on that should lead to that ontology

**Comment by simonjupp** [comment]
Agreed on filling the keyword property with data. 

I should stress that CategoryCodeSet and DefinedTermSet are both pending terms and it's not clear if these would ever make it into the Google dataset search index. If you want the ontologies to be indexed they'll have to be typed as a Dataset. For OLS we'll probably do both as they serve different use cases for us. I'm also going to put some markup in the OLS homepage to describe it as a DataCatalog. The foundry pages could use the `includedInDataCatalog` property to point to the entry in OLS. I also suggest we agree to use `sameAs` and point to the ontology IRI so the ontologies will share a common identity across resources. 

There's more info on what properties to use here https://developers.google.com/search/docs/data-types/dataset

**Comment by mcourtot** [comment]
Also try and have meaningful names/description - we have DataCatalog labeled as 'BioSamples' and then Dataset which we labeled only as 'Samples collection' as DataSet are contained in DataCatalog - but Google seems to index only the former :(

**Comment by nlharris** [comment]
Closing; reopen if needed
