### ISSUE TITLE
Add github handles to contact metadata

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#725]
Will require simultaneous extension of json-schema (optional field) plus adding of fields

I know many users handles so I will make the first pass, then we can crowdsource

**Comment by beckyjackson** [comment]
It looks like many contacts have github handles now. Can we move the `github` property to recommended, and issue a warning if it's missing?

**Comment by cmungall** [comment]
@beckyjackson - agreed!!!

**Comment by nlharris** [comment]
@beckyjackson is this something you could do?

**Comment by rvita** [comment]
This is something that I have been working on, but as a low priority.

**Comment by cthoyt** [comment]
Done in #1716
