### ISSUE TITLE
OPMI prefix and PURL request

### ISSUE THREAD

**Issue by yongqunh** [OBOFoundry/OBOFoundry.github.io#731]
Requested Prefix: OPMI

Ontology Title: Ontology of Precision Medicine and Investigation

Download link: https://raw.githubusercontent.com/OPMI/opmi/master/src/ontology/opmi-merged.owl  

Home page: https://github.com/OPMI/opmi 
 
Contact e-mail: yongqunh@med.umich.edu  

Mailing-list: opmi-discuss@@googlegroups.com    

Tracker link: https://github.com/OPMI/opmi/issues  

Description: 
The purpose of the Ontology of Precision Medicine and Investigation is to ontologically represent and standardize various entities and relations related to precision medicine and its associated investigations. Our current use cases include the new NIH-supported kidney precision medicine project (http://kpmp.org) and a respiratory disease precision medicine studies. 

Note: We submitted the request to obo-discuss <obo-discuss@googlegroups.com> on August 11, 2018. So far there has been no objection:   
https://groups.google.com/forum/#!searchin/obo-discuss/OPMI%7Csort:date/obo-discuss/jGMrmAJHPi4/MxnKcOcVAQAJ

**Comment by cstoeckert** [comment]
OPMI is listed on the OBO Foundry so this appears to be done.
