### ISSUE TITLE
Request for CPO prefix and PURL

### ISSUE THREAD

**Issue by CooperStansbury** [OBOFoundry/OBOFoundry.github.io#736]
Hello Everyone!

Requested Prefix: CPO
Ontology Title: Causal Pathway Ontology
Download link: hhttps://github.com/Display-Lab/cpo/blob/master/cpo.owl](https://github.com/Display-Lab/cpo/blob/master/cpo.owl) 
Home page: [https://github.com/Display-Lab/cpo](https://github.com/Display-Lab/cpo)
Contact e-mail: Zach Landis-Lewis <zachll@umich.edu>
Mailing-list:  [https://github.com/Display-Lab/cpo/issues](https://github.com/Display-Lab/cpo/issues)
Tracker link: [https://github.com/Display-Lab/cpo/issues](https://github.com/Display-Lab/cpo/issues)
Description: Casual Pathway Ontology (CPO) is an application ontology of information content entities regarding mechanisms involved in behavior change interventions. CPO is lightweight, making it easy to manage. CPO currently imports Basic Formal Ontology (BFO), Information Artifact Ontology (IAO) and the Relations Ontology (RO). CPO is part of a knowledge base that is used to tailor performance reports to healthcare professionals. 

See more here:
[https://github.com/Display-Lab/cpo](https://github.com/Display-Lab/cpo)

**Comment by pbuttigieg** [comment]
@CooperStansbury 


On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.
