### ISSUE TITLE
Request for PSDO prefix and PURL

### ISSUE THREAD

**Issue by CooperStansbury** [OBOFoundry/OBOFoundry.github.io#737]
Requested Prefix: PSDO
Ontology Title: Performance Summary Display Ontology
Download link: [https://github.com/Display-Lab/psdo/blob/master/psdo.owl](https://github.com/Display-Lab/psdo/blob/master/psdo.owl)
Home page: [https://github.com/Display-Lab/psdo](https://github.com/Display-Lab/psdo)
Contact e-mail: Zach Landis-Lewis <zachll@umich.edu>
Mailing-list:  [https://github.com/Display-Lab/psdo/issues](https://github.com/Display-Lab/psdo/issues)
Tracker link: [https://github.com/Display-Lab/psdo/issues](https://github.com/Display-Lab/psdo/issues)
Description: The Performance Summary Display Ontology (PSDO) is a lightweight application ontology used to reproducibly study visualizations of clinical performance and their associated outcomes in healthcare quality improvement settings. PSDO extends boundaries of visual representation artifacts by the IAO in the domain of distributed representations. PSDO describes dimensional representations of relational information displays that can be used to study the influence of feedback interventions on clinical practice.

See more here:
[https://github.com/Display-Lab/psdo](https://github.com/Display-Lab/psdo)

**Comment by pbuttigieg** [comment]
@CooperStansbury 

On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.

**Comment by cmungall** [comment]
It looks like this was never completed

I merged #852 which updates the main metadata (I may have done this prematurely, as there was no response to @pbuttigieg's comments above, apologies).

However, we are lacking an entry in the purl registry, so psdo.owl doesn't resolve, we have an empty ontology in OLS, etc

**Comment by cmungall** [comment]
It looks like the .owl file you produce @CooperStansbury is not finished yet

https://github.com/Display-Lab/psdo/blob/master/psdo.owl

e.g. is uses lowercase psdo PURLs

**Comment by CooperStansbury** [comment]
@grosscol @zachll it looks like there are a few changes before this is ready. Feel free to reach out to me. 

[https://github.com/OBOFoundry/purl.obolibrary.org/](https://github.com/OBOFoundry/purl.obolibrary.org/)

**Comment by grosscol** [comment]
@CooperStansbury If you want to address any structural changes to the owl file, I can sort out adding the custom term browser to 'ontology/psdo.md` such that the terms resolve to URL fragments on a github.io page for the ontology.

**Comment by jamesaoverton** [comment]
See PURL request here https://github.com/OBOFoundry/purl.obolibrary.org/pull/714

**Comment by jamesaoverton** [comment]
All done!
