### ISSUE TITLE
Request for VIRO prefix and purl

### ISSUE THREAD

**Issue by arpcard** [OBOFoundry/OBOFoundry.github.io#742]
We’d like to request a PURL and prefix in OBO for the Virulence Ontology (VIRO) we developed. Here is the information: 

**Ontology title:** Virulence Ontology
**Requested prefix:** VIRO
**Download link:** https://raw.githubusercontent.com/arpcard/viro/master/viro.owl
**Homepage:** https://github.com/arpcard/viro
**Contact email:** card@mcmaster.ca 
**Mailing-list:** https://mailman.mcmaster.ca/mailman/listinfo/card-l 
**Tracker link:** https://github.com/arpcard/viro/issues 
**PURL username:** arpcard

**Description:**
The Virulence Ontology describes bacterial virulence resistance genes, their products, mechanisms, targets, and associated phenotypes. It is integrated with the Comprehensive Antibiotic Resistance Database (https://card.mcmaster.ca), a curated resource containing high quality reference data on the molecular basis of antimicrobial resistance.

Thanks!

**Comment by cmungall** [comment]
Can you say more about how you intend to reuse existing OBOs, including

 * GO (e.g. biofilm foundation)
 * PRO (e.g. EbpA, EbpB)

What unique classes do you see VIRO contributing to OBO?

**Comment by pbuttigieg** [comment]
@arpcard 

On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.
