### ISSUE TITLE
OBIB (ontology for biobanking) is not shown on ontology page

### ISSUE THREAD

**Issue by zhengj2007** [OBOFoundry/OBOFoundry.github.io#75]
OBIB (ontology for biobanking) does not show on ontology page:
http://obofoundry.github.io/

How to add the OBIB link in?
http://obofoundry.github.io/ontology/obib.html

**Comment by cmungall** [comment]
Looks like I forgot to git add! Done. You can edit the details yourself

For future ref, to add a new ontology, make an md file (use another as template is probably easiest) then go

    cd ontology
    git add foo.md
    git commit -m new foo.md

Note that OBO admins can do this directly on master. Community must do this on a fork/branch and make a PR (or ask an OBO admin).

Unfortunately there is no way to do this over the GH web interface yet. in theory it wouldn't be hard to write a web app to do this, using github OAth credentials, if someone has the time.

**Comment by cmungall** [comment]
Hmm, it turns out I had added it. 

OK, I misread your question which was about the table on the front page. I will add something to the README. An obo admin needs to type `make` and then commit
