### ISSUE TITLE
OBO-discuss link needed for ontology registration FAQ

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#757]
The FAQ for ontology registration instructs the user to announce their ontology on the OBO-discuss list, but there is no link to the list. It would be helpful to have it.

http://obofoundry.org/faq/how-do-i-register-my-ontology.html

**Comment by mcourtot** [comment]
PR at https://github.com/OBOFoundry/OBOFoundry.github.io/pull/758

**Comment by nlharris** [comment]
http://obofoundry.org/faq/how-do-i-register-my-ontology.html no longer mentions the OBO-discuss mailing list. Can this ticket be closed as obsolete?

**Comment by nataled** [comment]
Yes. The FAQ points to a page with the appropriate link in place.
