### ISSUE TITLE
Request for XPO prefix and purl

### ISSUE THREAD

**Issue by seger** [OBOFoundry/OBOFoundry.github.io#765]
The Xenopus Phenotype Ontology is now in development and I wish to request the XPO prefix and PURL in OBO.

Requested prefix: XPO

Ontology title: Xenopus Phenotype Ontology

Download link: https://github.com/obophenotype/xenopus-phenotype-ontology/blob/master/xpo.owl

Home page: https://github.com/obophenotype/xenopus-phenotype-ontology

Contact email: esegerd3@gmail.com

Mailing list: https://groups.google.com/forum/#!forum/xenopus-phenotype-ontology-discuss

Tracker link: https://github.com/obophenotype/xenopus-phenotype-ontology/issues

Description:
The purpose of the Xenopus Phenotype Ontology is to represent and standardize anatomical, cellular, and gene function phenotypes in Xenopus laevis and tropicalis, the African clawed frogs. The XPO is being designed primarily to support phenotype curation in Xenbase (http://www.xenbase.org/), the model organism database for Xenopus, and to facilitate mappings between frog phenotypes and human disease.

**Comment by cmungall** [comment]
This has been granted: http://obofoundry.org/ontology/xpo
