### ISSUE TITLE
Create a Jenkins2 instance for running OBO consistency checks

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#778]
See also #515 

We will try and experiment where we do this with Jenkins, @kltm @dougl1sqrd I believe we will want a new repo in which to keep the Jenkinsfile

**Comment by jamesaoverton** [comment]
If possible, I'd like to use the same Jenkins intance to do additional ROBOT testing: 
https://github.com/ontodev/robot/issues/369

**Comment by kltm** [comment]
@cmungall I think the BBOP Jenkins might be fine, once we clear out the "must run" jobs, we can finally upgrade to Jenkins 2 and move it forward. Otherwise, if we need something OBOFoundry specifc, we can setup shop somewhere fresh.

**Comment by kltm** [comment]
All said, I would highly recommend having a declarative pipeline Jenkinsfile as the core runner.

**Comment by nlharris** [comment]
still in progress?

**Comment by matentzn** [comment]
All of this is subsumed by the dashboard now; for the next 1-2 years we don't need to care about it, because I am taking care of it, but then we need to think again.

**Comment by jamesaoverton** [comment]
This is better covered elsewhere, so I'm closing.
