### ISSUE TITLE
Implement handshake with biosharing

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#79]
cc @proccaserra, Peter McQuilton

**Comment by cmungall** [comment]
notes from call with Peter:

We are add reciprocal links to biosharing. We can link using the obo ontology ID and biosharing will resolve

**Comment by nlharris** [comment]
Is @cmungall the only person who can address this?

**Comment by jonquet** [comment]
FYI: FAIRsharing is pulling content automatically from NCBO BioPortal (@graybeal) which is itself pulling content from OBO Foundry. 
So in theory, there is no need for the OBO Foundry to bother implementing a direct handshake with FAIRsharing. But of course FAIRsharing will have to confirm this. 

Side note: FAIRsharing is also regularly pulling content from AgroPortal (and manage the duplicate for ontologies coming from different resources). 
We have discussed with them how to harmonize the metadata between AgroPortal's model and FAIRsharing. But there is for the moment no handshake (i.e. metadata synchronization) between OBO Foundry and AgroPortal (we sync metadata manually) neither for BioPortal.

**Comment by matentzn** [comment]
@cmungall please close this ticket or extract concrete action items

**Comment by nlharris** [comment]
I'm going to close this; if there are specific action items, please create a new ticket.
