### ISSUE TITLE
ncbitaxon needs contact & license

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#791]
per obo services grant checking that all ontologies have a human's email address, noted that obo-taxonomy@lists.sourceforge.net is the provided contact for ncbitaxon. This email address did not respond to me when I emailed it. Also noted license is missing, will request it once there is a human to contact.

**Comment by cmungall** [comment]
From
http://obofoundry.org/ontology/ncbitaxon

```
Releases of the obo/owl happen when the Continuous Integration Job is manually triggered. Currently this must be done by an OBO administrator. There is currently no fixed cycle, and this is generally done on demand. The team that informally handles this are:

James Overton, IEBD/OBO
Frederic Bastian, BgeeDb/Uberon
Chris Mungall, LBNL/GO/Monarch/Uberon/OBO
Peter Midford, Phenoscape
```

In practice it's me that presses the button on Jenkins so it should be me listed. This would be more useful than the generic obo contact. However, my name is on too many ontologies. Does anyone else from the @OBOFoundry/community or OBO taxonomy group want to be listed?

@pmidford? @balhoff

**Comment by fbastian** [comment]
You can add me, yes.

**Comment by balhoff** [comment]
@rvita sorry, I used to moderate obo-taxonomy@lists.sourceforge.net, but it mostly just gets spam these days. I wonder if there is any interest in reviving it.

**Comment by cmungall** [comment]
upstream ticket: https://github.com/obophenotype/ncbitaxon/issues/14

**Comment by beckyjackson** [comment]
License taken care of in #837. We still need a single contact though. It looks like @fbastian agreed to be added, should we move forward with this?

**Comment by cmungall** [comment]
Yes, please list @fbastian

**Comment by cmungall** [comment]
@rvita can you update the metadata? I think some people have been emailing the list and not getting a response (sorry @sierra-moxon)

**Comment by rvita** [comment]
update was done & merged

**Comment by yongqunh** [comment]
Great. Thanks!
