### ISSUE TITLE
sep needs contact info

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#792]
per OBO services grant, checking that all ontologies can be contacted and was unable to contact sep. Sample   processing and separation techniques contact label is  'SEP developers via the PSI and  MSI mailing lists' with email address of psidev-gps-dev@lists.sourceforge.net. This address was used on several occasions and no answer was ever received. sep also needs license info, will request once I have a contact person.

**Comment by cmungall** [comment]
All mailing lists here:
http://psidev.info/mailing-lists

General docs for full PSI family here:
http://www.psidev.info/groups/controlled-vocabularies

From this:
https://github.com/HUPO-PSI/gelml/commits/master/CV/sep.obo

All commits were by Yasset Perez-Riverol @ypriverol, so I nominate them as the contact, if they are willing

**Comment by rctauber** [comment]
SEP now has contact info, but it's still missing a license.

**Comment by beckyjackson** [comment]
SEP is marked as obsolete and inactive. Do we want to close this issue?

**Comment by nlharris** [comment]
Seems like this issue could be closed.
