### ISSUE TITLE
Ensure description fields are concise enough to fit into table

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#8]
Proposed recommendation:

Keep the description field concise. Don't write it like a paper abstract. Say immediately what the ontology contains.

Add more details as necessary in the markdown section

**Comment by cmungall** [comment]
Proposed policy:

 * Keep it to one sentence
 * Keep it concise
 * Do not include redundant information; e.g. don't provide the title or acronym; don't say who developed it -- these are all in other fields
 * Do not use qualifiers that will become redundant, e.g. "a new ontology that..."
 * Do not use adjectives that are truisms. E.g. don't say "A community ontology..." as all ontologies here are community ontologies
 * Do not use weasel phrases that take up room, e.g. "An ontology that is intended to..." just say directly what it is for
 * Don't pad. E.g. "X is under development as a community effort to provide standard terms for annotating Y" is redundant phrasing that holds for all ontologies here.
 * Don't puff up and allude to OBO principles in the description, or BFO; e.g "X is developed by following OBO Foundry principles and aligning with the BFO top ontology". This is true of most.  
 * Don't put information in parenthesis - more details can always go in the page itself. Minor clarification, e.g. informal taxon names OK

**Comment by nlharris** [comment]
Has this policy been incorporated into the appropriate policy doc? If so, I think this issue can be closed. If not, where should it go and who could put it there?

**Comment by nlharris** [comment]
Where would this advice go?

**Comment by nlharris** [comment]
seems like this still needs to be added to some documentation. maybe to http://obofoundry.org/principles/fp-008-documented.html, or make a new page and link from that principle?

**Comment by nlharris** [comment]
Seems like this is addressed by the home page redesign?
