### ISSUE TITLE
Check Dideo status

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#81]
AFAIK the last one that was added to ontologies.txt before the move.

**Comment by cmungall** [comment]
Looks like the last commit on ontologies.txt was a bit garbled:

https://code.google.com/p/obo-registry/source/diff?spec=svn124&r=124&format=side&path=/trunk/metadata/ontologies.txt

The contact is at OHSU, which is not correct and the ontology description is the content...

I will add something then we can have the submitter correct

**Comment by mcourtot** [comment]
looks ok to me now. Sent email to Mathias to check and update if needed.
