### ISSUE TITLE
Check for duplicates in YAML

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#811]
Currently it is possible to accidentally give multiple values for the same key in an object, and this does not raise any errors; see #812 

It seems this is a deficiency of PyYAML, it will silently ignore the dupes.

**Comment by nlharris** [comment]
Is this still an issue?

**Comment by cthoyt** [comment]
Since we're checking that the yaml is canonical in a principled way, this isn't an issue anymore.
