### ISSUE TITLE
ZP prefix request

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#813]
On behalf of Yvonne Bradford and ZFIN I would like to announce our intention to use the ZP prefix for the pre-coordinated Zebrafish Phenotype Ontology.

An early version, which should NOT be used yet in production, can be viewed here:

https://github.com/obophenotype/zebrafish-phenotype-ontology

The ontology is almost in its entirety derived from ZFIN EQ annotations, and uses the ontology development kit in conjunction with DOSDP patterns for release management and maintenance. Metadata can be found [here](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/metadata/zp.md).

An earlier version of the ZP is currently in use, for example by the Monarch Initiative. The final ontology is likely to include around 30,000 unique phenotype concepts, fully defined using the Entity-Quality (EQ) approach.

Please let us know whether there are any concerns about using the ZP prefix.

**Comment by ramonawalls** [comment]
This was discussed on obo-discuss, with no objections. Approved.
