### ISSUE TITLE
Create an OBO name space

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#819]
This issue was brought up at the operations committee meeting at ICBO 2018. Here are the original notes:

3.1) Move away from project namespaces towards an OBO namespace? 
Need a dedicated pro- and con- discussion, and talk about technical implementation
3.2) Current prefix assignment process. 
If we stick to prefixes, we need to resolve concerns about the 'review process' for requests. There need to be spelled out criteria what is a valid concern and what not. There also needs to be the ability to reserve prefixes early. 

Further discussion of this topic has occurred at several operations committee meetings. It is my view that the consensus is that this is not feasible to move existing ontologies to a single OBO namespace, and there is not a strong motivation to change the policy so that new ontologies use the obo namespace. However, with the creation of an OBO Core ontology, an OBO namespace may become appropriate.

I am creating this issue to capture any points of view that my differ from what I have state above.

**Comment by nlharris** [comment]
did anyone differ with ramona's stated proposals?

**Comment by matentzn** [comment]
I dont see any action items here; the issue can be used for future reference, but for now I will close it.
