### ISSUE TITLE
Add no white space clause to the Naming Convention principle

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/OBOFoundry.github.io#823]
Having leading or trailing white spaces, or extra spaces between words, in labels can cause lots of problems. ROBOT now has a check to identify these. This was discussed at the OBO Ops meeting on 1/28, with an agreement that is should probably be added to this principle.

**Comment by nlharris** [comment]
Seems like this could be added to https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/principles/fp-012-naming-conventions.md ?
