### ISSUE TITLE
Generating 1-page list of Principles

### ISSUE THREAD

**Issue by phismith** [OBOFoundry/OBOFoundry.github.io#831]
Is there some way to have a link under the obofoundry.org Principles tab which take you to a list of all the principles together on one page?

**Comment by cmungall** [comment]
Currently not supported. How high a priority is this? You can see the full list via the menu

**Comment by phismith** [comment]
Not a high priority. But if you are willing to add an extra line to that
menu saying (something like) Entire List, I would be willing to create a
pdf file with the compiled content.
BS

**Comment by cmungall** [comment]
It's maintainability I worry about; doing this as a one-off is easy but
unless there is an automated process in place it will fall out of sync

**Comment by phismith** [comment]
I think you and I would surely notice if the list was changed. And I commit
to recompiling if that happens.
Barry

**Comment by cmungall** [comment]
Oh sorry I misunderstood I thought you wanted the complete text of all on
one page. A page with just the list is easy

**Comment by phismith** [comment]
So can we have that?
BS

**Comment by nlharris** [comment]
Seems like this is satisfied by http://www.obofoundry.org/principles/fp-000-summary.html (not sure if that's a new page). Is that good enough, @phismith?

**Comment by cmungall** [comment]
good enough!
