### ISSUE TITLE
New ontology request: European Medical Information Framework for Alzheimer’s disease ontology

### ISSUE THREAD

**Issue by Isabellebos** [OBOFoundry/OBOFoundry.github.io#832]
Dear,
 
For the European Medical Information Framework for Alzheimer’s disease (EMIF-AD; http://www.emif.eu/emif-ad-2/) project we have created an ontology using the Protégé tool: https://emifad-webprotege.bmd-software.com/#projects/8fbe0d7a-21cc-42ea-9668-a8548dfea207/edit/Classes.
As this ontology is becoming a standard in Alzheimer’s disease research, we would like to publish this ontology. Could you inform us whether this is possible via obo foundary?
 
Thank you in advance.

**Comment by cmungall** [comment]
Hi,

One of the first things we require is a stable URL that resolves to the OWL
(open, not password protected). Are you able to provide that?

**Comment by cmungall** [comment]
Hello @Isabellebos, are you able to provide a download link for the ontology?

**Comment by pbuttigieg** [comment]
@Isabellebos  

On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.
