### ISSUE TITLE
Request for CANVAS prefix and PURL

### ISSUE THREAD

**Issue by kbdhaar** [OBOFoundry/OBOFoundry.github.io#833]
requested prefix: CANVAS
id: canvas
title: Cancer Variables of Social-Ecological Model ontology
home page: https://github.com/kbdhaar/OCRSEV_Main/tree/master/OCRSEV_main
contact: Name: Dharani Balasubramanian ; email:  kbdhaar@gmail.com ;  mailing-list: canvas-ontology@googlegroups.com ; and github username: kbdhaar
tracker: https://github.com/kbdhaar/OCRSEV_Main/issues

Description: CANVAS is developed to incorporate various social-ecological variables related to cancer belonging to five levels of the Social Ecological Model (SEM). This ontology reuses 25 other OBO ontologies. The goal of this ontology is facilitate semantic data integration.

**Comment by pbuttigieg** [comment]
@kbdhaar 

On behalf or the OBO Operations Committee, I apologise for the long waiting period in processing your request:

As new requests have come in, it became clear that a revision of our policies for inclusion of new ontologies was needed. The current state of those policies is viewable here: http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

If you are still interested in pursuing a prefix and IRI handling service for your submission through OBO Services, please respond to this message within two weeks (when our next OBO Operations call will take place). 

If we do not hear from you, we will close this issue; however, you can always reopen it if desired.
Thank you and our apologies once again.
