### ISSUE TITLE
schema validation should output report on stdout/stderr to make travis report useful

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#834]
See:

https://travis-ci.org/OBOFoundry/OBOFoundry.github.io/builds/494050997#L930-L934

It's impossible to see the report; need to either deploy the file somewhere, or just output results

**Comment by rctauber** [comment]
#829 will accomplish this - the script logs better messages to the console so you can see exactly what caused the failure. It shows both warnings and errors. There are just a few things blocking that PR (some missing Metadata). 

It still writes a file as well, so it may be good to also deploy that somewhere?
