### ISSUE TITLE
have obsolete resources at bottom of table on load

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#84]
Wondering if that wouldn't be better - currently stroked out lines look odd (a bit "draft" like) when opening the page.

**Comment by cmungall** [comment]
+1

sorting a bit fiddly, could also just hide and have a separate obsoletes table?

**Comment by mcourtot** [comment]
Saw the sorting :)
Still going through doc, but hopeful I'll find a way to 1) either triage obsolete ones towards a list and loop through this or 2) loop twice through sorted_ontologies for table at bottom of page or 3) create a separate page and call ontology_table ignoring non-obsolete.
*or* we need a parameter we can pass to the page to order on load, which method we could then reuse to order based on column headers (see #43) - though I guess obsolete should always be out of the normal table.

**Comment by jamesaoverton** [comment]
Fixed by afaaf9ef9f574f096859aa5474cce410fad2972f back in November.
