### ISSUE TITLE
Add recommendation for textual definitions of relations

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#846]
Principle 6 "Textual Definitions" says "Textual definitions SHOULD follow Aristotelian form (e.g. “a B that Cs” where B is the parent and C is the differentia), where this is practical." This applies best to class definitions. I would like to expand this recommendation to apply to relations: "a B between D and R, in which C", where D is the domain, R is the range, and C is the differentia.

I've used this pattern in RO Core, and I think it works well. For example RO:0000053 'has bearer' is defined as "A relation between an independent continuant (the bearer) and a specifically dependent continuant (the dependent), in which the dependent specifically depends on the bearer for its existence". When fixing some things on today's OBI call we came across some problems for which this would be a good general solution.

So I propose expanding that sentence to "Textual definitions SHOULD follow Aristotelian form where this is practical: e.g. “a B that Cs” where B is the parent and C is the differentia; or in the case of relations “a B between D and R, in which C” where D is the domain and R is the range."

**Comment by cmungall** [comment]
I think we should give this a go, but I recommend first testing on a broad
section of RO before instituting as a principle. I don't see any reason why
it wouldn't improve things. The definitions would be wordier as we'd use
terms like "the anatomical structure" rather than variables such as "S",
but I think most users would be happy with this.

**Comment by cmungall** [comment]
What should the style be when D=R?

Perhaps "A relation between two Xs where the first X [optional qualifier
describing role] <...> the second X [optional qualifier describing role]"

**Comment by jamesaoverton** [comment]
While textual definitions are required by Principle 6, the wording makes it clear that Aristotelian definitions are just recommended. I'm proposing this as a recommendation with the same (weak) force, more as a starting point than anything else. I have no desire to revise existing definitions en masse. If you can think of a way to make that intention more clear, please let me know.

I think your D=R case would also be a good addition, although if we have more than three examples we might want to restructure the text with bullet points or something.

**Comment by nlharris** [comment]
What's the status of this?

**Comment by cmungall** [comment]
I suggest we consolidate here: https://github.com/oborel/obo-relations/issues/523

And from an OBO side we just say "for relations follow the patterns decided in RO" and link to the documentation page that we will add to close the RO ticket

**Comment by nlharris** [comment]
So I can close this issue?

**Comment by wdduncan** [comment]
IIRC, there was push back on using Aristotelian definitions on an RO call a while back. The person (sorry I can't recall her name) said that the curators couldn't understand the Aristotelian definitions. FWIW, I support adding the recommendation.

**Comment by cmungall** [comment]
This issue can be closed by a PR to principle 6 that clarifies the status of the principle for non-classes.

I propose a slight variation to what James wrote:

 "Textual for classes, definitions SHOULD follow Aristotelian form where this is practical: e.g. “a B that Cs” where B is the parent and C is the differentia. In the case of relations (object properties), we recommend following the patterns established in the Relation Ontology. In the case of annotation properties, we recommend following the patterns established in OMO."

**Comment by cmungall** [comment]
Or we could consider merging this issue into #956, but it has been open a while

**Comment by jamesaoverton** [comment]
I agree that #956 addresses this discussion, so I'll close this issue.
