### ISSUE TITLE
Add explicit github repo field

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#848]
Currently it's possible to get the gh repo from the issues field (if GH is used).

It would be good to have an explicit field for this

In case it's helpful to anyone (or myself when I try this again), I used this horrible hack to check out all repos:

```
grep -h tracker ontology/*md | perl -npe "s@.*https://github.com/@git clone gitATgithub.com:@;s/gitAT/git@/;s@/issues@@" | grep ^git
```

**Comment by nlharris** [comment]
That hack is not horrible; it's awesome.

**Comment by jamesaoverton** [comment]
I support an explicit `repo` field, but I don't think we should require GitHub specifically.

Yes, based on existing tracker field, we could guess most of these.

**Comment by jonquet** [comment]
Note than in MOD 1.4 (and in AgroPortal) we use the DOAP property: doap:repository

https://link.springer.com/article/10.1007/s13740-018-0091-5
https://github.com/sifrproject/MOD-Ontology
http://usefulinc.com/ns/doap#

**Comment by jamesaoverton** [comment]
I found a "repository" field: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/util/schema/registry_schema.json#L368

Seems like enough to close this issue.
