### ISSUE TITLE
"Contact OBO" BFO question (quick)

### ISSUE THREAD

**Issue by WiseDesignCC** [OBOFoundry/OBOFoundry.github.io#851]
I'd like to find some OWL ontologies in OBO that conform to the BFO top-level schema that involve modeling concepts like electronic information, documents, etc. Unfortunately, searching on those things seems to have confused the search engine (understandably). Can anyone point me at a few BFO OWL ontologies? 

(I was going to just email someone, but the OBO page said this was the preferred way to "contact us". I'm aware this isn't really "an issue", and apologize for any confusion this causes)

**Comment by cmungall** [comment]
hi!

Issues are fine but you will likely get a bigger response from the obo-discuss mailing list.

you likely want to start here
http://obofoundry.org/ontology/iao
and feel free to open issues on the IAO issue tracker

**Comment by cmungall** [comment]
cc @zhengj2007
