### ISSUE TITLE
Landing page should use obo-discuss@googlegroups.com email address

### ISSUE THREAD

**Issue by kltm** [OBOFoundry/OBOFoundry.github.io#862]
Currently, the landing page uses the outdated sourceforge.net address; this should probably be removed.

**Comment by kltm** [comment]
Note: 
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/469
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/757
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/435
etc.

**Comment by nlharris** [comment]
Places where the address obo-discuss@lists.sourceforge.net appears:
> docs/Policy_for_OBO_namespace_and_associated_PURL_requests.md:Comments to [obo-discuss@lists.sourceforge.net](mailto:obo-discuss@lists.sourceforge.net)
docs/Policy_for_OBO_namespace_and_associated_PURL_requests.md:  1. First send an email to [obo-discuss](mailto:obo-discuss@lists.sourceforge.net) with your request to allow community feedback (you may need to [register](https://lists.sourceforge.net/lists/listinfo/obo-discuss) first)
legacy/crit.html:	  <a href="mailto:obo-discuss@lists.sourceforge.net">
legacy/participate.html:  <a href="mailto:obo-discuss@lists.sourceforge.net">
principles/fp-010-collaboration.md:It is expected that Foundry ontologies will collaborate with other Foundry ontologies, particularly in ensuring orthogonality of distinct ontologies, in re-using content from other ontologies in cross-product definitions where appropriate, and in establishing and evolving Foundry principles to advance the Foundry suite of ontologies to better serve the joint users. Where there are multiple ontology providers in a particular domain, they are particularly encouraged to get together and determine how the domain should be divided between the ontologies, or whether the ontologies should be merged into a single artifact. Should it be determined that there is a competing ontology in the same domain, the Foundry ontology should invite the developers of the external ontology to collaborate and should strive to negotiate an arrangement that is beneficial to both projects. If necessary, conflicts can be mediated in dedicated workshops or using the obo-discuss@lists.sourceforge.net discussion list where Foundry advisors and members of the editorial board can help the parties negotiate to a mutually agreeable solution. 

I don't know which of these is considered the "landing page" but presumably they should all be changed, right?

There are, additionally, a lot of places in this repo where I see (presumably obsolete) sourceforge URLs or other sourceforge mailing lists:

> _posts/2016-04-19-ECO-OBI-workshop.md:Please contact: mchibucos@som.umaryland.edu or the OBI developer list at obi-devel@lists.sourceforge.net if you are interested in participating. 
docs/Policy_for_OBO_namespace_and_associated_PURL_requests.md:Comments to [obo-discuss@lists.sourceforge.net](mailto:obo-discuss@lists.sourceforge.net)
docs/Policy_for_OBO_namespace_and_associated_PURL_requests.md:  1. First send an email to [obo-discuss](mailto:obo-discuss@lists.sourceforge.net) with your request to allow community feedback (you may need to [register](https://lists.sourceforge.net/lists/listinfo/obo-discuss) first)
docs/Policy_for_OBO_namespace_and_associated_PURL_requests.md:    * [obo-discuss message](https://sourceforge.net/p/obo/mailman/message/35692927/)
faq/how-do-i-edit-metadata.md:mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-cell-type
faq/how-do-i-edit-metadata.md:that the link for "Trackers" says sourceforge. This is out of date, as
faq/how-do-i-edit-metadata.md:The tracker entry in the yaml above is for sourceforge. The
faq/how-do-i-edit-metadata.md:@planteome-user has migrated their tracker from sourceforge to github,
legacy/crit.html:	  <a href="mailto:obo-discuss@lists.sourceforge.net">
legacy/participate.html:  <a href="http://lists.sourceforge.net/lists/listinfo/obo-discuss">
legacy/participate.html:  <a href="mailto:obo-discuss@lists.sourceforge.net">
legacy/relatedprojects.html:<h3> <a href="http://obi.sourceforge.net/">Ontologies for Biomedical Investigations</a></h3> 
legacy/resources.html:	  <a href="http://sourceforge.net/projects/obo">
ontology/caro.md:  source_url: http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/caro/caro.obo
ontology/cl.md:mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-cell-type
ontology/doid.md:DO wiki: http://diseaseontology.sourceforge.net/
ontology/fbsp.md:  source_url: http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/taxonomy/fly_taxonomy.obo
ontology/fma.md:tracker: https://sourceforge.net/p/obo/foundational-model-of-anatomy-fma-requests/
ontology/mamo.md:homepage: http://sourceforge.net/p/mamo-ontology/wiki/Home/
ontology/mamo.md:tracker: http://sourceforge.net/p/mamo-ontology/tickets/
ontology/mo.md:homepage: http://mged.sourceforge.net/ontologies/MGEDontology.php
ontology/mo.md:page: http://mged.sourceforge.net/software/downloads.php
ontology/ms.md:mailing_list: psidev-ms-vocab@lists.sourceforge.net
ontology/ms.md: * https://lists.sourceforge.net/lists/listinfo/psidev-ms-vocab
ontology/ncbitaxon.md:  email: obo-taxonomy@lists.sourceforge.net
ontology/ncbitaxon.md: * https://lists.sourceforge.net/lists/listinfo/obo-taxonomy
ontology/nmr.md:homepage: http://msi-ontology.sourceforge.net/
ontology/nmr.md:page: http://msi-ontology.sourceforge.net/ontology/NMR.owlDocument.doc
ontology/nmr.md:  source_url: https://msi-workgroups.svn.sourceforge.net/svnroot/msi-workgroups/ontology/NMR.owl
ontology/rex.md:  source_url: http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/physicochemical/rex.obo
ontology/sbo.md:tracker: https://sourceforge.net/p/sbo/term-request/
ontology/sep.md:  email: psidev-gps-dev@lists.sourceforge.net
ontology/so.md:mailing_list: https://sourceforge.net/p/song/mailman/song-devel/
ontology/uberon.md:mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-anatomy
ontology/vsao.md:  source_url: http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/tags/vocab-releases/VSAO/vsao.obo
ontology/xlmod.md:mailing_list: psidev-ms-vocab@lists.sourceforge.net
ontology/xlmod.md: * https://lists.sourceforge.net/lists/listinfo/psidev-ms-vocab
principles/fp-010-collaboration.md:It is expected that Foundry ontologies will collaborate with other Foundry ontologies, particularly in ensuring orthogonality of distinct ontologies, in re-using content from other ontologies in cross-product definitions where appropriate, and in establishing and evolving Foundry principles to advance the Foundry suite of ontologies to better serve the joint users. Where there are multiple ontology providers in a particular domain, they are particularly encouraged to get together and determine how the domain should be divided between the ontologies, or whether the ontologies should be merged into a single artifact. Should it be determined that there is a competing ontology in the same domain, the Foundry ontology should invite the developers of the external ontology to collaborate and should strive to negotiate an arrangement that is beneficial to both projects. If necessary, conflicts can be mediated in dedicated workshops or using the obo-discuss@lists.sourceforge.net discussion list where Foundry advisors and members of the editorial board can help the parties negotiate to a mutually agreeable solution. 
registry/ontologies.jsonld:            "DO wiki": "http://diseaseontology.sourceforge.net/",
registry/ontologies.jsonld:                "source_url": "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/caro/caro.obo"
registry/ontologies.jsonld:            "mailing_list": "https://lists.sourceforge.net/lists/listinfo/obo-cell-type",
registry/ontologies.jsonld:            "tracker": "https://sourceforge.net/p/obo/foundational-model-of-anatomy-fma-requests/"
registry/ontologies.jsonld:            "mailing_list": "psidev-ms-vocab@lists.sourceforge.net",
registry/ontologies.jsonld:                "email": "obo-taxonomy@lists.sourceforge.net",
registry/ontologies.jsonld:            "mailing_list": "https://sourceforge.net/p/song/mailman/song-devel/",
registry/ontologies.jsonld:            "mailing_list": "https://lists.sourceforge.net/lists/listinfo/obo-anatomy",
registry/ontologies.jsonld:            "mailing_list": "psidev-ms-vocab@lists.sourceforge.net",
registry/ontologies.jsonld:            "homepage": "http://sourceforge.net/p/mamo-ontology/wiki/Home/",
registry/ontologies.jsonld:            "tracker": "http://sourceforge.net/p/mamo-ontology/tickets/"
registry/ontologies.jsonld:            "tracker": "https://sourceforge.net/p/sbo/term-request/"
registry/ontologies.jsonld:                "source_url": "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/physicochemical/rex.obo"
registry/ontologies.jsonld:                "source_url": "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/taxonomy/fly_taxonomy.obo"
registry/ontologies.jsonld:            "homepage": "http://mged.sourceforge.net/ontologies/MGEDontology.php",
registry/ontologies.jsonld:            "page": "http://mged.sourceforge.net/software/downloads.php",
registry/ontologies.jsonld:                "source_url": "https://msi-workgroups.svn.sourceforge.net/svnroot/msi-workgroups/ontology/NMR.owl"
registry/ontologies.jsonld:            "homepage": "http://msi-ontology.sourceforge.net/",
registry/ontologies.jsonld:            "page": "http://msi-ontology.sourceforge.net/ontology/NMR.owlDocument.doc",
registry/ontologies.jsonld:                "email": "psidev-gps-dev@lists.sourceforge.net",
registry/ontologies.jsonld:                "source_url": "http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/tags/vocab-releases/VSAO/vsao.obo"
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#mailing-list>  "https://lists.sourceforge.net/lists/listinfo/obo-anatomy" ;
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#mailing-list>  "https://lists.sourceforge.net/lists/listinfo/obo-cell-type" ;
registry/ontologies.ttl:        <http://obofoundry.github.io/vocabulary/source_url>  "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/caro/caro.obo" .
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#bug-database>  "https://sourceforge.net/p/obo/foundational-model-of-anatomy-fma-requests/" ;
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#mailing-list>  "psidev-ms-vocab@lists.sourceforge.net" ;
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/mbox>  "obo-taxonomy@lists.sourceforge.net" .
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#mailing-list>  "https://sourceforge.net/p/song/mailman/song-devel/" ;
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#mailing-list>  "psidev-ms-vocab@lists.sourceforge.net" ;
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#bug-database>  "http://sourceforge.net/p/mamo-ontology/tickets/" ;
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/homepage>  <http://sourceforge.net/p/mamo-ontology/wiki/Home/> .
registry/ontologies.ttl:        <http://usefulinc.com/ns/doap#bug-database>  "https://sourceforge.net/p/sbo/term-request/" ;
registry/ontologies.ttl:        <http://obofoundry.github.io/vocabulary/source_url>  "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/physicochemical/rex.obo" .
registry/ontologies.ttl:        <http://obofoundry.github.io/vocabulary/source_url>  "http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/taxonomy/fly_taxonomy.obo" .
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/homepage>  <http://mged.sourceforge.net/ontologies/MGEDontology.php> ;
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/page>  <http://mged.sourceforge.net/software/downloads.php> .
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/homepage>  <http://msi-ontology.sourceforge.net/> ;
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/page>  <http://msi-ontology.sourceforge.net/ontology/NMR.owlDocument.doc> .
registry/ontologies.ttl:        <http://obofoundry.github.io/vocabulary/source_url>  "https://msi-workgroups.svn.sourceforge.net/svnroot/msi-workgroups/ontology/NMR.owl" .
registry/ontologies.ttl:        <http://xmlns.com/foaf/0.1/mbox>  "psidev-gps-dev@lists.sourceforge.net" .
registry/ontologies.ttl:        <http://obofoundry.github.io/vocabulary/source_url>  "http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/tags/vocab-releases/VSAO/vsao.obo" .
registry/ontologies.yml:- DO wiki: http://diseaseontology.sourceforge.net/
registry/ontologies.yml:  build: {method: obo2owl, notes: moving to owl soon, source_url: 'http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/anatomy/caro/caro.obo'}
registry/ontologies.yml:  mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-cell-type
registry/ontologies.yml:  tracker: https://sourceforge.net/p/obo/foundational-model-of-anatomy-fma-requests/
registry/ontologies.yml:  mailing_list: psidev-ms-vocab@lists.sourceforge.net
registry/ontologies.yml:  contact: {email: obo-taxonomy@lists.sourceforge.net, label: obo-taxonomy-list}
registry/ontologies.yml:  mailing_list: https://sourceforge.net/p/song/mailman/song-devel/
registry/ontologies.yml:  mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-anatomy
registry/ontologies.yml:  mailing_list: psidev-ms-vocab@lists.sourceforge.net
registry/ontologies.yml:  homepage: http://sourceforge.net/p/mamo-ontology/wiki/Home/
registry/ontologies.yml:  tracker: http://sourceforge.net/p/mamo-ontology/tickets/
registry/ontologies.yml:  tracker: https://sourceforge.net/p/sbo/term-request/
registry/ontologies.yml:  build: {insert_ontology_id: true, method: obo2owl, source_url: 'http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/physicochemical/rex.obo'}
registry/ontologies.yml:  build: {insert_ontology_id: true, method: obo2owl, source_url: 'http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/taxonomy/fly_taxonomy.obo'}
registry/ontologies.yml:  homepage: http://mged.sourceforge.net/ontologies/MGEDontology.php
registry/ontologies.yml:  page: http://mged.sourceforge.net/software/downloads.php
registry/ontologies.yml:  build: {method: owl2obo, source_url: 'https://msi-workgroups.svn.sourceforge.net/svnroot/msi-workgroups/ontology/NMR.owl'}
registry/ontologies.yml:  homepage: http://msi-ontology.sourceforge.net/
registry/ontologies.yml:  page: http://msi-ontology.sourceforge.net/ontology/NMR.owlDocument.doc
registry/ontologies.yml:  contact: {email: psidev-gps-dev@lists.sourceforge.net, label: SEP developers via
registry/ontologies.yml:  build: {method: obo2owl, source_url: 'http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/tags/vocab-releases/VSAO/vsao.obo'}


>

**Comment by nlharris** [comment]
Should I look into updating all those email addresses myself?

**Comment by jamesaoverton** [comment]
Switching our links from `obo-discuss@lists.sourceforge.net` to `obo-discuss@googlegroups.com` is a priority, because that specific mailing list has been migrated.

Sourceforge website and mailing lists still work (unlike Google Code, which disappeared from the Web). So I don't think there's a general problem, just that specific problem.

**Comment by nlharris** [comment]
Ok, the home page has the newer mailing list link (https://groups.google.com/forum/#!forum/obo-discuss) and I don't see the old obo-discuss@lists.sourceforge.net anywhere except for principles/fp-010-collaboration.md (see PR #1256).

**Comment by nlharris** [comment]
That PR has now been merged, so I'm calling this done.
