### ISSUE TITLE
Revamp issue labels

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#866]
The list of issue tracker labels has reached a rather intimidating length, lacks organization, and has some redundancies. I propose that we revamp these in light of the need for some to be used by those new to the Foundry. To this end, I have constructed a spreadsheet with the current set, along with proposals for clean-up and better documentation:

https://docs.google.com/spreadsheets/d/1IxG_as1fcUewttk05nr6gikYLr07C1H4ze0G_ETtCr4/edit#gid=0

The proposal includes (or will require) the following:

1. Delete some of the unnecessary or redundant labels. In some cases the use of a label-to-delete should be re-assigned to another label.

2. Rename if ambiguous.

3. Provide a short usage indicator.

4. Color-code the labels around a theme--in particular around specific working groups (where applicable). This will make it easier for each WG to review issues of relevance. This will also allow new users to find the labels they would most likely need (IDspace and review requests).

5. Review and clean up label usage.

Of course the proposed names, descriptions, and color scheme are open to discussion. At the moment there are 25 labels; implementing the proposal as-is would drop this number to 19. Hopefully even more can be removed or merged.

**Comment by cmungall** [comment]
This is great, thanks. Ticket metadata hygiene is of utmost importance.

I added a CJM Comments column

Some background that may be useful:

 * Anything that is Type-X was automigrated from gcode. I think we should endeavour to close these. They have been open so long it's unlikely they will get fixed. In many cases there will not be a clear course of action, so it may be better to open new tickets
 * The automigrated tag is actually quite useful for doing this step
 * Some like "enhancement" are github defaults and make more sense for s/w projects happy to delete these

We should create issue templates that auto-label issues, e.g for new ontology requests

**Comment by nataled** [comment]
Some time ago we reviewed those auto-migrated tags and added other labels to them. I already went ahead and added the appropriate new (that is, github) label to those few issues tagged with a Type-X label that lacked the newer tag, so they actually can be deleted. I found that not all cases of Type-X had the auto-migrated tag as well. It was rather inconsistently applied (or was revised upon review). Regarding the github defaults and the Type-technical that you suggested to delete, I presume you mean after appropriate re-tagging? For the latter, I suggested just to rename it to parallel labels for the other WGs.

**Comment by cmungall** [comment]
sounds good, thanks

>

**Comment by nataled** [comment]
Phase 1 complete. Color coding and descriptions added, some names revised, some labels deleted. Currently down to 18 labels (from the original 26).

For the next step, I think the color coding can substitute for the group-specific labels (such as "attn: Editorial WG"). Labels were color coded by which group the issue is most pertinent to (Ops, EWG, OWG, TWG, Users). Removing the specific labels will drop the number to 14.

**Comment by nlharris** [comment]
that sounds reasonable to me. the labels such as "attn: Editorial WG" don't seem particularly useful in practice, and as you noted, the color-coding already captures those.

**Comment by nataled** [comment]
In practice, it seems that the four 'attn' labels have served us well as a way to easily find all pertinent issues. They also seem to be well used. I suggest we keep them and close this issue.

**Comment by nlharris** [comment]
sounds good!
