### ISSUE TITLE
Status of RNAO project

### ISSUE THREAD

**Issue by althonos** [OBOFoundry/OBOFoundry.github.io#867]
Hi!

Currently, RNAO is listed as active on the OBO Foundry, but it has not been updated in 9 years, and contains many errors in both the OBO (unescaped quotes, odd relation semantics) and the OWL product (cardinality errors mostly). It can't be opened by `robot` because of these issues, so I tend to think it is virtually unusable. Should it be listed as *inactive* ?

cc @cmungall 
cc @AntonPetrov

**Comment by cmungall** [comment]
I support this, but cc-ing @leechuck and @micheldumontier who were involved in its construction

I think it's good practice to open an issue about the errors in the respective tracker: https://github.com/BGSU-RNA/rnao/issues (even though the tracker doesn't look very active).

Note that an 'inactive' status doesn't indicate anything about quality of the ontology - I think RNAO is a high quality formalization of RNA structural biology, but it doesn't appear to be actively maintained.

I also wonder if the content has been superseded by the [ncrno](http://www.obofoundry.org/ontology/ncro.html) cc @Huang-OMIT

**Comment by AntonPetrov** [comment]
I will point this out to the BGSU RNA team that hosts the repo and see if they have any input.

**Comment by althonos** [comment]
I opened the following issues in the RNAO repo:
* BGSU-RNA/rnao#2: Unescaped quotes in `rnao.obo`
* BGSU-RNA/rnao#3: Unreachable RO import caused by outdated URL
* BGSU-RNA/rnao#4: Duplicate annotations in `rnao.owl` 
* BGSU-RNA/rnao#5: Typedefs imported from RO should be refered to using xrefs
* BGSU-RNA/rnao#6: Make `RNAO:1000300` obsolete

**Comment by Huang-OMIT** [comment]
@cmungall Chris: I agree with you: most of the content in RNAO has been superseded by the ncro ontology.

**Comment by cmungall** [comment]
I emailed some of the original RNAO developers and will report back.

**Comment by nlharris** [comment]
any word from the RNAO developers?

**Comment by leechuck** [comment]
To the best of my knowledge, RNAO development is inactive; I have not been involved in RNAO for several years. I support moving it to inactive; it can be activated again once the issues have been resolved and the old dev team or a new team continues the development.

**Comment by Huang-OMIT** [comment]
Agree.

**Comment by rvita** [comment]
Colin Batchelor is the one who was giving me updated info on rnao as of last year:  batchelorc@rsc.org
@batchelorc

**Comment by cmungall** [comment]
ok, we are agreed - mark as inactive

>

**Comment by batchelorc** [comment]
I agree.
