### ISSUE TITLE
How do relevant OBO foundry concepts compare to geoscienceontology.org upper level concepts?

### ISSUE THREAD

**Issue by rduerr** [OBOFoundry/OBOFoundry.github.io#869]
One of my goals is to help in my own small way in ensuring that the semantics community becomes more harmonized.  Here is an example of an ontology that has upper level concepts that occur in many parts of the suite of OBO Foundry ontologies.  The number of science disciplines addressed is rapidly growing so it would behoove, the OBO community to determine how compatible this ontology is with OBO concepts.

**Comment by cmungall** [comment]
Thanks for your efforts, much appreciated!

I much prefer doing these kinds of analyses with an OWL file or equivalent. I see there is a sparql endpoint and an API but I just want to look at the ontology in Protege (or online equivalent like OLS).

From the pictures at a broader level things seem compatible:

![image](https://user-images.githubusercontent.com/50745/57113181-46fa2a80-6cf8-11e9-99fb-978f3133c292.png)

This looks very much like one of the early PATO diagrams and how PATO is used. We describe processes or their participants by attaching qualities/characteristics, and this is essentially the same pattern used in ontologies like ENVO to describe concepts like amount of rain etc.

Can you get a hold of the OWL?

**Comment by rduerr** [comment]
Yes, information on how to download the files are at http://geoscienceontology.org/documentation/obtain_files.html

Typically by issuing: 

curl -sH "accept:application/rdf+xml" -L http://www.geoscienceontology.org/svo/svu > svo-upper.rdf

or the equivalent for the other lower level ontology files

**Comment by cmungall** [comment]
Should we continue to house this ticket here? I am not sure there is much for the OBO community to do at the moment. 

I think the very first thing to do is to align on base representation semantics. It looks like SVL is not really represented in OWL, e.g.

![image](https://user-images.githubusercontent.com/50745/60370228-e8c18f00-99aa-11e9-9b8d-e848b0eb1528.png)

I will play will some kind of transformation to see if I can get it into a meaningful OWL representation

**Comment by cmungall** [comment]
Hmm, it seems SVL is more of a dictionary than an ontology? Most of the sub-ontologies are just flat lists with lexical properties, e.g.

`curl -sH "accept:text/turtle" -L http://www.geoscienceontology.org/svo/svl/process`

```
###  http://www.geoscienceontology.org/svo/svl/process#armament
:armament rdf:type owl:NamedIndividual ,
                        svu:Process ;
                        svu:hasPresentTense "armor" ;
                        svu:hasPresentParticiple "armoring" ;
                        svu:hasNominalization "armament" ;
                        skos:prefLabel "armament"@en .

###  http://www.geoscienceontology.org/svo/svl/process#arrest
:arrest rdf:type owl:NamedIndividual ,
                        svu:Process ;
                        svu:hasAssociatedWikipediaPage "https://en.wikipedia.org/wiki/Arrest" ;
                        svu:hasPresentTense "arrest" ;
                        svu:hasPresentParticiple "arresting" ;
                        svu:hasNominalization "arrest" ;
                        skos:prefLabel "arrest"@en .

###  http://www.geoscienceontology.org/svo/svl/process#arrival
:arrival rdf:type owl:NamedIndividual ,
                        svu:Process ;
                        svu:hasPresentTense "arrive" ;
                        svu:hasPresentParticiple "arriving" ;
                        svu:hasNominalization "arrival" ;
                        skos:prefLabel "arrival"@en .

###  http://www.geoscienceontology.org/svo/svl/process#ascension
:ascension rdf:type owl:NamedIndividual ,
                        svu:Process ;
                        svu:hasPresentTense "ascend" ;
                        svu:hasPresentParticiple "ascending" ;
                        svu:hasNominalization "ascension" ;
                        svu:hasNominalization "ascent" ;
                        skos:prefLabel "ascension"@en .

###  http://www.geoscienceontology.org/svo/svl/process#aspiration
:aspiration rdf:type owl:NamedIndividual ,
                        svu:Process ;
                        svu:hasPresentTense "aspire" ;
                        svu:hasPresentParticiple "aspiring" ;
                        svu:hasNominalization "aspiration" ;
                        skos:prefLabel "aspiration"@en .
```

I think some of the starting assumptions are so radically different that it's not really meaningful to compare yet. Does svl have a tracker we could carry on this discussion? I could also potentially give a presentation on OBO.

If you like you can file a ticket on this repo which is some experimental code to "OWLize" ontologies, thesauri and term lists of various forms: https://github.com/cmungall/owl_patternizer
