### ISSUE TITLE
update mamo

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#87]
from @niko-rodrigue 

Hello,

We would like to update the information about the mamo ontology owl file.

In http://www.obofoundry.org/cgi-bin/detail.cgi?id=mamo and in
http://obo-registry.googlecode.com/svn/trunk/metadata/ontologies.txt
the link is incorrect.

It is also the link used for http://purl.obolibrary.org/obo/mamo.owl on
the new web site at http://obofoundry.github.io/.

The correct link is
http://sourceforge.net/p/mamo-ontology/code/tags/latest/mamo-xml.owl.

Could you update the link, please ?
I tried to update the information on
http://obofoundry.github.io/ontology/mamo.html but the owl
file link is not stored there.

Thanks,
Nico

**Comment by mcourtot** [comment]
The SF link you indicate gives me a 404. Also, do you prefer to have a link towards a "raw" file? That would make it directly openable in Protege for example.

**Comment by niko-rodrigue** [comment]
yes, sorry, that's the link if you use subversion to get it.
The html link should be https://sourceforge.net/p/mamo-ontology/code/HEAD/tree/tags/latest/mamo-xml.owl?format=raw

**Comment by mcourtot** [comment]
I did the update but it seems the "raw" parameter is not passed, so I get served the HTML. Pinging @cmungall if he has any idea.

**Comment by niko-rodrigue** [comment]
I found a direct link without parameter in the url:
https://svn.code.sf.net/p/mamo-ontology/code/tags/latest/mamo-xml.owl

**Comment by niko-rodrigue** [comment]
I was looking at the go.md to see what is defined there and one solution could also be to define something like what they have :
build:
  checkout: svn --ignore-externals co svn://ext.geneontology.org/trunk/ontology
  system: svn
  method: vcs
  infallible: 1

**Comment by cmungall** [comment]
> https://svn.code.sf.net/p/mamo-ontology/code/tags/latest/mamo-xml.owl

this should work.

I recommend using the owl2obo build method (see the kisao entry). The svn/git co method is best if you have a whole 'distribution' (e.g. an obo and owl file, possibly subsets, other editions, supporting documentation).

The owl2obo method is a bit of a misnomer - it will run OORT using your owl as a base and make obo as well as rdf/xml owl (you provide owl-xml as source, but we recommend using the uglier but more widely consumed rdf form) and place these in the berkeley folder which is the default fall-through for unregistered purls.

You way want to look at making your own ontology build pipeline, e.g. using travis+robot https://github.com/ontodev/robot/

**Comment by niko-rodrigue** [comment]
I tried to access http://purl.obolibrary.org/obo/mamo.owl this morning and got the old version. When will the changes be propagated to the purl url ?

**Comment by mcourtot** [comment]
I just updated the PURL - this needs to be done manually.
If you give me your PURL user name I can add you to the obo-mamo group
which maintains them.

**Comment by niko-rodrigue** [comment]
If it need to be done after each release it might be useful for me to be able to update the files.
Although, I don't have a PURL name, I just tried to register on purl.org but it does not seems to work at the moment (I am getting "Create Failed: undefined (500)"). I will update the issue once I succeed to create my PURL user.

**Comment by mcourtot** [comment]
I redirected the PURL towards
https://svn.code.sf.net/p/mamo-ontology/code/tags/latest/mamo-xml.owl
So as long as your latest release uses this URL you don't have to touch it.



On Tue, Sep 1, 2015 at 10:34 AM, Nicolas Rodriguez <notifications@github.com

**Comment by niko-rodrigue** [comment]
That should be fine then. Although we would need to do the same for kisao as the purl does not resolve, see #67

**Comment by mcourtot** [comment]
:) there was no PURL for kisao - created now.
Lemme know when you have a PURL username and I'll add you to both.

**Comment by niko-rodrigue** [comment]
Thanks

**Comment by cmungall** [comment]
Is this done?

Note
 http://purl.obolibrary.org/obo/mamo.owl

resolves to OWL-XML (note: distinct from OWL RDF/XML). This is suboptimal, many RDF based parsers will not be able to consume this. We (obo) need to add documentation on standard release practices.
