### ISSUE TITLE
Request to register new ontology: GNO (glycan naming ontology)

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#875]
SUBMITTED ON BEHALF OF @edwardsnj

> Ontology title
> Concise title of your ontology (e.g, "Gene Ontology") 

Glycan Naming Ontology (GNOme)

> Requested IDspace
> Prefix of ontology in lowercase (e.g., go, uberon, chebi, cl). The OBO Foundry ID policy is described at http://obofoundry.org/id-policy.html <https://www.google.com/url?q=http://obofoundry.org/id-policy.html&sa=D&ust=1558462660064000&usg=AFQjCNEsNZrc8rTsZ6iORaer_gdob0-jmQ> 

gno

> What domain is the ontology intended to cover?
> For example, the GO covers the processes, functions and cellular locations of gene products. 

Glycan structures

> Ontology location
> Home page or URL of ontology. This can be a GitHub URL. 

https://github.com/glygen-glycan-data/GNOme

> Contact person
> Name, email address, and GitHub username of contact person. 

Nathan Edwards, nje5@georgetown.edu, edwardsnj

> Issue tracker
> URL for submitting and responding to suggestions, requests, etc. (e.g., https://github.com/geneontology/go-ontology/issues/ <https://www.google.com/url?q=https://github.com/geneontology/go-ontology/issues/&sa=D&ust=1558462660067000&usg=AFQjCNGVCAJS5jSOYxKJI1jtiCiugmUI6w>). 

https://github.com/glygen-glycan-data/GNOme/issues

> Ontology license
> Current license. Note that the OBO Foundry accepts CC0 or CC-BY. The OBO Foundry license policy is described at http://www.obofoundry.org/principles/fp-001-open.html <https://www.google.com/url?q=http://www.obofoundry.org/principles/fp-001-open.html&sa=D&ust=1558462660068000&usg=AFQjCNE1gXIAV29bPhoYGN02XVQOe7E_xw>.
> Choose one of the following (mark with asterisk):
>     CC0 (public domain)
>     CC-BY (version 3 or later)
> Other: 

CC-BY (for now). Exploring the possibility of CC0.

> Available ontology formats
> Note that OWL-RDF/XML is the only required format. The OBO Foundry format policy is described at http://obofoundry.org/principles/fp-002-format.html <https://www.google.com/url?q=http://obofoundry.org/principles/fp-002-format.html&sa=D&ust=1558462660070000&usg=AFQjCNFwyTehXydfpHkPjB_DVmP-UqQCjg>. 

OWL-RDF/XML (primary); OBO (derived), JSON-LD (derived)

> Data source
> Which resource, if any, was used to generate the ontology (e.g., NCBITaxon was created from the NCBI taxonomy resource; the Protein Ontology uses, in part, UniProtKB). 

Glycan structures and subsumption categories are from GlyTouCan
(glytoucan.org), subsumption relationships (subClassOf) are automatically computed.

> Related OBO Foundry ontologies
> What other ontologies are you aware of that intersect with your domain, and what are your plans for collaborating with them? 

ChEBI (oligosaccharide, polysaccharide, specific structures described as
IUPAC strings); GNOme is part of the GlyGen project, and GlyGen and
ChEBI are already looking for suitable collaboration connection points.

> Intended use/related projects
> Is your ontology serving the need of one or more specific projects? If so, please describe them. 

GlyGen, GlyTouCan

**Comment by lschriml** [comment]
Discussed on Operations call, 08/13/2019, Decision: Agreed to approve the request. 
Darren will contact the group. 
James will ask Becky to do the YAML for this group.

**Comment by beckyjackson** [comment]
@edwardsnj could you please provide a brief description of GNO for the registry page?

Additionally, do GlyTouCan and GlyGen already use GNO? If so, could you provide a link to an example of use for each?

**Comment by edwardsnj** [comment]
Great, thanks @beckyjackson for helping get this set up. 

How about:

 An ontology for glycans based on GlyTouCan, but organized by subsumption.

GNOme has not yet been adopted explicitly by GlyTouCan or GlyGen, though I will be helping both groups find use-cases for the ontology. The github repository provides a browser/viewer for the ontology ( https://raw.githack.com/glygen-glycan-data/GNOme/master/GNOme.browser.html ), and my site that prepares glycan annotations for GlyGen ( http://grg.tn/GlycanData ) uses GNOme for glycan annotations and annotation inference.

**Comment by nataled** [comment]
To add to the above, PRO will be using GNOme to create specific glycoprotein terms, in the same way something like PSI-MOD is used (has_part MOD:00046 indicates a proteoform is phosphorylated on some serine). Glycans are not well represented by any other ontology.

**Comment by beckyjackson** [comment]
Thanks for the details! @jamesaoverton should I create a purl config file for GNO as well?

**Comment by jamesaoverton** [comment]
Yes, we also need a basic PURL config file for GNO.

**Comment by nataled** [comment]
Anything else needed before this issue can be closed? I see GNO is not yet on the Foundry web site.

**Comment by jamesaoverton** [comment]
All configs are now merged and I updated the web site.
