### ISSUE TITLE
update and rearrange nav bar content

### ISSUE THREAD

**Issue by mellybelly** [OBOFoundry/OBOFoundry.github.io#883]
It would be terrific to have a Resources tab on the nav bar. There is a draft file here: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/resources.md
This could grow and be split out into Tutorials, Educational manuscripts, Blogs, Ontology Browsers, and Ontology-related Tools.

In addition, I think the nav bar could do with some rearrangement, suggested ordering:

Ontologies
Principles
Participate
Citation
Resources
FAQs
About
 (here move the OBO working groups to Participate tab?)

Time to retire Legacy?

also some of the important things, such as setting up your purls, are buried in the operations page: http://www.obofoundry.org/docs/OperationsCommittee.html
Maybe there should be a Requests or Configuration tab
Also Setting up Protege could move to the Resources page. 

I would be happy to try to make some rearrangements for review if people are game.

**Comment by cmungall** [comment]
please kill legacy, that was a placeholder for unmoved stuff 3 years ago!

**Comment by nataled** [comment]
I reviewed Legacy, and don't find a compelling reason to keep anything there. Many pages give 404 errors. The only suggestion I would not implement is moving the working groups to Participate. They are currently under About, which I think is appropriate since the pages describe what the groups do.

**Comment by nlharris** [comment]
See also #25 
At least some of the improvements that Melissa suggested have already been done. What else needs to be done?

**Comment by cmungall** [comment]
kill the legacy tab then this can be closed
