### ISSUE TITLE
vario metadata incomplete

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#886]
http://obofoundry.org/ontology/vario

no contact, no license

it does seem to be actively maintained:

```
$ curl -L -s http://variationontology.org/vario_download/vario.obo | grep ^date:
date: 08:11:2018 10:07
```

Some metadata can be found here, you can find the contact Mario on the pubs here:
http://www.variationontology.org/

**Comment by nlharris** [comment]
i couldn't find an email address for Mario Vihinen.

doesn't "no contact, no license" make vario not qualify for inclusion in obo foundry?

**Comment by rvita** [comment]
I've looked through all my notes & I have no further details to add for vario. In my mind, that means it should be obsoleted, unless anyone knows someone else to contact?

**Comment by cerivs** [comment]
Should the contact be Mauno Vihinen https://onlinelibrary.wiley.com/doi/abs/10.1002/humu.22954

**Comment by nlharris** [comment]
ah, i think you're right. we misread it as mario (or it got autocorrected).

but, really, is it our responsibility to try to find a way to contact them? aren't obo ontologies required to include a contact person?

**Comment by nlharris** [comment]
@rvita: Chris emailed you.

**Comment by rvita** [comment]
I have sent Mauno Vihinen the standard OBO services form email to ask for the missing information (on 12/1/20). I also asked if he has a github username.

**Comment by nlharris** [comment]
(Not a new ontology, but that label says "submitter action needed")

**Comment by rvita** [comment]
Mauno stated that he is the contact (added). Still waiting on license info.

**Comment by maunov** [comment]
Hi,

I send a fork about half a year ago indicating that VariO is alive, updated and available and informing about the license.
The latest version is from last year and a new one will be released soon.

Best wishes,

Mauno Vihinen

**Comment by pfabry** [comment]
Use issue #2090 for follow-up.
