### ISSUE TITLE
Prefix and PURL request: ICEO, Integrative and Conjugative Element Ontology

### ISSUE THREAD

**Issue by Lemon-Liu** [OBOFoundry/OBOFoundry.github.io#894]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Integrative and Conjugative Element Ontology

## Requested ID space
iceo

## Ontology location
https://github.com/ontoice/ICEO

## Contact person
Name: Meng LIU
Email address: liumeng94@sjtu.edu.cn
GitHub username: Lemon-Liu

## Issue tracker
https://github.com/ontoice/ICEO/issues

## Ontology license

- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
CC-BY 4.0
- [ ] Other: *please specify*

## Available ontology formats
OWL-RDF/XML

## What domain is the ontology intended to cover?
ICEO is an integrated biological ontology for the description of bacterial integrative and conjugative elements (ICEs).

## Related OBO Foundry ontologies
Ontology of Genes and Genomes (OGG), PRotein Ontology (PR), NCBI taxonomy ontology (NCBITaxon), Gene Ontology (GO).

## Intended use/related projects
ICEO will be used as the base of the next version of ICEberg database (http://db-mml.sjtu.edu.cn/ICEberg/) to standardize and integrate the rich ICE information for the advanced data sharing and organization. ICEO will also be combined and integrated to the ICEfinder (an ICE prediction tool with both web server and standalone versions available).

## Data source
ICEO uses information from the ICEberg database (http://db-mml.sjtu.edu.cn/ICEberg/).

## Additional comments or remarks
A full length paper about ICEO has been accepted for oral presentation in ICBO-2019. ICEO is accessible from BioPortal: https://bioportal.bioontology.org/ontologies/ICEO

**Comment by nataled** [comment]
Dear ICEO developers,

I took a quick look at your ontology. A few questions:

1) I'm confused as to the meaning of what you are calling roles (for example, "integrase role" ICEO:0000291). It would seem that these are actually functions, considering that they evolved to be what they are. Using the above example, you define an integrase as a protein that has an integrase role (which is, so far, undefined). But would it not be better to use integrase activity (GO:0008907) to define it?

2) There are numerous terms that already exist in other ontologies. Rolling circle replication (ICEO:0000136) is a GO term (GO:0070581), for example, and your relation "encoded by" already has a counterpart in RO. Considering that many other terms were already imported from other ontologies, these stand out. Do you plan on replacing your redundant terms with existing ones?

3) A few definitions are derived from the dictionary, with wording that has very little to do with the domain you are modeling (for example, ICEO:000132 "integration process"). I suspect you should use one of the integration process-related terms from GO.

**Comment by Lemon-Liu** [comment]
Dear Natale, 

Thanks for your kind review and valuable questions. We have checked and refined the ICEO according to your comments.

1, A specific integrative and Conjugative Element (ICE) may have many proteins that were found to be integrases based on prior knowledge. However, for a specific ICE to work out, there is only one protein that serves as ‘integrase role’, which means that the enzyme can mediate an exchange reaction between two DNA templates, resulting in the integration of a DNA segment from one template into another. Therefore, in our ICE system, integrase can serve as an integrase role. When the protein takes the integrase role, it can have the function of integrase activity. In our use case, we prefer the usage of the integrase role. We have added a definition to the ‘integrase role’ in the updated ICEO.   

2, Yes. We have replaced the redundant terms with existing ones as possible as we can. As suggested, we have imported the term GO:0070581. We could not find the ‘encoded by’ from RO. Instead, we found in IDO, and then we imported it from IDO. 

3, As suggested, we have used the definitions from peer-viewed articles relating to the ICE domain. We have replaced ‘integration process’ with its corresponding GO term.

**Comment by lschriml** [comment]
Discussed during 08/13/2019 Operations call, Decision: Agreement to approve the request. 
Bjoern will reply to the email.

**Comment by jamesaoverton** [comment]
This was approved, but it needs

1. registry entry https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1052
2. PURL entry

**Comment by Lemon-Liu** [comment]
> This was approved, but it needs
> 
> 1. registry entry #1052
> 2. PURL entry

Thanks for your kind reminder. I have created the iceo.yml for ICEO ontology [#570](https://github.com/OBOFoundry/purl.obolibrary.org/pull/570). 

Please let know if there are any other things we need to meet the requirement.  Thanks again.

**Comment by jamesaoverton** [comment]
This should all be complete now.
