### ISSUE TITLE
Prefix and PURL request: LABO, LABoratory Ontology

### ISSUE THREAD

**Issue by pfabry** [OBOFoundry/OBOFoundry.github.io#901]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title

clinical LABoratory Ontology

## Requested ID space

LABO

## Ontology location

https://github.com/OpenLHS/LABO

## Contact person
Name: Paul Fabry
Email address: paul.fabry@usherbrooke.ca
GitHub username: pfabry

## Issue tracker

https://github.com/OpenLHS/LABO/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats

OWL-RDF/XML

## What domain is the ontology intended to cover?

LABO is an ontology of informational entities formalizing clinical laboratory tests prescriptions and reporting documents.

## Related OBO Foundry ontologies

Prescription of DRugs Ontology (PDRO), 

## Intended use/related projects

LABO is a component of a core ontological model, along with the ontology of drug prescriptions PDRO, that aims to enable interoperability between various clinical data sources in the context of a Learning Health System.

## Data source

N/A

## Additional comments or remarks

A poster about LABO has been accepted for ICBO 2019, a paper has been submitted to JOWO 2019.

**Comment by bpeters42** [comment]
Thank you for the submission! Have you considered working with other ontologies covering the same domain, such as OBI? Minimally for the assays performed themselves? It would be great if this would not live in isolation

**Comment by cstoeckert** [comment]
Also it appears that the domain of this ontology is for clinical tests (in CLIA labs) as opposed to laboratory tests in general. OBO Foundry coverage is greater than just human health so please consider including "clinical" in your ontology title.

**Comment by adrien-barton** [comment]
@bpeters42 : Certainly! We actually import several terms from OBI and other OBO Foundry ontologies (IAO, OGMS…) For example, we use OBI classes such as 'planned process', 'value specification' and 'specimen', and OBI object properties such as 'has specified input', 'has specified output' and 'has specified value'. Note however that our focus in LABO is not on the tests themselves, but on the documents that are produced to prescribe such tests and report on them. But we articulate LABO entities with entities defined in OBO Foundry ontologies. 

@cstoeckert : Good point, we are changing "LABoratory Ontology" into "clinical LABoratory Ontology".

**Comment by zhengj2007** [comment]
Discussed on 2019-07-16 OBO operation committee meeting. @cstoeckert and @bpeters42  would like to discuss with @adrien-barton at ICBO 2019 meeting regarding the request and how to address @adrien-barton's needs.

**Comment by lschriml** [comment]
Discussed on Operations call, 08/13/2019: Chris S led the discussion, Decision: Agreed to move forward with the request.

**Comment by cstoeckert** [comment]
@adrien-barton Please create a YAML file for LABO that can be uploaded here: https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config and processed. 

As discussed at ICBO, you should submit new term requests to OBI for terms that are not restricted to clinical lab prescriptions which can then be shared more generally and imported back into LABO with the other OBI terms it uses. Thanks!

**Comment by mellybelly** [comment]
It would probably be good to document the relationship to LOINC, which has some potentially related atomic entities in their parts list and is the de facto clinical labs standard (and is an open standard).

**Comment by adrien-barton** [comment]
@lschriml and @cstoeckert : Thank you for the notification! @pfabry uploaded the YAML file, please let us know if there is any problem with it.
@mellybelly : Please find here the ODLS paper presenting LABO, which gives some information about how LABO is intended to articulate with other largely used relevant terminologies such as LOINC: https://github.com/OpenLHS/LABO/blob/master/Documentation/LABO_paper_ODLS2019.pdf . Do not hesitate to contact us in case of further questions.

**Comment by jamesaoverton** [comment]
I'm coordinating on the PURL configuration here: https://github.com/OBOFoundry/purl.obolibrary.org/pull/568

We also need a `labo.md` entry in this repository's https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology directory. @adrien-barton Can your team make a PR for that as well, please?

I'm reopening this ticket until we actually have OBO registry and PURL entries for LABO.
