### ISSUE TITLE
New Ontology Request: Ontology of Host-Pathogen Interactions (OHPI)

### ISSUE THREAD

**Issue by e4ong1031** [OBOFoundry/OBOFoundry.github.io#902]
## Ontology title
Ontology of Host-Pathogen Interactions

## Requested ID space
OHPI

## Ontology location
https://github.com/OHPI/ohpi/

## Contact person
Name: Edison Ong
Email address: edong@umich.edu
GitHub username: e4ong1031

## Issue tracker
https://github.com/OHPI/ohpi/issues

## Ontology license

- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
- OWL
- OBO
- JSON

## What domain is the ontology intended to cover?
- host-pathogen interactions

## Related OBO Foundry ontologies
- Vaccine Ontology (VO)
- Disease Ontology (DOID)
- Ontology of Genes and Genome
- Gene Ontology (GO)
- Protein Ontology (PR)
- Cell Ontology (CL)
- Cell Line Ontology (CLO)
- Interaction Network Ontology (INO)

## Intended use/related projects
1. Vaccine protective immune response mechanism study.
2. Identify host-pathogen interaction information through literature mining.
3. Facilitate rational vaccine design.

## Data source
1. Victors database (http://www.phidias.us/victors/)
Sayers S, Li L, Ong E, Deng S, Fu G, Lin Y, Yang B, Zhang S, Fa Z, Zhao B, Xiang Z, Li Y, Zhao Z, Olszewski MA, Chen L, He Y. Victors: a web-based knowledge base of virulence factors in human and animal pathogens. Nucleic Acid Research. 2019 Jan 8;47(D1):D693-D700. doi: 10.1093/nar/gky999. PMID: 30365026. PMCID: PMC6324020.

2. Protegen database (http://www.violinet.org/protegen/)
Yang B, Sayers S, Xiang Z, He Y. Protegen: a web-based protective antigen database and analysis system. Nucleic Acids Res. 2011 Jan;39(Database issue):D1073-8. doi: 10.1093/nar/gkq944. PMID: 20959289; PMCID: PMC3013795.

## Additional comments or remarks
OHPI has been submitted to the OBO-discuss since 02/05/2019 (https://groups.google.com/forum/?hl=en#!topic/obo-discuss/nTXwO5Dkb9w). The last comment received from others was 02/07/2019. We also made a substantial expansion of the OHPI host-pathogen interaction terms in the past few months.

We have re-designed the release pipeline which incorporated the Ontology Development Kit (ODK), Ontofox and Ontodog to automate the addition of over 4,000 virulence factors from 82 pathogens and over 2,000 host-pathogen interactions with the corresponding hosts, host cells or host cell line cells from the Victors database (http://www.phidias.us/victors/). We also identified 52 virulence factor genes, which encoded protective antigen proteins tested in 17 research vaccines (both the protective antigen proteins and vaccines are imported from the Vaccine Ontology). Detail of these protective antigen proteins is available in the Protegen database (http://www.violinet.org/protegen/). We are planning to utilize the virulence factor, protective antigen, vaccine, and host-pathogen interaction information in OHPI and perform literature mining in the future. The OHPI was submitted and has been accepted to this year ICBO VDOS workshop.

**Comment by matentzn** [comment]
Hey! Maybe it would be good to delineate your proposed ontology clearly from http://obofoundry.org/ontology/phipo.html and explain how they might be integrated? I am saying this from a bit of a naive standpoint (i.e. maybe these ontologies dont overlap despite their titles), but just to dispel  the confusion, maybe it would be good to clarify the PHIPO-OHPI relationship.

**Comment by e4ong1031** [comment]
Hi @matentzn , thanks for your comment.

The similar topic has been asked and discussed in the OBO-discuss. Below is the answer from the thread.

> Yes, PHIPO and OHPI do have overlaps since we both focus on the domain of host-pathogen interactions or called pathogen-host interactions. However, PHIPO and OHPI do have different emphases. ... OHPI is focused on representing specific host-pathogen interactions, such as ‘human-Brucella interaction in macrophage’. PHIPO is, from my understanding, focused on representing general phenotypes related to pathogen-host interactions. Therefore, I think PHIPO and OHPI are more complementary to each other rather than overlapping. The phenotypes of pathogen-host interactions defined in the PHIPO can be used in our OHPI for better annotating specific pathogen-host interactions. Our group does envision that we could collaborate closely on the development of both ontologies together. 

In addition to the above comment, the current OHPI also incorporated protective antigens from existing vaccines targeting varies pathogens. Such information can be utilized for future literature mining (identify host vaccine immune factor through HPI) and vaccine development in my opinion.

**Comment by matentzn** [comment]
Thanks for that! Sorry, missed the discussion on obo-discuss for some reason, now up to speed. Thanks.

**Comment by zhengj2007** [comment]
Discussed on 2019-07-16 OBO operation committee call. We accepted the request. 

@e4ong1031 Please go ahead to create yml and md files and make the pull requests.

**Comment by e4ong1031** [comment]
@zhengj2007 Thank you very much! I will prepare the files.
