### ISSUE TITLE
Add usage tags for all ontologies used by Monarch

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#903]
See the cl, envo, go entries for example of usage tags. We want to make these more complete. This ticket is about adding this info for all ontologies used by monarch. @nicolevasilevsky will make PRs (can't assign the ticket to you Nicole)

**Comment by nicolevasilevsky** [comment]
based on https://monarchinitiative.org/about/sources. I asked Kent for an updated list, but will start here.
- [ ] APO
- [ ] ECO
- [ ] EFO
- [ ] FBbt
- [ ] FBcv
- [ ] FBdv
- [ ] HPO
- [ ] MA
- [ ] MI
- [ ] MP
- [ ] MP
- [ ] OMIA
- [ ] OMIM
- [ ] PATO
- [ ] RGD
- [ ] RO
- [ ] SO
- [ ] Uberon
- [ ] WBbt
- [ ] WBls
- [ ] WBPhenotype
- [ ] ZFA
- [ ] ZFS
- [ ] ZP

**Comment by nicolevasilevsky** [comment]
@cmungall for these other ontologies, I'm not really sure how they are used by Monarch.

Would you like me to add usage tags to all of the remaining ontologies?

**Comment by cmungall** [comment]
I would prioritize ontologies that are used in some non-trivial ways, and I
would prioritize capturing the curation usage before the aggregation usage

**Comment by nlharris** [comment]
@nicolevasilevsky is this still in progress? Can we unassign @cmungall from this issue?

**Comment by nicolevasilevsky** [comment]
Sure. I think I'm blocked on this issue, but maybe I can ask Kent for help, maybe he can tell me how these other ontologies are used in Monarch.

**Comment by matentzn** [comment]
i think the most important is to list all those we annotate against (HPO, Mondo, ECTO, MAXO); 

then uPheno for phenotype integration and cross-species inference.

The best way to get a sense of what we use for aggregation is to go to the Monarch website, browse for Marfan Syndrome and just check what kind of categories are shown on the left. These will include Mondo, GENO, SEPIO, uPheno, GO and some more. I think there was a really cool Julie graphic that illustrates those, maybe in one of the papers.

Other uses in our wider field (not sure we wanna classify those as Monarch though):

GO, UBERON, CHEBI, CL, NBO for cross species integration and classification of phenotypes in Upheno.

 Foodon for the integration of dietary aspects of medical actions in MAXO (@LCCarmody maybe has some more ontologies she could name here). ENVO, CHeBI and others (@diatomsRcool ?)  for the integration and automatic classification of Environmental exposures.

**Comment by LCCarmody** [comment]
FoodON, UBERON, NBO, CHEBI are the big ones that I use.  I( will need to use HPO and maybe ENVO, but that hasn't been implemented. )
I will import from OBI but waiting on terms, then will import several.  

The ongoing Food/diet discussions are trying to resolve where diet will go, and there is a possibility it will go in ONS (https://github.com/enpadasi/Ontology-for-Nutritional-Studies).

**Comment by nlharris** [comment]
Is this still ongoing?

**Comment by matentzn** [comment]
I dont know whether keeping this ticket open really helps. Yes we should document the usage of all ontologies by Monarch. No we haven't documented all the usage, but we have documented some. I think Monarch would be doing a much greater service to doing this work as part of a wider OBO-Dashboard cleanup. In any case, this is not an OBOFOundry ticket... If anything, its a Monarch ticket.

**Comment by nlharris** [comment]
not sure if there's a way to transfer a ticket to a different org
