### ISSUE TITLE
ero has no tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#909]
We are trying to ensure that every OBO ontology that is not obsolete has a tracker. If you have one, send me its information and I'll add it.

**Comment by nlharris** [comment]
Do these ontology-specific requests need to be directed to the ontology owner?

**Comment by nlharris** [comment]
It doesn't seem very useful to post these issues saying "you" and not contact the ontology owner. Maybe the owner was also contacted by email, and this ticket is just for tracking? @rvita, can you clarify?

**Comment by rvita** [comment]
Many of these ontologies had no owners at the start of the metadata project & many of the known owners did not have github accounts. Juliane Schneider states that they do not have a tracker and that she needs someone to help them set one up. I am not sure if she has a github user account, the only one I found for her name is uncertain. I am not qualified to help her, so are there any volunteers to help her establish a term tracker?

**Comment by nlharris** [comment]
I think it's probably out of scope for OBO to help ontologies set up trackers. We have very limited person-hours. We could point her to documentation about using issue trackers on GitHub, e.g., https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues

**Comment by matentzn** [comment]
@rvita ERO is now the only ontology without a tracker; we have decided in the last meeting to make public trackers mandatory.. Is there anyone that could help the ERO people to set one up?

**Comment by nicolevasilevsky** [comment]
I know Juliane Schneider and used to work on ERO many years ago. ERO originally used JIRA, and then it morphed into the VIVO-ISF: https://github.com/openrif/vivo-isf-ontology

I am not even sure if ERO is actively maintained, I believe it is just maintained as part of VIVO-ISF.

Shall I reach out to Juliane and try to find out the status?

**Comment by matentzn** [comment]
That would be great :)

**Comment by nicolevasilevsky** [comment]
_Update_: Chatted with Juliane on 01/12/21 - she's no longer with Harvard Catalyst. I emailed Marc Ciriello, who is likely the proper contact person.

**Comment by nicolevasilevsky** [comment]
_Update_: I updated the contact person to Marc, and Marc replied to me and is going to look into creating a GitHub tracker or potentially archiving this ontology.

**Comment by nlharris** [comment]
@nicolevasilevsky any update on this?

**Comment by matentzn** [comment]
Yeah, would be great to solve this!

**Comment by nicolevasilevsky** [comment]
I emailed Marc again today 02/23/21
