### ISSUE TITLE
Travis CI documentation

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#91]
To add in the readme-sitedev file.

**Comment by cmungall** [comment]
In the main README now, should be moved

**Comment by mcourtot** [comment]
I guess we need different levels of documentation ;) I took me a little bit of digging to understand the .travis.yaml file and the after_success parameter, understanding that it call extract-metadata.py which then parses the corresponding ontology.md file. 
Still trying to figure out why the comment on the validate_markdown function says 
    """
    ensure the yaml encoded inside a YAML file is syntactically valid
    """ 
as I think in this case we're just passing the md file?

**Comment by cmungall** [comment]
Shall we close this or add additional documentation?

Note we have

http://obofoundry.github.io/faq/how-do-i-edit-metadata.html

Which is a start for an end-user guide

For sitedevs. travis and .travis.yml files are fairly standard now, I think what we have should be sufficient

**Comment by nlharris** [comment]
Can this be closed?

**Comment by jamesaoverton** [comment]
I think this is taken care of. Please open a new issue if you run into problems.
