### ISSUE TITLE
apo is missing a tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#911]
@srengel We are trying to   ensure that every OBO ontology that is not obsolete has a tracker. If you   have one, send me its information and I'll add it.
--

**Comment by srengel** [comment]
Hi @rvita we don't have a tracker for the APO.

**Comment by matentzn** [comment]
Are you sure @srengel 
I saw this one :) https://github.com/obophenotype/ascomycete-phenotype-ontology/issues

**Comment by srengel** [comment]
Hi @matentzn that indeed looks like us!  glad there are no languishing issues in there.  

@rvita please add the info from https://github.com/obophenotype/ascomycete-phenotype-ontology/issues to wherever that needs to go.  

thanks @matentzn

**Comment by rvita** [comment]
OK, I added it. I'll close after it is merged.

**Comment by cmungall** [comment]
@rvita - tip, you can do this in your commit message

fixes #939

This will close the ticket automatically after a merge
