### ISSUE TITLE
cheminf is missing a tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#914]
@egonw We are trying to ensure that every OBO ontology that is not obsolete has a tracker. If you   have one, send me its information and I'll add it.
--

**Comment by egonw** [comment]
Like an issue tracker? https://github.com/semanticchemistry/semanticchemistry/issues

**Comment by rvita** [comment]
Thanks, I added it. When the pull request is done, I'll close this ticket.

**Comment by egonw** [comment]
Ah, thanks. Added a PR myself: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/917

I saw for BFO also a link to BioPortal. CHEMINF can be found on BioPoral too. Shall I make a PR to add that too?

**Comment by rvita** [comment]
BioPortal should be taking their info from the OBO file, so I think it is not needed.
