### ISSUE TITLE
ddpheno is missing issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#918]
@pfey03 We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by pfey03** [comment]
@rvita Hi, we do not currently have an issue tracker as only myself handled it and the other curator told me if he needs a new term. But if required, I can add one and would like to do under the dictybase root. Should I and then send the link here? Thanks

**Comment by matentzn** [comment]
Hey @pfey03 

Remember I made this for you:
https://github.com/obophenotype/dicty-phenotype-ontology/issues

Wouldnt this be an option here?

**Comment by pfey03** [comment]
@matentzn Thanks for the reminder.

Ok, then we are all set @rvita

**Comment by pfey03** [comment]
@matentzn another question: How is DDPHENO updated in this repository https://github.com/obophenotype/dicty-phenotype-ontology/
Do I need to update when I update the ontology? Or do you grab it? I can let you know in the latter case.

**Comment by matentzn** [comment]
moved discussion [here](https://github.com/obophenotype/dicty-phenotype-ontology/issues/1)

**Comment by rvita** [comment]
I will add the tracker to the OBO yaml file now:
https://github.com/obophenotype/dicty-phenotype-ontology/issues
