### ISSUE TITLE
hao is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#925]
We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by balhoff** [comment]
@mjy is the maintainer.

**Comment by rvita** [comment]
Thanks, per @mjy I will add the official issue tracker and close once merged.

**Comment by rvita** [comment]
was added
