### ISSUE TITLE
idomal is missing a term tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#927]
We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by cmungall** [comment]
It has no term tracker because it's inactive. There have been no files to download for years. Correspondence from @cstoeckert   

> Marking them as inactive makes sense since they are not being actively developed.

See also #546 where we are trying to track down all missing ontologies
