### ISSUE TITLE
mfomd is missing a term tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#928]
@jannahastings We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by jannahastings** [comment]
Hi Randi, 

the tracker that I am using for MFOMD is the same as for the broader MF project:

https://github.com/jannahastings/mental-functioning-ontology/issues

Is that OK?

**Comment by rvita** [comment]
yes, I'll add it now. Thanks

**Comment by rvita** [comment]
added
