### ISSUE TITLE
mi is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#929]
@pporrasebi We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by pporrasebi** [comment]
Here you have it: https://github.com/HUPO-PSI/psi-mi-CV/issues.

Please let me know if you need anything else.

**Comment by rvita** [comment]
Thanks, I'll add it.

**Comment by beckyjackson** [comment]
Resolved by #937
