### ISSUE TITLE
Extra features? (jekyll / coveralls)

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#93]
Should we use a gemfile, and bundler? It seems this would allow us to keep in sync with the github version of jekyll as well as add extra features such as coveralls. Still digging, creating ticket for discussion.

**Comment by cmungall** [comment]
+1

**Comment by cmungall** [comment]
We should also make it clear in the sitedev docs: from the travis POV this is a python project, no need to run ruby / gem install. From the perspective of a hypothetical web dev we somehow manage to persuade to work on this, it's a jekyll project, they'd need to run ruby to test the site locally, but wouldn't need any python. For all-round people like us it's a bit of both.

**Comment by nlharris** [comment]
what's the status of this?

**Comment by nlharris** [comment]
can we close this?

**Comment by nlharris** [comment]
closing; please reopen if needed
