### ISSUE TITLE
mirnao is missing a term tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#932]
We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by nlharris** [comment]
Who is "you"?

**Comment by rvita** [comment]
I cannot find a github user for Pantelis Topalis (topalis@imbb.forth.gr), who seems to be the only contact. I just resent the email from Jul 31, 2018 requesting the missing metadata to him again.

**Comment by matentzn** [comment]
Mirnao has been obsoleted.
