### ISSUE TITLE
Inconsistent documentation on Version IRIs

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#942]
The [OBO ID Policy](http://www.obofoundry.org/id-policy.html) pages state that:

```
Versions are named by a date in the following format: YYYY-MM-DD. For a given version of an ontology, the ontology should be accessible at the following URL, where idspace; is replaced by the IDSPACE in lower case:

OWL: http://purl.obolibrary.org/obo/idspace/YYYY-MM-DD/idspace.owl
OBO: http://purl.obolibrary.org/obo/idspace/YYYY-MM-DD/idspace.obo
For example, for the version of OBI released 2009-11-06, the OWL document is accessible at http://purl.obolibrary.org/obo/obi/2009-11-06/obi.owl.
```

The [Citation](http://www.obofoundry.org/docs/Citation.html) pages state:

```
To facilitate reproducibility, be specific about the version of the ontology that you are referring to by using an ontology version IRI that contains the release date:

http://purl.obolibrary.org/obo/uberon/releases/2016-01-26/uberon.owl

The ontology version IRI is indicated by the owl:versionIRI property.
```

*Note the /releases/ part of the IRI.*

I believe the latter to be correct, and this is what the ODK and most of the purl configs have been implementing for a while, so probably the above id policy docs needs changing..

@cmungall @jamesaoverton

**Comment by jamesaoverton** [comment]
The ID policy for version IRIs goes back as far as I can remember, and many projects follow it. In practise, it usually requires making a new PURL entry for each release. E.g. https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obi.yml#L189

When projects started to migrate to GitHub, it was convenient to redirect `/releases/` to a GitHub URL prefix, which avoids the need for a new PURL entry for each release. E.g. https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ro.yml#L27

I prefer the policy as written, and explicitly making a PURL for each release. But that ship has sailed, so we should probably revise the policy and documentation.

**Comment by matentzn** [comment]
So this is how things currently run in the ODK.

**dpo.owl:**
```
<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/dpo.owl">
  <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/dpo/releases/2019-07-25"/>
  <oboInOwl:date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">25:07:2019 09:43</oboInOwl:date>
  <oboInOwl:default-namespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">FlyBase_miscellaneous_CV</oboInOwl:default-namespace>
</owl:Ontology>
```
translates to (`robot convert -i dpo-base.owl --check false -f obo -o dpo-base.obo`):

**dpo.obo:**
```
format-version: 1.2
data-version: releases/2019-07-25
date: 25:07:2019 09:43
default-namespace: FlyBase_miscellaneous_CV
ontology: dpo
```

**dpo-base.owl:**
```
<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/dpo/dpo-base.owl">
  <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/dpo/releases/2019-07-25/dpo-base.owl"/>
  <oboInOwl:date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">25:07:2019 09:44</oboInOwl:date>
  <oboInOwl:default-namespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">FlyBase_miscellaneous_CV</oboInOwl:default-namespace>
</owl:Ontology>
```

translates to:

**dpo-base.obo:**
```
format-version: 1.2
data-version: dpo/releases/2019-07-25/dpo-base.owl
date: 25:07:2019 09:44
default-namespace: FlyBase_miscellaneous_CV
ontology: dpo/dpo-base
```
Are we all good with that? @cmungall @jamesaoverton @dosumis @balhoff 

Note that:
1. The base namespace of dpo-base.obo will be misinterpreted in any OWL API based tool to be: http://purl.obolibrary.org/obo/dpo/dpo-base, which will affect what OWL API spits out looking for IRIs of subsets and similar (http://purl.obolibrary.org/obo/dpo#lethal_subset in dpo-edit.owl becomes http://purl.obolibrary.org/obo/dpo/dpo-base#lethal_subset in dpo-base.obo).
1. The version IRI of dpo-base.obo will be falsely interpreted to be: http://purl.obolibrary.org/obo/dpo/dpo-simple/dpo/releases/2019-07-25/dpo-simple.owl/dpo/dpo-simple.owl  
1. The version IRI of dpo.obo is 'correct', but points to its owl counterpart

**Comment by dosumis** [comment]
This ticket now mixes a number of issues:

1. OBO standard version IRIs - Many projects on GitHub no longer follow because there is no clear way to support this using GitHub tag releases without manually adding new version IRIs for each release. 
2. OBO ontology & data-version + their relationship to IRI, version IRI and base_iri for a few APs that ar e local to the ontolgy.  This relationship comes from the OBO to OWL conversion.

Issue 1: I'd prefer that we stick to the foundry standard for version IRIs, but am willing to switch to a scheme that adds `/releases/` to the path given that (a) This scheme is already widely used and (b) We need efficient ways to release ontologies that don't rely on editors remembering to carry out manual steps.

Issue2: As I understand it, our agreed aim for **released** OBO files is that, when converted to OWL, IRIs and version IRIs of all files should resolve to their OWL equivalents.  This is essential for re-use and provenance tracking.  I believe this can be achieved by writing OBO files directly from robot (I'm sure we've solved this multiple times!), but that IRI, + the OBO ontology & data-version tags get scrambled by OBO<->OWL roundtripping.

The issue with  base_iris for local APs (subsets & synonym types) should be clearly documented as a known bug (Where?).  Ideally we should have a plan for how to fix this. 

The issue with roundtripping and IRIs also needs to be properly documented - with the doc including known workarounds.

**Comment by matentzn** [comment]
I agree with @dosumis thanks for distinguishing these two issues. I just thought it makes sense to document how what we call "version iri" in OWL looks like in OBO, hence the additional comment. The obo output you see above is what our OBO parsers are doing when you run them on the correct OWL. 

The problem I see is this:
1. The current version iri scheme concatenates the `data-version:` with the `ontology:` fields. 
1. The ontology IRI has this http://purl.obolibrary.org/obo/**_dpo_**/dpo-base.owl bit in there, which necessarily turns the `ontology:` id into dpo/dpo-base.
1. there is no such 'bit' in the version IRI

Ergo, I think these two schemes are simply incompatible. Maybe @cmungall sees a way to solve this somewhere! So the only guarantee we have now is this: If we KNOW (as a human) how to construct the version IRI, we can retrieve the file (the updated OBO version iri stream as specified in the OWL works; and if you simply replace owl with obo, it works as well). Let me know if you see a solution!

**Comment by dosumis** [comment]
> The obo output you see above is what our OBO parsers are doing when you run them on the correct OWL 

I understand that. I thought it was possible to construct an OBO file that, when converted to OWL => the a version IRI that is correct for the OWL equivalent of the OBO file - for all the various flavours or release file we produce. But having done some experiments, I now realise that this is only true for the main release files:

```yaml
data_version: releases/25-07-2019
ontology: fbbt
```

=> 
http://purl.obolibrary.org/obo/fbbt.owl
http://purl.obolibrary.org/obo/fbbt/releases/25-07-2019/fbbt.owl

There's no combination of data-version and ontology tag values that produces valid version IRIs for derivative files - so this must have been broken in all previous releases of OBO derivative files too.

Apologies for not realising this earlier (I suspect I knew this at some point in the past but forgot).  I think this (again) points to the need for a good standard reference for known OBO to OWL conversion issues.  Without this, we will continue to  waste time going round in circles. 

So - no point in worrying about OBO file IRIs - apart from the main release file.  OWL versions should all be correct though - specified using robot to over-ride the results of conversion.  

Next question: Does that mean we can specify base IRIs correctly and consistently for built-in APs in both OBO and OWL versions?  It would be good to achieve this, but if you can't find a way to do it with a few simple experiments, then better to just document this as a known issue than waste more time trying to get it right.

**Comment by cmungall** [comment]
My PR addresses the `/releases/` part. Maybe make a new issue for anything obo-format specific, tho not sure there is an issue here

**Comment by matentzn** [comment]
Moved the subset IRI discussion [here](https://github.com/INCATools/ontology-development-kit/issues/259)

This issue is closed with adding improved documentation. Lets move the question on where to document OBO-OWL format related issues [here](https://github.com/INCATools/ontology-development-kit/issues/214), which is not ideal, but a better place than here.
