### ISSUE TITLE
Principle #4 "Versioning"

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/OBOFoundry.github.io#955]
Current wording (public)

**NOTE**

The original wording of this principle (given below) and content of this page is scheduled to be reviewed. Improved wording will be posted as it becomes available.

**Summary**

The ontology provider has documented procedures for versioning the ontology, and different versions of ontology are marked, stored, and officially released.

**Purpose**

OBO projects share their ontologies using files in OWL or OBO format (see OBO Principle 2). Ontologies are expected to change over time as they are developed and refined (see OBO Principle 16 on maintenance). This will lead to a series of different files. Consumers of ontologies must be able to specify exactly which ontology files they used to encode their data or build their applications, and be able to retrieve unaltered copies of those files in perpetuity. Note that this applies only to those versions which have been officially released.

**Recommendation**

Each official release MUST have a unique version identifier. Version identifiers for the ontology artifacts themselves may be of the form “YYYY-MM-DD” (that is, a date), or use a numbering system (such as semantic versioning, i.e, of the form "NN.n"), but in any case each MUST associate with a distinct official release. The date versioning system is preferred, as it meshes with the requirement that version IRIs be specified using dated PURLs (see below).

All OBO projects MUST also have PURLs that resolve to specific official releases of their ontology, in perpetuity. If the files are moved, the PURL MUST be updated to resolve to the new location. Consumers can then use the version IRI to uniquely identify which official release of the ontology they used, and to retrieve unaltered copies of the file(s).

Note that the content of official release files MUST NOT be changed. For example, if a bug is found in some official released file for some ontology, the bug MUST NOT be fixed by changing the file(s) for that official release. Instead the bug fixes should be included in a new official release, with new files, and consumers can switch to the new release.

**Implementation**

See examples (below) for guidelines on how to specify the version within the ontology itself. If terms are imported from an external ontology, the “IAO:imported from” annotation (see Principle 1) may specify a dated version of the ontology from which they are imported.

Regardless of the versioning system used for the ontology artifact, the version IRI SHOULD use an ISO-8601 dated PURL. In cases where there are multiple releases on the same day, the PURL points to the newest, and the previous release stays in the same folder or a subfolder, named in such a way as to distinguish the releases. Specifications for version IRIs are fully described in the OBO Foundry ID policy document. In short:

For a given version of an ontology, the ontology should be accessible at the following URL, where 'idspace' is replaced by the IDSPACE in lower case:

OWL: http://purl.obolibrary.org/obo/idspace/YYYY-MM-DD/idspace.owl
OBO: http://purl.obolibrary.org/obo/idspace/YYYY-MM-DD/idspace.obo

For example, for the version of OBI released 2009-11-06, the OWL document is accessible at http://purl.obolibrary.org/obo/obi/2009-11-06/obi.owl.

An accepted alternative to the above scheme is to include /releases/ in the PURL, as follows:

OWL: http://purl.obolibrary.org/obo/idspace/releases/YYYY-MM-DD/idspace.owl
OBO: http://purl.obolibrary.org/obo/idspace/releases/YYYY-MM-DD/idspace.obo

**Examples**

For an OBO format ontology use the metadata tag: data-version: 2015-03-31 data-version: 44.0

For an OWL format ontology, owl:versionInfo identifies the version and versionIRI identifies the resource: <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2014-12-03</owl:versionInfo> <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/obi/2014-12-03/obi.owl"/>

**Counter-Examples**

Category:Principles Category:Accepted

**Comment by nataled** [comment]
Unresolved discussion:

@zhengj2007 : I'd like to know recommendation of recording the versions of external terms used in an ontology.

@nataled : Check IAO for annotation addressing this, such as "imported on date X" and "import version is Y"

@nataled : We don't make it a requirement that versions for individual terms be indicated, as (supposedly) a given term shouldn't change its meaning over time (we intend propose that as a Principle). We instead note that it is possible to indicate the version, and provide instruction on doing so.

@cmungall : I believe Jie's comment was about the date of the MIREOT. This is potentially useful for different reasons that date of creation of a class in base. However, I think the right place to raise this is in the ROBOT tracker where the functionality can be added (there is no point making a principle that no one can implement without writing a competing code stack)

@zhengj2007 : Yes. Chris is right. What I mean is about the version of external ontologies where the terms imported from using MIREOT. As Chris said, it should be supported by some tools. I told with Oliver before. For example, add version information when use OntoFox. For example, OBI imports GO, UBeron, NCBITaon, etc terms. When run ontoFox to retrieve the terms from external ontologies, the output can contain something like, <rdfs:comment>import GO terms from http://obolibery.org/obo/go/2018-9-21/go.owl</rdfs:comments>. I think it is useful because sometimes I found inconsistent information due to ontology import the term from same external ontology but different versions.

@ramonawalls : A good way to handle this would be to have the IAO property for imported from point to the versioned IRI of the source ontology, rather than its general PURL. This is also probably something for Robot.

@zhengj2007 : Agree with Ramona. Question: Should we include it in the principle?

@cmungall : Not yet

**Comment by cmungall** [comment]
To reiterate, we should not complicate this page further with talk of versioning of MIREOTs and imported ontologies. This discussion should move to the ROBOT tracker.

I agree with @bpeters comments on the list, the content is not easily understood and it sounds like we are talking to ourselves.

E.g.

_Summary: The ontology provider has documented procedures for versioning the ontology, and different versions of ontology are marked, stored, and officially released._

This is opaque and indirect. No need to say "documented procedures for X", just say "X".

Keep it simple, how about this for the summary:

 * Each version of the ontology should be available from a stable Permanent URL (PURL)

Same for Purpose section, etc

**Comment by zhengj2007** [comment]
@nataled I think the version information of external ontologies used in an ontology can be either associated with each imported (reused) terms or associated with the ontology only, such as this ontology used the external ontologies, BFO version 2019-02-21, IAO version 2019-06-07, etc. Discussion of implementation should move to technique group, or ROBOT tool. Since not all OBO ontology developers use ROBOT tool, I think it should be document somewhere on the OBO Foundry website.
When I added my comments on this principle, I concern a couple of questions:
1. Whether versioning principle includes version of external ontology used in an ontology?
2. If not, whether needs it be added in the principle? 
I think it is an important piece of information. I'd like OBO Foundry has some rules/recommendations/suggestions on it. 

@cmungall I agree the discussion of versioning the external ontologies used in an ontology implementation can move to ROBOT. But I still think it should be documented how to indicate the versions of external ontologies used on the OBO Foundry site somewhere. I don't mind whether it is be part of the principle or not.

**Comment by cmungall** [comment]
> @cmungall <https://github.com/cmungall> I agree the discussion of
> versioning the external ontologies used in an ontology implementation can
> move to ROBOT. But I still think it should be documented how to indicate
> the versions of external ontologies used on the OBO Foundry site somewhere.
> I don't mind whether it is be part of the principle or not.
>

Seems reasonable, but we have to be careful about duplication of
documentation and drift. Given limited resources, when we have a
non-binding good-practice recommendation, how about as a general
documentation pattern we insert text into the principles that says "we
recommend doing X. An example is given on documentation for the ROBOT
command C, <see link>. You can either use ROBOT to follow this guideline or
use whatever tools you like adapted to follow the structure produced by
ROBOT"

**Comment by nataled** [comment]
@zhengj2007 The principle as originally formulated applies specifically to the ontology itself, not the imports. However, I do think your suggestion could be rolled into the 'open' principle, which covers issues of term and ontology reuse. To do so, we'd need to discuss it within the Operations meeting first (because it would be a modification of an existing fully-accepted principle). Personally, I think the version of import and the issue of re-use should be a breakout from Principle 1.

**Comment by wdduncan** [comment]
Closing issues as discussions pertinent to version 4 are adequate. Discussions concerning imports need be handled on the ROBOT tracker.
