### ISSUE TITLE
mod is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#974]
@rleduc42 We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by rleduc42** [comment]
Hello Rvita,

Is this what you need?

https://github.com/topdownproteomics/ProteoformNomenclatureStandard/issues

Regards,

Rich
-----------------------------------
Richard LeDuc, PhD
Bioinformaticist

**Comment by beckyjackson** [comment]
Is this resolved by #995? It looks like the link is different, but `mod.md` now has a tracker.
