### ISSUE TITLE
mop is missing issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#975]
@batchelorc We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by batchelorc** [comment]
Hello,

For MOP we'll use the RXNO one if that's OK: https://github.com/rsc-ontologies/rxno/issues

Colin.

**Comment by beckyjackson** [comment]
Resolved by #1000
