### ISSUE TITLE
ms is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#976]
@germa We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by germa** [comment]
Dear Randy,

most of the communication concerning ps-ms.obo issues is via the mailing list
psidev-ms-vocab@lists.sourceforge.net,
but we also use the GitHub issue tracker https://github.com/HUPO-PSI/psi-ms-CV/issues

**Comment by cmungall** [comment]
Randy note all mail lists should be there as URLs, not email addresses. You
can see now this is broken http://obofoundry.org/ontology/ms

**Comment by nlharris** [comment]
Is this fixed?

**Comment by rvita** [comment]
They have an email contact, but are still missing a term tracker. It looks to be this one to me:
https://github.com/HUPO-PSI/psi-ms-CV/issues @germa?

**Comment by matentzn** [comment]
Fixed by #1395
