### ISSUE TITLE
oae is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#977]
@yongqunh We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by yongqunh** [comment]
OAE issue tracker:
https://github.com/OAE-ontology/OAE/issues

Thanks!
Oliver He

**Comment by beckyjackson** [comment]
Resolved by #996
