### ISSUE TITLE
omit is missing a term tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#980]
@Huang-OMIT We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by Huang-OMIT** [comment]
@rvita Hi Rvita,

Here is the OMIT issue tracker: https://github.com/OmniSearch/omit/issues  

Thank you!

Jingshan

**Comment by beckyjackson** [comment]
Resolved by #994
