### ISSUE TITLE
ovae is missing an activity tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#983]
@yongqunh We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

**Comment by yongqunh** [comment]
OVAE issue tracker:
https://github.com/OVAE-Ontology/ovae/issues

Thanks!
Oliver He

**Comment by beckyjackson** [comment]
Resolved by #997
