### ISSUE TITLE
rxno is missing an issue tracker

### ISSUE THREAD

**Issue by rvita** [OBOFoundry/OBOFoundry.github.io#985]
@batchelorc We are trying to ensure that every OBO ontology that is not obsolete has an issue tracker. If you have one, send me its information and I'll add it.

--

**Comment by batchelorc** [comment]
Hello,

https://github.com/rsc-ontologies/rxno/issues

Many thanks!
Colin.

**Comment by beckyjackson** [comment]
Resolved by #999
