### ISSUE TITLE
images missing on website

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#986]
On this page, the images are missing:
http://www.obofoundry.org/docs/SettingUpProtege.html

**Comment by matentzn** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/953

Another proof we work similarly :P

**Comment by nicolevasilevsky** [comment]
Ha! I will close this, since it is a duplicate of #953
